CREATE TABLE [discovery].[ProcurementSnapshot]
(
[Division] [nvarchar] (255) NULL,
[CompanyNumber] [nvarchar] (255) NULL,
[Facility] [nvarchar] (255) NULL,
[Warehouse] [nvarchar] (255) NULL,
[PurchaseOrder] [nvarchar] (255) NULL,
[POType] [nvarchar] (255) NULL,
[LowestStatus] [nvarchar] (255) NULL,
[HighestStatus] [nvarchar] (255) NULL,
[Supplier] [nvarchar] (255) NULL,
[Currency] [nvarchar] (255) NULL,
[PurchaseLine] [nvarchar] (255) NULL,
[Item] [nvarchar] (255) NULL,
[ItemDescription] [nvarchar] (255) NULL,
[ConversionRate] [decimal] (15, 9) NULL,
[alternative] [nvarchar] (255) NULL,
[OrderedQty] [nvarchar] (255) NULL,
[OrderedQtyConverted] [nvarchar] (255) NULL,
[ReceivedQuantity] [nvarchar] (255) NULL,
[ReceivedQuantityConverted] [nvarchar] (255) NULL,
[ApprovedQty] [nvarchar] (255) NULL,
[ApprovedQtyConverted] [nvarchar] (255) NULL,
[RejectedQty] [nvarchar] (255) NULL,
[RejectedQtyConverted] [nvarchar] (255) NULL,
[StoredQty] [nvarchar] (255) NULL,
[StoredQtyConverted] [nvarchar] (255) NULL,
[PurchaseOrderUnit] [nvarchar] (255) NULL,
[PurchasePriceUnit] [nvarchar] (255) NULL,
[LineAmountOrderCurrency] [nvarchar] (255) NULL,
[RequestedDeliveryDate] [nvarchar] (255) NULL,
[ConfirmedDeliveryDate] [nvarchar] (255) NULL,
[PlanningDeliveryDate] [nvarchar] (255) NULL,
[StandardUnitofMeasure] [nvarchar] (255) NULL,
[StandardUnitofQty] [nvarchar] (255) NULL,
[ReportingUnitofMeasure] [nvarchar] (255) NULL,
[ReportingUnitofQty] [nvarchar] (255) NULL,
[product_category_direct] [int] NULL,
[product_category_level_1] [nvarchar] (255) NULL,
[product_category_level_2] [nvarchar] (255) NULL,
[product_category_level_3] [nvarchar] (255) NULL,
[product_category_level_4] [nvarchar] (255) NULL,
[product_category_level_5] [nvarchar] (255) NULL,
[EntryDate] [decimal] (8, 0) NULL,
[ChangeDate] [nvarchar] (255) NULL,
[DataSource] [varchar] (14) NULL,
[DataSourceKey] [int] NOT NULL,
[DateDataExtracted] [datetime] NULL
)
GO
