CREATE TABLE [tsa].[ics_land_aspect4_VARITBL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VARITBL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VARITBL_IsDuplicate] DEFAULT ((0)),
[VARI_RECSTS] [decimal] (1, 0) NULL,
[VARI_RECID] [nvarchar] (2) NULL,
[VARI_NR] [nvarchar] (16) NULL,
[VARI_KONCRN] [decimal] (3, 0) NULL,
[VARI_FIRMA] [decimal] (3, 0) NULL,
[VARI_TYPE] [nvarchar] (1) NULL,
[VARI_INR] [nvarchar] (16) NULL,
[VARI_BETEGN] [nvarchar] (255) NULL,
[VARI_GRP] [nvarchar] (2) NULL,
[VARI_MSGRP] [nvarchar] (2) NULL,
[VARI_RABGRP] [nvarchar] (5) NULL,
[VARI_ENHED] [nvarchar] (5) NULL,
[VARI_OMRFAK] [decimal] (9, 4) NULL,
[VARI_OMRKOD] [nvarchar] (1) NULL,
[VARI_PRISAN] [decimal] (7, 0) NULL,
[VARI_ANTDEC] [decimal] (1, 0) NULL,
[VARI_LEVDQR] [nvarchar] (16) NULL,
[VARI_STDVAL] [nvarchar] (4) NULL,
[VARI_STDPRI] [decimal] (11, 2) NULL,
[VARI_SENVAL] [nvarchar] (4) NULL,
[VARI_SENPRI] [decimal] (11, 2) NULL,
[VARI_BESOMK] [decimal] (11, 2) NULL,
[VARI_SPECAF] [nvarchar] (1) NULL,
[VARI_PRIRAB] [nvarchar] (1) NULL,
[VARI_MGDRAB] [nvarchar] (1) NULL,
[VARI_MINORD] [decimal] (13, 5) NULL,
[VARI_ENHORD] [decimal] (13, 5) NULL,
[VARI_MAXORD] [decimal] (13, 5) NULL,
[VARI_TIDMIN] [decimal] (3, 0) NULL,
[VARI_TIDENH] [decimal] (3, 0) NULL,
[VARI_DISPON] [nvarchar] (5) NULL,
[VARI_TOLD] [nvarchar] (4) NULL,
[VARI_TOLDPR] [nvarchar] (5) NULL,
[VARI_STAT] [nvarchar] (1) NULL,
[VARI_AENDDT] [decimal] (8, 0) NULL,
[VARI_AENDAF] [nvarchar] (10) NULL,
[VARI_OPRDT] [decimal] (8, 0) NULL,
[VARI_OPRAF] [nvarchar] (10) NULL,
[VARI_FRAGAN] [decimal] (7, 0) NULL,
[VARI_BRUVGT] [decimal] (13, 5) NULL,
[VARI_NETVGT] [decimal] (13, 5) NULL,
[VARI_RUMF] [decimal] (13, 5) NULL,
[VARI_KOLSTR] [decimal] (13, 5) NULL,
[VARI_KOLANG] [nvarchar] (1) NULL,
[VARI_PALSTR] [decimal] (13, 5) NULL,
[VARI_PALANG] [nvarchar] (1) NULL,
[VARI_ARTBEH] [nvarchar] (2) NULL,
[VARI_MLAGER] [nvarchar] (8) NULL,
[VARI_BESINT] [decimal] (3, 0) NULL,
[VARI_TS] [decimal] (8, 0) NULL,
[VARI_MODNR] [nvarchar] (16) NULL,
[VARI_MODVAR] [nvarchar] (8) NULL,
[VARI_LGD] [decimal] (11, 2) NULL,
[VARI_BRD] [decimal] (11, 2) NULL,
[VARI_HQJ] [decimal] (11, 2) NULL
)
GO
