CREATE TABLE [tsa].[ics_land_m3v7_MPLIND]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_m3v7_MPLIND_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_m3v7_MPLIND_IsDuplicate] DEFAULT ((0)),
[ICCONO] [decimal] (3, 0) NULL,
[ICFACI] [nvarchar] (255) NULL,
[ICWHLO] [nvarchar] (255) NULL,
[ICWHSL] [nvarchar] (255) NULL,
[ICBANO] [nvarchar] (255) NULL,
[ICCAMU] [nvarchar] (255) NULL,
[ICPUNO] [nvarchar] (255) NULL,
[ICPNLI] [decimal] (3, 0) NULL,
[ICPNLS] [decimal] (3, 0) NULL,
[ICPNLX] [decimal] (5, 0) NULL,
[ICSUDO] [nvarchar] (255) NULL,
[ICREPN] [decimal] (10, 0) NULL,
[ICPUOS] [nvarchar] (255) NULL,
[ICUGCD] [decimal] (1, 0) NULL,
[ICNEAC] [decimal] (1, 0) NULL,
[ICREOR] [decimal] (1, 0) NULL,
[ICCHPO] [decimal] (1, 0) NULL,
[ICRPQA] [decimal] (15, 6) NULL,
[ICRPQT] [decimal] (15, 6) NULL,
[ICTRDT] [decimal] (8, 0) NULL,
[ICPLDT] [decimal] (8, 0) NULL,
[ICRENE] [nvarchar] (255) NULL,
[ICRESP] [nvarchar] (255) NULL,
[ICBOLN] [nvarchar] (255) NULL,
[ICCARN] [nvarchar] (255) NULL,
[ICSMDT] [decimal] (8, 0) NULL,
[ICARDT] [decimal] (8, 0) NULL,
[ICNOPK] [decimal] (5, 0) NULL,
[ICFWRF] [nvarchar] (255) NULL,
[ICOEND] [decimal] (1, 0) NULL,
[ICSCOP] [decimal] (17, 6) NULL,
[ICSERA] [decimal] (11, 6) NULL,
[ICDTID] [decimal] (13, 0) NULL,
[ICTIHM] [decimal] (4, 0) NULL,
[ICDLIX] [decimal] (11, 0) NULL,
[ICAGNB] [nvarchar] (255) NULL,
[ICPACN] [nvarchar] (255) NULL,
[ICPACC] [nvarchar] (255) NULL,
[ICRGDT] [decimal] (8, 0) NULL,
[ICRGTM] [decimal] (6, 0) NULL,
[ICTXID] [decimal] (13, 0) NULL
)
GO
