CREATE TABLE [tsa].[ICS_LAND_SAP_GBR_KONV]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[KNUMV] [nvarchar] (10) NULL,
[KPOSN] [nvarchar] (6) NULL,
[STUNR] [nvarchar] (3) NULL,
[ZAEHK] [nvarchar] (2) NULL,
[KAPPL] [nvarchar] (2) NULL,
[KSCHL] [nvarchar] (4) NULL,
[KDATU] [datetime] NULL,
[KRECH] [nvarchar] (1) NULL,
[KAWRT] [decimal] (15, 2) NULL,
[KBETR] [decimal] (11, 2) NULL,
[WAERS] [nvarchar] (5) NULL,
[KKURS] [decimal] (9, 5) NULL,
[KPEIN] [decimal] (5, 0) NULL,
[KMEIN] [nvarchar] (3) NULL,
[KUMZA] [decimal] (5, 0) NULL,
[KUMNE] [decimal] (5, 0) NULL,
[KNTYP] [nvarchar] (1) NULL,
[KSTAT] [nvarchar] (1) NULL,
[KNPRS] [nvarchar] (1) NULL,
[KRUEK] [nvarchar] (1) NULL,
[KRELI] [nvarchar] (1) NULL,
[KHERK] [nvarchar] (1) NULL,
[KGRPE] [nvarchar] (1) NULL,
[KOUPD] [nvarchar] (1) NULL,
[KOLNR] [nvarchar] (2) NULL,
[KNUMH] [nvarchar] (10) NULL,
[KOPOS] [nvarchar] (2) NULL,
[KVSL1] [nvarchar] (3) NULL,
[SAKN1] [nvarchar] (10) NULL,
[MWSK1] [nvarchar] (2) NULL,
[KVSL2] [nvarchar] (3) NULL,
[SAKN2] [nvarchar] (10) NULL,
[MWSK2] [nvarchar] (2) NULL,
[LIFNR] [nvarchar] (10) NULL,
[KUNNR] [nvarchar] (10) NULL,
[KDIFF] [decimal] (5, 2) NULL,
[KWERT] [decimal] (13, 2) NULL,
[KSTEU] [nvarchar] (1) NULL,
[KINAK] [nvarchar] (1) NULL,
[KOAID] [nvarchar] (1) NULL,
[ZAEKO] [nvarchar] (2) NULL,
[KMXAW] [nvarchar] (1) NULL,
[KMXWR] [nvarchar] (1) NULL,
[KFAKTOR] [float] NULL,
[KDUPL] [nvarchar] (1) NULL,
[KFAKTOR1] [float] NULL,
[KZBZG] [nvarchar] (1) NULL,
[KSTBS] [decimal] (15, 2) NULL,
[KONMS] [nvarchar] (3) NULL,
[KONWS] [nvarchar] (5) NULL,
[KAWRT_K] [decimal] (15, 2) NULL,
[KWAEH] [nvarchar] (5) NULL,
[KWERT_K] [decimal] (13, 2) NULL,
[KFKIV] [nvarchar] (1) NULL,
[KVARC] [nvarchar] (1) NULL,
[KMPRS] [nvarchar] (1) NULL,
[PRSQU] [nvarchar] (1) NULL,
[VARCOND] [nvarchar] (26) NULL,
[STUFE] [decimal] (2, 0) NULL,
[WEGXX] [decimal] (4, 0) NULL,
[KTREL] [nvarchar] (1) NULL,
[MDFLG] [nvarchar] (1) NULL,
[TXJLV] [nvarchar] (1) NULL,
[KBFLAG] [binary] (2) NULL,
[KOLNR3] [nvarchar] (3) NULL,
[EtlSourceTable] [varchar] (200) NOT NULL
)
GO
