CREATE TABLE [tsa].[ics_land_m3_MPHEAD]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_m3_MPHEAD_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_m3_MPHEAD_IsDuplicate] DEFAULT ((0)),
[IACONO] [decimal] (3, 0) NULL,
[IADIVI] [nvarchar] (255) NULL,
[IAFACI] [nvarchar] (255) NULL,
[IAWHLO] [nvarchar] (255) NULL,
[IAPUNO] [nvarchar] (255) NULL,
[IAORTY] [nvarchar] (255) NULL,
[IAPOTC] [nvarchar] (255) NULL,
[IAPUSL] [nvarchar] (255) NULL,
[IASLDT] [decimal] (8, 0) NULL,
[IAPUST] [nvarchar] (255) NULL,
[IASCDT] [decimal] (8, 0) NULL,
[IACMCO] [nvarchar] (255) NULL,
[IAPUDT] [decimal] (8, 0) NULL,
[IASUNO] [nvarchar] (255) NULL,
[IALNCD] [nvarchar] (255) NULL,
[IACUCD] [nvarchar] (255) NULL,
[IATEPY] [nvarchar] (255) NULL,
[IAPYME] [nvarchar] (255) NULL,
[IAMODL] [nvarchar] (255) NULL,
[IATEDL] [nvarchar] (255) NULL,
[IATEAF] [nvarchar] (255) NULL,
[IATEPA] [nvarchar] (255) NULL,
[IARFID] [nvarchar] (255) NULL,
[IAYRE1] [nvarchar] (255) NULL,
[IADWDT] [decimal] (8, 0) NULL,
[IAHDDT] [decimal] (8, 0) NULL,
[IAPRSU] [nvarchar] (255) NULL,
[IAOURR] [nvarchar] (255) NULL,
[IAOURT] [nvarchar] (255) NULL,
[IAAGNT] [nvarchar] (255) NULL,
[IANTAM] [decimal] (15, 2) NULL,
[IABRAM] [decimal] (15, 2) NULL,
[IAOTBA] [decimal] (15, 2) NULL,
[IAPURC] [nvarchar] (255) NULL,
[IABUYE] [nvarchar] (255) NULL,
[IAAURE] [nvarchar] (255) NULL,
[IALEDT] [decimal] (8, 0) NULL,
[IAFUSC] [nvarchar] (255) NULL,
[IAEXAT] [decimal] (1, 0) NULL,
[IAPTAC] [decimal] (1, 0) NULL,
[IARTAC] [decimal] (1, 0) NULL,
[IAEXAV] [decimal] (1, 0) NULL,
[IANOPP] [decimal] (3, 0) NULL,
[IANOLN] [decimal] (3, 0) NULL,
[IAMTWP] [decimal] (1, 0) NULL,
[IAMTDP] [decimal] (1, 0) NULL,
[IACOAM] [decimal] (17, 6) NULL,
[IAODAM] [decimal] (15, 2) NULL,
[IAOTPC] [decimal] (5, 2) NULL,
[IAPRLA] [decimal] (1, 0) NULL,
[IAVOL3] [decimal] (9, 3) NULL,
[IAGRWE] [decimal] (9, 3) NULL,
[IATOQT] [decimal] (15, 6) NULL,
[IATFNO] [nvarchar] (255) NULL,
[IALRED] [decimal] (8, 0) NULL,
[IAATDT] [decimal] (8, 0) NULL,
[IAPOPO] [decimal] (1, 0) NULL,
[IATEL1] [nvarchar] (255) NULL,
[IADUDT] [decimal] (8, 0) NULL,
[IACUTE] [decimal] (1, 0) NULL,
[IAAGRA] [decimal] (11, 6) NULL,
[IAPYAD] [nvarchar] (255) NULL,
[IASHVI] [nvarchar] (255) NULL,
[IAFIDS] [nvarchar] (255) NULL,
[IARCDT] [decimal] (8, 0) NULL,
[IALIDT] [decimal] (8, 0) NULL,
[IAEXEP] [decimal] (15, 2) NULL,
[IAINEP] [decimal] (15, 2) NULL,
[IATLEX] [decimal] (15, 2) NULL,
[IATLIN] [decimal] (15, 2) NULL,
[IATEOR] [decimal] (1, 0) NULL,
[IATXID] [decimal] (13, 0) NULL,
[IAPRTX] [decimal] (13, 0) NULL,
[IAPOTX] [decimal] (13, 0) NULL,
[IADTID] [decimal] (13, 0) NULL,
[IAPROJ] [nvarchar] (255) NULL,
[IAELNO] [nvarchar] (255) NULL,
[IAECLC] [nvarchar] (255) NULL,
[IACPRI] [nvarchar] (255) NULL,
[IAHAFE] [nvarchar] (255) NULL,
[IATIHM] [decimal] (4, 0) NULL,
[IAMEDC] [nvarchar] (255) NULL,
[IARGDT] [decimal] (8, 0) NULL,
[IARGTM] [decimal] (6, 0) NULL,
[IALMDT] [decimal] (8, 0) NULL,
[IACHNO] [decimal] (3, 0) NULL,
[IACHID] [nvarchar] (255) NULL,
[IALMTS] [decimal] (18, 0) NULL,
[IAPRVW] [decimal] (8, 0) NULL,
[IARASN] [nvarchar] (255) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_m3_MPHEAD_1] ON [tsa].[ics_land_m3_MPHEAD] ([IAPUNO])
GO
