CREATE TABLE [tsa].[ics_land_SAP_GBR_T052]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_T052_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_T052_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[ZTERM] [nvarchar] (4) NULL,
[ZTAGG] [nvarchar] (2) NULL,
[ZDART] [nvarchar] (1) NULL,
[ZFAEL] [nvarchar] (2) NULL,
[ZMONA] [nvarchar] (2) NULL,
[ZTAG1] [nvarchar] (3) NULL,
[ZPRZ1] [decimal] (5, 3) NULL,
[ZTAG2] [nvarchar] (3) NULL,
[ZPRZ2] [decimal] (5, 3) NULL,
[ZTAG3] [nvarchar] (3) NULL,
[ZSTG1] [nvarchar] (2) NULL,
[ZSMN1] [nvarchar] (2) NULL,
[ZSTG2] [nvarchar] (2) NULL,
[ZSMN2] [nvarchar] (2) NULL,
[ZSTG3] [nvarchar] (2) NULL,
[ZSMN3] [nvarchar] (2) NULL,
[XZBRV] [nvarchar] (1) NULL,
[ZSCHF] [nvarchar] (1) NULL,
[XCHPB] [nvarchar] (1) NULL,
[TXN08] [nvarchar] (8) NULL,
[ZLSCH] [nvarchar] (1) NULL,
[XCHPM] [nvarchar] (1) NULL,
[KOART] [nvarchar] (1) NULL,
[XSPLT] [nvarchar] (1) NULL,
[XSCRC] [nvarchar] (1) NULL
)
GO
