CREATE TABLE [tsa].[ics_land_Navision_ROU_Purchase_Payables_Setup]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_ROU_Purchase_Payables_Setup_ExcludedFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_ROU_Purchase_Payables_Setup_IsDuplicate] DEFAULT ((0)),
[timestamp] [varbinary] (8) NULL,
[Primary Key] [varchar] (10) NOT NULL,
[Discount Posting] [int] NULL,
[Receipt on Invoice] [tinyint] NULL,
[Invoice Rounding] [tinyint] NULL,
[Ext_ Doc_ No_ Mandatory] [tinyint] NULL,
[Vendor Nos_] [varchar] (10) NULL,
[Quote Nos_] [varchar] (10) NULL,
[Order Nos_] [varchar] (10) NULL,
[Invoice Nos_] [varchar] (10) NULL,
[Posted Invoice Nos_] [varchar] (10) NULL,
[Credit Memo Nos_] [varchar] (10) NULL,
[Posted Credit Memo Nos_] [varchar] (10) NULL,
[Posted Receipt Nos_] [varchar] (10) NULL,
[Blanket Order Nos_] [varchar] (10) NULL,
[Calc_ Inv_ Discount] [tinyint] NULL,
[Appln_ between Currencies] [int] NULL,
[Copy Comments Blanket to Order] [tinyint] NULL,
[Copy Comments Order to Invoice] [tinyint] NULL,
[Copy Comments Order to Receipt] [tinyint] NULL,
[Allow VAT Difference] [tinyint] NULL,
[Calc_ Inv_ Disc_ per VAT ID] [tinyint] NULL,
[Posted Return Shpt_ Nos_] [varchar] (10) NULL,
[Copy Cmts Ret_Ord_ to Ret_Shpt] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Cr_ Memo] [tinyint] NULL,
[Return Order Nos_] [varchar] (10) NULL,
[Return Shipment on Credit Memo] [tinyint] NULL,
[Exact Cost Reversing Mandatory] [tinyint] NULL,
[Custom Invoice No_ Mandatory] [tinyint] NULL,
[Posting Desc_ Code] [varchar] (10) NULL,
[Posted Self-Invoice Nos_] [varchar] (10) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_ROU_Purchase_Payables_Setup] ON [tsa].[ics_land_Navision_ROU_Purchase_Payables_Setup] ([Primary Key])
GO
