CREATE TABLE [tsa].[ics_land_SAP_GBR_EKES]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_EKES_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_EKES_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[ETENS] [nvarchar] (4) NULL,
[EBTYP] [nvarchar] (2) NULL,
[EINDT] [datetime] NULL,
[LPEIN] [nvarchar] (1) NULL,
[UZEIT] [datetime] NULL,
[ERDAT] [datetime] NULL,
[EZEIT] [datetime] NULL,
[MENGE] [decimal] (13, 3) NULL,
[DABMG] [decimal] (13, 3) NULL,
[ESTKZ] [nvarchar] (1) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[KZDIS] [nvarchar] (1) NULL,
[XBLNR] [nvarchar] (35) NULL,
[VBELN] [nvarchar] (10) NULL,
[VBELP] [nvarchar] (6) NULL,
[MPROF] [nvarchar] (4) NULL,
[EMATN] [nvarchar] (18) NULL,
[MAHNZ] [decimal] (3, 0) NULL,
[CHARG] [nvarchar] (10) NULL,
[UECHA] [nvarchar] (6) NULL,
[REF_ETENS] [nvarchar] (4) NULL,
[IMWRK] [nvarchar] (1) NULL,
[VBELN_ST] [nvarchar] (10) NULL,
[VBELP_ST] [nvarchar] (6) NULL
)
GO
