CREATE TABLE [tsa].[ics_land_SAP_GBR_VBEP]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBEP_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBEP_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNR] [nvarchar] (6) NULL,
[ETENR] [nvarchar] (4) NULL,
[ETTYP] [nvarchar] (2) NULL,
[LFREL] [nvarchar] (1) NULL,
[EDATU] [datetime] NULL,
[EZEIT] [datetime] NULL,
[WMENG] [decimal] (13, 3) NULL,
[BMENG] [decimal] (13, 3) NULL,
[VRKME] [nvarchar] (3) NULL,
[LMENG] [decimal] (13, 3) NULL,
[MEINS] [nvarchar] (3) NULL,
[BDDAT] [datetime] NULL,
[BDART] [nvarchar] (2) NULL,
[PLART] [nvarchar] (1) NULL,
[VBELE] [nvarchar] (10) NULL,
[POSNE] [nvarchar] (6) NULL,
[ETENE] [nvarchar] (4) NULL,
[RSDAT] [datetime] NULL,
[IDNNR] [nvarchar] (10) NULL,
[BANFN] [nvarchar] (10) NULL,
[BSART] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[WEPOS] [nvarchar] (1) NULL,
[REPOS] [nvarchar] (1) NULL,
[LRGDT] [datetime] NULL,
[PRGRS] [nvarchar] (1) NULL,
[TDDAT] [datetime] NULL,
[MBDAT] [datetime] NULL,
[LDDAT] [datetime] NULL,
[WADAT] [datetime] NULL,
[CMENG] [decimal] (13, 3) NULL,
[LIFSP] [nvarchar] (2) NULL,
[GRSTR] [nvarchar] (3) NULL,
[ABART] [nvarchar] (1) NULL,
[ABRUF] [nvarchar] (10) NULL,
[ROMS1] [decimal] (13, 3) NULL,
[ROMS2] [decimal] (13, 3) NULL,
[ROMS3] [decimal] (13, 3) NULL,
[ROMEI] [nvarchar] (3) NULL,
[RFORM] [nvarchar] (2) NULL,
[UMVKZ] [decimal] (5, 0) NULL,
[UMVKN] [decimal] (5, 0) NULL,
[VERFP] [nvarchar] (1) NULL,
[BWART] [nvarchar] (3) NULL,
[BNFPO] [nvarchar] (5) NULL,
[ETART] [nvarchar] (1) NULL,
[AUFNR] [nvarchar] (12) NULL,
[PLNUM] [nvarchar] (10) NULL,
[SERNR] [nvarchar] (8) NULL,
[AESKD] [nvarchar] (17) NULL,
[ABGES] [float] NULL,
[MBUHR] [datetime] NULL,
[TDUHR] [datetime] NULL,
[LDUHR] [datetime] NULL,
[WAUHR] [datetime] NULL,
[AULWE] [nvarchar] (10) NULL,
[MBDAT_DRS] [datetime] NULL
)
GO
