CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Salesperson_Purchaser]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_IsDuplicate] DEFAULT ((0)),
[Code] [varchar] (10) NULL,
[Commission %] [decimal] (38, 20) NULL,
[E-Mail] [varchar] (80) NULL,
[Empty SalesPerson_Purch Code] [tinyint] NULL,
[Enable Synchronization] [tinyint] NULL,
[Global Dimension 1 Code] [varchar] (20) NULL,
[Global Dimension 2 Code] [varchar] (20) NULL,
[Job Title] [varchar] (30) NULL,
[Name] [varchar] (50) NULL,
[Navision User ID] [varchar] (20) NULL,
[Notify about Appmt_ Changes] [tinyint] NULL,
[Notify about Contact Changes] [tinyint] NULL,
[Notify about Task Changes] [tinyint] NULL,
[Notify about Team To-do Chgs_] [tinyint] NULL,
[Outlook Calendar Folder Path] [varchar] (250) NULL,
[Outlook Calendar FolderID] [image] NULL,
[Outlook Calendar StoreID] [image] NULL,
[Outlook Contacts Folder Path] [varchar] (250) NULL,
[Outlook Contacts FolderID] [image] NULL,
[Outlook Contacts StoreID] [image] NULL,
[Outlook Profile Name] [varchar] (80) NULL,
[Outlook Tasks Folder Path] [varchar] (250) NULL,
[Outlook Tasks FolderID] [image] NULL,
[Outlook Tasks StoreID] [image] NULL,
[Outlook User Name] [varchar] (80) NULL,
[Phone No_] [varchar] (30) NULL,
[Search E-Mail] [varchar] (80) NULL,
[Synchronize From] [varchar] (32) NULL,
[Synchronize To] [varchar] (32) NULL,
[Synchronize To-dos] [int] NULL,
[Version No_] [int] NULL,
[timestamp] [timestamp] NOT NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Rom_Live Icopal Romania$Salesperson_Purchaser_1] ON [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Salesperson_Purchaser] ([Code])
GO
