CREATE TABLE [tsa].[ics_land_baan_tiitm001610]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_tiitm001610_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_tiitm001610_IsDuplicate] DEFAULT ((0)),
[t_item] [nvarchar] (16) NULL,
[t_dsca] [nvarchar] (30) NULL,
[t_dscb] [nvarchar] (8) NULL,
[t_dscc] [nvarchar] (12) NULL,
[t_dscd] [nvarchar] (8) NULL,
[t_wght] [float] NULL,
[t_seak] [nvarchar] (16) NULL,
[t_seab] [nvarchar] (16) NULL,
[t_kitm] [smallint] NULL,
[t_citg] [nvarchar] (6) NULL,
[t_ctyp] [nvarchar] (3) NULL,
[t_csel] [nvarchar] (3) NULL,
[t_csig] [nvarchar] (3) NULL,
[t_cvat] [nvarchar] (9) NULL,
[t_txta] [int] NULL,
[t_uset] [nvarchar] (6) NULL,
[t_cuni] [nvarchar] (3) NULL,
[t_stgu] [nvarchar] (3) NULL,
[t_cwar] [nvarchar] (3) NULL,
[t_kltc] [smallint] NULL,
[t_obpr] [smallint] NULL,
[t_kpsl] [smallint] NULL,
[t_npsl] [int] NULL,
[t_pics] [smallint] NULL,
[t_abcc] [nvarchar] (1) NULL,
[t_lcod] [datetime] NULL,
[t_uscu] [float] NULL,
[t_usab] [float] NULL,
[t_slmp] [smallint] NULL,
[t_serv] [smallint] NULL,
[t_sfst] [float] NULL,
[t_maxs] [float] NULL,
[t_csps] [nvarchar] (3) NULL,
[t_cspd] [nvarchar] (3) NULL,
[t_cfmd] [nvarchar] (3) NULL,
[t_scst] [float] NULL,
[t_stoc] [float] NULL,
[t_blck] [float] NULL,
[t_ordr] [float] NULL,
[t_allo] [float] NULL,
[t_hall] [float] NULL,
[t_quot] [float] NULL,
[t_ltdt] [datetime] NULL,
[t_opol] [smallint] NULL,
[t_osys] [smallint] NULL,
[t_omth] [smallint] NULL,
[t_oqmf] [float] NULL,
[t_mioq] [float] NULL,
[t_maoq] [float] NULL,
[t_umer] [smallint] NULL,
[t_fioq] [float] NULL,
[t_ecoq] [float] NULL,
[t_reop] [float] NULL,
[t_oint] [smallint] NULL,
[t_ddfq] [float] NULL,
[t_oltm] [smallint] NULL,
[t_sftm] [smallint] NULL,
[t_fodt] [datetime] NULL,
[t_ocst] [float] NULL,
[t_auso] [smallint] NULL,
[t_cpha] [smallint] NULL,
[t_oqdr] [smallint] NULL,
[t_repi] [smallint] NULL,
[t_scdl] [nvarchar] (3) NULL,
[t_orip] [smallint] NULL,
[t_pcrp] [smallint] NULL,
[t_stpm] [smallint] NULL,
[t_mrpc] [smallint] NULL,
[t_plmm] [smallint] NULL,
[t_mrpo] [smallint] NULL,
[t_eitm] [smallint] NULL,
[t_bfcp] [smallint] NULL,
[t_bfep] [smallint] NULL,
[t_bfhr] [smallint] NULL,
[t_ndrp] [smallint] NULL,
[t_nnts] [smallint] NULL,
[t_qpnt] [float] NULL,
[t_unom] [float] NULL,
[t_runi] [float] NULL,
[t_scpf] [smallint] NULL,
[t_crmp] [smallint] NULL,
[t_tmfc] [smallint] NULL,
[t_roun] [smallint] NULL,
[t_ncst] [smallint] NULL,
[t_llcd] [smallint] NULL,
[t_llci] [smallint] NULL,
[t_mrpi] [smallint] NULL,
[t_stmr] [float] NULL,
[t_cuqp] [nvarchar] (3) NULL,
[t_cupp] [nvarchar] (3) NULL,
[t_cpgp] [nvarchar] (6) NULL,
[t_csgp] [nvarchar] (6) NULL,
[t_pcgp] [nvarchar] (6) NULL,
[t_ccur] [nvarchar] (3) NULL,
[t_ltpp] [datetime] NULL,
[t_prip] [float] NULL,
[t_avpr] [float] NULL,
[t_ltpr] [float] NULL,
[t_suno] [nvarchar] (6) NULL,
[t_qual] [smallint] NULL,
[t_purc] [float] NULL,
[t_txtp] [int] NULL,
[t_cuqs] [nvarchar] (3) NULL,
[t_cups] [nvarchar] (3) NULL,
[t_cpgs] [nvarchar] (6) NULL,
[t_csgs] [nvarchar] (6) NULL,
[t_cmgp] [nvarchar] (6) NULL,
[t_rbgp] [nvarchar] (6) NULL,
[t_pris] [float] NULL,
[t_ltsp] [datetime] NULL,
[t_prir] [float] NULL,
[t_umsp] [real] NULL,
[t_lmsp] [real] NULL,
[t_ccde] [nvarchar] (8) NULL,
[t_ctyo] [nvarchar] (3) NULL,
[t_txts] [int] NULL,
[t_cpcp] [nvarchar] (3) NULL,
[t_copr] [float] NULL,
[t_matc] [float] NULL,
[t_oprc] [float] NULL,
[t_cuid] [smallint] NULL,
[t_actf] [float] NULL,
[t_ltcp] [datetime] NULL,
[t_stva] [smallint] NULL,
[t_buyr] [int] NULL,
[t_cplb] [int] NULL,
[t_cppp] [smallint] NULL,
[t_ccit] [nvarchar] (16) NULL,
[t_ccfu] [smallint] NULL,
[t_ccco] [nvarchar] (8) NULL,
[t_prre] [smallint] NULL,
[t_copt] [smallint] NULL,
[t_cprp] [float] NULL,
[t_itmt] [smallint] NULL,
[t_proi] [smallint] NULL,
[t_cont] [smallint] NULL,
[t_cntr] [nvarchar] (3) NULL,
[t_czed] [smallint] NULL,
[t_reli] [nvarchar] (16) NULL,
[t_assi] [smallint] NULL,
[t_potc] [real] NULL,
[t_ffsi] [int] NULL,
[t_qbsi] [float] NULL,
[t_osyc] [smallint] NULL,
[t_ufra] [smallint] NULL,
[t_nobd] [smallint] NULL,
[t_blcm] [float] NULL,
[t_dcnt] [nvarchar] (3) NULL,
[t_exkb] [smallint] NULL,
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL
)
GO
