CREATE TABLE [tsa].[ics_land_aspect4_SSTATBL]
(
[EtlBatchRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlStepRunId] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[ExcludeFromMerge] [bit] NULL,
[IsDuplicate] [bit] NULL,
[SSTA_STATUS_KODE] [decimal] (1, 0) NULL,
[SSTA_RECORD_ID] [nvarchar] (2) NULL,
[SSTA_KUNDE_NUMMER] [nvarchar] (16) NULL,
[SSTA_VARE_NUMMER] [nvarchar] (16) NULL,
[SSTA_FAKTURADATO] [decimal] (8, 0) NULL,
[SSTA_LQBENR] [decimal] (3, 0) NULL,
[SSTA_KONCRN] [decimal] (3, 0) NULL,
[SSTA_FIRMA] [decimal] (3, 0) NULL,
[SSTA_SAELGER] [nvarchar] (8) NULL,
[SSTA_SPEC_AFTALE] [nvarchar] (1) NULL,
[SSTA_DISTRIKT] [nvarchar] (8) NULL,
[SSTA_BONUSORDNING] [nvarchar] (4) NULL,
[SSTA_VALUTA] [nvarchar] (4) NULL,
[SSTA_LEV_ADRESSENR] [nvarchar] (4) NULL,
[SSTA_BETALINGSKODE] [decimal] (3, 0) NULL,
[SSTA_BET_KUNDENR] [nvarchar] (16) NULL,
[SSTA_FAKTURA_NR] [decimal] (9, 0) NULL,
[SSTA_ORDRETYPE] [nvarchar] (2) NULL,
[SSTA_ANTAL_BASIS] [decimal] (13, 5) NULL,
[SSTA_SALG_GRUNDPRIS] [decimal] (11, 2) NULL,
[SSTA_SALG_SALGSPRIS] [decimal] (11, 2) NULL,
[SSTA_SALG_LINIERABAT] [decimal] (11, 2) NULL,
[SSTA_SALG_KOSTPRIS] [decimal] (11, 2) NULL,
[SSTA_BONUS] [decimal] (11, 2) NULL,
[SSTA_PROVISION] [decimal] (11, 2) NULL,
[SSTA_TOTALRABAT] [decimal] (11, 2) NULL,
[SSTA_UDF1] [nvarchar] (5) NULL,
[SSTA_UDF2] [nvarchar] (5) NULL,
[SSTA_UDF3] [nvarchar] (5) NULL,
[SSTA_UDF4] [nvarchar] (5) NULL,
[SSTA_UDF5] [nvarchar] (5) NULL,
[SSTA_LAGER_NUMMER] [nvarchar] (8) NULL,
[SSTA_LAGER_PARTI] [nvarchar] (24) NULL,
[SSTA_ORDRENR] [decimal] (9, 0) NULL,
[SSTA_LEV_LQBENR] [decimal] (4, 0) NULL,
[SSTA_ORDRE_LINIENR] [decimal] (4, 0) NULL,
[SSTA_OPR_BESTILT_ANTAL] [decimal] (13, 5) NULL,
[SSTA_OPR_TERMIN] [decimal] (8, 0) NULL,
[SSTA_LEVERANCE_DATO] [decimal] (8, 0) NULL,
[SSTA_HENSAT_FRAGT] [decimal] (11, 2) NULL,
[SSTA_ORDRE_DATO] [decimal] (8, 0) NULL,
[SSTA_QNS_TERMIN] [decimal] (8, 0) NULL,
[SSTA_KORREKTION] [decimal] (11, 2) NULL,
[SSTA_LOKAT] [nvarchar] (10) NULL,
[SSTA_PROJNR] [decimal] (9, 0) NULL,
[SSTA_AARSAG] [nvarchar] (5) NULL,
[SSTA_SOART] [nvarchar] (2) NULL,
[SSTA_SOARTB] [nvarchar] (2) NULL,
[SSTA_VSID] [nvarchar] (1) NULL,
[SSTA_VSPRNV] [nvarchar] (1) NULL,
[SSTA_AFGIFT] [decimal] (11, 2) NULL,
[SSTA_TS] [decimal] (8, 0) NULL,
[SSTA_VAKURS] [decimal] (13, 5) NULL,
[SSTA_FORH] [nvarchar] (16) NULL,
[SSTA_LEVNR] [nvarchar] (16) NULL,
[SST1_KAEDE] [nvarchar] (5) NULL,
[SST1_HGRP] [nvarchar] (5) NULL,
[SST1_E3TRIM] [nvarchar] (1) NULL
)
GO
