CREATE TABLE [tsa].[ics_land_m3_FGRECL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3_FGRECL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3_FGRECL_IsDuplicate] DEFAULT ((0)),
[F2CONO] [decimal] (3, 0) NULL,
[F2DIVI] [nvarchar] (255) NULL,
[F2PUNO] [nvarchar] (255) NULL,
[F2PNLI] [decimal] (3, 0) NULL,
[F2PNLS] [decimal] (3, 0) NULL,
[F2REPN] [decimal] (10, 0) NULL,
[F2RELP] [decimal] (1, 0) NULL,
[F2FACI] [nvarchar] (255) NULL,
[F2WHLO] [nvarchar] (255) NULL,
[F2SUDO] [nvarchar] (255) NULL,
[F2SUNO] [nvarchar] (255) NULL,
[F2SORN] [nvarchar] (255) NULL,
[F2TRDT] [decimal] (8, 0) NULL,
[F2ITNO] [nvarchar] (255) NULL,
[F2IMST] [decimal] (1, 0) NULL,
[F2IMDT] [decimal] (8, 0) NULL,
[F2SCOC] [decimal] (17, 6) NULL,
[F2SCOP] [decimal] (19, 8) NULL,
[F2SCDC] [decimal] (5, 2) NULL,
[F2PUCD] [decimal] (5, 0) NULL,
[F2CUCD] [nvarchar] (255) NULL,
[F2SERA] [decimal] (11, 6) NULL,
[F2CRTP] [decimal] (2, 0) NULL,
[F2RPQT] [decimal] (15, 6) NULL,
[F2RPQA] [decimal] (15, 6) NULL,
[F2CAWE] [decimal] (15, 6) NULL,
[F2IVQT] [decimal] (15, 6) NULL,
[F2IVQA] [decimal] (15, 6) NULL,
[F2IVCW] [decimal] (15, 6) NULL,
[F2RCAC] [decimal] (15, 2) NULL,
[F2ICAC] [decimal] (15, 2) NULL,
[F2IASR] [decimal] (1, 0) NULL,
[F2IASD] [decimal] (1, 0) NULL,
[F2ANBR] [decimal] (12, 0) NULL,
[F2SENO] [decimal] (4, 0) NULL,
[F2HSIN] [nvarchar] (255) NULL,
[F2SBAN] [nvarchar] (255) NULL,
[F2FGTP] [nvarchar] (255) NULL,
[F2ORTY] [nvarchar] (255) NULL,
[F2PIDT] [decimal] (8, 0) NULL,
[F2BUYE] [nvarchar] (255) NULL,
[F2RGDT] [decimal] (8, 0) NULL,
[F2RGTM] [decimal] (6, 0) NULL,
[F2LMDT] [decimal] (8, 0) NULL,
[F2CHNO] [decimal] (3, 0) NULL,
[F2CHID] [nvarchar] (255) NULL,
[F2FIAS] [decimal] (1, 0) NULL,
[F2LMTS] [decimal] (18, 0) NULL,
[F2BANO] [nvarchar] (255) NULL,
[F2TRTM] [decimal] (6, 0) NULL,
[F2CLAN] [nvarchar] (255) NULL,
[F2CLLN] [decimal] (3, 0) NULL,
[F2SCOA] [decimal] (19, 8) NULL,
[F2BLSB] [decimal] (1, 0) NULL
)
GO
