CREATE TABLE [tsa].[ics_land_M3V10gen_POL_OPAYMH]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_OPAYMH_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_OPAYMH_IsDuplicate] DEFAULT ((0)),
[UJACDT] [numeric] (8, 0) NULL,
[UJBKID] [nchar] (5) NULL,
[UJCDTT] [numeric] (2, 0) NULL,
[UJCHID] [nchar] (10) NULL,
[UJCHNO] [numeric] (3, 0) NULL,
[UJCKNO] [nchar] (15) NULL,
[UJCONO] [numeric] (3, 0) NULL,
[UJCRTP] [numeric] (2, 0) NULL,
[UJCSHD] [nchar] (5) NULL,
[UJCUCD] [nchar] (3) NULL,
[UJCUNM] [nvarchar] (36) NULL,
[UJDIVI] [nchar] (3) NULL,
[UJFACI] [nchar] (3) NULL,
[UJLMDT] [numeric] (8, 0) NULL,
[UJPLNB] [numeric] (2, 0) NULL,
[UJPMAM] [numeric] (15, 2) NULL,
[UJPMLA] [numeric] (15, 2) NULL,
[UJPMNB] [numeric] (9, 0) NULL,
[UJPTST] [nchar] (2) NULL,
[UJPYCD] [nchar] (3) NULL,
[UJPYDT] [numeric] (8, 0) NULL,
[UJPYNO] [nchar] (10) NULL,
[UJRAPM] [numeric] (11, 6) NULL,
[UJRGDT] [numeric] (8, 0) NULL,
[UJRGTM] [numeric] (6, 0) NULL,
[UJVONO] [numeric] (8, 0) NULL,
[UJVSER] [nchar] (3) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_OPAYMH_1] ON [tsa].[ics_land_M3V10gen_POL_OPAYMH] ([UJCONO], [UJPLNB], [UJPMNB])
GO
