CREATE TABLE [tsa].[ics_land_Symfonia_UR]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_UR_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_UR_IsDuplicate] DEFAULT ((0)),
[aktywny] [bit] NULL,
[bkonto] [varchar] (50) NULL,
[bnazwa] [varchar] (100) NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[dom] [varchar] (15) NULL,
[email] [varchar] (50) NULL,
[fax] [varchar] (25) NULL,
[flag] [smallint] NULL,
[formaplatn] [int] NULL,
[grupacen] [smallint] NULL,
[id] [int] NULL,
[idfk] [int] NULL,
[idfk2] [int] NULL,
[idKraju] [int] NULL,
[idTX] [int] NULL,
[imie] [varchar] (14) NULL,
[info] [smallint] NULL,
[katalog] [int] NULL,
[khfk] [varchar] (24) NULL,
[kod] [varchar] (40) NULL,
[kodpocz] [varchar] (10) NULL,
[limit] [smallint] NULL,
[limitkwota] [float] NULL,
[limitwaluta] [varchar] (3) NULL,
[lokal] [varchar] (15) NULL,
[miejscowosc] [varchar] (50) NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[naglowek] [varchar] (19) NULL,
[nazwa] [varchar] (150) NULL,
[nazwisko] [varchar] (24) NULL,
[negoc] [smallint] NULL,
[nip] [varchar] (20) NULL,
[plattermin] [smallint] NULL,
[plattyp] [int] NULL,
[regon] [varchar] (20) NULL,
[rejon] [varchar] (25) NULL,
[rodzaj] [int] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[tel1] [varchar] (25) NULL,
[tel2] [varchar] (25) NULL,
[typ] [smallint] NULL,
[typks] [varchar] (40) NULL,
[ulica] [varchar] (50) NULL,
[upust] [float] NULL,
[www] [varchar] (100) NULL,
[znacznik] [smallint] NULL
)
GO
