CREATE TABLE [tsa].[ics_land_SAP_SVK_T001W]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_T001W_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_T001W_IsDuplicate] DEFAULT ((0)),
[ACHVM] [nvarchar] (1) NULL,
[ADRNR] [nvarchar] (10) NULL,
[AWSLS] [nvarchar] (6) NULL,
[BEDPL] [nvarchar] (1) NULL,
[BETOL] [nvarchar] (3) NULL,
[BWKEY] [nvarchar] (4) NULL,
[BZIRK] [nvarchar] (6) NULL,
[BZQHL] [nvarchar] (1) NULL,
[CHAZV] [nvarchar] (1) NULL,
[CHAZV_OLD] [nvarchar] (1) NULL,
[CITYC] [nvarchar] (4) NULL,
[COUNC] [nvarchar] (3) NULL,
[DVSART] [nvarchar] (1) NULL,
[EKORG] [nvarchar] (4) NULL,
[FABKL] [nvarchar] (2) NULL,
[FPRFW] [nvarchar] (3) NULL,
[IWERK] [nvarchar] (4) NULL,
[J_1BBRANCH] [nvarchar] (4) NULL,
[KKOWK] [nvarchar] (1) NULL,
[KORDB] [nvarchar] (1) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LAND1] [nvarchar] (3) NULL,
[LET01] [decimal] (3, 0) NULL,
[LET02] [decimal] (3, 0) NULL,
[LET03] [decimal] (3, 0) NULL,
[LIFNR] [nvarchar] (10) NULL,
[MANDT] [nvarchar] (3) NULL,
[MGVLAUPD] [nvarchar] (1) NULL,
[MGVUPD] [nvarchar] (1) NULL,
[MISCH] [nvarchar] (1) NULL,
[NAME1] [nvarchar] (30) NULL,
[NAME2] [nvarchar] (30) NULL,
[NODETYPE] [nvarchar] (3) NULL,
[NSCHEMA] [nvarchar] (4) NULL,
[ORT01] [nvarchar] (25) NULL,
[PFACH] [nvarchar] (10) NULL,
[PKOSA] [nvarchar] (1) NULL,
[PSTLZ] [nvarchar] (10) NULL,
[REGIO] [nvarchar] (3) NULL,
[SOURCING] [nvarchar] (1) NULL,
[SPART] [nvarchar] (2) NULL,
[SPRAS] [nvarchar] (1) NULL,
[STRAS] [nvarchar] (30) NULL,
[TAXIW] [nvarchar] (1) NULL,
[TXJCD] [nvarchar] (15) NULL,
[TXNAM_MA1] [nvarchar] (16) NULL,
[TXNAM_MA2] [nvarchar] (16) NULL,
[TXNAM_MA3] [nvarchar] (16) NULL,
[VKORG] [nvarchar] (4) NULL,
[VLFKZ] [nvarchar] (1) NULL,
[VSTEL] [nvarchar] (4) NULL,
[VTBFI] [nvarchar] (2) NULL,
[VTWEG] [nvarchar] (2) NULL,
[WERKS] [nvarchar] (4) NULL,
[WKSOP] [nvarchar] (1) NULL,
[ZONE1] [nvarchar] (10) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_SAP_SVK_T001W_1] ON [tsa].[ics_land_SAP_SVK_T001W] ([MANDT], [WERKS])
GO
