CREATE TABLE [tsa].[ics_land_Navision_BGR_Purchase_Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Purchase_Line_ExcludedFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Purchase_Line_IsDuplicate] DEFAULT ((0)),
[timestamp] [varbinary] (8) NULL,
[Document Type] [int] NOT NULL,
[Document No_] [varchar] (20) NOT NULL,
[Line No_] [int] NOT NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Location Code] [varchar] (10) NULL,
[Posting Group] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Outstanding Quantity] [decimal] (38, 20) NULL,
[Qty_ to Invoice] [decimal] (38, 20) NULL,
[Qty_ to Receive] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[VAT %] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Allow Invoice Disc_] [tinyint] NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Job No_] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Outstanding Amount] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Quantity Received] [decimal] (38, 20) NULL,
[Quantity Invoiced] [decimal] (38, 20) NULL,
[Receipt No_] [varchar] (20) NULL,
[Receipt Line No_] [int] NULL,
[Profit %] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Sales Order No_] [varchar] (20) NULL,
[Sales Order Line No_] [int] NULL,
[Drop Shipment] [tinyint] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Entry Point] [varchar] (10) NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Tax Group Code] [varchar] (10) NULL,
[Use Tax] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Outstanding Amount (LCY)] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced (LCY)] [decimal] (38, 20) NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[System-Created Entry] [tinyint] NULL,
[Line Amount] [decimal] (38, 20) NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[Inv_ Disc_ Amount to Invoice] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Prepmt_ Line Amount] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Inv_] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Incl_ VAT] [decimal] (38, 20) NULL,
[Prepayment Amount] [decimal] (38, 20) NULL,
[Prepmt_ VAT Base Amt_] [decimal] (38, 20) NULL,
[Prepayment VAT %] [decimal] (38, 20) NULL,
[Prepmt_ VAT Calc_ Type] [int] NULL,
[Prepayment VAT Identifier] [varchar] (10) NULL,
[Prepayment Tax Area Code] [varchar] (20) NULL,
[Prepayment Tax Liable] [tinyint] NULL,
[Prepayment Tax Group Code] [varchar] (10) NULL,
[Prepmt Amt to Deduct] [decimal] (38, 20) NULL,
[Prepmt Amt Deducted] [decimal] (38, 20) NULL,
[Prepayment Line] [tinyint] NULL,
[Prepmt_ Amount Inv_ Incl_ VAT] [decimal] (38, 20) NULL,
[IC Partner Code] [varchar] (20) NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Line Type] [int] NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[Bin Code] [varchar] (20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Outstanding Qty_ (Base)] [decimal] (38, 20) NULL,
[Qty_ to Invoice (Base)] [decimal] (38, 20) NULL,
[Qty_ to Receive (Base)] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced (Base)] [decimal] (38, 20) NULL,
[Qty_ Received (Base)] [decimal] (38, 20) NULL,
[Qty_ Invoiced (Base)] [decimal] (38, 20) NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Maintenance Code] [varchar] (10) NULL,
[Insurance No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Use Duplication List] [tinyint] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Item Category Code] [varchar] (10) NULL,
[Nonstock] [tinyint] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Product Group Code] [varchar] (10) NULL,
[Special Order] [tinyint] NULL,
[Special Order Sales No_] [varchar] (20) NULL,
[Special Order Sales Line No_] [int] NULL,
[Completely Received] [tinyint] NULL,
[Requested Receipt Date] [datetime] NULL,
[Promised Receipt Date] [datetime] NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Planned Receipt Date] [datetime] NULL,
[Order Date] [datetime] NULL,
[Allow Item Charge Assignment] [tinyint] NULL,
[Return Qty_ to Ship] [decimal] (38, 20) NULL,
[Return Qty_ to Ship (Base)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped Not Invd_] [decimal] (38, 20) NULL,
[Ret_ Qty_ Shpd Not Invd_(Base)] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_ (LCY)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped] [decimal] (38, 20) NULL,
[Return Qty_ Shipped (Base)] [decimal] (38, 20) NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shipment Line No_] [int] NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Operation No_] [varchar] (10) NULL,
[Work Center No_] [varchar] (20) NULL,
[Finished] [tinyint] NULL,
[Prod_ Order Line No_] [int] NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[MPS Order] [tinyint] NULL,
[Planning Flexibility] [int] NULL,
[Safety Lead Time] [varchar] (32) NULL,
[Routing Reference No_] [int] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_BGR_Purchase_Line] ON [tsa].[ics_land_Navision_BGR_Purchase_Line] ([Document Type], [Document No_], [Line No_])
GO
