CREATE TABLE [tsa].[ics_land_M3V10gen_POL_MITAUN]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_MITAUN_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_MITAUN_IsDuplicate] DEFAULT ((0)),
[MUALUN] [nchar] (3) NULL,
[MUAUS1] [numeric] (1, 0) NULL,
[MUAUS2] [numeric] (1, 0) NULL,
[MUAUS3] [numeric] (1, 0) NULL,
[MUAUS4] [numeric] (1, 0) NULL,
[MUAUS5] [numeric] (1, 0) NULL,
[MUAUS6] [numeric] (1, 0) NULL,
[MUAUS9] [numeric] (1, 0) NULL,
[MUAUSB] [numeric] (1, 0) NULL,
[MUAUSC] [numeric] (1, 0) NULL,
[MUAUTP] [numeric] (1, 0) NULL,
[MUCHID] [nchar] (10) NULL,
[MUCHNO] [numeric] (3, 0) NULL,
[MUCOFA] [numeric] (15, 9) NULL,
[MUCONO] [numeric] (3, 0) NULL,
[MUDCCD] [numeric] (1, 0) NULL,
[MUDMCF] [numeric] (1, 0) NULL,
[MUFMID] [nchar] (5) NULL,
[MUITNO] [nchar] (15) NULL,
[MULMDT] [numeric] (8, 0) NULL,
[MULMTS] [numeric] (18, 0) NULL,
[MUPACT] [nchar] (6) NULL,
[MUPCOF] [numeric] (15, 9) NULL,
[MURESI] [nchar] (5) NULL,
[MURGDT] [numeric] (8, 0) NULL,
[MURGTM] [numeric] (6, 0) NULL,
[MUTXID] [numeric] (13, 0) NULL,
[MUUNMU] [numeric] (15, 6) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_MITAUN_1] ON [tsa].[ics_land_M3V10gen_POL_MITAUN] ([MUALUN], [MUAUTP], [MUCONO], [MUITNO])
GO
