CREATE TABLE [tsa].[ICS_LAND_SAP_GBR_T001]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[BUKRS] [nvarchar] (4) NULL,
[BUTXT] [nvarchar] (25) NULL,
[ORT01] [nvarchar] (25) NULL,
[LAND1] [nvarchar] (3) NULL,
[WAERS] [nvarchar] (5) NULL,
[SPRAS] [nvarchar] (1) NULL,
[KTOPL] [nvarchar] (4) NULL,
[WAABW] [nvarchar] (2) NULL,
[PERIV] [nvarchar] (2) NULL,
[KOKFI] [nvarchar] (1) NULL,
[RCOMP] [nvarchar] (6) NULL,
[ADRNR] [nvarchar] (10) NULL,
[STCEG] [nvarchar] (20) NULL,
[FIKRS] [nvarchar] (4) NULL,
[XFMCO] [nvarchar] (1) NULL,
[XFMCB] [nvarchar] (1) NULL,
[XFMCA] [nvarchar] (1) NULL,
[TXJCD] [nvarchar] (15) NULL,
[FMHRDATE] [datetime] NULL,
[BUVAR] [nvarchar] (1) NULL,
[FDBUK] [nvarchar] (4) NULL,
[XFDIS] [nvarchar] (1) NULL,
[XVALV] [nvarchar] (1) NULL,
[XSKFN] [nvarchar] (1) NULL,
[KKBER] [nvarchar] (4) NULL,
[XMWSN] [nvarchar] (1) NULL,
[MREGL] [nvarchar] (4) NULL,
[XGSBE] [nvarchar] (1) NULL,
[XGJRV] [nvarchar] (1) NULL,
[XKDFT] [nvarchar] (1) NULL,
[XPROD] [nvarchar] (1) NULL,
[XEINK] [nvarchar] (1) NULL,
[XJVAA] [nvarchar] (1) NULL,
[XVVWA] [nvarchar] (1) NULL,
[XSLTA] [nvarchar] (1) NULL,
[XFDMM] [nvarchar] (1) NULL,
[XFDSD] [nvarchar] (1) NULL,
[XEXTB] [nvarchar] (1) NULL,
[EBUKR] [nvarchar] (4) NULL,
[KTOP2] [nvarchar] (4) NULL,
[UMKRS] [nvarchar] (4) NULL,
[BUKRS_GLOB] [nvarchar] (6) NULL,
[FSTVA] [nvarchar] (4) NULL,
[OPVAR] [nvarchar] (4) NULL,
[XCOVR] [nvarchar] (1) NULL,
[TXKRS] [nvarchar] (1) NULL,
[WFVAR] [nvarchar] (4) NULL,
[XBBBF] [nvarchar] (1) NULL,
[XBBBE] [nvarchar] (1) NULL,
[XBBBA] [nvarchar] (1) NULL,
[XBBKO] [nvarchar] (1) NULL,
[XSTDT] [nvarchar] (1) NULL,
[MWSKV] [nvarchar] (2) NULL,
[MWSKA] [nvarchar] (2) NULL,
[IMPDA] [nvarchar] (1) NULL,
[XNEGP] [nvarchar] (1) NULL,
[XKKBI] [nvarchar] (1) NULL,
[WT_NEWWT] [nvarchar] (1) NULL,
[PP_PDATE] [nvarchar] (1) NULL,
[INFMT] [nvarchar] (4) NULL,
[FSTVARE] [nvarchar] (4) NULL,
[KOPIM] [nvarchar] (1) NULL,
[DKWEG] [nvarchar] (1) NULL,
[OFFSACCT] [nvarchar] (1) NULL,
[BAPOVAR] [nvarchar] (2) NULL,
[XCOS] [nvarchar] (1) NULL,
[XCESSION] [nvarchar] (1) NULL,
[XSPLT] [nvarchar] (1) NULL,
[SURCCM] [nvarchar] (1) NULL,
[DTPROV] [nvarchar] (2) NULL,
[DTAMTC] [nvarchar] (2) NULL,
[DTTAXC] [nvarchar] (2) NULL,
[DTTDSP] [nvarchar] (2) NULL,
[DTAXR] [nvarchar] (4) NULL,
[XVATDATE] [nvarchar] (1) NULL,
[PST_PER_VAR] [nvarchar] (1) NULL,
[FM_DERIVE_ACC] [nvarchar] (1) NULL,
[EtlSourceTable] [varchar] (200) NOT NULL
)
GO
