CREATE TABLE [tsa].[ics_land_SAP_SVK_EKBZ]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKBZ_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKBZ_IsDuplicate] DEFAULT ((0)),
[AREWB] [decimal] (13, 2) NULL,
[AREWR] [decimal] (13, 2) NULL,
[AREWW] [decimal] (13, 2) NULL,
[BELNR] [nvarchar] (10) NULL,
[BEWTP] [nvarchar] (1) NULL,
[BPMNG] [decimal] (13, 3) NULL,
[BUDAT] [nvarchar] (8) NULL,
[BUZEI] [nvarchar] (4) NULL,
[BWTAR] [nvarchar] (10) NULL,
[CPUDT] [nvarchar] (8) NULL,
[CPUTM] [nvarchar] (6) NULL,
[DMBTR] [decimal] (13, 2) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[ERNAM] [nvarchar] (12) NULL,
[FRBNR] [nvarchar] (16) NULL,
[GJAHR] [nvarchar] (4) NULL,
[HSWAE] [nvarchar] (5) NULL,
[KSCHL] [nvarchar] (4) NULL,
[LIFNR] [nvarchar] (10) NULL,
[MANDT] [nvarchar] (3) NULL,
[MENGE] [decimal] (13, 3) NULL,
[REEWR] [decimal] (13, 2) NULL,
[REFWR] [decimal] (13, 2) NULL,
[REWRB] [decimal] (13, 2) NULL,
[SAPRL] [nvarchar] (4) NULL,
[SHKKO] [nvarchar] (1) NULL,
[SHKZG] [nvarchar] (1) NULL,
[STUNR] [nvarchar] (3) NULL,
[VGABE] [nvarchar] (1) NULL,
[VNETW] [decimal] (13, 2) NULL,
[WAERS] [nvarchar] (5) NULL,
[WRBTR] [decimal] (13, 2) NULL,
[XBLNR] [nvarchar] (16) NULL,
[ZAEHK] [nvarchar] (2) NULL
)
GO
