CREATE TABLE [tsa].[ics_land_M3V10vil_POL_MITBAL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF__ics_land___Exclu__39AE55D6] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF__ics_land___IsDup__3AA27A0F] DEFAULT ((0)),
[MBABCD] [nchar] (1) NULL,
[MBABCM] [numeric] (18, 0) NULL,
[MBABFC] [nchar] (1) NULL,
[MBABFM] [numeric] (18, 0) NULL,
[MBACOC] [nchar] (1) NULL,
[MBACOM] [numeric] (18, 0) NULL,
[MBAGDY] [numeric] (18, 0) NULL,
[MBAGHO] [numeric] (18, 0) NULL,
[MBALMT] [numeric] (18, 0) NULL,
[MBALQC] [numeric] (18, 0) NULL,
[MBALQT] [numeric] (18, 0) NULL,
[MBALS1] [numeric] (18, 0) NULL,
[MBALUN] [nchar] (3) NULL,
[MBAVAL] [numeric] (18, 0) NULL,
[MBAVST] [numeric] (18, 0) NULL,
[MBBALO] [numeric] (18, 0) NULL,
[MBBCOS] [numeric] (18, 0) NULL,
[MBBUYE] [nchar] (10) NULL,
[MBCDYN] [numeric] (18, 0) NULL,
[MBCHID] [nchar] (10) NULL,
[MBCHNO] [numeric] (18, 0) NULL,
[MBCOMG] [numeric] (18, 0) NULL,
[MBCONC] [numeric] (18, 0) NULL,
[MBCONO] [numeric] (18, 0) NULL,
[MBCPCD] [nchar] (3) NULL,
[MBDCSS] [numeric] (18, 0) NULL,
[MBDDEX] [numeric] (18, 0) NULL,
[MBDDLO] [nchar] (10) NULL,
[MBDIGR] [nchar] (2) NULL,
[MBDILE] [numeric] (18, 0) NULL,
[MBDIVI] [nchar] (3) NULL,
[MBDMFN] [numeric] (18, 0) NULL,
[MBDPID] [numeric] (18, 0) NULL,
[MBDPLO] [nchar] (10) NULL,
[MBDTID] [numeric] (18, 0) NULL,
[MBEOQM] [numeric] (18, 0) NULL,
[MBEOQT] [numeric] (18, 0) NULL,
[MBEQDA] [numeric] (18, 0) NULL,
[MBFACI] [nchar] (3) NULL,
[MBFCCM] [nchar] (2) NULL,
[MBGRTS] [nchar] (5) NULL,
[MBIDDT] [numeric] (18, 0) NULL,
[MBINCD] [nchar] (3) NULL,
[MBINDT] [numeric] (18, 0) NULL,
[MBINSC] [numeric] (18, 0) NULL,
[MBINSL] [nchar] (10) NULL,
[MBITNO] [nchar] (15) NULL,
[MBKTEX] [numeric] (18, 0) NULL,
[MBLEA1] [numeric] (18, 0) NULL,
[MBLEA2] [numeric] (18, 0) NULL,
[MBLEA3] [numeric] (18, 0) NULL,
[MBLEAQ] [numeric] (18, 0) NULL,
[MBLEAT] [numeric] (18, 0) NULL,
[MBLEVD] [numeric] (18, 0) NULL,
[MBLEVL] [numeric] (18, 0) NULL,
[MBLMDT] [numeric] (18, 0) NULL,
[MBLMTS] [numeric] (18, 0) NULL,
[MBLOQT] [numeric] (18, 0) NULL,
[MBLRYE] [numeric] (18, 0) NULL,
[MBLYQT] [numeric] (18, 0) NULL,
[MBMABC] [nchar] (1) NULL,
[MBMNUN] [nchar] (3) NULL,
[MBMOQT] [numeric] (18, 0) NULL,
[MBMPCD] [numeric] (18, 0) NULL,
[MBMPCT] [numeric] (18, 0) NULL,
[MBMRPQ] [numeric] (18, 0) NULL,
[MBMRQT] [numeric] (18, 0) NULL,
[MBMSCH] [numeric] (18, 0) NULL,
[MBMSSQ] [numeric] (18, 0) NULL,
[MBMXPC] [numeric] (18, 0) NULL,
[MBMXSM] [numeric] (18, 0) NULL,
[MBMXST] [numeric] (18, 0) NULL,
[MBNCCA] [numeric] (18, 0) NULL,
[MBNUIN] [numeric] (18, 0) NULL,
[MBNUS7] [numeric] (18, 0) NULL,
[MBODDT] [numeric] (18, 0) NULL,
[MBOPLC] [numeric] (18, 0) NULL,
[MBOPOM] [numeric] (18, 0) NULL,
[MBORQT] [numeric] (18, 0) NULL,
[MBORTY] [nchar] (3) NULL,
[MBPAFL] [numeric] (18, 0) NULL,
[MBPFTM] [numeric] (18, 0) NULL,
[MBPISE] [nchar] (2) NULL,
[MBPLCD] [nchar] (2) NULL,
[MBPLHZ] [numeric] (18, 0) NULL,
[MBPLIC] [numeric] (18, 0) NULL,
[MBPLID] [numeric] (18, 0) NULL,
[MBPLIT] [numeric] (18, 0) NULL,
[MBPLNT] [nchar] (3) NULL,
[MBPLQT] [numeric] (18, 0) NULL,
[MBPOOT] [nchar] (3) NULL,
[MBPPMC] [numeric] (18, 0) NULL,
[MBPRCD] [nchar] (2) NULL,
[MBPRDC] [numeric] (18, 0) NULL,
[MBPRIF] [numeric] (18, 0) NULL,
[MBPUIT] [numeric] (18, 0) NULL,
[MBQUCW] [numeric] (18, 0) NULL,
[MBQUQT] [numeric] (18, 0) NULL,
[MBREDY] [numeric] (18, 0) NULL,
[MBREOP] [numeric] (18, 0) NULL,
[MBREQP] [numeric] (18, 0) NULL,
[MBREQT] [numeric] (18, 0) NULL,
[MBRESP] [nchar] (10) NULL,
[MBRGDT] [numeric] (18, 0) NULL,
[MBRGTM] [numeric] (18, 0) NULL,
[MBRJCW] [numeric] (18, 0) NULL,
[MBRJQT] [numeric] (18, 0) NULL,
[MBRLQT] [numeric] (18, 0) NULL,
[MBRPOP] [numeric] (18, 0) NULL,
[MBSAEL] [numeric] (18, 0) NULL,
[MBSALM] [numeric] (18, 0) NULL,
[MBSATD] [numeric] (18, 0) NULL,
[MBSCGR] [numeric] (18, 0) NULL,
[MBSCHT] [numeric] (18, 0) NULL,
[MBSCPO] [nchar] (3) NULL,
[MBSESO] [numeric] (18, 0) NULL,
[MBSHCC] [numeric] (18, 0) NULL,
[MBSLDY] [numeric] (18, 0) NULL,
[MBSLTP] [nchar] (2) NULL,
[MBSODY] [numeric] (18, 0) NULL,
[MBSPLC] [nchar] (2) NULL,
[MBSPMT] [numeric] (18, 0) NULL,
[MBSSDA] [numeric] (18, 0) NULL,
[MBSSMT] [numeric] (18, 0) NULL,
[MBSSQT] [numeric] (18, 0) NULL,
[MBSTAT] [nchar] (2) NULL,
[MBSTCW] [numeric] (18, 0) NULL,
[MBSTMT] [numeric] (18, 0) NULL,
[MBSTQT] [numeric] (18, 0) NULL,
[MBSTRL] [numeric] (18, 0) NULL,
[MBSTTX] [nvarchar] (30) NULL,
[MBSUNO] [nchar] (10) NULL,
[MBSUWH] [nchar] (3) NULL,
[MBSVEI] [numeric] (18, 0) NULL,
[MBTOMU] [numeric] (18, 0) NULL,
[MBTXID] [numeric] (18, 0) NULL,
[MBUNMU] [numeric] (18, 0) NULL,
[MBUSYE] [numeric] (18, 0) NULL,
[MBVTCP] [numeric] (18, 0) NULL,
[MBVTCS] [numeric] (18, 0) NULL,
[MBWHLO] [nchar] (3) NULL,
[MBWHLT] [nchar] (2) NULL,
[MBWHSL] [nchar] (10) NULL,
[MBWHSY] [nchar] (1) NULL,
[MBWHTY] [nchar] (2) NULL,
[MBYEQM] [numeric] (18, 0) NULL,
[MBYEQT] [numeric] (18, 0) NULL,
[MBZCAC] [numeric] (18, 0) NULL
)
GO
