CREATE TABLE [tsa].[ics_land_Symfonia_ARM_SalesInvoiceTrans]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_ARM_SalesInvoiceTrans_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_ARM_SalesInvoiceTrans_IsDuplicate] DEFAULT ((0)),
[Bonus] [varchar] (1) NULL,
[Custom1] [varchar] (1) NULL,
[Custom2] [varchar] (1) NULL,
[DeliveryTermID] [varchar] (1) NULL,
[DeliveryTermText] [varchar] (1) NULL,
[Discount] [varchar] (1) NULL,
[FreightCost] [varchar] (1) NULL,
[id] [int] NULL,
[Idline] [int] NULL,
[InvAmount] [float] NULL,
[InvCurrAmount] [float] NULL,
[InvCurrency] [varchar] (3) NULL,
[InvDate] [datetime] NULL,
[InvLineAmountLoc] [float] NULL,
[invlinenr] [smallint] NULL,
[InvNum] [varchar] (40) NULL,
[InvoiceLineType] [varchar] (1) NULL,
[InvoiceShipTo] [varchar] (4) NULL,
[InvoiceSoldTo] [varchar] (4) NULL,
[InvUOM] [varchar] (8) NULL,
[ItemNo] [varchar] (40) NULL,
[ItemQty] [float] NULL,
[LocalCurrencyCode] [varchar] (3) NULL,
[MatCharName1] [varchar] (1) NULL,
[MatCharName2] [varchar] (1) NULL,
[MatCharName3] [varchar] (1) NULL,
[MatCharName4] [varchar] (1) NULL,
[MatCharName5] [varchar] (1) NULL,
[MatCharValue1] [varchar] (1) NULL,
[MatCharValue2] [varchar] (1) NULL,
[MatCharValue3] [varchar] (1) NULL,
[MatCharValue4] [varchar] (1) NULL,
[MatCharValue5] [varchar] (1) NULL,
[OrderLineNr] [smallint] NULL,
[OrderNr] [varchar] (80) NULL,
[PaymentTermText] [varchar] (7) NULL,
[SalesPersonId] [int] NULL,
[SalesPersonName] [nvarchar] (128) NULL,
[StatisicalQty] [float] NULL,
[StatisticalUOM] [varchar] (8) NULL,
[StdCost] [float] NULL,
[SysID] [int] NULL,
[TermOfPaymentID] [int] NULL
)
GO
