CREATE TABLE [tsa].[ics_land_SAP_SVK_EKKO]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKKO_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKKO_IsDuplicate] DEFAULT ((0)),
[ABGRU] [nvarchar] (2) NULL,
[ABSGR] [nvarchar] (2) NULL,
[ADDNR] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[AEDAT] [nvarchar] (8) NULL,
[AMN] [nvarchar] (3) NULL,
[ANGDT] [nvarchar] (8) NULL,
[ANGNR] [nvarchar] (10) NULL,
[AUSNR] [nvarchar] (10) NULL,
[AUTLF] [nvarchar] (1) NULL,
[BEDAT] [nvarchar] (8) NULL,
[BNDDT] [nvarchar] (8) NULL,
[BSAKZ] [nvarchar] (1) NULL,
[BSART] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[BUKRS] [nvarchar] (4) NULL,
[BWBDT] [nvarchar] (8) NULL,
[CUR] [nvarchar] (3) NULL,
[DNO] [nvarchar] (12) NULL,
[DPT] [nvarchar] (15) NULL,
[EBELN] [nvarchar] (10) NULL,
[ECC] [nvarchar] (7) NULL,
[ECO] [nvarchar] (13) NULL,
[EKGRP] [nvarchar] (3) NULL,
[EKORG] [nvarchar] (4) NULL,
[ERNAM] [nvarchar] (12) NULL,
[EXNUM] [nvarchar] (10) NULL,
[FRGGR] [nvarchar] (2) NULL,
[FRGKE] [nvarchar] (1) NULL,
[FRGRL] [nvarchar] (1) NULL,
[FRGSX] [nvarchar] (2) NULL,
[FRGZU] [nvarchar] (8) NULL,
[GWLDT] [nvarchar] (8) NULL,
[IHRAN] [nvarchar] (8) NULL,
[IHREZ] [nvarchar] (12) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[IPP] [nvarchar] (9) NULL,
[KALSM] [nvarchar] (6) NULL,
[KDATB] [nvarchar] (8) NULL,
[KDATE] [nvarchar] (8) NULL,
[KNUMV] [nvarchar] (10) NULL,
[KONNR] [nvarchar] (10) NULL,
[KORNR] [nvarchar] (1) NULL,
[KTWRT] [decimal] (15, 2) NULL,
[KUFIX] [nvarchar] (1) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LANDS] [nvarchar] (3) NULL,
[LBLIF] [nvarchar] (10) NULL,
[LIFNR] [nvarchar] (10) NULL,
[LIFRE] [nvarchar] (10) NULL,
[LLIEF] [nvarchar] (10) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[LOGSY] [nvarchar] (10) NULL,
[LPHIS] [nvarchar] (1) NULL,
[LPONR] [nvarchar] (5) NULL,
[MANDT] [nvarchar] (3) NULL,
[MEMORY] [nvarchar] (1) NULL,
[PBN] [nvarchar] (14) NULL,
[PCD] [nvarchar] (2) NULL,
[PCN] [nvarchar] (16) NULL,
[PCO] [nvarchar] (3) NULL,
[PCY] [nvarchar] (3) NULL,
[PINCR] [nvarchar] (5) NULL,
[PLC] [nvarchar] (1) NULL,
[POSTAT] [nvarchar] (1) NULL,
[PROCSTAT] [nvarchar] (2) NULL,
[RESWK] [nvarchar] (4) NULL,
[REVNO] [nvarchar] (8) NULL,
[RLWRT] [decimal] (15, 2) NULL,
[SMB] [nvarchar] (6) NULL,
[SPRAS] [nvarchar] (1) NULL,
[STAFO] [nvarchar] (6) NULL,
[STAKO] [nvarchar] (1) NULL,
[STATU] [nvarchar] (1) NULL,
[STCEG] [nvarchar] (20) NULL,
[STCEG_L] [nvarchar] (3) NULL,
[SUBMI] [nvarchar] (10) NULL,
[SUS] [nvarchar] (5) NULL,
[TELF1] [nvarchar] (16) NULL,
[TOP] [nvarchar] (2) NULL,
[TRU] [nvarchar] (20) NULL,
[UNSEZ] [nvarchar] (12) NULL,
[UPINC] [nvarchar] (5) NULL,
[VERKF] [nvarchar] (30) NULL,
[WAERS] [nvarchar] (5) NULL,
[WEAKT] [nvarchar] (1) NULL,
[WKURS] [decimal] (9, 5) NULL,
[ZBD1P] [decimal] (5, 3) NULL,
[ZBD1T] [decimal] (3, 0) NULL,
[ZBD2P] [decimal] (5, 3) NULL,
[ZBD2T] [decimal] (3, 0) NULL,
[ZBD3T] [decimal] (3, 0) NULL,
[ZTERM] [nvarchar] (4) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_SAP_SVK_EKKO_1] ON [tsa].[ics_land_SAP_SVK_EKKO] ([EBELN])
GO
