CREATE TABLE [tsa].[ics_land_movex_FPLEDG]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_movex_FPLEDG_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_movex_FPLEDG_IsDuplicate] DEFAULT ((0)),
[EPCONO] [decimal] (3, 0) NULL,
[EPDIVI] [nvarchar] (3) NULL,
[EPYEA4] [decimal] (4, 0) NULL,
[EPJRNO] [decimal] (7, 0) NULL,
[EPJSNO] [decimal] (7, 0) NULL,
[EPTRCD] [decimal] (2, 0) NULL,
[EPSPYN] [nvarchar] (10) NULL,
[EPSUNO] [nvarchar] (10) NULL,
[EPSINO] [nvarchar] (24) NULL,
[EPINYR] [decimal] (4, 0) NULL,
[EPVSER] [nvarchar] (3) NULL,
[EPVONO] [decimal] (8, 0) NULL,
[EPIVTP] [nvarchar] (2) NULL,
[EPTDSC] [nvarchar] (10) NULL,
[EPAPCD] [nvarchar] (10) NULL,
[EPIVBL] [decimal] (1, 0) NULL,
[EPBLBY] [nvarchar] (10) NULL,
[EPBLDT] [decimal] (8, 0) NULL,
[EPAPRV] [decimal] (1, 0) NULL,
[EPSUCL] [nvarchar] (3) NULL,
[EPBKID] [nvarchar] (5) NULL,
[EPCUCD] [nvarchar] (3) NULL,
[EPCRTP] [decimal] (2, 0) NULL,
[EPARAT] [decimal] (11, 6) NULL,
[EPCUAM] [decimal] (15, 2) NULL,
[EPDCAM] [decimal] (1, 0) NULL,
[EPVTAM] [decimal] (15, 2) NULL,
[EPIVDT] [decimal] (8, 0) NULL,
[EPDUDT] [decimal] (8, 0) NULL,
[EPACDT] [decimal] (8, 0) NULL,
[EPTECD] [nvarchar] (3) NULL,
[EPPYTP] [nvarchar] (2) NULL,
[EPPYME] [nvarchar] (3) NULL,
[EPTEPY] [nvarchar] (3) NULL,
[EPRECO] [decimal] (1, 0) NULL,
[EPREDE] [decimal] (8, 0) NULL,
[EPSLOP] [decimal] (2, 0) NULL,
[EPPYST] [decimal] (1, 0) NULL,
[EPPYRS] [nvarchar] (2) NULL,
[EPARCD] [decimal] (1, 0) NULL,
[EPENME] [decimal] (1, 0) NULL,
[EPTXID] [decimal] (13, 0) NULL,
[EPTDCD] [nvarchar] (4) NULL,
[EPRGDT] [decimal] (8, 0) NULL,
[EPRGTM] [decimal] (6, 0) NULL,
[EPLMDT] [decimal] (8, 0) NULL,
[EPCHNO] [decimal] (3, 0) NULL,
[EPCHID] [nvarchar] (10) NULL
)
GO
