CREATE TABLE [tsa].[ics_land_SAP_GBR_RBKP]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_RBKP_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_RBKP_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[BELNR] [nvarchar] (10) NULL,
[GJAHR] [nvarchar] (4) NULL,
[BLART] [nvarchar] (2) NULL,
[BLDAT] [datetime] NULL,
[BUDAT] [datetime] NULL,
[USNAM] [nvarchar] (12) NULL,
[TCODE] [nvarchar] (20) NULL,
[CPUDT] [datetime] NULL,
[CPUTM] [datetime] NULL,
[VGART] [nvarchar] (2) NULL,
[XBLNR] [nvarchar] (16) NULL,
[BUKRS] [nvarchar] (4) NULL,
[LIFNR] [nvarchar] (10) NULL,
[WAERS] [nvarchar] (5) NULL,
[KURSF] [decimal] (9, 5) NULL,
[RMWWR] [decimal] (13, 2) NULL,
[BEZNK] [decimal] (13, 2) NULL,
[WMWST1] [decimal] (13, 2) NULL,
[MWSKZ1] [nvarchar] (2) NULL,
[WMWST2] [decimal] (13, 2) NULL,
[MWSKZ2] [nvarchar] (2) NULL,
[ZTERM] [nvarchar] (4) NULL,
[ZBD1T] [decimal] (3, 0) NULL,
[ZBD1P] [decimal] (5, 3) NULL,
[ZBD2T] [decimal] (3, 0) NULL,
[ZBD2P] [decimal] (5, 3) NULL,
[ZBD3T] [decimal] (3, 0) NULL,
[WSKTO] [decimal] (13, 2) NULL,
[XRECH] [nvarchar] (1) NULL,
[BKTXT] [nvarchar] (25) NULL,
[SAPRL] [nvarchar] (4) NULL,
[LOGSYS] [nvarchar] (10) NULL,
[XMWST] [nvarchar] (1) NULL,
[STBLG] [nvarchar] (10) NULL,
[STJAH] [nvarchar] (4) NULL,
[MWSKZ_BNK] [nvarchar] (2) NULL,
[TXJCD_BNK] [nvarchar] (15) NULL,
[IVTYP] [nvarchar] (1) NULL,
[XRBTX] [nvarchar] (1) NULL,
[REPART] [nvarchar] (1) NULL,
[RBSTAT] [nvarchar] (1) NULL,
[KNUMVE] [nvarchar] (10) NULL,
[KNUMVL] [nvarchar] (10) NULL,
[ARKUEN] [decimal] (13, 2) NULL,
[ARKUEMW] [decimal] (13, 2) NULL,
[MAKZN] [decimal] (13, 2) NULL,
[MAKZMW] [decimal] (13, 2) NULL,
[LIEFFN] [decimal] (13, 2) NULL,
[LIEFFMW] [decimal] (13, 2) NULL,
[XAUTAKZ] [nvarchar] (1) NULL,
[ESRNR] [nvarchar] (11) NULL,
[ESRPZ] [nvarchar] (2) NULL,
[ESRRE] [nvarchar] (27) NULL,
[QSSHB] [decimal] (13, 2) NULL,
[QSFBT] [decimal] (13, 2) NULL,
[QSSKZ] [nvarchar] (2) NULL,
[DIEKZ] [nvarchar] (1) NULL,
[LANDL] [nvarchar] (3) NULL,
[LZBKZ] [nvarchar] (3) NULL,
[TXKRS] [decimal] (9, 5) NULL,
[CTXKRS] [decimal] (9, 5) NULL,
[EMPFB] [nvarchar] (10) NULL,
[BVTYP] [nvarchar] (4) NULL,
[HBKID] [nvarchar] (5) NULL,
[ZUONR] [nvarchar] (18) NULL,
[ZLSPR] [nvarchar] (1) NULL,
[ZLSCH] [nvarchar] (1) NULL,
[ZFBDT] [datetime] NULL,
[KIDNO] [nvarchar] (30) NULL,
[REBZG] [nvarchar] (10) NULL,
[REBZJ] [nvarchar] (4) NULL,
[XINVE] [nvarchar] (1) NULL,
[EGMLD] [nvarchar] (3) NULL,
[XEGDR] [nvarchar] (1) NULL,
[VATDATE] [datetime] NULL,
[J_1BNFTYPE] [nvarchar] (2) NULL,
[BRNCH] [nvarchar] (4) NULL,
[ERFPR] [nvarchar] (12) NULL,
[SECCO] [nvarchar] (4) NULL,
[NAME1] [nvarchar] (35) NULL,
[NAME2] [nvarchar] (35) NULL,
[NAME3] [nvarchar] (35) NULL,
[NAME4] [nvarchar] (35) NULL,
[PSTLZ] [nvarchar] (10) NULL,
[ORT01] [nvarchar] (35) NULL,
[LAND1] [nvarchar] (3) NULL,
[STRAS] [nvarchar] (35) NULL,
[PFACH] [nvarchar] (10) NULL,
[PSTL2] [nvarchar] (10) NULL,
[PSKTO] [nvarchar] (16) NULL,
[BANKN] [nvarchar] (18) NULL,
[BANKL] [nvarchar] (15) NULL,
[BANKS] [nvarchar] (3) NULL,
[STCD1] [nvarchar] (16) NULL,
[STCD2] [nvarchar] (11) NULL,
[STKZU] [nvarchar] (1) NULL,
[STKZA] [nvarchar] (1) NULL,
[REGIO] [nvarchar] (3) NULL,
[BKONT] [nvarchar] (2) NULL,
[DTAWS] [nvarchar] (2) NULL,
[DTAMS] [nvarchar] (1) NULL,
[SPRAS] [nvarchar] (1) NULL,
[XCPDK] [nvarchar] (1) NULL,
[EMPFG] [nvarchar] (16) NULL,
[FITYP] [nvarchar] (2) NULL,
[STCDT] [nvarchar] (2) NULL,
[STKZN] [nvarchar] (1) NULL,
[STCD3] [nvarchar] (18) NULL,
[STCD4] [nvarchar] (18) NULL,
[BKREF] [nvarchar] (20) NULL,
[J_1KFREPRE] [nvarchar] (10) NULL,
[J_1KFTBUS] [nvarchar] (30) NULL,
[J_1KFTIND] [nvarchar] (30) NULL,
[ANRED] [nvarchar] (15) NULL,
[STCEG] [nvarchar] (20) NULL,
[ERNAME] [nvarchar] (12) NULL,
[REINDAT] [datetime] NULL,
[UZAWE] [nvarchar] (2) NULL,
[FDLEV] [nvarchar] (2) NULL,
[FDTAG] [datetime] NULL,
[ZBFIX] [nvarchar] (1) NULL,
[FRGKZ] [nvarchar] (1) NULL,
[ERFNAM] [nvarchar] (12) NULL,
[BUPLA] [nvarchar] (4) NULL,
[FILKD] [nvarchar] (10) NULL,
[GSBER] [nvarchar] (4) NULL,
[LOTKZ] [nvarchar] (10) NULL,
[SGTXT] [nvarchar] (50) NULL,
[PREPAY_STATUS] [nvarchar] (1) NULL,
[PREPAY_AWKEY] [nvarchar] (20) NULL,
[ASSIGN_STATUS] [nvarchar] (1) NULL,
[ASSIGN_NEXT_DATE] [datetime] NULL,
[ASSIGN_END_DATE] [datetime] NULL,
[COPY_BY_BELNR] [nvarchar] (10) NULL,
[COPY_BY_YEAR] [nvarchar] (4) NULL,
[COPY_TO_BELNR] [nvarchar] (10) NULL,
[COPY_TO_YEAR] [nvarchar] (4) NULL,
[COPY_USER] [nvarchar] (12) NULL,
[XREF3] [nvarchar] (20) NULL,
[J_1TPBUPL] [nvarchar] (5) NULL
)
GO
