CREATE TABLE [tsa].[ICS_LAND_SAP_GBR_KONH]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[KNUMH] [nvarchar] (10) NULL,
[ERNAM] [nvarchar] (12) NULL,
[ERDAT] [datetime] NULL,
[KVEWE] [nvarchar] (1) NULL,
[KOTABNR] [nvarchar] (3) NULL,
[KAPPL] [nvarchar] (2) NULL,
[KSCHL] [nvarchar] (4) NULL,
[VAKEY] [nvarchar] (100) NULL,
[DATAB] [datetime] NULL,
[DATBI] [datetime] NULL,
[KOSRT] [nvarchar] (10) NULL,
[KZUST] [nvarchar] (3) NULL,
[KNUMA_PI] [nvarchar] (10) NULL,
[KNUMA_AG] [nvarchar] (10) NULL,
[KNUMA_SQ] [nvarchar] (10) NULL,
[KNUMA_SD] [nvarchar] (10) NULL,
[AKTNR] [nvarchar] (10) NULL,
[KNUMA_BO] [nvarchar] (10) NULL,
[LICNO] [nvarchar] (20) NULL,
[LICDT] [datetime] NULL,
[VADAT] [nvarchar] (100) NULL,
[EtlSourceTable] [varchar] (200) NOT NULL
)
GO
