CREATE TABLE [tsa].[ics_land_SAP_SVK_LFM1]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_LFM1_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_LFM1_IsDuplicate] DEFAULT ((0)),
[ABUEB] [nvarchar] (4) NULL,
[AGREL] [nvarchar] (1) NULL,
[AUBEL] [nvarchar] (1) NULL,
[BLIND] [nvarchar] (1) NULL,
[BOIND] [nvarchar] (1) NULL,
[BOLRE] [nvarchar] (1) NULL,
[BOPNR] [nvarchar] (4) NULL,
[BSTAE] [nvarchar] (4) NULL,
[EIKTO] [nvarchar] (12) NULL,
[EKGRP] [nvarchar] (3) NULL,
[EKORG] [nvarchar] (4) NULL,
[ERDAT] [nvarchar] (8) NULL,
[ERNAM] [nvarchar] (12) NULL,
[EXPVZ] [nvarchar] (1) NULL,
[HSCABS] [decimal] (13, 2) NULL,
[HSCMAX] [decimal] (13, 2) NULL,
[HSCMIN] [decimal] (13, 2) NULL,
[HSCPE] [decimal] (5, 2) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[J_1NBOESL] [nvarchar] (3) NULL,
[KALSK] [nvarchar] (2) NULL,
[KZABS] [nvarchar] (1) NULL,
[KZAUT] [nvarchar] (1) NULL,
[KZRET] [nvarchar] (1) NULL,
[LEBRE] [nvarchar] (1) NULL,
[LFABC] [nvarchar] (1) NULL,
[LFRHY] [nvarchar] (3) NULL,
[LIBES] [nvarchar] (1) NULL,
[LIFNR] [nvarchar] (10) NULL,
[LIPRE] [nvarchar] (2) NULL,
[LISER] [nvarchar] (1) NULL,
[LOEVM] [nvarchar] (1) NULL,
[MANDT] [nvarchar] (3) NULL,
[MEGRU] [nvarchar] (4) NULL,
[MEPRF] [nvarchar] (1) NULL,
[MINBW] [decimal] (13, 2) NULL,
[MRPPP] [nvarchar] (3) NULL,
[NRGEW] [nvarchar] (1) NULL,
[PAPRF] [nvarchar] (4) NULL,
[PLIFZ] [decimal] (3, 0) NULL,
[PRFRE] [nvarchar] (1) NULL,
[RDPRF] [nvarchar] (4) NULL,
[SKRIT] [nvarchar] (1) NULL,
[SPERM] [nvarchar] (1) NULL,
[TELF1] [nvarchar] (16) NULL,
[UMSAE] [nvarchar] (1) NULL,
[UPPRS] [nvarchar] (1) NULL,
[VALID_PRO] [nvarchar] (4) NULL,
[VENSL] [decimal] (4, 1) NULL,
[VERKF] [nvarchar] (30) NULL,
[VSBED] [nvarchar] (2) NULL,
[WAERS] [nvarchar] (5) NULL,
[WEBRE] [nvarchar] (1) NULL,
[XERSR] [nvarchar] (1) NULL,
[XERSY] [nvarchar] (1) NULL,
[XNBWY] [nvarchar] (1) NULL,
[ZOLLA] [nvarchar] (6) NULL,
[ZTERM] [nvarchar] (4) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_SAP_SVK_LFM1_1] ON [tsa].[ics_land_SAP_SVK_LFM1] ([EKORG], [LIFNR], [MANDT])
GO
