CREATE TABLE [tsa].[ics_land_SAP_SVK_EKPO]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKPO_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKPO_IsDuplicate] DEFAULT ((0)),
[_SAPMP_GPOSE] [nvarchar] (5) NULL,
[ABDAT] [nvarchar] (8) NULL,
[ABELN] [nvarchar] (10) NULL,
[ABELP] [nvarchar] (5) NULL,
[ABFTZ] [decimal] (13, 3) NULL,
[ABMNG] [decimal] (13, 3) NULL,
[ABSKZ] [nvarchar] (1) NULL,
[ABUEB] [nvarchar] (4) NULL,
[ADACN] [nvarchar] (5) NULL,
[ADDRNUM] [nvarchar] (10) NULL,
[ADMOI] [nvarchar] (4) NULL,
[ADPRI] [nvarchar] (3) NULL,
[ADRN2] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[AEDAT] [nvarchar] (8) NULL,
[AFNAM] [nvarchar] (12) NULL,
[AFPNR] [nvarchar] (6) NULL,
[AGDAT] [nvarchar] (8) NULL,
[AGMEM] [nvarchar] (3) NULL,
[AKTNR] [nvarchar] (10) NULL,
[ANFNR] [nvarchar] (10) NULL,
[ANFPS] [nvarchar] (5) NULL,
[ANGNR] [nvarchar] (20) NULL,
[ANGPN] [nvarchar] (6) NULL,
[ANZPU] [decimal] (13, 3) NULL,
[ANZSN] [decimal] (10, 0) NULL,
[APOMS] [nvarchar] (1) NULL,
[ARSNR] [nvarchar] (10) NULL,
[ARSPS] [nvarchar] (4) NULL,
[ATTYP] [nvarchar] (2) NULL,
[AUDAT] [nvarchar] (8) NULL,
[AUREL] [nvarchar] (1) NULL,
[BANFN] [nvarchar] (10) NULL,
[BEDNR] [nvarchar] (10) NULL,
[BERID] [nvarchar] (10) NULL,
[BNFPO] [nvarchar] (5) NULL,
[BONBA] [decimal] (13, 2) NULL,
[BONUS] [nvarchar] (2) NULL,
[BORGR_MISS] [nvarchar] (1) NULL,
[BPRME] [nvarchar] (3) NULL,
[BPUMN] [decimal] (5, 0) NULL,
[BPUMZ] [decimal] (5, 0) NULL,
[BRGEW] [decimal] (13, 3) NULL,
[BRTWR] [decimal] (13, 2) NULL,
[BSARK] [nvarchar] (4) NULL,
[BSGRU] [nvarchar] (3) NULL,
[BSTAE] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[BUKRS] [nvarchar] (4) NULL,
[BWTAR] [nvarchar] (10) NULL,
[BWTTY] [nvarchar] (1) NULL,
[CCOMP] [nvarchar] (1) NULL,
[CHG_FPLNR] [nvarchar] (1) NULL,
[CHG_SRV] [nvarchar] (1) NULL,
[CONSNUM] [nvarchar] (3) NULL,
[CUOBJ] [nvarchar] (18) NULL,
[DISUB_KUNNR] [nvarchar] (10) NULL,
[DISUB_OWNER] [nvarchar] (10) NULL,
[DISUB_POSNR] [nvarchar] (6) NULL,
[DISUB_PSPNR] [nvarchar] (8) NULL,
[DISUB_SOBKZ] [nvarchar] (1) NULL,
[DISUB_VBELN] [nvarchar] (10) NULL,
[DRDAT] [nvarchar] (8) NULL,
[DRUHR] [nvarchar] (6) NULL,
[DRUNR] [nvarchar] (4) NULL,
[EAN11] [nvarchar] (18) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[EBON2] [nvarchar] (2) NULL,
[EBON3] [nvarchar] (2) NULL,
[EBONF] [nvarchar] (1) NULL,
[EFFWR] [decimal] (13, 2) NULL,
[EGLKZ] [nvarchar] (1) NULL,
[EILDT] [nvarchar] (8) NULL,
[EKKOL] [nvarchar] (4) NULL,
[ELIKZ] [nvarchar] (1) NULL,
[EMATN] [nvarchar] (18) NULL,
[EMLIF] [nvarchar] (10) NULL,
[EMNFR] [nvarchar] (10) NULL,
[EREKZ] [nvarchar] (1) NULL,
[ETDRK] [nvarchar] (1) NULL,
[ETFZ1] [decimal] (3, 0) NULL,
[ETFZ2] [decimal] (3, 0) NULL,
[EVERS] [nvarchar] (2) NULL,
[EXCPE] [nvarchar] (2) NULL,
[FABKZ] [nvarchar] (1) NULL,
[FFZHI] [decimal] (15, 3) NULL,
[FIPOS] [nvarchar] (14) NULL,
[FISTL] [nvarchar] (16) NULL,
[FKBER] [nvarchar] (16) NULL,
[FPLNR] [nvarchar] (10) NULL,
[GEBER] [nvarchar] (10) NULL,
[GEWEI] [nvarchar] (3) NULL,
[GNETWR] [decimal] (13, 2) NULL,
[GRANT_NBR] [nvarchar] (20) NULL,
[IDNLF] [nvarchar] (35) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[INFNR] [nvarchar] (10) NULL,
[INSMK] [nvarchar] (1) NULL,
[INSNC] [nvarchar] (1) NULL,
[IPRKZ] [nvarchar] (1) NULL,
[J_1AIDATEP] [nvarchar] (8) NULL,
[J_1AINDXP] [nvarchar] (5) NULL,
[J_1BINDUST] [nvarchar] (2) NULL,
[J_1BMATORG] [nvarchar] (1) NULL,
[J_1BMATUSE] [nvarchar] (1) NULL,
[J_1BNBM] [nvarchar] (16) NULL,
[J_1BOWNPRO] [nvarchar] (1) NULL,
[KANBA] [nvarchar] (1) NULL,
[KNTTP] [nvarchar] (1) NULL,
[KO_GSBER] [nvarchar] (4) NULL,
[KO_PARGB] [nvarchar] (4) NULL,
[KO_PPRCTR] [nvarchar] (10) NULL,
[KO_PRCTR] [nvarchar] (10) NULL,
[KOLIF] [nvarchar] (10) NULL,
[KONNR] [nvarchar] (10) NULL,
[KTMNG] [decimal] (13, 3) NULL,
[KTPNR] [nvarchar] (5) NULL,
[KUNNR] [nvarchar] (10) NULL,
[KZABS] [nvarchar] (1) NULL,
[KZBWS] [nvarchar] (1) NULL,
[KZFME] [nvarchar] (1) NULL,
[KZKFG] [nvarchar] (1) NULL,
[KZSTU] [nvarchar] (1) NULL,
[KZTLF] [nvarchar] (1) NULL,
[KZVBR] [nvarchar] (1) NULL,
[KZWI1] [decimal] (13, 2) NULL,
[KZWI2] [decimal] (13, 2) NULL,
[KZWI3] [decimal] (13, 2) NULL,
[KZWI4] [decimal] (13, 2) NULL,
[KZWI5] [decimal] (13, 2) NULL,
[KZWI6] [decimal] (13, 2) NULL,
[LABNR] [nvarchar] (20) NULL,
[LBLKZ] [nvarchar] (1) NULL,
[LEBRE] [nvarchar] (1) NULL,
[LEWED] [nvarchar] (8) NULL,
[LFRET] [nvarchar] (4) NULL,
[LGBZO] [nvarchar] (10) NULL,
[LGBZO_B] [nvarchar] (10) NULL,
[LGORT] [nvarchar] (4) NULL,
[LMEIN] [nvarchar] (3) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[LPRIO] [nvarchar] (2) NULL,
[LTSNR] [nvarchar] (6) NULL,
[MAHN1] [decimal] (3, 0) NULL,
[MAHN2] [decimal] (3, 0) NULL,
[MAHN3] [decimal] (3, 0) NULL,
[MAHNZ] [decimal] (3, 0) NULL,
[MANDT] [nvarchar] (3) NULL,
[MATKL] [nvarchar] (9) NULL,
[MATNR] [nvarchar] (18) NULL,
[MEINS] [nvarchar] (3) NULL,
[MENGE] [decimal] (13, 3) NULL,
[MEPRF] [nvarchar] (1) NULL,
[MFRGR] [nvarchar] (8) NULL,
[MFRNR] [nvarchar] (10) NULL,
[MFRPN] [nvarchar] (40) NULL,
[MFZHI] [decimal] (15, 3) NULL,
[MHDRZ] [decimal] (4, 0) NULL,
[MLMAA] [nvarchar] (1) NULL,
[MPROF] [nvarchar] (4) NULL,
[MTART] [nvarchar] (4) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[NAVNW] [decimal] (13, 2) NULL,
[NETPR] [decimal] (11, 2) NULL,
[NETWR] [decimal] (13, 2) NULL,
[NFABD] [nvarchar] (8) NULL,
[NLABD] [nvarchar] (8) NULL,
[NOTKZ] [nvarchar] (1) NULL,
[NOVET] [nvarchar] (1) NULL,
[NRFHG] [nvarchar] (1) NULL,
[NTGEW] [decimal] (13, 3) NULL,
[PACKNO] [nvarchar] (10) NULL,
[PEINH] [decimal] (5, 0) NULL,
[PLIFZ] [decimal] (3, 0) NULL,
[PNSTAT] [nvarchar] (1) NULL,
[PRDAT] [nvarchar] (8) NULL,
[PRSDR] [nvarchar] (1) NULL,
[PSTYP] [nvarchar] (1) NULL,
[PUNEI] [nvarchar] (3) NULL,
[RDPRF] [nvarchar] (4) NULL,
[REFSITE] [nvarchar] (4) NULL,
[REPOS] [nvarchar] (1) NULL,
[RESLO] [nvarchar] (4) NULL,
[RETPO] [nvarchar] (1) NULL,
[REVLV] [nvarchar] (2) NULL,
[SAISJ] [nvarchar] (4) NULL,
[SAISO] [nvarchar] (4) NULL,
[SATNR] [nvarchar] (18) NULL,
[SCHPR] [nvarchar] (1) NULL,
[SERNP] [nvarchar] (4) NULL,
[SERRU] [nvarchar] (1) NULL,
[SIKGR] [nvarchar] (3) NULL,
[SKTOF] [nvarchar] (1) NULL,
[SOBKZ] [nvarchar] (1) NULL,
[SPINF] [nvarchar] (1) NULL,
[SSQSS] [nvarchar] (8) NULL,
[STAFO] [nvarchar] (6) NULL,
[STAPO] [nvarchar] (1) NULL,
[STATU] [nvarchar] (1) NULL,
[STATUS] [nvarchar] (1) NULL,
[STPAC] [nvarchar] (1) NULL,
[TECHS] [nvarchar] (12) NULL,
[TWRKZ] [nvarchar] (1) NULL,
[TXJCD] [nvarchar] (15) NULL,
[TXZ01] [nvarchar] (40) NULL,
[TZONRC] [nvarchar] (6) NULL,
[UEBPO] [nvarchar] (5) NULL,
[UEBTK] [nvarchar] (1) NULL,
[UEBTO] [decimal] (3, 1) NULL,
[UMREN] [decimal] (5, 0) NULL,
[UMREZ] [decimal] (5, 0) NULL,
[UMSOK] [nvarchar] (1) NULL,
[UNTTO] [decimal] (3, 1) NULL,
[UPTYP] [nvarchar] (1) NULL,
[UPVOR] [nvarchar] (1) NULL,
[USEQU] [nvarchar] (1) NULL,
[VOLEH] [nvarchar] (3) NULL,
[VOLUM] [decimal] (13, 3) NULL,
[VORAB] [nvarchar] (1) NULL,
[VRTKZ] [nvarchar] (1) NULL,
[WEBAZ] [decimal] (3, 0) NULL,
[WEBRE] [nvarchar] (1) NULL,
[WEPOS] [nvarchar] (1) NULL,
[WERKS] [nvarchar] (4) NULL,
[WEUNB] [nvarchar] (1) NULL,
[XCONDITIONS] [nvarchar] (1) NULL,
[XERSY] [nvarchar] (1) NULL,
[XOBLR] [nvarchar] (1) NULL,
[ZGTYP] [nvarchar] (4) NULL,
[ZWERT] [decimal] (13, 2) NULL
)
GO
