CREATE TABLE [tsa].[ics_land_Symfonia_TW]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_TW_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_TW_IsDuplicate] DEFAULT ((0)),
[aktywny] [bit] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[flag] [smallint] NULL,
[fundusz] [int] NULL,
[id] [int] NULL,
[idlongname] [int] NULL,
[info] [smallint] NULL,
[jm] [varchar] (8) NULL,
[jmdef] [smallint] NULL,
[jmdod1] [varchar] (8) NULL,
[jmdod2] [varchar] (8) NULL,
[jmdom] [varchar] (8) NULL,
[jmuzup] [varchar] (8) NULL,
[katalog] [int] NULL,
[kod] [varchar] (40) NULL,
[kodpaskowy] [varchar] (150) NULL,
[kontofk] [varchar] (24) NULL,
[metoda] [smallint] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (100) NULL,
[nazwaFiskal] [varchar] (40) NULL,
[negoc] [smallint] NULL,
[odwrotneObc] [smallint] NULL,
[pcn] [varchar] (10) NULL,
[przelicz] [smallint] NULL,
[przelit] [smallint] NULL,
[przeljmdod1] [float] NULL,
[przeljmdod2] [float] NULL,
[przeljmdom] [float] NULL,
[przelkg] [float] NULL,
[przeluz] [float] NULL,
[rodzaj] [int] NULL,
[stanmax] [float] NULL,
[stanmin] [float] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[sww] [varchar] (20) NULL,
[szablon] [varchar] (40) NULL,
[typ] [smallint] NULL,
[typks] [varchar] (40) NULL,
[vat50] [smallint] NULL,
[vatsp] [int] NULL,
[zaokrag] [smallint] NULL,
[znacznik] [smallint] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Symfonia_TW_1] ON [tsa].[ics_land_Symfonia_TW] ([id])
GO
