CREATE TABLE [tsa].[ics_land_Symfonia_PN]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_PN_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_PN_IsDuplicate] DEFAULT ((0)),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[bufor] [smallint] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[datarozl] [datetime] NULL,
[dkid] [int] NULL,
[e_status] [smallint] NULL,
[exp_fk] [smallint] NULL,
[flag] [smallint] NULL,
[guid] [uniqueidentifier] NULL,
[id] [int] NULL,
[khadid] [int] NULL,
[khdzial] [int] NULL,
[khid] [int] NULL,
[kod] [varchar] (40) NULL,
[kurs] [float] NULL,
[kwota] [float] NULL,
[kwotarozl] [float] NULL,
[kwotarozlpln] [float] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[ok] [smallint] NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[plattyp] [int] NULL,
[rejestr] [int] NULL,
[related_fk] [smallint] NULL,
[schemat] [varchar] (4) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[stan] [float] NULL,
[status] [smallint] NULL,
[strona] [int] NULL,
[subtyp] [smallint] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[typdk] [varchar] (4) NULL,
[typkh] [smallint] NULL,
[waluta] [varchar] (3) NULL,
[wartosc] [float] NULL,
[wartoscWal] [float] NULL,
[wyplata] [smallint] NULL,
[wystawil] [int] NULL,
[znacznik] [smallint] NULL
)
GO
