CREATE TABLE [tsa].[ics_land_SAP_GBR_VBPA]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBPA_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBPA_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNR] [nvarchar] (6) NULL,
[PARVW] [nvarchar] (2) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LIFNR] [nvarchar] (10) NULL,
[PERNR] [nvarchar] (8) NULL,
[PARNR] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[ABLAD] [nvarchar] (25) NULL,
[LAND1] [nvarchar] (3) NULL,
[ADRDA] [nvarchar] (1) NULL,
[XCPDK] [nvarchar] (1) NULL,
[HITYP] [nvarchar] (1) NULL,
[PRFRE] [nvarchar] (1) NULL,
[BOKRE] [nvarchar] (1) NULL,
[HISTUNR] [nvarchar] (2) NULL,
[KNREF] [nvarchar] (30) NULL,
[LZONE] [nvarchar] (10) NULL,
[HZUOR] [nvarchar] (2) NULL,
[STCEG] [nvarchar] (20) NULL,
[PARVW_FF] [nvarchar] (1) NULL,
[ADRNP] [nvarchar] (10) NULL,
[KALE] [nvarchar] (1) NULL
)
GO
