CREATE TABLE [tsa].[ics_land_M3V10gen_POL_MWOPOL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_MWOPOL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_MWOPOL_IsDuplicate] DEFAULT ((0)),
[BHCHID] [nchar] (10) NULL,
[BHCHNO] [numeric] (3, 0) NULL,
[BHCOFA] [numeric] (15, 9) NULL,
[BHCONO] [numeric] (3, 0) NULL,
[BHDMCF] [numeric] (1, 0) NULL,
[BHEMNO] [nchar] (10) NULL,
[BHFACI] [nchar] (3) NULL,
[BHLMDT] [numeric] (8, 0) NULL,
[BHLMTS] [numeric] (18, 0) NULL,
[BHMAQA] [numeric] (15, 6) NULL,
[BHMAQT] [numeric] (15, 6) NULL,
[BHMAUN] [nchar] (3) NULL,
[BHMCPL] [numeric] (1, 0) NULL,
[BHMFNO] [numeric] (7, 0) NULL,
[BHOADS] [numeric] (1, 0) NULL,
[BHOPNO] [numeric] (4, 0) NULL,
[BHPLCF] [numeric] (1, 0) NULL,
[BHPLNO] [numeric] (10, 0) NULL,
[BHPLOA] [numeric] (15, 6) NULL,
[BHPLOB] [numeric] (15, 6) NULL,
[BHPRNO] [nchar] (15) NULL,
[BHREFD] [numeric] (8, 0) NULL,
[BHRGDT] [numeric] (8, 0) NULL,
[BHRGTM] [numeric] (6, 0) NULL,
[BHRSDT] [numeric] (8, 0) NULL,
[BHSCQA] [numeric] (15, 6) NULL,
[BHSCQT] [numeric] (15, 6) NULL,
[BHUMAS] [numeric] (7, 2) NULL,
[BHUMAT] [numeric] (7, 2) NULL,
[BHUPIT] [numeric] (7, 2) NULL,
[BHUSET] [numeric] (7, 2) NULL,
[BHWOSQ] [numeric] (9, 0) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_MWOPOL_1] ON [tsa].[ics_land_M3V10gen_POL_MWOPOL] ([BHCONO], [BHFACI], [BHPLNO], [BHWOSQ])
GO
