CREATE TABLE [tsa].[ics_land_SAP_GBR_VEDA]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VEDA_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VEDA_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[VPOSN] [nvarchar] (6) NULL,
[VLAUFZ] [nvarchar] (3) NULL,
[VLAUEZ] [nvarchar] (1) NULL,
[VLAUFK] [nvarchar] (2) NULL,
[VINSDAT] [datetime] NULL,
[VABNDAT] [datetime] NULL,
[VBEGDAT] [datetime] NULL,
[VUNTDAT] [datetime] NULL,
[VKUESCH] [nvarchar] (4) NULL,
[VAKTSCH] [nvarchar] (4) NULL,
[VEINDAT] [datetime] NULL,
[VWUNDAT] [datetime] NULL,
[VKUEPAR] [nvarchar] (1) NULL,
[VKUEGRU] [nvarchar] (2) NULL,
[VENDDAT] [datetime] NULL,
[VBELKUE] [nvarchar] (20) NULL,
[VBEDKUE] [datetime] NULL,
[VBEGREG] [nvarchar] (2) NULL,
[VVORZEIT] [nvarchar] (3) NULL,
[VVOREIN] [nvarchar] (1) NULL,
[VDEMDAT] [datetime] NULL,
[VASDA] [datetime] NULL,
[WIMID] [nvarchar] (12) NULL,
[VASDR] [nvarchar] (2) NULL,
[VENDREG] [nvarchar] (2) NULL
)
GO
