CREATE TABLE [tsa].[ics_land_SAP_GBR_VBUP]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBUP_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBUP_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNR] [nvarchar] (6) NULL,
[RFSTA] [nvarchar] (1) NULL,
[RFGSA] [nvarchar] (1) NULL,
[BESTA] [nvarchar] (1) NULL,
[LFSTA] [nvarchar] (1) NULL,
[LFGSA] [nvarchar] (1) NULL,
[WBSTA] [nvarchar] (1) NULL,
[FKSTA] [nvarchar] (1) NULL,
[FKSAA] [nvarchar] (1) NULL,
[ABSTA] [nvarchar] (1) NULL,
[GBSTA] [nvarchar] (1) NULL,
[KOSTA] [nvarchar] (1) NULL,
[LVSTA] [nvarchar] (1) NULL,
[UVALL] [nvarchar] (1) NULL,
[UVVLK] [nvarchar] (1) NULL,
[UVFAK] [nvarchar] (1) NULL,
[UVPRS] [nvarchar] (1) NULL,
[FKIVP] [nvarchar] (1) NULL,
[UVP01] [nvarchar] (1) NULL,
[UVP02] [nvarchar] (1) NULL,
[UVP03] [nvarchar] (1) NULL,
[UVP04] [nvarchar] (1) NULL,
[UVP05] [nvarchar] (1) NULL,
[PKSTA] [nvarchar] (1) NULL,
[KOQUA] [nvarchar] (1) NULL,
[COSTA] [nvarchar] (1) NULL,
[CMPPI] [nvarchar] (1) NULL,
[CMPPJ] [nvarchar] (1) NULL,
[UVPIK] [nvarchar] (1) NULL,
[UVPAK] [nvarchar] (1) NULL,
[UVWAK] [nvarchar] (1) NULL,
[DCSTA] [nvarchar] (1) NULL,
[RRSTA] [nvarchar] (1) NULL,
[VLSTP] [nvarchar] (1) NULL,
[FSSTA] [nvarchar] (1) NULL,
[LSSTA] [nvarchar] (1) NULL,
[PDSTA] [nvarchar] (1) NULL,
[MANEK] [nvarchar] (1) NULL,
[HDALL] [nvarchar] (1) NULL,
[LTSPS] [nvarchar] (1) NULL
)
GO
