CREATE TABLE [tsa].[ics_land_SAP_GBR_KNB1]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_KNB1_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_KNB1_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[KUNNR] [nvarchar] (10) NULL,
[BUKRS] [nvarchar] (4) NULL,
[PERNR] [nvarchar] (8) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[SPERR] [nvarchar] (1) NULL,
[LOEVM] [nvarchar] (1) NULL,
[ZUAWA] [nvarchar] (3) NULL,
[BUSAB] [nvarchar] (2) NULL,
[AKONT] [nvarchar] (10) NULL,
[BEGRU] [nvarchar] (4) NULL,
[KNRZE] [nvarchar] (10) NULL,
[KNRZB] [nvarchar] (10) NULL,
[ZAMIM] [nvarchar] (1) NULL,
[ZAMIV] [nvarchar] (1) NULL,
[ZAMIR] [nvarchar] (1) NULL,
[ZAMIB] [nvarchar] (1) NULL,
[ZAMIO] [nvarchar] (1) NULL,
[ZWELS] [nvarchar] (10) NULL,
[XVERR] [nvarchar] (1) NULL,
[ZAHLS] [nvarchar] (1) NULL,
[ZTERM] [nvarchar] (4) NULL,
[WAKON] [nvarchar] (4) NULL,
[VZSKZ] [nvarchar] (2) NULL,
[ZINDT] [datetime] NULL,
[ZINRT] [nvarchar] (2) NULL,
[EIKTO] [nvarchar] (12) NULL,
[ZSABE] [nvarchar] (15) NULL,
[KVERM] [nvarchar] (30) NULL,
[FDGRV] [nvarchar] (10) NULL,
[VRBKZ] [nvarchar] (2) NULL,
[VLIBB] [decimal] (13, 2) NULL,
[VRSZL] [decimal] (3, 0) NULL,
[VRSPR] [decimal] (3, 0) NULL,
[VRSNR] [nvarchar] (10) NULL,
[VERDT] [datetime] NULL,
[PERKZ] [nvarchar] (1) NULL,
[XDEZV] [nvarchar] (1) NULL,
[XAUSZ] [nvarchar] (1) NULL,
[WEBTR] [decimal] (13, 2) NULL,
[REMIT] [nvarchar] (10) NULL,
[DATLZ] [datetime] NULL,
[XZVER] [nvarchar] (1) NULL,
[TOGRU] [nvarchar] (4) NULL,
[KULTG] [decimal] (3, 0) NULL,
[HBKID] [nvarchar] (5) NULL,
[XPORE] [nvarchar] (1) NULL,
[BLNKZ] [nvarchar] (2) NULL,
[ALTKN] [nvarchar] (10) NULL,
[ZGRUP] [nvarchar] (2) NULL,
[URLID] [nvarchar] (4) NULL,
[MGRUP] [nvarchar] (2) NULL,
[LOCKB] [nvarchar] (7) NULL,
[UZAWE] [nvarchar] (2) NULL,
[EKVBD] [nvarchar] (10) NULL,
[SREGL] [nvarchar] (3) NULL,
[XEDIP] [nvarchar] (1) NULL,
[FRGRP] [nvarchar] (4) NULL,
[VRSDG] [nvarchar] (3) NULL,
[TLFXS] [nvarchar] (31) NULL,
[INTAD] [nvarchar] (130) NULL,
[XKNZB] [nvarchar] (1) NULL,
[GUZTE] [nvarchar] (4) NULL,
[GRICD] [nvarchar] (2) NULL,
[GRIDT] [nvarchar] (2) NULL,
[WBRSL] [nvarchar] (2) NULL,
[CONFS] [nvarchar] (1) NULL,
[UPDAT] [datetime] NULL,
[UPTIM] [datetime] NULL,
[NODEL] [nvarchar] (1) NULL,
[TLFNS] [nvarchar] (30) NULL,
[CESSION_KZ] [nvarchar] (2) NULL,
[AVSND] [nvarchar] (1) NULL,
[AD_HASH] [nvarchar] (10) NULL,
[QLAND] [nvarchar] (3) NULL,
[CIIUCODE] [nvarchar] (4) NULL,
[GMVKZD] [nvarchar] (1) NULL
)
GO
