CREATE TABLE [tsa].[ICS_LAND_SAP_GBR_VBRP]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNR] [nvarchar] (6) NULL,
[UEPOS] [nvarchar] (6) NULL,
[FKIMG] [decimal] (13, 3) NULL,
[VRKME] [nvarchar] (3) NULL,
[UMVKZ] [decimal] (5, 0) NULL,
[UMVKN] [decimal] (5, 0) NULL,
[MEINS] [nvarchar] (3) NULL,
[SMENG] [decimal] (13, 3) NULL,
[FKLMG] [decimal] (13, 3) NULL,
[LMENG] [decimal] (13, 3) NULL,
[NTGEW] [decimal] (15, 3) NULL,
[BRGEW] [decimal] (15, 3) NULL,
[GEWEI] [nvarchar] (3) NULL,
[VOLUM] [decimal] (15, 3) NULL,
[VOLEH] [nvarchar] (3) NULL,
[GSBER] [nvarchar] (4) NULL,
[PRSDT] [datetime] NULL,
[FBUDA] [datetime] NULL,
[KURSK] [decimal] (9, 5) NULL,
[NETWR] [decimal] (15, 2) NULL,
[VBELV] [nvarchar] (10) NULL,
[POSNV] [nvarchar] (6) NULL,
[VGBEL] [nvarchar] (10) NULL,
[VGPOS] [nvarchar] (6) NULL,
[VGTYP] [nvarchar] (1) NULL,
[AUBEL] [nvarchar] (10) NULL,
[AUPOS] [nvarchar] (6) NULL,
[AUREF] [nvarchar] (1) NULL,
[MATNR] [nvarchar] (18) NULL,
[ARKTX] [nvarchar] (40) NULL,
[PMATN] [nvarchar] (18) NULL,
[CHARG] [nvarchar] (10) NULL,
[MATKL] [nvarchar] (9) NULL,
[PSTYV] [nvarchar] (4) NULL,
[POSAR] [nvarchar] (1) NULL,
[PRODH] [nvarchar] (18) NULL,
[VSTEL] [nvarchar] (4) NULL,
[ATPKZ] [nvarchar] (1) NULL,
[SPART] [nvarchar] (2) NULL,
[POSPA] [nvarchar] (6) NULL,
[WERKS] [nvarchar] (4) NULL,
[ALAND] [nvarchar] (3) NULL,
[WKREG] [nvarchar] (3) NULL,
[WKCOU] [nvarchar] (3) NULL,
[WKCTY] [nvarchar] (4) NULL,
[TAXM1] [nvarchar] (1) NULL,
[TAXM2] [nvarchar] (1) NULL,
[TAXM3] [nvarchar] (1) NULL,
[TAXM4] [nvarchar] (1) NULL,
[TAXM5] [nvarchar] (1) NULL,
[TAXM6] [nvarchar] (1) NULL,
[TAXM7] [nvarchar] (1) NULL,
[TAXM8] [nvarchar] (1) NULL,
[TAXM9] [nvarchar] (1) NULL,
[KOWRR] [nvarchar] (1) NULL,
[PRSFD] [nvarchar] (1) NULL,
[SKTOF] [nvarchar] (1) NULL,
[SKFBP] [decimal] (13, 2) NULL,
[KONDM] [nvarchar] (2) NULL,
[KTGRM] [nvarchar] (2) NULL,
[KOSTL] [nvarchar] (10) NULL,
[BONUS] [nvarchar] (2) NULL,
[PROVG] [nvarchar] (2) NULL,
[EANNR] [nvarchar] (13) NULL,
[VKGRP] [nvarchar] (3) NULL,
[VKBUR] [nvarchar] (4) NULL,
[SPARA] [nvarchar] (2) NULL,
[SHKZG] [nvarchar] (1) NULL,
[ERNAM] [nvarchar] (12) NULL,
[ERDAT] [datetime] NULL,
[ERZET] [datetime] NULL,
[BWTAR] [nvarchar] (10) NULL,
[LGORT] [nvarchar] (4) NULL,
[STAFO] [nvarchar] (6) NULL,
[WAVWR] [decimal] (13, 2) NULL,
[KZWI1] [decimal] (13, 2) NULL,
[KZWI2] [decimal] (13, 2) NULL,
[KZWI3] [decimal] (13, 2) NULL,
[KZWI4] [decimal] (13, 2) NULL,
[KZWI5] [decimal] (13, 2) NULL,
[KZWI6] [decimal] (13, 2) NULL,
[STCUR] [decimal] (9, 5) NULL,
[UVPRS] [nvarchar] (1) NULL,
[UVALL] [nvarchar] (1) NULL,
[EAN11] [nvarchar] (18) NULL,
[PRCTR] [nvarchar] (10) NULL,
[KVGR1] [nvarchar] (3) NULL,
[KVGR2] [nvarchar] (3) NULL,
[KVGR3] [nvarchar] (3) NULL,
[KVGR4] [nvarchar] (3) NULL,
[KVGR5] [nvarchar] (3) NULL,
[MVGR1] [nvarchar] (3) NULL,
[MVGR2] [nvarchar] (3) NULL,
[MVGR3] [nvarchar] (3) NULL,
[MVGR4] [nvarchar] (3) NULL,
[MVGR5] [nvarchar] (3) NULL,
[MATWA] [nvarchar] (18) NULL,
[BONBA] [decimal] (13, 2) NULL,
[KOKRS] [nvarchar] (4) NULL,
[PAOBJNR] [nvarchar] (10) NULL,
[PS_PSP_PNR] [nvarchar] (8) NULL,
[AUFNR] [nvarchar] (12) NULL,
[TXJCD] [nvarchar] (15) NULL,
[CMPRE] [decimal] (11, 2) NULL,
[CMPNT] [nvarchar] (1) NULL,
[CUOBJ] [nvarchar] (18) NULL,
[CUOBJ_CH] [nvarchar] (18) NULL,
[KOUPD] [nvarchar] (1) NULL,
[UECHA] [nvarchar] (6) NULL,
[XCHAR] [nvarchar] (1) NULL,
[ABRVW] [nvarchar] (3) NULL,
[SERNR] [nvarchar] (8) NULL,
[BZIRK_AUFT] [nvarchar] (6) NULL,
[KDGRP_AUFT] [nvarchar] (2) NULL,
[KONDA_AUFT] [nvarchar] (2) NULL,
[LLAND_AUFT] [nvarchar] (3) NULL,
[MPROK] [nvarchar] (1) NULL,
[PLTYP_AUFT] [nvarchar] (2) NULL,
[REGIO_AUFT] [nvarchar] (3) NULL,
[VKORG_AUFT] [nvarchar] (4) NULL,
[VTWEG_AUFT] [nvarchar] (2) NULL,
[ABRBG] [datetime] NULL,
[PROSA] [nvarchar] (1) NULL,
[UEPVW] [nvarchar] (1) NULL,
[AUTYP] [nvarchar] (1) NULL,
[STADAT] [datetime] NULL,
[FPLNR] [nvarchar] (10) NULL,
[FPLTR] [nvarchar] (6) NULL,
[AKTNR] [nvarchar] (10) NULL,
[KNUMA_PI] [nvarchar] (10) NULL,
[KNUMA_AG] [nvarchar] (10) NULL,
[PREFE] [nvarchar] (1) NULL,
[MWSBP] [decimal] (13, 2) NULL,
[AUGRU_AUFT] [nvarchar] (3) NULL,
[FAREG] [nvarchar] (1) NULL,
[UPMAT] [nvarchar] (18) NULL,
[UKONM] [nvarchar] (2) NULL,
[CMPRE_FLT] [float] NULL,
[ABFOR] [nvarchar] (2) NULL,
[ABGES] [float] NULL,
[J_1ARFZ] [nvarchar] (1) NULL,
[J_1AREGIO] [nvarchar] (3) NULL,
[J_1AGICD] [nvarchar] (2) NULL,
[J_1ADTYP] [nvarchar] (2) NULL,
[J_1ATXREL] [nvarchar] (10) NULL,
[J_1BCFOP] [nvarchar] (10) NULL,
[J_1BTAXLW1] [nvarchar] (3) NULL,
[J_1BTAXLW2] [nvarchar] (3) NULL,
[J_1BTXSDC] [nvarchar] (2) NULL,
[BRTWR] [decimal] (15, 2) NULL,
[WKTNR] [nvarchar] (10) NULL,
[WKTPS] [nvarchar] (6) NULL,
[RPLNR] [nvarchar] (10) NULL,
[KURSK_DAT] [datetime] NULL,
[WGRU1] [nvarchar] (18) NULL,
[WGRU2] [nvarchar] (18) NULL,
[KDKG1] [nvarchar] (2) NULL,
[KDKG2] [nvarchar] (2) NULL,
[KDKG3] [nvarchar] (2) NULL,
[KDKG4] [nvarchar] (2) NULL,
[KDKG5] [nvarchar] (2) NULL,
[VKAUS] [nvarchar] (3) NULL,
[J_1AINDXP] [nvarchar] (5) NULL,
[J_1AIDATEP] [datetime] NULL,
[KZFME] [nvarchar] (1) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[VERTT] [nvarchar] (1) NULL,
[VERTN] [nvarchar] (13) NULL,
[SGTXT] [nvarchar] (50) NULL,
[DELCO] [nvarchar] (3) NULL,
[BEMOT] [nvarchar] (2) NULL,
[RRREL] [nvarchar] (1) NULL,
[AKKUR] [decimal] (9, 5) NULL,
[WMINR] [nvarchar] (10) NULL,
[VGBEL_EX] [nvarchar] (10) NULL,
[VGPOS_EX] [nvarchar] (6) NULL,
[LOGSYS] [nvarchar] (10) NULL,
[VGTYP_EX] [nvarchar] (3) NULL,
[J_1BTAXLW3] [nvarchar] (3) NULL,
[J_1BTAXLW4] [nvarchar] (3) NULL,
[J_1BTAXLW5] [nvarchar] (3) NULL,
[MSR_ID] [nvarchar] (10) NULL,
[MSR_REFUND_CODE] [nvarchar] (3) NULL,
[MSR_RET_REASON] [nvarchar] (3) NULL,
[NRAB_KNUMH] [nvarchar] (10) NULL,
[NRAB_VALUE] [decimal] (13, 2) NULL,
[DISPUTE_CASE] [binary] (16) NULL,
[FUND_USAGE_ITEM] [binary] (16) NULL,
[FARR_RELTYPE] [nvarchar] (10) NULL,
[CLAIMS_TAXATION] [nvarchar] (1) NULL,
[AUFPL] [nvarchar] (10) NULL,
[APLZL] [nvarchar] (8) NULL,
[DPCNR] [nvarchar] (10) NULL,
[DCPNR] [nvarchar] (3) NULL,
[DPNRB] [nvarchar] (3) NULL,
[PEROP_BEG] [datetime] NULL,
[PEROP_END] [datetime] NULL,
[FONDS] [nvarchar] (10) NULL,
[FISTL] [nvarchar] (16) NULL,
[FKBER] [nvarchar] (16) NULL,
[GRANT_NBR] [nvarchar] (20) NULL,
[PRS_WORK_PERIOD] [nvarchar] (7) NULL,
[PPRCTR] [nvarchar] (10) NULL,
[PARGB] [nvarchar] (4) NULL,
[AUFPL_OAA] [nvarchar] (10) NULL,
[APLZL_OAA] [nvarchar] (8) NULL,
[CAMPAIGN] [binary] (16) NULL,
[COMPREAS] [nvarchar] (4) NULL,
[EtlSourceTable] [varchar] (200) NOT NULL
)
GO
