CREATE TABLE [tsa].[ics_land_Symfonia_MG]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_MG_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_MG_IsDuplicate] DEFAULT ((0)),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[bufor] [smallint] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[datasp] [datetime] NULL,
[exp_fk] [smallint] NULL,
[flag] [smallint] NULL,
[grupacen] [smallint] NULL,
[guid] [uniqueidentifier] NULL,
[id] [int] NULL,
[iddokkoryg] [int] NULL,
[info] [smallint] NULL,
[jpk] [smallint] NULL,
[katalog] [int] NULL,
[khadid] [int] NULL,
[khdzial] [int] NULL,
[khid] [int] NULL,
[kod] [varchar] (40) NULL,
[magazyn] [int] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (40) NULL,
[netto] [float] NULL,
[odebrane] [varchar] (40) NULL,
[ok] [smallint] NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[przychod] [float] NULL,
[rejestrVat] [int] NULL,
[rodzaj] [int] NULL,
[rozchod] [float] NULL,
[rozlmg] [smallint] NULL,
[rr] [smallint] NULL,
[schemat] [varchar] (4) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[statusFK] [smallint] NULL,
[statusRDF] [smallint] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[typ_dk] [varchar] (4) NULL,
[wartk] [float] NULL,
[wartoscWz] [float] NULL,
[wystawil] [int] NULL,
[znacznik] [smallint] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Symfonia_MG_1] ON [tsa].[ics_land_Symfonia_MG] ([id])
GO
