CREATE TABLE [tsa].[ics_land_Navision_ROU_Purchase_Invoice_Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_ROU_Purchase_Invoice_Line_ExcludedFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_ROU_Purchase_Invoice_Line_IsDuplicate] DEFAULT ((0)),
[timestamp] [varbinary] (8) NULL,
[Document No_] [varchar] (20) NOT NULL,
[Line No_] [int] NOT NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Location Code] [varchar] (10) NULL,
[Posting Group] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[VAT %] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Allow Invoice Disc_] [tinyint] NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Job No_] [varchar] (20) NULL,
[Phase Code] [varchar] (10) NULL,
[Task Code] [varchar] (10) NULL,
[Step Code] [varchar] (10) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Entry Point] [varchar] (10) NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Tax Group Code] [varchar] (10) NULL,
[Use Tax] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[System-Created Entry] [tinyint] NULL,
[Line Amount] [decimal] (38, 20) NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[Bin Code] [varchar] (20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Maintenance Code] [varchar] (10) NULL,
[Insurance No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Use Duplication List] [tinyint] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Item Category Code] [varchar] (10) NULL,
[Nonstock] [tinyint] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Product Group Code] [varchar] (10) NULL,
[Return Reason Code] [varchar] (10) NULL,
[No_ of Palet] [decimal] (38, 20) NULL,
[Palet Weight] [decimal] (38, 20) NULL,
[Palet Type] [varchar] (250) NULL,
[Routing No_] [varchar] (20) NULL,
[Operation No_] [varchar] (10) NULL,
[Work Center No_] [varchar] (20) NULL,
[Prod_ Order Line No_] [int] NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Routing Reference No_] [int] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_ROU_Purchase_Invoice_Line] ON [tsa].[ics_land_Navision_ROU_Purchase_Invoice_Line] ([Document No_], [Line No_])
GO
