CREATE TABLE [tsa].[ics_land_SAP_GBR_MARD]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_MARD_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_MARD_IsDuplicate] DEFAULT ((0)),
[BSKRF] [float] NULL,
[DISKZ] [nvarchar] (1) NULL,
[DLINL] [datetime] NULL,
[EINME] [decimal] (18, 0) NULL,
[ERSDA] [datetime] NULL,
[EXPPG] [nvarchar] (1) NULL,
[EXVER] [nvarchar] (2) NULL,
[HERKL] [nvarchar] (3) NULL,
[INSME] [decimal] (18, 0) NULL,
[KEINM] [decimal] (18, 0) NULL,
[KINSM] [decimal] (18, 0) NULL,
[KLABS] [decimal] (18, 0) NULL,
[KSPEM] [decimal] (18, 0) NULL,
[KZILE] [nvarchar] (3) NULL,
[KZILL] [nvarchar] (3) NULL,
[KZILQ] [nvarchar] (3) NULL,
[KZILS] [nvarchar] (3) NULL,
[KZVLE] [nvarchar] (3) NULL,
[KZVLL] [nvarchar] (3) NULL,
[KZVLQ] [nvarchar] (3) NULL,
[KZVLS] [nvarchar] (3) NULL,
[LABST] [decimal] (18, 0) NULL,
[LBSTF] [decimal] (18, 0) NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFMON] [nvarchar] (2) NULL,
[LGORT] [nvarchar] (4) NULL,
[LGPBE] [nvarchar] (10) NULL,
[LMINB] [decimal] (18, 0) NULL,
[LSOBS] [nvarchar] (2) NULL,
[LVORM] [nvarchar] (1) NULL,
[LWMKB] [nvarchar] (3) NULL,
[MANDT] [nvarchar] (3) NULL,
[MATNR] [nvarchar] (18) NULL,
[MDJIN] [nvarchar] (4) NULL,
[MDRUE] [nvarchar] (1) NULL,
[PRCTL] [nvarchar] (10) NULL,
[PSTAT] [nvarchar] (15) NULL,
[RETME] [decimal] (18, 0) NULL,
[SPEME] [decimal] (18, 0) NULL,
[SPERR] [nvarchar] (1) NULL,
[UMLME] [decimal] (18, 0) NULL,
[VKLAB] [decimal] (18, 0) NULL,
[VKUML] [decimal] (18, 0) NULL,
[VMEIN] [decimal] (18, 0) NULL,
[VMINS] [decimal] (18, 0) NULL,
[VMLAB] [decimal] (18, 0) NULL,
[VMRET] [decimal] (18, 0) NULL,
[VMSPE] [decimal] (18, 0) NULL,
[VMUML] [decimal] (18, 0) NULL,
[WERKS] [nvarchar] (4) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_SAP_GBR_MARD_1] ON [tsa].[ics_land_SAP_GBR_MARD] ([LGORT], [MATNR], [WERKS])
GO
