CREATE TABLE [tsa].[ics_land_SAP_SVK_EKBE]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKBE_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKBE_IsDuplicate] DEFAULT ((0)),
[AREWB] [decimal] (13, 2) NULL,
[AREWR] [decimal] (13, 2) NULL,
[AREWW] [decimal] (13, 2) NULL,
[BAMNG] [decimal] (13, 3) NULL,
[BEKKN] [nvarchar] (2) NULL,
[BELNR] [nvarchar] (10) NULL,
[BEWTP] [nvarchar] (1) NULL,
[BLDAT] [nvarchar] (8) NULL,
[BPMNG] [decimal] (13, 3) NULL,
[BPWES] [decimal] (13, 3) NULL,
[BUDAT] [nvarchar] (8) NULL,
[BUZEI] [nvarchar] (4) NULL,
[BWART] [nvarchar] (3) NULL,
[BWTAR] [nvarchar] (10) NULL,
[CHARG] [nvarchar] (10) NULL,
[CPUDT] [nvarchar] (8) NULL,
[CPUTM] [nvarchar] (6) NULL,
[DMBTR] [decimal] (13, 2) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[ELIKZ] [nvarchar] (1) NULL,
[EMATN] [nvarchar] (18) NULL,
[ERNAM] [nvarchar] (12) NULL,
[ET_UPD] [nvarchar] (1) NULL,
[ETENS] [nvarchar] (4) NULL,
[EVERE] [nvarchar] (2) NULL,
[GJAHR] [nvarchar] (4) NULL,
[GRUND] [nvarchar] (4) NULL,
[HSWAE] [nvarchar] (5) NULL,
[INTROW] [nvarchar] (10) NULL,
[KNUMV] [nvarchar] (10) NULL,
[LEMIN] [nvarchar] (1) NULL,
[LFBNR] [nvarchar] (10) NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFPOS] [nvarchar] (4) NULL,
[LSMEH] [nvarchar] (3) NULL,
[LSMNG] [decimal] (13, 3) NULL,
[MANDT] [nvarchar] (3) NULL,
[MATNR] [nvarchar] (18) NULL,
[MENGE] [decimal] (13, 3) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[PACKNO] [nvarchar] (10) NULL,
[QTY_DIFF] [decimal] (13, 3) NULL,
[REEWR] [decimal] (13, 2) NULL,
[REFWR] [decimal] (13, 2) NULL,
[REWRB] [decimal] (13, 2) NULL,
[SAPRL] [nvarchar] (4) NULL,
[SHKZG] [nvarchar] (1) NULL,
[SRVPOS] [nvarchar] (18) NULL,
[VGABE] [nvarchar] (1) NULL,
[WAERS] [nvarchar] (5) NULL,
[WERKS] [nvarchar] (4) NULL,
[WESBS] [decimal] (13, 3) NULL,
[WRBTR] [decimal] (13, 2) NULL,
[XBLNR] [nvarchar] (16) NULL,
[XUNPL] [nvarchar] (1) NULL,
[XWOFF] [nvarchar] (1) NULL,
[XWSBR] [nvarchar] (1) NULL,
[ZEKKN] [nvarchar] (2) NULL
)
GO
