CREATE TABLE [tsa].[ics_land_M3V10vil_POL_MITMAS]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF__ics_land___Exclu__147CD127] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF__ics_land___IsDup__1570F560] DEFAULT ((0)),
[MMAAD0] [numeric] (18, 0) NULL,
[MMAAD1] [numeric] (18, 0) NULL,
[MMACHK] [numeric] (18, 0) NULL,
[MMACRF] [nchar] (8) NULL,
[MMACTI] [numeric] (18, 0) NULL,
[MMAEQY] [numeric] (18, 0) NULL,
[MMAES2] [numeric] (18, 0) NULL,
[MMAESC] [numeric] (18, 0) NULL,
[MMALUC] [numeric] (18, 0) NULL,
[MMALUN] [nchar] (3) NULL,
[MMAMOR] [numeric] (18, 0) NULL,
[MMAMPT] [numeric] (18, 0) NULL,
[MMARPA] [nchar] (10) NULL,
[MMARPR] [nchar] (10) NULL,
[MMARR1] [numeric] (18, 0) NULL,
[MMATMN] [numeric] (18, 0) NULL,
[MMATMO] [nchar] (10) NULL,
[MMATNR] [numeric] (18, 0) NULL,
[MMAUTC] [numeric] (18, 0) NULL,
[MMAWDY] [numeric] (18, 0) NULL,
[MMBACD] [numeric] (18, 0) NULL,
[MMBGRP] [nchar] (2) NULL,
[MMBOGR] [numeric] (18, 0) NULL,
[MMBPEY] [numeric] (18, 0) NULL,
[MMBUAR] [nchar] (3) NULL,
[MMBYPR] [numeric] (18, 0) NULL,
[MMCAWP] [numeric] (18, 0) NULL,
[MMCCO1] [numeric] (18, 0) NULL,
[MMCCO2] [numeric] (18, 0) NULL,
[MMCCO3] [numeric] (18, 0) NULL,
[MMCETY] [nchar] (2) NULL,
[MMCFI1] [nchar] (10) NULL,
[MMCFI2] [numeric] (18, 0) NULL,
[MMCFI3] [nchar] (3) NULL,
[MMCFI4] [nchar] (5) NULL,
[MMCFI5] [nchar] (1) NULL,
[MMCHCD] [numeric] (18, 0) NULL,
[MMCHCL] [numeric] (18, 0) NULL,
[MMCHID] [nchar] (10) NULL,
[MMCHNO] [numeric] (18, 0) NULL,
[MMCONC] [numeric] (18, 0) NULL,
[MMCONO] [numeric] (18, 0) NULL,
[MMCPUN] [nchar] (3) NULL,
[MMCUCD] [nchar] (3) NULL,
[MMCUCS] [nchar] (3) NULL,
[MMCWUN] [nchar] (3) NULL,
[MMDCCD] [numeric] (18, 0) NULL,
[MMDIGI] [nchar] (2) NULL,
[MMDIM1] [nchar] (15) NULL,
[MMDIM2] [nchar] (15) NULL,
[MMDIM3] [nchar] (15) NULL,
[MMDIRR] [numeric] (18, 0) NULL,
[MMDOID] [nvarchar] (20) NULL,
[MMDPID] [numeric] (18, 0) NULL,
[MMDTID] [numeric] (18, 0) NULL,
[MMDWNO] [nvarchar] (20) NULL,
[MMECAC] [nchar] (2) NULL,
[MMECCC] [nchar] (4) NULL,
[MMECFL] [numeric] (18, 0) NULL,
[MMECMA] [numeric] (18, 0) NULL,
[MMECVE] [nchar] (4) NULL,
[MMEPCD] [numeric] (18, 0) NULL,
[MMETRF] [nchar] (3) NULL,
[MMEVGR] [nchar] (2) NULL,
[MMEXCA] [numeric] (18, 0) NULL,
[MMEXPD] [numeric] (18, 0) NULL,
[MMFCCM] [nchar] (2) NULL,
[MMFCU1] [numeric] (18, 0) NULL,
[MMFEBA] [numeric] (18, 0) NULL,
[MMFRAG] [numeric] (18, 0) NULL,
[MMFRE3] [nchar] (5) NULL,
[MMFRE4] [nchar] (5) NULL,
[MMFUDS] [nvarchar] (60) NULL,
[MMFUNC] [nchar] (15) NULL,
[MMGRMT] [nchar] (3) NULL,
[MMGRP1] [nchar] (15) NULL,
[MMGRP2] [nchar] (15) NULL,
[MMGRP3] [nchar] (15) NULL,
[MMGRP4] [nchar] (15) NULL,
[MMGRP5] [nchar] (15) NULL,
[MMGRTI] [nchar] (10) NULL,
[MMGRTS] [nchar] (5) NULL,
[MMGRWE] [numeric] (18, 0) NULL,
[MMHAC1] [nchar] (4) NULL,
[MMHAC2] [nchar] (4) NULL,
[MMHAC3] [nchar] (4) NULL,
[MMHAZI] [numeric] (18, 0) NULL,
[MMHDPR] [nchar] (15) NULL,
[MMHIE1] [nchar] (15) NULL,
[MMHIE2] [nchar] (15) NULL,
[MMHIE3] [nchar] (15) NULL,
[MMHIE4] [nchar] (15) NULL,
[MMHIE5] [nchar] (15) NULL,
[MMIACP] [numeric] (18, 0) NULL,
[MMIEAA] [numeric] (18, 0) NULL,
[MMINDI] [numeric] (18, 0) NULL,
[MMITCL] [nchar] (5) NULL,
[MMITDS] [nvarchar] (30) NULL,
[MMITGR] [nchar] (8) NULL,
[MMITNO] [nchar] (15) NULL,
[MMITRC] [numeric] (18, 0) NULL,
[MMITRF] [nchar] (3) NULL,
[MMITTY] [nchar] (3) NULL,
[MMLAMA] [numeric] (18, 0) NULL,
[MMLEAI] [numeric] (18, 0) NULL,
[MMLMDT] [numeric] (18, 0) NULL,
[MMLMTS] [numeric] (18, 0) NULL,
[MMMABU] [numeric] (18, 0) NULL,
[MMMAPL] [nchar] (10) NULL,
[MMMAPN] [numeric] (18, 0) NULL,
[MMMBFR] [nchar] (6) NULL,
[MMMBSR] [nchar] (6) NULL,
[MMMBUR] [nchar] (6) NULL,
[MMMDIR] [nchar] (6) NULL,
[MMMES1] [nchar] (6) NULL,
[MMMES2] [nchar] (6) NULL,
[MMMES3] [nchar] (6) NULL,
[MMMES4] [nchar] (6) NULL,
[MMMPGM] [nvarchar] (20) NULL,
[MMMVA1] [numeric] (18, 0) NULL,
[MMMVA2] [numeric] (18, 0) NULL,
[MMMVA3] [numeric] (18, 0) NULL,
[MMMVA4] [numeric] (18, 0) NULL,
[MMNESA] [nchar] (3) NULL,
[MMNEWE] [numeric] (18, 0) NULL,
[MMNMIT] [nchar] (2) NULL,
[MMNPTO] [numeric] (18, 0) NULL,
[MMNSUF] [nvarchar] (20) NULL,
[MMORTY] [nchar] (3) NULL,
[MMOTDI] [numeric] (18, 0) NULL,
[MMPDCC] [numeric] (18, 0) NULL,
[MMPEQ1] [numeric] (18, 0) NULL,
[MMPEQ2] [numeric] (18, 0) NULL,
[MMPEQ3] [numeric] (18, 0) NULL,
[MMPEQ4] [numeric] (18, 0) NULL,
[MMPET1] [numeric] (18, 0) NULL,
[MMPET2] [numeric] (18, 0) NULL,
[MMPET3] [numeric] (18, 0) NULL,
[MMPET4] [numeric] (18, 0) NULL,
[MMPLCD] [nchar] (2) NULL,
[MMPLMZ] [numeric] (18, 0) NULL,
[MMPOCY] [numeric] (18, 0) NULL,
[MMPPDT] [numeric] (18, 0) NULL,
[MMPPUN] [nchar] (3) NULL,
[MMPRCM] [nchar] (6) NULL,
[MMPRGP] [nchar] (3) NULL,
[MMPRGR] [numeric] (18, 0) NULL,
[MMPROD] [nchar] (10) NULL,
[MMPRVG] [nchar] (2) NULL,
[MMPUCD] [numeric] (18, 0) NULL,
[MMPUPR] [numeric] (18, 0) NULL,
[MMPUUN] [nchar] (3) NULL,
[MMQACD] [numeric] (18, 0) NULL,
[MMRESP] [nchar] (10) NULL,
[MMRGDT] [numeric] (18, 0) NULL,
[MMRGTM] [numeric] (18, 0) NULL,
[MMRIDC] [numeric] (18, 0) NULL,
[MMRIDE] [nchar] (10) NULL,
[MMSACD] [numeric] (18, 0) NULL,
[MMSALE] [numeric] (18, 0) NULL,
[MMSAPR] [numeric] (18, 0) NULL,
[MMSCGR] [numeric] (18, 0) NULL,
[MMSEPR] [numeric] (18, 0) NULL,
[MMSMFI] [numeric] (18, 0) NULL,
[MMSPAC] [nchar] (6) NULL,
[MMSPDT] [numeric] (18, 0) NULL,
[MMSPE1] [nvarchar] (25) NULL,
[MMSPE2] [nvarchar] (25) NULL,
[MMSPE3] [nvarchar] (25) NULL,
[MMSPE4] [nvarchar] (25) NULL,
[MMSPE5] [nvarchar] (25) NULL,
[MMSPUC] [numeric] (18, 0) NULL,
[MMSPUN] [nchar] (3) NULL,
[MMSTAT] [nchar] (2) NULL,
[MMSTCD] [numeric] (18, 0) NULL,
[MMSTCN] [nchar] (2) NULL,
[MMSTCS] [numeric] (18, 0) NULL,
[MMSTNC] [nchar] (1) NULL,
[MMSTUN] [nchar] (3) NULL,
[MMSUNO] [nchar] (10) NULL,
[MMTANK] [numeric] (18, 0) NULL,
[MMTAXC] [nchar] (3) NULL,
[MMTBFR] [numeric] (18, 0) NULL,
[MMTBSR] [numeric] (18, 0) NULL,
[MMTBUR] [numeric] (18, 0) NULL,
[MMTECR] [nchar] (3) NULL,
[MMTOHI] [numeric] (18, 0) NULL,
[MMTORE] [numeric] (18, 0) NULL,
[MMTPCD] [numeric] (18, 0) NULL,
[MMTPLI] [nchar] (15) NULL,
[MMTRPA] [nchar] (6) NULL,
[MMTXID] [numeric] (18, 0) NULL,
[MMUNMS] [nchar] (3) NULL,
[MMUNNN] [numeric] (18, 0) NULL,
[MMUNPA] [nchar] (3) NULL,
[MMVOL3] [numeric] (18, 0) NULL,
[MMVTCP] [numeric] (18, 0) NULL,
[MMVTCS] [numeric] (18, 0) NULL,
[MMWADY] [numeric] (18, 0) NULL,
[MMWAL1] [numeric] (18, 0) NULL,
[MMWAL2] [numeric] (18, 0) NULL,
[MMWAL3] [numeric] (18, 0) NULL,
[MMWAL4] [numeric] (18, 0) NULL,
[MMWAPC] [numeric] (18, 0) NULL,
[MMWSCA] [nchar] (6) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10vil_POL_MITMAS_1] ON [tsa].[ics_land_M3V10vil_POL_MITMAS] ([MMCONO], [MMITNO])
GO
