CREATE TABLE [tsa].[ics_land_M3V10gen_POL_FRCALP]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_FRCALP_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_FRCALP_IsDuplicate] DEFAULT ((0)),
[HEANBR] [numeric] (9, 0) NULL,
[HEBANO] [nvarchar] (20) NULL,
[HEBJNO] [nvarchar] (18) NULL,
[HEBSOB] [numeric] (15, 2) NULL,
[HECANB] [numeric] (17, 0) NULL,
[HECHID] [nchar] (10) NULL,
[HECHNO] [numeric] (3, 0) NULL,
[HECONO] [numeric] (3, 0) NULL,
[HEFACI] [nchar] (3) NULL,
[HEFSRC] [nchar] (1) NULL,
[HEGTYP] [nchar] (2) NULL,
[HEHACP] [numeric] (17, 6) NULL,
[HEITNO] [nchar] (15) NULL,
[HELMDT] [numeric] (8, 0) NULL,
[HELMTS] [numeric] (18, 0) NULL,
[HEMFCO] [numeric] (17, 6) NULL,
[HEMRGD] [numeric] (8, 0) NULL,
[HEMRGT] [numeric] (6, 0) NULL,
[HERGDT] [numeric] (8, 0) NULL,
[HERGTM] [numeric] (6, 0) NULL,
[HETMSX] [numeric] (3, 0) NULL,
[HETRDT] [numeric] (8, 0) NULL,
[HETRQT] [numeric] (15, 6) NULL,
[HETRTM] [numeric] (6, 0) NULL,
[HETRTP] [nchar] (3) NULL,
[HETTID] [nchar] (3) NULL,
[HETTYP] [numeric] (2, 0) NULL,
[HEWHLO] [nchar] (3) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_FRCALP_1] ON [tsa].[ics_land_M3V10gen_POL_FRCALP] ([HEBJNO], [HECONO], [HEITNO], [HEMRGD], [HEMRGT], [HETMSX], [HETRDT], [HETRTM], [HEWHLO])
GO
