CREATE TABLE [tsa].[ics_land_baan_ttdpur002610]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_ttdpur002610_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_ttdpur002610_IsDuplicate] DEFAULT ((0)),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cact] [varchar] (8) NULL,
[t_ccco] [varchar] (8) NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_citt] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cpla] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_cspa] [varchar] (8) NULL,
[t_cstl] [varchar] (4) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvqp] [float] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_opol] [tinyint] NULL,
[t_oqua] [float] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_prih] [float] NULL,
[t_proc] [tinyint] NULL,
[t_qdat] [datetime] NULL,
[t_qono] [int] NULL,
[t_qspa] [tinyint] NULL,
[t_rank] [tinyint] NULL,
[t_sdsc] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_txta] [int] NULL,
[t_valp] [real] NULL,
[t_widt] [float] NULL
)
GO
