CREATE TABLE [tsa].[ICS_LAND_SAP_DEU_TVKO]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[VKORG] [nvarchar] (4) NULL,
[WAERS] [nvarchar] (5) NULL,
[BUKRS] [nvarchar] (4) NULL,
[ADRNR] [nvarchar] (10) NULL,
[TXNAM_ADR] [nvarchar] (16) NULL,
[TXNAM_KOP] [nvarchar] (16) NULL,
[TXNAM_FUS] [nvarchar] (16) NULL,
[TXNAM_GRU] [nvarchar] (16) NULL,
[VKOAU] [nvarchar] (4) NULL,
[KUNNR] [nvarchar] (10) NULL,
[BOAVO] [nvarchar] (1) NULL,
[VKOKL] [nvarchar] (2) NULL,
[EKORG] [nvarchar] (4) NULL,
[EKGRP] [nvarchar] (3) NULL,
[LIFNR] [nvarchar] (10) NULL,
[WERKS] [nvarchar] (4) NULL,
[BSART] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[BWART] [nvarchar] (3) NULL,
[LGORT] [nvarchar] (4) NULL,
[TXNAM_SDB] [nvarchar] (16) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[XSTCEG] [nvarchar] (1) NULL,
[J_1ANUTIME] [nvarchar] (1) NULL,
[MAXBI] [nvarchar] (3) NULL,
[PLAUFZ] [nvarchar] (3) NULL,
[PLAUEZ] [nvarchar] (1) NULL,
[ZZKZVE] [nvarchar] (1) NULL,
[EtlSourceTable] [varchar] (200) NOT NULL
)
GO
