CREATE TABLE [tsa].[ics_land_Navision_ROU_SalesPerson_Purchaser]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_ROU_SalesPerson_Purchaser_ExcludedFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_ROU_SalesPerson_Purchaser_IsDuplicate] DEFAULT ((0)),
[timestamp] [varbinary] (8) NULL,
[Code] [varchar] (10) NOT NULL,
[Name] [varchar] (50) NULL,
[Commission %] [decimal] (38, 20) NULL,
[Global Dimension 1 Code] [varchar] (20) NULL,
[Global Dimension 2 Code] [varchar] (20) NULL,
[E-Mail] [varchar] (80) NULL,
[Phone No_] [varchar] (30) NULL,
[Job Title] [varchar] (30) NULL,
[Search E-Mail] [varchar] (80) NULL,
[Outlook Contacts Folder Path] [varchar] (250) NULL,
[Outlook Tasks Folder Path] [varchar] (250) NULL,
[Outlook Calendar Folder Path] [varchar] (250) NULL,
[Navision User ID] [varchar] (20) NULL,
[Outlook User Name] [varchar] (80) NULL,
[Enable Synchronization] [tinyint] NULL,
[Outlook Profile Name] [varchar] (80) NULL,
[Outlook Contacts FolderID] [varbinary] (max) NULL,
[Outlook Tasks FolderID] [varbinary] (max) NULL,
[Outlook Calendar FolderID] [varbinary] (max) NULL,
[Outlook Contacts StoreID] [varbinary] (max) NULL,
[Outlook Tasks StoreID] [varbinary] (max) NULL,
[Outlook Calendar StoreID] [varbinary] (max) NULL,
[Notify about Contact Changes] [tinyint] NULL,
[Notify about Task Changes] [tinyint] NULL,
[Notify about Appmt_ Changes] [tinyint] NULL,
[Synchronize From] [varchar] (32) NULL,
[Synchronize To] [varchar] (32) NULL,
[Synchronize To-dos] [int] NULL,
[Version No_] [int] NULL,
[Notify about Team To-do Chgs_] [tinyint] NULL,
[Empty SalesPerson_Purch Code] [tinyint] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_ROU_SalesPerson_Purchaser] ON [tsa].[ics_land_Navision_ROU_SalesPerson_Purchaser] ([Code])
GO
