CREATE TABLE [tsa].[ics_land_SAP_GBR_CSKS]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_CSKS_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_CSKS_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[KOKRS] [nvarchar] (4) NULL,
[KOSTL] [nvarchar] (10) NULL,
[DATBI] [datetime] NULL,
[DATAB] [datetime] NULL,
[BKZKP] [nvarchar] (1) NULL,
[PKZKP] [nvarchar] (1) NULL,
[BUKRS] [nvarchar] (4) NULL,
[GSBER] [nvarchar] (4) NULL,
[KOSAR] [nvarchar] (1) NULL,
[VERAK] [nvarchar] (20) NULL,
[VERAK_USER] [nvarchar] (12) NULL,
[WAERS] [nvarchar] (5) NULL,
[KALSM] [nvarchar] (6) NULL,
[TXJCD] [nvarchar] (15) NULL,
[PRCTR] [nvarchar] (10) NULL,
[WERKS] [nvarchar] (4) NULL,
[LOGSYSTEM] [nvarchar] (10) NULL,
[ERSDA] [datetime] NULL,
[USNAM] [nvarchar] (12) NULL,
[BKZKS] [nvarchar] (1) NULL,
[BKZER] [nvarchar] (1) NULL,
[BKZOB] [nvarchar] (1) NULL,
[PKZKS] [nvarchar] (1) NULL,
[PKZER] [nvarchar] (1) NULL,
[VMETH] [nvarchar] (2) NULL,
[MGEFL] [nvarchar] (1) NULL,
[ABTEI] [nvarchar] (12) NULL,
[NKOST] [nvarchar] (10) NULL,
[KVEWE] [nvarchar] (1) NULL,
[KAPPL] [nvarchar] (2) NULL,
[KOSZSCHL] [nvarchar] (6) NULL,
[LAND1] [nvarchar] (3) NULL,
[ANRED] [nvarchar] (15) NULL,
[NAME1] [nvarchar] (35) NULL,
[NAME2] [nvarchar] (35) NULL,
[NAME3] [nvarchar] (35) NULL,
[NAME4] [nvarchar] (35) NULL,
[ORT01] [nvarchar] (35) NULL,
[ORT02] [nvarchar] (35) NULL,
[STRAS] [nvarchar] (35) NULL,
[PFACH] [nvarchar] (10) NULL,
[PSTLZ] [nvarchar] (10) NULL,
[PSTL2] [nvarchar] (10) NULL,
[REGIO] [nvarchar] (3) NULL,
[SPRAS] [nvarchar] (1) NULL,
[TELBX] [nvarchar] (15) NULL,
[TELF1] [nvarchar] (16) NULL,
[TELF2] [nvarchar] (16) NULL,
[TELFX] [nvarchar] (31) NULL,
[TELTX] [nvarchar] (30) NULL,
[TELX1] [nvarchar] (30) NULL,
[DATLT] [nvarchar] (14) NULL,
[DRNAM] [nvarchar] (4) NULL,
[KHINR] [nvarchar] (12) NULL,
[CCKEY] [nvarchar] (23) NULL,
[KOMPL] [nvarchar] (1) NULL,
[STAKZ] [nvarchar] (1) NULL,
[OBJNR] [nvarchar] (22) NULL,
[FUNKT] [nvarchar] (3) NULL,
[AFUNK] [nvarchar] (3) NULL,
[CPI_TEMPL] [nvarchar] (10) NULL,
[CPD_TEMPL] [nvarchar] (10) NULL,
[FUNC_AREA] [nvarchar] (16) NULL,
[SCI_TEMPL] [nvarchar] (10) NULL,
[SCD_TEMPL] [nvarchar] (10) NULL,
[VNAME] [nvarchar] (6) NULL,
[RECID] [nvarchar] (2) NULL,
[ETYPE] [nvarchar] (3) NULL,
[JV_OTYPE] [nvarchar] (4) NULL,
[JV_JIBCL] [nvarchar] (3) NULL,
[JV_JIBSA] [nvarchar] (5) NULL,
[FERC_IND] [nvarchar] (4) NULL
)
GO
