CREATE TABLE [tsa].[ics_land_Symfonia_ZL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_ZL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Symfonia_ZL_IsDuplicate] DEFAULT ((0)),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[cena] [float] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[data_real] [datetime] NULL,
[data_status] [datetime] NULL,
[dzial] [int] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[idkh] [int] NULL,
[idrn] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[iloscGotowa] [float] NULL,
[katalog] [int] NULL,
[kod] [varchar] (40) NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (40) NULL,
[okres] [smallint] NULL,
[opis] [varchar] (100) NULL,
[rodzaj] [int] NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[status] [smallint] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[typ] [smallint] NULL,
[typ_dk] [varchar] (4) NULL,
[znacznik] [smallint] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Symfonia_ZL_1] ON [tsa].[ics_land_Symfonia_ZL] ([id])
GO
