CREATE TABLE [tsa].[ics_land_M3V10ved_POL_MITBAL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_land_ved_MITBAL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_land_ved_MITBAL_IsDuplicate] DEFAULT ((0)),
[MBABCD] [nchar] (1) NULL,
[MBABCM] [numeric] (1, 0) NULL,
[MBABFC] [nchar] (1) NULL,
[MBABFM] [numeric] (1, 0) NULL,
[MBACOC] [nchar] (1) NULL,
[MBACOM] [numeric] (1, 0) NULL,
[MBAGDY] [numeric] (5, 0) NULL,
[MBAGHO] [numeric] (4, 0) NULL,
[MBALMT] [numeric] (1, 0) NULL,
[MBALQC] [numeric] (1, 0) NULL,
[MBALQT] [numeric] (15, 6) NULL,
[MBALS1] [numeric] (1, 0) NULL,
[MBALUN] [nchar] (3) NULL,
[MBAVAL] [numeric] (15, 6) NULL,
[MBAVST] [numeric] (15, 6) NULL,
[MBBALO] [numeric] (1, 0) NULL,
[MBBCOS] [numeric] (17, 6) NULL,
[MBBUYE] [nchar] (10) NULL,
[MBCDYN] [numeric] (1, 0) NULL,
[MBCHID] [nchar] (10) NULL,
[MBCHNO] [numeric] (3, 0) NULL,
[MBCOMG] [numeric] (1, 0) NULL,
[MBCONC] [numeric] (1, 0) NULL,
[MBCONO] [numeric] (3, 0) NULL,
[MBCPCD] [nchar] (3) NULL,
[MBDCSS] [numeric] (1, 0) NULL,
[MBDDEX] [numeric] (1, 0) NULL,
[MBDDLO] [nchar] (10) NULL,
[MBDIGR] [nchar] (2) NULL,
[MBDILE] [numeric] (15, 6) NULL,
[MBDIVI] [nchar] (3) NULL,
[MBDMFN] [numeric] (3, 0) NULL,
[MBDPID] [numeric] (2, 0) NULL,
[MBDPLO] [nchar] (10) NULL,
[MBDTID] [numeric] (13, 0) NULL,
[MBEOQM] [numeric] (2, 0) NULL,
[MBEOQT] [numeric] (15, 6) NULL,
[MBEQDA] [numeric] (3, 0) NULL,
[MBFACI] [nchar] (3) NULL,
[MBFCCM] [nchar] (2) NULL,
[MBGRTS] [nchar] (5) NULL,
[MBIDDT] [numeric] (8, 0) NULL,
[MBINCD] [nchar] (3) NULL,
[MBINDT] [numeric] (8, 0) NULL,
[MBINSC] [numeric] (1, 0) NULL,
[MBINSL] [nchar] (10) NULL,
[MBITNO] [nchar] (15) NULL,
[MBKTEX] [numeric] (1, 0) NULL,
[MBLEA1] [numeric] (3, 0) NULL,
[MBLEA2] [numeric] (3, 0) NULL,
[MBLEA3] [numeric] (3, 0) NULL,
[MBLEAQ] [numeric] (3, 0) NULL,
[MBLEAT] [numeric] (3, 0) NULL,
[MBLEVD] [numeric] (2, 0) NULL,
[MBLEVL] [numeric] (2, 0) NULL,
[MBLMDT] [numeric] (8, 0) NULL,
[MBLMTS] [numeric] (18, 0) NULL,
[MBLOQT] [numeric] (15, 6) NULL,
[MBLRYE] [numeric] (15, 6) NULL,
[MBLYQT] [numeric] (15, 6) NULL,
[MBMABC] [nchar] (1) NULL,
[MBMNUN] [nchar] (3) NULL,
[MBMOQT] [numeric] (15, 6) NULL,
[MBMPCD] [numeric] (8, 0) NULL,
[MBMPCT] [numeric] (6, 0) NULL,
[MBMRPQ] [numeric] (15, 6) NULL,
[MBMRQT] [numeric] (15, 6) NULL,
[MBMSCH] [numeric] (1, 0) NULL,
[MBMSSQ] [numeric] (15, 6) NULL,
[MBMXPC] [numeric] (3, 0) NULL,
[MBMXSM] [numeric] (1, 0) NULL,
[MBMXST] [numeric] (15, 6) NULL,
[MBNCCA] [numeric] (1, 0) NULL,
[MBNUIN] [numeric] (4, 0) NULL,
[MBNUS7] [numeric] (7, 0) NULL,
[MBODDT] [numeric] (8, 0) NULL,
[MBOPLC] [numeric] (1, 0) NULL,
[MBOPOM] [numeric] (1, 0) NULL,
[MBORQT] [numeric] (15, 6) NULL,
[MBORTY] [nchar] (3) NULL,
[MBPAFL] [numeric] (1, 0) NULL,
[MBPFTM] [numeric] (3, 0) NULL,
[MBPISE] [nchar] (2) NULL,
[MBPLCD] [nchar] (2) NULL,
[MBPLHZ] [numeric] (3, 0) NULL,
[MBPLIC] [numeric] (1, 0) NULL,
[MBPLID] [numeric] (8, 0) NULL,
[MBPLIT] [numeric] (6, 0) NULL,
[MBPLNT] [nchar] (3) NULL,
[MBPLQT] [numeric] (15, 6) NULL,
[MBPOOT] [nchar] (3) NULL,
[MBPPMC] [numeric] (1, 0) NULL,
[MBPRCD] [nchar] (2) NULL,
[MBPRDC] [numeric] (1, 0) NULL,
[MBPRIF] [numeric] (3, 0) NULL,
[MBPUIT] [numeric] (1, 0) NULL,
[MBQUCW] [numeric] (15, 6) NULL,
[MBQUQT] [numeric] (15, 6) NULL,
[MBREDY] [numeric] (5, 0) NULL,
[MBREOP] [numeric] (15, 6) NULL,
[MBREQP] [numeric] (15, 6) NULL,
[MBREQT] [numeric] (15, 6) NULL,
[MBRESP] [nchar] (10) NULL,
[MBRGDT] [numeric] (8, 0) NULL,
[MBRGTM] [numeric] (6, 0) NULL,
[MBRJCW] [numeric] (15, 6) NULL,
[MBRJQT] [numeric] (15, 6) NULL,
[MBRLQT] [numeric] (15, 6) NULL,
[MBRPOP] [numeric] (1, 0) NULL,
[MBSAEL] [numeric] (5, 0) NULL,
[MBSALM] [numeric] (1, 0) NULL,
[MBSATD] [numeric] (3, 0) NULL,
[MBSCGR] [numeric] (3, 1) NULL,
[MBSCHT] [numeric] (1, 0) NULL,
[MBSCPO] [nchar] (3) NULL,
[MBSESO] [numeric] (1, 0) NULL,
[MBSHCC] [numeric] (1, 0) NULL,
[MBSLDY] [numeric] (5, 0) NULL,
[MBSLTP] [nchar] (2) NULL,
[MBSODY] [numeric] (3, 0) NULL,
[MBSPLC] [nchar] (2) NULL,
[MBSPMT] [numeric] (1, 0) NULL,
[MBSSDA] [numeric] (3, 0) NULL,
[MBSSMT] [numeric] (1, 0) NULL,
[MBSSQT] [numeric] (15, 6) NULL,
[MBSTAT] [nchar] (2) NULL,
[MBSTCW] [numeric] (15, 6) NULL,
[MBSTMT] [numeric] (1, 0) NULL,
[MBSTQT] [numeric] (15, 6) NULL,
[MBSTRL] [numeric] (1, 0) NULL,
[MBSTTX] [nvarchar] (30) NULL,
[MBSUNO] [nchar] (10) NULL,
[MBSUWH] [nchar] (3) NULL,
[MBSVEI] [numeric] (1, 0) NULL,
[MBTOMU] [numeric] (15, 6) NULL,
[MBTXID] [numeric] (13, 0) NULL,
[MBUNMU] [numeric] (15, 6) NULL,
[MBUSYE] [numeric] (15, 6) NULL,
[MBVTCP] [numeric] (2, 0) NULL,
[MBVTCS] [numeric] (2, 0) NULL,
[MBWHLO] [nchar] (3) NULL,
[MBWHLT] [nchar] (2) NULL,
[MBWHSL] [nchar] (10) NULL,
[MBWHSY] [nchar] (1) NULL,
[MBWHTY] [nchar] (2) NULL,
[MBYEQM] [numeric] (1, 0) NULL,
[MBYEQT] [numeric] (15, 6) NULL,
[MBZCAC] [numeric] (1, 0) NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10ved_POL_MITBAL_1] ON [tsa].[ics_land_M3V10ved_POL_MITBAL] ([MBCONO], [MBITNO], [MBWHLO])
GO
EXEC sp_addextendedproperty N'MS_Description', N'Mandatory reference to the database-specific unique identifier for the original source system of this data record.', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'DataSourceKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The Batch Run Id context in which this record was added or last updated on this table – soft link back to the Batch Management database (BMI_BAT_MAN).', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'EtlBatchRunId'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name of the module or mapping within the ETL process that was responsible for this record being added to this table.', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'EtlCreatedBy'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ETL system date and time that the ETL process first added this record to this table.', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'EtlCreatedOn'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name of the only or main table or object in the source system of record from which this row was extracted', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'EtlSourceTable'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The Step Run Id context (within a Batch Run) in which this record was added or last updated on this table – soft link back to the Batch Management database (BMI_BAT_MAN).', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'EtlStepRunId'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The Thread Run Id context (within a Step Run) in which this record was added or last updated on this table – soft link back to the Batch Management database (BMI_BAT_MAN).', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'EtlThreadRunId'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used as part of ETL processing when merging from TSA to PSA.  Indicates that this row should not be merged to PSA for some reason - e.g. becuae it is a possible duplicate.', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'ExcludeFromMerge'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used as part of ETL processing when merging from TSA to PSA. Indicates that this row is a suspected duplicate, one reason why a row might be excluded from the TSA-to-PSA merge.', 'SCHEMA', N'tsa', 'TABLE', N'ics_land_M3V10ved_POL_MITBAL', 'COLUMN', N'IsDuplicate'
GO
