CREATE TABLE [tsa].[ICS_LAND_SAP_GBR_KNVK]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[PARNR] [nvarchar] (10) NULL,
[KUNNR] [nvarchar] (10) NULL,
[NAMEV] [nvarchar] (35) NULL,
[NAME1] [nvarchar] (35) NULL,
[ORT01] [nvarchar] (35) NULL,
[ADRND] [nvarchar] (10) NULL,
[ADRNP] [nvarchar] (10) NULL,
[ABTPA] [nvarchar] (12) NULL,
[ABTNR] [nvarchar] (4) NULL,
[UEPAR] [nvarchar] (10) NULL,
[TELF1] [nvarchar] (16) NULL,
[ANRED] [nvarchar] (30) NULL,
[PAFKT] [nvarchar] (2) NULL,
[PARVO] [nvarchar] (1) NULL,
[PAVIP] [nvarchar] (1) NULL,
[PARGE] [nvarchar] (1) NULL,
[PARLA] [nvarchar] (1) NULL,
[GBDAT] [datetime] NULL,
[VRTNR] [nvarchar] (10) NULL,
[BRYTH] [nvarchar] (4) NULL,
[AKVER] [nvarchar] (2) NULL,
[NMAIL] [nvarchar] (1) NULL,
[PARAU] [nvarchar] (40) NULL,
[PARH1] [nvarchar] (2) NULL,
[PARH2] [nvarchar] (2) NULL,
[PARH3] [nvarchar] (2) NULL,
[PARH4] [nvarchar] (2) NULL,
[PARH5] [nvarchar] (2) NULL,
[MOAB1] [datetime] NULL,
[MOBI1] [datetime] NULL,
[MOAB2] [datetime] NULL,
[MOBI2] [datetime] NULL,
[DIAB1] [datetime] NULL,
[DIBI1] [datetime] NULL,
[DIAB2] [datetime] NULL,
[DIBI2] [datetime] NULL,
[MIAB1] [datetime] NULL,
[MIBI1] [datetime] NULL,
[MIAB2] [datetime] NULL,
[MIBI2] [datetime] NULL,
[DOAB1] [datetime] NULL,
[DOBI1] [datetime] NULL,
[DOAB2] [datetime] NULL,
[DOBI2] [datetime] NULL,
[FRAB1] [datetime] NULL,
[FRBI1] [datetime] NULL,
[FRAB2] [datetime] NULL,
[FRBI2] [datetime] NULL,
[SAAB1] [datetime] NULL,
[SABI1] [datetime] NULL,
[SAAB2] [datetime] NULL,
[SABI2] [datetime] NULL,
[SOAB1] [datetime] NULL,
[SOBI1] [datetime] NULL,
[SOAB2] [datetime] NULL,
[SOBI2] [datetime] NULL,
[PAKN1] [nvarchar] (3) NULL,
[PAKN2] [nvarchar] (3) NULL,
[PAKN3] [nvarchar] (3) NULL,
[PAKN4] [nvarchar] (3) NULL,
[PAKN5] [nvarchar] (3) NULL,
[SORTL] [nvarchar] (10) NULL,
[FAMST] [nvarchar] (1) NULL,
[SPNAM] [nvarchar] (10) NULL,
[TITEL_AP] [nvarchar] (35) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[DUEFL] [nvarchar] (1) NULL,
[LIFNR] [nvarchar] (10) NULL,
[LOEVM] [nvarchar] (1) NULL,
[KZHERK] [nvarchar] (1) NULL,
[ADRNP_2] [nvarchar] (10) NULL,
[PRSNR] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NOT NULL
)
GO
