CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchases & Payables Setup]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchases & Payables Setup_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchases & Payables Setup_IsDuplicate] DEFAULT ((0)),
[Allow VAT Difference] [tinyint] NULL,
[Appln_ between Currencies] [int] NULL,
[Archive Quotes and Orders] [tinyint] NULL,
[Blanket Order Nos_] [varchar] (10) NULL,
[Calc_ Inv_ Disc_ per VAT ID] [tinyint] NULL,
[Calc_ Inv_ Discount] [tinyint] NULL,
[Check Prepmt_ when Posting] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Cr_ Memo] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Ret_Shpt] [tinyint] NULL,
[Copy Comments Blanket to Order] [tinyint] NULL,
[Copy Comments Order to Invoice] [tinyint] NULL,
[Copy Comments Order to Receipt] [tinyint] NULL,
[Credit Memo Nos_] [varchar] (10) NULL,
[Default Posting Date] [int] NULL,
[Default Qty_ to Ship_Rcv_] [int] NULL,
[Discount Posting] [int] NULL,
[EU VAT Bus_ Posting Group] [varchar] (20) NULL,
[Exact Cost Reversing Mandatory] [tinyint] NULL,
[Ext_ Doc_ No_ Mandatory] [tinyint] NULL,
[Intr_ Jnl_ Incl_ Item Charges] [tinyint] NULL,
[Invoice Nos_] [varchar] (10) NULL,
[Invoice Rounding] [tinyint] NULL,
[Order Nos_] [varchar] (10) NULL,
[Posted Credit Memo Nos_] [varchar] (10) NULL,
[Posted Invoice Nos_] [varchar] (10) NULL,
[Posted Prepmt_ Cr_ Memo Nos_] [varchar] (10) NULL,
[Posted Prepmt_ Inv_ Nos_] [varchar] (10) NULL,
[Posted Receipt Nos_] [varchar] (10) NULL,
[Posted Return Shpt_ Nos_] [varchar] (10) NULL,
[Posted Unreal_ VAT Prot_ Nos_] [varchar] (20) NULL,
[Primary Key] [varchar] (10) NULL,
[Protokol VAT Bus_ Post_ Group] [varchar] (20) NULL,
[Quote Nos_] [varchar] (10) NULL,
[Receipt on Invoice] [tinyint] NULL,
[Return Order Nos_] [varchar] (10) NULL,
[Return Shipment on Credit Memo] [tinyint] NULL,
[timestamp] [varbinary] (max) NULL,
[Unreal_ VAT Prot_ Nos_] [varchar] (20) NULL,
[Vendor Nos_] [varchar] (10) NULL
)
GO
