CREATE TABLE [tsa].[ics_land_SAP_SVK_EKET]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKET_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_SVK_EKET_IsDuplicate] DEFAULT ((0)),
[ABART] [nvarchar] (1) NULL,
[ALTDT] [nvarchar] (8) NULL,
[AMENG] [decimal] (13, 3) NULL,
[AULWE] [nvarchar] (10) NULL,
[BANFN] [nvarchar] (10) NULL,
[BEDAT] [nvarchar] (8) NULL,
[BNFPO] [nvarchar] (5) NULL,
[CCI] [nvarchar] (1) NULL,
[CHARG] [nvarchar] (10) NULL,
[CHKOM] [nvarchar] (1) NULL,
[DABMG] [decimal] (13, 3) NULL,
[DAT01] [nvarchar] (8) NULL,
[DNO] [nvarchar] (12) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[ECC] [nvarchar] (7) NULL,
[EINDT] [nvarchar] (8) NULL,
[ESTKZ] [nvarchar] (1) NULL,
[ETENR] [nvarchar] (4) NULL,
[FIXKZ] [nvarchar] (1) NULL,
[GLMNG] [decimal] (13, 3) NULL,
[LDDAT] [nvarchar] (8) NULL,
[LDUHR] [nvarchar] (6) NULL,
[LICHA] [nvarchar] (15) NULL,
[LPEIN] [nvarchar] (1) NULL,
[MAHNZ] [decimal] (3, 0) NULL,
[MANDT] [nvarchar] (3) NULL,
[MBDAT] [nvarchar] (8) NULL,
[MBUHR] [nvarchar] (6) NULL,
[MENGE] [decimal] (13, 3) NULL,
[MNG02] [decimal] (13, 3) NULL,
[PCCI] [nvarchar] (1) NULL,
[PLC] [nvarchar] (1) NULL,
[PSEL] [nvarchar] (1) NULL,
[PSEN] [nvarchar] (6) NULL,
[QUNUM] [nvarchar] (10) NULL,
[QUPOS] [nvarchar] (3) NULL,
[RSNUM] [nvarchar] (10) NULL,
[SEL] [nvarchar] (1) NULL,
[SEN] [nvarchar] (6) NULL,
[SERNR] [nvarchar] (8) NULL,
[SHM] [nvarchar] (3) NULL,
[SLFDT] [nvarchar] (8) NULL,
[SMB] [nvarchar] (6) NULL,
[TDDAT] [nvarchar] (8) NULL,
[TDUHR] [nvarchar] (6) NULL,
[UZEIT] [nvarchar] (6) NULL,
[VERID] [nvarchar] (4) NULL,
[WADAT] [nvarchar] (8) NULL,
[WAMNG] [decimal] (13, 3) NULL,
[WAUHR] [nvarchar] (6) NULL,
[WEMNG] [decimal] (13, 3) NULL
)
GO
