CREATE TABLE [tsa].[ics_land_SAP_GBR_VBFA]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBFA_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_SAP_GBR_VBFA_IsDuplicate] DEFAULT ((0)),
[MANDT] [nvarchar] (3) NULL,
[VBELV] [nvarchar] (10) NULL,
[POSNV] [nvarchar] (6) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNN] [nvarchar] (6) NULL,
[VBTYP_N] [nvarchar] (1) NULL,
[RFMNG] [decimal] (15, 3) NULL,
[MEINS] [nvarchar] (3) NULL,
[RFWRT] [decimal] (15, 2) NULL,
[WAERS] [nvarchar] (5) NULL,
[VBTYP_V] [nvarchar] (1) NULL,
[PLMIN] [nvarchar] (1) NULL,
[TAQUI] [nvarchar] (1) NULL,
[ERDAT] [datetime] NULL,
[ERZET] [datetime] NULL,
[MATNR] [nvarchar] (18) NULL,
[BWART] [nvarchar] (3) NULL,
[BDART] [nvarchar] (2) NULL,
[PLART] [nvarchar] (1) NULL,
[STUFE] [nvarchar] (2) NULL,
[LGNUM] [nvarchar] (3) NULL,
[AEDAT] [datetime] NULL,
[FKTYP] [nvarchar] (1) NULL,
[BRGEW] [decimal] (15, 3) NULL,
[GEWEI] [nvarchar] (3) NULL,
[VOLUM] [decimal] (15, 3) NULL,
[VOLEH] [nvarchar] (3) NULL,
[FPLNR] [nvarchar] (10) NULL,
[FPLTR] [nvarchar] (6) NULL,
[RFMNG_FLO] [float] NULL,
[RFMNG_FLT] [float] NULL,
[VRKME] [nvarchar] (3) NULL,
[ABGES] [float] NULL,
[SOBKZ] [nvarchar] (1) NULL,
[SONUM] [nvarchar] (16) NULL,
[KZBEF] [nvarchar] (1) NULL,
[NTGEW] [decimal] (13, 3) NULL,
[LOGSYS] [nvarchar] (10) NULL,
[WBSTA] [nvarchar] (1) NULL,
[CMETH] [nvarchar] (1) NULL,
[MJAHR] [nvarchar] (4) NULL
)
GO
