CREATE TABLE [tsa].[ics_land_baan_ttdpur010610]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_ttdpur010610_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_ttdpur010610_IsDuplicate] DEFAULT ((0)),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cbrn] [varchar] (6) NULL,
[t_ccon] [int] NULL,
[t_ccor] [varchar] (3) NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdec] [varchar] (3) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_cpay] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_creg] [varchar] (3) NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_fixr] [tinyint] NULL,
[t_odis] [real] NULL,
[t_qdat] [datetime] NULL,
[t_qono] [int] NULL,
[t_ratf] [int] NULL,
[t_ratp] [float] NULL,
[t_refa] [varchar] (30) NULL,
[t_refb] [varchar] (20) NULL,
[t_rpdt] [datetime] NULL,
[t_rtdt] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_trdt] [datetime] NULL,
[t_trtm] [int] NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_baan_ttdpur010610_1] ON [tsa].[ics_land_baan_ttdpur010610] ([t_qono], [t_trdt], [t_trtm])
GO
