CREATE TABLE [tsa].[ics_land_baan_ttdpur301610]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_ttdpur301610_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_ttdpur301610_IsDuplicate] DEFAULT ((0)),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_bamt] [float] NULL,
[t_bqan] [float] NULL,
[t_camt] [float] NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdat] [datetime] NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_citt] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cqan] [float] NULL,
[t_cupp] [varchar] (3) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvpp] [float] NULL,
[t_cvqp] [float] NULL,
[t_cwar] [varchar] (3) NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_icyp] [tinyint] NULL,
[t_ieva] [tinyint] NULL,
[t_ipri] [tinyint] NULL,
[t_iqab] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_maxq] [float] NULL,
[t_minq] [float] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_quan] [float] NULL,
[t_sdsc] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_txta] [int] NULL,
[t_widt] [float] NULL
)
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_baan_ttdpur301610_1] ON [tsa].[ics_land_baan_ttdpur301610] ([t_cono], [t_pono])
GO
