CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Salesperson_Purchaser]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_IsDuplicate] DEFAULT ((0)),
[Code] [varchar] (10) NULL,
[Commission_%] [decimal] (38, 20) NULL,
[E-Mail] [varchar] (80) NULL,
[Empty_SalesPerson_Purch_Code] [tinyint] NULL,
[Enable_Synchronization] [tinyint] NULL,
[Global_Dimension_1_Code] [varchar] (20) NULL,
[Global_Dimension_2_Code] [varchar] (20) NULL,
[Job_Title] [varchar] (30) NULL,
[Name] [varchar] (50) NULL,
[Navision_User_ID] [varchar] (20) NULL,
[Notify_about_Appmt__Changes] [tinyint] NULL,
[Notify_about_Contact_Changes] [tinyint] NULL,
[Notify_about_Task_Changes] [tinyint] NULL,
[Notify_about_Team_To-do_Chgs_] [tinyint] NULL,
[Outlook_Calendar_Folder_Path] [varchar] (250) NULL,
[Outlook_Calendar_FolderID] [image] NULL,
[Outlook_Calendar_StoreID] [image] NULL,
[Outlook_Contacts_Folder_Path] [varchar] (250) NULL,
[Outlook_Contacts_FolderID] [image] NULL,
[Outlook_Contacts_StoreID] [image] NULL,
[Outlook_Profile_Name] [varchar] (80) NULL,
[Outlook_Tasks_Folder_Path] [varchar] (250) NULL,
[Outlook_Tasks_FolderID] [image] NULL,
[Outlook_Tasks_StoreID] [image] NULL,
[Outlook_User_Name] [varchar] (80) NULL,
[Phone_No_] [varchar] (30) NULL,
[Search_E-Mail] [varchar] (80) NULL,
[Synchronize_From] [varchar] (32) NULL,
[Synchronize_To] [varchar] (32) NULL,
[Synchronize_To-dos] [int] NULL,
[Version_No_] [int] NULL,
[timestamp] [timestamp] NOT NULL
)
GO
