CREATE TABLE [tsa].[PU_LINK_CATEGORY]
(
[CATEGORY_ID] [int] NOT NULL,
[SYSTEM_ID] [int] NOT NULL,
[MATERIAL_CODE] [varchar] (50) NOT NULL,
[CREATE_BY] [varchar] (100) NULL,
[CREATE_DATE] [datetime] NULL
)
GO
ALTER TABLE [tsa].[PU_LINK_CATEGORY] ADD CONSTRAINT [PK_PU_LINK_CATEGORY_1] PRIMARY KEY CLUSTERED  ([CATEGORY_ID], [SYSTEM_ID], [MATERIAL_CODE])
GO
