-- <Migration ID="d64e63ad-9c07-4191-ba60-15bede59ca31" />
GO

PRINT N'Creating [psa].[ics_stg_m3_FGINLI]'
GO
CREATE TABLE [psa].[ics_stg_m3_FGINLI]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_FGINLI_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_FGINLI_IsIncomplete] DEFAULT ((0)),
[F5ACDT] [decimal] (8, 0) NULL,
[F5ADDG] [decimal] (15, 2) NULL,
[F5ATNB] [decimal] (17, 0) NULL,
[F5ATNR] [decimal] (17, 0) NULL,
[F5CHID] [nvarchar] (255) NULL,
[F5CHNO] [decimal] (3, 0) NULL,
[F5CONO] [decimal] (3, 0) NULL,
[F5DIVI] [nvarchar] (255) NULL,
[F5DNCM] [decimal] (15, 2) NULL,
[F5DNNR] [nvarchar] (255) NULL,
[F5DNPR] [decimal] (17, 6) NULL,
[F5DNQA] [decimal] (15, 6) NULL,
[F5DNQT] [decimal] (15, 6) NULL,
[F5DNRP] [nvarchar] (255) NULL,
[F5DNRQ] [nvarchar] (255) NULL,
[F5ECLC] [nvarchar] (255) NULL,
[F5FIAS] [decimal] (1, 0) NULL,
[F5HDPR] [nvarchar] (255) NULL,
[F5ICAC] [decimal] (15, 2) NULL,
[F5IMDT] [decimal] (8, 0) NULL,
[F5IMST] [decimal] (1, 0) NULL,
[F5INLP] [decimal] (1, 0) NULL,
[F5INS1] [nvarchar] (255) NULL,
[F5INS2] [nvarchar] (255) NULL,
[F5INS3] [nvarchar] (255) NULL,
[F5INS4] [nvarchar] (255) NULL,
[F5INS5] [nvarchar] (255) NULL,
[F5INYR] [decimal] (4, 0) NULL,
[F5IVCW] [decimal] (15, 6) NULL,
[F5IVDI] [decimal] (5, 2) NULL,
[F5IVLC] [decimal] (15, 2) NULL,
[F5IVNA] [decimal] (15, 2) NULL,
[F5IVOC] [decimal] (17, 6) NULL,
[F5IVQA] [decimal] (15, 6) NULL,
[F5IVQT] [decimal] (15, 6) NULL,
[F5LMDT] [decimal] (8, 0) NULL,
[F5OPTX] [nvarchar] (255) NULL,
[F5OPTY] [nvarchar] (255) NULL,
[F5OPTZ] [nvarchar] (255) NULL,
[F5PNLI] [decimal] (3, 0) NULL,
[F5PNLS] [decimal] (3, 0) NULL,
[F5PPUN] [nvarchar] (255) NULL,
[F5PUCD] [decimal] (5, 0) NULL,
[F5PUNO] [nvarchar] (255) NULL,
[F5PUUN] [nvarchar] (255) NULL,
[F5RCAC] [decimal] (15, 2) NULL,
[F5RELP] [decimal] (1, 0) NULL,
[F5REPN] [decimal] (10, 0) NULL,
[F5RGDT] [decimal] (8, 0) NULL,
[F5RGTM] [decimal] (6, 0) NULL,
[F5RPQA] [decimal] (15, 6) NULL,
[F5RPQT] [decimal] (15, 6) NULL,
[F5SERA] [decimal] (11, 6) NULL,
[F5SERS] [decimal] (2, 0) NULL,
[F5SINO] [nvarchar] (255) NULL,
[F5SUNO] [nvarchar] (255) NULL,
[F5TXID] [decimal] (13, 0) NULL,
[F5VRCD] [nvarchar] (255) NULL,
[F5VTCD] [decimal] (2, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_m3_FPLEDG]'
GO
CREATE TABLE [psa].[ics_stg_m3_FPLEDG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_FPLEDG_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_FPLEDG_IsIncomplete] DEFAULT ((0)),
[EPACDT] [decimal] (8, 0) NULL,
[EPAPCD] [nvarchar] (255) NULL,
[EPAPRV] [decimal] (1, 0) NULL,
[EPARAT] [decimal] (11, 6) NULL,
[EPARCD] [decimal] (1, 0) NULL,
[EPBKID] [nvarchar] (255) NULL,
[EPBLBY] [nvarchar] (255) NULL,
[EPBLDT] [decimal] (8, 0) NULL,
[EPCHID] [nvarchar] (255) NULL,
[EPCHNO] [decimal] (3, 0) NULL,
[EPCONO] [decimal] (3, 0) NULL,
[EPCRTP] [decimal] (2, 0) NULL,
[EPCUAM] [decimal] (15, 2) NULL,
[EPCUCD] [nvarchar] (255) NULL,
[EPDCAM] [decimal] (1, 0) NULL,
[EPDEDA] [decimal] (8, 0) NULL,
[EPDIVI] [nvarchar] (255) NULL,
[EPDUDT] [decimal] (8, 0) NULL,
[EPENME] [decimal] (1, 0) NULL,
[EPGEOC] [decimal] (9, 0) NULL,
[EPINYR] [decimal] (4, 0) NULL,
[EPIVBL] [decimal] (1, 0) NULL,
[EPIVCL] [nvarchar] (255) NULL,
[EPIVDT] [decimal] (8, 0) NULL,
[EPIVTP] [nvarchar] (255) NULL,
[EPJRNO] [decimal] (7, 0) NULL,
[EPJSNO] [decimal] (7, 0) NULL,
[EPLMDT] [decimal] (8, 0) NULL,
[EPLMTS] [decimal] (18, 0) NULL,
[EPPYME] [nvarchar] (255) NULL,
[EPPYRS] [nvarchar] (255) NULL,
[EPPYST] [decimal] (1, 0) NULL,
[EPPYTP] [nvarchar] (255) NULL,
[EPRECO] [decimal] (1, 0) NULL,
[EPREDE] [decimal] (8, 0) NULL,
[EPRGDT] [decimal] (8, 0) NULL,
[EPRGTM] [decimal] (6, 0) NULL,
[EPSINO] [nvarchar] (255) NULL,
[EPSLOP] [decimal] (2, 0) NULL,
[EPSPYN] [nvarchar] (255) NULL,
[EPSUCL] [nvarchar] (255) NULL,
[EPSUNO] [nvarchar] (255) NULL,
[EPTDCD] [nvarchar] (255) NULL,
[EPTDSC] [nvarchar] (255) NULL,
[EPTECD] [nvarchar] (255) NULL,
[EPTEPY] [nvarchar] (255) NULL,
[EPTRCD] [decimal] (2, 0) NULL,
[EPTXID] [decimal] (13, 0) NULL,
[EPTXIN] [decimal] (1, 0) NULL,
[EPVONO] [decimal] (8, 0) NULL,
[EPVSER] [nvarchar] (255) NULL,
[EPVTAM] [decimal] (15, 2) NULL,
[EPYEA4] [decimal] (4, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_m3_MPLINE]'
GO
CREATE TABLE [psa].[ics_stg_m3_MPLINE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_MPLINE_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_MPLINE_IsIncomplete] DEFAULT ((0)),
[IBACLI] [decimal] (1, 0) NULL,
[IBACRF] [nvarchar] (255) NULL,
[IBADQA] [decimal] (15, 6) NULL,
[IBAGNB] [nvarchar] (255) NULL,
[IBATDT] [decimal] (8, 0) NULL,
[IBATNR] [decimal] (17, 0) NULL,
[IBATPR] [nvarchar] (255) NULL,
[IBBANO] [nvarchar] (255) NULL,
[IBBAOR] [nvarchar] (255) NULL,
[IBBUYE] [nvarchar] (255) NULL,
[IBCAQA] [decimal] (15, 6) NULL,
[IBCDES] [nvarchar] (255) NULL,
[IBCFD1] [decimal] (5, 2) NULL,
[IBCFD2] [decimal] (5, 2) NULL,
[IBCFD3] [decimal] (5, 2) NULL,
[IBCFIN] [decimal] (10, 0) NULL,
[IBCFMB] [decimal] (15, 9) NULL,
[IBCFPB] [decimal] (15, 9) NULL,
[IBCFQA] [decimal] (15, 6) NULL,
[IBCHCS] [nvarchar] (255) NULL,
[IBCHID] [nvarchar] (255) NULL,
[IBCHNO] [decimal] (3, 0) NULL,
[IBCIAD] [nvarchar] (255) NULL,
[IBCLAN] [nvarchar] (255) NULL,
[IBCLLI] [decimal] (1, 0) NULL,
[IBCLLN] [decimal] (3, 0) NULL,
[IBCOCE] [nvarchar] (255) NULL,
[IBCODT] [decimal] (8, 0) NULL,
[IBCOLO] [nvarchar] (255) NULL,
[IBCONO] [decimal] (3, 0) NULL,
[IBCPPR] [decimal] (17, 6) NULL,
[IBCPRI] [nvarchar] (255) NULL,
[IBCPUC] [decimal] (5, 0) NULL,
[IBCSNO] [nvarchar] (255) NULL,
[IBDNDT] [decimal] (8, 0) NULL,
[IBDT4T] [decimal] (1, 0) NULL,
[IBDTID] [decimal] (13, 0) NULL,
[IBDUPL] [decimal] (1, 0) NULL,
[IBDUPO] [nvarchar] (255) NULL,
[IBDWCP] [decimal] (1, 0) NULL,
[IBDWDT] [decimal] (8, 0) NULL,
[IBECDD] [decimal] (8, 0) NULL,
[IBECF1] [nvarchar] (255) NULL,
[IBECF2] [nvarchar] (255) NULL,
[IBECF3] [nvarchar] (255) NULL,
[IBECF4] [nvarchar] (255) NULL,
[IBECF5] [nvarchar] (255) NULL,
[IBECLC] [nvarchar] (255) NULL,
[IBECVE] [nvarchar] (255) NULL,
[IBECVS] [decimal] (3, 0) NULL,
[IBELNO] [nvarchar] (255) NULL,
[IBETRF] [nvarchar] (255) NULL,
[IBEXAT] [decimal] (1, 0) NULL,
[IBEXAV] [decimal] (1, 0) NULL,
[IBEXEP] [decimal] (15, 2) NULL,
[IBFACI] [nvarchar] (255) NULL,
[IBFATP] [nvarchar] (255) NULL,
[IBFRRC] [decimal] (1, 0) NULL,
[IBFRRE] [decimal] (12, 0) NULL,
[IBFSCD] [decimal] (1, 0) NULL,
[IBFUSC] [nvarchar] (255) NULL,
[IBGEOC] [decimal] (9, 0) NULL,
[IBGETY] [nvarchar] (255) NULL,
[IBGRMT] [nvarchar] (255) NULL,
[IBHAFE] [nvarchar] (255) NULL,
[IBHDPR] [nvarchar] (255) NULL,
[IBIDAG] [decimal] (1, 0) NULL,
[IBIDAT] [decimal] (8, 0) NULL,
[IBINEP] [decimal] (15, 2) NULL,
[IBIRCV] [nvarchar] (255) NULL,
[IBITNO] [nvarchar] (255) NULL,
[IBIVQA] [decimal] (15, 6) NULL,
[IBLICC] [nvarchar] (255) NULL,
[IBLMDT] [decimal] (8, 0) NULL,
[IBLMTS] [decimal] (18, 0) NULL,
[IBLNAM] [decimal] (15, 2) NULL,
[IBLPUD] [decimal] (8, 0) NULL,
[IBLTPP] [nvarchar] (255) NULL,
[IBMODL] [nvarchar] (255) NULL,
[IBMSTN] [decimal] (10, 0) NULL,
[IBNOED] [decimal] (1, 0) NULL,
[IBNPDE] [decimal] (3, 0) NULL,
[IBODI1] [decimal] (5, 2) NULL,
[IBODI2] [decimal] (5, 2) NULL,
[IBODI3] [decimal] (5, 2) NULL,
[IBOEND] [decimal] (1, 0) NULL,
[IBOFCI] [nvarchar] (255) NULL,
[IBOPTX] [nvarchar] (255) NULL,
[IBOPTY] [nvarchar] (255) NULL,
[IBOPTZ] [nvarchar] (255) NULL,
[IBORAD] [nvarchar] (255) NULL,
[IBORCO] [nvarchar] (255) NULL,
[IBORQA] [decimal] (15, 6) NULL,
[IBORTY] [nvarchar] (255) NULL,
[IBOTOD] [decimal] (1, 0) NULL,
[IBOURR] [nvarchar] (255) NULL,
[IBOURT] [nvarchar] (255) NULL,
[IBOWHL] [nvarchar] (255) NULL,
[IBPACT] [nvarchar] (255) NULL,
[IBPDDT] [decimal] (8, 0) NULL,
[IBPGRN] [decimal] (7, 0) NULL,
[IBPIAD] [nvarchar] (255) NULL,
[IBPITD] [nvarchar] (255) NULL,
[IBPITT] [nvarchar] (255) NULL,
[IBPLDT] [decimal] (8, 0) NULL,
[IBPLPN] [decimal] (7, 0) NULL,
[IBPLPS] [decimal] (3, 0) NULL,
[IBPNLI] [decimal] (3, 0) NULL,
[IBPNLS] [decimal] (3, 0) NULL,
[IBPOTC] [nvarchar] (255) NULL,
[IBPPUN] [nvarchar] (255) NULL,
[IBPRCS] [nvarchar] (255) NULL,
[IBPRIP] [nvarchar] (255) NULL,
[IBPROD] [nvarchar] (255) NULL,
[IBPROJ] [nvarchar] (255) NULL,
[IBPSET] [decimal] (1, 0) NULL,
[IBPTCD] [decimal] (1, 0) NULL,
[IBPUCD] [decimal] (5, 0) NULL,
[IBPUNO] [nvarchar] (255) NULL,
[IBPUPR] [decimal] (17, 6) NULL,
[IBPURC] [nvarchar] (255) NULL,
[IBPUSL] [nvarchar] (255) NULL,
[IBPUST] [nvarchar] (255) NULL,
[IBPUUN] [nvarchar] (255) NULL,
[IBRASN] [nvarchar] (255) NULL,
[IBRCDT] [decimal] (8, 0) NULL,
[IBRE20] [nvarchar] (255) NULL,
[IBREPP] [decimal] (1, 0) NULL,
[IBRESF] [nvarchar] (255) NULL,
[IBREVN] [nvarchar] (255) NULL,
[IBRGDT] [decimal] (8, 0) NULL,
[IBRGTM] [decimal] (6, 0) NULL,
[IBRJQA] [decimal] (15, 6) NULL,
[IBRORC] [decimal] (1, 0) NULL,
[IBRORL] [decimal] (6, 0) NULL,
[IBRORN] [nvarchar] (255) NULL,
[IBRORX] [decimal] (3, 0) NULL,
[IBRRQA] [decimal] (15, 6) NULL,
[IBRVQA] [decimal] (15, 6) NULL,
[IBSDES] [nvarchar] (255) NULL,
[IBSDQA] [decimal] (15, 6) NULL,
[IBSEBI] [nvarchar] (255) NULL,
[IBSEQN] [decimal] (7, 0) NULL,
[IBSFLI] [decimal] (3, 0) NULL,
[IBSFLS] [decimal] (3, 0) NULL,
[IBSITE] [nvarchar] (255) NULL,
[IBSIZE] [nvarchar] (255) NULL,
[IBSORN] [nvarchar] (255) NULL,
[IBSRCD] [decimal] (1, 0) NULL,
[IBSUAG] [nvarchar] (255) NULL,
[IBSUDO] [nvarchar] (255) NULL,
[IBSUFI] [nvarchar] (255) NULL,
[IBSUNO] [nvarchar] (255) NULL,
[IBTAXC] [nvarchar] (255) NULL,
[IBTEDL] [nvarchar] (255) NULL,
[IBTEL1] [nvarchar] (255) NULL,
[IBTERE] [nvarchar] (255) NULL,
[IBTIHM] [decimal] (4, 0) NULL,
[IBTNQA] [decimal] (15, 6) NULL,
[IBTRRC] [decimal] (1, 0) NULL,
[IBTRRL] [decimal] (6, 0) NULL,
[IBTRRN] [nvarchar] (255) NULL,
[IBTRRX] [decimal] (3, 0) NULL,
[IBTXID] [decimal] (13, 0) NULL,
[IBULEX] [decimal] (1, 0) NULL,
[IBUPAV] [decimal] (1, 0) NULL,
[IBUPCK] [decimal] (1, 0) NULL,
[IBUPIV] [decimal] (1, 0) NULL,
[IBVDDT] [decimal] (8, 0) NULL,
[IBVRCD] [nvarchar] (255) NULL,
[IBVTCD] [decimal] (2, 0) NULL,
[IBWHLO] [nvarchar] (255) NULL,
[IBWSCA] [nvarchar] (255) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_m3_MPLIND]'
GO
CREATE TABLE [psa].[ics_stg_m3_MPLIND]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_MPLIND_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3_MPLIND_IsIncomplete] DEFAULT ((0)),
[ICAGNB] [nvarchar] (255) NULL,
[ICARDT] [decimal] (8, 0) NULL,
[ICBANO] [nvarchar] (255) NULL,
[ICBOLN] [nvarchar] (255) NULL,
[ICCAMU] [nvarchar] (255) NULL,
[ICCARN] [nvarchar] (255) NULL,
[ICCHPO] [decimal] (1, 0) NULL,
[ICCONO] [decimal] (3, 0) NULL,
[ICDLIX] [decimal] (11, 0) NULL,
[ICDNDT] [decimal] (8, 0) NULL,
[ICDTID] [decimal] (13, 0) NULL,
[ICFACI] [nvarchar] (255) NULL,
[ICFWRF] [nvarchar] (255) NULL,
[ICLMTS] [decimal] (18, 0) NULL,
[ICNDDT] [decimal] (8, 0) NULL,
[ICNEAC] [decimal] (1, 0) NULL,
[ICNOPK] [decimal] (5, 0) NULL,
[ICOEND] [decimal] (1, 0) NULL,
[ICPACC] [nvarchar] (255) NULL,
[ICPACN] [nvarchar] (255) NULL,
[ICPLDT] [decimal] (8, 0) NULL,
[ICPNLI] [decimal] (3, 0) NULL,
[ICPNLS] [decimal] (3, 0) NULL,
[ICPNLX] [decimal] (5, 0) NULL,
[ICPUNO] [nvarchar] (255) NULL,
[ICPUOS] [nvarchar] (255) NULL,
[ICRENE] [nvarchar] (255) NULL,
[ICREOR] [decimal] (1, 0) NULL,
[ICREPN] [decimal] (10, 0) NULL,
[ICRESP] [nvarchar] (255) NULL,
[ICRGDT] [decimal] (8, 0) NULL,
[ICRGTM] [decimal] (6, 0) NULL,
[ICRPQA] [decimal] (15, 6) NULL,
[ICRPQT] [decimal] (15, 6) NULL,
[ICSCOP] [decimal] (19, 8) NULL,
[ICSDDT] [decimal] (8, 0) NULL,
[ICSERA] [decimal] (11, 6) NULL,
[ICSMDT] [decimal] (8, 0) NULL,
[ICSTWH] [nvarchar] (255) NULL,
[ICSUDO] [nvarchar] (255) NULL,
[ICSUNO] [nvarchar] (255) NULL,
[ICTIHM] [decimal] (4, 0) NULL,
[ICTRDT] [decimal] (8, 0) NULL,
[ICTXID] [decimal] (13, 0) NULL,
[ICUGCD] [decimal] (1, 0) NULL,
[ICWHLO] [nvarchar] (255) NULL,
[ICWHSL] [nvarchar] (255) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_m3v7_FGINLI]'
GO
CREATE TABLE [psa].[ics_stg_m3v7_FGINLI]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_FGINLI_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_FGINLI_IsIncomplete] DEFAULT ((0)),
[F5ACDT] [decimal] (8, 0) NULL,
[F5ADDG] [decimal] (15, 2) NULL,
[F5CHID] [nvarchar] (255) NULL,
[F5CHNO] [decimal] (3, 0) NULL,
[F5CONO] [decimal] (3, 0) NULL,
[F5DIVI] [nvarchar] (255) NULL,
[F5DNCM] [decimal] (15, 2) NULL,
[F5DNNR] [nvarchar] (255) NULL,
[F5DNPR] [decimal] (17, 6) NULL,
[F5DNQA] [decimal] (15, 6) NULL,
[F5DNQT] [decimal] (15, 6) NULL,
[F5DNRP] [nvarchar] (255) NULL,
[F5DNRQ] [nvarchar] (255) NULL,
[F5ECLC] [nvarchar] (255) NULL,
[F5ICAC] [decimal] (15, 2) NULL,
[F5IMDT] [decimal] (8, 0) NULL,
[F5IMST] [decimal] (1, 0) NULL,
[F5INLP] [decimal] (1, 0) NULL,
[F5INS1] [nvarchar] (255) NULL,
[F5INS2] [nvarchar] (255) NULL,
[F5INS3] [nvarchar] (255) NULL,
[F5INS4] [nvarchar] (255) NULL,
[F5INS5] [nvarchar] (255) NULL,
[F5INYR] [decimal] (4, 0) NULL,
[F5IVCW] [decimal] (15, 6) NULL,
[F5IVDI] [decimal] (5, 2) NULL,
[F5IVLC] [decimal] (15, 2) NULL,
[F5IVNA] [decimal] (15, 2) NULL,
[F5IVOC] [decimal] (17, 6) NULL,
[F5IVQA] [decimal] (15, 6) NULL,
[F5IVQT] [decimal] (15, 6) NULL,
[F5LMDT] [decimal] (8, 0) NULL,
[F5PNLI] [decimal] (3, 0) NULL,
[F5PNLS] [decimal] (3, 0) NULL,
[F5PPUN] [nvarchar] (255) NULL,
[F5PUCD] [decimal] (5, 0) NULL,
[F5PUNO] [nvarchar] (255) NULL,
[F5PUUN] [nvarchar] (255) NULL,
[F5RCAC] [decimal] (15, 2) NULL,
[F5RELP] [decimal] (1, 0) NULL,
[F5REPN] [decimal] (10, 0) NULL,
[F5RGDT] [decimal] (8, 0) NULL,
[F5RGTM] [decimal] (6, 0) NULL,
[F5RPQA] [decimal] (15, 6) NULL,
[F5RPQT] [decimal] (15, 6) NULL,
[F5SERA] [decimal] (11, 6) NULL,
[F5SERS] [decimal] (2, 0) NULL,
[F5SINO] [nvarchar] (255) NULL,
[F5SUNO] [nvarchar] (255) NULL,
[F5TXID] [decimal] (13, 0) NULL,
[F5VRCD] [nvarchar] (255) NULL,
[F5VTCD] [decimal] (2, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_m3v7_FPLEDG]'
GO
CREATE TABLE [psa].[ics_stg_m3v7_FPLEDG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_FPLEDG_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_FPLEDG_IsIncomplete] DEFAULT ((0)),
[EPACDT] [decimal] (8, 0) NULL,
[EPAPCD] [nvarchar] (255) NULL,
[EPAPRV] [decimal] (1, 0) NULL,
[EPARAT] [decimal] (11, 6) NULL,
[EPARCD] [decimal] (1, 0) NULL,
[EPBKID] [nvarchar] (255) NULL,
[EPBLBY] [nvarchar] (255) NULL,
[EPBLDT] [decimal] (8, 0) NULL,
[EPCHID] [nvarchar] (255) NULL,
[EPCHNO] [decimal] (3, 0) NULL,
[EPCONO] [decimal] (3, 0) NULL,
[EPCRTP] [decimal] (2, 0) NULL,
[EPCUAM] [decimal] (15, 2) NULL,
[EPCUCD] [nvarchar] (255) NULL,
[EPDCAM] [decimal] (1, 0) NULL,
[EPDEDA] [decimal] (8, 0) NULL,
[EPDIVI] [nvarchar] (255) NULL,
[EPDUDT] [decimal] (8, 0) NULL,
[EPENME] [decimal] (1, 0) NULL,
[EPINYR] [decimal] (4, 0) NULL,
[EPIVBL] [decimal] (1, 0) NULL,
[EPIVDT] [decimal] (8, 0) NULL,
[EPIVTP] [nvarchar] (255) NULL,
[EPJRNO] [decimal] (7, 0) NULL,
[EPJSNO] [decimal] (7, 0) NULL,
[EPLMDT] [decimal] (8, 0) NULL,
[EPPYME] [nvarchar] (255) NULL,
[EPPYRS] [nvarchar] (255) NULL,
[EPPYST] [decimal] (1, 0) NULL,
[EPPYTP] [nvarchar] (255) NULL,
[EPRECO] [decimal] (1, 0) NULL,
[EPREDE] [decimal] (8, 0) NULL,
[EPRGDT] [decimal] (8, 0) NULL,
[EPRGTM] [decimal] (6, 0) NULL,
[EPSINO] [nvarchar] (255) NULL,
[EPSLOP] [decimal] (2, 0) NULL,
[EPSPYN] [nvarchar] (255) NULL,
[EPSUCL] [nvarchar] (255) NULL,
[EPSUNO] [nvarchar] (255) NULL,
[EPTDCD] [nvarchar] (255) NULL,
[EPTDSC] [nvarchar] (255) NULL,
[EPTECD] [nvarchar] (255) NULL,
[EPTEPY] [nvarchar] (255) NULL,
[EPTRCD] [decimal] (2, 0) NULL,
[EPTXID] [decimal] (13, 0) NULL,
[EPVONO] [decimal] (8, 0) NULL,
[EPVSER] [nvarchar] (255) NULL,
[EPVTAM] [decimal] (15, 2) NULL,
[EPYEA4] [decimal] (4, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_m3v7_MPLIND]'
GO
CREATE TABLE [psa].[ics_stg_m3v7_MPLIND]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_MPLIND_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_MPLIND_IsIncomplete] DEFAULT ((0)),
[ICAGNB] [nvarchar] (255) NULL,
[ICARDT] [decimal] (8, 0) NULL,
[ICBANO] [nvarchar] (255) NULL,
[ICBOLN] [nvarchar] (255) NULL,
[ICCAMU] [nvarchar] (255) NULL,
[ICCARN] [nvarchar] (255) NULL,
[ICCHPO] [decimal] (1, 0) NULL,
[ICCONO] [decimal] (3, 0) NULL,
[ICDLIX] [decimal] (11, 0) NULL,
[ICDTID] [decimal] (13, 0) NULL,
[ICFACI] [nvarchar] (255) NULL,
[ICFWRF] [nvarchar] (255) NULL,
[ICNEAC] [decimal] (1, 0) NULL,
[ICNOPK] [decimal] (5, 0) NULL,
[ICOEND] [decimal] (1, 0) NULL,
[ICPACC] [nvarchar] (255) NULL,
[ICPACN] [nvarchar] (255) NULL,
[ICPLDT] [decimal] (8, 0) NULL,
[ICPNLI] [decimal] (3, 0) NULL,
[ICPNLS] [decimal] (3, 0) NULL,
[ICPNLX] [decimal] (5, 0) NULL,
[ICPUNO] [nvarchar] (255) NULL,
[ICPUOS] [nvarchar] (255) NULL,
[ICRENE] [nvarchar] (255) NULL,
[ICREOR] [decimal] (1, 0) NULL,
[ICREPN] [decimal] (10, 0) NULL,
[ICRESP] [nvarchar] (255) NULL,
[ICRGDT] [decimal] (8, 0) NULL,
[ICRGTM] [decimal] (6, 0) NULL,
[ICRPQA] [decimal] (15, 6) NULL,
[ICRPQT] [decimal] (15, 6) NULL,
[ICSCOP] [decimal] (17, 6) NULL,
[ICSERA] [decimal] (11, 6) NULL,
[ICSMDT] [decimal] (8, 0) NULL,
[ICSUDO] [nvarchar] (255) NULL,
[ICTIHM] [decimal] (4, 0) NULL,
[ICTRDT] [decimal] (8, 0) NULL,
[ICTXID] [decimal] (13, 0) NULL,
[ICUGCD] [decimal] (1, 0) NULL,
[ICWHLO] [nvarchar] (255) NULL,
[ICWHSL] [nvarchar] (255) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_m3v7_MPLINE]'
GO
CREATE TABLE [psa].[ics_stg_m3v7_MPLINE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_MPLINE_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_m3v7_MPLINE_IsIncomplete] DEFAULT ((0)),
[IBACLI] [decimal] (1, 0) NULL,
[IBACRF] [nvarchar] (255) NULL,
[IBADQA] [decimal] (15, 6) NULL,
[IBAGNB] [nvarchar] (255) NULL,
[IBATDT] [decimal] (8, 0) NULL,
[IBATNR] [decimal] (17, 0) NULL,
[IBATPR] [nvarchar] (255) NULL,
[IBBAOR] [nvarchar] (255) NULL,
[IBBUYE] [nvarchar] (255) NULL,
[IBCAQA] [decimal] (15, 6) NULL,
[IBCFD1] [decimal] (5, 2) NULL,
[IBCFD2] [decimal] (5, 2) NULL,
[IBCFD3] [decimal] (5, 2) NULL,
[IBCFIN] [decimal] (10, 0) NULL,
[IBCFMB] [decimal] (15, 9) NULL,
[IBCFPB] [decimal] (15, 9) NULL,
[IBCFQA] [decimal] (15, 6) NULL,
[IBCHID] [nvarchar] (255) NULL,
[IBCHNO] [decimal] (3, 0) NULL,
[IBCLAN] [nvarchar] (255) NULL,
[IBCLLI] [decimal] (1, 0) NULL,
[IBCLLN] [decimal] (3, 0) NULL,
[IBCOCE] [nvarchar] (255) NULL,
[IBCODT] [decimal] (8, 0) NULL,
[IBCONO] [decimal] (3, 0) NULL,
[IBCPPR] [decimal] (17, 6) NULL,
[IBCPRI] [nvarchar] (255) NULL,
[IBCPUC] [decimal] (5, 0) NULL,
[IBCSNO] [nvarchar] (255) NULL,
[IBDT4T] [decimal] (1, 0) NULL,
[IBDTID] [decimal] (13, 0) NULL,
[IBDWCP] [decimal] (1, 0) NULL,
[IBDWDT] [decimal] (8, 0) NULL,
[IBECDD] [decimal] (8, 0) NULL,
[IBECF1] [nvarchar] (255) NULL,
[IBECF2] [nvarchar] (255) NULL,
[IBECF3] [nvarchar] (255) NULL,
[IBECF4] [nvarchar] (255) NULL,
[IBECF5] [nvarchar] (255) NULL,
[IBECLC] [nvarchar] (255) NULL,
[IBECVE] [nvarchar] (255) NULL,
[IBECVS] [decimal] (3, 0) NULL,
[IBELNO] [nvarchar] (255) NULL,
[IBETRF] [nvarchar] (255) NULL,
[IBEXAT] [decimal] (1, 0) NULL,
[IBEXAV] [decimal] (1, 0) NULL,
[IBEXEP] [decimal] (15, 2) NULL,
[IBFACI] [nvarchar] (255) NULL,
[IBFUSC] [nvarchar] (255) NULL,
[IBGRMT] [nvarchar] (255) NULL,
[IBHAFE] [nvarchar] (255) NULL,
[IBHDPR] [nvarchar] (255) NULL,
[IBIDAG] [decimal] (1, 0) NULL,
[IBIDAT] [decimal] (8, 0) NULL,
[IBINEP] [decimal] (15, 2) NULL,
[IBIRCV] [nvarchar] (255) NULL,
[IBITNO] [nvarchar] (255) NULL,
[IBIVQA] [decimal] (15, 6) NULL,
[IBLICC] [nvarchar] (255) NULL,
[IBLMDT] [decimal] (8, 0) NULL,
[IBLMTS] [decimal] (18, 0) NULL,
[IBLNAM] [decimal] (15, 2) NULL,
[IBLPUD] [decimal] (8, 0) NULL,
[IBLTPP] [nvarchar] (255) NULL,
[IBMSTN] [decimal] (10, 0) NULL,
[IBNOED] [decimal] (1, 0) NULL,
[IBNPDE] [decimal] (3, 0) NULL,
[IBODI1] [decimal] (5, 2) NULL,
[IBODI2] [decimal] (5, 2) NULL,
[IBODI3] [decimal] (5, 2) NULL,
[IBOEND] [decimal] (1, 0) NULL,
[IBOPTX] [nvarchar] (255) NULL,
[IBOPTY] [nvarchar] (255) NULL,
[IBOPTZ] [nvarchar] (255) NULL,
[IBORQA] [decimal] (15, 6) NULL,
[IBORTY] [nvarchar] (255) NULL,
[IBOTOD] [decimal] (1, 0) NULL,
[IBOURR] [nvarchar] (255) NULL,
[IBOURT] [nvarchar] (255) NULL,
[IBPACT] [nvarchar] (255) NULL,
[IBPDDT] [decimal] (8, 0) NULL,
[IBPGRN] [decimal] (7, 0) NULL,
[IBPITD] [nvarchar] (255) NULL,
[IBPITT] [nvarchar] (255) NULL,
[IBPLDT] [decimal] (8, 0) NULL,
[IBPLPN] [decimal] (7, 0) NULL,
[IBPLPS] [decimal] (3, 0) NULL,
[IBPNLI] [decimal] (3, 0) NULL,
[IBPNLS] [decimal] (3, 0) NULL,
[IBPOTC] [nvarchar] (255) NULL,
[IBPPUN] [nvarchar] (255) NULL,
[IBPRCS] [nvarchar] (255) NULL,
[IBPRIP] [nvarchar] (255) NULL,
[IBPROD] [nvarchar] (255) NULL,
[IBPROJ] [nvarchar] (255) NULL,
[IBPTCD] [decimal] (1, 0) NULL,
[IBPUCD] [decimal] (5, 0) NULL,
[IBPUNO] [nvarchar] (255) NULL,
[IBPUPR] [decimal] (17, 6) NULL,
[IBPURC] [nvarchar] (255) NULL,
[IBPUSL] [nvarchar] (255) NULL,
[IBPUST] [nvarchar] (255) NULL,
[IBPUUN] [nvarchar] (255) NULL,
[IBRCDT] [decimal] (8, 0) NULL,
[IBREPP] [decimal] (1, 0) NULL,
[IBRESF] [nvarchar] (255) NULL,
[IBREVN] [nvarchar] (255) NULL,
[IBRGDT] [decimal] (8, 0) NULL,
[IBRGTM] [decimal] (6, 0) NULL,
[IBRJQA] [decimal] (15, 6) NULL,
[IBRORC] [decimal] (1, 0) NULL,
[IBRORL] [decimal] (6, 0) NULL,
[IBRORN] [nvarchar] (255) NULL,
[IBRORX] [decimal] (3, 0) NULL,
[IBRRQA] [decimal] (15, 6) NULL,
[IBRVQA] [decimal] (15, 6) NULL,
[IBSDQA] [decimal] (15, 6) NULL,
[IBSEBI] [nvarchar] (255) NULL,
[IBSEQN] [decimal] (7, 0) NULL,
[IBSITE] [nvarchar] (255) NULL,
[IBSORN] [nvarchar] (255) NULL,
[IBSUAG] [nvarchar] (255) NULL,
[IBSUDO] [nvarchar] (255) NULL,
[IBSUFI] [nvarchar] (255) NULL,
[IBSUNO] [nvarchar] (255) NULL,
[IBTAXC] [nvarchar] (255) NULL,
[IBTERE] [nvarchar] (255) NULL,
[IBTIHM] [decimal] (4, 0) NULL,
[IBTNQA] [decimal] (15, 6) NULL,
[IBTXID] [decimal] (13, 0) NULL,
[IBULEX] [decimal] (1, 0) NULL,
[IBUPAV] [decimal] (1, 0) NULL,
[IBUPCK] [decimal] (1, 0) NULL,
[IBUPIV] [decimal] (1, 0) NULL,
[IBVDDT] [decimal] (8, 0) NULL,
[IBVRCD] [nvarchar] (255) NULL,
[IBVTCD] [decimal] (2, 0) NULL,
[IBWHLO] [nvarchar] (255) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_movex_FGINLI]'
GO
CREATE TABLE [psa].[ics_stg_movex_FGINLI]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_FGINLI_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_FGINLI_IsIncomplete] DEFAULT ((0)),
[F5ACDT] [decimal] (8, 0) NULL,
[F5ADDG] [decimal] (15, 2) NULL,
[F5CHID] [nvarchar] (10) NULL,
[F5CHNO] [decimal] (3, 0) NULL,
[F5CONO] [decimal] (3, 0) NULL,
[F5DIVI] [nvarchar] (3) NULL,
[F5DNCM] [decimal] (15, 2) NULL,
[F5DNNR] [nvarchar] (24) NULL,
[F5DNPR] [decimal] (17, 6) NULL,
[F5DNQA] [decimal] (15, 6) NULL,
[F5DNQT] [decimal] (15, 6) NULL,
[F5DNRP] [nvarchar] (3) NULL,
[F5DNRQ] [nvarchar] (3) NULL,
[F5ECLC] [nvarchar] (2) NULL,
[F5ICAC] [decimal] (15, 2) NULL,
[F5IMDT] [decimal] (8, 0) NULL,
[F5IMST] [decimal] (1, 0) NULL,
[F5INLP] [decimal] (1, 0) NULL,
[F5INS1] [nvarchar] (1) NULL,
[F5INS2] [nvarchar] (1) NULL,
[F5INS3] [nvarchar] (1) NULL,
[F5INS4] [nvarchar] (1) NULL,
[F5INS5] [nvarchar] (1) NULL,
[F5INYR] [decimal] (4, 0) NULL,
[F5IVCW] [decimal] (15, 6) NULL,
[F5IVDI] [decimal] (5, 2) NULL,
[F5IVLC] [decimal] (15, 2) NULL,
[F5IVNA] [decimal] (15, 2) NULL,
[F5IVOC] [decimal] (17, 6) NULL,
[F5IVQA] [decimal] (15, 6) NULL,
[F5IVQT] [decimal] (15, 6) NULL,
[F5LMDT] [decimal] (8, 0) NULL,
[F5PNLI] [decimal] (3, 0) NULL,
[F5PNLS] [decimal] (3, 0) NULL,
[F5PPUN] [nvarchar] (3) NULL,
[F5PUCD] [decimal] (5, 0) NULL,
[F5PUNO] [nvarchar] (7) NULL,
[F5PUUN] [nvarchar] (3) NULL,
[F5RCAC] [decimal] (15, 2) NULL,
[F5RELP] [decimal] (1, 0) NULL,
[F5REPN] [decimal] (10, 0) NULL,
[F5RGDT] [decimal] (8, 0) NULL,
[F5RGTM] [decimal] (6, 0) NULL,
[F5RPQA] [decimal] (15, 6) NULL,
[F5RPQT] [decimal] (15, 6) NULL,
[F5SERA] [decimal] (11, 6) NULL,
[F5SINO] [nvarchar] (24) NULL,
[F5SUNO] [nvarchar] (10) NULL,
[F5VRCD] [nvarchar] (2) NULL,
[F5VTCD] [decimal] (2, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_movex_FPLEDG]'
GO
CREATE TABLE [psa].[ics_stg_movex_FPLEDG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_FPLEDG_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_FPLEDG_IsIncomplete] DEFAULT ((0)),
[EPACDT] [decimal] (8, 0) NULL,
[EPAPCD] [nvarchar] (10) NULL,
[EPAPRV] [decimal] (1, 0) NULL,
[EPARAT] [decimal] (11, 6) NULL,
[EPARCD] [decimal] (1, 0) NULL,
[EPBKID] [nvarchar] (5) NULL,
[EPBLBY] [nvarchar] (10) NULL,
[EPBLDT] [decimal] (8, 0) NULL,
[EPCHID] [nvarchar] (10) NULL,
[EPCHNO] [decimal] (3, 0) NULL,
[EPCONO] [decimal] (3, 0) NULL,
[EPCRTP] [decimal] (2, 0) NULL,
[EPCUAM] [decimal] (15, 2) NULL,
[EPCUCD] [nvarchar] (3) NULL,
[EPDCAM] [decimal] (1, 0) NULL,
[EPDIVI] [nvarchar] (3) NULL,
[EPDUDT] [decimal] (8, 0) NULL,
[EPENME] [decimal] (1, 0) NULL,
[EPINYR] [decimal] (4, 0) NULL,
[EPIVBL] [decimal] (1, 0) NULL,
[EPIVDT] [decimal] (8, 0) NULL,
[EPIVTP] [nvarchar] (2) NULL,
[EPJRNO] [decimal] (7, 0) NULL,
[EPJSNO] [decimal] (7, 0) NULL,
[EPLMDT] [decimal] (8, 0) NULL,
[EPPYME] [nvarchar] (3) NULL,
[EPPYRS] [nvarchar] (2) NULL,
[EPPYST] [decimal] (1, 0) NULL,
[EPPYTP] [nvarchar] (2) NULL,
[EPRECO] [decimal] (1, 0) NULL,
[EPREDE] [decimal] (8, 0) NULL,
[EPRGDT] [decimal] (8, 0) NULL,
[EPRGTM] [decimal] (6, 0) NULL,
[EPSINO] [nvarchar] (24) NULL,
[EPSLOP] [decimal] (2, 0) NULL,
[EPSPYN] [nvarchar] (10) NULL,
[EPSUCL] [nvarchar] (3) NULL,
[EPSUNO] [nvarchar] (10) NULL,
[EPTDCD] [nvarchar] (4) NULL,
[EPTDSC] [nvarchar] (10) NULL,
[EPTECD] [nvarchar] (3) NULL,
[EPTEPY] [nvarchar] (3) NULL,
[EPTRCD] [decimal] (2, 0) NULL,
[EPTXID] [decimal] (13, 0) NULL,
[EPVONO] [decimal] (8, 0) NULL,
[EPVSER] [nvarchar] (3) NULL,
[EPVTAM] [decimal] (15, 2) NULL,
[EPYEA4] [decimal] (4, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_movex_MPLIND]'
GO
CREATE TABLE [psa].[ics_stg_movex_MPLIND]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_MPLIND_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_MPLIND_IsIncomplete] DEFAULT ((0)),
[ICAGNB] [nvarchar] (7) NULL,
[ICARDT] [decimal] (8, 0) NULL,
[ICBANO] [nvarchar] (12) NULL,
[ICBOLN] [nvarchar] (14) NULL,
[ICCAMU] [nvarchar] (12) NULL,
[ICCARN] [nvarchar] (30) NULL,
[ICCHPO] [decimal] (1, 0) NULL,
[ICCONO] [decimal] (3, 0) NULL,
[ICDLIX] [decimal] (11, 0) NULL,
[ICDTID] [decimal] (13, 0) NULL,
[ICFACI] [nvarchar] (3) NULL,
[ICFWRF] [nvarchar] (10) NULL,
[ICNEAC] [decimal] (1, 0) NULL,
[ICNOPK] [decimal] (5, 0) NULL,
[ICOEND] [decimal] (1, 0) NULL,
[ICPLDT] [decimal] (8, 0) NULL,
[ICPNLI] [decimal] (3, 0) NULL,
[ICPNLS] [decimal] (3, 0) NULL,
[ICPNLX] [decimal] (3, 0) NULL,
[ICPUNO] [nvarchar] (7) NULL,
[ICPUOS] [nvarchar] (2) NULL,
[ICRENE] [nvarchar] (10) NULL,
[ICREOR] [decimal] (1, 0) NULL,
[ICREPN] [decimal] (10, 0) NULL,
[ICRESP] [nvarchar] (10) NULL,
[ICRGDT] [decimal] (8, 0) NULL,
[ICRGTM] [decimal] (6, 0) NULL,
[ICRPQA] [decimal] (15, 6) NULL,
[ICRPQT] [decimal] (15, 6) NULL,
[ICSCOP] [decimal] (17, 6) NULL,
[ICSERA] [decimal] (11, 6) NULL,
[ICSMDT] [decimal] (8, 0) NULL,
[ICSUDO] [nvarchar] (20) NULL,
[ICTIHM] [decimal] (4, 0) NULL,
[ICTRDT] [decimal] (8, 0) NULL,
[ICTXID] [decimal] (13, 0) NULL,
[ICUGCD] [decimal] (1, 0) NULL,
[ICWHLO] [nvarchar] (3) NULL,
[ICWHSL] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_movex_MPLINE]'
GO
CREATE TABLE [psa].[ics_stg_movex_MPLINE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_MPLINE_IsDeleted] DEFAULT ((0)),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_land_movex_MPLINE_IsIncomplete] DEFAULT ((0)),
[IBACLI] [decimal] (1, 0) NULL,
[IBACRF] [nvarchar] (8) NULL,
[IBADQA] [decimal] (15, 6) NULL,
[IBAGNB] [nvarchar] (7) NULL,
[IBATDT] [decimal] (8, 0) NULL,
[IBATNR] [decimal] (17, 0) NULL,
[IBATPR] [nvarchar] (1) NULL,
[IBBUYE] [nvarchar] (10) NULL,
[IBCAQA] [decimal] (15, 6) NULL,
[IBCFD1] [decimal] (5, 2) NULL,
[IBCFD2] [decimal] (5, 2) NULL,
[IBCFD3] [decimal] (5, 2) NULL,
[IBCFIN] [decimal] (7, 0) NULL,
[IBCFMB] [decimal] (15, 9) NULL,
[IBCFPB] [decimal] (15, 9) NULL,
[IBCFQA] [decimal] (15, 6) NULL,
[IBCHID] [nvarchar] (10) NULL,
[IBCHNO] [decimal] (3, 0) NULL,
[IBCLAN] [nvarchar] (7) NULL,
[IBCLLI] [decimal] (1, 0) NULL,
[IBCLLN] [decimal] (3, 0) NULL,
[IBCOCE] [nvarchar] (8) NULL,
[IBCODT] [decimal] (8, 0) NULL,
[IBCONO] [decimal] (3, 0) NULL,
[IBCPPR] [decimal] (17, 6) NULL,
[IBCPRI] [nvarchar] (5) NULL,
[IBCPUC] [decimal] (5, 0) NULL,
[IBCSNO] [nvarchar] (16) NULL,
[IBDT4T] [decimal] (1, 0) NULL,
[IBDTID] [decimal] (13, 0) NULL,
[IBDWCP] [decimal] (1, 0) NULL,
[IBDWDT] [decimal] (8, 0) NULL,
[IBECDD] [decimal] (8, 0) NULL,
[IBECF1] [nvarchar] (5) NULL,
[IBECF2] [nvarchar] (5) NULL,
[IBECF3] [nvarchar] (5) NULL,
[IBECF4] [nvarchar] (5) NULL,
[IBECF5] [nvarchar] (5) NULL,
[IBECLC] [nvarchar] (2) NULL,
[IBECVE] [nvarchar] (4) NULL,
[IBECVS] [decimal] (3, 0) NULL,
[IBELNO] [nvarchar] (8) NULL,
[IBETRF] [nvarchar] (3) NULL,
[IBEXAT] [decimal] (1, 0) NULL,
[IBEXAV] [decimal] (1, 0) NULL,
[IBEXEP] [decimal] (15, 2) NULL,
[IBFACI] [nvarchar] (3) NULL,
[IBFUSC] [nvarchar] (3) NULL,
[IBGRMT] [nvarchar] (3) NULL,
[IBHAFE] [nvarchar] (6) NULL,
[IBHDPR] [nvarchar] (15) NULL,
[IBIDAG] [decimal] (1, 0) NULL,
[IBIDAT] [decimal] (8, 0) NULL,
[IBINEP] [decimal] (15, 2) NULL,
[IBIRCV] [nvarchar] (20) NULL,
[IBITNO] [nvarchar] (15) NULL,
[IBIVQA] [decimal] (15, 6) NULL,
[IBLICC] [nvarchar] (1) NULL,
[IBLMDT] [decimal] (8, 0) NULL,
[IBLNAM] [decimal] (15, 2) NULL,
[IBLPUD] [decimal] (8, 0) NULL,
[IBLTPP] [nvarchar] (1) NULL,
[IBMSTN] [decimal] (10, 0) NULL,
[IBNOED] [decimal] (1, 0) NULL,
[IBNPDE] [decimal] (3, 0) NULL,
[IBODI1] [decimal] (5, 2) NULL,
[IBODI2] [decimal] (5, 2) NULL,
[IBODI3] [decimal] (5, 2) NULL,
[IBOEND] [decimal] (1, 0) NULL,
[IBORQA] [decimal] (15, 6) NULL,
[IBORTY] [nvarchar] (3) NULL,
[IBOTOD] [decimal] (1, 0) NULL,
[IBOURR] [nvarchar] (10) NULL,
[IBOURT] [nvarchar] (1) NULL,
[IBPACT] [nvarchar] (6) NULL,
[IBPDDT] [decimal] (8, 0) NULL,
[IBPGRN] [decimal] (7, 0) NULL,
[IBPITD] [nvarchar] (30) NULL,
[IBPITT] [nvarchar] (60) NULL,
[IBPLDT] [decimal] (8, 0) NULL,
[IBPLPN] [decimal] (7, 0) NULL,
[IBPLPS] [decimal] (3, 0) NULL,
[IBPNLI] [decimal] (3, 0) NULL,
[IBPNLS] [decimal] (3, 0) NULL,
[IBPOTC] [nvarchar] (2) NULL,
[IBPPUN] [nvarchar] (3) NULL,
[IBPRCS] [nvarchar] (3) NULL,
[IBPRIP] [nvarchar] (1) NULL,
[IBPROD] [nvarchar] (10) NULL,
[IBPROJ] [nvarchar] (7) NULL,
[IBPTCD] [decimal] (1, 0) NULL,
[IBPUCD] [decimal] (5, 0) NULL,
[IBPUNO] [nvarchar] (7) NULL,
[IBPUPR] [decimal] (17, 6) NULL,
[IBPURC] [nvarchar] (10) NULL,
[IBPUSL] [nvarchar] (2) NULL,
[IBPUST] [nvarchar] (2) NULL,
[IBPUUN] [nvarchar] (3) NULL,
[IBRCDT] [decimal] (8, 0) NULL,
[IBREPP] [decimal] (1, 0) NULL,
[IBRESF] [nvarchar] (10) NULL,
[IBREVN] [nvarchar] (2) NULL,
[IBRGDT] [decimal] (8, 0) NULL,
[IBRGTM] [decimal] (6, 0) NULL,
[IBRJQA] [decimal] (15, 6) NULL,
[IBRORC] [decimal] (1, 0) NULL,
[IBRORL] [decimal] (6, 0) NULL,
[IBRORN] [nvarchar] (10) NULL,
[IBRRQA] [decimal] (15, 6) NULL,
[IBRVQA] [decimal] (15, 6) NULL,
[IBSDQA] [decimal] (15, 6) NULL,
[IBSEBI] [nvarchar] (1) NULL,
[IBSEQN] [decimal] (7, 0) NULL,
[IBSITE] [nvarchar] (30) NULL,
[IBSORN] [nvarchar] (20) NULL,
[IBSUAG] [nvarchar] (10) NULL,
[IBSUFI] [nvarchar] (20) NULL,
[IBSUNO] [nvarchar] (10) NULL,
[IBTAXC] [nvarchar] (3) NULL,
[IBTERE] [nvarchar] (10) NULL,
[IBTIHM] [decimal] (4, 0) NULL,
[IBTNQA] [decimal] (15, 6) NULL,
[IBTXID] [decimal] (13, 0) NULL,
[IBULEX] [decimal] (1, 0) NULL,
[IBUPAV] [decimal] (1, 0) NULL,
[IBUPIV] [decimal] (1, 0) NULL,
[IBVDDT] [decimal] (8, 0) NULL,
[IBVRCD] [nvarchar] (2) NULL,
[IBVTCD] [decimal] (2, 0) NULL,
[IBWHLO] [nvarchar] (3) NULL
)
GO
