-- <Migration ID="3c789f8c-5893-4ea3-95ec-927ab2f5deb4" />
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Code') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Code];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Header') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Header];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Invoice_Header') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Header];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Invoice_Line') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Line];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Line') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Line];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Line_Discount') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Line_Discount];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Payables_Setup') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Payables_Setup];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_PrePayment_Pct') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_PrePayment_Pct];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Purchase_Price') DROP TABLE [tsa].[ics_land_Navision_Bul_Purchase_Price];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_SalesPerson_Purchaser') DROP TABLE [tsa].[ics_land_Navision_Bul_SalesPerson_Purchaser];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Bul_Std_Purchase_Line') DROP TABLE [tsa].[ics_land_Navision_Bul_Std_Purchase_Line];

IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Code') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Code];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Header') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Header];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Invoice_Header') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Invoice_Header];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Invoice_Line') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Invoice_Line];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Line') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Line];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Line_Discount') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Line_Discount];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Payables_Setup') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Payables_Setup];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_PrePayment_Pct') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_PrePayment_Pct];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Purchase_Price') DROP TABLE [tsa].[ics_land_Navision_Rom_Purchase_Price];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_SalesPerson_Purchaser') DROP TABLE [tsa].[ics_land_Navision_Rom_SalesPerson_Purchaser];
IF EXISTS (SELECT 1 FROM sys.tables WHERE SCHEMA_NAME(schema_id)=N'tsa' AND name=N'ics_land_Navision_Rom_Std_Purchase_Line') DROP TABLE [tsa].[ics_land_Navision_Rom_Std_Purchase_Line];

PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Code]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Code]
(
[timestamp] [binary] (16) NULL,
[Code] [nvarchar] (10) NULL,
[Description] [nvarchar] (50) NULL,
[Currency_Code] [nvarchar] (10) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_Code] on [tsa].[ics_land_Navision_Bul_Purchase_Code]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_Code] ON [tsa].[ics_land_Navision_Bul_Purchase_Code] ([Code])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Header]
(
[Document Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Pay-to Name] [varchar] (50) NULL,
[Pay-to Name 2] [varchar] (50) NULL,
[Pay-to Address] [varchar] (50) NULL,
[Pay-to Address 2] [varchar] (50) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (50) NULL,
[Your Reference] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Name] [varchar] (50) NULL,
[Ship-to Name 2] [varchar] (50) NULL,
[Ship-to Address] [varchar] (50) NULL,
[Ship-to Address 2] [varchar] (50) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Contact] [varchar] (50) NULL,
[Order Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Expected Receipt Date] [datetime] NULL,
[Posting Description] [varchar] (50) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Due Date] [datetime] NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Location Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Prices Including VAT] [tinyint] NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Language Code] [varchar] (10) NULL,
[Purchaser Code] [varchar] (10) NULL,
[Order Class] [varchar] (10) NULL,
[No_ Printed] [int] NULL,
[On Hold] [varchar] (3) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Receive] [tinyint] NULL,
[Invoice] [tinyint] NULL,
[Receiving No_] [varchar] (20) NULL,
[Posting No_] [varchar] (20) NULL,
[Last Receiving No_] [varchar] (20) NULL,
[Last Posting No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Shipment No_] [varchar] (20) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[Vendor Cr_ Memo No_] [varchar] (20) NULL,
[VAT Registration No_] [varchar] (20) NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Reason Code] [varchar] (10) NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[VAT Country_Region Code] [varchar] (10) NULL,
[Buy-from Vendor Name] [varchar] (50) NULL,
[Buy-from Vendor Name 2] [varchar] (50) NULL,
[Buy-from Address] [varchar] (50) NULL,
[Buy-from Address 2] [varchar] (50) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (50) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to Country_Region Code] [varchar] (10) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from Country_Region Code] [varchar] (10) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Country_Region Code] [varchar] (10) NULL,
[Bal_ Account Type] [int] NULL,
[Order Address Code] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Correction] [tinyint] NULL,
[Document Date] [datetime] NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Payment Method Code] [varchar] (10) NULL,
[No_ Series] [varchar] (10) NULL,
[Posting No_ Series] [varchar] (10) NULL,
[Receiving No_ Series] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[Applies-to ID] [varchar] (20) NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[Status] [int] NULL,
[Invoice Discount Calculation] [int] NULL,
[Invoice Discount Value] [decimal] (38, 20) NULL,
[Send IC Document] [tinyint] NULL,
[IC Status] [int] NULL,
[Buy-from IC Partner Code] [varchar] (20) NULL,
[Pay-to IC Partner Code] [varchar] (20) NULL,
[IC Direction] [int] NULL,
[Prepayment No_] [varchar] (20) NULL,
[Last Prepayment No_] [varchar] (20) NULL,
[Prepmt_ Cr_ Memo No_] [varchar] (20) NULL,
[Last Prepmt_ Cr_ Memo No_] [varchar] (20) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Prepayment No_ Series] [varchar] (10) NULL,
[Compress Prepayment] [tinyint] NULL,
[Prepayment Due Date] [datetime] NULL,
[Prepmt_ Cr_ Memo No_ Series] [varchar] (10) NULL,
[Prepmt_ Posting Description] [varchar] (50) NULL,
[Prepmt_ Pmt_ Discount Date] [datetime] NULL,
[Prepmt_ Payment Terms Code] [varchar] (10) NULL,
[Prepmt_ Payment Discount %] [decimal] (38, 20) NULL,
[Quote No_] [varchar] (20) NULL,
[Doc_ No_ Occurrence] [int] NULL,
[Campaign No_] [varchar] (20) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Posting from Whse_ Ref_] [int] NULL,
[Requested Receipt Date] [datetime] NULL,
[Promised Receipt Date] [datetime] NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Vendor Authorization No_] [varchar] (20) NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shipment No_ Series] [varchar] (10) NULL,
[Ship] [tinyint] NULL,
[Last Return Shipment No_] [varchar] (20) NULL,
[Assigned User ID] [varchar] (20) NULL,
[Identification No_] [varchar] (13) NULL,
[Customs Declaration No_] [varchar] (30) NULL,
[Debit Memo] [tinyint] NULL,
[To Invoice No_] [varchar] (20) NULL,
[To Invoice Date] [datetime] NULL,
[Void] [tinyint] NULL,
[Void Date] [datetime] NULL,
[VAT Subject] [varchar] (30) NULL,
[Sales Protocol] [tinyint] NULL,
[Do not include in VAT Ledgers] [tinyint] NULL,
[VAT Settlement Date] [datetime] NULL,
[VAT Exempt Ground] [varchar] (10) NULL,
[Composed By] [varchar] (30) NULL,
[Transport Country_Region Code] [varchar] (10) NULL,
[Speditor] [varchar] (10) NULL,
[Date Received] [datetime] NULL,
[Time Received] [datetime] NULL,
[BizTalk Purchase Quote] [tinyint] NULL,
[BizTalk Purch_ Order Cnfmn_] [tinyint] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[BizTalk Purchase Receipt] [tinyint] NULL,
[BizTalk Purchase Credit Memo] [tinyint] NULL,
[Date Sent] [datetime] NULL,
[Time Sent] [datetime] NULL,
[BizTalk Request for Purch_ Qte] [tinyint] NULL,
[BizTalk Purchase Order] [tinyint] NULL,
[Vendor Quote No_] [varchar] (20) NULL,
[BizTalk Document Sent] [tinyint] NULL,
[Unrealized VAT] [tinyint] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase Header] on [tsa].[ics_land_Navision_Bul_Purchase_Header]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase Header] ON [tsa].[ics_land_Navision_Bul_Purchase_Header] ([Document Type], [No_])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Header]
(
[No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Pay-to Name] [varchar] (50) NULL,
[Pay-to Name 2] [varchar] (50) NULL,
[Pay-to Address] [varchar] (50) NULL,
[Pay-to Address 2] [varchar] (50) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (50) NULL,
[Your Reference] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Name] [varchar] (50) NULL,
[Ship-to Name 2] [varchar] (50) NULL,
[Ship-to Address] [varchar] (50) NULL,
[Ship-to Address 2] [varchar] (50) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Contact] [varchar] (50) NULL,
[Order Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Expected Receipt Date] [datetime] NULL,
[Posting Description] [varchar] (50) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Due Date] [datetime] NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Location Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Prices Including VAT] [tinyint] NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Language Code] [varchar] (10) NULL,
[Purchaser Code] [varchar] (10) NULL,
[Order No_] [varchar] (20) NULL,
[No_ Printed] [int] NULL,
[On Hold] [varchar] (3) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[VAT Registration No_] [varchar] (20) NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Reason Code] [varchar] (10) NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[VAT Country_Region Code] [varchar] (10) NULL,
[Buy-from Vendor Name] [varchar] (50) NULL,
[Buy-from Vendor Name 2] [varchar] (50) NULL,
[Buy-from Address] [varchar] (50) NULL,
[Buy-from Address 2] [varchar] (50) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (50) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to Country_Region Code] [varchar] (10) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from Country_Region Code] [varchar] (10) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Country_Region Code] [varchar] (10) NULL,
[Bal_ Account Type] [int] NULL,
[Order Address Code] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Correction] [tinyint] NULL,
[Document Date] [datetime] NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Payment Method Code] [varchar] (10) NULL,
[Pre-Assigned No_ Series] [varchar] (10) NULL,
[No_ Series] [varchar] (10) NULL,
[Order No_ Series] [varchar] (10) NULL,
[Pre-Assigned No_] [varchar] (20) NULL,
[User ID] [varchar] (20) NULL,
[Source Code] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[Prepayment No_ Series] [varchar] (10) NULL,
[Prepayment Invoice] [tinyint] NULL,
[Prepayment Order No_] [varchar] (20) NULL,
[Quote No_] [varchar] (20) NULL,
[Campaign No_] [varchar] (20) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Identification No_] [varchar] (13) NULL,
[Customs Declaration No_] [varchar] (10) NULL,
[Debit Memo] [tinyint] NULL,
[To Invoice No_] [varchar] (20) NULL,
[To Invoice Date] [datetime] NULL,
[Void] [tinyint] NULL,
[Void Date] [datetime] NULL,
[VAT Subject] [varchar] (30) NULL,
[Sales Protocol] [tinyint] NULL,
[Do not include in VAT Ledgers] [tinyint] NULL,
[VAT Settlement Date] [datetime] NULL,
[VAT Exempt Ground] [varchar] (10) NULL,
[Composed By] [varchar] (30) NULL,
[VAT Protocol] [tinyint] NULL,
[Date Received] [datetime] NULL,
[Time Received] [datetime] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[Unrealized VAT] [tinyint] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_Invoice_Header] on [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Header]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_Invoice_Header] ON [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Header] ([No_])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Line]
(
[Document No_] [varchar] (20) NULL,
[Line No_] [int] NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Location Code] [varchar] (10) NULL,
[Posting Group] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[VAT %] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Allow Invoice Disc_] [tinyint] NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Job No_] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Entry Point] [varchar] (10) NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Tax Group Code] [varchar] (10) NULL,
[Use Tax] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[System-Created Entry] [tinyint] NULL,
[Line Amount] [decimal] (38, 20) NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Prepayment Line] [tinyint] NULL,
[IC Partner Code] [varchar] (20) NULL,
[Posting Date] [datetime] NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Line Type] [int] NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[Bin Code] [varchar] (20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Maintenance Code] [varchar] (10) NULL,
[Insurance No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Use Duplication List] [tinyint] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Item Category Code] [varchar] (10) NULL,
[Nonstock] [tinyint] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Product Group Code] [varchar] (10) NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Operation No_] [varchar] (10) NULL,
[Work Center No_] [varchar] (20) NULL,
[Prod_ Order Line No_] [int] NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Routing Reference No_] [int] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_Invoice_Line] on [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Line]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_Invoice_Line] ON [tsa].[ics_land_Navision_Bul_Purchase_Invoice_Line] ([Document No_], [No_])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Line]
(
[Document Type] [int] NULL,
[Document No_] [varchar] (20) NULL,
[Line No_] [int] NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Location Code] [varchar] (10) NULL,
[Posting Group] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Outstanding Quantity] [decimal] (38, 20) NULL,
[Qty_ to Invoice] [decimal] (38, 20) NULL,
[Qty_ to Receive] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[VAT %] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Allow Invoice Disc_] [tinyint] NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Job No_] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Outstanding Amount] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Quantity Received] [decimal] (38, 20) NULL,
[Quantity Invoiced] [decimal] (38, 20) NULL,
[Receipt No_] [varchar] (20) NULL,
[Receipt Line No_] [int] NULL,
[Profit %] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Sales Order No_] [varchar] (20) NULL,
[Sales Order Line No_] [int] NULL,
[Drop Shipment] [tinyint] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Entry Point] [varchar] (10) NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Tax Group Code] [varchar] (10) NULL,
[Use Tax] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Outstanding Amount (LCY)] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced (LCY)] [decimal] (38, 20) NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[System-Created Entry] [tinyint] NULL,
[Line Amount] [decimal] (38, 20) NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[Inv_ Disc_ Amount to Invoice] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Prepmt_ Line Amount] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Inv_] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Incl_ VAT] [decimal] (38, 20) NULL,
[Prepayment Amount] [decimal] (38, 20) NULL,
[Prepmt_ VAT Base Amt_] [decimal] (38, 20) NULL,
[Prepayment VAT %] [decimal] (38, 20) NULL,
[Prepmt_ VAT Calc_ Type] [int] NULL,
[Prepayment VAT Identifier] [varchar] (10) NULL,
[Prepayment Tax Area Code] [varchar] (20) NULL,
[Prepayment Tax Liable] [tinyint] NULL,
[Prepayment Tax Group Code] [varchar] (10) NULL,
[Prepmt Amt to Deduct] [decimal] (38, 20) NULL,
[Prepmt Amt Deducted] [decimal] (38, 20) NULL,
[Prepayment Line] [tinyint] NULL,
[Prepmt_ Amount Inv_ Incl_ VAT] [decimal] (38, 20) NULL,
[IC Partner Code] [varchar] (20) NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Line Type] [int] NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[Bin Code] [varchar] (20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Outstanding Qty_ (Base)] [decimal] (38, 20) NULL,
[Qty_ to Invoice (Base)] [decimal] (38, 20) NULL,
[Qty_ to Receive (Base)] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced (Base)] [decimal] (38, 20) NULL,
[Qty_ Received (Base)] [decimal] (38, 20) NULL,
[Qty_ Invoiced (Base)] [decimal] (38, 20) NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Maintenance Code] [varchar] (10) NULL,
[Insurance No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Use Duplication List] [tinyint] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Item Category Code] [varchar] (10) NULL,
[Nonstock] [tinyint] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Product Group Code] [varchar] (10) NULL,
[Special Order] [tinyint] NULL,
[Special Order Sales No_] [varchar] (20) NULL,
[Special Order Sales Line No_] [int] NULL,
[Completely Received] [tinyint] NULL,
[Requested Receipt Date] [datetime] NULL,
[Promised Receipt Date] [datetime] NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Planned Receipt Date] [datetime] NULL,
[Order Date] [datetime] NULL,
[Allow Item Charge Assignment] [tinyint] NULL,
[Return Qty_ to Ship] [decimal] (38, 20) NULL,
[Return Qty_ to Ship (Base)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped Not Invd_] [decimal] (38, 20) NULL,
[Ret_ Qty_ Shpd Not Invd_(Base)] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_ (LCY)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped] [decimal] (38, 20) NULL,
[Return Qty_ Shipped (Base)] [decimal] (38, 20) NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shipment Line No_] [int] NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Operation No_] [varchar] (10) NULL,
[Work Center No_] [varchar] (20) NULL,
[Finished] [tinyint] NULL,
[Prod_ Order Line No_] [int] NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[MPS Order] [tinyint] NULL,
[Planning Flexibility] [int] NULL,
[Safety Lead Time] [varchar] (32) NULL,
[Routing Reference No_] [int] NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_Line] on [tsa].[ics_land_Navision_Bul_Purchase_Line]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_Line] ON [tsa].[ics_land_Navision_Bul_Purchase_Line] ([Document Type], [Document No_], [No_])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Line_Discount]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Line_Discount]
(
[Item No_] [varchar] (20) NULL,
[Vendor No_] [varchar] (20) NULL,
[Starting Date] [datetime] NULL,
[Currency Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Ending Date] [datetime] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_Line_Discount] on [tsa].[ics_land_Navision_Bul_Purchase_Line_Discount]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_Line_Discount] ON [tsa].[ics_land_Navision_Bul_Purchase_Line_Discount] ([Item No_], [Vendor No_], [Starting Date], [Currency Code], [Variant Code], [Unit of Measure Code], [Minimum Quantity])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Payables_Setup]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Payables_Setup]
(
[timestamp] [binary] (16) NULL,
[Primary_Key] [nvarchar] (10) NULL,
[Discount_Posting] [int] NULL,
[Receipt_on_Invoice] [smallint] NULL,
[Invoice_Rounding] [smallint] NULL,
[Ext__Doc__No__Mandatory] [smallint] NULL,
[Vendor_Nos_] [nvarchar] (10) NULL,
[Quote_Nos_] [nvarchar] (10) NULL,
[Order_Nos_] [nvarchar] (10) NULL,
[Invoice_Nos_] [nvarchar] (10) NULL,
[Posted_Invoice_Nos_] [nvarchar] (10) NULL,
[Credit_Memo_Nos_] [nvarchar] (10) NULL,
[Posted_Credit_Memo_Nos_] [nvarchar] (10) NULL,
[Posted_Receipt_Nos_] [nvarchar] (10) NULL,
[Blanket_Order_Nos_] [nvarchar] (10) NULL,
[Calc__Inv__Discount] [smallint] NULL,
[Appln__between_Currencies] [int] NULL,
[Copy_Comments_Blanket_to_Order] [smallint] NULL,
[Copy_Comments_Order_to_Invoice] [smallint] NULL,
[Copy_Comments_Order_to_Receipt] [smallint] NULL,
[Allow_VAT_Difference] [smallint] NULL,
[Calc__Inv__Disc__per_VAT_ID] [smallint] NULL,
[Posted_Prepmt__Inv__Nos_] [nvarchar] (10) NULL,
[Posted_Prepmt__Cr__Memo_Nos_] [nvarchar] (10) NULL,
[Check_Prepmt__when_Posting] [smallint] NULL,
[Default_Posting_Date] [int] NULL,
[Default_Qty__to_Ship_Rcv_] [int] NULL,
[Archive_Quotes_and_Orders] [smallint] NULL,
[Posted_Return_Shpt__Nos_] [nvarchar] (10) NULL,
[Copy_Cmts_Ret_Ord__to_Ret_Shpt] [smallint] NULL,
[Copy_Cmts_Ret_Ord__to_Cr__Memo] [smallint] NULL,
[Return_Order_Nos_] [nvarchar] (10) NULL,
[Return_Shipment_on_Credit_Memo] [smallint] NULL,
[Exact_Cost_Reversing_Mandatory] [smallint] NULL,
[EU_VAT_Bus__Posting_Group] [nvarchar] (20) NULL,
[Intr__Jnl__Incl__Item_Charges] [smallint] NULL,
[Unreal__VAT_Prot__Nos_] [nvarchar] (20) NULL,
[Posted_Unreal__VAT_Prot__Nos_] [nvarchar] (20) NULL,
[Protokol_VAT_Bus__Post__Group] [nvarchar] (20) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_Payables_Setup] on [tsa].[ics_land_Navision_Bul_Purchase_Payables_Setup]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_Payables_Setup] ON [tsa].[ics_land_Navision_Bul_Purchase_Payables_Setup] ([Primary_Key])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_PrePayment_Pct]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_PrePayment_Pct]
(
[Item No_] [varchar] (20) NULL,
[Vendor No_] [varchar] (20) NULL,
[Starting Date] [datetime] NULL,
[Ending Date] [datetime] NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_PrePayment_Pct] on [tsa].[ics_land_Navision_Bul_Purchase_PrePayment_Pct]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_PrePayment_Pct] ON [tsa].[ics_land_Navision_Bul_Purchase_PrePayment_Pct] ([Item No_], [Vendor No_], [Starting Date])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Purchase_Price]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Purchase_Price]
(
[Item No_] [varchar] (20) NULL,
[Vendor No_] [varchar] (20) NULL,
[Starting Date] [datetime] NULL,
[Currency Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Ending Date] [datetime] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_Purchase_Price] on [tsa].[ics_land_Navision_Bul_Purchase_Price]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_Purchase_Price] ON [tsa].[ics_land_Navision_Bul_Purchase_Price] ([Item No_], [Vendor No_], [Starting Date], [Currency Code], [Variant Code], [Unit of Measure Code], [Minimum Quantity])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_SalesPerson_Purchaser]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_SalesPerson_Purchaser]
(
[Code] [varchar] (10) NULL,
[Name] [varchar] (50) NULL,
[Commission %] [decimal] (38, 20) NULL,
[Global Dimension 1 Code] [varchar] (20) NULL,
[Global Dimension 2 Code] [varchar] (20) NULL,
[E-Mail] [varchar] (80) NULL,
[Phone No_] [varchar] (30) NULL,
[Job Title] [varchar] (30) NULL,
[Search E-Mail] [varchar] (80) NULL,
[E-Mail 2] [varchar] (80) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Navision_Bul_SalesPerson_Purchaser] on [tsa].[ics_land_Navision_Bul_SalesPerson_Purchaser]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Navision_Bul_SalesPerson_Purchaser] ON [tsa].[ics_land_Navision_Bul_SalesPerson_Purchaser] ([Code])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Bul_Std_Purchase_Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Bul_Std_Purchase_Line]
(
[Standard Purchase Code] [varchar] (10) NULL,
[Line No_] [int] NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Description] [varchar] (50) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Amount Excl_ VAT] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_Standard Purchase Line] on [tsa].[ics_land_Navision_Bul_Std_Purchase_Line]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_Standard Purchase Line] ON [tsa].[ics_land_Navision_Bul_Std_Purchase_Line] ([Standard Purchase Code], [Line No_])
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Code]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Code]
(
[Code] [nvarchar] (10) NULL,
[Description] [nvarchar] (50) NULL,
[Currency_Code] [nvarchar] (10) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Header]
(
[Document Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Pay-to Name] [varchar] (50) NULL,
[Pay-to Name 2] [varchar] (50) NULL,
[Pay-to Address] [varchar] (50) NULL,
[Pay-to Address 2] [varchar] (50) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (50) NULL,
[Your Reference] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Name] [varchar] (50) NULL,
[Ship-to Name 2] [varchar] (50) NULL,
[Ship-to Address] [varchar] (50) NULL,
[Ship-to Address 2] [varchar] (50) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Contact] [varchar] (50) NULL,
[Order Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Expected Receipt Date] [datetime] NULL,
[Posting Description] [varchar] (50) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Due Date] [datetime] NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Location Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Prices Including VAT] [tinyint] NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Language Code] [varchar] (10) NULL,
[Purchaser Code] [varchar] (10) NULL,
[Order Class] [varchar] (10) NULL,
[No_ Printed] [int] NULL,
[On Hold] [varchar] (3) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Receive] [tinyint] NULL,
[Invoice] [tinyint] NULL,
[Receiving No_] [varchar] (20) NULL,
[Posting No_] [varchar] (20) NULL,
[Last Receiving No_] [varchar] (20) NULL,
[Last Posting No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Shipment No_] [varchar] (20) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[Vendor Cr_ Memo No_] [varchar] (20) NULL,
[VAT Registration No_] [varchar] (20) NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Reason Code] [varchar] (10) NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[VAT Country_Region Code] [varchar] (10) NULL,
[Buy-from Vendor Name] [varchar] (50) NULL,
[Buy-from Vendor Name 2] [varchar] (50) NULL,
[Buy-from Address] [varchar] (50) NULL,
[Buy-from Address 2] [varchar] (50) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (50) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to Country_Region Code] [varchar] (10) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from Country_Region Code] [varchar] (10) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Country_Region Code] [varchar] (10) NULL,
[Bal_ Account Type] [int] NULL,
[Order Address Code] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Correction] [tinyint] NULL,
[Document Date] [datetime] NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Payment Method Code] [varchar] (10) NULL,
[No_ Series] [varchar] (10) NULL,
[Posting No_ Series] [varchar] (10) NULL,
[Receiving No_ Series] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[Applies-to ID] [varchar] (20) NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[Status] [int] NULL,
[Invoice Discount Calculation] [int] NULL,
[Invoice Discount Value] [decimal] (38, 20) NULL,
[Send IC Document] [tinyint] NULL,
[IC Status] [int] NULL,
[Buy-from IC Partner Code] [varchar] (20) NULL,
[Pay-to IC Partner Code] [varchar] (20) NULL,
[IC Direction] [int] NULL,
[Prepayment No_] [varchar] (20) NULL,
[Last Prepayment No_] [varchar] (20) NULL,
[Prepmt_ Cr_ Memo No_] [varchar] (20) NULL,
[Last Prepmt_ Cr_ Memo No_] [varchar] (20) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Prepayment No_ Series] [varchar] (10) NULL,
[Compress Prepayment] [tinyint] NULL,
[Prepayment Due Date] [datetime] NULL,
[Prepmt_ Cr_ Memo No_ Series] [varchar] (10) NULL,
[Prepmt_ Posting Description] [varchar] (50) NULL,
[Prepmt_ Pmt_ Discount Date] [datetime] NULL,
[Prepmt_ Payment Terms Code] [varchar] (10) NULL,
[Prepmt_ Payment Discount %] [decimal] (38, 20) NULL,
[Quote No_] [varchar] (20) NULL,
[Doc_ No_ Occurrence] [int] NULL,
[Campaign No_] [varchar] (20) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Posting from Whse_ Ref_] [int] NULL,
[Requested Receipt Date] [datetime] NULL,
[Promised Receipt Date] [datetime] NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Vendor Authorization No_] [varchar] (20) NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shipment No_ Series] [varchar] (10) NULL,
[Ship] [tinyint] NULL,
[Last Return Shipment No_] [varchar] (20) NULL,
[Assigned User ID] [varchar] (20) NULL,
[Identification No_] [varchar] (13) NULL,
[Customs Declaration No_] [varchar] (30) NULL,
[Debit Memo] [tinyint] NULL,
[To Invoice No_] [varchar] (20) NULL,
[To Invoice Date] [datetime] NULL,
[Void] [tinyint] NULL,
[Void Date] [datetime] NULL,
[VAT Subject] [varchar] (30) NULL,
[Sales Protocol] [tinyint] NULL,
[Do not include in VAT Ledgers] [tinyint] NULL,
[VAT Settlement Date] [datetime] NULL,
[VAT Exempt Ground] [varchar] (10) NULL,
[Composed By] [varchar] (30) NULL,
[Transport Country_Region Code] [varchar] (10) NULL,
[Speditor] [varchar] (10) NULL,
[Date Received] [datetime] NULL,
[Time Received] [datetime] NULL,
[BizTalk Purchase Quote] [tinyint] NULL,
[BizTalk Purch_ Order Cnfmn_] [tinyint] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[BizTalk Purchase Receipt] [tinyint] NULL,
[BizTalk Purchase Credit Memo] [tinyint] NULL,
[Date Sent] [datetime] NULL,
[Time Sent] [datetime] NULL,
[BizTalk Request for Purch_ Qte] [tinyint] NULL,
[BizTalk Purchase Order] [tinyint] NULL,
[Vendor Quote No_] [varchar] (20) NULL,
[BizTalk Document Sent] [tinyint] NULL,
[Unrealized VAT] [tinyint] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Invoice_Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Invoice_Header]
(
[No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Pay-to Name] [varchar] (50) NULL,
[Pay-to Name 2] [varchar] (50) NULL,
[Pay-to Address] [varchar] (50) NULL,
[Pay-to Address 2] [varchar] (50) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (50) NULL,
[Your Reference] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Name] [varchar] (50) NULL,
[Ship-to Name 2] [varchar] (50) NULL,
[Ship-to Address] [varchar] (50) NULL,
[Ship-to Address 2] [varchar] (50) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Contact] [varchar] (50) NULL,
[Order Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Expected Receipt Date] [datetime] NULL,
[Posting Description] [varchar] (50) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Due Date] [datetime] NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Location Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Prices Including VAT] [tinyint] NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Language Code] [varchar] (10) NULL,
[Purchaser Code] [varchar] (10) NULL,
[Order No_] [varchar] (20) NULL,
[No_ Printed] [int] NULL,
[On Hold] [varchar] (3) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[VAT Registration No_] [varchar] (20) NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Reason Code] [varchar] (10) NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[VAT Country_Region Code] [varchar] (10) NULL,
[Buy-from Vendor Name] [varchar] (50) NULL,
[Buy-from Vendor Name 2] [varchar] (50) NULL,
[Buy-from Address] [varchar] (50) NULL,
[Buy-from Address 2] [varchar] (50) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (50) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to Country_Region Code] [varchar] (10) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from Country_Region Code] [varchar] (10) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Country_Region Code] [varchar] (10) NULL,
[Bal_ Account Type] [int] NULL,
[Order Address Code] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Correction] [tinyint] NULL,
[Document Date] [datetime] NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Payment Method Code] [varchar] (10) NULL,
[Pre-Assigned No_ Series] [varchar] (10) NULL,
[No_ Series] [varchar] (10) NULL,
[Order No_ Series] [varchar] (10) NULL,
[Pre-Assigned No_] [varchar] (20) NULL,
[User ID] [varchar] (20) NULL,
[Source Code] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[Prepayment No_ Series] [varchar] (10) NULL,
[Prepayment Invoice] [tinyint] NULL,
[Prepayment Order No_] [varchar] (20) NULL,
[Quote No_] [varchar] (20) NULL,
[Campaign No_] [varchar] (20) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Identification No_] [varchar] (13) NULL,
[Customs Declaration No_] [varchar] (10) NULL,
[Debit Memo] [tinyint] NULL,
[To Invoice No_] [varchar] (20) NULL,
[To Invoice Date] [datetime] NULL,
[Void] [tinyint] NULL,
[Void Date] [datetime] NULL,
[VAT Subject] [varchar] (30) NULL,
[Sales Protocol] [tinyint] NULL,
[Do not include in VAT Ledgers] [tinyint] NULL,
[VAT Settlement Date] [datetime] NULL,
[VAT Exempt Ground] [varchar] (10) NULL,
[Composed By] [varchar] (30) NULL,
[VAT Protocol] [tinyint] NULL,
[Date Received] [datetime] NULL,
[Time Received] [datetime] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[Unrealized VAT] [tinyint] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Invoice_Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Invoice_Line]
(
[Document No_] [varchar] (20) NULL,
[Line No_] [int] NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Location Code] [varchar] (10) NULL,
[Posting Group] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[VAT %] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Allow Invoice Disc_] [tinyint] NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Job No_] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Entry Point] [varchar] (10) NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Tax Group Code] [varchar] (10) NULL,
[Use Tax] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[System-Created Entry] [tinyint] NULL,
[Line Amount] [decimal] (38, 20) NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Prepayment Line] [tinyint] NULL,
[IC Partner Code] [varchar] (20) NULL,
[Posting Date] [datetime] NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Line Type] [int] NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[Bin Code] [varchar] (20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Maintenance Code] [varchar] (10) NULL,
[Insurance No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Use Duplication List] [tinyint] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Item Category Code] [varchar] (10) NULL,
[Nonstock] [tinyint] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Product Group Code] [varchar] (10) NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Operation No_] [varchar] (10) NULL,
[Work Center No_] [varchar] (20) NULL,
[Prod_ Order Line No_] [int] NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Routing Reference No_] [int] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Line]
(
[Document Type] [int] NULL,
[Document No_] [varchar] (20) NULL,
[Line No_] [int] NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Location Code] [varchar] (10) NULL,
[Posting Group] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Outstanding Quantity] [decimal] (38, 20) NULL,
[Qty_ to Invoice] [decimal] (38, 20) NULL,
[Qty_ to Receive] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[VAT %] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Allow Invoice Disc_] [tinyint] NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Job No_] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Outstanding Amount] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Quantity Received] [decimal] (38, 20) NULL,
[Quantity Invoiced] [decimal] (38, 20) NULL,
[Receipt No_] [varchar] (20) NULL,
[Receipt Line No_] [int] NULL,
[Profit %] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Sales Order No_] [varchar] (20) NULL,
[Sales Order Line No_] [int] NULL,
[Drop Shipment] [tinyint] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Entry Point] [varchar] (10) NULL,
[Area] [varchar] (10) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Tax Group Code] [varchar] (10) NULL,
[Use Tax] [tinyint] NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Outstanding Amount (LCY)] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced (LCY)] [decimal] (38, 20) NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[System-Created Entry] [tinyint] NULL,
[Line Amount] [decimal] (38, 20) NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[Inv_ Disc_ Amount to Invoice] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Prepmt_ Line Amount] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Inv_] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Incl_ VAT] [decimal] (38, 20) NULL,
[Prepayment Amount] [decimal] (38, 20) NULL,
[Prepmt_ VAT Base Amt_] [decimal] (38, 20) NULL,
[Prepayment VAT %] [decimal] (38, 20) NULL,
[Prepmt_ VAT Calc_ Type] [int] NULL,
[Prepayment VAT Identifier] [varchar] (10) NULL,
[Prepayment Tax Area Code] [varchar] (20) NULL,
[Prepayment Tax Liable] [tinyint] NULL,
[Prepayment Tax Group Code] [varchar] (10) NULL,
[Prepmt Amt to Deduct] [decimal] (38, 20) NULL,
[Prepmt Amt Deducted] [decimal] (38, 20) NULL,
[Prepayment Line] [tinyint] NULL,
[Prepmt_ Amount Inv_ Incl_ VAT] [decimal] (38, 20) NULL,
[IC Partner Code] [varchar] (20) NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Line Type] [int] NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[Bin Code] [varchar] (20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Outstanding Qty_ (Base)] [decimal] (38, 20) NULL,
[Qty_ to Invoice (Base)] [decimal] (38, 20) NULL,
[Qty_ to Receive (Base)] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced (Base)] [decimal] (38, 20) NULL,
[Qty_ Received (Base)] [decimal] (38, 20) NULL,
[Qty_ Invoiced (Base)] [decimal] (38, 20) NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Maintenance Code] [varchar] (10) NULL,
[Insurance No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Use Duplication List] [tinyint] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Item Category Code] [varchar] (10) NULL,
[Nonstock] [tinyint] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Product Group Code] [varchar] (10) NULL,
[Special Order] [tinyint] NULL,
[Special Order Sales No_] [varchar] (20) NULL,
[Special Order Sales Line No_] [int] NULL,
[Completely Received] [tinyint] NULL,
[Requested Receipt Date] [datetime] NULL,
[Promised Receipt Date] [datetime] NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Planned Receipt Date] [datetime] NULL,
[Order Date] [datetime] NULL,
[Allow Item Charge Assignment] [tinyint] NULL,
[Return Qty_ to Ship] [decimal] (38, 20) NULL,
[Return Qty_ to Ship (Base)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped Not Invd_] [decimal] (38, 20) NULL,
[Ret_ Qty_ Shpd Not Invd_(Base)] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_ (LCY)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped] [decimal] (38, 20) NULL,
[Return Qty_ Shipped (Base)] [decimal] (38, 20) NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shipment Line No_] [int] NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Operation No_] [varchar] (10) NULL,
[Work Center No_] [varchar] (20) NULL,
[Finished] [tinyint] NULL,
[Prod_ Order Line No_] [int] NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[MPS Order] [tinyint] NULL,
[Planning Flexibility] [int] NULL,
[Safety Lead Time] [varchar] (32) NULL,
[Routing Reference No_] [int] NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Line_Discount]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Line_Discount]
(
[Item No_] [varchar] (20) NULL,
[Vendor No_] [varchar] (20) NULL,
[Starting Date] [datetime] NULL,
[Currency Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Ending Date] [datetime] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Payables_Setup]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Payables_Setup]
(
[Primary_Key] [nvarchar] (10) NULL,
[Discount_Posting] [int] NULL,
[Receipt_on_Invoice] [smallint] NULL,
[Invoice_Rounding] [smallint] NULL,
[Ext__Doc__No__Mandatory] [smallint] NULL,
[Vendor_Nos_] [nvarchar] (10) NULL,
[Quote_Nos_] [nvarchar] (10) NULL,
[Order_Nos_] [nvarchar] (10) NULL,
[Invoice_Nos_] [nvarchar] (10) NULL,
[Posted_Invoice_Nos_] [nvarchar] (10) NULL,
[Credit_Memo_Nos_] [nvarchar] (10) NULL,
[Posted_Credit_Memo_Nos_] [nvarchar] (10) NULL,
[Posted_Receipt_Nos_] [nvarchar] (10) NULL,
[Blanket_Order_Nos_] [nvarchar] (10) NULL,
[Calc__Inv__Discount] [smallint] NULL,
[Appln__between_Currencies] [int] NULL,
[Copy_Comments_Blanket_to_Order] [smallint] NULL,
[Copy_Comments_Order_to_Invoice] [smallint] NULL,
[Copy_Comments_Order_to_Receipt] [smallint] NULL,
[Allow_VAT_Difference] [smallint] NULL,
[Calc__Inv__Disc__per_VAT_ID] [smallint] NULL,
[Posted_Prepmt__Inv__Nos_] [nvarchar] (10) NULL,
[Posted_Prepmt__Cr__Memo_Nos_] [nvarchar] (10) NULL,
[Check_Prepmt__when_Posting] [smallint] NULL,
[Default_Posting_Date] [int] NULL,
[Default_Qty__to_Ship_Rcv_] [int] NULL,
[Archive_Quotes_and_Orders] [smallint] NULL,
[Posted_Return_Shpt__Nos_] [nvarchar] (10) NULL,
[Copy_Cmts_Ret_Ord__to_Ret_Shpt] [smallint] NULL,
[Copy_Cmts_Ret_Ord__to_Cr__Memo] [smallint] NULL,
[Return_Order_Nos_] [nvarchar] (10) NULL,
[Return_Shipment_on_Credit_Memo] [smallint] NULL,
[Exact_Cost_Reversing_Mandatory] [smallint] NULL,
[EU_VAT_Bus__Posting_Group] [nvarchar] (20) NULL,
[Intr__Jnl__Incl__Item_Charges] [smallint] NULL,
[Unreal__VAT_Prot__Nos_] [nvarchar] (20) NULL,
[Posted_Unreal__VAT_Prot__Nos_] [nvarchar] (20) NULL,
[Protokol_VAT_Bus__Post__Group] [nvarchar] (20) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_PrePayment_Pct]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_PrePayment_Pct]
(
[Item No_] [varchar] (20) NULL,
[Vendor No_] [varchar] (20) NULL,
[Starting Date] [datetime] NULL,
[Ending Date] [datetime] NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Purchase_Price]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Purchase_Price]
(
[Item No_] [varchar] (20) NULL,
[Vendor No_] [varchar] (20) NULL,
[Starting Date] [datetime] NULL,
[Currency Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Ending Date] [datetime] NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_SalesPerson_Purchaser]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_SalesPerson_Purchaser]
(
[Code] [varchar] (10) NULL,
[Name] [varchar] (50) NULL,
[Commission %] [decimal] (38, 20) NULL,
[Global Dimension 1 Code] [varchar] (20) NULL,
[Global Dimension 2 Code] [varchar] (20) NULL,
[E-Mail] [varchar] (80) NULL,
[Phone No_] [varchar] (30) NULL,
[Job Title] [varchar] (30) NULL,
[Search E-Mail] [varchar] (80) NULL,
[E-Mail 2] [varchar] (80) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Std_Purchase_Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Std_Purchase_Line]
(
[Standard Purchase Code] [varchar] (10) NULL,
[Line No_] [int] NULL,
[Type] [int] NULL,
[No_] [varchar] (20) NULL,
[Description] [varchar] (50) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Amount Excl_ VAT] [decimal] (38, 20) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Variant Code] [varchar] (10) NULL,
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [nvarchar] (10) NULL,
[EtlSourceTable] [varchar] (200) NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [nvarchar] (200) NULL,
[ExcludeFromMerge] [nvarchar] (10) NULL,
[IsDuplicate] [nvarchar] (10) NULL
)
GO
