-- <Migration ID="712d74ed-b8c3-4458-a1ae-47ec29c8d22b" />
GO

PRINT N'Creating [psa].[ics_stg_baan_ttdpur041610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur041610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur041610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur041610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amta] [float] NULL,
[t_bqua] [float] NULL,
[t_btsp] [tinyint] NULL,
[t_cact] [varchar] (8) NULL,
[t_ccco] [varchar] (8) NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_citg] [varchar] (6) NULL,
[t_citt] [varchar] (3) NULL,
[t_clot] [varchar] (16) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_cpla] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_csgp] [varchar] (6) NULL,
[t_cspa] [varchar] (8) NULL,
[t_cstl] [varchar] (4) NULL,
[t_ctrj] [varchar] (3) NULL,
[t_cupp] [varchar] (3) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvpp] [float] NULL,
[t_cvqp] [float] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddta] [datetime] NULL,
[t_ddtb] [datetime] NULL,
[t_ddtc] [datetime] NULL,
[t_ddtd] [datetime] NULL,
[t_dim1] [varchar] (6) NULL,
[t_dim2] [varchar] (6) NULL,
[t_dim3] [varchar] (6) NULL,
[t_dim4] [varchar] (6) NULL,
[t_dim5] [varchar] (6) NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dlev_1] [tinyint] NULL,
[t_dlev_2] [tinyint] NULL,
[t_dlev_3] [tinyint] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_dqua] [float] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_lsel] [tinyint] NULL,
[t_odat] [datetime] NULL,
[t_opno] [smallint] NULL,
[t_opol] [tinyint] NULL,
[t_oqua] [float] NULL,
[t_orno] [int] NULL,
[t_pacn] [varchar] (12) NULL,
[t_pdno] [int] NULL,
[t_plev] [tinyint] NULL,
[t_pono] [smallint] NULL,
[t_posi] [smallint] NULL,
[t_pric] [float] NULL,
[t_quad] [float] NULL,
[t_qual] [tinyint] NULL,
[t_quap] [float] NULL,
[t_revi] [varchar] (6) NULL,
[t_sdsc] [tinyint] NULL,
[t_sorn] [int] NULL,
[t_spon] [smallint] NULL,
[t_srvo] [int] NULL,
[t_srvp] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_txta] [int] NULL,
[t_typ1] [tinyint] NULL,
[t_typ2] [tinyint] NULL,
[t_typ3] [tinyint] NULL,
[t_typ4] [tinyint] NULL,
[t_typ5] [tinyint] NULL,
[t_widt] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur042610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur042610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur042610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur042610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cadr] [varchar] (6) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ckor] [tinyint] NULL,
[t_geoc_l] [varchar] (10) NULL,
[t_nama] [varchar] (35) NULL,
[t_namb] [varchar] (30) NULL,
[t_namc] [varchar] (30) NULL,
[t_namd] [varchar] (30) NULL,
[t_name] [varchar] (30) NULL,
[t_namf] [varchar] (30) NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_pstc] [varchar] (10) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur081610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur081610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur081610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur081610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amta] [float] NULL,
[t_cntr] [varchar] (3) NULL,
[t_item] [varchar] (16) NULL,
[t_orno] [int] NULL,
[t_qana] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur045610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur045610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur045610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur045610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amnt] [float] NULL,
[t_bqua] [float] NULL,
[t_cdis] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_cono] [int] NULL,
[t_coop] [float] NULL,
[t_copr] [float] NULL,
[t_cpcp] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_cwar] [varchar] (3) NULL,
[t_damt_1] [float] NULL,
[t_damt_2] [float] NULL,
[t_damt_3] [float] NULL,
[t_date] [datetime] NULL,
[t_ddtb] [datetime] NULL,
[t_dino] [varchar] (10) NULL,
[t_diqu] [float] NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dqua] [float] NULL,
[t_fico] [smallint] NULL,
[t_iamt] [float] NULL,
[t_invd] [datetime] NULL,
[t_invn] [int] NULL,
[t_iqan] [float] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam] [float] NULL,
[t_mark] [tinyint] NULL,
[t_matc] [tinyint] NULL,
[t_odam] [float] NULL,
[t_opno] [smallint] NULL,
[t_orno] [int] NULL,
[t_pdno] [int] NULL,
[t_pmsk] [varchar] (20) NULL,
[t_pono] [smallint] NULL,
[t_posi] [smallint] NULL,
[t_pric] [float] NULL,
[t_quad] [float] NULL,
[t_quap] [float] NULL,
[t_reno] [int] NULL,
[t_rono] [smallint] NULL,
[t_spur] [tinyint] NULL,
[t_srnb] [tinyint] NULL,
[t_stsc] [tinyint] NULL,
[t_stsd] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_torn] [int] NULL,
[t_tpon] [smallint] NULL,
[t_tsrn] [smallint] NULL,
[t_txta] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur046610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur046610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur046610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur046610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amta] [float] NULL,
[t_amtb] [float] NULL,
[t_amtc] [float] NULL,
[t_aprp] [smallint] NULL,
[t_apry] [smallint] NULL,
[t_ccur] [varchar] (3) NULL,
[t_clos] [tinyint] NULL,
[t_icom] [smallint] NULL,
[t_invn] [int] NULL,
[t_orno] [int] NULL,
[t_pdat] [datetime] NULL,
[t_pono] [smallint] NULL,
[t_qana] [float] NULL,
[t_srnb] [tinyint] NULL,
[t_srni] [tinyint] NULL,
[t_stsp] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_ttyp] [varchar] (3) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur082610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur082610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur082610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur082610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amta] [float] NULL,
[t_cpgp] [varchar] (6) NULL,
[t_orno] [int] NULL,
[t_qana] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur302610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur302610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur302610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur302610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cono] [int] NULL,
[t_ddta] [datetime] NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_posi] [smallint] NULL,
[t_quan] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur047610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur047610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur047610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur047610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cntr] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_cwar] [varchar] (3) NULL,
[t_opol] [tinyint] NULL,
[t_orno] [int] NULL,
[t_ponb] [smallint] NULL,
[t_pono] [smallint] NULL,
[t_qana] [float] NULL,
[t_sitm] [varchar] (16) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur050610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur050610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur050610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur050610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cbrn] [varchar] (6) NULL,
[t_ccon] [int] NULL,
[t_ccor] [varchar] (3) NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdec] [varchar] (3) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_cfsg] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_corg] [tinyint] NULL,
[t_cosn] [varchar] (8) NULL,
[t_cotp] [varchar] (3) NULL,
[t_cpay] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_crcd] [varchar] (3) NULL,
[t_creg] [varchar] (3) NULL,
[t_ctcd] [varchar] (3) NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_odis] [real] NULL,
[t_orno] [int] NULL,
[t_prno] [int] NULL,
[t_pspr] [varchar] (6) NULL,
[t_pstx] [varchar] (6) NULL,
[t_ragr] [varchar] (16) NULL,
[t_ratf] [int] NULL,
[t_ratp] [float] NULL,
[t_refa] [varchar] (30) NULL,
[t_refb] [varchar] (20) NULL,
[t_stat] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_trdt] [datetime] NULL,
[t_trtm] [int] NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL,
[t_user] [varchar] (12) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur051610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur051610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur051610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur051610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amta] [float] NULL,
[t_btsp] [tinyint] NULL,
[t_cact] [varchar] (8) NULL,
[t_ccco] [varchar] (8) NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_cdsc_1] [varchar] (3) NULL,
[t_cdsc_2] [varchar] (3) NULL,
[t_cdsc_3] [varchar] (3) NULL,
[t_citg] [varchar] (6) NULL,
[t_ckor] [tinyint] NULL,
[t_clot] [varchar] (16) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_coop] [float] NULL,
[t_copr] [float] NULL,
[t_cosn] [varchar] (8) NULL,
[t_cpla] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_crcd] [varchar] (3) NULL,
[t_csgp] [varchar] (6) NULL,
[t_cspa] [varchar] (8) NULL,
[t_cstl] [varchar] (4) NULL,
[t_ctcd] [varchar] (3) NULL,
[t_cupp] [varchar] (3) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvpp] [float] NULL,
[t_cvqp] [float] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddta] [datetime] NULL,
[t_ddtb] [datetime] NULL,
[t_ddtc] [datetime] NULL,
[t_dim1] [varchar] (6) NULL,
[t_dim2] [varchar] (6) NULL,
[t_dim3] [varchar] (6) NULL,
[t_dim4] [varchar] (6) NULL,
[t_dim5] [varchar] (6) NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dlev_1] [tinyint] NULL,
[t_dlev_2] [tinyint] NULL,
[t_dlev_3] [tinyint] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_egen] [tinyint] NULL,
[t_invd] [datetime] NULL,
[t_invn] [int] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_logn] [varchar] (16) NULL,
[t_lsel] [tinyint] NULL,
[t_odat] [datetime] NULL,
[t_opno] [smallint] NULL,
[t_opol] [tinyint] NULL,
[t_orno] [int] NULL,
[t_pacn] [varchar] (12) NULL,
[t_pcsr] [tinyint] NULL,
[t_pdno] [int] NULL,
[t_plev] [tinyint] NULL,
[t_pmsk] [varchar] (20) NULL,
[t_pono] [smallint] NULL,
[t_posi] [smallint] NULL,
[t_pric] [float] NULL,
[t_qana] [float] NULL,
[t_quad] [float] NULL,
[t_qual] [tinyint] NULL,
[t_quap] [float] NULL,
[t_revi] [varchar] (6) NULL,
[t_sern] [smallint] NULL,
[t_sorn] [int] NULL,
[t_spon] [smallint] NULL,
[t_spur] [tinyint] NULL,
[t_srvo] [int] NULL,
[t_srvp] [smallint] NULL,
[t_stcd] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_trdt] [datetime] NULL,
[t_trtm] [int] NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL,
[t_typ1] [tinyint] NULL,
[t_typ2] [tinyint] NULL,
[t_typ3] [tinyint] NULL,
[t_typ4] [tinyint] NULL,
[t_typ5] [tinyint] NULL,
[t_user] [varchar] (12) NULL,
[t_widt] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur061610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur061610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur061610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur061610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_citg] [varchar] (6) NULL,
[t_dejt] [int] NULL,
[t_dete] [int] NULL,
[t_detl] [int] NULL,
[t_frte] [real] NULL,
[t_frtl] [real] NULL,
[t_item] [varchar] (16) NULL,
[t_ndte] [smallint] NULL,
[t_ndtl] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_year] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur080610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur080610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur080610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur080610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cvpp] [float] NULL,
[t_cvqp] [float] NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_disl_1] [smallint] NULL,
[t_disl_2] [smallint] NULL,
[t_disl_3] [smallint] NULL,
[t_dlev_1] [tinyint] NULL,
[t_dlev_2] [tinyint] NULL,
[t_dlev_3] [tinyint] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_itst] [tinyint] NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_oqua] [float] NULL,
[t_orno] [int] NULL,
[t_pgst_1] [tinyint] NULL,
[t_pgst_2] [tinyint] NULL,
[t_pgst_3] [tinyint] NULL,
[t_plev] [tinyint] NULL,
[t_plst_1] [tinyint] NULL,
[t_plst_2] [tinyint] NULL,
[t_plst_3] [tinyint] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_updd_1] [tinyint] NULL,
[t_updd_2] [tinyint] NULL,
[t_updd_3] [tinyint] NULL,
[t_updp] [tinyint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur300610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur300610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur300610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur300610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_ccon] [int] NULL,
[t_ccor] [varchar] (3) NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdat] [datetime] NULL,
[t_cdec] [varchar] (3) NULL,
[t_cdes] [varchar] (30) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_cpay] [varchar] (3) NULL,
[t_csts] [tinyint] NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_edat] [datetime] NULL,
[t_icap] [tinyint] NULL,
[t_icpr] [tinyint] NULL,
[t_icyp] [tinyint] NULL,
[t_refe] [varchar] (30) NULL,
[t_sdat] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur301610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur301610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur301610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur301610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_bamt] [float] NULL,
[t_bqan] [float] NULL,
[t_camt] [float] NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdat] [datetime] NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_citt] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cqan] [float] NULL,
[t_cupp] [varchar] (3) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvpp] [float] NULL,
[t_cvqp] [float] NULL,
[t_cwar] [varchar] (3) NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_icyp] [tinyint] NULL,
[t_ieva] [tinyint] NULL,
[t_ipri] [tinyint] NULL,
[t_iqab] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_maxq] [float] NULL,
[t_minq] [float] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_quan] [float] NULL,
[t_sdsc] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_txta] [int] NULL,
[t_widt] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur303610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur303610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur303610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur303610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cadr] [varchar] (6) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ckor] [tinyint] NULL,
[t_cono] [int] NULL,
[t_geoc_l] [varchar] (10) NULL,
[t_nama] [varchar] (35) NULL,
[t_namb] [varchar] (30) NULL,
[t_namc] [varchar] (30) NULL,
[t_namd] [varchar] (30) NULL,
[t_name] [varchar] (30) NULL,
[t_namf] [varchar] (30) NULL,
[t_pstc] [varchar] (10) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur305610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur305610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur305610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur305610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_ccon] [int] NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdat] [datetime] NULL,
[t_cdec] [varchar] (3) NULL,
[t_cdes] [varchar] (30) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_cpay] [varchar] (3) NULL,
[t_csts] [tinyint] NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_edat] [datetime] NULL,
[t_icap] [tinyint] NULL,
[t_icpr] [tinyint] NULL,
[t_icyp] [tinyint] NULL,
[t_idtr] [tinyint] NULL,
[t_loco] [varchar] (8) NULL,
[t_refe] [varchar] (30) NULL,
[t_sdat] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_trdt] [datetime] NULL,
[t_trtm] [int] NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur306610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur306610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur306610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur306610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_bamt] [float] NULL,
[t_bqan] [float] NULL,
[t_camt] [float] NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdat] [datetime] NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_cono] [int] NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cqan] [float] NULL,
[t_cupp] [varchar] (3) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvpp] [float] NULL,
[t_cvqp] [float] NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_icyp] [tinyint] NULL,
[t_idel] [tinyint] NULL,
[t_idil] [tinyint] NULL,
[t_idtr] [tinyint] NULL,
[t_ieva] [tinyint] NULL,
[t_ipri] [tinyint] NULL,
[t_iprl] [tinyint] NULL,
[t_iqab] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_loco] [varchar] (8) NULL,
[t_maxq] [float] NULL,
[t_minq] [float] NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_posi] [smallint] NULL,
[t_pric] [float] NULL,
[t_quan] [float] NULL,
[t_sdsc] [tinyint] NULL,
[t_sern] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_trdt] [datetime] NULL,
[t_trtm] [int] NULL,
[t_txta] [int] NULL,
[t_widt] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur310610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur310610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur310610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur310610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cono] [int] NULL,
[t_pono] [smallint] NULL,
[t_upid] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur332610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur332610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur332610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur332610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_damt] [float] NULL,
[t_dile] [tinyint] NULL,
[t_disc] [real] NULL,
[t_gnpr] [tinyint] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_qanp] [float] NULL,
[t_stdt] [datetime] NULL,
[t_tdat] [datetime] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur333610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur333610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur333610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur333610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis] [varchar] (3) NULL,
[t_cono] [int] NULL,
[t_damt] [float] NULL,
[t_dile] [tinyint] NULL,
[t_disc] [real] NULL,
[t_pono] [smallint] NULL,
[t_qanp] [float] NULL,
[t_stdt] [datetime] NULL,
[t_tdat] [datetime] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur335610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur335610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur335610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur335610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cono] [int] NULL,
[t_dile] [tinyint] NULL,
[t_dmth] [tinyint] NULL,
[t_kogr] [tinyint] NULL,
[t_pono] [smallint] NULL,
[t_stsc] [tinyint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur336610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur336610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur336610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur336610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cono] [int] NULL,
[t_dile] [tinyint] NULL,
[t_dmth] [tinyint] NULL,
[t_pono] [smallint] NULL,
[t_stsc] [tinyint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur400610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur400610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur400610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur400610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_bqua] [float] NULL,
[t_date] [datetime] NULL,
[t_dino] [varchar] (10) NULL,
[t_diqu] [float] NULL,
[t_oqua] [float] NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_text] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur000610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur000610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur000610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur000610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_acpd_4] [tinyint] NULL,
[t_agto_4] [tinyint] NULL,
[t_arac_4] [tinyint] NULL,
[t_back_4] [tinyint] NULL,
[t_brla_3] [tinyint] NULL,
[t_cabt_3] [tinyint] NULL,
[t_caiq_4] [tinyint] NULL,
[t_capo_1] [tinyint] NULL,
[t_citt] [varchar] (3) NULL,
[t_clro_4] [tinyint] NULL,
[t_cmod_3] [tinyint] NULL,
[t_conp_3] [tinyint] NULL,
[t_copy_3] [smallint] NULL,
[t_cppy_3] [tinyint] NULL,
[t_cpty_4] [tinyint] NULL,
[t_cpyp_3] [tinyint] NULL,
[t_csoc_4] [tinyint] NULL,
[t_csog_4] [tinyint] NULL,
[t_cspn_4] [smallint] NULL,
[t_edib] [tinyint] NULL,
[t_erac_4] [tinyint] NULL,
[t_erdc_4] [tinyint] NULL,
[t_fmsa] [tinyint] NULL,
[t_fpri_4] [tinyint] NULL,
[t_hish_3] [tinyint] NULL,
[t_hisl_3] [tinyint] NULL,
[t_hisp_5] [tinyint] NULL,
[t_hisq_1] [tinyint] NULL,
[t_hist_3] [tinyint] NULL,
[t_imae_3] [tinyint] NULL,
[t_lipf_6] [tinyint] NULL,
[t_mavp_4] [tinyint] NULL,
[t_mldi_4] [tinyint] NULL,
[t_muco_3] [tinyint] NULL,
[t_nbol] [smallint] NULL,
[t_ndbe_3] [tinyint] NULL,
[t_pcac_3] [tinyint] NULL,
[t_pccd_5] [tinyint] NULL,
[t_pcus] [tinyint] NULL,
[t_pitd_4] [tinyint] NULL,
[t_pors] [tinyint] NULL,
[t_potd_4] [tinyint] NULL,
[t_pqcp_1] [smallint] NULL,
[t_prcp_4] [smallint] NULL,
[t_puom] [varchar] (3) NULL,
[t_purc_4] [tinyint] NULL,
[t_pusd] [tinyint] NULL,
[t_reno_4] [tinyint] NULL,
[t_rmcp_1] [smallint] NULL,
[t_rnlb_4] [tinyint] NULL,
[t_rpcs_3] [tinyint] NULL,
[t_rpds_1] [int] NULL,
[t_sepi_4] [tinyint] NULL,
[t_sern] [smallint] NULL,
[t_serp_3] [tinyint] NULL,
[t_serp_4] [tinyint] NULL,
[t_serq_1] [tinyint] NULL,
[t_sspc_3] [tinyint] NULL,
[t_sspi_1] [tinyint] NULL,
[t_sspo_4] [tinyint] NULL,
[t_tcsp_5] [tinyint] NULL,
[t_uoia_3] [tinyint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur401610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur401610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur401610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur401610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_clot] [varchar] (16) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_dino] [varchar] (10) NULL,
[t_item] [varchar] (16) NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_qstc] [float] NULL,
[t_qstr] [float] NULL,
[t_sera] [tinyint] NULL,
[t_serb] [int] NULL,
[t_suno] [varchar] (6) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur001610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur001610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur001610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur001610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cbrn] [varchar] (6) NULL,
[t_ccon] [int] NULL,
[t_ccor] [varchar] (3) NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdec] [varchar] (3) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_cotp] [varchar] (3) NULL,
[t_cpay] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_creg] [varchar] (3) NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_exdt] [datetime] NULL,
[t_fixr] [tinyint] NULL,
[t_odis] [real] NULL,
[t_qdat] [datetime] NULL,
[t_qono] [int] NULL,
[t_qspa] [tinyint] NULL,
[t_ratf] [int] NULL,
[t_ratp] [float] NULL,
[t_rdat] [datetime] NULL,
[t_refa] [varchar] (30) NULL,
[t_refb] [varchar] (20) NULL,
[t_rpdt] [datetime] NULL,
[t_rsts] [tinyint] NULL,
[t_rtdt] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur703610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur703610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur703610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur703610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_ckor] [tinyint] NULL,
[t_cosn] [varchar] (8) NULL,
[t_crcd] [varchar] (3) NULL,
[t_ctcd] [varchar] (3) NULL,
[t_date] [datetime] NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_sern] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_time] [int] NULL,
[t_user] [varchar] (12) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur020610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur020610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur020610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur020610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cntr] [varchar] (3) NULL,
[t_item] [varchar] (16) NULL,
[t_suno] [varchar] (6) NULL,
[t_txta] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur704610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur704610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur704610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur704610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_akcd] [varchar] (2) NULL,
[t_cosn] [varchar] (8) NULL,
[t_crcd] [varchar] (3) NULL,
[t_ctcd] [varchar] (3) NULL,
[t_date] [datetime] NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_time] [int] NULL,
[t_user] [varchar] (12) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur002610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur002610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur002610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur002610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cact] [varchar] (8) NULL,
[t_ccco] [varchar] (8) NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_citt] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cpla] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_cspa] [varchar] (8) NULL,
[t_cstl] [varchar] (4) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvqp] [float] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_opol] [tinyint] NULL,
[t_oqua] [float] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_prih] [float] NULL,
[t_proc] [tinyint] NULL,
[t_qdat] [datetime] NULL,
[t_qono] [int] NULL,
[t_qspa] [tinyint] NULL,
[t_rank] [tinyint] NULL,
[t_sdsc] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_txta] [int] NULL,
[t_valp] [real] NULL,
[t_widt] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur010610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur010610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur010610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur010610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cbrn] [varchar] (6) NULL,
[t_ccon] [int] NULL,
[t_ccor] [varchar] (3) NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdec] [varchar] (3) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_cpay] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_creg] [varchar] (3) NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_fixr] [tinyint] NULL,
[t_odis] [real] NULL,
[t_qdat] [datetime] NULL,
[t_qono] [int] NULL,
[t_ratf] [int] NULL,
[t_ratp] [float] NULL,
[t_refa] [varchar] (30) NULL,
[t_refb] [varchar] (20) NULL,
[t_rpdt] [datetime] NULL,
[t_rtdt] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_trdt] [datetime] NULL,
[t_trtm] [int] NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur021610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur021610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur021610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur021610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_ecoq] [float] NULL,
[t_item] [varchar] (16) NULL,
[t_itsu] [varchar] (16) NULL,
[t_mioq] [float] NULL,
[t_oltm] [smallint] NULL,
[t_pric] [float] NULL,
[t_suno] [varchar] (6) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur011610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur011610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur011610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur011610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amnt] [float] NULL,
[t_cact] [varchar] (8) NULL,
[t_ccco] [varchar] (8) NULL,
[t_ccty] [varchar] (3) NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cpla] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_cspa] [varchar] (8) NULL,
[t_cstl] [varchar] (4) NULL,
[t_cuqp] [varchar] (3) NULL,
[t_cvat] [varchar] (9) NULL,
[t_cvqp] [float] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_leng] [float] NULL,
[t_opol] [tinyint] NULL,
[t_oqua] [float] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_prih] [float] NULL,
[t_qdat] [datetime] NULL,
[t_qono] [int] NULL,
[t_qspa] [tinyint] NULL,
[t_sdsc] [tinyint] NULL,
[t_sern] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_thic] [float] NULL,
[t_trdt] [datetime] NULL,
[t_trtm] [int] NULL,
[t_txta] [int] NULL,
[t_widt] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur027610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur027610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur027610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur027610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_ccos] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_inta] [tinyint] NULL,
[t_suno] [varchar] (6) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur036610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur036610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur036610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur036610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cntr] [varchar] (3) NULL,
[t_cuni] [varchar] (3) NULL,
[t_dile] [tinyint] NULL,
[t_dmth] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_kogr] [tinyint] NULL,
[t_stsc] [tinyint] NULL,
[t_suno] [varchar] (6) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur037610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur037610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur037610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur037610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cntr] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_cuni] [varchar] (3) NULL,
[t_dile] [tinyint] NULL,
[t_dmth] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_kogr] [tinyint] NULL,
[t_stsc] [tinyint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur028610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur028610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur028610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur028610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_ccos] [varchar] (3) NULL,
[t_crtr] [tinyint] NULL,
[t_frcs] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_llim] [float] NULL,
[t_luni] [tinyint] NULL,
[t_pono] [smallint] NULL,
[t_puni] [tinyint] NULL,
[t_raun] [varchar] (3) NULL,
[t_ulim] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur030610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur030610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur030610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur030610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_damt] [float] NULL,
[t_dile] [tinyint] NULL,
[t_disc] [real] NULL,
[t_gnpr] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_pric] [float] NULL,
[t_prin] [float] NULL,
[t_qanp] [float] NULL,
[t_stdt] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_tdat] [datetime] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur031610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur031610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur031610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur031610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis] [varchar] (3) NULL,
[t_cpgp] [varchar] (6) NULL,
[t_damt] [float] NULL,
[t_dile] [tinyint] NULL,
[t_disc] [real] NULL,
[t_gnpr] [tinyint] NULL,
[t_qanp] [float] NULL,
[t_stdt] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_tdat] [datetime] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur043610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur043610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur043610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur043610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_comp] [smallint] NULL,
[t_cotp] [varchar] (3) NULL,
[t_cwar] [varchar] (3) NULL,
[t_dole] [tinyint] NULL,
[t_logn] [varchar] (16) NULL,
[t_serp] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur032610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur032610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur032610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur032610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_damt] [float] NULL,
[t_dile] [tinyint] NULL,
[t_disc] [real] NULL,
[t_gnpr] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_pric] [float] NULL,
[t_qanp] [float] NULL,
[t_stdt] [datetime] NULL,
[t_tdat] [datetime] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur033610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur033610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur033610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur033610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis] [varchar] (3) NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cplp] [varchar] (3) NULL,
[t_damt] [float] NULL,
[t_dile] [tinyint] NULL,
[t_disc] [real] NULL,
[t_gnpr] [tinyint] NULL,
[t_qanp] [float] NULL,
[t_stdt] [datetime] NULL,
[t_tdat] [datetime] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur034610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur034610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur034610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur034610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_apyn] [tinyint] NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cplp] [varchar] (3) NULL,
[t_cuni] [varchar] (3) NULL,
[t_dile] [tinyint] NULL,
[t_dmth] [tinyint] NULL,
[t_kogr] [tinyint] NULL,
[t_stsa] [tinyint] NULL,
[t_stsb] [tinyint] NULL,
[t_stsc] [tinyint] NULL,
[t_suno] [varchar] (6) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur048610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur048610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur048610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur048610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_dqua] [float] NULL,
[t_issu] [float] NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur035610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur035610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur035610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur035610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cplp] [varchar] (3) NULL,
[t_cuni] [varchar] (3) NULL,
[t_dile] [tinyint] NULL,
[t_dmth] [tinyint] NULL,
[t_kogr] [tinyint] NULL,
[t_stsa] [tinyint] NULL,
[t_stsb] [tinyint] NULL,
[t_stsc] [tinyint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur040610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur040610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur040610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur040610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cbrn] [varchar] (6) NULL,
[t_ccon] [int] NULL,
[t_ccor] [varchar] (3) NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdec] [varchar] (3) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_cfsg] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_corg] [tinyint] NULL,
[t_cotp] [varchar] (3) NULL,
[t_cpay] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_creg] [varchar] (3) NULL,
[t_ctrj] [varchar] (3) NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_ddtc] [datetime] NULL,
[t_egen] [tinyint] NULL,
[t_odat] [datetime] NULL,
[t_odis] [real] NULL,
[t_orno] [int] NULL,
[t_prno] [int] NULL,
[t_pspr] [varchar] (6) NULL,
[t_pstx] [varchar] (6) NULL,
[t_ragr] [varchar] (16) NULL,
[t_ratf] [int] NULL,
[t_ratp] [float] NULL,
[t_refa] [varchar] (30) NULL,
[t_refb] [varchar] (20) NULL,
[t_suno] [varchar] (6) NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur053610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur053610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur053610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur053610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cosn] [varchar] (8) NULL,
[t_date] [datetime] NULL,
[t_dsca] [varchar] (30) NULL,
[t_orno] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_baan_ttdpur054610]'
GO
CREATE TABLE [psa].[ics_stg_baan_ttdpur054610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur054610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur054610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_eorn] [int] NULL,
[t_epon] [smallint] NULL,
[t_oorn] [int] NULL,
[t_opon] [smallint] NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL
)
GO
