-- <Migration ID="083b44ee-ffa5-4cc2-9b0b-0d14841bb733" />
GO

PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Code]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Code]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Code_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Code_IsDuplicate] DEFAULT ((0)),
[Code] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Description] [varchar] (50) NULL,
[timestamp] [varbinary] (max) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchases & Payables Setup]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchases & Payables Setup]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchases & Payables Setup_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchases & Payables Setup_IsDuplicate] DEFAULT ((0)),
[Allow VAT Difference] [tinyint] NULL,
[Appln_ between Currencies] [int] NULL,
[Archive Quotes and Orders] [tinyint] NULL,
[Blanket Order Nos_] [varchar] (10) NULL,
[Calc_ Inv_ Disc_ per VAT ID] [tinyint] NULL,
[Calc_ Inv_ Discount] [tinyint] NULL,
[Check Prepmt_ when Posting] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Cr_ Memo] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Ret_Shpt] [tinyint] NULL,
[Copy Comments Blanket to Order] [tinyint] NULL,
[Copy Comments Order to Invoice] [tinyint] NULL,
[Copy Comments Order to Receipt] [tinyint] NULL,
[Credit Memo Nos_] [varchar] (10) NULL,
[Default Posting Date] [int] NULL,
[Default Qty_ to Ship_Rcv_] [int] NULL,
[Discount Posting] [int] NULL,
[EU VAT Bus_ Posting Group] [varchar] (20) NULL,
[Exact Cost Reversing Mandatory] [tinyint] NULL,
[Ext_ Doc_ No_ Mandatory] [tinyint] NULL,
[Intr_ Jnl_ Incl_ Item Charges] [tinyint] NULL,
[Invoice Nos_] [varchar] (10) NULL,
[Invoice Rounding] [tinyint] NULL,
[Order Nos_] [varchar] (10) NULL,
[Posted Credit Memo Nos_] [varchar] (10) NULL,
[Posted Invoice Nos_] [varchar] (10) NULL,
[Posted Prepmt_ Cr_ Memo Nos_] [varchar] (10) NULL,
[Posted Prepmt_ Inv_ Nos_] [varchar] (10) NULL,
[Posted Receipt Nos_] [varchar] (10) NULL,
[Posted Return Shpt_ Nos_] [varchar] (10) NULL,
[Posted Unreal_ VAT Prot_ Nos_] [varchar] (20) NULL,
[Primary Key] [varchar] (10) NULL,
[Protokol VAT Bus_ Post_ Group] [varchar] (20) NULL,
[Quote Nos_] [varchar] (10) NULL,
[Receipt on Invoice] [tinyint] NULL,
[Return Order Nos_] [varchar] (10) NULL,
[Return Shipment on Credit Memo] [tinyint] NULL,
[timestamp] [varbinary] (max) NULL,
[Unreal_ VAT Prot_ Nos_] [varchar] (20) NULL,
[Vendor Nos_] [varchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Salesperson_Purchaser]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Salesperson_Purchaser]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Salesperson_Purchaser_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Salesperson_Purchaser_IsDuplicate] DEFAULT ((0)),
[Code] [varchar] (10) NULL,
[Commission %] [decimal] (38, 20) NULL,
[E-Mail] [varchar] (80) NULL,
[E-Mail 2] [varchar] (80) NULL,
[Global Dimension 1 Code] [varchar] (20) NULL,
[Global Dimension 2 Code] [varchar] (20) NULL,
[Job Title] [varchar] (30) NULL,
[Name] [varchar] (50) NULL,
[Phone No_] [varchar] (30) NULL,
[Search E-Mail] [varchar] (80) NULL,
[timestamp] [varbinary] (max) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Line_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Standard Purchase Line_IsDuplicate] DEFAULT ((0)),
[Amount Excl_ VAT] [decimal] (38, 20) NULL,
[Description] [varchar] (50) NULL,
[Line No_] [int] NULL,
[No_] [varchar] (20) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Standard Purchase Code] [varchar] (10) NULL,
[timestamp] [varbinary] (max) NULL,
[Type] [int] NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Header]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Header_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Header_IsDuplicate] DEFAULT ((0)),
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Area] [varchar] (10) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Bal_ Account Type] [int] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[Buy-from Address] [varchar] (30) NULL,
[Buy-from Address 2] [varchar] (30) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (30) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Buy-from Country Code] [varchar] (10) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from Vendor Name] [varchar] (30) NULL,
[Buy-from Vendor Name 2] [varchar] (30) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Correction] [tinyint] NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Custom Invoice No_] [varchar] (20) NULL,
[Date Received] [datetime] NULL,
[Document Date] [datetime] NULL,
[Due Date] [datetime] NULL,
[EU 3-Party Trade] [tinyint] NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Job No_] [varchar] (20) NULL,
[Language Code] [varchar] (10) NULL,
[Location Code] [varchar] (10) NULL,
[No_] [varchar] (20) NULL,
[No_ Printed] [int] NULL,
[No_ Series] [varchar] (10) NULL,
[Not Declaration 394] [tinyint] NULL,
[On Hold] [varchar] (3) NULL,
[Order Address Code] [varchar] (10) NULL,
[Order Date] [datetime] NULL,
[Order No_] [varchar] (20) NULL,
[Order No_ Series] [varchar] (10) NULL,
[Pay-to Address] [varchar] (30) NULL,
[Pay-to Address 2] [varchar] (30) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (30) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Pay-to Country Code] [varchar] (10) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to Name] [varchar] (30) NULL,
[Pay-to Name 2] [varchar] (30) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Payment Method Code] [varchar] (10) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Posting Description] [varchar] (50) NULL,
[Pre-Assigned No_] [varchar] (20) NULL,
[Pre-Assigned No_ Series] [varchar] (10) NULL,
[Prices Including VAT] [tinyint] NULL,
[Purchaser Code] [varchar] (10) NULL,
[Reason Code] [varchar] (10) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Ship-to Address] [varchar] (30) NULL,
[Ship-to Address 2] [varchar] (30) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Contact] [varchar] (30) NULL,
[Ship-to Country Code] [varchar] (10) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Name] [varchar] (30) NULL,
[Ship-to Name 2] [varchar] (30) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Source Code] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Time Received] [datetime] NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[User ID] [varchar] (20) NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Country Code] [varchar] (10) NULL,
[VAT Registration No_] [varchar] (20) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Your Reference] [varchar] (30) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Header]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Header_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Header_IsDuplicate] DEFAULT ((0)),
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Applies-to ID] [varchar] (20) NULL,
[Area] [varchar] (10) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Bal_ Account Type] [int] NULL,
[BizTalk Document Sent] [tinyint] NULL,
[BizTalk Purch_ Order Cnfmn_] [tinyint] NULL,
[BizTalk Purchase Credit Memo] [tinyint] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[BizTalk Purchase Order] [tinyint] NULL,
[BizTalk Purchase Quote] [tinyint] NULL,
[BizTalk Purchase Receipt] [tinyint] NULL,
[BizTalk Request for Purch_ Qte] [tinyint] NULL,
[Buy-from Address] [varchar] (30) NULL,
[Buy-from Address 2] [varchar] (30) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (30) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Buy-from Country Code] [varchar] (10) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from IC Partner Code] [varchar] (20) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from Vendor Name] [varchar] (30) NULL,
[Buy-from Vendor Name 2] [varchar] (30) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Campaign No_] [varchar] (20) NULL,
[Correction] [tinyint] NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Custom Invoice No_] [varchar] (20) NULL,
[Date Received] [datetime] NULL,
[Date Sent] [datetime] NULL,
[Doc_ No_ Occurrence] [int] NULL,
[Document Date] [datetime] NULL,
[Document Type] [int] NULL,
[Due Date] [datetime] NULL,
[EU 3-Party Trade] [tinyint] NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[IC Direction] [int] NULL,
[IC Status] [int] NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Invoice] [tinyint] NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Invoice Discount Calculation] [int] NULL,
[Invoice Discount Value] [decimal] (38, 20) NULL,
[Job No_] [varchar] (20) NULL,
[Language Code] [varchar] (10) NULL,
[Last Posting No_] [varchar] (20) NULL,
[Last Receiving No_] [varchar] (20) NULL,
[Last Return Shipment No_] [varchar] (20) NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Location Code] [varchar] (10) NULL,
[No_] [varchar] (20) NULL,
[No_ Printed] [int] NULL,
[No_ Series] [varchar] (10) NULL,
[Not Declaration 394] [tinyint] NULL,
[On Hold] [varchar] (3) NULL,
[Order Address Code] [varchar] (10) NULL,
[Order Class] [varchar] (10) NULL,
[Order Date] [datetime] NULL,
[Pay-to Address] [varchar] (30) NULL,
[Pay-to Address 2] [varchar] (30) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (30) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Pay-to Country Code] [varchar] (10) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to IC Partner Code] [varchar] (20) NULL,
[Pay-to Name] [varchar] (30) NULL,
[Pay-to Name 2] [varchar] (30) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Payment Method Code] [varchar] (10) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Posting Desc_ Code] [varchar] (10) NULL,
[Posting Description] [varchar] (50) NULL,
[Posting No_] [varchar] (20) NULL,
[Posting No_ Series] [varchar] (10) NULL,
[Posting from Whse_ Ref_] [int] NULL,
[Prices Including VAT] [tinyint] NULL,
[Promised Receipt Date] [datetime] NULL,
[Purchaser Code] [varchar] (10) NULL,
[Reason Code] [varchar] (10) NULL,
[Receive] [tinyint] NULL,
[Receiving No_] [varchar] (20) NULL,
[Receiving No_ Series] [varchar] (10) NULL,
[Requested Receipt Date] [datetime] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shipment No_ Series] [varchar] (10) NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Send IC Document] [tinyint] NULL,
[Ship] [tinyint] NULL,
[Ship-to Address] [varchar] (30) NULL,
[Ship-to Address 2] [varchar] (30) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Contact] [varchar] (30) NULL,
[Ship-to Country Code] [varchar] (10) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Name] [varchar] (30) NULL,
[Ship-to Name 2] [varchar] (30) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Status] [int] NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Time Received] [datetime] NULL,
[Time Sent] [datetime] NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Country Code] [varchar] (10) NULL,
[VAT Registration No_] [varchar] (20) NULL,
[Vendor Authorization No_] [varchar] (20) NULL,
[Vendor Cr_ Memo No_] [varchar] (20) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Vendor Quote No_] [varchar] (20) NULL,
[Vendor Shipment No_] [varchar] (20) NULL,
[Your Reference] [varchar] (30) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Line_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Line_IsDuplicate] DEFAULT ((0)),
[Allow Invoice Disc_] [tinyint] NULL,
[Allow Item Charge Assignment] [tinyint] NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced (LCY)] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Area] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Bin Code] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Completely Received] [tinyint] NULL,
[Country of Origin Code] [varchar] (10) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Currency Code] [varchar] (10) NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Document No_] [varchar] (20) NULL,
[Document Type] [int] NULL,
[Drop Shipment] [tinyint] NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Finished] [tinyint] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Insurance No_] [varchar] (20) NULL,
[Inv_ Disc_ Amount to Invoice] [decimal] (38, 20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Item Category Code] [varchar] (10) NULL,
[Job No_] [varchar] (20) NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Line Amount] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Line No_] [int] NULL,
[Location Code] [varchar] (10) NULL,
[MPS Order] [tinyint] NULL,
[Maintenance Code] [varchar] (10) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[No_] [varchar] (20) NULL,
[No_ of Palet] [decimal] (38, 20) NULL,
[Nonstock] [tinyint] NULL,
[Operation No_] [varchar] (10) NULL,
[Order Date] [datetime] NULL,
[Outstanding Amount] [decimal] (38, 20) NULL,
[Outstanding Amount (LCY)] [decimal] (38, 20) NULL,
[Outstanding Qty_ (Base)] [decimal] (38, 20) NULL,
[Outstanding Quantity] [decimal] (38, 20) NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Palet Type] [varchar] (250) NULL,
[Palet Weight] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Phase Code] [varchar] (10) NULL,
[Planned Receipt Date] [datetime] NULL,
[Planning Flexibility] [int] NULL,
[Posting Group] [varchar] (10) NULL,
[Prod_ Order Line No_] [int] NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Product Group Code] [varchar] (10) NULL,
[Profit %] [decimal] (38, 20) NULL,
[Promised Receipt Date] [datetime] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Qty_ Invoiced (Base)] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced (Base)] [decimal] (38, 20) NULL,
[Qty_ Received (Base)] [decimal] (38, 20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Qty_ to Invoice] [decimal] (38, 20) NULL,
[Qty_ to Invoice (Base)] [decimal] (38, 20) NULL,
[Qty_ to Receive] [decimal] (38, 20) NULL,
[Qty_ to Receive (Base)] [decimal] (38, 20) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Quantity Invoiced] [decimal] (38, 20) NULL,
[Quantity Received] [decimal] (38, 20) NULL,
[Receipt Line No_] [int] NULL,
[Receipt No_] [varchar] (20) NULL,
[Requested Receipt Date] [datetime] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Ret_ Qty_ Shpd Not Invd_(Base)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped] [decimal] (38, 20) NULL,
[Return Qty_ Shipped (Base)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped Not Invd_] [decimal] (38, 20) NULL,
[Return Qty_ to Ship] [decimal] (38, 20) NULL,
[Return Qty_ to Ship (Base)] [decimal] (38, 20) NULL,
[Return Reason Code] [varchar] (10) NULL,
[Return Shipment Line No_] [int] NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shpd_ Not Invd_] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_ (LCY)] [decimal] (38, 20) NULL,
[Routing No_] [varchar] (20) NULL,
[Routing Reference No_] [int] NULL,
[Safety Lead Time] [varchar] (32) NULL,
[Sales Order Line No_] [int] NULL,
[Sales Order No_] [varchar] (20) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Special Order] [tinyint] NULL,
[Special Order Sales Line No_] [int] NULL,
[Special Order Sales No_] [varchar] (20) NULL,
[Step Code] [varchar] (10) NULL,
[System-Created Entry] [tinyint] NULL,
[Tariff No_] [varchar] (10) NULL,
[Task Code] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Group Code] [varchar] (10) NULL,
[Tax Liable] [tinyint] NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Type] [int] NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Use Duplication List] [tinyint] NULL,
[Use Tax] [tinyint] NULL,
[VAT %] [decimal] (38, 20) NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Work Center No_] [varchar] (20) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Line_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purch_ Inv_ Line_IsDuplicate] DEFAULT ((0)),
[Allow Invoice Disc_] [tinyint] NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Area] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Bin Code] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Document No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Insurance No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Item Category Code] [varchar] (10) NULL,
[Job No_] [varchar] (20) NULL,
[Line Amount] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Line No_] [int] NULL,
[Location Code] [varchar] (10) NULL,
[Maintenance Code] [varchar] (10) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[No_] [varchar] (20) NULL,
[No_ of Palet] [decimal] (38, 20) NULL,
[Nonstock] [tinyint] NULL,
[Operation No_] [varchar] (10) NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Palet Type] [varchar] (250) NULL,
[Palet Weight] [decimal] (38, 20) NULL,
[Phase Code] [varchar] (10) NULL,
[Posting Group] [varchar] (10) NULL,
[Prod_ Order Line No_] [int] NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Product Group Code] [varchar] (10) NULL,
[Purchasing Code] [varchar] (10) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Routing Reference No_] [int] NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Step Code] [varchar] (10) NULL,
[System-Created Entry] [tinyint] NULL,
[Task Code] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Group Code] [varchar] (10) NULL,
[Tax Liable] [tinyint] NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Type] [int] NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Use Duplication List] [tinyint] NULL,
[Use Tax] [tinyint] NULL,
[VAT %] [decimal] (38, 20) NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Work Center No_] [varchar] (20) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Purchase Line Discount]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Purchase Line Discount]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Line Discount_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Line Discount_IsDuplicate] DEFAULT ((0)),
[Currency Code] [varchar] (10) NULL,
[Ending Date] [datetime] NULL,
[Item No_] [varchar] (20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Starting Date] [datetime] NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Vendor No_] [varchar] (20) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Price]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Price]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Price_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchase Price_IsDuplicate] DEFAULT ((0)),
[Currency Code] [varchar] (10) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Ending Date] [datetime] NULL,
[Item No_] [varchar] (20) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Starting Date] [datetime] NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Vendor No_] [varchar] (20) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Purchases&PayablesSetup]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Purchases&PayablesSetup]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchases & Payables Setup_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Purchases & Payables Setup_IsDuplicate] DEFAULT ((0)),
[Allow VAT Difference] [tinyint] NULL,
[Appln_ between Currencies] [int] NULL,
[Blanket Order Nos_] [varchar] (10) NULL,
[Calc_ Inv_ Disc_ per VAT ID] [tinyint] NULL,
[Calc_ Inv_ Discount] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Cr_ Memo] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Ret_Shpt] [tinyint] NULL,
[Copy Comments Blanket to Order] [tinyint] NULL,
[Copy Comments Order to Invoice] [tinyint] NULL,
[Copy Comments Order to Receipt] [tinyint] NULL,
[Credit Memo Nos_] [varchar] (10) NULL,
[Custom Invoice No_ Mandatory] [tinyint] NULL,
[Discount Posting] [int] NULL,
[Exact Cost Reversing Mandatory] [tinyint] NULL,
[Ext_ Doc_ No_ Mandatory] [tinyint] NULL,
[Invoice Nos_] [varchar] (10) NULL,
[Invoice Rounding] [tinyint] NULL,
[Order Nos_] [varchar] (10) NULL,
[Posted Credit Memo Nos_] [varchar] (10) NULL,
[Posted Invoice Nos_] [varchar] (10) NULL,
[Posted Receipt Nos_] [varchar] (10) NULL,
[Posted Return Shpt_ Nos_] [varchar] (10) NULL,
[Posted Self-Invoice Nos_] [varchar] (10) NULL,
[Posting Desc_ Code] [varchar] (10) NULL,
[Primary Key] [varchar] (10) NULL,
[Quote Nos_] [varchar] (10) NULL,
[Receipt on Invoice] [tinyint] NULL,
[Return Order Nos_] [varchar] (10) NULL,
[Return Shipment on Credit Memo] [tinyint] NULL,
[Vendor Nos_] [varchar] (10) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Salesperson_Purchaser]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Salesperson_Purchaser]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_IsDuplicate] DEFAULT ((0)),
[Code] [varchar] (10) NULL,
[Commission %] [decimal] (38, 20) NULL,
[E-Mail] [varchar] (80) NULL,
[Empty SalesPerson_Purch Code] [tinyint] NULL,
[Enable Synchronization] [tinyint] NULL,
[Global Dimension 1 Code] [varchar] (20) NULL,
[Global Dimension 2 Code] [varchar] (20) NULL,
[Job Title] [varchar] (30) NULL,
[Name] [varchar] (50) NULL,
[Navision User ID] [varchar] (20) NULL,
[Notify about Appmt_ Changes] [tinyint] NULL,
[Notify about Contact Changes] [tinyint] NULL,
[Notify about Task Changes] [tinyint] NULL,
[Notify about Team To-do Chgs_] [tinyint] NULL,
[Outlook Calendar Folder Path] [varchar] (250) NULL,
[Outlook Calendar FolderID] [image] NULL,
[Outlook Calendar StoreID] [image] NULL,
[Outlook Contacts Folder Path] [varchar] (250) NULL,
[Outlook Contacts FolderID] [image] NULL,
[Outlook Contacts StoreID] [image] NULL,
[Outlook Profile Name] [varchar] (80) NULL,
[Outlook Tasks Folder Path] [varchar] (250) NULL,
[Outlook Tasks FolderID] [image] NULL,
[Outlook Tasks StoreID] [image] NULL,
[Outlook User Name] [varchar] (80) NULL,
[Phone No_] [varchar] (30) NULL,
[Search E-Mail] [varchar] (80) NULL,
[Synchronize From] [varchar] (32) NULL,
[Synchronize To] [varchar] (32) NULL,
[Synchronize To-dos] [int] NULL,
[Version No_] [int] NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Standard Purchase Code]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Standard Purchase Code]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Standard Purchase Code_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Standard Purchase Code_IsDuplicate] DEFAULT ((0)),
[Code] [varchar] (10) NULL,
[Currency Code] [varchar] (10) NULL,
[Description] [varchar] (50) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Standard Purchase Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_Rom_Live Icopal Romania$Standard Purchase Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Standard Purchase Line_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_Rom_Live Icopal Romania1812$Standard Purchase Line_IsDuplicate] DEFAULT ((0)),
[Amount Excl_ VAT] [decimal] (38, 20) NULL,
[Description] [varchar] (50) NULL,
[Line No_] [int] NULL,
[No_] [varchar] (20) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Standard Purchase Code] [varchar] (10) NULL,
[Type] [int] NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Header]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Header_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Header_IsDuplicate] DEFAULT ((0)),
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Area] [varchar] (10) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Bal_ Account Type] [int] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[Buy-from Address] [varchar] (50) NULL,
[Buy-from Address 2] [varchar] (50) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (50) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Buy-from Country_Region Code] [varchar] (10) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from Vendor Name] [varchar] (50) NULL,
[Buy-from Vendor Name 2] [varchar] (50) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Campaign No_] [varchar] (20) NULL,
[Composed By] [varchar] (30) NULL,
[Correction] [tinyint] NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Customs Declaration No_] [varchar] (10) NULL,
[Date Received] [datetime] NULL,
[Debit Memo] [tinyint] NULL,
[Do not include in VAT Ledgers] [tinyint] NULL,
[Document Date] [datetime] NULL,
[Due Date] [datetime] NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Identification No_] [varchar] (13) NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Language Code] [varchar] (10) NULL,
[Location Code] [varchar] (10) NULL,
[No_] [varchar] (20) NULL,
[No_ Printed] [int] NULL,
[No_ Series] [varchar] (10) NULL,
[On Hold] [varchar] (3) NULL,
[Order Address Code] [varchar] (10) NULL,
[Order Date] [datetime] NULL,
[Order No_] [varchar] (20) NULL,
[Order No_ Series] [varchar] (10) NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Payment Method Code] [varchar] (10) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Pay-to Address] [varchar] (50) NULL,
[Pay-to Address 2] [varchar] (50) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (50) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Pay-to Country_Region Code] [varchar] (10) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to Name] [varchar] (50) NULL,
[Pay-to Name 2] [varchar] (50) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Posting Description] [varchar] (50) NULL,
[Pre-Assigned No_] [varchar] (20) NULL,
[Pre-Assigned No_ Series] [varchar] (10) NULL,
[Prepayment Invoice] [tinyint] NULL,
[Prepayment No_ Series] [varchar] (10) NULL,
[Prepayment Order No_] [varchar] (20) NULL,
[Prices Including VAT] [tinyint] NULL,
[Purchaser Code] [varchar] (10) NULL,
[Quote No_] [varchar] (20) NULL,
[Reason Code] [varchar] (10) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Sales Protocol] [tinyint] NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Ship-to Address] [varchar] (50) NULL,
[Ship-to Address 2] [varchar] (50) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Contact] [varchar] (50) NULL,
[Ship-to Country_Region Code] [varchar] (10) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Name] [varchar] (50) NULL,
[Ship-to Name 2] [varchar] (50) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Source Code] [varchar] (10) NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Time Received] [datetime] NULL,
[timestamp] [varbinary] (max) NULL,
[To Invoice Date] [datetime] NULL,
[To Invoice No_] [varchar] (20) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Unrealized VAT] [tinyint] NULL,
[User ID] [varchar] (20) NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Country_Region Code] [varchar] (10) NULL,
[VAT Exempt Ground] [varchar] (10) NULL,
[VAT Protocol] [tinyint] NULL,
[VAT Registration No_] [varchar] (20) NULL,
[VAT Settlement Date] [datetime] NULL,
[VAT Subject] [varchar] (30) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Void] [tinyint] NULL,
[Void Date] [datetime] NULL,
[Your Reference] [varchar] (30) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Line_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purch_ Inv_ Line_IsDuplicate] DEFAULT ((0)),
[Allow Invoice Disc_] [tinyint] NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Area] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Bin Code] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Document No_] [varchar] (20) NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[IC Partner Code] [varchar] (20) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Insurance No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Item Category Code] [varchar] (10) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Type] [int] NULL,
[Job No_] [varchar] (20) NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Line Amount] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Line No_] [int] NULL,
[Location Code] [varchar] (10) NULL,
[Maintenance Code] [varchar] (10) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[No_] [varchar] (20) NULL,
[Nonstock] [tinyint] NULL,
[Operation No_] [varchar] (10) NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Posting Date] [datetime] NULL,
[Posting Group] [varchar] (10) NULL,
[Prepayment Line] [tinyint] NULL,
[Prod_ Order Line No_] [int] NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Product Group Code] [varchar] (10) NULL,
[Purchasing Code] [varchar] (10) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Routing Reference No_] [int] NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[System-Created Entry] [tinyint] NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Group Code] [varchar] (10) NULL,
[Tax Liable] [tinyint] NULL,
[timestamp] [varbinary] (max) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Type] [int] NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Use Duplication List] [tinyint] NULL,
[Use Tax] [tinyint] NULL,
[Variant Code] [varchar] (10) NULL,
[VAT %] [decimal] (38, 20) NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Work Center No_] [varchar] (20) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Header]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Header]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Header_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Header_IsDuplicate] DEFAULT ((0)),
[Applies-to Doc_ No_] [varchar] (20) NULL,
[Applies-to Doc_ Type] [int] NULL,
[Applies-to ID] [varchar] (20) NULL,
[Area] [varchar] (10) NULL,
[Assigned User ID] [varchar] (20) NULL,
[Bal_ Account No_] [varchar] (20) NULL,
[Bal_ Account Type] [int] NULL,
[BizTalk Document Sent] [tinyint] NULL,
[BizTalk Purch_ Order Cnfmn_] [tinyint] NULL,
[BizTalk Purchase Credit Memo] [tinyint] NULL,
[BizTalk Purchase Invoice] [tinyint] NULL,
[BizTalk Purchase Order] [tinyint] NULL,
[BizTalk Purchase Quote] [tinyint] NULL,
[BizTalk Purchase Receipt] [tinyint] NULL,
[BizTalk Request for Purch_ Qte] [tinyint] NULL,
[Buy-from Address] [varchar] (50) NULL,
[Buy-from Address 2] [varchar] (50) NULL,
[Buy-from City] [varchar] (30) NULL,
[Buy-from Contact] [varchar] (50) NULL,
[Buy-from Contact No_] [varchar] (20) NULL,
[Buy-from Country_Region Code] [varchar] (10) NULL,
[Buy-from County] [varchar] (30) NULL,
[Buy-from IC Partner Code] [varchar] (20) NULL,
[Buy-from Post Code] [varchar] (20) NULL,
[Buy-from Vendor Name] [varchar] (50) NULL,
[Buy-from Vendor Name 2] [varchar] (50) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Campaign No_] [varchar] (20) NULL,
[Composed By] [varchar] (30) NULL,
[Compress Prepayment] [tinyint] NULL,
[Correction] [tinyint] NULL,
[Currency Code] [varchar] (10) NULL,
[Currency Factor] [decimal] (38, 20) NULL,
[Customs Declaration No_] [varchar] (30) NULL,
[Date Received] [datetime] NULL,
[Date Sent] [datetime] NULL,
[Debit Memo] [tinyint] NULL,
[Do not include in VAT Ledgers] [tinyint] NULL,
[Doc_ No_ Occurrence] [int] NULL,
[Document Date] [datetime] NULL,
[Document Type] [int] NULL,
[Due Date] [datetime] NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[IC Direction] [int] NULL,
[IC Status] [int] NULL,
[Identification No_] [varchar] (13) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Invoice] [tinyint] NULL,
[Invoice Disc_ Code] [varchar] (20) NULL,
[Invoice Discount Calculation] [int] NULL,
[Invoice Discount Value] [decimal] (38, 20) NULL,
[Language Code] [varchar] (10) NULL,
[Last Posting No_] [varchar] (20) NULL,
[Last Prepayment No_] [varchar] (20) NULL,
[Last Prepmt_ Cr_ Memo No_] [varchar] (20) NULL,
[Last Receiving No_] [varchar] (20) NULL,
[Last Return Shipment No_] [varchar] (20) NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Location Code] [varchar] (10) NULL,
[No_] [varchar] (20) NULL,
[No_ Printed] [int] NULL,
[No_ Series] [varchar] (10) NULL,
[On Hold] [varchar] (3) NULL,
[Order Address Code] [varchar] (10) NULL,
[Order Class] [varchar] (10) NULL,
[Order Date] [datetime] NULL,
[Payment Discount %] [decimal] (38, 20) NULL,
[Payment Method Code] [varchar] (10) NULL,
[Payment Terms Code] [varchar] (10) NULL,
[Pay-to Address] [varchar] (50) NULL,
[Pay-to Address 2] [varchar] (50) NULL,
[Pay-to City] [varchar] (30) NULL,
[Pay-to Contact] [varchar] (50) NULL,
[Pay-to Contact No_] [varchar] (20) NULL,
[Pay-to Country_Region Code] [varchar] (10) NULL,
[Pay-to County] [varchar] (30) NULL,
[Pay-to IC Partner Code] [varchar] (20) NULL,
[Pay-to Name] [varchar] (50) NULL,
[Pay-to Name 2] [varchar] (50) NULL,
[Pay-to Post Code] [varchar] (20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Pmt_ Discount Date] [datetime] NULL,
[Posting Date] [datetime] NULL,
[Posting Description] [varchar] (50) NULL,
[Posting from Whse_ Ref_] [int] NULL,
[Posting No_] [varchar] (20) NULL,
[Posting No_ Series] [varchar] (10) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Prepayment Due Date] [datetime] NULL,
[Prepayment No_] [varchar] (20) NULL,
[Prepayment No_ Series] [varchar] (10) NULL,
[Prepmt_ Cr_ Memo No_] [varchar] (20) NULL,
[Prepmt_ Cr_ Memo No_ Series] [varchar] (10) NULL,
[Prepmt_ Payment Discount %] [decimal] (38, 20) NULL,
[Prepmt_ Payment Terms Code] [varchar] (10) NULL,
[Prepmt_ Pmt_ Discount Date] [datetime] NULL,
[Prepmt_ Posting Description] [varchar] (50) NULL,
[Prices Including VAT] [tinyint] NULL,
[Promised Receipt Date] [datetime] NULL,
[Purchaser Code] [varchar] (10) NULL,
[Quote No_] [varchar] (20) NULL,
[Reason Code] [varchar] (10) NULL,
[Receive] [tinyint] NULL,
[Receiving No_] [varchar] (20) NULL,
[Receiving No_ Series] [varchar] (10) NULL,
[Requested Receipt Date] [datetime] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shipment No_ Series] [varchar] (10) NULL,
[Sales Protocol] [tinyint] NULL,
[Sell-to Customer No_] [varchar] (20) NULL,
[Send IC Document] [tinyint] NULL,
[Ship] [tinyint] NULL,
[Shipment Method Code] [varchar] (10) NULL,
[Ship-to Address] [varchar] (50) NULL,
[Ship-to Address 2] [varchar] (50) NULL,
[Ship-to City] [varchar] (30) NULL,
[Ship-to Code] [varchar] (10) NULL,
[Ship-to Contact] [varchar] (50) NULL,
[Ship-to Country_Region Code] [varchar] (10) NULL,
[Ship-to County] [varchar] (30) NULL,
[Ship-to Name] [varchar] (50) NULL,
[Ship-to Name 2] [varchar] (50) NULL,
[Ship-to Post Code] [varchar] (20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Speditor] [varchar] (10) NULL,
[Status] [int] NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Liable] [tinyint] NULL,
[Time Received] [datetime] NULL,
[Time Sent] [datetime] NULL,
[timestamp] [varbinary] (max) NULL,
[To Invoice Date] [datetime] NULL,
[To Invoice No_] [varchar] (20) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Country_Region Code] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Unrealized VAT] [tinyint] NULL,
[VAT Base Discount %] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Country_Region Code] [varchar] (10) NULL,
[VAT Exempt Ground] [varchar] (10) NULL,
[VAT Registration No_] [varchar] (20) NULL,
[VAT Settlement Date] [datetime] NULL,
[VAT Subject] [varchar] (30) NULL,
[Vendor Authorization No_] [varchar] (20) NULL,
[Vendor Cr_ Memo No_] [varchar] (20) NULL,
[Vendor Invoice No_] [varchar] (20) NULL,
[Vendor Order No_] [varchar] (20) NULL,
[Vendor Posting Group] [varchar] (10) NULL,
[Vendor Quote No_] [varchar] (20) NULL,
[Vendor Shipment No_] [varchar] (20) NULL,
[Void] [tinyint] NULL,
[Void Date] [datetime] NULL,
[Your Reference] [varchar] (30) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line_IsDuplicate] DEFAULT ((0)),
[Allow Invoice Disc_] [tinyint] NULL,
[Allow Item Charge Assignment] [tinyint] NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Amt_ Rcd_ Not Invoiced (LCY)] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Area] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Bin Code] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Completely Received] [tinyint] NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Currency Code] [varchar] (10) NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Document No_] [varchar] (20) NULL,
[Document Type] [int] NULL,
[Drop Shipment] [tinyint] NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Finished] [tinyint] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[IC Partner Code] [varchar] (20) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Inbound Whse_ Handling Time] [varchar] (32) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Insurance No_] [varchar] (20) NULL,
[Inv_ Disc_ Amount to Invoice] [decimal] (38, 20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Item Category Code] [varchar] (10) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Type] [int] NULL,
[Job No_] [varchar] (20) NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Lead Time Calculation] [varchar] (32) NULL,
[Line Amount] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Line No_] [int] NULL,
[Location Code] [varchar] (10) NULL,
[Maintenance Code] [varchar] (10) NULL,
[MPS Order] [tinyint] NULL,
[Net Weight] [decimal] (38, 20) NULL,
[No_] [varchar] (20) NULL,
[Nonstock] [tinyint] NULL,
[Operation No_] [varchar] (10) NULL,
[Order Date] [datetime] NULL,
[Outstanding Amount] [decimal] (38, 20) NULL,
[Outstanding Amount (LCY)] [decimal] (38, 20) NULL,
[Outstanding Qty_ (Base)] [decimal] (38, 20) NULL,
[Outstanding Quantity] [decimal] (38, 20) NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Planned Receipt Date] [datetime] NULL,
[Planning Flexibility] [int] NULL,
[Posting Group] [varchar] (10) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Prepayment Amount] [decimal] (38, 20) NULL,
[Prepayment Line] [tinyint] NULL,
[Prepayment Tax Area Code] [varchar] (20) NULL,
[Prepayment Tax Group Code] [varchar] (10) NULL,
[Prepayment Tax Liable] [tinyint] NULL,
[Prepayment VAT %] [decimal] (38, 20) NULL,
[Prepayment VAT Identifier] [varchar] (10) NULL,
[Prepmt Amt Deducted] [decimal] (38, 20) NULL,
[Prepmt Amt to Deduct] [decimal] (38, 20) NULL,
[Prepmt_ Amount Inv_ Incl_ VAT] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Incl_ VAT] [decimal] (38, 20) NULL,
[Prepmt_ Amt_ Inv_] [decimal] (38, 20) NULL,
[Prepmt_ Line Amount] [decimal] (38, 20) NULL,
[Prepmt_ VAT Base Amt_] [decimal] (38, 20) NULL,
[Prepmt_ VAT Calc_ Type] [int] NULL,
[Prod_ Order Line No_] [int] NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Product Group Code] [varchar] (10) NULL,
[Profit %] [decimal] (38, 20) NULL,
[Promised Receipt Date] [datetime] NULL,
[Purchasing Code] [varchar] (10) NULL,
[Qty_ Invoiced (Base)] [decimal] (38, 20) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced] [decimal] (38, 20) NULL,
[Qty_ Rcd_ Not Invoiced (Base)] [decimal] (38, 20) NULL,
[Qty_ Received (Base)] [decimal] (38, 20) NULL,
[Qty_ to Invoice] [decimal] (38, 20) NULL,
[Qty_ to Invoice (Base)] [decimal] (38, 20) NULL,
[Qty_ to Receive] [decimal] (38, 20) NULL,
[Qty_ to Receive (Base)] [decimal] (38, 20) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Quantity Invoiced] [decimal] (38, 20) NULL,
[Quantity Received] [decimal] (38, 20) NULL,
[Receipt Line No_] [int] NULL,
[Receipt No_] [varchar] (20) NULL,
[Requested Receipt Date] [datetime] NULL,
[Responsibility Center] [varchar] (10) NULL,
[Ret_ Qty_ Shpd Not Invd_(Base)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped] [decimal] (38, 20) NULL,
[Return Qty_ Shipped (Base)] [decimal] (38, 20) NULL,
[Return Qty_ Shipped Not Invd_] [decimal] (38, 20) NULL,
[Return Qty_ to Ship] [decimal] (38, 20) NULL,
[Return Qty_ to Ship (Base)] [decimal] (38, 20) NULL,
[Return Reason Code] [varchar] (10) NULL,
[Return Shipment Line No_] [int] NULL,
[Return Shipment No_] [varchar] (20) NULL,
[Return Shpd_ Not Invd_] [decimal] (38, 20) NULL,
[Return Shpd_ Not Invd_ (LCY)] [decimal] (38, 20) NULL,
[Routing No_] [varchar] (20) NULL,
[Routing Reference No_] [int] NULL,
[Safety Lead Time] [varchar] (32) NULL,
[Sales Order Line No_] [int] NULL,
[Sales Order No_] [varchar] (20) NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[Special Order] [tinyint] NULL,
[Special Order Sales Line No_] [int] NULL,
[Special Order Sales No_] [varchar] (20) NULL,
[System-Created Entry] [tinyint] NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Group Code] [varchar] (10) NULL,
[Tax Liable] [tinyint] NULL,
[timestamp] [varbinary] (max) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Type] [int] NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Use Duplication List] [tinyint] NULL,
[Use Tax] [tinyint] NULL,
[Variant Code] [varchar] (10) NULL,
[VAT %] [decimal] (38, 20) NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Work Center No_] [varchar] (20) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line Discount]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line Discount]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line Discount_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Line Discount_IsDuplicate] DEFAULT ((0)),
[Currency Code] [varchar] (10) NULL,
[Ending Date] [datetime] NULL,
[Item No_] [varchar] (20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Starting Date] [datetime] NULL,
[timestamp] [varbinary] (max) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Vendor No_] [varchar] (20) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Prepayment %]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Prepayment %]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Prepayment %_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Prepayment %_IsDuplicate] DEFAULT ((0)),
[Ending Date] [datetime] NULL,
[Item No_] [varchar] (20) NULL,
[Prepayment %] [decimal] (38, 20) NULL,
[Starting Date] [datetime] NULL,
[timestamp] [varbinary] (max) NULL,
[Vendor No_] [varchar] (20) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Price]'
GO
CREATE TABLE [tsa].[ics_land_Navision_BGR_Icopal Bulgaria$Purchase Price]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Price_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_Navision_BGR_Icopal Bulgaria$Purchase Price_IsDuplicate] DEFAULT ((0)),
[Currency Code] [varchar] (10) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Ending Date] [datetime] NULL,
[Item No_] [varchar] (20) NULL,
[Minimum Quantity] [decimal] (38, 20) NULL,
[Starting Date] [datetime] NULL,
[timestamp] [varbinary] (max) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Variant Code] [varchar] (10) NULL,
[Vendor No_] [varchar] (20) NULL
)
GO
