-- <Migration ID="0761169c-c5ea-40ac-8df4-bd9155e73cfd" />
GO

PRINT N'Creating [psa].[ics_stg_Symfonia_ARM_Customerfile]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ARM_Customerfile]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_Customerfile_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_Customerfile_IsIncomplete] DEFAULT ('N'),
[Address_1] [nvarchar] (82) NULL,
[Address_2] [varchar] (1) NULL,
[Address_3] [varchar] (1) NULL,
[City] [nvarchar] (50) NULL,
[Code] [varchar] (4) NULL,
[Country] [nvarchar] (50) NULL,
[Customer_Type] [varchar] (1) NULL,
[CustomerGroup1] [varchar] (1) NULL,
[CustomerGroup2] [varchar] (1) NULL,
[CustomerGroup3] [varchar] (1) NULL,
[CustomerGroup4] [varchar] (1) NULL,
[CustomerGroup5] [varchar] (1) NULL,
[CustomerTypeText] [varchar] (1) NULL,
[khid] [int] NULL,
[Name] [nvarchar] (150) NULL,
[SysID] [int] NULL,
[VATID] [nvarchar] (20) NULL,
[Zip_Code] [nvarchar] (10) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_SR]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_SR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SR_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idrj] [int] NULL,
[stannl] [float] NULL,
[stannlwal] [float] NULL,
[stanpl] [float] NULL,
[stanplwal] [float] NULL,
[waluta] [varchar] (3) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ARM_Items]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ARM_Items]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_Items_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_Items_IsIncomplete] DEFAULT ('N'),
[Code] [varchar] (40) NULL,
[Custom1] [varchar] (1) NULL,
[Custom2] [varchar] (1) NULL,
[GTIN] [varchar] (1) NULL,
[id] [int] NULL,
[Item_Type_Text] [varchar] (1) NULL,
[LocalDescription1] [varchar] (1) NULL,
[LocalDescription2] [varchar] (1) NULL,
[LocalMaterialGroup1] [varchar] (1) NULL,
[LocalMaterialGroup2] [varchar] (1) NULL,
[LocalMaterialGroup3] [varchar] (1) NULL,
[LocalMaterialGroup4] [varchar] (1) NULL,
[LocalMaterialGroup5] [varchar] (1) NULL,
[Name] [varchar] (100) NULL,
[SysID] [int] NULL,
[type1] [varchar] (1) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_StanyMinMax]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_StanyMinMax]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_StanyMinMax_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_StanyMinMax_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[MagazynId] [int] NULL,
[StanMax] [float] NULL,
[StanMin] [float] NULL,
[TowarId] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_CT]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_CT]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CT_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CT_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idck] [int] NULL,
[idpm] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_TC]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_TC]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TC_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TC_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[icon] [int] NULL,
[id] [int] NULL,
[kod] [varchar] (40) NULL,
[nazwa] [varchar] (100) NULL,
[powiazanie] [int] NULL,
[rodzaj] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_DT]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_DT]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DT_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DT_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idkh] [int] NULL,
[idtw] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_TX]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_TX]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TX_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TX_IsIncomplete] DEFAULT ('N'),
[flag] [smallint] NULL,
[id] [int] NULL,
[opis] [text] NULL,
[subtyp] [smallint] NULL,
[typ] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ARM_SalesInvoiceTrans]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ARM_SalesInvoiceTrans]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_SalesInvoiceTrans_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_SalesInvoiceTrans_IsIncomplete] DEFAULT ('N'),
[Bonus] [varchar] (1) NULL,
[Custom1] [varchar] (1) NULL,
[Custom2] [varchar] (1) NULL,
[DeliveryTermID] [varchar] (1) NULL,
[DeliveryTermText] [varchar] (1) NULL,
[Discount] [varchar] (1) NULL,
[FreightCost] [varchar] (1) NULL,
[id] [int] NULL,
[Idline] [int] NULL,
[InvAmount] [float] NULL,
[InvCurrAmount] [float] NULL,
[InvCurrency] [varchar] (3) NULL,
[InvDate] [datetime] NULL,
[InvLineAmountLoc] [float] NULL,
[invlinenr] [smallint] NULL,
[InvNum] [varchar] (40) NULL,
[InvoiceLineType] [varchar] (1) NULL,
[InvoiceShipTo] [varchar] (4) NULL,
[InvoiceSoldTo] [varchar] (4) NULL,
[InvUOM] [varchar] (8) NULL,
[ItemNo] [varchar] (40) NULL,
[ItemQty] [float] NULL,
[LocalCurrencyCode] [varchar] (3) NULL,
[MatCharName1] [varchar] (1) NULL,
[MatCharName2] [varchar] (1) NULL,
[MatCharName3] [varchar] (1) NULL,
[MatCharName4] [varchar] (1) NULL,
[MatCharName5] [varchar] (1) NULL,
[MatCharValue1] [varchar] (1) NULL,
[MatCharValue2] [varchar] (1) NULL,
[MatCharValue3] [varchar] (1) NULL,
[MatCharValue4] [varchar] (1) NULL,
[MatCharValue5] [varchar] (1) NULL,
[OrderLineNr] [smallint] NULL,
[OrderNr] [varchar] (80) NULL,
[PaymentTermText] [varchar] (7) NULL,
[SalesPersonId] [int] NULL,
[SalesPersonName] [nvarchar] (128) NULL,
[StatisicalQty] [float] NULL,
[StatisticalUOM] [varchar] (8) NULL,
[StdCost] [float] NULL,
[SysID] [int] NULL,
[TermOfPaymentID] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_TD]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_TD]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TD_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TD_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[charakter] [smallint] NULL,
[datarej] [smallint] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[idDokKoryg] [int] NULL,
[idDokSkojarz] [int] NULL,
[idDokZal] [int] NULL,
[idDokZalKon] [int] NULL,
[idRejestr] [int] NULL,
[idRejestrNaliczony] [int] NULL,
[idRejestrNP] [int] NULL,
[idRejestrOO] [int] NULL,
[idSchematKs] [int] NULL,
[idSeriaKoryg] [int] NULL,
[idSeriaSkojarz] [int] NULL,
[idSeriaZal] [int] NULL,
[idSeriaZalKon] [int] NULL,
[jednostka] [smallint] NULL,
[jpkRodzaj] [smallint] NULL,
[kod] [varchar] (40) NULL,
[nazwa] [varchar] (100) NULL,
[opis] [varchar] (100) NULL,
[symbolFK] [varchar] (4) NULL,
[terminRozl] [smallint] NULL,
[typ] [smallint] NULL,
[typFK] [varchar] (4) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ARM_ShipNotInvoiced]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ARM_ShipNotInvoiced]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_ShipNotInvoiced_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_ShipNotInvoiced_IsIncomplete] DEFAULT ('N'),
[AmountLocal] [float] NULL,
[Bonus] [varchar] (1) NULL,
[ExpectedInvDate] [datetime] NULL,
[id] [int] NULL,
[InvoiceLineType] [varchar] (1) NULL,
[InvoiceShipTo] [varchar] (4) NULL,
[InvoiceSoldTo] [varchar] (4) NULL,
[ItemNo] [varchar] (40) NULL,
[ItemQty] [float] NULL,
[ItemUOM] [varchar] (8) NULL,
[LineBonus] [varchar] (1) NULL,
[lineid] [int] NULL,
[LocalCurrency] [varchar] (3) NULL,
[OrderCurrency] [varchar] (3) NULL,
[OrderLineAmount] [float] NULL,
[OrderLineNr] [smallint] NULL,
[OrderNr] [varchar] (80) NULL,
[SalesCompanyId] [int] NULL,
[SalesPersonId] [int] NULL,
[SalesPersonName] [nvarchar] (128) NULL,
[ShippingDokNr] [varchar] (40) NULL,
[StatItemQty] [float] NULL,
[StatItemUOM] [varchar] (8) NULL,
[SysId] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_TR]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_TR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TR_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[datarozl] [datetime] NULL,
[dzial] [int] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[id_komu] [int] NULL,
[id_kto] [int] NULL,
[kod] [varchar] (40) NULL,
[nrozl_oper] [int] NULL,
[nrozlilosc] [int] NULL,
[ok] [smallint] NULL,
[owner_base] [int] NULL,
[owner_id] [int] NULL,
[status] [smallint] NULL,
[subtyp] [smallint] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL,
[wartosc_rozl] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_EP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_EP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_EP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_EP_IsIncomplete] DEFAULT ('N'),
[guid] [uniqueidentifier] NULL,
[id] [int] NULL,
[kurs] [float] NULL,
[podmiot] [int] NULL,
[typ] [smallint] NULL,
[zobowiazanie] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ZE]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ZE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZE_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idKh] [int] NULL,
[idTw] [int] NULL,
[idZn] [int] NULL,
[ilosc] [float] NULL,
[lp] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_CK]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_CK]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CK_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CK_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[cenowy] [smallint] NULL,
[cykliczny] [smallint] NULL,
[czw] [bit] NULL,
[datado] [datetime] NULL,
[dataod] [datetime] NULL,
[dzial] [int] NULL,
[id] [int] NULL,
[kod] [varchar] (40) NULL,
[kontrah] [smallint] NULL,
[laczony] [smallint] NULL,
[nd] [bit] NULL,
[numer] [smallint] NULL,
[numerlacz] [smallint] NULL,
[opis] [varchar] (80) NULL,
[pon] [bit] NULL,
[pt] [bit] NULL,
[sb] [bit] NULL,
[sr] [bit] NULL,
[wt] [bit] NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ZN]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ZN]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZN_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZN_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[dzial] [int] NULL,
[id] [int] NULL,
[idUser] [int] NULL,
[opcje] [smallint] NULL,
[opis] [varchar] (100) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_CN]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_CN]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CN_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CN_IsIncomplete] DEFAULT ('N'),
[aktywna] [smallint] NULL,
[cena] [float] NULL,
[createdBy] [int] NULL,
[dataend] [datetime] NULL,
[datastart] [datetime] NULL,
[flag] [smallint] NULL,
[flagcen] [smallint] NULL,
[id] [int] NULL,
[idck] [int] NULL,
[idpd] [int] NULL,
[idpm] [int] NULL,
[parametr] [float] NULL,
[subtyp] [smallint] NULL,
[typ] [smallint] NULL,
[typceny] [smallint] NULL,
[typpar] [smallint] NULL,
[typpd] [smallint] NULL,
[waluta] [varchar] (3) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_TW]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_TW]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TW_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_TW_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[flag] [smallint] NULL,
[fundusz] [int] NULL,
[id] [int] NULL,
[idlongname] [int] NULL,
[info] [smallint] NULL,
[jm] [varchar] (8) NULL,
[jmdef] [smallint] NULL,
[jmdod1] [varchar] (8) NULL,
[jmdod2] [varchar] (8) NULL,
[jmdom] [varchar] (8) NULL,
[jmuzup] [varchar] (8) NULL,
[katalog] [int] NULL,
[kod] [varchar] (40) NULL,
[kodpaskowy] [varchar] (150) NULL,
[kontofk] [varchar] (24) NULL,
[metoda] [smallint] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (100) NULL,
[nazwaFiskal] [varchar] (40) NULL,
[negoc] [smallint] NULL,
[odwrotneObc] [smallint] NULL,
[pcn] [varchar] (10) NULL,
[przelicz] [smallint] NULL,
[przelit] [smallint] NULL,
[przeljmdod1] [float] NULL,
[przeljmdod2] [float] NULL,
[przeljmdom] [float] NULL,
[przelkg] [float] NULL,
[przeluz] [float] NULL,
[rodzaj] [int] NULL,
[stanmax] [float] NULL,
[stanmin] [float] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[sww] [varchar] (20) NULL,
[szablon] [varchar] (40) NULL,
[typ] [smallint] NULL,
[typks] [varchar] (40) NULL,
[vat50] [smallint] NULL,
[vatsp] [int] NULL,
[zaokrag] [smallint] NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_DK]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_DK]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DK_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DK_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[bufor] [smallint] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[data_obcy] [datetime] NULL,
[datarej] [datetime] NULL,
[datarej2] [datetime] NULL,
[datasp] [datetime] NULL,
[datawplywu] [datetime] NULL,
[dataZest1] [datetime] NULL,
[eFaktura] [smallint] NULL,
[exp_fk] [smallint] NULL,
[flag] [smallint] NULL,
[formaplatn] [int] NULL,
[grupacen] [smallint] NULL,
[guid] [uniqueidentifier] NULL,
[id] [int] NULL,
[iddokkoryg] [int] NULL,
[info] [smallint] NULL,
[jpk] [smallint] NULL,
[katalog] [int] NULL,
[khadid] [int] NULL,
[khid] [int] NULL,
[kod] [varchar] (40) NULL,
[kod_obcy] [varchar] (40) NULL,
[koszt] [float] NULL,
[kosztAproksymowany] [float] NULL,
[kurs] [float] NULL,
[kursDoch] [float] NULL,
[magazyn] [int] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (40) NULL,
[netto] [float] NULL,
[odadid] [int] NULL,
[odebrane] [varchar] (40) NULL,
[odid] [int] NULL,
[ok] [smallint] NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[paragon] [int] NULL,
[plattermin] [datetime] NULL,
[plattyp] [int] NULL,
[rabat] [float] NULL,
[rejestrVat] [int] NULL,
[rejestrVat2] [int] NULL,
[rodzaj] [int] NULL,
[rozlmg] [smallint] NULL,
[rr] [smallint] NULL,
[schemat] [varchar] (4) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[statusFK] [smallint] NULL,
[statusRDF] [smallint] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[typ] [smallint] NULL,
[typ_dk] [varchar] (4) NULL,
[typceny] [int] NULL,
[vat] [float] NULL,
[walBrutto] [float] NULL,
[walNetto] [float] NULL,
[waluta] [varchar] (3) NULL,
[wartoscSp] [float] NULL,
[wartPrzychod] [float] NULL,
[wplaty] [float] NULL,
[wystawil] [int] NULL,
[znacznik] [smallint] NULL,
[zyskdod] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_UR]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_UR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_UR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_UR_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[bkonto] [varchar] (50) NULL,
[bnazwa] [varchar] (100) NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[dom] [varchar] (15) NULL,
[email] [varchar] (50) NULL,
[fax] [varchar] (25) NULL,
[flag] [smallint] NULL,
[formaplatn] [int] NULL,
[grupacen] [smallint] NULL,
[id] [int] NULL,
[idfk] [int] NULL,
[idfk2] [int] NULL,
[idKraju] [int] NULL,
[idTX] [int] NULL,
[imie] [varchar] (14) NULL,
[info] [smallint] NULL,
[katalog] [int] NULL,
[khfk] [varchar] (24) NULL,
[kod] [varchar] (40) NULL,
[kodpocz] [varchar] (10) NULL,
[limit] [smallint] NULL,
[limitkwota] [float] NULL,
[limitwaluta] [varchar] (3) NULL,
[lokal] [varchar] (15) NULL,
[miejscowosc] [varchar] (50) NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[naglowek] [varchar] (19) NULL,
[nazwa] [varchar] (150) NULL,
[nazwisko] [varchar] (24) NULL,
[negoc] [smallint] NULL,
[nip] [varchar] (20) NULL,
[plattermin] [smallint] NULL,
[plattyp] [int] NULL,
[regon] [varchar] (20) NULL,
[rejon] [varchar] (25) NULL,
[rodzaj] [int] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[tel1] [varchar] (25) NULL,
[tel2] [varchar] (25) NULL,
[typ] [smallint] NULL,
[typks] [varchar] (40) NULL,
[ulica] [varchar] (50) NULL,
[upust] [float] NULL,
[www] [varchar] (100) NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_DP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_DP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DP_IsIncomplete] DEFAULT ('N'),
[bufor] [smallint] NULL,
[cena] [float] NULL,
[cenaBaza] [float] NULL,
[cenaBazaPl] [float] NULL,
[cenabaztow] [float] NULL,
[cenawal] [float] NULL,
[data] [datetime] NULL,
[flag] [smallint] NULL,
[grupacen] [smallint] NULL,
[id] [int] NULL,
[idkh] [int] NULL,
[idlongname] [int] NULL,
[idpozkoryg] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[iloscjedn] [float] NULL,
[iloscRLKS] [float] NULL,
[iloscwp] [float] NULL,
[jm] [varchar] (8) NULL,
[jmwp] [varchar] (8) NULL,
[kod] [varchar] (40) NULL,
[kompensata] [smallint] NULL,
[koszt] [float] NULL,
[kosztAproksymowany] [float] NULL,
[lp] [smallint] NULL,
[magazyn] [int] NULL,
[odwrotneObc] [smallint] NULL,
[opis] [varchar] (40) NULL,
[opisdod] [varchar] (20) NULL,
[rejestrVAT] [int] NULL,
[rejestrVAT2] [int] NULL,
[schemat] [varchar] (4) NULL,
[stvat] [int] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[superkoryg] [int] NULL,
[typ] [smallint] NULL,
[typceny] [int] NULL,
[vat50] [smallint] NULL,
[walBrutto] [float] NULL,
[walcenybaz] [varchar] (3) NULL,
[walNetto] [float] NULL,
[waluta] [varchar] (3) NULL,
[wartNetto] [float] NULL,
[wartPrzychod] [float] NULL,
[wartstvat] [smallint] NULL,
[wartTowaru] [float] NULL,
[wartVat] [float] NULL,
[zyskdod] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_UZ]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_UZ]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_UZ_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_UZ_IsIncomplete] DEFAULT ('N'),
[bazauz] [smallint] NULL,
[cena] [float] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[idkh] [int] NULL,
[idobcy] [int] NULL,
[iduz] [int] NULL,
[kodobcy] [varchar] (40) NULL,
[subtyp] [smallint] NULL,
[typ] [smallint] NULL,
[waluta] [varchar] (3) NULL,
[wart] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_DW]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_DW]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DW_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_DW_IsIncomplete] DEFAULT ('N'),
[bufor] [int] NULL,
[cena] [float] NULL,
[data] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[iddkpz] [int] NULL,
[iddkzk] [int] NULL,
[iddw] [int] NULL,
[idkh] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[iloscdosp] [float] NULL,
[iloscPz] [float] NULL,
[kod] [varchar] (40) NULL,
[magazyn] [int] NULL,
[numer] [int] NULL,
[stan] [float] NULL,
[subtyp] [smallint] NULL,
[typ] [smallint] NULL,
[wartoscdosp] [float] NULL,
[wartoscst] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_WD]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_WD]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_WD_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_WD_IsIncomplete] DEFAULT ('N'),
[cena] [float] NULL,
[dzial] [varchar] (40) NULL,
[flag] [smallint] NULL,
[guid_obcy] [uniqueidentifier] NULL,
[id] [int] NULL,
[id_obcy] [int] NULL,
[id_wlasny] [int] NULL,
[idkh] [int] NULL,
[idkhfk] [int] NULL,
[ilosc] [float] NULL,
[kodkh] [varchar] (40) NULL,
[kodtw] [varchar] (40) NULL,
[opis] [varchar] (100) NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ErrorLog]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ErrorLog]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ErrorLog_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ErrorLog_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[errno] [int] NULL,
[id] [int] NULL,
[opis] [varchar] (2000) NULL,
[super] [int] NULL,
[typ] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_WR]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_WR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_WR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_WR_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[bkonto] [varchar] (50) NULL,
[bnazwa] [varchar] (100) NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[dom] [varchar] (15) NULL,
[email] [varchar] (50) NULL,
[fax] [varchar] (25) NULL,
[flag] [smallint] NULL,
[formaplatn] [int] NULL,
[grupacen] [smallint] NULL,
[id] [int] NULL,
[idfk] [int] NULL,
[idfk2] [int] NULL,
[idKraju] [int] NULL,
[idTX] [int] NULL,
[imie] [varchar] (14) NULL,
[info] [smallint] NULL,
[katalog] [int] NULL,
[khfk] [varchar] (24) NULL,
[kod] [varchar] (40) NULL,
[kodpocz] [varchar] (10) NULL,
[limit] [smallint] NULL,
[limitkwota] [float] NULL,
[limitwaluta] [varchar] (3) NULL,
[lokal] [varchar] (15) NULL,
[miejscowosc] [varchar] (50) NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[naglowek] [varchar] (19) NULL,
[nazwa] [varchar] (150) NULL,
[nazwisko] [varchar] (24) NULL,
[negoc] [smallint] NULL,
[nip] [varchar] (20) NULL,
[plattermin] [smallint] NULL,
[plattyp] [int] NULL,
[regon] [varchar] (20) NULL,
[rejon] [varchar] (25) NULL,
[rodzaj] [int] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[tel1] [varchar] (25) NULL,
[tel2] [varchar] (25) NULL,
[typ] [smallint] NULL,
[typks] [varchar] (40) NULL,
[ulica] [varchar] (50) NULL,
[upust] [float] NULL,
[www] [varchar] (100) NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_FP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_FP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_FP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_FP_IsIncomplete] DEFAULT ('N'),
[fundusz] [int] NULL,
[id] [int] NULL,
[idDk] [int] NULL,
[wartNetto] [float] NULL,
[wplata] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ZR]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ZR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZR_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idtw] [int] NULL,
[idzl] [int] NULL,
[ilosc] [float] NULL,
[wartosc] [float] NULL,
[wspolczynnik] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_EK]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_EK]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_EK_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_EK_IsIncomplete] DEFAULT ('N'),
[flag] [smallint] NULL,
[id] [int] NULL,
[idEKwzor] [int] NULL,
[idSK] [int] NULL,
[kod] [varchar] (40) NULL,
[kwota] [smallint] NULL,
[mnoznik] [float] NULL,
[nazwa] [varchar] (100) NULL,
[nr_poz] [smallint] NULL,
[szablon] [varchar] (40) NULL,
[wymiar01] [varchar] (40) NULL,
[wymiar02] [varchar] (40) NULL,
[wymiar03] [varchar] (40) NULL,
[wymiar04] [varchar] (40) NULL,
[wymiar05] [varchar] (40) NULL,
[wymiar06] [varchar] (40) NULL,
[wymiar07] [varchar] (40) NULL,
[wymiar08] [varchar] (40) NULL,
[wymiar09] [varchar] (40) NULL,
[wymiar10] [varchar] (40) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_XT]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_XT]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_XT_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_XT_IsIncomplete] DEFAULT ('N'),
[baza] [smallint] NULL,
[data1] [datetime] NULL,
[data2] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[klient] [int] NULL,
[kod] [varchar] (40) NULL,
[long] [int] NULL,
[long2] [int] NULL,
[nazwa] [varchar] (100) NULL,
[podkatalog] [smallint] NULL,
[root] [int] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL,
[zawartosc] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_HW]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_HW]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_HW_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_HW_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[iddk] [int] NULL,
[typdk] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ZL]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ZL]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZL_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZL_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[cena] [float] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[data_real] [datetime] NULL,
[data_status] [datetime] NULL,
[dzial] [int] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[idkh] [int] NULL,
[idrn] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[iloscGotowa] [float] NULL,
[katalog] [int] NULL,
[kod] [varchar] (40) NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (40) NULL,
[okres] [smallint] NULL,
[opis] [varchar] (100) NULL,
[rodzaj] [int] NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[status] [smallint] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[typ] [smallint] NULL,
[typ_dk] [varchar] (4) NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_IL]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_IL]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_IL_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_IL_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[data_stan0] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[magazyn] [int] NULL,
[nazwa] [varchar] (40) NULL,
[typ] [smallint] NULL,
[wlasciwosci] [smallint] NULL,
[wystawil] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ZO]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ZO]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZO_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZO_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[bufor] [smallint] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[datarej] [datetime] NULL,
[datasp] [datetime] NULL,
[datawplywu] [datetime] NULL,
[exp_fk] [smallint] NULL,
[flag] [smallint] NULL,
[formaplatn] [int] NULL,
[grupacen] [smallint] NULL,
[guid] [uniqueidentifier] NULL,
[id] [int] NULL,
[iddokkoryg] [int] NULL,
[info] [smallint] NULL,
[katalog] [int] NULL,
[khadid] [int] NULL,
[khid] [int] NULL,
[kod] [varchar] (40) NULL,
[kod_obcy] [varchar] (40) NULL,
[kurs] [float] NULL,
[magazyn] [int] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (40) NULL,
[netto] [float] NULL,
[odadid] [int] NULL,
[odebrane] [varchar] (40) NULL,
[odid] [int] NULL,
[ok] [smallint] NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[paragon] [int] NULL,
[plattermin] [datetime] NULL,
[plattyp] [int] NULL,
[rabat] [float] NULL,
[rodzaj] [int] NULL,
[rozlmg] [smallint] NULL,
[rr] [smallint] NULL,
[schemat] [varchar] (4) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[statusRDF] [smallint] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[typ] [smallint] NULL,
[typ_dk] [varchar] (4) NULL,
[typceny] [int] NULL,
[vat] [float] NULL,
[walBrutto] [float] NULL,
[walNetto] [float] NULL,
[waluta] [varchar] (3) NULL,
[wartoscSp] [float] NULL,
[wplaty] [float] NULL,
[wystawil] [int] NULL,
[znacznik] [smallint] NULL,
[zyskdod] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_INIFILE]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_INIFILE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_INIFILE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_INIFILE_IsIncomplete] DEFAULT ('N'),
[klucz] [varchar] (100) NULL,
[napis] [varchar] (256) NULL,
[plik] [varchar] (100) NULL,
[sekcja] [varchar] (100) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ZP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ZP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZP_IsIncomplete] DEFAULT ('N'),
[bufor] [smallint] NULL,
[cena] [float] NULL,
[cenaBaza] [float] NULL,
[cenaBazaPl] [float] NULL,
[cenabaztow] [float] NULL,
[cenawal] [float] NULL,
[data] [datetime] NULL,
[flag] [smallint] NULL,
[grupacen] [smallint] NULL,
[id] [int] NULL,
[idkh] [int] NULL,
[idlongname] [int] NULL,
[idpozkoryg] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[iloscjedn] [float] NULL,
[iloscwp] [float] NULL,
[jm] [varchar] (8) NULL,
[jmwp] [varchar] (8) NULL,
[kod] [varchar] (40) NULL,
[kompensata] [smallint] NULL,
[lp] [smallint] NULL,
[magazyn] [int] NULL,
[odwrotneObc] [smallint] NULL,
[opis] [varchar] (40) NULL,
[opisdod] [varchar] (20) NULL,
[schemat] [varchar] (4) NULL,
[stvat] [int] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[superkoryg] [int] NULL,
[typ] [smallint] NULL,
[typceny] [int] NULL,
[walBrutto] [float] NULL,
[walcenybaz] [varchar] (3) NULL,
[walNetto] [float] NULL,
[waluta] [varchar] (3) NULL,
[wartNetto] [float] NULL,
[wartstvat] [smallint] NULL,
[wartTowaru] [float] NULL,
[wartVat] [float] NULL,
[zyskdod] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_KR]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_KR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_KR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_KR_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[flag] [smallint] NULL,
[formatNIP] [varchar] (100) NULL,
[formatVAT] [varchar] (100) NULL,
[id] [int] NULL,
[kod] [varchar] (40) NULL,
[nazwa] [varchar] (100) NULL,
[typ] [smallint] NULL,
[ue] [bit] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ZZ]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ZZ]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZZ_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ZZ_IsIncomplete] DEFAULT ('N'),
[baza1] [smallint] NULL,
[baza2] [smallint] NULL,
[baza3] [smallint] NULL,
[cena] [float] NULL,
[data] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[id1] [int] NULL,
[id2] [int] NULL,
[id3] [int] NULL,
[id3pos] [int] NULL,
[iddkreal] [int] NULL,
[ilosc] [float] NULL,
[ilosc2] [float] NULL,
[kod1] [varchar] (40) NULL,
[kod2] [varchar] (40) NULL,
[magazyn] [int] NULL,
[opis] [varchar] (100) NULL,
[subtyp] [smallint] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[waluta] [varchar] (3) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_IP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_IP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_IP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_IP_IsIncomplete] DEFAULT ('N'),
[cena] [float] NULL,
[dataDw] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[iddw] [int] NULL,
[idil] [int] NULL,
[idtw] [int] NULL,
[iloscjest] [float] NULL,
[iloscma] [float] NULL,
[kod_obcy] [varchar] (40) NULL,
[nazwaDw] [varchar] (40) NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_IT]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_IT]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_IT_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_IT_IsIncomplete] DEFAULT ('N'),
[dostawa] [varchar] (3) NULL,
[id] [int] NULL,
[idKrajuPo] [int] NULL,
[idKrajuWy] [int] NULL,
[idmg] [int] NULL,
[transakcja] [smallint] NULL,
[transport] [smallint] NULL,
[wartStat] [float] NULL,
[zmieniony] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_KH]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_KH]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_KH_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_KH_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[bkonto] [varchar] (50) NULL,
[bnazwa] [varchar] (100) NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[dom] [varchar] (15) NULL,
[email] [varchar] (50) NULL,
[fax] [varchar] (25) NULL,
[flag] [smallint] NULL,
[formaplatn] [int] NULL,
[grupacen] [smallint] NULL,
[id] [int] NULL,
[idfk] [int] NULL,
[idfk2] [int] NULL,
[idKraju] [int] NULL,
[idMpk] [int] NULL,
[idTX] [int] NULL,
[imie] [varchar] (14) NULL,
[info] [smallint] NULL,
[katalog] [int] NULL,
[khfk] [varchar] (24) NULL,
[kod] [varchar] (40) NULL,
[kodpocz] [varchar] (10) NULL,
[limit] [smallint] NULL,
[limitkwota] [float] NULL,
[limitwaluta] [varchar] (3) NULL,
[lokal] [varchar] (15) NULL,
[miejscowosc] [varchar] (50) NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[naglowek] [varchar] (19) NULL,
[nazwa] [varchar] (150) NULL,
[nazwisko] [varchar] (24) NULL,
[negoc] [smallint] NULL,
[nip] [varchar] (20) NULL,
[pesel] [varchar] (15) NULL,
[plattermin] [smallint] NULL,
[plattyp] [int] NULL,
[regon] [varchar] (20) NULL,
[rejon] [varchar] (25) NULL,
[rodzaj] [int] NULL,
[statusUE] [bit] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[tel1] [varchar] (25) NULL,
[tel2] [varchar] (25) NULL,
[typ] [smallint] NULL,
[typceny] [int] NULL,
[typks] [varchar] (40) NULL,
[ulica] [varchar] (50) NULL,
[upust] [float] NULL,
[www] [varchar] (100) NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_KP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_KP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_KP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_KP_IsIncomplete] DEFAULT ('N'),
[flag] [smallint] NULL,
[id] [int] NULL,
[idck] [int] NULL,
[idpd] [int] NULL,
[typpd] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_LOCAL_LOG]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_LOCAL_LOG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_LOCAL_LOG_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_LOCAL_LOG_IsIncomplete] DEFAULT ('N'),
[baseName] [varchar] (19) NULL,
[id] [int] NULL,
[operation] [smallint] NULL,
[rec_id] [int] NULL,
[term] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_LOG_BASE]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_LOG_BASE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_LOG_BASE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_LOG_BASE_IsIncomplete] DEFAULT ('N'),
[baseName] [varchar] (19) NULL,
[id] [int] NULL,
[operation] [smallint] NULL,
[rec_id] [int] NULL,
[term] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_LogKonwersji]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_LogKonwersji]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_LogKonwersji_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_LogKonwersji_IsIncomplete] DEFAULT ('N'),
[czas] [datetime] NULL,
[id] [int] NULL,
[opis] [varchar] (1024) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_NT]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_NT]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_NT_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_NT_IsIncomplete] DEFAULT ('N'),
[baza] [smallint] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[opis] [text] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[typ] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_PO]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_PO]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PO_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PO_IsIncomplete] DEFAULT ('N'),
[flag] [smallint] NULL,
[id] [int] NULL,
[id1] [int] NULL,
[id2] [int] NULL,
[typ] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_MG]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_MG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MG_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MG_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[bufor] [smallint] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[datasp] [datetime] NULL,
[exp_fk] [smallint] NULL,
[flag] [smallint] NULL,
[grupacen] [smallint] NULL,
[guid] [uniqueidentifier] NULL,
[id] [int] NULL,
[iddokkoryg] [int] NULL,
[info] [smallint] NULL,
[jpk] [smallint] NULL,
[katalog] [int] NULL,
[khadid] [int] NULL,
[khdzial] [int] NULL,
[khid] [int] NULL,
[kod] [varchar] (40) NULL,
[magazyn] [int] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (40) NULL,
[netto] [float] NULL,
[odebrane] [varchar] (40) NULL,
[ok] [smallint] NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[przychod] [float] NULL,
[rejestrVat] [int] NULL,
[rodzaj] [int] NULL,
[rozchod] [float] NULL,
[rozlmg] [smallint] NULL,
[rr] [smallint] NULL,
[schemat] [varchar] (4) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[statusFK] [smallint] NULL,
[statusRDF] [smallint] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[typ_dk] [varchar] (4) NULL,
[wartk] [float] NULL,
[wartoscWz] [float] NULL,
[wystawil] [int] NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_MZ]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_MZ]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MZ_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MZ_IsIncomplete] DEFAULT ('N'),
[bufor] [smallint] NULL,
[cena] [float] NULL,
[data] [datetime] NULL,
[flag] [smallint] NULL,
[grupacen] [smallint] NULL,
[id] [int] NULL,
[idkh] [int] NULL,
[idlongname] [int] NULL,
[idpozkoryg] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[iloscjedn] [float] NULL,
[iloscRLKS] [float] NULL,
[iloscwp] [float] NULL,
[jm] [varchar] (8) NULL,
[jmwp] [varchar] (8) NULL,
[kod] [varchar] (40) NULL,
[kompensata] [smallint] NULL,
[lp] [smallint] NULL,
[lwartk] [smallint] NULL,
[magazyn] [int] NULL,
[opis] [varchar] (40) NULL,
[opisdod] [varchar] (20) NULL,
[przychod] [float] NULL,
[rejestr] [int] NULL,
[rozchod] [float] NULL,
[schemat] [varchar] (4) NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[superkoryg] [int] NULL,
[typ] [smallint] NULL,
[wartk] [float] NULL,
[wartNetto] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_RE]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_RE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RE_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[super] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_OP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_OP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_OP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_OP_IsIncomplete] DEFAULT ('N'),
[datarozl] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[id_co] [int] NULL,
[id_transakcji] [int] NULL,
[ilosc] [float] NULL,
[ilosc_rozl] [float] NULL,
[kod] [varchar] (40) NULL,
[ok] [smallint] NULL,
[owner_base] [int] NULL,
[owner_id] [int] NULL,
[subtyp] [smallint] NULL,
[wartosc] [float] NULL,
[wartosc_rozl] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_PN]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_PN]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PN_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PN_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[bufor] [smallint] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[datarozl] [datetime] NULL,
[dkid] [int] NULL,
[e_status] [smallint] NULL,
[exp_fk] [smallint] NULL,
[flag] [smallint] NULL,
[guid] [uniqueidentifier] NULL,
[id] [int] NULL,
[khadid] [int] NULL,
[khdzial] [int] NULL,
[khid] [int] NULL,
[kod] [varchar] (40) NULL,
[kurs] [float] NULL,
[kwota] [float] NULL,
[kwotarozl] [float] NULL,
[kwotarozlpln] [float] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[ok] [smallint] NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[plattyp] [int] NULL,
[rejestr] [int] NULL,
[related_fk] [smallint] NULL,
[schemat] [varchar] (4) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[stan] [float] NULL,
[status] [smallint] NULL,
[strona] [int] NULL,
[subtyp] [smallint] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[typdk] [varchar] (4) NULL,
[typkh] [smallint] NULL,
[waluta] [varchar] (3) NULL,
[wartosc] [float] NULL,
[wartoscWal] [float] NULL,
[wyplata] [smallint] NULL,
[wystawil] [int] NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_RLKS]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_RLKS]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RLKS_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RLKS_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[iddp] [int] NULL,
[idmz] [int] NULL,
[ilosc] [float] NULL,
[wartosc] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_RN]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_RN]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RN_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RN_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[id] [int] NULL,
[idtw] [int] NULL,
[kod] [varchar] (40) NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (100) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_PR]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_PR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PR_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[czas] [datetime] NULL,
[dane] [text] NULL,
[dscname] [varchar] (14) NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[idComp] [int] NULL,
[is_text] [smallint] NULL,
[katalog] [int] NULL,
[nazwa] [varchar] (68) NULL,
[rap_flag] [smallint] NULL,
[skrot] [varchar] (50) NULL,
[subtyp] [smallint] NULL,
[typ] [smallint] NULL,
[znacznik] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia__KonwersjaIdToCore]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia__KonwersjaIdToCore]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia__KonwersjaIdToCore_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia__KonwersjaIdToCore_IsIncomplete] DEFAULT ('N'),
[coreId] [int] NULL,
[hmfID] [int] NULL,
[objId] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_PW]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_PW]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PW_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_PW_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[iddkmg] [int] NULL,
[iddw] [int] NULL,
[idkoryg] [int] NULL,
[idmg] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[ilosczreal] [float] NULL,
[subtyp] [smallint] NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia__MigracjaDodatkowePolaKh]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia__MigracjaDodatkowePolaKh]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia__MigracjaDodatkowePolaKh_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia__MigracjaDodatkowePolaKh_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idkh] [int] NULL,
[nrpola] [smallint] NULL,
[opis] [varchar] (60) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_RO]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_RO]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RO_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RO_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[id1] [int] NULL,
[id2] [int] NULL,
[ilosc] [float] NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia__MigracjaDodatkowePolaTw]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia__MigracjaDodatkowePolaTw]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia__MigracjaDodatkowePolaTw_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia__MigracjaDodatkowePolaTw_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[idtw] [int] NULL,
[nrpola] [smallint] NULL,
[opis] [varchar] (60) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ROPN]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ROPN]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ROPN_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ROPN_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[id] [int] NULL,
[id1] [int] NULL,
[id2] [int] NULL,
[kurs1] [float] NULL,
[kurs2] [float] NULL,
[wartosc] [float] NULL,
[wartoscW1] [float] NULL,
[wartoscW2] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_AcInfo]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_AcInfo]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_AcInfo_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_AcInfo_IsIncomplete] DEFAULT ('N'),
[Ac_Name] [varchar] (15) NULL,
[Ac_Value] [image] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_RP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_RP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RP_IsIncomplete] DEFAULT ('N'),
[data] [datetime] NULL,
[exp_fk] [smallint] NULL,
[id] [int] NULL,
[idrj] [int] NULL,
[kod] [varchar] (40) NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[stan] [float] NULL,
[stanwal] [float] NULL,
[statusFK] [smallint] NULL,
[typdk] [varchar] (4) NULL,
[waluta] [varchar] (3) NULL,
[wplaty] [float] NULL,
[wplatywal] [float] NULL,
[wyplaty] [float] NULL,
[wyplatywal] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_amsys_objects]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_amsys_objects]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_amsys_objects_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_amsys_objects_IsIncomplete] DEFAULT ('N'),
[init] [smallint] NULL,
[lp] [int] NULL,
[name] [varchar] (100) NULL,
[obtype] [varchar] (2) NULL,
[type] [char] (1) NULL,
[ver] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_RV]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_RV]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RV_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RV_IsIncomplete] DEFAULT ('N'),
[datarej] [datetime] NULL,
[datawyst] [datetime] NULL,
[dkid] [int] NULL,
[id] [int] NULL,
[netto] [float] NULL,
[rejestr] [int] NULL,
[stvat] [int] NULL,
[vat] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_AD]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_AD]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_AD_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_AD_IsIncomplete] DEFAULT ('N'),
[dom] [varchar] (15) NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[idkh] [int] NULL,
[idKraju] [int] NULL,
[kodpocz] [varchar] (10) NULL,
[lokal] [varchar] (15) NULL,
[miejscowosc] [varchar] (50) NULL,
[nazwa] [varchar] (150) NULL,
[nazwaAdr] [varchar] (64) NULL,
[nip] [varchar] (20) NULL,
[typkh] [smallint] NULL,
[ulica] [varchar] (50) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_RZ]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_RZ]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RZ_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_RZ_IsIncomplete] DEFAULT ('N'),
[bazadokrz] [smallint] NULL,
[bazapozrz] [smallint] NULL,
[data] [datetime] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[iddokrz] [int] NULL,
[idkh] [int] NULL,
[idpozrz] [int] NULL,
[idtw] [int] NULL,
[iloscrl] [float] NULL,
[iloscrz] [float] NULL,
[magazyn] [int] NULL,
[subtyp] [smallint] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_ARM_BackLog]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_ARM_BackLog]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_BackLog_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_ARM_BackLog_IsIncomplete] DEFAULT ('N'),
[AmountLocal] [float] NULL,
[Bonus] [varchar] (1) NULL,
[ExpectedInvDate] [datetime] NULL,
[id] [int] NULL,
[InternalOrderNr] [varchar] (40) NULL,
[InvoiceShipTo] [varchar] (4) NULL,
[InvoiceSoldTo] [varchar] (4) NULL,
[ItemNo] [varchar] (40) NULL,
[ItemQty] [float] NULL,
[ItemUOM] [varchar] (8) NULL,
[LineBonus] [varchar] (1) NULL,
[lineid] [int] NULL,
[LineNr] [smallint] NULL,
[LocalCurrency] [varchar] (3) NULL,
[OrderCurrency] [varchar] (3) NULL,
[OrderLineAmount] [float] NULL,
[OrderLineType] [varchar] (1) NULL,
[OrderNr] [varchar] (80) NULL,
[OrginalQty] [float] NULL,
[SalesCompanyId] [int] NULL,
[SalesPersonId] [int] NULL,
[SalesPersonName] [nvarchar] (128) NULL,
[StatItemQty] [float] NULL,
[StatItemUOM] [varchar] (8) NULL,
[SysId] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_SD]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_SD]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SD_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SD_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[dzial] [bit] NULL,
[id] [int] NULL,
[idTypDok] [int] NULL,
[kod] [varchar] (40) NULL,
[numeracja] [smallint] NULL,
[szablon] [varchar] (100) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_AU]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_AU]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_AU_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_AU_IsIncomplete] DEFAULT ('N'),
[id] [int] NULL,
[o_id] [int] NULL,
[o_oper] [smallint] NULL,
[o_parent] [int] NULL,
[o_seed] [int] NULL,
[o_type] [int] NULL,
[o_unit] [int] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_SK]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_SK]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SK_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SK_IsIncomplete] DEFAULT ('N'),
[flag] [smallint] NULL,
[id] [int] NULL,
[kod] [varchar] (40) NULL,
[kodKor] [varchar] (4) NULL,
[nazwa] [varchar] (100) NULL,
[super] [int] NULL,
[trescFK] [varchar] (60) NULL,
[typ] [smallint] NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_CP]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_CP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_CP_IsIncomplete] DEFAULT ('N'),
[bazapoz] [smallint] NULL,
[cena] [float] NULL,
[cenowy] [smallint] NULL,
[flag] [smallint] NULL,
[id] [int] NULL,
[idck] [int] NULL,
[idpoz] [int] NULL,
[kod] [varchar] (40) NULL,
[typ] [smallint] NULL,
[waluta] [varchar] (3) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_Symfonia_SM]'
GO
CREATE TABLE [psa].[ics_stg_Symfonia_SM]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SM_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_SM_IsIncomplete] DEFAULT ('N'),
[flag] [smallint] NULL,
[id] [int] NULL,
[idtw] [int] NULL,
[magazyn] [int] NULL,
[stan] [float] NULL,
[stanHandl] [float] NULL,
[subtyp] [smallint] NULL,
[typ] [smallint] NULL,
[wartosc] [float] NULL
)
GO
