-- <Migration ID="e03e3eb8-3b6f-403e-9548-589322848e07" />
go

if object_id('tsa.ics_land_M3V10gen_POL_FGRECL','U') is not null drop table tsa.ics_land_M3V10gen_POL_FGRECL
go
if object_id('tsa.ics_land_M3V10ved_POL_FGRECL','U') is not null drop table tsa.ics_land_M3V10ved_POL_FGRECL 
go
if object_id('tsa.ics_land_M3V10vil_POL_FGRECL','U') is not null drop table tsa.ics_land_M3V10vil_POL_FGRECL
go
if object_id('tsa.ics_land_m3v7_FGRECL','U') is not null drop table tsa.ics_land_m3v7_FGRECL 
go
if object_id('tsa.ics_land_m3_FGRECL','U') is not null drop table tsa.ics_land_m3_FGRECL

GO

PRINT N'Creating [tsa].[ics_land_m3v7_FGRECL]'
GO
CREATE TABLE [tsa].[ics_land_m3v7_FGRECL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V7_FGRECL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V7_FGRECL_IsDuplicate] DEFAULT ((0)),
[F2CONO] [decimal] (3, 0) NULL,
[F2DIVI] [nvarchar] (255) NULL,
[F2PUNO] [nvarchar] (255) NULL,
[F2PNLI] [decimal] (3, 0) NULL,
[F2PNLS] [decimal] (3, 0) NULL,
[F2REPN] [decimal] (10, 0) NULL,
[F2RELP] [decimal] (1, 0) NULL,
[F2FACI] [nvarchar] (255) NULL,
[F2WHLO] [nvarchar] (255) NULL,
[F2SUDO] [nvarchar] (255) NULL,
[F2SUNO] [nvarchar] (255) NULL,
[F2SORN] [nvarchar] (255) NULL,
[F2TRDT] [decimal] (8, 0) NULL,
[F2ITNO] [nvarchar] (255) NULL,
[F2IMST] [decimal] (1, 0) NULL,
[F2IMDT] [decimal] (8, 0) NULL,
[F2SCOC] [decimal] (17, 6) NULL,
[F2SCOP] [decimal] (17, 6) NULL,
[F2SCDC] [decimal] (5, 2) NULL,
[F2PUCD] [decimal] (5, 0) NULL,
[F2CUCD] [nvarchar] (255) NULL,
[F2SERA] [decimal] (11, 6) NULL,
[F2CRTP] [decimal] (2, 0) NULL,
[F2RPQT] [decimal] (15, 6) NULL,
[F2RPQA] [decimal] (15, 6) NULL,
[F2CAWE] [decimal] (15, 6) NULL,
[F2IVQT] [decimal] (15, 6) NULL,
[F2IVQA] [decimal] (15, 6) NULL,
[F2IVCW] [decimal] (15, 6) NULL,
[F2RCAC] [decimal] (15, 2) NULL,
[F2ICAC] [decimal] (15, 2) NULL,
[F2IASR] [decimal] (1, 0) NULL,
[F2IASD] [decimal] (1, 0) NULL,
[F2ANBR] [decimal] (9, 0) NULL,
[F2SENO] [decimal] (4, 0) NULL,
[F2HSIN] [nvarchar] (255) NULL,
[F2SBAN] [nvarchar] (255) NULL,
[F2FGTP] [nvarchar] (255) NULL,
[F2ORTY] [nvarchar] (255) NULL,
[F2PIDT] [decimal] (8, 0) NULL,
[F2BUYE] [nvarchar] (255) NULL,
[F2RGDT] [decimal] (8, 0) NULL,
[F2RGTM] [decimal] (6, 0) NULL,
[F2LMDT] [decimal] (8, 0) NULL,
[F2CHNO] [decimal] (3, 0) NULL,
[F2CHID] [nvarchar] (255) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_m3_FGRECL]'
GO
CREATE TABLE [tsa].[ics_land_m3_FGRECL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3_FGRECL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3_FGRECL_IsDuplicate] DEFAULT ((0)),
[F2CONO] [decimal] (3, 0) NULL,
[F2DIVI] [nvarchar] (255) NULL,
[F2PUNO] [nvarchar] (255) NULL,
[F2PNLI] [decimal] (3, 0) NULL,
[F2PNLS] [decimal] (3, 0) NULL,
[F2REPN] [decimal] (10, 0) NULL,
[F2RELP] [decimal] (1, 0) NULL,
[F2FACI] [nvarchar] (255) NULL,
[F2WHLO] [nvarchar] (255) NULL,
[F2SUDO] [nvarchar] (255) NULL,
[F2SUNO] [nvarchar] (255) NULL,
[F2SORN] [nvarchar] (255) NULL,
[F2TRDT] [decimal] (8, 0) NULL,
[F2ITNO] [nvarchar] (255) NULL,
[F2IMST] [decimal] (1, 0) NULL,
[F2IMDT] [decimal] (8, 0) NULL,
[F2SCOC] [decimal] (17, 6) NULL,
[F2SCOP] [decimal] (19, 8) NULL,
[F2SCDC] [decimal] (5, 2) NULL,
[F2PUCD] [decimal] (5, 0) NULL,
[F2CUCD] [nvarchar] (255) NULL,
[F2SERA] [decimal] (11, 6) NULL,
[F2CRTP] [decimal] (2, 0) NULL,
[F2RPQT] [decimal] (15, 6) NULL,
[F2RPQA] [decimal] (15, 6) NULL,
[F2CAWE] [decimal] (15, 6) NULL,
[F2IVQT] [decimal] (15, 6) NULL,
[F2IVQA] [decimal] (15, 6) NULL,
[F2IVCW] [decimal] (15, 6) NULL,
[F2RCAC] [decimal] (15, 2) NULL,
[F2ICAC] [decimal] (15, 2) NULL,
[F2IASR] [decimal] (1, 0) NULL,
[F2IASD] [decimal] (1, 0) NULL,
[F2ANBR] [decimal] (12, 0) NULL,
[F2SENO] [decimal] (4, 0) NULL,
[F2HSIN] [nvarchar] (255) NULL,
[F2SBAN] [nvarchar] (255) NULL,
[F2FGTP] [nvarchar] (255) NULL,
[F2ORTY] [nvarchar] (255) NULL,
[F2PIDT] [decimal] (8, 0) NULL,
[F2BUYE] [nvarchar] (255) NULL,
[F2RGDT] [decimal] (8, 0) NULL,
[F2RGTM] [decimal] (6, 0) NULL,
[F2LMDT] [decimal] (8, 0) NULL,
[F2CHNO] [decimal] (3, 0) NULL,
[F2CHID] [nvarchar] (255) NULL,
[F2FIAS] [decimal] (1, 0) NULL,
[F2LMTS] [decimal] (18, 0) NULL,
[F2BANO] [nvarchar] (255) NULL,
[F2TRTM] [decimal] (6, 0) NULL,
[F2CLAN] [nvarchar] (255) NULL,
[F2CLLN] [decimal] (3, 0) NULL,
[F2SCOA] [decimal] (19, 8) NULL,
[F2BLSB] [decimal] (1, 0) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_M3V10vil_POL_FGRECL]'
GO
CREATE TABLE [tsa].[ics_land_M3V10vil_POL_FGRECL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_vil_FGRECL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_vil_FGRECL_IsDuplicate] DEFAULT ((0)),
[F2ANBR] [numeric] (9, 0) NULL,
[F2BUYE] [nchar] (10) NULL,
[F2CAWE] [numeric] (15, 6) NULL,
[F2CHID] [nchar] (10) NULL,
[F2CHNO] [numeric] (3, 0) NULL,
[F2CONO] [numeric] (3, 0) NULL,
[F2CRTP] [numeric] (2, 0) NULL,
[F2CUCD] [nchar] (3) NULL,
[F2DIVI] [nchar] (3) NULL,
[F2FACI] [nchar] (3) NULL,
[F2FGTP] [nchar] (2) NULL,
[F2FIAS] [numeric] (1, 0) NULL,
[F2HSIN] [nvarchar] (24) NULL,
[F2IASD] [numeric] (1, 0) NULL,
[F2IASR] [numeric] (1, 0) NULL,
[F2ICAC] [numeric] (15, 2) NULL,
[F2IMDT] [numeric] (8, 0) NULL,
[F2IMST] [numeric] (1, 0) NULL,
[F2ITNO] [nchar] (15) NULL,
[F2IVCW] [numeric] (15, 6) NULL,
[F2IVQA] [numeric] (15, 6) NULL,
[F2IVQT] [numeric] (15, 6) NULL,
[F2LMDT] [numeric] (8, 0) NULL,
[F2ORTY] [nchar] (3) NULL,
[F2PIDT] [numeric] (8, 0) NULL,
[F2PNLI] [numeric] (3, 0) NULL,
[F2PNLS] [numeric] (3, 0) NULL,
[F2PUCD] [numeric] (5, 0) NULL,
[F2PUNO] [nchar] (7) NULL,
[F2RCAC] [numeric] (15, 2) NULL,
[F2RELP] [numeric] (1, 0) NULL,
[F2REPN] [numeric] (10, 0) NULL,
[F2RGDT] [numeric] (8, 0) NULL,
[F2RGTM] [numeric] (6, 0) NULL,
[F2RPQA] [numeric] (15, 6) NULL,
[F2RPQT] [numeric] (15, 6) NULL,
[F2SBAN] [nchar] (10) NULL,
[F2SCDC] [numeric] (5, 2) NULL,
[F2SCOC] [numeric] (17, 6) NULL,
[F2SCOP] [numeric] (17, 6) NULL,
[F2SENO] [numeric] (4, 0) NULL,
[F2SERA] [numeric] (11, 6) NULL,
[F2SORN] [nvarchar] (20) NULL,
[F2SUDO] [nvarchar] (20) NULL,
[F2SUNO] [nchar] (10) NULL,
[F2TRDT] [numeric] (8, 0) NULL,
[F2WHLO] [nchar] (3) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_M3V10ved_POL_FGRECL]'
GO
CREATE TABLE [tsa].[ics_land_M3V10ved_POL_FGRECL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_land_ved_FGRECL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_land_ved_FGRECL_IsDuplicate] DEFAULT ((0)),
[F2ANBR] [numeric] (9, 0) NULL,
[F2BUYE] [nchar] (10) NULL,
[F2CAWE] [numeric] (15, 6) NULL,
[F2CHID] [nchar] (10) NULL,
[F2CHNO] [numeric] (3, 0) NULL,
[F2CONO] [numeric] (3, 0) NULL,
[F2CRTP] [numeric] (2, 0) NULL,
[F2CUCD] [nchar] (3) NULL,
[F2DIVI] [nchar] (3) NULL,
[F2FACI] [nchar] (3) NULL,
[F2FGTP] [nchar] (2) NULL,
[F2FIAS] [numeric] (1, 0) NULL,
[F2HSIN] [nvarchar] (24) NULL,
[F2IASD] [numeric] (1, 0) NULL,
[F2IASR] [numeric] (1, 0) NULL,
[F2ICAC] [numeric] (15, 2) NULL,
[F2IMDT] [numeric] (8, 0) NULL,
[F2IMST] [numeric] (1, 0) NULL,
[F2ITNO] [nchar] (15) NULL,
[F2IVCW] [numeric] (15, 6) NULL,
[F2IVQA] [numeric] (15, 6) NULL,
[F2IVQT] [numeric] (15, 6) NULL,
[F2LMDT] [numeric] (8, 0) NULL,
[F2ORTY] [nchar] (3) NULL,
[F2PIDT] [numeric] (8, 0) NULL,
[F2PNLI] [numeric] (3, 0) NULL,
[F2PNLS] [numeric] (3, 0) NULL,
[F2PUCD] [numeric] (5, 0) NULL,
[F2PUNO] [nchar] (7) NULL,
[F2RCAC] [numeric] (15, 2) NULL,
[F2RELP] [numeric] (1, 0) NULL,
[F2REPN] [numeric] (10, 0) NULL,
[F2RGDT] [numeric] (8, 0) NULL,
[F2RGTM] [numeric] (6, 0) NULL,
[F2RPQA] [numeric] (15, 6) NULL,
[F2RPQT] [numeric] (15, 6) NULL,
[F2SBAN] [nchar] (10) NULL,
[F2SCDC] [numeric] (5, 2) NULL,
[F2SCOC] [numeric] (17, 6) NULL,
[F2SCOP] [numeric] (17, 6) NULL,
[F2SENO] [numeric] (4, 0) NULL,
[F2SERA] [numeric] (11, 6) NULL,
[F2SORN] [nvarchar] (20) NULL,
[F2SUDO] [nvarchar] (20) NULL,
[F2SUNO] [nchar] (10) NULL,
[F2TRDT] [numeric] (8, 0) NULL,
[F2WHLO] [nchar] (3) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_M3V10gen_POL_FGRECL]'
GO
CREATE TABLE [tsa].[ics_land_M3V10gen_POL_FGRECL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_FGRECL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_gen_FGRECL_IsDuplicate] DEFAULT ((0)),
[F2ANBR] [numeric] (9, 0) NULL,
[F2BUYE] [nchar] (10) NULL,
[F2CAWE] [numeric] (15, 6) NULL,
[F2CHID] [nchar] (10) NULL,
[F2CHNO] [numeric] (3, 0) NULL,
[F2CONO] [numeric] (3, 0) NULL,
[F2CRTP] [numeric] (2, 0) NULL,
[F2CUCD] [nchar] (3) NULL,
[F2DIVI] [nchar] (3) NULL,
[F2FACI] [nchar] (3) NULL,
[F2FGTP] [nchar] (2) NULL,
[F2FIAS] [numeric] (1, 0) NULL,
[F2HSIN] [nvarchar] (24) NULL,
[F2IASD] [numeric] (1, 0) NULL,
[F2IASR] [numeric] (1, 0) NULL,
[F2ICAC] [numeric] (15, 2) NULL,
[F2IMDT] [numeric] (8, 0) NULL,
[F2IMST] [numeric] (1, 0) NULL,
[F2ITNO] [nchar] (15) NULL,
[F2IVCW] [numeric] (15, 6) NULL,
[F2IVQA] [numeric] (15, 6) NULL,
[F2IVQT] [numeric] (15, 6) NULL,
[F2LMDT] [numeric] (8, 0) NULL,
[F2ORTY] [nchar] (3) NULL,
[F2PIDT] [numeric] (8, 0) NULL,
[F2PNLI] [numeric] (3, 0) NULL,
[F2PNLS] [numeric] (3, 0) NULL,
[F2PUCD] [numeric] (5, 0) NULL,
[F2PUNO] [nchar] (7) NULL,
[F2RCAC] [numeric] (15, 2) NULL,
[F2RELP] [numeric] (1, 0) NULL,
[F2REPN] [numeric] (10, 0) NULL,
[F2RGDT] [numeric] (8, 0) NULL,
[F2RGTM] [numeric] (6, 0) NULL,
[F2RPQA] [numeric] (15, 6) NULL,
[F2RPQT] [numeric] (15, 6) NULL,
[F2SBAN] [nchar] (10) NULL,
[F2SCDC] [numeric] (5, 2) NULL,
[F2SCOC] [numeric] (17, 6) NULL,
[F2SCOP] [numeric] (17, 6) NULL,
[F2SENO] [numeric] (4, 0) NULL,
[F2SERA] [numeric] (11, 6) NULL,
[F2SORN] [nvarchar] (20) NULL,
[F2SUDO] [nvarchar] (20) NULL,
[F2SUNO] [nchar] (10) NULL,
[F2TRDT] [numeric] (8, 0) NULL,
[F2WHLO] [nchar] (3) NULL
)
GO
