-- <Migration ID="4b650fad-b496-419e-8d26-433f857368a0" />
GO

if object_id('[tsa].[ics_land_aspect4_ordhtbli]', 'U') is not null
	drop table [tsa].[ics_land_aspect4_ordhtbli] ;

	go
	if object_id('[tsa].[ics_land_aspect4_ordltbli]', 'U') is not null
	drop table [tsa].[ics_land_aspect4_ordltbli] ;
	go

	if object_id('[tsa].[ics_land_aspect4_modmtbl]', 'U') is not null
	drop table [tsa].[ics_land_aspect4_modmtbl] ;

	go





PRINT N'Creating [tsa].[ics_land_aspect4_ordhtbli]'
GO
CREATE TABLE [tsa].[ics_land_aspect4_ordhtbli]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_ordhtbli_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_ordhtbli_IsDuplicate] DEFAULT ((0)),
[ORDH_I_STATUS_KODE] [decimal] (1, 0) NULL,
[ORDH_I_RECORD_ID] [nvarchar] (2) NULL,
[ORDH_I_ORDREART] [nvarchar] (1) NULL,
[ORDH_I_ORDREKLASSE] [nvarchar] (1) NULL,
[ORDH_I_RECORDTYPE] [nvarchar] (2) NULL,
[ORDH_I_ORDRENR] [decimal] (9, 0) NULL,
[ORDH_I_LEV_LQBENR] [decimal] (4, 0) NULL,
[ORDH_I_KONCRN] [decimal] (3, 0) NULL,
[ORDH_I_FIRMA] [decimal] (3, 0) NULL,
[ORDH_I_OPDAT_DATO] [decimal] (8, 0) NULL,
[ORDH_I_OPDAT_AF] [nvarchar] (10) NULL,
[ORDH_I_OPRET_DATO] [decimal] (8, 0) NULL,
[ORDH_I_OPRET_AF] [nvarchar] (10) NULL,
[ORDH_I_ORDRESTATUS] [decimal] (2, 0) NULL,
[ORDH_LEVERANDQRNR] [nvarchar] (16) NULL,
[ORDH_I_LEV_TERMIN_DT] [decimal] (8, 0) NULL,
[ORDH_I_LEV_TERMIN_KL] [decimal] (4, 0) NULL,
[ORDH_I_UDLQB_TERMIN_DT] [decimal] (8, 0) NULL,
[ORDH_I_UDLQB_TERMIN_KL] [decimal] (4, 0) NULL,
[ORDH_I_RAMMEORDRENR] [decimal] (9, 0) NULL,
[ORDH_I_PRIORITET] [decimal] (2, 0) NULL,
[ORDH_I_LEV_ADRESSENR] [nvarchar] (4) NULL,
[ORDH_I_LEV_NAVN1] [nvarchar] (255) NULL,
[ORDH_I_LEV_NAVN2] [nvarchar] (255) NULL,
[ORDH_I_LEV_NAVN3] [nvarchar] (255) NULL,
[ORDH_I_LEV_NAVN4] [nvarchar] (255) NULL,
[ORDH_I_LEV_NAVN5] [nvarchar] (255) NULL,
[ORDH_I_LEV_KONTAKTPERSON] [nvarchar] (255) NULL,
[ORDH_I_LEV_TLF] [nvarchar] (20) NULL,
[ORDH_LEVERANDQR_ORDRENR] [nvarchar] (16) NULL,
[ORDH_LEVERANDQR_SAGSBEH] [nvarchar] (16) NULL,
[ORDH_I_VORES_SAGSBEH] [nvarchar] (16) NULL,
[ORDH_BEST] [nvarchar] (1) NULL,
[ORDH_BEST_ANTAL] [decimal] (2, 0) NULL,
[ORDH_RYKKER] [nvarchar] (1) NULL,
[ORDH_RYKKER_ANTAL] [decimal] (2, 0) NULL,
[ORDH_FILLER1] [nvarchar] (9) NULL,
[ORDH_I_EKSP_GEBYR] [decimal] (11, 2) NULL,
[ORDH_I_FORS_GEBYR] [decimal] (11, 2) NULL,
[ORDH_I_DIV1_GEBYR] [decimal] (11, 2) NULL,
[ORDH_I_DIV2_GEBYR] [decimal] (11, 2) NULL,
[ORDH_I_LEV_MAADE] [nvarchar] (255) NULL,
[ORDH_I_LEV_BETINGELSER] [nvarchar] (255) NULL,
[ORDH_FILLER2] [nvarchar] (8) NULL,
[ORDH_I_DISTRIKT] [nvarchar] (8) NULL,
[ORDH_I_VALUTA] [nvarchar] (4) NULL,
[ORDH_I_SPROG] [decimal] (2, 0) NULL,
[ORDH_I_MOMS] [nvarchar] (1) NULL,
[ORDH_I_BONUS] [nvarchar] (4) NULL,
[ORDH_BET_LEVERANDQRNR] [nvarchar] (16) NULL,
[ORDH_I_BET_VILKAAR] [nvarchar] (1) NULL,
[ORDH_I_BET_DAGE] [decimal] (3, 0) NULL,
[ORDH_I_RABAT_1_PCT] [decimal] (5, 2) NULL,
[ORDH_I_RABAT_1_DAGE] [decimal] (3, 0) NULL,
[ORDH_I_RABAT_2_PCT] [decimal] (5, 2) NULL,
[ORDH_I_RABAT_2_DAGE] [decimal] (3, 0) NULL,
[ORDH_I_TOTALRABAT_PCT] [decimal] (5, 2) NULL,
[ORDH_FILLER3] [nvarchar] (3) NULL,
[ORDH_RYKKER_DATO] [decimal] (8, 0) NULL,
[ORDH_FILLER4] [nvarchar] (6) NULL,
[ORDH_I_LEV_MAADE_KODE] [nvarchar] (2) NULL,
[ORDH_BESTILLINGS_DATO] [decimal] (8, 0) NULL,
[ORDH_I_OVERFQR_STATUS] [decimal] (1, 0) NULL,
[ORDH_I_BETALINGSKODE] [decimal] (3, 0) NULL,
[ORDH_KUNDENR_REFERENCE] [nvarchar] (16) NULL,
[ORDH_I_PROJNR] [decimal] (9, 0) NULL,
[ORDH_I_AARSAG] [nvarchar] (5) NULL,
[ORDH_I_LAGER] [nvarchar] (8) NULL,
[ORDH_I_TLAGER] [nvarchar] (8) NULL,
[ORDH_IOART] [nvarchar] (2) NULL,
[ORDH_IOARTB] [nvarchar] (2) NULL,
[ORDH_I_FRKDAT] [decimal] (8, 0) NULL,
[ORDH_I_FRKKL] [decimal] (4, 0) NULL,
[ORDH_I_LEVBK] [nvarchar] (2) NULL,
[ORDH_ITS] [decimal] (8, 0) NULL,
[ORDH_I_MOMSNR] [nvarchar] (15) NULL,
[ORDH_I_LAND] [nvarchar] (5) NULL,
[ORDH_I_POSTNR] [nvarchar] (255) NULL,
[ORDH_I_GODK] [nvarchar] (1) NULL,
[ORDH_I_PAR1] [nvarchar] (10) NULL,
[ORDH_I_NR1] [nvarchar] (16) NULL,
[ORDH_I_TEKST1] [nvarchar] (255) NULL,
[ORDH_I_MGD1] [decimal] (13, 5) NULL,
[ORDH_I_MGD2] [decimal] (13, 5) NULL,
[ORDH_I_MGD3] [decimal] (13, 5) NULL,
[ORDH_I_BELQB1] [decimal] (11, 2) NULL,
[ORDH_I_BELQB2] [decimal] (11, 2) NULL,
[ORDH_I_BELQB3] [decimal] (11, 2) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_aspect4_ordltbli]'
GO
CREATE TABLE [tsa].[ics_land_aspect4_ordltbli]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_ordltbli] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_ordltbliIsDuplicate] DEFAULT ((0)),
[ORDL_I_STATUS_KODE] [decimal] (1, 0) NULL,
[ORDL_I_RESSOURCETYPE] [nvarchar] (1) NULL,
[ORDL_I_TRANSTYPE] [nvarchar] (1) NULL,
[ORDL_I_ORDREART] [nvarchar] (1) NULL,
[ORDL_I_ORDREKLASSE] [nvarchar] (1) NULL,
[ORDL_I_RECORDTYPE] [nvarchar] (2) NULL,
[ORDL_I_ORDRENR] [decimal] (9, 0) NULL,
[ORDL_I_LEV_LQBENR] [decimal] (4, 0) NULL,
[ORDL_I_LINIENR] [decimal] (4, 0) NULL,
[ORDL_I_KONCRN] [decimal] (3, 0) NULL,
[ORDL_I_FIRMA] [decimal] (3, 0) NULL,
[ORDL_I_OPDAT_DATO] [decimal] (8, 0) NULL,
[ORDL_I_OPDAT_AF] [nvarchar] (10) NULL,
[ORDL_I_OPRET_DATO] [decimal] (8, 0) NULL,
[ORDL_I_OPRET_AF] [nvarchar] (10) NULL,
[ORDL_I_ORDRESTATUS] [decimal] (2, 0) NULL,
[ORDL_I_PRIORITET] [decimal] (2, 0) NULL,
[ORDL_I_VARENR] [nvarchar] (16) NULL,
[ORDL_I_LEV_TERMIN_DT] [decimal] (8, 0) NULL,
[ORDL_I_LEV_TERMIN_KL] [decimal] (4, 0) NULL,
[ORDL_I_PRIS] [decimal] (11, 2) NULL,
[ORDL_I_BELQB] [decimal] (11, 2) NULL,
[ORDL_I_BESTILT_ANTAL] [decimal] (13, 5) NULL,
[ORDL_I_LEVERET_ANTAL] [decimal] (13, 5) NULL,
[ORDL_I_RABAT] [decimal] (11, 2) NULL,
[ORDL_I_LAGR_NUMMER] [nvarchar] (8) NULL,
[ORDL_I_LAGR_PARTI] [nvarchar] (24) NULL,
[ORDL_I_UDF1] [nvarchar] (5) NULL,
[ORDL_I_UDF2] [nvarchar] (5) NULL,
[ORDL_I_UDF3] [nvarchar] (5) NULL,
[ORDL_I_UDF4] [nvarchar] (5) NULL,
[ORDL_I_UDF5] [nvarchar] (5) NULL,
[ORDL_I_ANTAL_U_LEVERING] [decimal] (13, 5) NULL,
[ORDL_I_OPR_BESTILT_ANTAL] [decimal] (13, 5) NULL,
[ORDL_I_LEVERANCE_NR] [decimal] (4, 0) NULL,
[ORDL_I_LEVERANCE_DATO] [decimal] (8, 0) NULL,
[ORDL_I_ORDREPOLITIK] [nvarchar] (2) NULL,
[ORDL_I_PRISANGIVELSE] [decimal] (6, 0) NULL,
[ORDL_I_RABATTYPE] [nvarchar] (1) NULL,
[ORDL_I_PRISRABAT] [nvarchar] (1) NULL,
[ORDL_I_MAENGDERABAT] [nvarchar] (1) NULL,
[ORDL_I_PRISLISTE] [nvarchar] (1) NULL,
[ORDL_LEVERANDQR_VARENR] [nvarchar] (16) NULL,
[ORDL_LEVERANDQR_VARENAVN] [nvarchar] (255) NULL,
[ORDL_I_SPECIALAFTALE] [nvarchar] (1) NULL,
[ORDL_I_GRUNDPRIS_BRUGES_IKKE] [decimal] (11, 2) NULL,
[ORDL_I_KOSTBELQB] [decimal] (11, 2) NULL,
[ORDL_I_AFSLUTTES] [nvarchar] (1) NULL,
[ORDL_I_OPR_LEV_TERMIN_DT] [decimal] (8, 0) NULL,
[ORDL_I_OPR_LEV_TERMIN_KL] [decimal] (4, 0) NULL,
[ORDL_LEVERANDQR_FAKT_DATO] [decimal] (8, 0) NULL,
[ORDL_I_QNS_LEV_TERMIN_DT] [decimal] (8, 0) NULL,
[ORDL_I_QNS_LEV_TERMIN_KL] [decimal] (4, 0) NULL,
[ORDL_LEVDQR] [nvarchar] (16) NULL,
[ORDL_ANTFK] [decimal] (13, 5) NULL,
[ORDL_ANTUFK] [decimal] (13, 5) NULL,
[ORDL_FAKBEL] [decimal] (11, 2) NULL,
[ORDL_I_PROJNR] [decimal] (9, 0) NULL,
[ORDL_I_AARSAG] [nvarchar] (5) NULL,
[ORDL_I_LOKAT] [nvarchar] (10) NULL,
[ORDL_I_TLAGER] [nvarchar] (8) NULL,
[ORDL_I_TPARTI] [nvarchar] (24) NULL,
[ORDL_I_TLOKAT] [nvarchar] (10) NULL,
[ORDL_I_FRKDAT] [decimal] (8, 0) NULL,
[ORDL_I_FRKKL] [decimal] (4, 0) NULL,
[ORDL_ANTLLG] [decimal] (13, 5) NULL,
[ORDL_BEHTYP] [nvarchar] (2) NULL,
[ORDL_ANTUFL] [decimal] (13, 5) NULL,
[ORDL_I_KORREKTION] [decimal] (11, 2) NULL,
[ORDL_I_TOTALRABAT] [nvarchar] (1) NULL,
[ORDL_I_PRISGRUPPE] [nvarchar] (2) NULL,
[ORDL_I_PRIS_DATO] [decimal] (8, 0) NULL,
[ORDL_I_ULPCT] [decimal] (5, 2) NULL,
[ORDL_I_OLPCT] [decimal] (5, 2) NULL,
[ORDL_I_SUPKOR] [decimal] (5, 2) NULL,
[ORDL_ITS] [decimal] (8, 0) NULL,
[ORDL_I_ANBESI] [decimal] (13, 5) NULL,
[ORDL_I_PAR1] [nvarchar] (10) NULL,
[ORDL_I_NR1] [nvarchar] (16) NULL,
[ORDL_I_TEKST1] [nvarchar] (255) NULL,
[ORDL_I_MGD1] [decimal] (13, 5) NULL,
[ORDL_I_MGD2] [decimal] (13, 5) NULL,
[ORDL_I_MGD3] [decimal] (13, 5) NULL,
[ORDL_I_BELQB1] [decimal] (11, 2) NULL,
[ORDL_I_BELQB2] [decimal] (11, 2) NULL,
[ORDL_I_BELQB3] [decimal] (11, 2) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_aspect4_modmtbl]'
GO
CREATE TABLE [tsa].[ics_land_aspect4_modmtbl]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_modmtbl_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_modmtbl_IsDuplicate] DEFAULT ((0)),
[MODM_RECSTS] [decimal] (1, 0) NULL,
[MODM_RECID] [nvarchar] (2) NULL,
[MODM_TYPE] [nvarchar] (2) NULL,
[MODM_NR] [decimal] (9, 0) NULL,
[MODM_LLQBNR] [decimal] (4, 0) NULL,
[MODM_LINIE] [decimal] (4, 0) NULL,
[MODM_KONCRN] [decimal] (3, 0) NULL,
[MODM_FIRMA] [decimal] (3, 0) NULL,
[MODM_JOUNR] [decimal] (9, 0) NULL,
[MODM_BILNR] [decimal] (9, 0) NULL,
[MODM_BILDT] [decimal] (8, 0) NULL,
[MODM_BILTXT] [nvarchar] (255) NULL,
[MODM_REGID] [nvarchar] (8) NULL,
[MODM_LEVNR] [nvarchar] (16) NULL,
[MODM_VARENR] [nvarchar] (16) NULL,
[MODM_UDF1] [nvarchar] (5) NULL,
[MODM_UDF2] [nvarchar] (5) NULL,
[MODM_UDF3] [nvarchar] (5) NULL,
[MODM_UDF4] [nvarchar] (5) NULL,
[MODM_UDF5] [nvarchar] (5) NULL,
[MODM_LAGER] [nvarchar] (8) NULL,
[MODM_PARTI] [nvarchar] (24) NULL,
[MODM_LOKAT] [nvarchar] (10) NULL,
[MODM_ANTAL] [decimal] (13, 5) NULL,
[MODM_ANTALB] [decimal] (13, 5) NULL,
[MODM_SBELQB] [decimal] (11, 2) NULL,
[MODM_KBELQB] [decimal] (11, 2) NULL,
[MODM_OBELQB] [decimal] (11, 2) NULL,
[MODM_VREGN] [nvarchar] (2) NULL,
[MODM_LREGN] [nvarchar] (2) NULL,
[MODM_DREGN] [nvarchar] (2) NULL,
[MODM_AREGN] [nvarchar] (2) NULL,
[MODM_DIST] [nvarchar] (8) NULL,
[MODM_VAREB] [nvarchar] (16) NULL,
[MODM_UDF1B] [nvarchar] (5) NULL,
[MODM_UDF2B] [nvarchar] (5) NULL,
[MODM_UDF3B] [nvarchar] (5) NULL,
[MODM_UDF4B] [nvarchar] (5) NULL,
[MODM_UDF5B] [nvarchar] (5) NULL,
[MODM_BEST] [decimal] (13, 5) NULL,
[MODM_BESTB] [decimal] (13, 5) NULL,
[MODM_OBEST] [decimal] (13, 5) NULL,
[MODM_OBESTB] [decimal] (13, 5) NULL,
[MODM_LEVTER] [decimal] (8, 0) NULL,
[MODM_OPRTER] [decimal] (8, 0) NULL,
[MODM_QNSTER] [decimal] (8, 0) NULL,
[MODM_OPRDT] [decimal] (8, 0) NULL,
[MODM_OPRAF] [nvarchar] (10) NULL,
[MODM_PROJNR] [decimal] (9, 0) NULL,
[MODM_AARSAG] [nvarchar] (5) NULL,
[MODM_IOART] [nvarchar] (2) NULL,
[MODM_BEHTYP] [nvarchar] (2) NULL,
[MODM_MARSAG] [nvarchar] (5) NULL,
[MODM_TS] [decimal] (8, 0) NULL,
[MODM_FJOUNR] [decimal] (9, 0) NULL,
[MODM_FBILAG] [decimal] (9, 0) NULL,
[MODM_MTCHAF] [nvarchar] (10) NULL,
[MODM_UDLID] [nvarchar] (30) NULL
)
GO
