-- <Migration ID="33a85079-9b59-430c-a6b7-675e712077bb" />
GO

if object_id('[tsa].[ics_land_baan_ttiitm004610]', 'U') is not null
	drop table [tsa].[ics_land_baan_ttiitm004610] ;

	if object_id('[tsa].[ics_land_aspect4_VAOFTBL]', 'U') is not null
	drop table [tsa].[ics_land_aspect4_VAOFTBL]

	if object_id('[tsa].[ics_land_aspect4_VARITBL]', 'U') is not null
	drop table  [tsa].[ics_land_aspect4_VARITBL]
	if object_id('[tsa].[ics_land_aspect4_VARBTBL]', 'U') is not null
	drop table  [tsa].[ics_land_aspect4_VARBTBL]

PRINT N'Creating [tsa].[ics_land_baan_tiitm001610]'
GO
CREATE TABLE [tsa].[ics_land_baan_tiitm001610]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_tiitm001610_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_baan_tiitm001610_IsDuplicate] DEFAULT ((0)),
[t_item] [nvarchar] (16) NULL,
[t_dsca] [nvarchar] (30) NULL,
[t_dscb] [nvarchar] (8) NULL,
[t_dscc] [nvarchar] (12) NULL,
[t_dscd] [nvarchar] (8) NULL,
[t_wght] [float] NULL,
[t_seak] [nvarchar] (16) NULL,
[t_seab] [nvarchar] (16) NULL,
[t_kitm] [smallint] NULL,
[t_citg] [nvarchar] (6) NULL,
[t_ctyp] [nvarchar] (3) NULL,
[t_csel] [nvarchar] (3) NULL,
[t_csig] [nvarchar] (3) NULL,
[t_cvat] [nvarchar] (9) NULL,
[t_txta] [int] NULL,
[t_uset] [nvarchar] (6) NULL,
[t_cuni] [nvarchar] (3) NULL,
[t_stgu] [nvarchar] (3) NULL,
[t_cwar] [nvarchar] (3) NULL,
[t_kltc] [smallint] NULL,
[t_obpr] [smallint] NULL,
[t_kpsl] [smallint] NULL,
[t_npsl] [int] NULL,
[t_pics] [smallint] NULL,
[t_abcc] [nvarchar] (1) NULL,
[t_lcod] [datetime] NULL,
[t_uscu] [float] NULL,
[t_usab] [float] NULL,
[t_slmp] [smallint] NULL,
[t_serv] [smallint] NULL,
[t_sfst] [float] NULL,
[t_maxs] [float] NULL,
[t_csps] [nvarchar] (3) NULL,
[t_cspd] [nvarchar] (3) NULL,
[t_cfmd] [nvarchar] (3) NULL,
[t_scst] [float] NULL,
[t_stoc] [float] NULL,
[t_blck] [float] NULL,
[t_ordr] [float] NULL,
[t_allo] [float] NULL,
[t_hall] [float] NULL,
[t_quot] [float] NULL,
[t_ltdt] [datetime] NULL,
[t_opol] [smallint] NULL,
[t_osys] [smallint] NULL,
[t_omth] [smallint] NULL,
[t_oqmf] [float] NULL,
[t_mioq] [float] NULL,
[t_maoq] [float] NULL,
[t_umer] [smallint] NULL,
[t_fioq] [float] NULL,
[t_ecoq] [float] NULL,
[t_reop] [float] NULL,
[t_oint] [smallint] NULL,
[t_ddfq] [float] NULL,
[t_oltm] [smallint] NULL,
[t_sftm] [smallint] NULL,
[t_fodt] [datetime] NULL,
[t_ocst] [float] NULL,
[t_auso] [smallint] NULL,
[t_cpha] [smallint] NULL,
[t_oqdr] [smallint] NULL,
[t_repi] [smallint] NULL,
[t_scdl] [nvarchar] (3) NULL,
[t_orip] [smallint] NULL,
[t_pcrp] [smallint] NULL,
[t_stpm] [smallint] NULL,
[t_mrpc] [smallint] NULL,
[t_plmm] [smallint] NULL,
[t_mrpo] [smallint] NULL,
[t_eitm] [smallint] NULL,
[t_bfcp] [smallint] NULL,
[t_bfep] [smallint] NULL,
[t_bfhr] [smallint] NULL,
[t_ndrp] [smallint] NULL,
[t_nnts] [smallint] NULL,
[t_qpnt] [float] NULL,
[t_unom] [float] NULL,
[t_runi] [float] NULL,
[t_scpf] [smallint] NULL,
[t_crmp] [smallint] NULL,
[t_tmfc] [smallint] NULL,
[t_roun] [smallint] NULL,
[t_ncst] [smallint] NULL,
[t_llcd] [smallint] NULL,
[t_llci] [smallint] NULL,
[t_mrpi] [smallint] NULL,
[t_stmr] [float] NULL,
[t_cuqp] [nvarchar] (3) NULL,
[t_cupp] [nvarchar] (3) NULL,
[t_cpgp] [nvarchar] (6) NULL,
[t_csgp] [nvarchar] (6) NULL,
[t_pcgp] [nvarchar] (6) NULL,
[t_ccur] [nvarchar] (3) NULL,
[t_ltpp] [datetime] NULL,
[t_prip] [float] NULL,
[t_avpr] [float] NULL,
[t_ltpr] [float] NULL,
[t_suno] [nvarchar] (6) NULL,
[t_qual] [smallint] NULL,
[t_purc] [float] NULL,
[t_txtp] [int] NULL,
[t_cuqs] [nvarchar] (3) NULL,
[t_cups] [nvarchar] (3) NULL,
[t_cpgs] [nvarchar] (6) NULL,
[t_csgs] [nvarchar] (6) NULL,
[t_cmgp] [nvarchar] (6) NULL,
[t_rbgp] [nvarchar] (6) NULL,
[t_pris] [float] NULL,
[t_ltsp] [datetime] NULL,
[t_prir] [float] NULL,
[t_umsp] [real] NULL,
[t_lmsp] [real] NULL,
[t_ccde] [nvarchar] (8) NULL,
[t_ctyo] [nvarchar] (3) NULL,
[t_txts] [int] NULL,
[t_cpcp] [nvarchar] (3) NULL,
[t_copr] [float] NULL,
[t_matc] [float] NULL,
[t_oprc] [float] NULL,
[t_cuid] [smallint] NULL,
[t_actf] [float] NULL,
[t_ltcp] [datetime] NULL,
[t_stva] [smallint] NULL,
[t_buyr] [int] NULL,
[t_cplb] [int] NULL,
[t_cppp] [smallint] NULL,
[t_ccit] [nvarchar] (16) NULL,
[t_ccfu] [smallint] NULL,
[t_ccco] [nvarchar] (8) NULL,
[t_prre] [smallint] NULL,
[t_copt] [smallint] NULL,
[t_cprp] [float] NULL,
[t_itmt] [smallint] NULL,
[t_proi] [smallint] NULL,
[t_cont] [smallint] NULL,
[t_cntr] [nvarchar] (3) NULL,
[t_czed] [smallint] NULL,
[t_reli] [nvarchar] (16) NULL,
[t_assi] [smallint] NULL,
[t_potc] [real] NULL,
[t_ffsi] [int] NULL,
[t_qbsi] [float] NULL,
[t_osyc] [smallint] NULL,
[t_ufra] [smallint] NULL,
[t_nobd] [smallint] NULL,
[t_blcm] [float] NULL,
[t_dcnt] [nvarchar] (3) NULL,
[t_exkb] [smallint] NULL,
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL
)
GO
PRINT N'Creating [tsa].[ics_land_aspect4_VAOFTBL]'
GO
CREATE TABLE [tsa].[ics_land_aspect4_VAOFTBL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VAOFTBL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VAOFTBL_IsDuplicate] DEFAULT ((0)),
[VAOF_RECSTS] [decimal] (1, 0) NULL,
[VAOF_RECID] [nvarchar] (2) NULL,
[VAOF_VARENR] [nvarchar] (16) NULL,
[VAOF_ENHED] [nvarchar] (5) NULL,
[VAOF_FRADT] [decimal] (8, 0) NULL,
[VAOF_KONCRN] [decimal] (3, 0) NULL,
[VAOF_FIRMA] [decimal] (3, 0) NULL,
[VAOF_OMRFAK] [decimal] (9, 4) NULL,
[VAOF_OMRKOD] [nvarchar] (1) NULL,
[VAOF_AENDDT] [decimal] (8, 0) NULL,
[VAOF_AENDAF] [nvarchar] (10) NULL,
[VAOF_OPRDT] [decimal] (8, 0) NULL,
[VAOF_OPRAF] [nvarchar] (10) NULL,
[VAOF_TS] [decimal] (8, 0) NULL,
[VAOF_LGD] [decimal] (13, 5) NULL,
[VAOF_BRD] [decimal] (13, 5) NULL,
[VAOF_HQJ] [decimal] (13, 5) NULL,
[VAOF_VGT] [decimal] (13, 5) NULL,
[VAOF_TYPE] [nvarchar] (1) NULL,
[VAOF_SVGT] [decimal] (13, 5) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_aspect4_VARBTBL]'
GO
CREATE TABLE [tsa].[ics_land_aspect4_VARBTBL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VARBTBL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VARBTBL_IsDuplicate] DEFAULT ((0)),
[VARB_RECSTS] [decimal] (1, 0) NULL,
[VARB_RECID] [nvarchar] (2) NULL,
[VARB_NR] [nvarchar] (16) NULL,
[VARB_KONCRN] [decimal] (3, 0) NULL,
[VARB_FIRMA] [decimal] (3, 0) NULL,
[VARB_TYPE] [nvarchar] (1) NULL,
[VARB_BETEGN] [nvarchar] (255) NULL,
[VARB_STATUS] [decimal] (2, 0) NULL,
[VARB_STYPE] [nvarchar] (1) NULL,
[VARB_GRP0] [nvarchar] (5) NULL,
[VARB_GRP1] [nvarchar] (5) NULL,
[VARB_GRP2] [nvarchar] (5) NULL,
[VARB_GRP3] [nvarchar] (5) NULL,
[VARB_GRP4] [nvarchar] (5) NULL,
[VARB_GRP5] [nvarchar] (5) NULL,
[VARB_GRP6] [nvarchar] (5) NULL,
[VARB_GRP7] [nvarchar] (5) NULL,
[VARB_GRP8] [nvarchar] (5) NULL,
[VARB_GRP9] [nvarchar] (5) NULL,
[VARB_REGN] [nvarchar] (2) NULL,
[VARB_ENHED] [nvarchar] (5) NULL,
[VARB_PRISAN] [decimal] (7, 0) NULL,
[VARB_ANTDEC] [decimal] (1, 0) NULL,
[VARB_LAGER] [nvarchar] (8) NULL,
[VARB_LOKAT] [nvarchar] (10) NULL,
[VARB_PARTI] [nvarchar] (1) NULL,
[VARB_LSTAT] [nvarchar] (1) NULL,
[VARB_LHIST] [nvarchar] (1) NULL,
[VARB_KALK] [nvarchar] (1) NULL,
[VARB_DISP] [nvarchar] (1) NULL,
[VARB_SIKDAG] [decimal] (3, 0) NULL,
[VARB_ORDPOL] [nvarchar] (2) NULL,
[VARB_LLC] [decimal] (2, 0) NULL,
[VARB_MINLAG] [decimal] (13, 5) NULL,
[VARB_MAXLAG] [decimal] (13, 5) NULL,
[VARB_TOLD] [nvarchar] (2) NULL,
[VARB_OLAND] [nvarchar] (5) NULL,
[VARB_PPLUK] [nvarchar] (1) NULL,
[VARB_PJOBK] [nvarchar] (1) NULL,
[VARB_PPROD] [nvarchar] (1) NULL,
[VARB_REGI] [nvarchar] (1) NULL,
[VARB_FSTMGI] [decimal] (13, 5) NULL,
[VARB_KORRFI] [decimal] (5, 2) NULL,
[VARB_VARMGI] [decimal] (13, 5) NULL,
[VARB_KORRVI] [decimal] (5, 2) NULL,
[VARB_VEDGOI] [nvarchar] (1) NULL,
[VARB_VEDKAI] [nvarchar] (1) NULL,
[VARB_VEDINI] [nvarchar] (1) NULL,
[VARB_KASPCI] [decimal] (5, 2) NULL,
[VARB_TIDKDI] [nvarchar] (1) NULL,
[VARB_TIDMIN] [decimal] (9, 2) NULL,
[VARB_TIDENH] [decimal] (9, 2) NULL,
[VARB_KALKOR] [decimal] (13, 5) NULL,
[VARB_MINORD] [decimal] (13, 5) NULL,
[VARB_ENHORD] [decimal] (13, 5) NULL,
[VARB_MAXORD] [decimal] (13, 5) NULL,
[VARB_MODNR] [nvarchar] (16) NULL,
[VARB_MODVAR] [nvarchar] (8) NULL,
[VARB_PLUK] [nvarchar] (1) NULL,
[VARB_FQLG] [nvarchar] (1) NULL,
[VARB_PROD] [nvarchar] (1) NULL,
[VARB_TEKSLK] [decimal] (9, 2) NULL,
[VARB_SLKKO] [nvarchar] (1) NULL,
[VARB_SLKKAL] [nvarchar] (1) NULL,
[VARB_REGU] [nvarchar] (1) NULL,
[VARB_FSTMGU] [decimal] (13, 5) NULL,
[VARB_KORRFU] [decimal] (5, 2) NULL,
[VARB_VARMGU] [decimal] (13, 5) NULL,
[VARB_KORRVU] [decimal] (5, 2) NULL,
[VARB_VEDGOU] [nvarchar] (1) NULL,
[VARB_VEDKAU] [nvarchar] (1) NULL,
[VARB_VEDINU] [nvarchar] (1) NULL,
[VARB_KASPCU] [decimal] (5, 2) NULL,
[VARB_TIDKDU] [nvarchar] (1) NULL,
[VARB_AENDDT] [decimal] (8, 0) NULL,
[VARB_AENDAF] [nvarchar] (10) NULL,
[VARB_OPRDT] [decimal] (8, 0) NULL,
[VARB_OPRAF] [nvarchar] (10) NULL,
[VARB_PLAGER] [nvarchar] (8) NULL,
[VARB_ORDTYP] [nvarchar] (2) NULL,
[VARB_FBRDAG] [decimal] (13, 5) NULL,
[VARB_VOLKL] [nvarchar] (1) NULL,
[VARB_SIKFAK] [decimal] (5, 2) NULL,
[VARB_MANDSP] [nvarchar] (1) NULL,
[VARB_TS] [decimal] (8, 0) NULL,
[VARB_KMTODE] [nvarchar] (1) NULL,
[VARB_BOBAND] [nvarchar] (5) NULL,
[VARB_KVEDL] [decimal] (3, 0) NULL,
[VARB_FVEDL] [decimal] (3, 0) NULL,
[VARB_GRPA] [nvarchar] (5) NULL,
[VARB_GRPB] [nvarchar] (5) NULL,
[VARB_GRPC] [nvarchar] (5) NULL,
[VARB_GRPD] [nvarchar] (5) NULL,
[VARB_GRPE] [nvarchar] (5) NULL,
[VARB_GRPF] [nvarchar] (5) NULL,
[VARB_GRPG] [nvarchar] (5) NULL,
[VARB_GRPH] [nvarchar] (5) NULL,
[VARB_GRPI] [nvarchar] (5) NULL,
[VARB_GRPJ] [nvarchar] (5) NULL,
[VARB_PAR0] [nvarchar] (10) NULL,
[VARB_PAR1] [nvarchar] (10) NULL,
[VARB_PAR2] [nvarchar] (10) NULL,
[VARB_PAR3] [nvarchar] (10) NULL,
[VARB_PAR4] [nvarchar] (10) NULL,
[VARB_PAR5] [nvarchar] (10) NULL,
[VARB_PAR6] [nvarchar] (10) NULL,
[VARB_PAR7] [nvarchar] (10) NULL,
[VARB_PAR8] [nvarchar] (10) NULL,
[VARB_PAR9] [nvarchar] (10) NULL,
[VARB_NUM0] [decimal] (11, 2) NULL,
[VARB_NUM1] [decimal] (11, 2) NULL,
[VARB_NUM2] [decimal] (11, 2) NULL,
[VARB_NUM3] [decimal] (11, 2) NULL,
[VARB_NUM4] [decimal] (11, 2) NULL,
[VARB_NUM5] [decimal] (11, 2) NULL,
[VARB_NUM6] [decimal] (11, 2) NULL,
[VARB_NUM7] [decimal] (11, 2) NULL,
[VARB_NUM8] [decimal] (11, 2) NULL,
[VARB_NUM9] [decimal] (11, 2) NULL,
[VARB_RNR0] [nvarchar] (16) NULL,
[VARB_RNR1] [nvarchar] (16) NULL,
[VARB_RNR2] [nvarchar] (16) NULL,
[VARB_RNR3] [nvarchar] (16) NULL,
[VARB_RNR4] [nvarchar] (16) NULL,
[VARB_RNR5] [nvarchar] (16) NULL,
[VARB_RNR6] [nvarchar] (16) NULL,
[VARB_RNR7] [nvarchar] (16) NULL,
[VARB_RNR8] [nvarchar] (16) NULL,
[VARB_RNR9] [nvarchar] (16) NULL,
[VARB_ALFA0] [nvarchar] (1) NULL,
[VARB_ALFA1] [nvarchar] (1) NULL,
[VARB_ALFA2] [nvarchar] (1) NULL,
[VARB_ALFA3] [nvarchar] (1) NULL,
[VARB_ALFA4] [nvarchar] (1) NULL,
[VARB_ALFA5] [nvarchar] (1) NULL,
[VARB_ALFA6] [nvarchar] (1) NULL,
[VARB_ALFA7] [nvarchar] (1) NULL,
[VARB_ALFA8] [nvarchar] (1) NULL,
[VARB_ALFA9] [nvarchar] (1) NULL
)
GO
PRINT N'Creating [tsa].[ics_land_aspect4_VARITBL]'
GO
CREATE TABLE [tsa].[ics_land_aspect4_VARITBL]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VARITBL_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_aspect4_VARITBL_IsDuplicate] DEFAULT ((0)),
[VARI_RECSTS] [decimal] (1, 0) NULL,
[VARI_RECID] [nvarchar] (2) NULL,
[VARI_NR] [nvarchar] (16) NULL,
[VARI_KONCRN] [decimal] (3, 0) NULL,
[VARI_FIRMA] [decimal] (3, 0) NULL,
[VARI_TYPE] [nvarchar] (1) NULL,
[VARI_INR] [nvarchar] (16) NULL,
[VARI_BETEGN] [nvarchar] (255) NULL,
[VARI_GRP] [nvarchar] (2) NULL,
[VARI_MSGRP] [nvarchar] (2) NULL,
[VARI_RABGRP] [nvarchar] (5) NULL,
[VARI_ENHED] [nvarchar] (5) NULL,
[VARI_OMRFAK] [decimal] (9, 4) NULL,
[VARI_OMRKOD] [nvarchar] (1) NULL,
[VARI_PRISAN] [decimal] (7, 0) NULL,
[VARI_ANTDEC] [decimal] (1, 0) NULL,
[VARI_LEVDQR] [nvarchar] (16) NULL,
[VARI_STDVAL] [nvarchar] (4) NULL,
[VARI_STDPRI] [decimal] (11, 2) NULL,
[VARI_SENVAL] [nvarchar] (4) NULL,
[VARI_SENPRI] [decimal] (11, 2) NULL,
[VARI_BESOMK] [decimal] (11, 2) NULL,
[VARI_SPECAF] [nvarchar] (1) NULL,
[VARI_PRIRAB] [nvarchar] (1) NULL,
[VARI_MGDRAB] [nvarchar] (1) NULL,
[VARI_MINORD] [decimal] (13, 5) NULL,
[VARI_ENHORD] [decimal] (13, 5) NULL,
[VARI_MAXORD] [decimal] (13, 5) NULL,
[VARI_TIDMIN] [decimal] (3, 0) NULL,
[VARI_TIDENH] [decimal] (3, 0) NULL,
[VARI_DISPON] [nvarchar] (5) NULL,
[VARI_TOLD] [nvarchar] (4) NULL,
[VARI_TOLDPR] [nvarchar] (5) NULL,
[VARI_STAT] [nvarchar] (1) NULL,
[VARI_AENDDT] [decimal] (8, 0) NULL,
[VARI_AENDAF] [nvarchar] (10) NULL,
[VARI_OPRDT] [decimal] (8, 0) NULL,
[VARI_OPRAF] [nvarchar] (10) NULL,
[VARI_FRAGAN] [decimal] (7, 0) NULL,
[VARI_BRUVGT] [decimal] (13, 5) NULL,
[VARI_NETVGT] [decimal] (13, 5) NULL,
[VARI_RUMF] [decimal] (13, 5) NULL,
[VARI_KOLSTR] [decimal] (13, 5) NULL,
[VARI_KOLANG] [nvarchar] (1) NULL,
[VARI_PALSTR] [decimal] (13, 5) NULL,
[VARI_PALANG] [nvarchar] (1) NULL,
[VARI_ARTBEH] [nvarchar] (2) NULL,
[VARI_MLAGER] [nvarchar] (8) NULL,
[VARI_BESINT] [decimal] (3, 0) NULL,
[VARI_TS] [decimal] (8, 0) NULL,
[VARI_MODNR] [nvarchar] (16) NULL,
[VARI_MODVAR] [nvarchar] (8) NULL,
[VARI_LGD] [decimal] (11, 2) NULL,
[VARI_BRD] [decimal] (11, 2) NULL,
[VARI_HQJ] [decimal] (11, 2) NULL
)
GO
