--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

set nocount on

merge into [dbo].[unit_of_measure_type] as Target
using (values
  (-5,'Not Defined','Used where the logic to identify the correct static type has not been supplied or specified')
 ,(-4,'Not Applicable','Used where this static type has no relevance in this context')
 ,(-3,'Not Implemented in Source','Used when the source system does not support the concept of this static type')
 ,(-2,'Lookup Not Found','Indicates that the source system provided a value but that there is no matching lookup')
 ,(-1,'Not Specified at Source','Indicates that the value in the source system was NULL')
 ,(10,'Area','E.g. M², Square Feet, Acres, Hectares etc.')
 ,(11,'Distance','')
 ,(12,'Altitude','')
 ,(13,'Volume','')
 ,(14,'Aggregate','Includes Count, Average, Sum, Percent etc')
 ,(15,'Piece','e.g roll, box, pallet')
 ,(16,'Periodicity','E.g. Monthly, Quarterly, Annually etc.')
 ,(17,'Weight','E.g Kilograms, grams, metric tonne, imperial ton etc')
) as Source ([unit_of_measure_type_id],[unit_of_measure_type_name],[narrative])
on (Target.[unit_of_measure_type_id] = Source.[unit_of_measure_type_id])
when matched and (
	nullif(Source.[unit_of_measure_type_name], Target.[unit_of_measure_type_name]) is not null or nullif(Target.[unit_of_measure_type_name], Source.[unit_of_measure_type_name]) is not null or 
	nullif(Source.[narrative], Target.[narrative]) is not null or nullif(Target.[narrative], Source.[narrative]) is not null) then
 update set
  [unit_of_measure_type_name] = Source.[unit_of_measure_type_name], 
  [narrative] = Source.[narrative]
when not matched by target then
 insert([unit_of_measure_type_id],[unit_of_measure_type_name],[narrative])
 values(Source.[unit_of_measure_type_id],Source.[unit_of_measure_type_name],Source.[narrative])
when not matched by source then 
 delete
;
go
declare @mergeError int
 , @mergeCount int
select @mergeError = @@error, @mergeCount = @@rowcount
if @mergeError != 0
 begin
 print 'ERROR OCCURRED IN MERGE FOR [dbo].[unit_of_measure_type]. Rows affected: ' + cast(@mergeCount as varchar(100)); -- SQL should always return zero rows affected
 end
else
 begin
 print '[dbo].[unit_of_measure_type] rows affected by MERGE: ' + cast(@mergeCount as varchar(100));
 end
go

set nocount off
go
