--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[TsaToPsaLoadControlTable] ON

MERGE INTO [dbo].[TsaToPsaLoadControlTable] AS Target
USING (VALUES
  (2,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_EKPO','BMI_BI_DW','psa','ics_stg_SAP_GBR_EKPO','Full',100101,'EBELP,EBELN','EBELP,EBELN',0)
 ,(3,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_EKBZ','BMI_BI_DW','psa','ics_stg_SAP_SVK_EKBZ','Full',100101,'ZAEHK,EBELN,BUZEI,BELNR','ZAEHK,EBELN,BUZEI,BELNR',0)
 ,(5,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur034610','BMI_BI_DW','psa','ics_stg_baan_ttdpur034610','Full',100142,'t_suno,t_dile,t_cpgp','t_suno,t_dile,t_cpgp',0)
 ,(8,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_ADRC','BMI_BI_DW','psa','ics_stg_SAP_GBR_ADRC','Full',100101,'DATE_FROM,ADDRNUMBER','DATE_FROM,ADDRNUMBER',0)
 ,(9,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_EKET','BMI_BI_DW','psa','ics_stg_SAP_SVK_EKET','Full',100101,'ETENR,EBELP,EBELN','ETENR,EBELP,EBELN',0)
 ,(11,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur035610','BMI_BI_DW','psa','ics_stg_baan_ttdpur035610','Full',100142,'t_dile,t_cplp,t_cpgp','t_dile,t_cplp,t_cpgp',0)
 ,(13,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_MITMAS','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_MITMAS','Full',100141,'MMITNO,MMCONO','MMITNO,MMCONO',0)
 ,(14,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_CCURRA','BMI_BI_DW','psa','ics_stg_m3_CCURRA','Full',100144,'CUCUTD,CUCRTP,CUCUCD,CUDIVI,CUCONO','CUCUTD,CUCRTP,CUCUCD,CUDIVI,CUCONO',0)
 ,(15,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_LFB1','BMI_BI_DW','psa','ics_stg_SAP_SVK_LFB1','Full',100101,'LIFNR,BUKRS','LIFNR,BUKRS',0)
 ,(16,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_MITTRA','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_MITTRA','Full',100141,'MTWHLO,MTTMSX,MTRGTM,MTRGDT,MTITNO,MTCONO','MTWHLO,MTTMSX,MTRGTM,MTRGDT,MTITNO,MTCONO',0)
 ,(17,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur036610','BMI_BI_DW','psa','ics_stg_baan_ttdpur036610','Full',100142,'t_suno,t_item,t_dile,t_cntr','t_suno,t_item,t_dile,t_cntr',0)
 ,(19,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_MITWHL','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_MITWHL','Full',100141,'MWWHLO,MWCONO','MWWHLO,MWCONO',0)
 ,(20,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_EKKO','BMI_BI_DW','psa','ics_stg_SAP_SVK_EKKO','Full',100101,'EBELN','EBELN',0)
 ,(22,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_CSYTAB','BMI_BI_DW','psa','ics_stg_m3_CSYTAB','Full',100144,'CTLNCD,CTSTKY,CTSTCO,CTDIVI,CTCONO','CTLNCD,CTSTKY,CTSTCO,CTDIVI,CTCONO',0)
 ,(23,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur037610','BMI_BI_DW','psa','ics_stg_baan_ttdpur037610','Full',100142,'t_item,t_dile,t_cplp,t_cntr','t_item,t_dile,t_cplp,t_cntr',0)
 ,(25,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MILOMA','BMI_BI_DW','psa','ics_stg_m3_MILOMA','Full',100144,'LMBANO,LMITNO','LMBANO,LMITNO',0)
 ,(26,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_MPLIND','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_MPLIND','Full',100141,'ICPUNO,ICPNLX,ICPNLS,ICPNLI,ICCONO','ICPUNO,ICPNLX,ICPNLS,ICPNLI,ICCONO',0)
 ,(27,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MITAUN','BMI_BI_DW','psa','ics_stg_m3_MITAUN','Full',100144,'MUALUN,MUAUTP,MUITNO','MUALUN,MUAUTP,MUITNO',0)
 ,(28,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_LFA1','BMI_BI_DW','psa','ics_stg_SAP_SVK_LFA1','Full',100101,'MANDT,LIFNR','MANDT,LIFNR',0)
 ,(29,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_MPLINE','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_MPLINE','Full',100141,'IBPUNO,IBPNLS,IBPNLI,IBCONO','IBPUNO,IBPNLS,IBPNLI,IBCONO',0)
 ,(30,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MITBAL','BMI_BI_DW','psa','ics_stg_m3_MITBAL','Full',100144,'MBITNO,MBWHLO,MBCONO','MBITNO,MBWHLO,MBCONO',0)
 ,(31,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur042610','BMI_BI_DW','psa','ics_stg_baan_ttdpur042610','Full',100142,'t_pono,t_orno,t_ckor','t_pono,t_orno,t_ckor',0)
 ,(33,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MITFAC','BMI_BI_DW','psa','ics_stg_m3_MITFAC','Full',100144,'M9ITNO,M9FACI,M9CONO','M9ITNO,M9FACI,M9CONO',0)
 ,(35,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MITLOC','BMI_BI_DW','psa','ics_stg_m3_MITLOC','Full',100144,'MLREPN,MLCAMU,MLBANO,MLWHSL,MLITNO,MLWHLO,MLCONO','MLREPN,MLCAMU,MLBANO,MLWHSL,MLITNO,MLWHLO,MLCONO',0)
 ,(36,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_MARA','BMI_BI_DW','psa','ics_stg_SAP_SVK_MARA','Full',100101,'MATNR','MATNR',0)
 ,(38,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MITMAS','BMI_BI_DW','psa','ics_stg_m3_MITMAS','Full',100144,'MMITNO,MMCONO','MMITNO,MMCONO',0)
 ,(39,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur040610','BMI_BI_DW','psa','ics_stg_baan_ttdpur040610','Full',100142,'t_orno','t_orno',0)
 ,(41,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MITPOP','BMI_BI_DW','psa','ics_stg_m3_MITPOP','Full',100144,'MPVFDT,MPE0PA,MPPOPN,MPITNO,MPALWT,MPCONO','MPVFDT,MPE0PA,MPPOPN,MPITNO,MPALWT,MPCONO',0)
 ,(43,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_MARM','BMI_BI_DW','psa','ics_stg_SAP_SVK_MARM','Full',100101,'MEINH,MATNR','MEINH,MATNR',0)
 ,(45,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_movex_FGINLI','BMI_BI_DW','psa','ics_stg_movex_FGINLI','Full',100146,'F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI','F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI',0)
 ,(46,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_OCHCUS','BMI_BI_DW','psa','ics_stg_m3_OCHCUS','Full',100144,'OSFVDT,OSCHCT,OSCUNO,OSCONO','OSFVDT,OSCHCT,OSCUNO,OSCONO',0)
 ,(47,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur041610','BMI_BI_DW','psa','ics_stg_baan_ttdpur041610','Full',100142,'t_pono,t_orno','t_pono,t_orno',0)
 ,(49,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_OCUSMA','BMI_BI_DW','psa','ics_stg_m3_OCUSMA','Full',100144,'OKCUNO,OKCONO','OKCUNO,OKCONO',0)
 ,(51,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_OINVOH','BMI_BI_DW','psa','ics_stg_m3_OINVOH','Full',100144,'UHIVNO,UHDIVI,UHCONO','UHIVNO,UHDIVI,UHCONO',0)
 ,(52,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_T001W','BMI_BI_DW','psa','ics_stg_SAP_SVK_T001W','Full',100101,'WERKS,MANDT','WERKS,MANDT',0)
 ,(54,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_movex_MPLIND','BMI_BI_DW','psa','ics_stg_movex_MPLIND','Full',100146,'ICSUDO,ICREPN,ICPUNO,ICPNLX,ICPNLS,ICPNLI','ICSUDO,ICREPN,ICPUNO,ICPNLX,ICPNLS,ICPNLI',0)
 ,(55,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_OINVOL','BMI_BI_DW','psa','ics_stg_m3_OINVOL','Full',100144,'ONINPX,ONIVRF,ONWHLO,ONDLIX,ONORNO,ONIVTP,ONIVSQ,ONYEA4,ONIVNO,ONDIVI,ONCONO','ONINPX,ONIVRF,ONWHLO,ONDLIX,ONORNO,ONIVTP,ONIVSQ,ONYEA4,ONIVNO,ONDIVI,ONCONO',0)
 ,(56,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur043610','BMI_BI_DW','psa','ics_stg_baan_ttdpur043610','Full',100142,'t_logn','t_logn',0)
 ,(57,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_OCUSMA','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_OCUSMA','Full',100141,'OKCUNO,OKCONO','OKCUNO,OKCONO',0)
 ,(58,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_OOHEAD','BMI_BI_DW','psa','ics_stg_m3_OOHEAD','Full',100144,'OAORNO,OACONO','OAORNO,OACONO',0)
 ,(59,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_ODHEAD','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_ODHEAD','Full',100141,'UAWHLO,UAORNO,UADLIX,UACONO','UAWHLO,UAORNO,UADLIX,UACONO',0)
 ,(60,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_OOLINE','BMI_BI_DW','psa','ics_stg_m3_OOLINE','Full',100144,'OBPONR,OBORNO,OBCONO','OBPONR,OBORNO,OBCONO',0)
 ,(61,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_ODLINE','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_ODLINE','Full',100141,'UBWHLO,UBPOSX,UBPONR,UBORNO,UBDLIX,UBCONO','UBWHLO,UBPOSX,UBPONR,UBORNO,UBDLIX,UBCONO',0)
 ,(62,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_movex_MPLINE','BMI_BI_DW','psa','ics_stg_movex_MPLINE','Full',100146,'IBPUNO,IBPNLS,IBPNLI,IBCONO','IBPUNO,IBPNLS,IBPNLI,IBCONO',0)
 ,(63,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_OSBSTD','BMI_BI_DW','psa','ics_stg_m3_OSBSTD','Full',100144,'UCORIG,UCWHLO,UCPONR,UCDLIX,UCORNO,UCDIVI,UCCONO','UCORIG,UCWHLO,UCPONR,UCDLIX,UCORNO,UCDIVI,UCCONO',0)
 ,(64,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur045610','BMI_BI_DW','psa','ics_stg_baan_ttdpur045610','Full',100142,'t_srnb,t_pono,t_orno','t_srnb,t_pono,t_orno',0)
 ,(66,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_CCURRA','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_CCURRA','Full',100113,'CUDIVI,CUCUTD,CUCUCD,CUCRTP,CUCONO','CUDIVI,CUCUTD,CUCUCD,CUCRTP,CUCONO',0)
 ,(69,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_OOHEAD','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_OOHEAD','Full',100141,'OAORNO,OACONO','OAORNO,OACONO',0)
 ,(70,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_FGINLI','BMI_BI_DW','psa','ics_stg_m3_FGINLI','Full',100144,'F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI','F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI',0)
 ,(72,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur046610','BMI_BI_DW','psa','ics_stg_baan_ttdpur046610','Full',100142,'t_suno,t_srni,t_srnb,t_pono,t_orno','t_suno,t_srni,t_srnb,t_pono,t_orno',0)
 ,(73,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_OOLINE','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_OOLINE','Full',100141,'OBPOSX,OBPONR,OBORNO,OBCONO','OBPOSX,OBPONR,OBORNO,OBCONO',0)
 ,(78,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_FPLEDG','BMI_BI_DW','psa','ics_stg_m3_FPLEDG','Full',100144,'EPYEA4,EPJSNO,EPJRNO,EPDIVI','EPYEA4,EPJSNO,EPJRNO,EPDIVI',0)
 ,(80,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur047610','BMI_BI_DW','psa','ics_stg_baan_ttdpur047610','Full',100142,'t_pono,t_ponb,t_orno','t_pono,t_ponb,t_orno',0)
 ,(82,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_CSYTAB','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_CSYTAB','Full',100113,'CTSTKY,CTSTCO,CTLNCD,CTDIVI,CTCONO','CTSTKY,CTSTCO,CTLNCD,CTDIVI,CTCONO',0)
 ,(83,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_CCURRA','BMI_BI_DW','psa','ics_stg_m3v7_CCURRA','Full',100145,'CUCUTD,CUCRTP,CUCUCD,CUDIVI,CUCONO','CUCUTD,CUCRTP,CUCUCD,CUDIVI,CUCONO',0)
 ,(112,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_OCHCUS','BMI_BI_DW','psa','ics_stg_m3v7_OCHCUS','Full',100145,'OSFVDT,OSCUNO,OSCONO','OSFVDT,OSCUNO,OSCONO',0)
 ,(85,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MPLIND','BMI_BI_DW','psa','ics_stg_m3_MPLIND','Full',100144,'ICSUDO,ICREPN,ICPUNO,ICPNLX,ICPNLS,ICPNLI','ICSUDO,ICREPN,ICPUNO,ICPNLX,ICPNLS,ICPNLI',0)
 ,(86,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_FGINLI','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_FGINLI','Full',100113,'F5SUNO,F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI,F5INYR,F5INLP,F5DIVI,F5CONO','F5SUNO,F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI,F5INYR,F5INLP,F5DIVI,F5CONO',0)
 ,(87,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur048610','BMI_BI_DW','psa','ics_stg_baan_ttdpur048610','Full',100142,'t_pono,t_orno','t_pono,t_orno',0)
 ,(89,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_CSYTAB','BMI_BI_DW','psa','ics_stg_m3v7_CSYTAB','Full',100145,'CTLNCD,CTSTKY,CTSTCO,CTDIVI,CTCONO','CTLNCD,CTSTKY,CTSTCO,CTDIVI,CTCONO',0)
 ,(90,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_FPLEDG','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_FPLEDG','Full',100113,'EPYEA4,EPJSNO,EPJRNO,EPDIVI,EPCONO','EPYEA4,EPJSNO,EPJRNO,EPDIVI,EPCONO',0)
 ,(91,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MILOMA','BMI_BI_DW','psa','ics_stg_m3v7_MILOMA','Full',100145,'LMBANO,LMITNO','LMBANO,LMITNO',0)
 ,(92,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MPLINE','BMI_BI_DW','psa','ics_stg_m3_MPLINE','Full',100144,'IBPUNO,IBPNLS,IBPNLI,IBFACI','IBPUNO,IBPNLS,IBPNLI,IBFACI',0)
 ,(94,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur053610','BMI_BI_DW','psa','ics_stg_baan_ttdpur053610','Full',100142,'t_orno,t_cosn','t_orno,t_cosn',0)
 ,(95,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MITAUN','BMI_BI_DW','psa','ics_stg_m3v7_MITAUN','Full',100145,'MUALUN,MUAUTP,MUITNO','MUALUN,MUAUTP,MUITNO',0)
 ,(97,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MITBAL','BMI_BI_DW','psa','ics_stg_m3v7_MITBAL','Full',100145,'MBITNO,MBWHLO,MBCONO','MBITNO,MBWHLO,MBCONO',0)
 ,(99,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MITFAC','BMI_BI_DW','psa','ics_stg_m3v7_MITFAC','Full',100145,'M9ITNO,M9FACI,M9CONO','M9ITNO,M9FACI,M9CONO',0)
 ,(100,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_FGINLI','BMI_BI_DW','psa','ics_stg_m3v7_FGINLI','Full',100145,'F5SUNO,F5SINO,F5REPN,F5PUNO,F5PNLS,F5PNLI,F5CONO','F5SUNO,F5SINO,F5REPN,F5PUNO,F5PNLS,F5PNLI,F5CONO',0)
 ,(102,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur050610','BMI_BI_DW','psa','ics_stg_baan_ttdpur050610','Full',100142,'t_trtm,t_trdt,t_orno','t_trtm,t_trdt,t_orno',0)
 ,(103,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MITLOC','BMI_BI_DW','psa','ics_stg_m3v7_MITLOC','Full',100145,'MLREPN,MLBANO,MLWHSL,MLITNO,MLWHLO,MLCONO','MLREPN,MLBANO,MLWHSL,MLITNO,MLWHLO,MLCONO',0)
 ,(105,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MITMAS','BMI_BI_DW','psa','ics_stg_m3v7_MITMAS','Full',100145,'MMITNO,MMCONO','MMITNO,MMCONO',0)
 ,(107,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MITPOP','BMI_BI_DW','psa','ics_stg_m3v7_MITPOP','Full',100145,'MPE0PA,MPPOPN,MPITNO,MPCONO','MPE0PA,MPPOPN,MPITNO,MPCONO',0)
 ,(108,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_FPLEDG','BMI_BI_DW','psa','ics_stg_m3v7_FPLEDG','Full',100145,'EPYEA4,EPJSNO,EPJRNO,EPDIVI','EPYEA4,EPJSNO,EPJRNO,EPDIVI',0)
 ,(110,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur051610','BMI_BI_DW','psa','ics_stg_baan_ttdpur051610','Full',100142,'t_trtm,t_trdt,t_sern,t_pono,t_orno,t_ckor','t_trtm,t_trdt,t_sern,t_pono,t_orno,t_ckor',0)
 ,(114,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_OCUSMA','BMI_BI_DW','psa','ics_stg_m3v7_OCUSMA','Full',100145,'OKCUNO,OKCONO','OKCUNO,OKCONO',0)
 ,(115,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MPLIND','BMI_BI_DW','psa','ics_stg_m3v7_MPLIND','Full',100145,'ICSUDO,ICREPN,ICPUNO,ICPNLX,ICPNLS,ICPNLI','ICSUDO,ICREPN,ICPUNO,ICPNLX,ICPNLS,ICPNLI',0)
 ,(116,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_MITMAS','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_MITMAS','Full',100113,'MMITNO,MMCONO','MMITNO,MMCONO',0)
 ,(117,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur054610','BMI_BI_DW','psa','ics_stg_baan_ttdpur054610','Full',100142,'t_pono,t_orno','t_pono,t_orno',0)
 ,(118,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_OINVOH','BMI_BI_DW','psa','ics_stg_m3v7_OINVOH','Full',100145,'UHIVNO,UHCONO','UHIVNO,UHCONO',0)
 ,(119,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_MITTRA','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_MITTRA','Full',100113,'MTWHLO,MTTMSX,MTRGTM,MTRGDT,MTITNO,MTCONO','MTWHLO,MTTMSX,MTRGTM,MTRGDT,MTITNO,MTCONO',0)
 ,(120,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_OINVOL','BMI_BI_DW','psa','ics_stg_m3v7_OINVOL','Full',100145,'ONIVRF,ONWHLO,ONDLIX,ONORNO,ONIVTP,ONIVSQ,ONYEA4,ONIVNO,ONDIVI,ONCONO','ONIVRF,ONWHLO,ONDLIX,ONORNO,ONIVTP,ONIVSQ,ONYEA4,ONIVNO,ONDIVI,ONCONO',0)
 ,(122,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_OOHEAD','BMI_BI_DW','psa','ics_stg_m3v7_OOHEAD','Full',100145,'OAORNO,OACONO','OAORNO,OACONO',0)
 ,(123,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MPLINE','BMI_BI_DW','psa','ics_stg_m3v7_MPLINE','Full',100145,'IBPUNO,IBPNLS,IBPNLI,IBFACI','IBPUNO,IBPNLS,IBPNLI,IBFACI',0)
 ,(124,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_MITWHL','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_MITWHL','Full',100113,'MWWHLO,MWCONO','MWWHLO,MWCONO',0)
 ,(125,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur061610','BMI_BI_DW','psa','ics_stg_baan_ttdpur061610','Full',100142,'t_year,t_suno,t_item,t_citg','t_year,t_suno,t_item,t_citg',0)
 ,(126,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_OOLINE','BMI_BI_DW','psa','ics_stg_m3v7_OOLINE','Full',100145,'OBPONR,OBORNO,OBCONO','OBPONR,OBORNO,OBCONO',0)
 ,(128,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_OSBSTD','BMI_BI_DW','psa','ics_stg_m3v7_OSBSTD','Full',100145,'UCWHLO,UCPONR,UCDLIX,UCORNO,UCDIVI,UCCONO','UCWHLO,UCPONR,UCDLIX,UCORNO,UCDIVI,UCCONO',0)
 ,(131,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_movex_FPLEDG','BMI_BI_DW','psa','ics_stg_movex_FPLEDG','Full',100146,'EPYEA4,EPJSNO,EPJRNO,EPDIVI','EPYEA4,EPJSNO,EPJRNO,EPDIVI',0)
 ,(132,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_MPLIND','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_MPLIND','Full',100113,'ICPUNO,ICPNLX,ICPNLS,ICPNLI,ICCONO','ICPUNO,ICPNLX,ICPNLS,ICPNLI,ICCONO',0)
 ,(133,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur080610','BMI_BI_DW','psa','ics_stg_baan_ttdpur080610','Full',100142,'t_pono,t_orno,t_item,t_cntr','t_pono,t_orno,t_item,t_cntr',0)
 ,(134,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_movex_CSYTAB','BMI_BI_DW','psa','ics_stg_movex_CSYTAB','Full',100146,'CTLNCD,CTSTKY,CTSTCO,CTDIVI,CTCONO','CTLNCD,CTSTKY,CTSTCO,CTDIVI,CTCONO',0)
 ,(135,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_MPLINE','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_MPLINE','Full',100113,'IBPUNO,IBPNLS,IBPNLI,IBCONO','IBPUNO,IBPNLS,IBPNLI,IBCONO',0)
 ,(140,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur081610','BMI_BI_DW','psa','ics_stg_baan_ttdpur081610','Full',100142,'t_orno,t_item,t_cntr','t_orno,t_item,t_cntr',0)
 ,(147,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur082610','BMI_BI_DW','psa','ics_stg_baan_ttdpur082610','Full',100142,'t_orno,t_cpgp','t_orno,t_cpgp',0)
 ,(148,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_movex_MITMAS','BMI_BI_DW','psa','ics_stg_movex_MITMAS','Full',100146,'MMITNO,MMCONO','MMITNO,MMCONO',0)
 ,(154,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur302610','BMI_BI_DW','psa','ics_stg_baan_ttdpur302610','Full',100142,'t_pono,t_ddta,t_cono','t_pono,t_ddta,t_cono',0)
 ,(158,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_OCUSMA','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_OCUSMA','Full',100113,'OKCUNO,OKCONO','OKCUNO,OKCONO',0)
 ,(160,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_ODHEAD','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_ODHEAD','Full',100113,'UAWHLO,UAORNO,UADLIX,UACONO','UAWHLO,UAORNO,UADLIX,UACONO',0)
 ,(161,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur300610','BMI_BI_DW','psa','ics_stg_baan_ttdpur300610','Full',100142,'t_cono','t_cono',0)
 ,(163,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_ODLINE','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_ODLINE','Full',100113,'UBWHLO,UBPOSX,UBPONR,UBORNO,UBDLIX,UBCONO','UBWHLO,UBPOSX,UBPONR,UBORNO,UBDLIX,UBCONO',0)
 ,(168,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur301610','BMI_BI_DW','psa','ics_stg_baan_ttdpur301610','Full',100142,'t_pono,t_cono','t_pono,t_cono',0)
 ,(169,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_OOHEAD','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_OOHEAD','Full',100113,'OAORNO,OACONO','OAORNO,OACONO',0)
 ,(170,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10gen_POL_OOLINE','BMI_BI_DW','psa','ics_stg_M3V10gen_POL_OOLINE','Full',100113,'OBPOSX,OBPONR,OBORNO,OBCONO','OBPOSX,OBPONR,OBORNO,OBCONO',0)
 ,(172,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur303610','BMI_BI_DW','psa','ics_stg_baan_ttdpur303610','Full',100142,'t_cono,t_ckor','t_cono,t_ckor',0)
 ,(175,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_CCURRA','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_CCURRA','Full',100140,'CUDIVI,CUCUTD,CUCUCD,CUCRTP,CUCONO','CUDIVI,CUCUTD,CUCUCD,CUCRTP,CUCONO',0)
 ,(176,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur305610','BMI_BI_DW','psa','ics_stg_baan_ttdpur305610','Full',100142,'t_trtm,t_trdt,t_cono','t_trtm,t_trdt,t_cono',0)
 ,(180,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur306610','BMI_BI_DW','psa','ics_stg_baan_ttdpur306610','Full',100142,'t_trtm,t_trdt,t_sern,t_pono,t_cono,t_comp','t_trtm,t_trdt,t_sern,t_pono,t_cono,t_comp',0)
 ,(181,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_MAKT','BMI_BI_DW','psa','ics_stg_SAP_GBR_MAKT','Full',100101,'SPRAS,MATNR','SPRAS,MATNR',0)
 ,(183,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_MARA','BMI_BI_DW','psa','ics_stg_SAP_GBR_MARA','Full',100101,'MATNR','MATNR',0)
 ,(185,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_MARD','BMI_BI_DW','psa','ics_stg_SAP_GBR_MARD','Full',100101,'WERKS,MATNR,LGORT','WERKS,MATNR,LGORT',0)
 ,(273,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_MITWHL','BMI_BI_DW','psa','ics_stg_m3v7_MITWHL','Full',100145,'MWWHLO,MWCONO','MWWHLO,MWCONO',0)
 ,(186,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_CSYTAB','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_CSYTAB','Full',100140,'CTSTKY,CTSTCO,CTLNCD,CTDIVI,CTCONO','CTSTKY,CTSTCO,CTLNCD,CTDIVI,CTCONO',0)
 ,(187,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur310610','BMI_BI_DW','psa','ics_stg_baan_ttdpur310610','Full',100142,'t_upid,t_pono,t_cono','t_upid,t_pono,t_cono',0)
 ,(189,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_MBEW','BMI_BI_DW','psa','ics_stg_SAP_GBR_MBEW','Full',100101,'BWKEY,MATNR','BWKEY,MATNR',0)
 ,(190,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_FGINLI','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_FGINLI','Full',100140,'F5SUNO,F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI,F5INYR,F5INLP,F5DIVI,F5CONO','F5SUNO,F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI,F5INYR,F5INLP,F5DIVI,F5CONO',0)
 ,(191,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_T001L','BMI_BI_DW','psa','ics_stg_SAP_GBR_T001L','Full',100101,'LGORT,WERKS,MANDT','LGORT,WERKS,MANDT',0)
 ,(193,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur332610','BMI_BI_DW','psa','ics_stg_baan_ttdpur332610','Full',100142,'t_stdt,t_qanp,t_pono,t_dile,t_cono','t_stdt,t_qanp,t_pono,t_dile,t_cono',0)
 ,(194,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_T001W','BMI_BI_DW','psa','ics_stg_SAP_GBR_T001W','Full',100101,'WERKS','WERKS',0)
 ,(195,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_FPLEDG','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_FPLEDG','Full',100140,'EPYEA4,EPJSNO,EPJRNO,EPDIVI,EPCONO','EPYEA4,EPJSNO,EPJRNO,EPDIVI,EPCONO',0)
 ,(198,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur333610','BMI_BI_DW','psa','ics_stg_baan_ttdpur333610','Full',100142,'t_stdt,t_qanp,t_pono,t_dile,t_cono','t_stdt,t_qanp,t_pono,t_dile,t_cono',0)
 ,(202,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur335610','BMI_BI_DW','psa','ics_stg_baan_ttdpur335610','Full',100142,'t_pono,t_dile,t_cono','t_pono,t_dile,t_cono',0)
 ,(207,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur336610','BMI_BI_DW','psa','ics_stg_baan_ttdpur336610','Full',100142,'t_pono,t_dile,t_cono','t_pono,t_dile,t_cono',0)
 ,(209,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_MITMAS','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_MITMAS','Full',100140,'MMITNO,MMCONO','MMITNO,MMCONO',0)
 ,(210,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_MITTRA','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_MITTRA','Full',100140,'MTWHLO,MTTMSX,MTRGTM,MTRGDT,MTITNO,MTCONO','MTWHLO,MTTMSX,MTRGTM,MTRGDT,MTITNO,MTCONO',0)
 ,(211,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur400610','BMI_BI_DW','psa','ics_stg_baan_ttdpur400610','Full',100142,'t_suno,t_pono,t_orno,t_dino','t_suno,t_pono,t_orno,t_dino',0)
 ,(213,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_MITWHL','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_MITWHL','Full',100140,'MWWHLO,MWCONO','MWWHLO,MWCONO',0)
 ,(214,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur000610','BMI_BI_DW','psa','ics_stg_baan_ttdpur000610','Full',100142,'t_sern','t_sern',0)
 ,(216,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur401610','BMI_BI_DW','psa','ics_stg_baan_ttdpur401610','Full',100142,'t_suno,t_serb,t_sera,t_pono,t_orno,t_dino','t_suno,t_serb,t_sera,t_pono,t_orno,t_dino',0)
 ,(218,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_MPLIND','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_MPLIND','Full',100140,'ICPUNO,ICPNLX,ICPNLS,ICPNLI,ICCONO','ICPUNO,ICPNLX,ICPNLS,ICPNLI,ICCONO',0)
 ,(219,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur001610','BMI_BI_DW','psa','ics_stg_baan_ttdpur001610','Full',100142,'t_qono','t_qono',0)
 ,(220,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_MPLINE','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_MPLINE','Full',100140,'IBPUNO,IBPNLS,IBPNLI,IBCONO','IBPUNO,IBPNLS,IBPNLI,IBCONO',0)
 ,(221,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur703610','BMI_BI_DW','psa','ics_stg_baan_ttdpur703610','Full',100142,'t_pono,t_orno','t_pono,t_orno',0)
 ,(223,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_EKBZ','BMI_BI_DW','psa','ics_stg_SAP_GBR_EKBZ','Full',100101,'BUZEI,BELNR,ZAEHK,EBELN','BUZEI,BELNR,ZAEHK,EBELN',0)
 ,(224,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_LFM1','BMI_BI_DW','psa','ics_stg_SAP_SVK_LFM1','Full',100101,'MANDT,LIFNR,EKORG','MANDT,LIFNR,EKORG',0)
 ,(226,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur020610','BMI_BI_DW','psa','ics_stg_baan_ttdpur020610','Full',100142,'t_suno,t_item,t_cntr','t_suno,t_item,t_cntr',0)
 ,(228,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur704610','BMI_BI_DW','psa','ics_stg_baan_ttdpur704610','Full',100142,'t_time,t_pono,t_orno,t_date','t_time,t_pono,t_orno,t_date',0)
 ,(230,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_TCURR','BMI_BI_DW','psa','ics_stg_SAP_GBR_TCURR','Full',100101,'GDATU,TCURR,FCURR,KURST,MANDT','GDATU,TCURR,FCURR,KURST,MANDT',0)
 ,(231,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_T052U','BMI_BI_DW','psa','ics_stg_SAP_SVK_T052U','Full',100101,'ZTERM,ZTAGG,SPRAS,MANDT','ZTERM,ZTAGG,SPRAS,MANDT',0)
 ,(233,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur021610','BMI_BI_DW','psa','ics_stg_baan_ttdpur021610','Full',100142,'t_suno,t_item','t_suno,t_item',0)
 ,(236,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_T052U','BMI_BI_DW','psa','ics_stg_SAP_GBR_T052U','Full',100101,'ZTAGG,ZTERM,SPRAS,MANDT','ZTAGG,ZTERM,SPRAS,MANDT',0)
 ,(238,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur002610','BMI_BI_DW','psa','ics_stg_baan_ttdpur002610','Full',100142,'t_qono,t_pono','t_qono,t_pono',0)
 ,(240,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_OCUSMA','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_OCUSMA','Full',100140,'OKCUNO,OKCONO','OKCUNO,OKCONO',0)
 ,(241,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_LFM1','BMI_BI_DW','psa','ics_stg_SAP_GBR_LFM1','Full',100101,'EKORG,LIFNR,MANDT','EKORG,LIFNR,MANDT',0)
 ,(242,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_ODHEAD','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_ODHEAD','Full',100140,'UAWHLO,UAORNO,UADLIX,UACONO','UAWHLO,UAORNO,UADLIX,UACONO',0)
 ,(243,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur010610','BMI_BI_DW','psa','ics_stg_baan_ttdpur010610','Full',100142,'t_trtm,t_trdt,t_qono','t_trtm,t_trdt,t_qono',0)
 ,(244,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_ODLINE','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_ODLINE','Full',100140,'UBWHLO,UBPOSX,UBPONR,UBORNO,UBDLIX,UBCONO','UBWHLO,UBPOSX,UBPONR,UBORNO,UBDLIX,UBCONO',0)
 ,(246,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_EKBE','BMI_BI_DW','psa','ics_stg_SAP_GBR_EKBE','Full',100101,'BUZEI,BELNR,GJAHR,VGABE,ZEKKN,EBELP,EBELN,MANDT','BUZEI,BELNR,GJAHR,VGABE,ZEKKN,EBELP,EBELN,MANDT',0)
 ,(248,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur027610','BMI_BI_DW','psa','ics_stg_baan_ttdpur027610','Full',100142,'t_suno,t_cplp','t_suno,t_cplp',0)
 ,(249,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_OOHEAD','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_OOHEAD','Full',100140,'OAORNO,OACONO','OAORNO,OACONO',0)
 ,(250,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10ved_POL_OOLINE','BMI_BI_DW','psa','ics_stg_M3V10ved_POL_OOLINE','Full',100140,'OBPOSX,OBPONR,OBORNO,OBCONO','OBPOSX,OBPONR,OBORNO,OBCONO',0)
 ,(251,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_MARM','BMI_BI_DW','psa','ics_stg_SAP_GBR_MARM','Full',100101,'MEINH,MATNR','MEINH,MATNR',0)
 ,(253,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur028610','BMI_BI_DW','psa','ics_stg_baan_ttdpur028610','Full',100142,'t_pono,t_ccos','t_pono,t_ccos',0)
 ,(255,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_CIDADR','BMI_BI_DW','psa','ics_stg_m3_CIDADR','Full',100144,'SASTDT,SAADID,SAADTE,SASUNO','SASTDT,SAADID,SAADTE,SASUNO',0)
 ,(257,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_LIKP','BMI_BI_DW','psa','ics_stg_SAP_GBR_LIKP','Full',100101,'VBELN','VBELN',0)
 ,(258,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_CIDMAS','BMI_BI_DW','psa','ics_stg_m3_CIDMAS','Full',100144,'IDSUNO','IDSUNO',0)
 ,(259,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_ADRC','BMI_BI_DW','psa','ics_stg_SAP_SVK_ADRC','Full',100101,'DATE_FROM,CLIENT,ADDRNUMBER','DATE_FROM,CLIENT,ADDRNUMBER',0)
 ,(260,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_CCURRA','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_CCURRA','Full',100141,'CUDIVI,CUCUTD,CUCUCD,CUCRTP,CUCONO','CUDIVI,CUCUTD,CUCUCD,CUCRTP,CUCONO',0)
 ,(261,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur011610','BMI_BI_DW','psa','ics_stg_baan_ttdpur011610','Full',100142,'t_trtm,t_trdt,t_sern,t_qono,t_pono','t_trtm,t_trdt,t_sern,t_qono,t_pono',0)
 ,(262,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_CMNDIV','BMI_BI_DW','psa','ics_stg_m3_CMNDIV','Full',100144,'CCDIVI,CCCONO','CCDIVI,CCCONO',0)
 ,(264,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3_MITWHL','BMI_BI_DW','psa','ics_stg_m3_MITWHL','Full',100144,'MWWHLO,MWCONO','MWWHLO,MWCONO',0)
 ,(266,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_LFB1','BMI_BI_DW','psa','ics_stg_SAP_GBR_LFB1','Full',100101,'LIFNR,BUKRS','LIFNR,BUKRS',0)
 ,(267,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_CIDADR','BMI_BI_DW','psa','ics_stg_m3v7_CIDADR','Full',100145,'SASTDT,SAADID,SAADTE,SASUNO','SASTDT,SAADID,SAADTE,SASUNO',0)
 ,(268,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_EKPO','BMI_BI_DW','psa','ics_stg_SAP_SVK_EKPO','Full',100101,'EBELP,EBELN','EBELP,EBELN',0)
 ,(270,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur030610','BMI_BI_DW','psa','ics_stg_baan_ttdpur030610','Full',100142,'t_suno,t_stdt,t_qanp,t_item,t_dile,t_cntr','t_suno,t_stdt,t_qanp,t_item,t_dile,t_cntr',0)
 ,(271,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_m3v7_CIDMAS','BMI_BI_DW','psa','ics_stg_m3v7_CIDMAS','Full',100145,'IDSUNO','IDSUNO',0)
 ,(275,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_LFA1','BMI_BI_DW','psa','ics_stg_SAP_GBR_LFA1','Full',100101,'LIFNR','LIFNR',0)
 ,(276,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_MAKT','BMI_BI_DW','psa','ics_stg_SAP_SVK_MAKT','Full',100101,'SPRAS,MATNR','SPRAS,MATNR',0)
 ,(277,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_CSYTAB','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_CSYTAB','Full',100141,'CTSTKY,CTSTCO,CTLNCD,CTDIVI,CTCONO','CTSTKY,CTSTCO,CTLNCD,CTDIVI,CTCONO',0)
 ,(278,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur031610','BMI_BI_DW','psa','ics_stg_baan_ttdpur031610','Full',100142,'t_suno,t_stdt,t_qanp,t_dile,t_cpgp','t_suno,t_stdt,t_qanp,t_dile,t_cpgp',0)
 ,(280,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_FGINLI','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_FGINLI','Full',100141,'F5SUNO,F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI,F5INYR,F5INLP,F5DIVI,F5CONO','F5SUNO,F5SINO,F5REPN,F5RELP,F5PUNO,F5PNLS,F5PNLI,F5INYR,F5INLP,F5DIVI,F5CONO',0)
 ,(281,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_EKET','BMI_BI_DW','psa','ics_stg_SAP_GBR_EKET','Full',100101,'ETENR,EBELP,EBELN','ETENR,EBELP,EBELN',0)
 ,(282,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_TCURR','BMI_BI_DW','psa','ics_stg_SAP_SVK_TCURR','Full',100101,'TCURR,MANDT,KURST,GDATU,FCURR','TCURR,MANDT,KURST,GDATU,FCURR',0)
 ,(284,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur032610','BMI_BI_DW','psa','ics_stg_baan_ttdpur032610','Full',100142,'t_stdt,t_qanp,t_item,t_dile,t_cplp,t_cntr','t_stdt,t_qanp,t_item,t_dile,t_cplp,t_cntr',0)
 ,(285,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_M3V10vil_POL_FPLEDG','BMI_BI_DW','psa','ics_stg_M3V10vil_POL_FPLEDG','Full',100141,'EPYEA4,EPJSNO,EPJRNO,EPDIVI,EPCONO','EPYEA4,EPJSNO,EPJRNO,EPDIVI,EPCONO',0)
 ,(287,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_GBR_EKKO','BMI_BI_DW','psa','ics_stg_SAP_GBR_EKKO','Full',100101,'EBELN','EBELN',0)
 ,(288,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_SAP_SVK_EKBE','BMI_BI_DW','psa','ics_stg_SAP_SVK_EKBE','Full',100101,'ZEKKN,VGABE,MANDT,GJAHR,EBELP,EBELN,BUZEI,BELNR','ZEKKN,VGABE,MANDT,GJAHR,EBELP,EBELN,BUZEI,BELNR',0)
 ,(290,'2017-12-21T14:26:19.467','GROUPICOPAL\ukrna','BMI_BI_DW','tsa','ics_land_baan_ttdpur033610','BMI_BI_DW','psa','ics_stg_baan_ttdpur033610','Full',100142,'t_stdt,t_qanp,t_dile,t_cplp,t_cpgp','t_stdt,t_qanp,t_dile,t_cplp,t_cpgp',0)
 ,(1333,'2017-12-29T10:58:00.200','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Code','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Code','Full',100139,'Code','Code',0)
 ,(1334,'2017-12-29T10:58:00.210','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Std_Purchase_Line','BMI_BI_DW','psa','ics_stg_Navision_BGR_Std_Purchase_Line','Full',100139,'Standard Purchase Code,Line No_','Standard Purchase Code,Line No_',0)
 ,(1335,'2017-12-29T10:58:00.220','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Invoice_Header','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Invoice_Header','Full',100139,'No_','No_',0)
 ,(1336,'2017-12-29T10:58:00.230','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Invoice_Line','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Invoice_Line','Full',100139,'Document No_,Line No_','Document No_,Line No_',0)
 ,(1337,'2017-12-29T10:58:00.240','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_SalesPerson_Purchaser','BMI_BI_DW','psa','ics_stg_Navision_BGR_SalesPerson_Purchaser','Full',100139,'Code','Code',0)
 ,(1338,'2017-12-29T10:58:00.250','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Price','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Price','Full',100139,'Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity','Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity',0)
 ,(1339,'2017-12-29T10:58:00.267','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Header','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Header','Full',100139,'Document Type,No_','Document Type,No_',0)
 ,(1340,'2017-12-29T10:58:00.277','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Line','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Line','Full',100139,'Document Type,Document No_,Line No_','Document Type,Document No_,Line No_',0)
 ,(1341,'2017-12-29T10:58:00.287','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_PrePayment_Pct','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_PrePayment_Pct','Full',100139,'Item No_,Vendor No_,Starting Date','Item No_,Vendor No_,Starting Date',0)
 ,(1342,'2017-12-29T10:58:00.297','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Payables_Setup','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Payables_Setup','Full',100139,'Primary Key','Primary Key',0)
 ,(1343,'2017-12-29T10:58:00.303','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_BGR_Purchase_Line_Discount','BMI_BI_DW','psa','ics_stg_Navision_BGR_Purchase_Line_Discount','Full',100139,'Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity','Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity',0)
 ,(1344,'2017-12-29T10:58:00.320','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Line_Discount','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Line_Discount','Full',100138,'Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity','Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity',0)
 ,(1345,'2017-12-29T10:58:00.337','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Header','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Header','Full',100138,'Document Type,No_','Document Type,No_',0)
 ,(1346,'2017-12-29T10:58:00.350','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Line','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Line','Full',100138,'Document Type,Document No_,Line No_','Document Type,Document No_,Line No_',0)
 ,(1347,'2017-12-29T10:58:00.360','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Code','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Code','Full',100138,'Code','Code',0)
 ,(1348,'2017-12-29T10:58:00.373','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Std_Purchase_Line','BMI_BI_DW','psa','ics_stg_Navision_ROU_Std_Purchase_Line','Full',100138,'Standard Purchase Code,Line No_','Standard Purchase Code,Line No_',0)
 ,(1349,'2017-12-29T10:58:00.383','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_SalesPerson_Purchaser','BMI_BI_DW','psa','ics_stg_Navision_ROU_SalesPerson_Purchaser','Full',100138,'Code','Code',0)
 ,(1350,'2017-12-29T10:58:00.393','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Payables_Setup','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Payables_Setup','Full',100138,'Primary Key','Primary Key',0)
 ,(1351,'2017-12-29T10:58:00.403','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Invoice_Header','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Invoice_Header','Full',100138,'No_','No_',0)
 ,(1352,'2017-12-29T10:58:00.417','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Invoice_Line','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Invoice_Line','Full',100138,'Document No_,Line No_','Document No_,Line No_',0)
 ,(1353,'2017-12-29T10:58:00.430','GROUPICOPAL\ukmbs','BMI_BI_DW','tsa','ics_land_Navision_ROU_Purchase_Price','BMI_BI_DW','psa','ics_stg_Navision_ROU_Purchase_Price','Full',100138,'Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity','Item No_,Vendor No_,Starting Date,Currency Code,Variant Code,Unit of Measure Code,Minimum Quantity',0)
) AS Source ([ID],[CreatedDate],[CreatedBy],[SourceDB],[SourceSchema],[SourceTable],[TargetDB],[TargetSchema],[TargetTable],[LoadMode],[DataSourceKey],[SourcePK],[TargetPK],[Done])
ON (Target.[ID] = Source.[ID])
WHEN MATCHED AND (
	NULLIF(Source.[CreatedDate], Target.[CreatedDate]) IS NOT NULL OR NULLIF(Target.[CreatedDate], Source.[CreatedDate]) IS NOT NULL OR 
	NULLIF(Source.[CreatedBy], Target.[CreatedBy]) IS NOT NULL OR NULLIF(Target.[CreatedBy], Source.[CreatedBy]) IS NOT NULL OR 
	NULLIF(Source.[SourceDB], Target.[SourceDB]) IS NOT NULL OR NULLIF(Target.[SourceDB], Source.[SourceDB]) IS NOT NULL OR 
	NULLIF(Source.[SourceSchema], Target.[SourceSchema]) IS NOT NULL OR NULLIF(Target.[SourceSchema], Source.[SourceSchema]) IS NOT NULL OR 
	NULLIF(Source.[SourceTable], Target.[SourceTable]) IS NOT NULL OR NULLIF(Target.[SourceTable], Source.[SourceTable]) IS NOT NULL OR 
	NULLIF(Source.[TargetDB], Target.[TargetDB]) IS NOT NULL OR NULLIF(Target.[TargetDB], Source.[TargetDB]) IS NOT NULL OR 
	NULLIF(Source.[TargetSchema], Target.[TargetSchema]) IS NOT NULL OR NULLIF(Target.[TargetSchema], Source.[TargetSchema]) IS NOT NULL OR 
	NULLIF(Source.[TargetTable], Target.[TargetTable]) IS NOT NULL OR NULLIF(Target.[TargetTable], Source.[TargetTable]) IS NOT NULL OR 
	NULLIF(Source.[LoadMode], Target.[LoadMode]) IS NOT NULL OR NULLIF(Target.[LoadMode], Source.[LoadMode]) IS NOT NULL OR 
	NULLIF(Source.[DataSourceKey], Target.[DataSourceKey]) IS NOT NULL OR NULLIF(Target.[DataSourceKey], Source.[DataSourceKey]) IS NOT NULL OR 
	NULLIF(Source.[SourcePK], Target.[SourcePK]) IS NOT NULL OR NULLIF(Target.[SourcePK], Source.[SourcePK]) IS NOT NULL OR 
	NULLIF(Source.[TargetPK], Target.[TargetPK]) IS NOT NULL OR NULLIF(Target.[TargetPK], Source.[TargetPK]) IS NOT NULL OR 
	NULLIF(Source.[Done], Target.[Done]) IS NOT NULL OR NULLIF(Target.[Done], Source.[Done]) IS NOT NULL) THEN
 UPDATE SET
  [CreatedDate] = Source.[CreatedDate], 
  [CreatedBy] = Source.[CreatedBy], 
  [SourceDB] = Source.[SourceDB], 
  [SourceSchema] = Source.[SourceSchema], 
  [SourceTable] = Source.[SourceTable], 
  [TargetDB] = Source.[TargetDB], 
  [TargetSchema] = Source.[TargetSchema], 
  [TargetTable] = Source.[TargetTable], 
  [LoadMode] = Source.[LoadMode], 
  [DataSourceKey] = Source.[DataSourceKey], 
  [SourcePK] = Source.[SourcePK], 
  [TargetPK] = Source.[TargetPK], 
  [Done] = Source.[Done]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([ID],[CreatedDate],[CreatedBy],[SourceDB],[SourceSchema],[SourceTable],[TargetDB],[TargetSchema],[TargetTable],[LoadMode],[DataSourceKey],[SourcePK],[TargetPK],[Done])
 VALUES(Source.[ID],Source.[CreatedDate],Source.[CreatedBy],Source.[SourceDB],Source.[SourceSchema],Source.[SourceTable],Source.[TargetDB],Source.[TargetSchema],Source.[TargetTable],Source.[LoadMode],Source.[DataSourceKey],Source.[SourcePK],Source.[TargetPK],Source.[Done])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[TsaToPsaLoadControlTable]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[TsaToPsaLoadControlTable] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [dbo].[TsaToPsaLoadControlTable] OFF
GO
SET NOCOUNT OFF
GO