--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

set nocount on

merge into [stg].[SSIS_BUDGET_ProductCategoryGroupLookup] as Target
using (values
  (1000,'Flat Roofing Total','Flat Roofing',46257)
 ,(2000,'Pitched Roofing Tot','Pitched Roofing',46297)
 ,(3000,'Building Membranes Tot','Building Membranes',46317)
 ,(4000,'Civil Engineering Total','Civil Engineering',46346)
 ,(5000,'Products Total','Other',46357)
 ,(5500,'Not Exported to Qlikview','Not Exported to Qlikview',46377)
 ,(6000,'Installation Services','Installation Services',null)
 ,(8800,'Unmapped L2 Categories','UnMapped Items',46247)
 ,(9900,'Total','',null)
) as Source ([ProductCategoryGroupId],[ProductCategoryGroupName],[QlikViewCategoryLevel2Name],[QlikViewCategoryLevel2Id])
on (Target.[ProductCategoryGroupId] = Source.[ProductCategoryGroupId])
when matched and (
	nullif(Source.[ProductCategoryGroupName], Target.[ProductCategoryGroupName]) is not null or nullif(Target.[ProductCategoryGroupName], Source.[ProductCategoryGroupName]) is not null or 
	nullif(Source.[QlikViewCategoryLevel2Name], Target.[QlikViewCategoryLevel2Name]) is not null or nullif(Target.[QlikViewCategoryLevel2Name], Source.[QlikViewCategoryLevel2Name]) is not null or 
	nullif(Source.[QlikViewCategoryLevel2Id], Target.[QlikViewCategoryLevel2Id]) is not null or nullif(Target.[QlikViewCategoryLevel2Id], Source.[QlikViewCategoryLevel2Id]) is not null) then
 update set
  [ProductCategoryGroupName] = Source.[ProductCategoryGroupName], 
  [QlikViewCategoryLevel2Name] = Source.[QlikViewCategoryLevel2Name], 
  [QlikViewCategoryLevel2Id] = Source.[QlikViewCategoryLevel2Id]
when not matched by target then
 insert([ProductCategoryGroupId],[ProductCategoryGroupName],[QlikViewCategoryLevel2Name],[QlikViewCategoryLevel2Id])
 values(Source.[ProductCategoryGroupId],Source.[ProductCategoryGroupName],Source.[QlikViewCategoryLevel2Name],Source.[QlikViewCategoryLevel2Id])
when not matched by source then 
 delete
;
go
declare @mergeError int
 , @mergeCount int
select @mergeError = @@error, @mergeCount = @@rowcount
if @mergeError != 0
 begin
 print 'ERROR OCCURRED IN MERGE FOR [stg].[SSIS_BUDGET_ProductCategoryGroupLookup]. Rows affected: ' + cast(@mergeCount as varchar(100)); -- SQL should always return zero rows affected
 end
else
 begin
 print '[stg].[SSIS_BUDGET_ProductCategoryGroupLookup] rows affected by MERGE: ' + cast(@mergeCount as varchar(100));
 end
go

set nocount off
go
