GRANT SELECT ON SCHEMA:: [INFORMATION_SCHEMA] TO [DataFeedReaders]
GO
GRANT SELECT ON SCHEMA:: [INFORMATION_SCHEMA] TO [DataFeeds]
GO
GRANT SELECT ON SCHEMA:: [INFORMATION_SCHEMA] TO [DataFeedWriters]
GO
