CREATE TABLE [psa].[ics_stg_Navision_BGR_Purchase_Invoice_Line]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_BGR_Purchase_Invoice_Line_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_BGR_Purchase_Invoice_Line_IsIncomplete] DEFAULT ('N'),
[Allow Invoice Disc_] [tinyint] NULL,
[Amount] [decimal] (38, 20) NULL,
[Amount Including VAT] [decimal] (38, 20) NULL,
[Appl_-to Item Entry] [int] NULL,
[Area] [varchar] (10) NULL,
[Attached to Line No_] [int] NULL,
[Bin Code] [varchar] (20) NULL,
[Blanket Order Line No_] [int] NULL,
[Blanket Order No_] [varchar] (20) NULL,
[Budgeted FA No_] [varchar] (20) NULL,
[Buy-from Vendor No_] [varchar] (20) NULL,
[Cross-Reference No_] [varchar] (20) NULL,
[Cross-Reference Type] [int] NULL,
[Cross-Reference Type No_] [varchar] (30) NULL,
[Depr_ Acquisition Cost] [tinyint] NULL,
[Depr_ until FA Posting Date] [tinyint] NULL,
[Depreciation Book Code] [varchar] (10) NULL,
[Description] [varchar] (50) NULL,
[Description 2] [varchar] (50) NULL,
[Direct Unit Cost] [decimal] (38, 20) NULL,
[Document No_] [varchar] (20) NOT NULL,
[Duplicate in Depreciation Book] [varchar] (10) NULL,
[Entry Point] [varchar] (10) NULL,
[Expected Receipt Date] [datetime] NULL,
[FA Posting Date] [datetime] NULL,
[FA Posting Type] [int] NULL,
[Gen_ Bus_ Posting Group] [varchar] (10) NULL,
[Gen_ Prod_ Posting Group] [varchar] (10) NULL,
[Gross Weight] [decimal] (38, 20) NULL,
[IC Partner Code] [varchar] (20) NULL,
[IC Partner Ref_ Type] [int] NULL,
[IC Partner Reference] [varchar] (20) NULL,
[Indirect Cost %] [decimal] (38, 20) NULL,
[Insurance No_] [varchar] (20) NULL,
[Inv_ Discount Amount] [decimal] (38, 20) NULL,
[Item Category Code] [varchar] (10) NULL,
[Job Currency Code] [varchar] (20) NULL,
[Job Currency Factor] [decimal] (38, 20) NULL,
[Job Line Amount] [decimal] (38, 20) NULL,
[Job Line Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Disc_ Amount (LCY)] [decimal] (38, 20) NULL,
[Job Line Discount %] [decimal] (38, 20) NULL,
[Job Line Discount Amount] [decimal] (38, 20) NULL,
[Job Line Type] [int] NULL,
[Job No_] [varchar] (20) NULL,
[Job Task No_] [varchar] (20) NULL,
[Job Total Price] [decimal] (38, 20) NULL,
[Job Total Price (LCY)] [decimal] (38, 20) NULL,
[Job Unit Price] [decimal] (38, 20) NULL,
[Job Unit Price (LCY)] [decimal] (38, 20) NULL,
[Line Amount] [decimal] (38, 20) NULL,
[Line Discount %] [decimal] (38, 20) NULL,
[Line Discount Amount] [decimal] (38, 20) NULL,
[Line No_] [int] NOT NULL,
[Location Code] [varchar] (10) NULL,
[Maintenance Code] [varchar] (10) NULL,
[Net Weight] [decimal] (38, 20) NULL,
[No_] [varchar] (20) NULL,
[Nonstock] [tinyint] NULL,
[Operation No_] [varchar] (10) NULL,
[Overhead Rate] [decimal] (38, 20) NULL,
[Pay-to Vendor No_] [varchar] (20) NULL,
[Posting Date] [datetime] NULL,
[Posting Group] [varchar] (10) NULL,
[Prepayment Line] [tinyint] NULL,
[Prod_ Order Line No_] [int] NULL,
[Prod_ Order No_] [varchar] (20) NULL,
[Product Group Code] [varchar] (10) NULL,
[Purchasing Code] [varchar] (10) NULL,
[Qty_ per Unit of Measure] [decimal] (38, 20) NULL,
[Quantity] [decimal] (38, 20) NULL,
[Quantity (Base)] [decimal] (38, 20) NULL,
[Responsibility Center] [varchar] (10) NULL,
[Return Reason Code] [varchar] (10) NULL,
[Routing No_] [varchar] (20) NULL,
[Routing Reference No_] [int] NULL,
[Salvage Value] [decimal] (38, 20) NULL,
[Shortcut Dimension 1 Code] [varchar] (20) NULL,
[Shortcut Dimension 2 Code] [varchar] (20) NULL,
[System-Created Entry] [tinyint] NULL,
[Tax Area Code] [varchar] (20) NULL,
[Tax Group Code] [varchar] (10) NULL,
[Tax Liable] [tinyint] NULL,
[timestamp] [varbinary] (8) NULL,
[Transaction Specification] [varchar] (10) NULL,
[Transaction Type] [varchar] (10) NULL,
[Transport Method] [varchar] (10) NULL,
[Type] [int] NULL,
[Unit Cost] [decimal] (38, 20) NULL,
[Unit Cost (LCY)] [decimal] (38, 20) NULL,
[Unit of Measure] [varchar] (10) NULL,
[Unit of Measure (Cross Ref_)] [varchar] (10) NULL,
[Unit of Measure Code] [varchar] (10) NULL,
[Unit Price (LCY)] [decimal] (38, 20) NULL,
[Unit Volume] [decimal] (38, 20) NULL,
[Units per Parcel] [decimal] (38, 20) NULL,
[Use Duplication List] [tinyint] NULL,
[Use Tax] [tinyint] NULL,
[Variant Code] [varchar] (10) NULL,
[VAT %] [decimal] (38, 20) NULL,
[VAT Base Amount] [decimal] (38, 20) NULL,
[VAT Bus_ Posting Group] [varchar] (10) NULL,
[VAT Calculation Type] [int] NULL,
[VAT Difference] [decimal] (38, 20) NULL,
[VAT Identifier] [varchar] (10) NULL,
[VAT Prod_ Posting Group] [varchar] (10) NULL,
[Vendor Item No_] [varchar] (20) NULL,
[Work Center No_] [varchar] (20) NULL
)
GO
ALTER TABLE [psa].[ics_stg_Navision_BGR_Purchase_Invoice_Line] ADD CONSTRAINT [PK_psa_ics_stg_Navision_BGR_Purchase_Invoice_Line] PRIMARY KEY CLUSTERED  ([Document No_], [Line No_])
GO
