CREATE TABLE [psa].[ics_stg_movex_MPLINE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_movex_MPLINE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_movex_MPLINE_IsIncomplete] DEFAULT ('N'),
[IBACLI] [decimal] (1, 0) NULL,
[IBACRF] [nvarchar] (8) NULL,
[IBADQA] [decimal] (15, 6) NULL,
[IBAGNB] [nvarchar] (7) NULL,
[IBATDT] [decimal] (8, 0) NULL,
[IBATNR] [decimal] (17, 0) NULL,
[IBATPR] [nvarchar] (1) NULL,
[IBBUYE] [nvarchar] (10) NULL,
[IBCAQA] [decimal] (15, 6) NULL,
[IBCFD1] [decimal] (5, 2) NULL,
[IBCFD2] [decimal] (5, 2) NULL,
[IBCFD3] [decimal] (5, 2) NULL,
[IBCFIN] [decimal] (7, 0) NULL,
[IBCFMB] [decimal] (15, 9) NULL,
[IBCFPB] [decimal] (15, 9) NULL,
[IBCFQA] [decimal] (15, 6) NULL,
[IBCHID] [nvarchar] (10) NULL,
[IBCHNO] [decimal] (3, 0) NULL,
[IBCLAN] [nvarchar] (7) NULL,
[IBCLLI] [decimal] (1, 0) NULL,
[IBCLLN] [decimal] (3, 0) NULL,
[IBCOCE] [nvarchar] (8) NULL,
[IBCODT] [decimal] (8, 0) NULL,
[IBCONO] [decimal] (3, 0) NOT NULL,
[IBCPPR] [decimal] (17, 6) NULL,
[IBCPRI] [nvarchar] (5) NULL,
[IBCPUC] [decimal] (5, 0) NULL,
[IBCSNO] [nvarchar] (16) NULL,
[IBDT4T] [decimal] (1, 0) NULL,
[IBDTID] [decimal] (13, 0) NULL,
[IBDWCP] [decimal] (1, 0) NULL,
[IBDWDT] [decimal] (8, 0) NULL,
[IBECDD] [decimal] (8, 0) NULL,
[IBECF1] [nvarchar] (5) NULL,
[IBECF2] [nvarchar] (5) NULL,
[IBECF3] [nvarchar] (5) NULL,
[IBECF4] [nvarchar] (5) NULL,
[IBECF5] [nvarchar] (5) NULL,
[IBECLC] [nvarchar] (2) NULL,
[IBECVE] [nvarchar] (4) NULL,
[IBECVS] [decimal] (3, 0) NULL,
[IBELNO] [nvarchar] (8) NULL,
[IBETRF] [nvarchar] (3) NULL,
[IBEXAT] [decimal] (1, 0) NULL,
[IBEXAV] [decimal] (1, 0) NULL,
[IBEXEP] [decimal] (15, 2) NULL,
[IBFACI] [nvarchar] (3) NULL,
[IBFUSC] [nvarchar] (3) NULL,
[IBGRMT] [nvarchar] (3) NULL,
[IBHAFE] [nvarchar] (6) NULL,
[IBHDPR] [nvarchar] (15) NULL,
[IBIDAG] [decimal] (1, 0) NULL,
[IBIDAT] [decimal] (8, 0) NULL,
[IBINEP] [decimal] (15, 2) NULL,
[IBIRCV] [nvarchar] (20) NULL,
[IBITNO] [nvarchar] (15) NULL,
[IBIVQA] [decimal] (15, 6) NULL,
[IBLICC] [nvarchar] (1) NULL,
[IBLMDT] [decimal] (8, 0) NULL,
[IBLNAM] [decimal] (15, 2) NULL,
[IBLPUD] [decimal] (8, 0) NULL,
[IBLTPP] [nvarchar] (1) NULL,
[IBMSTN] [decimal] (10, 0) NULL,
[IBNOED] [decimal] (1, 0) NULL,
[IBNPDE] [decimal] (3, 0) NULL,
[IBODI1] [decimal] (5, 2) NULL,
[IBODI2] [decimal] (5, 2) NULL,
[IBODI3] [decimal] (5, 2) NULL,
[IBOEND] [decimal] (1, 0) NULL,
[IBORQA] [decimal] (15, 6) NULL,
[IBORTY] [nvarchar] (3) NULL,
[IBOTOD] [decimal] (1, 0) NULL,
[IBOURR] [nvarchar] (10) NULL,
[IBOURT] [nvarchar] (1) NULL,
[IBPACT] [nvarchar] (6) NULL,
[IBPDDT] [decimal] (8, 0) NULL,
[IBPGRN] [decimal] (7, 0) NULL,
[IBPITD] [nvarchar] (30) NULL,
[IBPITT] [nvarchar] (60) NULL,
[IBPLDT] [decimal] (8, 0) NULL,
[IBPLPN] [decimal] (7, 0) NULL,
[IBPLPS] [decimal] (3, 0) NULL,
[IBPNLI] [decimal] (3, 0) NOT NULL,
[IBPNLS] [decimal] (3, 0) NOT NULL,
[IBPOTC] [nvarchar] (2) NULL,
[IBPPUN] [nvarchar] (3) NULL,
[IBPRCS] [nvarchar] (3) NULL,
[IBPRIP] [nvarchar] (1) NULL,
[IBPROD] [nvarchar] (10) NULL,
[IBPROJ] [nvarchar] (7) NULL,
[IBPTCD] [decimal] (1, 0) NULL,
[IBPUCD] [decimal] (5, 0) NULL,
[IBPUNO] [nvarchar] (7) NOT NULL,
[IBPUPR] [decimal] (17, 6) NULL,
[IBPURC] [nvarchar] (10) NULL,
[IBPUSL] [nvarchar] (2) NULL,
[IBPUST] [nvarchar] (2) NULL,
[IBPUUN] [nvarchar] (3) NULL,
[IBRCDT] [decimal] (8, 0) NULL,
[IBREPP] [decimal] (1, 0) NULL,
[IBRESF] [nvarchar] (10) NULL,
[IBREVN] [nvarchar] (2) NULL,
[IBRGDT] [decimal] (8, 0) NULL,
[IBRGTM] [decimal] (6, 0) NULL,
[IBRJQA] [decimal] (15, 6) NULL,
[IBRORC] [decimal] (1, 0) NULL,
[IBRORL] [decimal] (6, 0) NULL,
[IBRORN] [nvarchar] (10) NULL,
[IBRRQA] [decimal] (15, 6) NULL,
[IBRVQA] [decimal] (15, 6) NULL,
[IBSDQA] [decimal] (15, 6) NULL,
[IBSEBI] [nvarchar] (1) NULL,
[IBSEQN] [decimal] (7, 0) NULL,
[IBSITE] [nvarchar] (30) NULL,
[IBSORN] [nvarchar] (20) NULL,
[IBSUAG] [nvarchar] (10) NULL,
[IBSUFI] [nvarchar] (20) NULL,
[IBSUNO] [nvarchar] (10) NULL,
[IBTAXC] [nvarchar] (3) NULL,
[IBTERE] [nvarchar] (10) NULL,
[IBTIHM] [decimal] (4, 0) NULL,
[IBTNQA] [decimal] (15, 6) NULL,
[IBTXID] [decimal] (13, 0) NULL,
[IBULEX] [decimal] (1, 0) NULL,
[IBUPAV] [decimal] (1, 0) NULL,
[IBUPIV] [decimal] (1, 0) NULL,
[IBVDDT] [decimal] (8, 0) NULL,
[IBVRCD] [nvarchar] (2) NULL,
[IBVTCD] [decimal] (2, 0) NULL,
[IBWHLO] [nvarchar] (3) NULL
)
GO
ALTER TABLE [psa].[ics_stg_movex_MPLINE] ADD CONSTRAINT [PK_psa_ics_stg_movex_MPLINE] PRIMARY KEY CLUSTERED  ([IBCONO], [IBPUNO], [IBPNLI], [IBPNLS])
GO
