CREATE TABLE [psa].[ics_stg_M3V10gen_POL_MPPOEX]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_gen_MPPOEX_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_gen_MPPOEX_IsIncomplete] DEFAULT ('N'),
[PECHID] [nchar] (10) NULL,
[PECHNO] [numeric] (3, 0) NULL,
[PECONO] [numeric] (18, 0) NOT NULL,
[PEDTCD] [numeric] (1, 0) NULL,
[PEEALI] [numeric] (1, 0) NULL,
[PEFACI] [nchar] (3) NULL,
[PEFDAY] [numeric] (3, 0) NULL,
[PEFUDX] [numeric] (18, 0) NOT NULL,
[PEFUPF] [numeric] (1, 0) NULL,
[PEFUSC] [nchar] (3) NULL,
[PELMDT] [numeric] (8, 0) NULL,
[PEPNLI] [numeric] (18, 0) NOT NULL,
[PEPNLS] [numeric] (18, 0) NOT NULL,
[PEPUNO] [nchar] (7) NOT NULL,
[PEREMK] [nvarchar] (30) NULL,
[PERESP] [nchar] (10) NULL,
[PERGDT] [numeric] (8, 0) NULL,
[PERGTM] [numeric] (6, 0) NULL,
[PESTAT] [nchar] (2) NULL,
[PESUNO] [nchar] (10) NULL,
[PETXID] [numeric] (13, 0) NULL,
[PEWHLO] [nchar] (3) NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_MPPOEX] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_MPPOEX] PRIMARY KEY CLUSTERED  ([PECONO], [PEFUDX], [PEPNLI], [PEPNLS], [PEPUNO])
GO
