CREATE TABLE [psa].[ics_stg_M3V10ved_POL_FGRECL]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ved_FGRECL_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ved_FGRECL_IsIncomplete] DEFAULT ('N'),
[F2ANBR] [numeric] (9, 0) NULL,
[F2BUYE] [nchar] (10) NULL,
[F2CAWE] [numeric] (15, 6) NULL,
[F2CHID] [nchar] (10) NULL,
[F2CHNO] [numeric] (3, 0) NULL,
[F2CONO] [numeric] (18, 0) NOT NULL,
[F2CRTP] [numeric] (2, 0) NULL,
[F2CUCD] [nchar] (3) NULL,
[F2DIVI] [nchar] (3) NOT NULL,
[F2FACI] [nchar] (3) NULL,
[F2FGTP] [nchar] (2) NULL,
[F2FIAS] [numeric] (1, 0) NULL,
[F2HSIN] [nvarchar] (24) NULL,
[F2IASD] [numeric] (1, 0) NULL,
[F2IASR] [numeric] (1, 0) NULL,
[F2ICAC] [numeric] (15, 2) NULL,
[F2IMDT] [numeric] (8, 0) NULL,
[F2IMST] [numeric] (1, 0) NULL,
[F2ITNO] [nchar] (15) NULL,
[F2IVCW] [numeric] (15, 6) NULL,
[F2IVQA] [numeric] (15, 6) NULL,
[F2IVQT] [numeric] (15, 6) NULL,
[F2LMDT] [numeric] (8, 0) NULL,
[F2ORTY] [nchar] (3) NULL,
[F2PIDT] [numeric] (8, 0) NULL,
[F2PNLI] [numeric] (18, 0) NOT NULL,
[F2PNLS] [numeric] (18, 0) NOT NULL,
[F2PUCD] [numeric] (5, 0) NULL,
[F2PUNO] [nchar] (7) NOT NULL,
[F2RCAC] [numeric] (15, 2) NULL,
[F2RELP] [numeric] (18, 0) NOT NULL,
[F2REPN] [numeric] (18, 0) NOT NULL,
[F2RGDT] [numeric] (8, 0) NULL,
[F2RGTM] [numeric] (6, 0) NULL,
[F2RPQA] [numeric] (15, 6) NULL,
[F2RPQT] [numeric] (15, 6) NULL,
[F2SBAN] [nchar] (10) NULL,
[F2SCDC] [numeric] (5, 2) NULL,
[F2SCOC] [numeric] (17, 6) NULL,
[F2SCOP] [numeric] (17, 6) NULL,
[F2SENO] [numeric] (4, 0) NULL,
[F2SERA] [numeric] (11, 6) NULL,
[F2SORN] [nvarchar] (20) NULL,
[F2SUDO] [nvarchar] (20) NULL,
[F2SUNO] [nchar] (10) NULL,
[F2TRDT] [numeric] (8, 0) NULL,
[F2WHLO] [nchar] (3) NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10ved_POL_FGRECL] ADD CONSTRAINT [PK_psa_ics_stg_M3V10ved_POL_FGRECL] PRIMARY KEY CLUSTERED  ([F2CONO], [F2DIVI], [F2PNLI], [F2PNLS], [F2PUNO], [F2RELP], [F2REPN])
GO
EXEC sp_addextendedproperty N'IncludeInMerge', N'Y', 'SCHEMA', N'psa', 'TABLE', N'ics_stg_M3V10ved_POL_FGRECL', NULL, NULL
GO
