CREATE TABLE [psa].[ics_stg_ibs_lit_procure_SROORPHE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ibs_lit_procure_SROORPHE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ibs_lit_procure_SROORPHE_IsIncomplete] DEFAULT ('N'),
[OHSTAT] [nvarchar] (1) NULL,
[OHTYPE] [nvarchar] (1) NULL,
[OHORNO] [decimal] (12, 0) NOT NULL,
[OHORDT] [nvarchar] (2) NULL,
[OHODAT] [decimal] (8, 0) NULL,
[OHSUNO] [nvarchar] (11) NULL,
[OHSOPE] [nvarchar] (20) NULL,
[OHOREF] [nvarchar] (15) NULL,
[OHHAND] [nvarchar] (10) NULL,
[OHLANG] [nvarchar] (3) NULL,
[OHBALC] [nvarchar] (1) NULL,
[OHODIS] [decimal] (4, 2) NULL,
[OHSTXC] [nvarchar] (3) NULL,
[OHHORD] [nvarchar] (1) NULL,
[OHWSID] [nvarchar] (10) NULL,
[OHADSC] [nvarchar] (1) NULL,
[OHHDSC] [nvarchar] (1) NULL,
[OHTOPC] [nvarchar] (3) NULL,
[OHTOPT] [nvarchar] (30) NULL,
[OHTODC] [nvarchar] (3) NULL,
[OHTODD] [nvarchar] (30) NULL,
[OHMOTC] [nvarchar] (3) NULL,
[OHMOTT] [nvarchar] (30) NULL,
[OHNXLI] [decimal] (5, 0) NULL,
[OHSROM] [nvarchar] (3) NULL,
[OHDELT] [decimal] (8, 0) NULL,
[OHSGRP] [nvarchar] (6) NULL,
[OHNAME] [nvarchar] (30) NULL,
[OHPTIC] [nvarchar] (1) NULL,
[OHPDPO] [nvarchar] (1) NULL,
[OHPDPU] [nvarchar] (1) NULL,
[OHPORD] [nvarchar] (1) NULL,
[OHPUNP] [nvarchar] (1) NULL,
[OHPUSH] [nvarchar] (1) NULL,
[OHPURT] [nvarchar] (1) NULL,
[OHPUST] [nvarchar] (1) NULL,
[OHPNOD] [nvarchar] (1) NULL,
[OHPQUN] [nvarchar] (1) NULL,
[OHPDQN] [nvarchar] (1) NULL,
[OHPDPC] [nvarchar] (1) NULL,
[OHPDDP] [nvarchar] (1) NULL,
[OHROCO] [nvarchar] (1) NULL,
[OHPCUR] [nvarchar] (4) NULL,
[OHEXR3] [decimal] (13, 7) NULL,
[OHOTDC] [nvarchar] (30) NULL,
[OHTRPT] [decimal] (3, 0) NULL,
[OHORDS] [decimal] (2, 0) NULL,
[OHWHRD] [nvarchar] (1) NULL,
[OHEDOR] [nvarchar] (1) NULL,
[OHEDCR] [nvarchar] (1) NULL,
[OHCOUN] [nvarchar] (4) NULL,
[OHTREG] [nvarchar] (16) NULL,
[OHDCOU] [nvarchar] (4) NULL,
[OHDTRG] [nvarchar] (16) NULL,
[OHNOTR] [nvarchar] (3) NULL,
[OHPOVA] [nvarchar] (4) NULL,
[OHGDSM] [nvarchar] (30) NULL,
[OHECHG] [nvarchar] (1) NULL,
[OHFSRM] [nvarchar] (3) NULL,
[OHIORD] [nvarchar] (1) NULL,
[OHPOFX] [nvarchar] (35) NULL,
[OHPPOF] [nvarchar] (1) NULL,
[OHSPOF] [nvarchar] (1) NULL,
[OHCCOD] [nvarchar] (3) NULL,
[OHREAS] [nvarchar] (3) NULL,
[OHDTIM] [decimal] (5, 0) NULL,
[OHOANO] [decimal] (3, 0) NULL,
[OHVIEC] [nvarchar] (1) NULL,
[OHPROD] [nvarchar] (1) NULL,
[OHDMPI] [nvarchar] (1) NULL,
[OHBMPI] [nvarchar] (1) NULL,
[OHDOPC] [nvarchar] (1) NULL,
[OHBOPC] [nvarchar] (1) NULL,
[OHDROC] [nvarchar] (1) NULL,
[OHBROC] [nvarchar] (1) NULL,
[OHPMPC] [nvarchar] (1) NULL,
[OHPOMB] [nvarchar] (1) NULL,
[OHPRGR] [nvarchar] (1) NULL,
[OHPCLO] [nvarchar] (1) NULL,
[OHAVWC] [nvarchar] (1) NULL,
[OHOVAL] [decimal] (17, 4) NULL,
[OHITET] [decimal] (17, 3) NULL,
[OHITIT] [decimal] (17, 3) NULL,
[OHITT] [decimal] (17, 3) NULL,
[OHRCCD] [nvarchar] (2) NULL,
[OHNLVA] [nvarchar] (10) NULL,
[OHPRVR] [nvarchar] (1) NULL,
[OHATES] [nvarchar] (1) NULL,
[OHPRAC] [nvarchar] (1) NULL,
[OHATTC] [nvarchar] (1) NULL,
[OHLIMC] [nvarchar] (1) NULL,
[OHPDTN] [nvarchar] (1) NULL,
[OHPTRN] [nvarchar] (1) NULL,
[OHSTAM] [nvarchar] (1) NULL,
[OHSDAN] [decimal] (3, 0) NULL,
[OHTXKY] [decimal] (15, 0) NULL,
[OHMDCC] [nvarchar] (1) NULL,
[OHFCMP] [nvarchar] (2) NULL,
[OHMSON] [decimal] (12, 0) NULL,
[OHCSTS] [nvarchar] (7) NULL,
[OHDIVN] [nvarchar] (8) NULL,
[OHRTLN] [nvarchar] (1) NULL,
[OHTAXC] [nvarchar] (1) NULL,
[OHDSOR] [nvarchar] (1) NULL,
[OHPRCO] [decimal] (1, 0) NULL,
[OHDCDE] [nvarchar] (3) NULL,
[OHFPOR] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_ibs_lit_procure_SROORPHE] ADD CONSTRAINT [pk_psa_ics_stg_ibs_lit_procure_SROORPHE] PRIMARY KEY CLUSTERED  ([OHORNO])
GO
EXEC sp_addextendedproperty N'IncludeInMerge', N'Y', 'SCHEMA', N'psa', 'TABLE', N'ics_stg_ibs_lit_procure_SROORPHE', NULL, NULL
GO
