CREATE TABLE [psa].[ics_stg_M3V10ved_POL_MITTRA]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ved_MITTRA_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ved_MITTRA_IsIncomplete] DEFAULT ('N'),
[MTACRF] [nchar] (8) NULL,
[MTADCU] [numeric] (3, 0) NULL,
[MTANBR] [numeric] (9, 0) NULL,
[MTATNB] [numeric] (17, 0) NULL,
[MTATNR] [numeric] (17, 0) NULL,
[MTBANO] [nvarchar] (20) NULL,
[MTBIRT] [numeric] (10, 0) NULL,
[MTBRE2] [nvarchar] (20) NULL,
[MTBREF] [nvarchar] (20) NULL,
[MTCAMU] [nvarchar] (20) NULL,
[MTCANB] [numeric] (17, 0) NULL,
[MTCAWE] [numeric] (15, 6) NULL,
[MTCDTP] [numeric] (1, 0) NULL,
[MTCFGL] [nchar] (15) NULL,
[MTCNDA] [numeric] (8, 0) NULL,
[MTCONO] [numeric] (18, 0) NOT NULL,
[MTCSQT] [numeric] (15, 6) NULL,
[MTCWTQ] [numeric] (15, 6) NULL,
[MTCWTT] [numeric] (15, 6) NULL,
[MTDEID] [numeric] (7, 0) NULL,
[MTECVE] [nchar] (4) NULL,
[MTELNO] [nchar] (8) NULL,
[MTFIAS] [numeric] (1, 0) NULL,
[MTHACP] [numeric] (17, 6) NULL,
[MTHACS] [numeric] (1, 0) NULL,
[MTINDI] [numeric] (1, 0) NULL,
[MTINER] [numeric] (1, 0) NULL,
[MTITNO] [nchar] (15) NOT NULL,
[MTLMTS] [numeric] (18, 0) NULL,
[MTLOCH] [numeric] (1, 0) NULL,
[MTMFCO] [numeric] (17, 6) NULL,
[MTNHAI] [nchar] (15) NULL,
[MTNHSN] [nvarchar] (20) NULL,
[MTNSTQ] [numeric] (15, 6) NULL,
[MTNSTT] [numeric] (15, 6) NULL,
[MTOPAN] [nvarchar] (20) NULL,
[MTPANR] [nvarchar] (20) NULL,
[MTPLSX] [numeric] (3, 0) NULL,
[MTPRMF] [numeric] (7, 0) NULL,
[MTPROJ] [nchar] (7) NULL,
[MTREPN] [numeric] (10, 0) NULL,
[MTRESP] [nchar] (10) NULL,
[MTRFTX] [nvarchar] (40) NULL,
[MTRGDT] [numeric] (18, 0) NOT NULL,
[MTRGTM] [numeric] (18, 0) NOT NULL,
[MTRIDI] [numeric] (11, 0) NULL,
[MTRIDL] [numeric] (6, 0) NULL,
[MTRIDN] [nchar] (10) NULL,
[MTRIDO] [numeric] (6, 0) NULL,
[MTRIDX] [numeric] (3, 0) NULL,
[MTRORC] [numeric] (1, 0) NULL,
[MTRORL] [numeric] (6, 0) NULL,
[MTRORN] [nchar] (10) NULL,
[MTRORX] [numeric] (3, 0) NULL,
[MTRPRT] [numeric] (1, 0) NULL,
[MTRSCD] [nchar] (3) NULL,
[MTSCNB] [nchar] (10) NULL,
[MTSLTP] [nchar] (2) NULL,
[MTSTAS] [nchar] (1) NULL,
[MTSTCD] [numeric] (1, 0) NULL,
[MTSTNO] [numeric] (15, 6) NULL,
[MTSUDO] [nvarchar] (20) NULL,
[MTTMSX] [numeric] (18, 0) NOT NULL,
[MTTRDT] [numeric] (8, 0) NULL,
[MTTRPR] [numeric] (17, 6) NULL,
[MTTRQA] [numeric] (15, 6) NULL,
[MTTRQT] [numeric] (15, 6) NULL,
[MTTRTM] [numeric] (6, 0) NULL,
[MTTRTP] [nchar] (3) NULL,
[MTTTID] [nchar] (3) NULL,
[MTTTYP] [numeric] (2, 0) NULL,
[MTTUPC] [numeric] (1, 0) NULL,
[MTUPIS] [numeric] (1, 0) NULL,
[MTWHLO] [nchar] (3) NOT NULL,
[MTWHSL] [nchar] (10) NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10ved_POL_MITTRA] ADD CONSTRAINT [PK_psa_ics_stg_M3V10ved_POL_MITTRA] PRIMARY KEY CLUSTERED  ([MTCONO], [MTITNO], [MTRGDT], [MTRGTM], [MTTMSX], [MTWHLO])
GO
