CREATE TABLE [psa].[ics_stg_baan_ttdpur046610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur046610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur046610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_amta] [float] NULL,
[t_amtb] [float] NULL,
[t_amtc] [float] NULL,
[t_aprp] [smallint] NULL,
[t_apry] [smallint] NULL,
[t_ccur] [varchar] (3) NULL,
[t_clos] [tinyint] NULL,
[t_icom] [smallint] NULL,
[t_invn] [int] NULL,
[t_orno] [int] NULL,
[t_pdat] [datetime] NULL,
[t_pono] [smallint] NULL,
[t_qana] [float] NULL,
[t_srnb] [tinyint] NULL,
[t_srni] [tinyint] NULL,
[t_stsp] [tinyint] NULL,
[t_suno] [varchar] (6) NULL,
[t_ttyp] [varchar] (3) NULL
)
GO
