CREATE TABLE [psa].[ics_stg_SAP_GBR_T001L]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_T001L_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_T001L_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NOT NULL,
[WERKS] [nvarchar] (4) NOT NULL,
[LGORT] [nvarchar] (4) NOT NULL,
[LGOBE] [nvarchar] (16) NULL,
[SPART] [nvarchar] (2) NULL,
[XLONG] [nvarchar] (1) NULL,
[XBUFX] [nvarchar] (1) NULL,
[DISKZ] [nvarchar] (1) NULL,
[XBLGO] [nvarchar] (1) NULL,
[XRESS] [nvarchar] (1) NULL,
[XHUPF] [nvarchar] (1) NULL,
[PARLG] [nvarchar] (4) NULL,
[VKORG] [nvarchar] (4) NULL,
[VTWEG] [nvarchar] (2) NULL,
[VSTEL] [nvarchar] (4) NULL,
[LIFNR] [nvarchar] (10) NULL,
[KUNNR] [nvarchar] (10) NULL,
[MESBS] [nvarchar] (60) NULL,
[MESST] [nvarchar] (1) NULL,
[OIH_LICNO] [nvarchar] (15) NULL,
[OIG_ITRFL] [nvarchar] (1) NULL,
[OIB_TNKASSIGN] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_T001L] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_T001L_PK] PRIMARY KEY CLUSTERED  ([MANDT], [WERKS], [LGORT])
GO
