CREATE TABLE [psa].[ics_stg_baan_ttdpur080610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur080610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur080610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cdis_1] [varchar] (3) NULL,
[t_cdis_2] [varchar] (3) NULL,
[t_cdis_3] [varchar] (3) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cpgp] [varchar] (6) NULL,
[t_cvpp] [float] NULL,
[t_cvqp] [float] NULL,
[t_disc_1] [real] NULL,
[t_disc_2] [real] NULL,
[t_disc_3] [real] NULL,
[t_disl_1] [smallint] NULL,
[t_disl_2] [smallint] NULL,
[t_disl_3] [smallint] NULL,
[t_dlev_1] [tinyint] NULL,
[t_dlev_2] [tinyint] NULL,
[t_dlev_3] [tinyint] NULL,
[t_dmth_1] [tinyint] NULL,
[t_dmth_2] [tinyint] NULL,
[t_dmth_3] [tinyint] NULL,
[t_item] [varchar] (16) NULL,
[t_itst] [tinyint] NULL,
[t_ldam_1] [float] NULL,
[t_ldam_2] [float] NULL,
[t_ldam_3] [float] NULL,
[t_oqua] [float] NULL,
[t_orno] [int] NULL,
[t_pgst_1] [tinyint] NULL,
[t_pgst_2] [tinyint] NULL,
[t_pgst_3] [tinyint] NULL,
[t_plev] [tinyint] NULL,
[t_plst_1] [tinyint] NULL,
[t_plst_2] [tinyint] NULL,
[t_plst_3] [tinyint] NULL,
[t_pono] [smallint] NULL,
[t_pric] [float] NULL,
[t_updd_1] [tinyint] NULL,
[t_updd_2] [tinyint] NULL,
[t_updd_3] [tinyint] NULL,
[t_updp] [tinyint] NULL
)
GO
