CREATE TABLE [psa].[ics_stg_Navision_ROU_Purchase_Payables_Setup]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_ROU_Purchase_Payables_Setup_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_ROU_Purchase_Payables_Setup_IsIncomplete] DEFAULT ('N'),
[Allow VAT Difference] [tinyint] NULL,
[Appln_ between Currencies] [int] NULL,
[Blanket Order Nos_] [varchar] (10) NULL,
[Calc_ Inv_ Disc_ per VAT ID] [tinyint] NULL,
[Calc_ Inv_ Discount] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Cr_ Memo] [tinyint] NULL,
[Copy Cmts Ret_Ord_ to Ret_Shpt] [tinyint] NULL,
[Copy Comments Blanket to Order] [tinyint] NULL,
[Copy Comments Order to Invoice] [tinyint] NULL,
[Copy Comments Order to Receipt] [tinyint] NULL,
[Credit Memo Nos_] [varchar] (10) NULL,
[Custom Invoice No_ Mandatory] [tinyint] NULL,
[Discount Posting] [int] NULL,
[Exact Cost Reversing Mandatory] [tinyint] NULL,
[Ext_ Doc_ No_ Mandatory] [tinyint] NULL,
[Invoice Nos_] [varchar] (10) NULL,
[Invoice Rounding] [tinyint] NULL,
[Order Nos_] [varchar] (10) NULL,
[Posted Credit Memo Nos_] [varchar] (10) NULL,
[Posted Invoice Nos_] [varchar] (10) NULL,
[Posted Receipt Nos_] [varchar] (10) NULL,
[Posted Return Shpt_ Nos_] [varchar] (10) NULL,
[Posted Self-Invoice Nos_] [varchar] (10) NULL,
[Posting Desc_ Code] [varchar] (10) NULL,
[Primary Key] [varchar] (10) NOT NULL,
[Quote Nos_] [varchar] (10) NULL,
[Receipt on Invoice] [tinyint] NULL,
[Return Order Nos_] [varchar] (10) NULL,
[Return Shipment on Credit Memo] [tinyint] NULL,
[timestamp] [varbinary] (8) NULL,
[Vendor Nos_] [varchar] (10) NULL
)
GO
ALTER TABLE [psa].[ics_stg_Navision_ROU_Purchase_Payables_Setup] ADD CONSTRAINT [PK_psa_ics_stg_Navision_ROU_Purchase_Payables_Setup] PRIMARY KEY CLUSTERED  ([Primary Key])
GO
