CREATE TABLE [psa].[ics_stg_SAP_GBR_TKA01]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_TKA01_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_TKA01_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[KOKRS] [nvarchar] (4) NULL,
[BEZEI] [nvarchar] (25) NULL,
[WAERS] [nvarchar] (5) NULL,
[KTOPL] [nvarchar] (4) NULL,
[LMONA] [nvarchar] (2) NULL,
[KOKFI] [nvarchar] (1) NULL,
[LOGSYSTEM] [nvarchar] (10) NULL,
[ALEMT] [nvarchar] (2) NULL,
[MD_LOGSYSTEM] [nvarchar] (10) NULL,
[KHINR] [nvarchar] (12) NULL,
[KOMP1] [nvarchar] (1) NULL,
[KOMP0] [nvarchar] (1) NULL,
[KOMP2] [nvarchar] (1) NULL,
[ERKRS] [nvarchar] (4) NULL,
[DPRCT] [nvarchar] (10) NULL,
[PHINR] [nvarchar] (12) NULL,
[PCLDG] [nvarchar] (2) NULL,
[PCBEL] [nvarchar] (1) NULL,
[XWBUK] [nvarchar] (1) NULL,
[BPHINR] [nvarchar] (12) NULL,
[XBPALE] [nvarchar] (1) NULL,
[KSTAR_FIN] [nvarchar] (10) NULL,
[KSTAR_FID] [nvarchar] (10) NULL,
[PCACUR] [nvarchar] (5) NULL,
[PCACURTP] [nvarchar] (2) NULL,
[PCATRCUR] [nvarchar] (1) NULL,
[CTYP] [nvarchar] (2) NULL,
[RCLAC] [nvarchar] (1) NULL,
[BLART] [nvarchar] (2) NULL,
[FIKRS] [nvarchar] (4) NULL,
[RCL_PRIMAC] [nvarchar] (1) NULL,
[PCA_ALEMT] [nvarchar] (2) NULL,
[PCA_VALU] [nvarchar] (1) NULL,
[CVPROF] [nvarchar] (4) NULL,
[CVACT] [nvarchar] (1) NULL,
[VNAME] [nvarchar] (12) NULL,
[PCA_ACC_DIFF] [nvarchar] (1) NULL,
[TP_VALOHB] [nvarchar] (1) NULL,
[DEFPRCTR] [nvarchar] (10) NULL,
[AUTH_USE_NO_STD] [nvarchar] (1) NULL,
[AUTH_USE_ADD1] [nvarchar] (1) NULL,
[AUTH_USE_ADD2] [nvarchar] (1) NULL,
[AUTH_KE_NO_STD] [nvarchar] (1) NULL,
[AUTH_KE_USE_ADD1] [nvarchar] (1) NULL,
[AUTH_KE_USE_ADD2] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_TKA01] ADD CONSTRAINT [AK_psa_ics_stg_SAP_GBR_TKA01_EtlRecordId] UNIQUE CLUSTERED  ([EtlRecordId])
GO
