CREATE TABLE [psa].[ics_stg_SAP_GBR_EKPO]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_EKPO_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_EKPO_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[STATU] [nvarchar] (1) NULL,
[AEDAT] [datetime] NULL,
[TXZ01] [nvarchar] (40) NULL,
[MATNR] [nvarchar] (18) NULL,
[EMATN] [nvarchar] (18) NULL,
[BUKRS] [nvarchar] (4) NULL,
[WERKS] [nvarchar] (4) NULL,
[LGORT] [nvarchar] (4) NULL,
[BEDNR] [nvarchar] (10) NULL,
[MATKL] [nvarchar] (9) NULL,
[INFNR] [nvarchar] (10) NULL,
[IDNLF] [nvarchar] (35) NULL,
[KTMNG] [decimal] (13, 3) NULL,
[MENGE] [decimal] (13, 3) NULL,
[MEINS] [nvarchar] (3) NULL,
[BPRME] [nvarchar] (3) NULL,
[BPUMZ] [decimal] (5, 0) NULL,
[BPUMN] [decimal] (5, 0) NULL,
[UMREZ] [decimal] (5, 0) NULL,
[UMREN] [decimal] (5, 0) NULL,
[NETPR] [decimal] (11, 2) NULL,
[PEINH] [decimal] (5, 0) NULL,
[NETWR] [decimal] (13, 2) NULL,
[BRTWR] [decimal] (13, 2) NULL,
[AGDAT] [datetime] NULL,
[WEBAZ] [decimal] (3, 0) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[BONUS] [nvarchar] (2) NULL,
[INSMK] [nvarchar] (1) NULL,
[SPINF] [nvarchar] (1) NULL,
[PRSDR] [nvarchar] (1) NULL,
[SCHPR] [nvarchar] (1) NULL,
[MAHNZ] [decimal] (3, 0) NULL,
[MAHN1] [decimal] (3, 0) NULL,
[MAHN2] [decimal] (3, 0) NULL,
[MAHN3] [decimal] (3, 0) NULL,
[UEBTO] [decimal] (3, 1) NULL,
[UEBTK] [nvarchar] (1) NULL,
[UNTTO] [decimal] (3, 1) NULL,
[BWTAR] [nvarchar] (10) NULL,
[BWTTY] [nvarchar] (1) NULL,
[ABSKZ] [nvarchar] (1) NULL,
[AGMEM] [nvarchar] (3) NULL,
[ELIKZ] [nvarchar] (1) NULL,
[EREKZ] [nvarchar] (1) NULL,
[PSTYP] [nvarchar] (1) NULL,
[KNTTP] [nvarchar] (1) NULL,
[KZVBR] [nvarchar] (1) NULL,
[VRTKZ] [nvarchar] (1) NULL,
[TWRKZ] [nvarchar] (1) NULL,
[WEPOS] [nvarchar] (1) NULL,
[WEUNB] [nvarchar] (1) NULL,
[REPOS] [nvarchar] (1) NULL,
[WEBRE] [nvarchar] (1) NULL,
[KZABS] [nvarchar] (1) NULL,
[LABNR] [nvarchar] (20) NULL,
[KONNR] [nvarchar] (10) NULL,
[KTPNR] [nvarchar] (5) NULL,
[ABDAT] [datetime] NULL,
[ABFTZ] [decimal] (13, 3) NULL,
[ETFZ1] [decimal] (3, 0) NULL,
[ETFZ2] [decimal] (3, 0) NULL,
[KZSTU] [nvarchar] (1) NULL,
[NOTKZ] [nvarchar] (1) NULL,
[LMEIN] [nvarchar] (3) NULL,
[EVERS] [nvarchar] (2) NULL,
[ZWERT] [decimal] (13, 2) NULL,
[NAVNW] [decimal] (13, 2) NULL,
[ABMNG] [decimal] (13, 3) NULL,
[PRDAT] [datetime] NULL,
[BSTYP] [nvarchar] (1) NULL,
[EFFWR] [decimal] (13, 2) NULL,
[XOBLR] [nvarchar] (1) NULL,
[KUNNR] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[EKKOL] [nvarchar] (4) NULL,
[SKTOF] [nvarchar] (1) NULL,
[STAFO] [nvarchar] (6) NULL,
[PLIFZ] [decimal] (3, 0) NULL,
[NTGEW] [decimal] (13, 3) NULL,
[GEWEI] [nvarchar] (3) NULL,
[TXJCD] [nvarchar] (15) NULL,
[ETDRK] [nvarchar] (1) NULL,
[SOBKZ] [nvarchar] (1) NULL,
[ARSNR] [nvarchar] (10) NULL,
[ARSPS] [nvarchar] (4) NULL,
[INSNC] [nvarchar] (1) NULL,
[SSQSS] [nvarchar] (8) NULL,
[ZGTYP] [nvarchar] (4) NULL,
[EAN11] [nvarchar] (18) NULL,
[BSTAE] [nvarchar] (4) NULL,
[REVLV] [nvarchar] (2) NULL,
[GEBER] [nvarchar] (10) NULL,
[FISTL] [nvarchar] (16) NULL,
[FIPOS] [nvarchar] (14) NULL,
[KO_GSBER] [nvarchar] (4) NULL,
[KO_PARGB] [nvarchar] (4) NULL,
[KO_PRCTR] [nvarchar] (10) NULL,
[KO_PPRCTR] [nvarchar] (10) NULL,
[MEPRF] [nvarchar] (1) NULL,
[BRGEW] [decimal] (13, 3) NULL,
[VOLUM] [decimal] (13, 3) NULL,
[VOLEH] [nvarchar] (3) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[VORAB] [nvarchar] (1) NULL,
[KOLIF] [nvarchar] (10) NULL,
[LTSNR] [nvarchar] (6) NULL,
[PACKNO] [nvarchar] (10) NULL,
[FPLNR] [nvarchar] (10) NULL,
[GNETWR] [decimal] (13, 2) NULL,
[STAPO] [nvarchar] (1) NULL,
[UEBPO] [nvarchar] (5) NULL,
[LEWED] [datetime] NULL,
[EMLIF] [nvarchar] (10) NULL,
[LBLKZ] [nvarchar] (1) NULL,
[SATNR] [nvarchar] (18) NULL,
[ATTYP] [nvarchar] (2) NULL,
[KANBA] [nvarchar] (1) NULL,
[ADRN2] [nvarchar] (10) NULL,
[CUOBJ] [nvarchar] (18) NULL,
[XERSY] [nvarchar] (1) NULL,
[EILDT] [datetime] NULL,
[DRDAT] [datetime] NULL,
[DRUHR] [datetime] NULL,
[DRUNR] [nvarchar] (4) NULL,
[AKTNR] [nvarchar] (10) NULL,
[ABELN] [nvarchar] (10) NULL,
[ABELP] [nvarchar] (5) NULL,
[ANZPU] [decimal] (13, 3) NULL,
[PUNEI] [nvarchar] (3) NULL,
[SAISO] [nvarchar] (4) NULL,
[SAISJ] [nvarchar] (4) NULL,
[EBON2] [nvarchar] (2) NULL,
[EBON3] [nvarchar] (2) NULL,
[EBONF] [nvarchar] (1) NULL,
[MLMAA] [nvarchar] (1) NULL,
[MHDRZ] [decimal] (4, 0) NULL,
[ANFNR] [nvarchar] (10) NULL,
[ANFPS] [nvarchar] (5) NULL,
[KZKFG] [nvarchar] (1) NULL,
[USEQU] [nvarchar] (1) NULL,
[UMSOK] [nvarchar] (1) NULL,
[BANFN] [nvarchar] (10) NULL,
[BNFPO] [nvarchar] (5) NULL,
[MTART] [nvarchar] (4) NULL,
[UPTYP] [nvarchar] (1) NULL,
[UPVOR] [nvarchar] (1) NULL,
[KZWI1] [decimal] (13, 2) NULL,
[KZWI2] [decimal] (13, 2) NULL,
[KZWI3] [decimal] (13, 2) NULL,
[KZWI4] [decimal] (13, 2) NULL,
[KZWI5] [decimal] (13, 2) NULL,
[KZWI6] [decimal] (13, 2) NULL,
[SIKGR] [nvarchar] (3) NULL,
[MFZHI] [decimal] (15, 3) NULL,
[FFZHI] [decimal] (15, 3) NULL,
[RETPO] [nvarchar] (1) NULL,
[AUREL] [nvarchar] (1) NULL,
[BSGRU] [nvarchar] (3) NULL,
[LFRET] [nvarchar] (4) NULL,
[MFRGR] [nvarchar] (8) NULL,
[NRFHG] [nvarchar] (1) NULL,
[J_1BNBM] [nvarchar] (16) NULL,
[J_1BMATUSE] [nvarchar] (1) NULL,
[J_1BMATORG] [nvarchar] (1) NULL,
[J_1BOWNPRO] [nvarchar] (1) NULL,
[J_1BINDUST] [nvarchar] (2) NULL,
[ABUEB] [nvarchar] (4) NULL,
[NLABD] [datetime] NULL,
[NFABD] [datetime] NULL,
[KZBWS] [nvarchar] (1) NULL,
[BONBA] [decimal] (13, 2) NULL,
[FABKZ] [nvarchar] (1) NULL,
[J_1AINDXP] [nvarchar] (5) NULL,
[J_1AIDATEP] [datetime] NULL,
[MPROF] [nvarchar] (4) NULL,
[EGLKZ] [nvarchar] (1) NULL,
[KZTLF] [nvarchar] (1) NULL,
[KZFME] [nvarchar] (1) NULL,
[RDPRF] [nvarchar] (4) NULL,
[TECHS] [nvarchar] (12) NULL,
[CHG_SRV] [nvarchar] (1) NULL,
[CHG_FPLNR] [nvarchar] (1) NULL,
[MFRPN] [nvarchar] (40) NULL,
[MFRNR] [nvarchar] (10) NULL,
[EMNFR] [nvarchar] (10) NULL,
[NOVET] [nvarchar] (1) NULL,
[AFNAM] [nvarchar] (12) NULL,
[TZONRC] [nvarchar] (6) NULL,
[IPRKZ] [nvarchar] (1) NULL,
[LEBRE] [nvarchar] (1) NULL,
[BERID] [nvarchar] (10) NULL,
[XCONDITIONS] [nvarchar] (1) NULL,
[APOMS] [nvarchar] (1) NULL,
[CCOMP] [nvarchar] (1) NULL,
[GRANT_NBR] [nvarchar] (20) NULL,
[FKBER] [nvarchar] (16) NULL,
[STATUS] [nvarchar] (1) NULL,
[RESLO] [nvarchar] (4) NULL,
[KBLNR] [nvarchar] (10) NULL,
[KBLPOS] [nvarchar] (3) NULL,
[WEORA] [nvarchar] (1) NULL,
[SRV_BAS_COM] [nvarchar] (1) NULL,
[PRIO_URG] [nvarchar] (2) NULL,
[PRIO_REQ] [nvarchar] (3) NULL,
[EMPST] [nvarchar] (25) NULL,
[SPE_ABGRU] [nvarchar] (2) NULL,
[SPE_CRM_SO] [nvarchar] (10) NULL,
[SPE_CRM_SO_ITEM] [nvarchar] (6) NULL,
[SPE_CRM_REF_SO] [nvarchar] (35) NULL,
[SPE_CRM_REF_ITEM] [nvarchar] (6) NULL,
[SPE_CRM_FKREL] [nvarchar] (1) NULL,
[SPE_CHNG_SYS] [nvarchar] (1) NULL,
[SPE_INSMK_SRC] [nvarchar] (1) NULL,
[SPE_CQ_CTRLTYPE] [nvarchar] (1) NULL,
[SPE_CQ_NOCQ] [nvarchar] (1) NULL,
[REASON_CODE] [nvarchar] (4) NULL,
[CQU_SAR] [decimal] (15, 3) NULL,
[ANZSN] [bigint] NULL,
[SPE_EWM_DTC] [nvarchar] (1) NULL,
[EXLIN] [nvarchar] (40) NULL,
[EXSNR] [nvarchar] (5) NULL,
[EHTYP] [nvarchar] (4) NULL,
[RETPC] [decimal] (5, 2) NULL,
[DPTYP] [nvarchar] (4) NULL,
[DPPCT] [decimal] (5, 2) NULL,
[DPAMT] [decimal] (11, 2) NULL,
[DPDAT] [datetime] NULL,
[FLS_RSTO] [nvarchar] (1) NULL,
[EXT_RFX_NUMBER] [nvarchar] (35) NULL,
[EXT_RFX_ITEM] [nvarchar] (10) NULL,
[EXT_RFX_SYSTEM] [nvarchar] (10) NULL,
[SRM_CONTRACT_ID] [nvarchar] (10) NULL,
[SRM_CONTRACT_ITM] [nvarchar] (10) NULL,
[BLK_REASON_ID] [nvarchar] (4) NULL,
[BLK_REASON_TXT] [nvarchar] (40) NULL,
[ITCONS] [nvarchar] (1) NULL,
[FIXMG] [nvarchar] (1) NULL,
[WABWE] [nvarchar] (1) NULL,
[TC_AUT_DET] [nvarchar] (2) NULL,
[MANUAL_TC_REASON] [nvarchar] (2) NULL,
[FISCAL_INCENTIVE] [nvarchar] (4) NULL,
[TAX_SUBJECT_ST] [nvarchar] (1) NULL,
[FISCAL_INCENTIVE_ID] [nvarchar] (4) NULL,
[_BEV1_NEGEN_ITEM] [nvarchar] (1) NULL,
[_BEV1_NEDEPFREE] [nvarchar] (1) NULL,
[_BEV1_NESTRUCCAT] [nvarchar] (1) NULL,
[ADVCODE] [nvarchar] (2) NULL,
[BUDGET_PD] [nvarchar] (10) NULL,
[EXCPE] [nvarchar] (2) NULL,
[FMFGUS_KEY] [nvarchar] (22) NULL,
[IUID_RELEVANT] [nvarchar] (1) NULL,
[MRPIND] [nvarchar] (1) NULL,
[REFSITE] [nvarchar] (4) NULL,
[REF_ITEM] [nvarchar] (5) NULL,
[SOURCE_ID] [nvarchar] (3) NULL,
[SOURCE_KEY] [nvarchar] (32) NULL,
[PUT_BACK] [nvarchar] (1) NULL,
[POL_ID] [nvarchar] (10) NULL,
[CONS_ORDER] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EKPO] ADD CONSTRAINT [AK_psa_ics_stg_SAP_GBR_EKPO_EtlRecordId] UNIQUE CLUSTERED  ([EtlRecordId])
GO
