CREATE TABLE [psa].[ics_stg_M3V10gen_POL_OINVOH]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_OINVOH_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_OINVOH_IsDuplicate] DEFAULT ((0)),
[UH3RDP] [nchar] (10) NULL,
[UHACDT] [numeric] (18, 0) NULL,
[UHCASH] [numeric] (18, 0) NULL,
[UHCHID] [nchar] (10) NULL,
[UHCHNO] [numeric] (18, 0) NULL,
[UHCONO] [numeric] (18, 0) NOT NULL,
[UHCUCD] [nchar] (3) NULL,
[UHDIVI] [nchar] (3) NOT NULL,
[UHDUDT] [numeric] (18, 0) NULL,
[UHEXIN] [nchar] (14) NULL,
[UHFAC2] [nchar] (3) NULL,
[UHFACI] [nchar] (3) NULL,
[UHIDAT] [numeric] (18, 0) NULL,
[UHINPX] [nchar] (6) NOT NULL,
[UHINRC] [nchar] (10) NULL,
[UHINST] [nchar] (2) NULL,
[UHIVAM] [numeric] (18, 0) NULL,
[UHIVLA] [numeric] (18, 0) NULL,
[UHIVNO] [numeric] (18, 0) NOT NULL,
[UHIVTP] [nchar] (2) NULL,
[UHLMDT] [numeric] (18, 0) NULL,
[UHLMTS] [numeric] (18, 0) NULL,
[UHMUST] [numeric] (18, 0) NULL,
[UHNESI] [numeric] (18, 0) NULL,
[UHNREF] [nvarchar] (20) NULL,
[UHNVAT] [numeric] (18, 0) NULL,
[UHORIG] [numeric] (18, 0) NULL,
[UHPYNO] [nchar] (10) NULL,
[UHRAFC] [numeric] (18, 0) NULL,
[UHRAIN] [numeric] (18, 0) NULL,
[UHRALC] [numeric] (18, 0) NULL,
[UHRGDT] [numeric] (18, 0) NULL,
[UHRGTM] [numeric] (18, 0) NULL,
[UHRINP] [nchar] (6) NULL,
[UHRIVN] [numeric] (18, 0) NULL,
[UHRXIN] [nchar] (14) NULL,
[UHRYEA] [numeric] (18, 0) NULL,
[UHSBTO] [numeric] (18, 0) NULL,
[UHUPAC] [numeric] (18, 0) NULL,
[UHUPBC] [numeric] (18, 0) NULL,
[UHUPEC] [numeric] (18, 0) NULL,
[UHVONO] [numeric] (18, 0) NULL,
[UHVSER] [nchar] (3) NULL,
[UHYEA4] [numeric] (18, 0) NOT NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_OINVOH] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_OINVOH] PRIMARY KEY CLUSTERED  ([UHCONO], [UHDIVI], [UHINPX], [UHIVNO], [UHYEA4])
GO
