CREATE TABLE [psa].[ics_stg_SAP_GBR_EBAN]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_EBAN_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_EBAN_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[BANFN] [nvarchar] (10) NULL,
[BNFPO] [nvarchar] (5) NULL,
[BSART] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[BSAKZ] [nvarchar] (1) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[STATU] [nvarchar] (1) NULL,
[ESTKZ] [nvarchar] (1) NULL,
[FRGKZ] [nvarchar] (1) NULL,
[FRGZU] [nvarchar] (8) NULL,
[FRGST] [nvarchar] (2) NULL,
[EKGRP] [nvarchar] (3) NULL,
[ERNAM] [nvarchar] (12) NULL,
[ERDAT] [datetime] NULL,
[AFNAM] [nvarchar] (12) NULL,
[TXZ01] [nvarchar] (40) NULL,
[MATNR] [nvarchar] (18) NULL,
[EMATN] [nvarchar] (18) NULL,
[WERKS] [nvarchar] (4) NULL,
[LGORT] [nvarchar] (4) NULL,
[BEDNR] [nvarchar] (10) NULL,
[MATKL] [nvarchar] (9) NULL,
[RESWK] [nvarchar] (4) NULL,
[MENGE] [decimal] (13, 3) NULL,
[MEINS] [nvarchar] (3) NULL,
[BUMNG] [decimal] (13, 3) NULL,
[BADAT] [datetime] NULL,
[LPEIN] [nvarchar] (1) NULL,
[LFDAT] [datetime] NULL,
[FRGDT] [datetime] NULL,
[WEBAZ] [decimal] (3, 0) NULL,
[PREIS] [decimal] (11, 2) NULL,
[PEINH] [decimal] (5, 0) NULL,
[PSTYP] [nvarchar] (1) NULL,
[KNTTP] [nvarchar] (1) NULL,
[KZVBR] [nvarchar] (1) NULL,
[KFLAG] [nvarchar] (1) NULL,
[VRTKZ] [nvarchar] (1) NULL,
[TWRKZ] [nvarchar] (1) NULL,
[WEPOS] [nvarchar] (1) NULL,
[WEUNB] [nvarchar] (1) NULL,
[REPOS] [nvarchar] (1) NULL,
[LIFNR] [nvarchar] (10) NULL,
[FLIEF] [nvarchar] (10) NULL,
[EKORG] [nvarchar] (4) NULL,
[VRTYP] [nvarchar] (1) NULL,
[KONNR] [nvarchar] (10) NULL,
[KTPNR] [nvarchar] (5) NULL,
[INFNR] [nvarchar] (10) NULL,
[ZUGBA] [nvarchar] (1) NULL,
[QUNUM] [nvarchar] (10) NULL,
[QUPOS] [nvarchar] (3) NULL,
[DISPO] [nvarchar] (3) NULL,
[SERNR] [nvarchar] (8) NULL,
[BVDAT] [datetime] NULL,
[BATOL] [decimal] (3, 0) NULL,
[BVDRK] [decimal] (7, 0) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[BEDAT] [datetime] NULL,
[BSMNG] [decimal] (13, 3) NULL,
[LBLNI] [nvarchar] (10) NULL,
[BWTAR] [nvarchar] (10) NULL,
[XOBLR] [nvarchar] (1) NULL,
[EBAKZ] [nvarchar] (1) NULL,
[RSNUM] [nvarchar] (10) NULL,
[SOBKZ] [nvarchar] (1) NULL,
[ARSNR] [nvarchar] (10) NULL,
[ARSPS] [nvarchar] (4) NULL,
[FIXKZ] [nvarchar] (1) NULL,
[BMEIN] [nvarchar] (3) NULL,
[REVLV] [nvarchar] (2) NULL,
[VORAB] [nvarchar] (1) NULL,
[PACKNO] [nvarchar] (10) NULL,
[KANBA] [nvarchar] (1) NULL,
[BPUEB] [nvarchar] (1) NULL,
[CUOBJ] [nvarchar] (18) NULL,
[FRGGR] [nvarchar] (2) NULL,
[FRGRL] [nvarchar] (1) NULL,
[AKTNR] [nvarchar] (10) NULL,
[CHARG] [nvarchar] (10) NULL,
[UMSOK] [nvarchar] (1) NULL,
[VERID] [nvarchar] (4) NULL,
[FIPOS] [nvarchar] (14) NULL,
[FISTL] [nvarchar] (16) NULL,
[GEBER] [nvarchar] (10) NULL,
[KZKFG] [nvarchar] (1) NULL,
[SATNR] [nvarchar] (18) NULL,
[MNG02] [decimal] (13, 3) NULL,
[DAT01] [datetime] NULL,
[ATTYP] [nvarchar] (2) NULL,
[ADRNR] [nvarchar] (10) NULL,
[ADRN2] [nvarchar] (10) NULL,
[KUNNR] [nvarchar] (10) NULL,
[EMLIF] [nvarchar] (10) NULL,
[LBLKZ] [nvarchar] (1) NULL,
[KZBWS] [nvarchar] (1) NULL,
[WAERS] [nvarchar] (5) NULL,
[IDNLF] [nvarchar] (35) NULL,
[GSFRG] [nvarchar] (1) NULL,
[MPROF] [nvarchar] (4) NULL,
[KZFME] [nvarchar] (1) NULL,
[SPRAS] [nvarchar] (1) NULL,
[TECHS] [nvarchar] (12) NULL,
[MFRPN] [nvarchar] (40) NULL,
[MFRNR] [nvarchar] (10) NULL,
[EMNFR] [nvarchar] (10) NULL,
[FORDN] [nvarchar] (10) NULL,
[FORDP] [nvarchar] (5) NULL,
[PLIFZ] [decimal] (3, 0) NULL,
[BERID] [nvarchar] (10) NULL,
[UZEIT] [datetime] NULL,
[FKBER] [nvarchar] (16) NULL,
[GRANT_NBR] [nvarchar] (20) NULL,
[MEMORY] [nvarchar] (1) NULL,
[BANPR] [nvarchar] (2) NULL,
[RLWRT] [decimal] (15, 2) NULL,
[BLCKD] [nvarchar] (1) NULL,
[REVNO] [nvarchar] (8) NULL,
[BLCKT] [nvarchar] (60) NULL,
[BESWK] [nvarchar] (4) NULL,
[EPROFILE] [nvarchar] (2) NULL,
[EPREFDOC] [nvarchar] (10) NULL,
[EPREFITM] [nvarchar] (5) NULL,
[GMMNG] [decimal] (13, 3) NULL,
[WRTKZ] [nvarchar] (1) NULL,
[RESLO] [nvarchar] (4) NULL,
[KBLNR] [nvarchar] (10) NULL,
[KBLPOS] [nvarchar] (3) NULL,
[PRIO_URG] [nvarchar] (2) NULL,
[PRIO_REQ] [nvarchar] (3) NULL,
[MEMORYTYPE] [nvarchar] (1) NULL,
[ANZSN] [bigint] NULL,
[MHDRZ] [decimal] (4, 0) NULL,
[IPRKZ] [nvarchar] (1) NULL,
[NODISP] [nvarchar] (1) NULL,
[SRM_CONTRACT_ID] [nvarchar] (10) NULL,
[SRM_CONTRACT_ITM] [nvarchar] (10) NULL,
[BUDGET_PD] [nvarchar] (10) NULL,
[FMFGUS_KEY] [nvarchar] (22) NULL,
[ADVCODE] [nvarchar] (2) NULL,
[STACODE] [nvarchar] (2) NULL,
[BANFN_CS] [nvarchar] (10) NULL,
[BNFPO_CS] [nvarchar] (5) NULL,
[ITEM_CS] [nvarchar] (1) NULL,
[BSMNG_SND] [decimal] (13, 3) NULL,
[IUID_RELEVANT] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EBAN] ADD CONSTRAINT [AK_psa_ics_stg_SAP_GBR_EBAN_EtlRecordId] UNIQUE CLUSTERED  ([EtlRecordId])
GO
