CREATE TABLE [psa].[ics_stg_M3V10gen_POL_MITLOC]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_gen_MITLOC_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_gen_MITLOC_IsIncomplete] DEFAULT ('N'),
[MLACUQ] [numeric] (15, 6) NULL,
[MLACUW] [numeric] (15, 6) NULL,
[MLADJW] [numeric] (15, 6) NULL,
[MLALOC] [numeric] (1, 0) NULL,
[MLALQT] [numeric] (15, 6) NULL,
[MLATNR] [numeric] (17, 0) NULL,
[MLATV1] [nchar] (15) NULL,
[MLATV2] [nchar] (15) NULL,
[MLATV3] [nchar] (15) NULL,
[MLATV4] [nchar] (15) NULL,
[MLATV5] [nchar] (15) NULL,
[MLAUDD] [numeric] (3, 0) NULL,
[MLAUDE] [numeric] (1, 0) NULL,
[MLBANO] [nvarchar] (20) NOT NULL,
[MLBRE2] [nvarchar] (20) NULL,
[MLBREF] [nvarchar] (20) NULL,
[MLBREM] [nvarchar] (20) NULL,
[MLCAMU] [nvarchar] (20) NOT NULL,
[MLCANB] [numeric] (17, 0) NULL,
[MLCAWE] [numeric] (15, 6) NULL,
[MLCHID] [nchar] (10) NULL,
[MLCHNO] [numeric] (3, 0) NULL,
[MLCNDT] [numeric] (8, 0) NULL,
[MLCONO] [numeric] (18, 0) NOT NULL,
[MLDTID] [numeric] (13, 0) NULL,
[MLFACI] [nchar] (3) NULL,
[MLFIFL] [numeric] (1, 0) NULL,
[MLIDDT] [numeric] (8, 0) NULL,
[MLINCW] [numeric] (15, 6) NULL,
[MLINDT] [numeric] (8, 0) NULL,
[MLINON] [numeric] (1, 0) NULL,
[MLINVC] [numeric] (1, 0) NULL,
[MLIQTY] [numeric] (15, 6) NULL,
[MLITNO] [nchar] (15) NOT NULL,
[MLLMDT] [numeric] (8, 0) NULL,
[MLLMTS] [numeric] (18, 0) NULL,
[MLODDT] [numeric] (8, 0) NULL,
[MLOPAN] [nvarchar] (20) NULL,
[MLPACT] [nchar] (6) NULL,
[MLPLQT] [numeric] (15, 6) NULL,
[MLPOCY] [numeric] (5, 2) NULL,
[MLPPRI] [nchar] (1) NULL,
[MLPRDT] [numeric] (8, 0) NULL,
[MLPUAB] [numeric] (1, 0) NULL,
[MLRCLN] [numeric] (7, 0) NULL,
[MLRCLS] [numeric] (8, 0) NULL,
[MLREPN] [numeric] (18, 0) NOT NULL,
[MLRGDT] [numeric] (8, 0) NULL,
[MLRGTM] [numeric] (6, 0) NULL,
[MLSEDT] [numeric] (8, 0) NULL,
[MLSLTP] [nchar] (2) NULL,
[MLSTAS] [nchar] (1) NULL,
[MLSTES] [numeric] (1, 0) NULL,
[MLSTNB] [numeric] (10, 0) NULL,
[MLSTQM] [numeric] (15, 6) NULL,
[MLSTQT] [numeric] (15, 6) NULL,
[MLTXID] [numeric] (13, 0) NULL,
[MLWHLO] [nchar] (3) NOT NULL,
[MLWHLT] [nchar] (2) NULL,
[MLWHSL] [nchar] (10) NOT NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_MITLOC] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_MITLOC] PRIMARY KEY CLUSTERED  ([MLBANO], [MLCAMU], [MLCONO], [MLITNO], [MLREPN], [MLWHLO], [MLWHSL])
GO
