CREATE TABLE [psa].[ics_stg_M3V10ved_POL_FSLEDG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ved_FSLEDG_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ved_FSLEDG_IsIncomplete] DEFAULT ('N'),
[ESACBL] [numeric] (1, 0) NULL,
[ESACDT] [numeric] (8, 0) NULL,
[ESADAT] [numeric] (8, 0) NULL,
[ESAPRV] [numeric] (1, 0) NULL,
[ESARAT] [numeric] (11, 6) NULL,
[ESARCD] [numeric] (1, 0) NULL,
[ESBKID] [nchar] (5) NULL,
[ESBLBY] [nchar] (10) NULL,
[ESBLDT] [numeric] (8, 0) NULL,
[ESCHID] [nchar] (10) NULL,
[ESCHNO] [numeric] (3, 0) NULL,
[ESCINO] [nchar] (15) NULL,
[ESCLCD] [numeric] (1, 0) NULL,
[ESCLST] [numeric] (1, 0) NULL,
[ESCONO] [numeric] (18, 0) NOT NULL,
[ESCRST] [numeric] (1, 0) NULL,
[ESCRTP] [numeric] (2, 0) NULL,
[ESCUAM] [numeric] (15, 2) NULL,
[ESCUCD] [nchar] (3) NULL,
[ESCUCL] [nchar] (3) NULL,
[ESCUNO] [nchar] (10) NULL,
[ESDCAM] [numeric] (1, 0) NULL,
[ESDFPD] [numeric] (8, 0) NULL,
[ESDFPT] [numeric] (1, 0) NULL,
[ESDIVI] [nchar] (3) NOT NULL,
[ESDNRE] [nchar] (8) NULL,
[ESDTP5] [numeric] (8, 0) NULL,
[ESDUDT] [numeric] (8, 0) NULL,
[ESGRPD] [numeric] (8, 0) NULL,
[ESIIAM] [numeric] (15, 2) NULL,
[ESIICD] [numeric] (1, 0) NULL,
[ESIIST] [numeric] (1, 0) NULL,
[ESINYR] [numeric] (4, 0) NULL,
[ESIVCL] [nchar] (5) NULL,
[ESIVDT] [numeric] (8, 0) NULL,
[ESIVTP] [nchar] (2) NULL,
[ESJRNO] [numeric] (18, 0) NOT NULL,
[ESJSNO] [numeric] (18, 0) NOT NULL,
[ESLMDT] [numeric] (8, 0) NULL,
[ESLMTS] [numeric] (18, 0) NULL,
[ESLRDT] [numeric] (8, 0) NULL,
[ESPYCD] [nchar] (3) NULL,
[ESPYNO] [nchar] (10) NULL,
[ESPYRS] [nchar] (2) NULL,
[ESPYTP] [nchar] (2) NULL,
[ESRECO] [numeric] (1, 0) NULL,
[ESREDE] [numeric] (8, 0) NULL,
[ESRESP] [nchar] (10) NULL,
[ESRGDT] [numeric] (8, 0) NULL,
[ESRGTM] [numeric] (6, 0) NULL,
[ESRMBL] [numeric] (1, 0) NULL,
[ESRMQT] [numeric] (1, 0) NULL,
[ESRMST] [numeric] (1, 0) NULL,
[ESRVDT] [numeric] (8, 0) NULL,
[ESSAGS] [numeric] (2, 0) NULL,
[ESSLOP] [numeric] (2, 0) NULL,
[ESSMCD] [nchar] (4) NULL,
[ESTDSC] [nchar] (10) NULL,
[ESTECD] [nchar] (3) NULL,
[ESTEPY] [nchar] (3) NULL,
[ESTRCD] [numeric] (2, 0) NULL,
[ESTXID] [numeric] (13, 0) NULL,
[ESVONO] [numeric] (8, 0) NULL,
[ESVSER] [nchar] (3) NULL,
[ESVTAM] [numeric] (15, 2) NULL,
[ESYEA4] [numeric] (18, 0) NOT NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10ved_POL_FSLEDG] ADD CONSTRAINT [PK_psa_ics_stg_M3V10ved_POL_FSLEDG] PRIMARY KEY CLUSTERED  ([ESCONO], [ESDIVI], [ESJRNO], [ESJSNO], [ESYEA4])
GO
