CREATE TABLE [psa].[ics_stg_SAP_SVK_MARA]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_MARA_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_MARA_IsIncomplete] DEFAULT ('N'),
[_SAPMP_ABMEIN] [nvarchar] (3) NULL,
[_SAPMP_AHO] [nvarchar] (3) NULL,
[_SAPMP_BRAD] [decimal] (4, 0) NULL,
[_SAPMP_FBAK] [nvarchar] (1) NULL,
[_SAPMP_FBDK] [decimal] (7, 2) NULL,
[_SAPMP_FBHK] [decimal] (7, 2) NULL,
[_SAPMP_KADP] [decimal] (5, 2) NULL,
[_SAPMP_KADU] [decimal] (7, 2) NULL,
[_SAPMP_KEDU] [decimal] (7, 2) NULL,
[_SAPMP_MIFRR] [decimal] (7, 2) NULL,
[_SAPMP_RILI] [nvarchar] (1) NULL,
[_SAPMP_SPBI] [decimal] (7, 2) NULL,
[_SAPMP_SPTR] [decimal] (13, 3) NULL,
[_SAPMP_TRAD] [decimal] (7, 2) NULL,
[ADSPC_SPC] [nvarchar] (1) NULL,
[AEKLK] [nvarchar] (1) NULL,
[AENAM] [nvarchar] (12) NULL,
[AESZN] [nvarchar] (6) NULL,
[ATTYP] [nvarchar] (2) NULL,
[BBTYP] [nvarchar] (1) NULL,
[BEGRU] [nvarchar] (4) NULL,
[BEHVO] [nvarchar] (2) NULL,
[BFLME] [nvarchar] (1) NULL,
[BISMT] [nvarchar] (18) NULL,
[BLANZ] [nvarchar] (3) NULL,
[BLATT] [nvarchar] (3) NULL,
[BMATN] [nvarchar] (18) NULL,
[BREIT] [decimal] (13, 3) NULL,
[BRGEW] [decimal] (13, 3) NULL,
[BSTME] [nvarchar] (3) NULL,
[BWSCL] [nvarchar] (1) NULL,
[BWVOR] [nvarchar] (1) NULL,
[CADKZ] [nvarchar] (1) NULL,
[CMETH] [nvarchar] (1) NULL,
[CMREL] [nvarchar] (1) NULL,
[COMPL] [nvarchar] (2) NULL,
[CUOBF] [nvarchar] (18) NULL,
[DATAB] [nvarchar] (8) NULL,
[DISST] [nvarchar] (3) NULL,
[DPCBT] [nvarchar] (1) NULL,
[DVERS] [nvarchar] (18) NULL,
[EAN11] [nvarchar] (18) NULL,
[EANNR] [nvarchar] (13) NULL,
[EKWSL] [nvarchar] (4) NULL,
[ENTAR] [nvarchar] (1) NULL,
[ERGEI] [nvarchar] (3) NULL,
[ERGEW] [decimal] (13, 3) NULL,
[ERNAM] [nvarchar] (12) NULL,
[ERSDA] [nvarchar] (8) NULL,
[ERVOE] [nvarchar] (3) NULL,
[ERVOL] [decimal] (13, 3) NULL,
[ETIAG] [nvarchar] (18) NULL,
[ETIAR] [nvarchar] (2) NULL,
[ETIFO] [nvarchar] (2) NULL,
[EVVAL] [nvarchar] (1) NULL,
[EXTWG] [nvarchar] (18) NULL,
[FERTH] [nvarchar] (18) NULL,
[FORMT] [nvarchar] (4) NULL,
[FUELG] [decimal] (3, 0) NULL,
[GDS_RELEVANT] [nvarchar] (1) NULL,
[GENNR] [nvarchar] (18) NULL,
[GEWEI] [nvarchar] (3) NULL,
[GEWTO] [decimal] (3, 1) NULL,
[GROES] [nvarchar] (32) NULL,
[GTIN_VARIANT] [nvarchar] (2) NULL,
[HOEHE] [decimal] (13, 3) NULL,
[IHIVI] [nvarchar] (1) NULL,
[ILOOS] [nvarchar] (1) NULL,
[IMATN] [nvarchar] (18) NULL,
[INHAL] [decimal] (13, 3) NULL,
[INHBR] [decimal] (13, 3) NULL,
[INHME] [nvarchar] (3) NULL,
[IPRKZ] [nvarchar] (1) NULL,
[KOSCH] [nvarchar] (18) NULL,
[KUNNR] [nvarchar] (10) NULL,
[KZEFF] [nvarchar] (1) NULL,
[KZGVH] [nvarchar] (1) NULL,
[KZKFG] [nvarchar] (1) NULL,
[KZKUP] [nvarchar] (1) NULL,
[KZNFM] [nvarchar] (1) NULL,
[KZREV] [nvarchar] (1) NULL,
[KZUMW] [nvarchar] (1) NULL,
[KZWSM] [nvarchar] (1) NULL,
[LABOR] [nvarchar] (3) NULL,
[LAEDA] [nvarchar] (8) NULL,
[LAENG] [decimal] (13, 3) NULL,
[LIQDT] [nvarchar] (8) NULL,
[LVORM] [nvarchar] (1) NULL,
[MAGRV] [nvarchar] (4) NULL,
[MANDT] [nvarchar] (3) NULL,
[MATFI] [nvarchar] (1) NULL,
[MATKL] [nvarchar] (9) NULL,
[MATNR] [nvarchar] (18) NOT NULL,
[MBRSH] [nvarchar] (1) NULL,
[MEABM] [nvarchar] (3) NULL,
[MEINS] [nvarchar] (3) NULL,
[MFRNR] [nvarchar] (10) NULL,
[MFRPN] [nvarchar] (40) NULL,
[MHDHB] [decimal] (4, 0) NULL,
[MHDLP] [decimal] (3, 0) NULL,
[MHDRZ] [decimal] (4, 0) NULL,
[MLGUT] [nvarchar] (1) NULL,
[MPROF] [nvarchar] (4) NULL,
[MSBOOKPARTNO] [nvarchar] (18) NULL,
[MSTAE] [nvarchar] (2) NULL,
[MSTAV] [nvarchar] (2) NULL,
[MSTDE] [nvarchar] (8) NULL,
[MSTDV] [nvarchar] (8) NULL,
[MTART] [nvarchar] (4) NULL,
[MTPOS_MARA] [nvarchar] (4) NULL,
[NORMT] [nvarchar] (18) NULL,
[NRFHG] [nvarchar] (1) NULL,
[NTGEW] [decimal] (13, 3) NULL,
[NUMTP] [nvarchar] (2) NULL,
[OVLPN] [nvarchar] (32) NULL,
[PICNUM] [nvarchar] (18) NULL,
[PLGTP] [nvarchar] (2) NULL,
[PMATA] [nvarchar] (18) NULL,
[PRDHA] [nvarchar] (18) NULL,
[PROFL] [nvarchar] (3) NULL,
[PRZUS] [nvarchar] (1) NULL,
[PSTAT] [nvarchar] (15) NULL,
[QMPUR] [nvarchar] (1) NULL,
[RAUBE] [nvarchar] (2) NULL,
[RBNRM] [nvarchar] (9) NULL,
[RDMHD] [nvarchar] (1) NULL,
[RMATP] [nvarchar] (18) NULL,
[SAISJ] [nvarchar] (4) NULL,
[SAISO] [nvarchar] (4) NULL,
[SAITY] [nvarchar] (2) NULL,
[SATNR] [nvarchar] (18) NULL,
[SERLV] [nvarchar] (1) NULL,
[SLED_BBD] [nvarchar] (1) NULL,
[SPART] [nvarchar] (2) NULL,
[SPROF] [nvarchar] (1) NULL,
[STFAK] [decimal] (5, 0) NULL,
[STOFF] [nvarchar] (18) NULL,
[TAKLV] [nvarchar] (1) NULL,
[TEMPB] [nvarchar] (2) NULL,
[TRAGR] [nvarchar] (4) NULL,
[VABME] [nvarchar] (1) NULL,
[VARID] [binary] (1) NULL,
[VCHNR] [nvarchar] (12) NULL,
[VHART] [nvarchar] (4) NULL,
[VOLEH] [nvarchar] (3) NULL,
[VOLTO] [decimal] (3, 1) NULL,
[VOLUM] [decimal] (13, 3) NULL,
[VPREH] [decimal] (5, 0) NULL,
[VPSTA] [nvarchar] (15) NULL,
[VTYPE] [nvarchar] (10) NULL,
[WESCH] [decimal] (13, 3) NULL,
[WRKST] [nvarchar] (48) NULL,
[XCHPF] [nvarchar] (1) NULL,
[XGCHP] [nvarchar] (1) NULL,
[XGRDT] [nvarchar] (1) NULL,
[ZEIAR] [nvarchar] (3) NULL,
[ZEIFO] [nvarchar] (4) NULL,
[ZEINR] [nvarchar] (22) NULL,
[ZEIVR] [nvarchar] (2) NULL,
[ZZMATKL1] [nvarchar] (10) NULL,
[ZZMATKL2] [nvarchar] (5) NULL,
[ZZPOVOD] [nvarchar] (20) NULL,
[ZZPRPOV] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_SVK_MARA] ADD CONSTRAINT [PK_psa_ics_stg_SAP_SVK_MARA] PRIMARY KEY CLUSTERED  ([MATNR])
GO
EXEC sp_addextendedproperty N'IncludeInMerge', N'Y', 'SCHEMA', N'psa', 'TABLE', N'ics_stg_SAP_SVK_MARA', NULL, NULL
GO
