CREATE TABLE [psa].[ics_stg_Symfonia_MZ]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MZ_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MZ_IsIncomplete] DEFAULT ('N'),
[bufor] [smallint] NULL,
[cena] [float] NULL,
[data] [datetime] NULL,
[flag] [smallint] NULL,
[grupacen] [smallint] NULL,
[id] [int] NOT NULL,
[idkh] [int] NULL,
[idlongname] [int] NULL,
[idpozkoryg] [int] NULL,
[idtw] [int] NULL,
[ilosc] [float] NULL,
[iloscjedn] [float] NULL,
[iloscRLKS] [float] NULL,
[iloscwp] [float] NULL,
[jm] [varchar] (8) NULL,
[jmwp] [varchar] (8) NULL,
[kod] [varchar] (40) NULL,
[kompensata] [smallint] NULL,
[lp] [smallint] NULL,
[lwartk] [smallint] NULL,
[magazyn] [int] NULL,
[opis] [varchar] (40) NULL,
[opisdod] [varchar] (20) NULL,
[przychod] [float] NULL,
[rejestr] [int] NULL,
[rozchod] [float] NULL,
[schemat] [varchar] (4) NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[superkoryg] [int] NULL,
[typ] [smallint] NULL,
[wartk] [float] NULL,
[wartNetto] [float] NULL
)
GO
ALTER TABLE [psa].[ics_stg_Symfonia_MZ] ADD CONSTRAINT [PK_psa_ics_stg_Symfonia_MZ] PRIMARY KEY CLUSTERED  ([id])
GO
