CREATE TABLE [psa].[ics_stg_M3V10vil_POL_MITVEN]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_MITVEN_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_MITVEN_IsIncomplete] DEFAULT ('N'),
[IFAPDT] [numeric] (8, 0) NULL,
[IFCHID] [nchar] (10) NULL,
[IFCHNO] [numeric] (3, 0) NULL,
[IFCMCO] [nchar] (2) NULL,
[IFCONO] [numeric] (18, 0) NOT NULL,
[IFCRTP] [numeric] (2, 0) NULL,
[IFCUCD] [nchar] (3) NULL,
[IFDTID] [numeric] (13, 0) NULL,
[IFFACI] [nchar] (3) NULL,
[IFFVD1] [numeric] (8, 0) NULL,
[IFFVDT] [numeric] (8, 0) NULL,
[IFGRMT] [nchar] (3) NULL,
[IFISRS] [nchar] (2) NULL,
[IFITNO] [nchar] (15) NOT NULL,
[IFLEA1] [numeric] (3, 0) NULL,
[IFLEA5] [numeric] (3, 0) NULL,
[IFLMDT] [numeric] (8, 0) NULL,
[IFLMTS] [numeric] (18, 0) NULL,
[IFLOQT] [numeric] (15, 6) NULL,
[IFLPCD] [numeric] (8, 0) NULL,
[IFMCPR] [numeric] (5, 2) NULL,
[IFMEDC] [nchar] (10) NULL,
[IFMPSH] [numeric] (5, 2) NULL,
[IFORCO] [nchar] (3) NULL,
[IFORTY] [nchar] (3) NULL,
[IFPAAM] [numeric] (15, 2) NULL,
[IFPACT] [nchar] (6) NULL,
[IFPCCP] [numeric] (17, 6) NULL,
[IFPPUN] [nchar] (3) NULL,
[IFPRCS] [nchar] (3) NOT NULL,
[IFPUCD] [numeric] (5, 0) NULL,
[IFPUP1] [numeric] (17, 6) NULL,
[IFPUPR] [numeric] (17, 6) NULL,
[IFPUQT] [numeric] (15, 6) NULL,
[IFPUUN] [nchar] (3) NULL,
[IFQCUD] [numeric] (8, 0) NULL,
[IFQUCL] [nchar] (2) NULL,
[IFRCDT] [numeric] (8, 0) NULL,
[IFRESP] [nchar] (10) NULL,
[IFRFID] [nchar] (10) NULL,
[IFRGDT] [numeric] (8, 0) NULL,
[IFRGTM] [numeric] (6, 0) NULL,
[IFRTYP] [nchar] (1) NULL,
[IFSITD] [nvarchar] (30) NULL,
[IFSITE] [nvarchar] (30) NULL,
[IFSITT] [nvarchar] (60) NULL,
[IFSMSQ] [numeric] (15, 6) NULL,
[IFSTAP] [nchar] (1) NULL,
[IFSUFI] [nvarchar] (20) NOT NULL,
[IFSUNO] [nchar] (10) NOT NULL,
[IFSUP1] [numeric] (15, 2) NULL,
[IFSUPR] [numeric] (15, 2) NULL,
[IFTXID] [numeric] (13, 0) NULL,
[IFUNMU] [numeric] (15, 6) NULL,
[IFUVD1] [numeric] (8, 0) NULL,
[IFUVDT] [numeric] (8, 0) NULL,
[IFWHLO] [nchar] (3) NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_MITVEN] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_MITVEN] PRIMARY KEY CLUSTERED  ([IFCONO], [IFITNO], [IFPRCS], [IFSUFI], [IFSUNO])
GO
