CREATE TABLE [psa].[ics_stg_M3V10gen_POL_OPAYMH]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_gen_OPAYMH_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_gen_OPAYMH_IsIncomplete] DEFAULT ('N'),
[UJACDT] [numeric] (8, 0) NULL,
[UJBKID] [nchar] (5) NULL,
[UJCDTT] [numeric] (2, 0) NULL,
[UJCHID] [nchar] (10) NULL,
[UJCHNO] [numeric] (3, 0) NULL,
[UJCKNO] [nchar] (15) NULL,
[UJCONO] [numeric] (18, 0) NOT NULL,
[UJCRTP] [numeric] (2, 0) NULL,
[UJCSHD] [nchar] (5) NULL,
[UJCUCD] [nchar] (3) NULL,
[UJCUNM] [nvarchar] (36) NULL,
[UJDIVI] [nchar] (3) NULL,
[UJFACI] [nchar] (3) NULL,
[UJLMDT] [numeric] (8, 0) NULL,
[UJPLNB] [numeric] (18, 0) NOT NULL,
[UJPMAM] [numeric] (15, 2) NULL,
[UJPMLA] [numeric] (15, 2) NULL,
[UJPMNB] [numeric] (18, 0) NOT NULL,
[UJPTST] [nchar] (2) NULL,
[UJPYCD] [nchar] (3) NULL,
[UJPYDT] [numeric] (8, 0) NULL,
[UJPYNO] [nchar] (10) NULL,
[UJRAPM] [numeric] (11, 6) NULL,
[UJRGDT] [numeric] (8, 0) NULL,
[UJRGTM] [numeric] (6, 0) NULL,
[UJVONO] [numeric] (8, 0) NULL,
[UJVSER] [nchar] (3) NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_OPAYMH] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_OPAYMH] PRIMARY KEY CLUSTERED  ([UJCONO], [UJPLNB], [UJPMNB])
GO
