CREATE TABLE [psa].[ics_stg_movex_MITPOP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_movex_MITPOP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_movex_MITPOP_IsIncomplete] DEFAULT ('N'),
[MPCONO] [decimal] (3, 0) NULL,
[MPALWT] [decimal] (2, 0) NULL,
[MPALWQ] [nvarchar] (255) NULL,
[MPITNO] [nvarchar] (255) NULL,
[MPPOPN] [nvarchar] (255) NULL,
[MPE0PA] [nvarchar] (255) NULL,
[MPVFDT] [decimal] (8, 0) NULL,
[MPLVDT] [decimal] (8, 0) NULL,
[MPCNQT] [decimal] (15, 6) NULL,
[MPALUN] [nvarchar] (255) NULL,
[MPORCO] [nvarchar] (255) NULL,
[MPSEQN] [decimal] (7, 0) NULL,
[MPREMK] [nvarchar] (255) NULL,
[MPCFIN] [decimal] (10, 0) NULL,
[MPTXID] [decimal] (13, 0) NULL,
[MPSEA1] [nvarchar] (255) NULL,
[MPATPE] [nvarchar] (255) NULL,
[MPATNR] [decimal] (17, 0) NULL,
[MPRGDT] [decimal] (8, 0) NULL,
[MPRGTM] [decimal] (6, 0) NULL,
[MPLMDT] [decimal] (8, 0) NULL,
[MPCHNO] [decimal] (3, 0) NULL,
[MPCHID] [nvarchar] (255) NULL,
[MPLMTS] [decimal] (18, 0) NULL
)
GO
