CREATE TABLE [psa].[ics_land_Navision_Rom_Live Icopal Romania$Salesperson_Purchaser]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_Rom_Live Icopal Romania1812$Salesperson_Purchaser_IsIncomplete] DEFAULT ('N'),
[Code] [varchar] (10) NULL,
[Commission %] [decimal] (38, 20) NULL,
[E-Mail] [varchar] (80) NULL,
[Empty SalesPerson_Purch Code] [tinyint] NULL,
[Enable Synchronization] [tinyint] NULL,
[Global Dimension 1 Code] [varchar] (20) NULL,
[Global Dimension 2 Code] [varchar] (20) NULL,
[Job Title] [varchar] (30) NULL,
[Name] [varchar] (50) NULL,
[Navision User ID] [varchar] (20) NULL,
[Notify about Appmt_ Changes] [tinyint] NULL,
[Notify about Contact Changes] [tinyint] NULL,
[Notify about Task Changes] [tinyint] NULL,
[Notify about Team To-do Chgs_] [tinyint] NULL,
[Outlook Calendar Folder Path] [varchar] (250) NULL,
[Outlook Calendar FolderID] [image] NULL,
[Outlook Calendar StoreID] [image] NULL,
[Outlook Contacts Folder Path] [varchar] (250) NULL,
[Outlook Contacts FolderID] [image] NULL,
[Outlook Contacts StoreID] [image] NULL,
[Outlook Profile Name] [varchar] (80) NULL,
[Outlook Tasks Folder Path] [varchar] (250) NULL,
[Outlook Tasks FolderID] [image] NULL,
[Outlook Tasks StoreID] [image] NULL,
[Outlook User Name] [varchar] (80) NULL,
[Phone No_] [varchar] (30) NULL,
[Search E-Mail] [varchar] (80) NULL,
[Synchronize From] [varchar] (32) NULL,
[Synchronize To] [varchar] (32) NULL,
[Synchronize To-dos] [int] NULL,
[Version No_] [int] NULL,
[timestamp] [timestamp] NOT NULL
)
GO
