CREATE TABLE [psa].[ics_stg_M3V10vil_POL_MWOPOL]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_MWOPOL_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_MWOPOL_IsIncomplete] DEFAULT ('N'),
[BHCHID] [nchar] (10) NULL,
[BHCHNO] [numeric] (3, 0) NULL,
[BHCOFA] [numeric] (15, 9) NULL,
[BHCONO] [numeric] (18, 0) NOT NULL,
[BHDMCF] [numeric] (1, 0) NULL,
[BHEMNO] [nchar] (10) NULL,
[BHFACI] [nchar] (3) NOT NULL,
[BHLMDT] [numeric] (8, 0) NULL,
[BHLMTS] [numeric] (18, 0) NULL,
[BHMAQA] [numeric] (15, 6) NULL,
[BHMAQT] [numeric] (15, 6) NULL,
[BHMAUN] [nchar] (3) NULL,
[BHMCPL] [numeric] (1, 0) NULL,
[BHMFNO] [numeric] (7, 0) NULL,
[BHOADS] [numeric] (1, 0) NULL,
[BHOPNO] [numeric] (4, 0) NULL,
[BHPLCF] [numeric] (1, 0) NULL,
[BHPLNO] [numeric] (18, 0) NOT NULL,
[BHPLOA] [numeric] (15, 6) NULL,
[BHPLOB] [numeric] (15, 6) NULL,
[BHPRNO] [nchar] (15) NULL,
[BHREFD] [numeric] (8, 0) NULL,
[BHRGDT] [numeric] (8, 0) NULL,
[BHRGTM] [numeric] (6, 0) NULL,
[BHRSDT] [numeric] (8, 0) NULL,
[BHSCQA] [numeric] (15, 6) NULL,
[BHSCQT] [numeric] (15, 6) NULL,
[BHUMAS] [numeric] (7, 2) NULL,
[BHUMAT] [numeric] (7, 2) NULL,
[BHUPIT] [numeric] (7, 2) NULL,
[BHUSET] [numeric] (7, 2) NULL,
[BHWOSQ] [numeric] (18, 0) NOT NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_MWOPOL] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_MWOPOL] PRIMARY KEY CLUSTERED  ([BHCONO], [BHFACI], [BHPLNO], [BHWOSQ])
GO
