CREATE TABLE [psa].[ics_stg_cegid_comp_fra_procure_PIECE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_cegid_comp_fra_procure_PIECE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_+ ics_stg_cegid_comp_fra_procure_PIECE_IsIncomplete] DEFAULT ('N'),
[GP_NATUREPIECEG] [nvarchar] (3) NULL,
[GP_DATEPIECE] [datetime] NULL,
[GP_SOUCHE] [nvarchar] (3) NOT NULL,
[GP_PRENUMERO] [nvarchar] (17) NULL,
[GP_NUMERO] [int] NOT NULL,
[GP_NUMPIECE] [nvarchar] (35) NULL,
[GP_INDICEG] [int] NULL,
[GP_REFCOMPTABLE] [nvarchar] (35) NULL,
[GP_REFCPTASTOCK] [nvarchar] (35) NULL,
[GP_REFINTERNE] [nvarchar] (35) NULL,
[GP_REFEXTERNE] [nvarchar] (35) NULL,
[GP_DEVENIRPIECE] [nvarchar] (35) NULL,
[GP_TIERS] [nvarchar] (17) NULL,
[GP_TIERSLIVRE] [nvarchar] (17) NULL,
[GP_TIERSFACTURE] [nvarchar] (17) NULL,
[GP_TIERSPAYEUR] [nvarchar] (17) NULL,
[GP_AFFAIRE] [nvarchar] (17) NULL,
[GP_AFFAIRE1] [nvarchar] (14) NULL,
[GP_AFFAIRE2] [nvarchar] (13) NULL,
[GP_AFFAIRE3] [nvarchar] (12) NULL,
[GP_AVENANT] [nvarchar] (2) NULL,
[GP_REPRESENTANT] [nvarchar] (17) NULL,
[GP_APPORTEUR] [nvarchar] (17) NULL,
[GP_TIERSSAL1] [nvarchar] (17) NULL,
[GP_TIERSSAL2] [nvarchar] (17) NULL,
[GP_TIERSSAL3] [nvarchar] (17) NULL,
[GP_PRESCRIPTEUR] [nvarchar] (17) NULL,
[GP_JALCOMPTABLE] [nvarchar] (3) NULL,
[GP_CREATEUR] [nvarchar] (3) NULL,
[GP_UTILISATEUR] [nvarchar] (3) NULL,
[GP_ETABLISSEMENT] [nvarchar] (3) NULL,
[GP_DEPOT] [nvarchar] (3) NULL,
[GP_DEPOTDEST] [nvarchar] (3) NULL,
[GP_MODEREGLE] [nvarchar] (3) NULL,
[GP_TVAENCAISSEMENT] [nvarchar] (3) NULL,
[GP_REGIMETAXE] [nvarchar] (3) NULL,
[GP_TARIFTIERS] [nvarchar] (3) NULL,
[GP_TYPEREMISE] [nvarchar] (3) NULL,
[GP_PRIORITE] [nvarchar] (3) NULL,
[GP_EXPEDITION] [nvarchar] (3) NULL,
[GP_TRANSPORT] [nvarchar] (3) NULL,
[GP_DEVISE] [nvarchar] (3) NULL,
[GP_FACTUREHT] [nvarchar] (1) NULL,
[GP_VIVANTE] [nvarchar] (1) NULL,
[GP_SUPPRIME] [nvarchar] (1) NULL,
[GP_ETATEXPORT] [nvarchar] (3) NULL,
[GP_ETATVISA] [nvarchar] (3) NULL,
[GP_VISEUR] [nvarchar] (3) NULL,
[GP_DATEVISA] [datetime] NULL,
[GP_DATEEXPORT] [datetime] NULL,
[GP_AFFACTURAGE] [nvarchar] (1) NULL,
[GP_CONTREMARQUE] [nvarchar] (1) NULL,
[GP_NBCOLIS] [int] NULL,
[GP_NBTRANSMIS] [int] NULL,
[GP_TAUXDEV] [decimal] (15, 9) NULL,
[GP_COTATION] [decimal] (15, 9) NULL,
[GP_DATETAUXDEV] [datetime] NULL,
[GP_ESCOMPTE] [decimal] (19, 4) NULL,
[GP_TOTALESC] [decimal] (19, 4) NULL,
[GP_TOTALESCDEV] [decimal] (19, 4) NULL,
[GP_TOTESCTTC] [decimal] (19, 4) NULL,
[GP_TOTESCTTCDEV] [decimal] (19, 4) NULL,
[GP_QUALIFESCOMPTE] [nvarchar] (3) NULL,
[GP_REMISEPIED] [decimal] (19, 4) NULL,
[GP_TOTALREMISE] [decimal] (19, 4) NULL,
[GP_TOTALREMISEDEV] [decimal] (19, 4) NULL,
[GP_TOTREMISETTC] [decimal] (19, 4) NULL,
[GP_TOTREMISETTCDEV] [decimal] (19, 4) NULL,
[GP_TOTALHT] [decimal] (19, 4) NULL,
[GP_TOTALHTDEV] [decimal] (19, 4) NULL,
[GP_TOTALTTC] [decimal] (19, 4) NULL,
[GP_TOTALTTCDEV] [decimal] (19, 4) NULL,
[GP_TOTALQTEFACT] [decimal] (19, 4) NULL,
[GP_TOTALQTESTOCK] [decimal] (19, 4) NULL,
[GP_TOTALBASEREMDEV] [decimal] (19, 4) NULL,
[GP_TOTALBASEREM] [decimal] (19, 4) NULL,
[GP_TOTALBASEESCDEV] [decimal] (19, 4) NULL,
[GP_TOTALBASEESC] [decimal] (19, 4) NULL,
[GP_HEURECREATION] [datetime] NULL,
[GP_DATECREATION] [datetime] NULL,
[GP_DATEMODIF] [datetime] NULL,
[GP_DATEINTEGR] [datetime] NULL,
[GP_DATEREFEXTERNE] [datetime] NULL,
[GP_DATELIVRAISON] [datetime] NULL,
[GP_NUMADRESSELIVR] [int] NULL,
[GP_NUMADRESSEFACT] [int] NULL,
[GP_LIBRETIERS1] [nvarchar] (6) NULL,
[GP_LIBRETIERS2] [nvarchar] (6) NULL,
[GP_LIBRETIERS3] [nvarchar] (6) NULL,
[GP_LIBRETIERS4] [nvarchar] (6) NULL,
[GP_LIBRETIERS5] [nvarchar] (6) NULL,
[GP_LIBRETIERS6] [nvarchar] (6) NULL,
[GP_LIBRETIERS7] [nvarchar] (6) NULL,
[GP_LIBRETIERS8] [nvarchar] (6) NULL,
[GP_LIBRETIERS9] [nvarchar] (6) NULL,
[GP_LIBRETIERSA] [nvarchar] (6) NULL,
[GP_MAJLIBRETIERS] [nvarchar] (13) NULL,
[GP_LIBREPIECE1] [nvarchar] (6) NULL,
[GP_LIBREPIECE2] [nvarchar] (6) NULL,
[GP_LIBREPIECE3] [nvarchar] (6) NULL,
[GP_DATELIBREPIECE1] [datetime] NULL,
[GP_DATELIBREPIECE2] [datetime] NULL,
[GP_DATELIBREPIECE3] [datetime] NULL,
[GP_LIBREAFF1] [nvarchar] (6) NULL,
[GP_LIBREAFF2] [nvarchar] (6) NULL,
[GP_LIBREAFF3] [nvarchar] (6) NULL,
[GP_TOTALLINEAIRE] [decimal] (19, 4) NULL,
[GP_TOTALSURFACE] [decimal] (19, 4) NULL,
[GP_TOTALPOIDSBRUT] [decimal] (19, 4) NULL,
[GP_TOTALPOIDSNET] [decimal] (19, 4) NULL,
[GP_TOTALPOIDSDOUA] [decimal] (19, 4) NULL,
[GP_POIDSPESEE] [decimal] (19, 4) NULL,
[GP_TOTALVOLUME] [decimal] (19, 4) NULL,
[GP_TOTALHEURE] [decimal] (19, 4) NULL,
[GP_CREEPAR] [nvarchar] (3) NULL,
[GP_SOCIETE] [nvarchar] (3) NULL,
[GP_ARRONDILIGNE] [nvarchar] (1) NULL,
[GP_SAISIECONTRE] [nvarchar] (1) NULL,
[GP_RIB] [nvarchar] (70) NULL,
[GP_CBINTERNET] [nvarchar] (25) NULL,
[GP_CBLIBELLE] [nvarchar] (35) NULL,
[GP_CBDATEEXPIRE] [nvarchar] (7) NULL,
[GP_TYPECARTE] [nvarchar] (3) NULL,
[GP_CAISSE] [nvarchar] (3) NULL,
[GP_NUMZCAISSE] [int] NULL,
[GP_VENTEACHAT] [nvarchar] (3) NULL,
[GP_ARTICLESLOT] [nvarchar] (1) NULL,
[GP_ACOMPTEDEV] [decimal] (19, 4) NULL,
[GP_ACOMPTE] [decimal] (19, 4) NULL,
[GP_EDITEE] [nvarchar] (1) NULL,
[GP_PERIODE] [int] NULL,
[GP_SEMAINE] [int] NULL,
[GP_PERSPECTIVE] [int] NULL,
[GP_DOMAINE] [nvarchar] (3) NULL,
[GP_PIECEISREGLE] [nvarchar] (1) NULL,
[GP_HRDOSSIER] [nvarchar] (17) NULL,
[GP_GENERAUTO] [nvarchar] (3) NULL,
[GP_DATEDEBUTFAC] [datetime] NULL,
[GP_DATEFINFAC] [datetime] NULL,
[GP_FACREPRISE] [int] NULL,
[GP_RESSOURCE] [nvarchar] (17) NULL,
[GP_AFFAIREDEVIS] [nvarchar] (17) NULL,
[GP_ETATCOMPTA] [nvarchar] (3) NULL,
[GP_DATECOMPTA] [datetime] NULL,
[GP_CODEORDRE] [int] NULL,
[GP_TICKETANNULE] [nvarchar] (1) NULL,
[GP_DETAXE] [nvarchar] (1) NULL,
[GP_NUMDETAXE] [nvarchar] (17) NULL,
[GP_IDENTIFIANTWOT] [int] NULL,
[GP_TARIFSPECIAL] [nvarchar] (17) NULL,
[GP_REPRESENTANT2] [nvarchar] (17) NULL,
[GP_REPRESENTANT3] [nvarchar] (17) NULL,
[GP_NUMEROCONTACT] [int] NULL,
[GP_FERMETUREAFF] [nvarchar] (1) NULL,
[GP_CDETYPE] [nvarchar] (3) NULL,
[GP_ARTICLE] [nvarchar] (35) NULL,
[GP_CODEARTICLE] [nvarchar] (18) NULL,
[GP_PLANIFIABLE] [nvarchar] (1) NULL,
[GP_BLOCNOTE] [ntext] NULL,
[GP_OPERATION] [nvarchar] (17) NULL,
[GP_COMMISSIONR] [decimal] (19, 4) NULL,
[GP_COMMISSIONR2] [decimal] (19, 4) NULL,
[GP_COMMISSIONR3] [decimal] (19, 4) NULL,
[GP_TYPETAUXFIXING] [nvarchar] (4) NULL,
[GP_TAUXFIXING] [decimal] (19, 4) NULL,
[GP_ECHEBLOQUE] [nvarchar] (1) NULL,
[GP_REGIMETAXE2] [nvarchar] (3) NULL,
[GP_REGIMETAXE3] [nvarchar] (3) NULL,
[GP_REGIMETAXE4] [nvarchar] (3) NULL,
[GP_REGIMETAXE5] [nvarchar] (3) NULL,
[GP_PAYS] [nvarchar] (3) NULL,
[GP_TYPEPAYS] [nvarchar] (1) NULL,
[GP_GUIDWOT] [nvarchar] (36) NULL,
[GP_CODEUT] [nvarchar] (17) NULL,
[GP_DATEENLEVEMENT] [datetime] NULL,
[GP_DATEARRIVEETHEO] [datetime] NULL,
[GP_COMPTATIERS] [nvarchar] (3) NULL,
[GP_ARTICLECATA] [nvarchar] (17) NULL,
[GP_HISTORISE] [nvarchar] (1) NULL,
[GP_APPORTEURTIERS] [nvarchar] (17) NULL,
[GP_DEPOTTRANSIT] [nvarchar] (3) NULL,
[GP_REPRISEACTIV] [nvarchar] (3) NULL,
[GP_DATEENGAGEMENT] [datetime] NULL,
[GP_LITIGEFACT] [nvarchar] (1) NULL,
[GP_CODEAGENCE] [nvarchar] (6) NULL,
[GP_MANDAT] [int] NULL
)
GO
ALTER TABLE [psa].[ics_stg_cegid_comp_fra_procure_PIECE] ADD CONSTRAINT [PK_psa_ics_stg_cegid_comp_fra_procure_PIECE] PRIMARY KEY CLUSTERED  ([GP_NUMERO], [GP_SOUCHE])
GO
