CREATE TABLE [psa].[ics_stg_SAP_GBR_RSEG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_RSEG_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_RSEG_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[BELNR] [nvarchar] (10) NULL,
[GJAHR] [nvarchar] (4) NULL,
[BUZEI] [nvarchar] (6) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[ZEKKN] [nvarchar] (2) NULL,
[MATNR] [nvarchar] (18) NULL,
[BWKEY] [nvarchar] (4) NULL,
[BWTAR] [nvarchar] (10) NULL,
[BUKRS] [nvarchar] (4) NULL,
[WERKS] [nvarchar] (4) NULL,
[WRBTR] [decimal] (13, 2) NULL,
[SHKZG] [nvarchar] (1) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[TXJCD] [nvarchar] (15) NULL,
[MENGE] [decimal] (13, 3) NULL,
[BSTME] [nvarchar] (3) NULL,
[BPMNG] [decimal] (13, 3) NULL,
[BPRME] [nvarchar] (3) NULL,
[LBKUM] [decimal] (13, 3) NULL,
[VRKUM] [decimal] (13, 3) NULL,
[MEINS] [nvarchar] (3) NULL,
[PSTYP] [nvarchar] (1) NULL,
[KNTTP] [nvarchar] (1) NULL,
[BKLAS] [nvarchar] (4) NULL,
[EREKZ] [nvarchar] (1) NULL,
[EXKBE] [nvarchar] (1) NULL,
[XEKBZ] [nvarchar] (1) NULL,
[TBTKZ] [nvarchar] (1) NULL,
[SPGRP] [nvarchar] (1) NULL,
[SPGRM] [nvarchar] (1) NULL,
[SPGRT] [nvarchar] (1) NULL,
[SPGRG] [nvarchar] (1) NULL,
[SPGRV] [nvarchar] (1) NULL,
[SPGRQ] [nvarchar] (1) NULL,
[SPGRS] [nvarchar] (1) NULL,
[SPGRC] [nvarchar] (1) NULL,
[SPGREXT] [nvarchar] (1) NULL,
[BUSTW] [nvarchar] (4) NULL,
[XBLNR] [nvarchar] (16) NULL,
[XRUEB] [nvarchar] (1) NULL,
[BNKAN] [decimal] (13, 2) NULL,
[KSCHL] [nvarchar] (4) NULL,
[SALK3] [decimal] (13, 2) NULL,
[VMSAL] [decimal] (13, 2) NULL,
[XLIFO] [nvarchar] (1) NULL,
[LFBNR] [nvarchar] (10) NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFPOS] [nvarchar] (4) NULL,
[MATBF] [nvarchar] (18) NULL,
[RBMNG] [decimal] (13, 3) NULL,
[BPRBM] [decimal] (13, 3) NULL,
[RBWWR] [decimal] (13, 2) NULL,
[LFEHL] [nvarchar] (1) NULL,
[GRICD] [nvarchar] (2) NULL,
[GRIRG] [nvarchar] (3) NULL,
[GITYP] [nvarchar] (2) NULL,
[PACKNO] [nvarchar] (10) NULL,
[INTROW] [nvarchar] (10) NULL,
[SGTXT] [nvarchar] (50) NULL,
[XSKRL] [nvarchar] (1) NULL,
[KZMEK] [nvarchar] (1) NULL,
[MRMOK] [nvarchar] (1) NULL,
[STUNR] [nvarchar] (3) NULL,
[ZAEHK] [nvarchar] (2) NULL,
[STOCK_POSTING] [decimal] (13, 2) NULL,
[STOCK_POSTING_PP] [decimal] (13, 2) NULL,
[STOCK_POSTING_PY] [decimal] (13, 2) NULL,
[WEREC] [nvarchar] (1) NULL,
[LIFNR] [nvarchar] (10) NULL,
[FRBNR] [nvarchar] (16) NULL,
[XHISTMA] [nvarchar] (1) NULL,
[COMPLAINT_REASON] [nvarchar] (2) NULL,
[RETAMT_FC] [decimal] (13, 2) NULL,
[RETPC] [decimal] (5, 2) NULL,
[RETDUEDT] [datetime] NULL,
[XRETTAXNET] [nvarchar] (1) NULL,
[RE_ACCOUNT] [nvarchar] (10) NULL,
[ERP_CONTRACT_ID] [nvarchar] (10) NULL,
[ERP_CONTRACT_ITM] [nvarchar] (5) NULL,
[SRM_CONTRACT_ID] [nvarchar] (10) NULL,
[SRM_CONTRACT_ITM] [nvarchar] (10) NULL,
[CONT_PSTYP] [nvarchar] (1) NULL,
[SRVMAPKEY] [nvarchar] (10) NULL,
[CHARG] [nvarchar] (10) NULL,
[XCPRF] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_RSEG] ADD CONSTRAINT [AK_psa_ics_stg_SAP_GBR_RSEG_EtlRecordId] UNIQUE CLUSTERED  ([EtlRecordId])
GO
