CREATE TABLE [psa].[ICS_STG_SAP_GBR_KNA1]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LAND1] [nvarchar] (3) NULL,
[NAME1] [nvarchar] (35) NULL,
[NAME2] [nvarchar] (35) NULL,
[ORT01] [nvarchar] (35) NULL,
[PSTLZ] [nvarchar] (10) NULL,
[REGIO] [nvarchar] (3) NULL,
[SORTL] [nvarchar] (10) NULL,
[STRAS] [nvarchar] (35) NULL,
[TELF1] [nvarchar] (16) NULL,
[TELFX] [nvarchar] (31) NULL,
[XCPDK] [nvarchar] (1) NULL,
[ADRNR] [nvarchar] (10) NULL,
[MCOD1] [nvarchar] (25) NULL,
[MCOD2] [nvarchar] (25) NULL,
[MCOD3] [nvarchar] (25) NULL,
[ANRED] [nvarchar] (15) NULL,
[AUFSD] [nvarchar] (2) NULL,
[BAHNE] [nvarchar] (25) NULL,
[BAHNS] [nvarchar] (25) NULL,
[BBBNR] [nvarchar] (7) NULL,
[BBSNR] [nvarchar] (5) NULL,
[BEGRU] [nvarchar] (4) NULL,
[BRSCH] [nvarchar] (4) NULL,
[BUBKZ] [nvarchar] (1) NULL,
[DATLT] [nvarchar] (14) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[EXABL] [nvarchar] (1) NULL,
[FAKSD] [nvarchar] (2) NULL,
[FISKN] [nvarchar] (10) NULL,
[KNAZK] [nvarchar] (2) NULL,
[KNRZA] [nvarchar] (10) NULL,
[KONZS] [nvarchar] (10) NULL,
[KTOKD] [nvarchar] (4) NULL,
[KUKLA] [nvarchar] (2) NULL,
[LIFNR] [nvarchar] (10) NULL,
[LIFSD] [nvarchar] (2) NULL,
[LOCCO] [nvarchar] (10) NULL,
[LOEVM] [nvarchar] (1) NULL,
[NAME3] [nvarchar] (35) NULL,
[NAME4] [nvarchar] (35) NULL,
[NIELS] [nvarchar] (2) NULL,
[ORT02] [nvarchar] (35) NULL,
[PFACH] [nvarchar] (10) NULL,
[PSTL2] [nvarchar] (10) NULL,
[COUNC] [nvarchar] (3) NULL,
[CITYC] [nvarchar] (4) NULL,
[RPMKR] [nvarchar] (5) NULL,
[SPERR] [nvarchar] (1) NULL,
[SPRAS] [nvarchar] (1) NULL,
[STCD1] [nvarchar] (16) NULL,
[STCD2] [nvarchar] (11) NULL,
[STKZA] [nvarchar] (1) NULL,
[STKZU] [nvarchar] (1) NULL,
[TELBX] [nvarchar] (15) NULL,
[TELF2] [nvarchar] (16) NULL,
[TELTX] [nvarchar] (30) NULL,
[TELX1] [nvarchar] (30) NULL,
[LZONE] [nvarchar] (10) NULL,
[XZEMP] [nvarchar] (1) NULL,
[VBUND] [nvarchar] (6) NULL,
[STCEG] [nvarchar] (20) NULL,
[DEAR1] [nvarchar] (1) NULL,
[DEAR2] [nvarchar] (1) NULL,
[DEAR3] [nvarchar] (1) NULL,
[DEAR4] [nvarchar] (1) NULL,
[DEAR5] [nvarchar] (1) NULL,
[GFORM] [nvarchar] (2) NULL,
[BRAN1] [nvarchar] (10) NULL,
[BRAN2] [nvarchar] (10) NULL,
[BRAN3] [nvarchar] (10) NULL,
[BRAN4] [nvarchar] (10) NULL,
[BRAN5] [nvarchar] (10) NULL,
[EKONT] [nvarchar] (10) NULL,
[UMSAT] [decimal] (8, 2) NULL,
[UMJAH] [nvarchar] (4) NULL,
[UWAER] [nvarchar] (5) NULL,
[JMZAH] [nvarchar] (6) NULL,
[JMJAH] [nvarchar] (4) NULL,
[KATR1] [nvarchar] (2) NULL,
[KATR2] [nvarchar] (2) NULL,
[KATR3] [nvarchar] (2) NULL,
[KATR4] [nvarchar] (2) NULL,
[KATR5] [nvarchar] (2) NULL,
[KATR6] [nvarchar] (3) NULL,
[KATR7] [nvarchar] (3) NULL,
[KATR8] [nvarchar] (3) NULL,
[KATR9] [nvarchar] (3) NULL,
[KATR10] [nvarchar] (3) NULL,
[STKZN] [nvarchar] (1) NULL,
[UMSA1] [decimal] (15, 2) NULL,
[TXJCD] [nvarchar] (15) NULL,
[PERIV] [nvarchar] (2) NULL,
[ABRVW] [nvarchar] (3) NULL,
[INSPBYDEBI] [nvarchar] (1) NULL,
[INSPATDEBI] [nvarchar] (1) NULL,
[KTOCD] [nvarchar] (4) NULL,
[PFORT] [nvarchar] (35) NULL,
[WERKS] [nvarchar] (4) NULL,
[DTAMS] [nvarchar] (1) NULL,
[DTAWS] [nvarchar] (2) NULL,
[DUEFL] [nvarchar] (1) NULL,
[HZUOR] [nvarchar] (2) NULL,
[SPERZ] [nvarchar] (1) NULL,
[ETIKG] [nvarchar] (10) NULL,
[CIVVE] [nvarchar] (1) NULL,
[MILVE] [nvarchar] (1) NULL,
[KDKG1] [nvarchar] (2) NULL,
[KDKG2] [nvarchar] (2) NULL,
[KDKG3] [nvarchar] (2) NULL,
[KDKG4] [nvarchar] (2) NULL,
[KDKG5] [nvarchar] (2) NULL,
[XKNZA] [nvarchar] (1) NULL,
[FITYP] [nvarchar] (2) NULL,
[STCDT] [nvarchar] (2) NULL,
[STCD3] [nvarchar] (18) NULL,
[STCD4] [nvarchar] (18) NULL,
[STCD5] [nvarchar] (60) NULL,
[XICMS] [nvarchar] (1) NULL,
[XXIPI] [nvarchar] (1) NULL,
[XSUBT] [nvarchar] (3) NULL,
[CFOPC] [nvarchar] (2) NULL,
[TXLW1] [nvarchar] (3) NULL,
[TXLW2] [nvarchar] (3) NULL,
[CCC01] [nvarchar] (1) NULL,
[CCC02] [nvarchar] (1) NULL,
[CCC03] [nvarchar] (1) NULL,
[CCC04] [nvarchar] (1) NULL,
[CASSD] [nvarchar] (2) NULL,
[KNURL] [nvarchar] (132) NULL,
[J_1KFREPRE] [nvarchar] (10) NULL,
[J_1KFTBUS] [nvarchar] (30) NULL,
[J_1KFTIND] [nvarchar] (30) NULL,
[CONFS] [nvarchar] (1) NULL,
[UPDAT] [datetime] NULL,
[UPTIM] [datetime] NULL,
[NODEL] [nvarchar] (1) NULL,
[DEAR6] [nvarchar] (1) NULL,
[SUFRAMA] [nvarchar] (9) NULL,
[RG] [nvarchar] (11) NULL,
[EXP] [nvarchar] (3) NULL,
[UF] [nvarchar] (2) NULL,
[RGDATE] [datetime] NULL,
[RIC] [nvarchar] (11) NULL,
[RNE] [nvarchar] (10) NULL,
[RNEDATE] [datetime] NULL,
[CNAE] [nvarchar] (7) NULL,
[LEGALNAT] [nvarchar] (4) NULL,
[CRTN] [nvarchar] (1) NULL,
[ICMSTAXPAY] [nvarchar] (2) NULL,
[INDTYP] [nvarchar] (2) NULL,
[TDT] [nvarchar] (2) NULL,
[COMSIZE] [nvarchar] (2) NULL,
[DECREGPC] [nvarchar] (2) NULL,
[_VSO_R_PALHGT] [decimal] (13, 3) NULL,
[_VSO_R_PAL_UL] [nvarchar] (3) NULL,
[_VSO_R_PK_MAT] [nvarchar] (1) NULL,
[_VSO_R_MATPAL] [nvarchar] (18) NULL,
[_VSO_R_I_NO_LYR] [nvarchar] (2) NULL,
[_VSO_R_ONE_MAT] [nvarchar] (1) NULL,
[_VSO_R_ONE_SORT] [nvarchar] (1) NULL,
[_VSO_R_ULD_SIDE] [nvarchar] (1) NULL,
[_VSO_R_LOAD_PREF] [nvarchar] (1) NULL,
[_VSO_R_DPOINT] [nvarchar] (10) NULL,
[ALC] [nvarchar] (8) NULL,
[PMT_OFFICE] [nvarchar] (5) NULL,
[PSOFG] [nvarchar] (10) NULL,
[PSOIS] [nvarchar] (20) NULL,
[PSON1] [nvarchar] (35) NULL,
[PSON2] [nvarchar] (35) NULL,
[PSON3] [nvarchar] (35) NULL,
[PSOVN] [nvarchar] (35) NULL,
[PSOTL] [nvarchar] (20) NULL,
[PSOHS] [nvarchar] (6) NULL,
[PSOST] [nvarchar] (28) NULL,
[PSOO1] [nvarchar] (50) NULL,
[PSOO2] [nvarchar] (50) NULL,
[PSOO3] [nvarchar] (50) NULL,
[PSOO4] [nvarchar] (50) NULL,
[PSOO5] [nvarchar] (50) NULL,
[EtlRecordId] [bigint] NOT NULL,
[IsIncomplete] [char] (1) NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NOT NULL,
[EtlDeletedBy] [varchar] (200) NOT NULL,
[IsDeleted] [char] (1) NOT NULL
)
GO
