CREATE TABLE [psa].[ics_stg_SAP_GBR_VBUP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_VBUP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_VBUP_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNR] [nvarchar] (6) NULL,
[RFSTA] [nvarchar] (1) NULL,
[RFGSA] [nvarchar] (1) NULL,
[BESTA] [nvarchar] (1) NULL,
[LFSTA] [nvarchar] (1) NULL,
[LFGSA] [nvarchar] (1) NULL,
[WBSTA] [nvarchar] (1) NULL,
[FKSTA] [nvarchar] (1) NULL,
[FKSAA] [nvarchar] (1) NULL,
[ABSTA] [nvarchar] (1) NULL,
[GBSTA] [nvarchar] (1) NULL,
[KOSTA] [nvarchar] (1) NULL,
[LVSTA] [nvarchar] (1) NULL,
[UVALL] [nvarchar] (1) NULL,
[UVVLK] [nvarchar] (1) NULL,
[UVFAK] [nvarchar] (1) NULL,
[UVPRS] [nvarchar] (1) NULL,
[FKIVP] [nvarchar] (1) NULL,
[UVP01] [nvarchar] (1) NULL,
[UVP02] [nvarchar] (1) NULL,
[UVP03] [nvarchar] (1) NULL,
[UVP04] [nvarchar] (1) NULL,
[UVP05] [nvarchar] (1) NULL,
[PKSTA] [nvarchar] (1) NULL,
[KOQUA] [nvarchar] (1) NULL,
[COSTA] [nvarchar] (1) NULL,
[CMPPI] [nvarchar] (1) NULL,
[CMPPJ] [nvarchar] (1) NULL,
[UVPIK] [nvarchar] (1) NULL,
[UVPAK] [nvarchar] (1) NULL,
[UVWAK] [nvarchar] (1) NULL,
[DCSTA] [nvarchar] (1) NULL,
[RRSTA] [nvarchar] (1) NULL,
[VLSTP] [nvarchar] (1) NULL,
[FSSTA] [nvarchar] (1) NULL,
[LSSTA] [nvarchar] (1) NULL,
[PDSTA] [nvarchar] (1) NULL,
[MANEK] [nvarchar] (1) NULL,
[HDALL] [nvarchar] (1) NULL,
[LTSPS] [nvarchar] (1) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_VBUP] ADD CONSTRAINT [AK_psa_ics_stg_SAP_GBR_VBUP_EtlRecordId] UNIQUE CLUSTERED  ([EtlRecordId])
GO
