CREATE TABLE [psa].[ics_stg_baan_ttdpur001610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur001610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur001610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_cbrn] [varchar] (6) NULL,
[t_ccon] [int] NULL,
[t_ccor] [varchar] (3) NULL,
[t_ccrs] [varchar] (3) NULL,
[t_ccty] [varchar] (3) NULL,
[t_ccur] [varchar] (3) NULL,
[t_cdec] [varchar] (3) NULL,
[t_cfrw] [varchar] (3) NULL,
[t_clan] [varchar] (3) NULL,
[t_comp] [smallint] NULL,
[t_cotp] [varchar] (3) NULL,
[t_cpay] [varchar] (3) NULL,
[t_cplp] [varchar] (3) NULL,
[t_creg] [varchar] (3) NULL,
[t_cvyn] [tinyint] NULL,
[t_cwar] [varchar] (3) NULL,
[t_ddat] [datetime] NULL,
[t_exdt] [datetime] NULL,
[t_fixr] [tinyint] NULL,
[t_odis] [real] NULL,
[t_qdat] [datetime] NULL,
[t_qono] [int] NULL,
[t_qspa] [tinyint] NULL,
[t_ratf] [int] NULL,
[t_ratp] [float] NULL,
[t_rdat] [datetime] NULL,
[t_refa] [varchar] (30) NULL,
[t_refb] [varchar] (20) NULL,
[t_rpdt] [datetime] NULL,
[t_rsts] [tinyint] NULL,
[t_rtdt] [datetime] NULL,
[t_suno] [varchar] (6) NULL,
[t_txta] [int] NULL,
[t_txtb] [int] NULL
)
GO
