CREATE TABLE [psa].[ics_stg_Navision_BGR_Icopal Bulgaria$Purchase Header]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_BGR_Icopal Bulgaria$Purchase Header_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_BGR_Icopal Bulgaria$Purchase Header_IsIncomplete] DEFAULT ('N'),
[Applies-to_Doc__No_] [varchar] (20) NULL,
[Applies-to_Doc__Type] [int] NULL,
[Applies-to_ID] [varchar] (20) NULL,
[Area] [varchar] (10) NULL,
[Assigned_User_ID] [varchar] (20) NULL,
[Bal__Account_No_] [varchar] (20) NULL,
[Bal__Account_Type] [int] NULL,
[BizTalk_Document_Sent] [tinyint] NULL,
[BizTalk_Purch__Order_Cnfmn_] [tinyint] NULL,
[BizTalk_Purchase_Credit_Memo] [tinyint] NULL,
[BizTalk_Purchase_Invoice] [tinyint] NULL,
[BizTalk_Purchase_Order] [tinyint] NULL,
[BizTalk_Purchase_Quote] [tinyint] NULL,
[BizTalk_Purchase_Receipt] [tinyint] NULL,
[BizTalk_Request_for_Purch__Qte] [tinyint] NULL,
[Buy-from_Address] [varchar] (50) NULL,
[Buy-from_Address_2] [varchar] (50) NULL,
[Buy-from_City] [varchar] (30) NULL,
[Buy-from_Contact] [varchar] (50) NULL,
[Buy-from_Contact_No_] [varchar] (20) NULL,
[Buy-from_Country_Region_Code] [varchar] (10) NULL,
[Buy-from_County] [varchar] (30) NULL,
[Buy-from_IC_Partner_Code] [varchar] (20) NULL,
[Buy-from_Post_Code] [varchar] (20) NULL,
[Buy-from_Vendor_Name] [varchar] (50) NULL,
[Buy-from_Vendor_Name_2] [varchar] (50) NULL,
[Buy-from_Vendor_No_] [varchar] (20) NULL,
[Campaign_No_] [varchar] (20) NULL,
[Composed_By] [varchar] (30) NULL,
[Compress_Prepayment] [tinyint] NULL,
[Correction] [tinyint] NULL,
[Currency_Code] [varchar] (10) NULL,
[Currency_Factor] [decimal] (38, 20) NULL,
[Customs_Declaration_No_] [varchar] (30) NULL,
[Date_Received] [datetime] NULL,
[Date_Sent] [datetime] NULL,
[Debit_Memo] [tinyint] NULL,
[Do_not_include_in_VAT_Ledgers] [tinyint] NULL,
[Doc__No__Occurrence] [int] NULL,
[Document_Date] [datetime] NULL,
[Document_Type] [int] NOT NULL,
[Due_Date] [datetime] NULL,
[Entry_Point] [varchar] (10) NULL,
[Expected_Receipt_Date] [datetime] NULL,
[Gen__Bus__Posting_Group] [varchar] (10) NULL,
[IC_Direction] [int] NULL,
[IC_Status] [int] NULL,
[Identification_No_] [varchar] (13) NULL,
[Inbound_Whse__Handling_Time] [varchar] (32) NULL,
[Invoice] [tinyint] NULL,
[Invoice_Disc__Code] [varchar] (20) NULL,
[Invoice_Discount_Calculation] [int] NULL,
[Invoice_Discount_Value] [decimal] (38, 20) NULL,
[Language_Code] [varchar] (10) NULL,
[Last_Posting_No_] [varchar] (20) NULL,
[Last_Prepayment_No_] [varchar] (20) NULL,
[Last_Prepmt__Cr__Memo_No_] [varchar] (20) NULL,
[Last_Receiving_No_] [varchar] (20) NULL,
[Last_Return_Shipment_No_] [varchar] (20) NULL,
[Lead_Time_Calculation] [varchar] (32) NULL,
[Location_Code] [varchar] (10) NULL,
[No_] [varchar] (20) NOT NULL,
[No__Printed] [int] NULL,
[No__Series] [varchar] (10) NULL,
[On_Hold] [varchar] (3) NULL,
[Order_Address_Code] [varchar] (10) NULL,
[Order_Class] [varchar] (10) NULL,
[Order_Date] [datetime] NULL,
[Payment_Discount_%] [decimal] (38, 20) NULL,
[Payment_Method_Code] [varchar] (10) NULL,
[Payment_Terms_Code] [varchar] (10) NULL,
[Pay-to_Address] [varchar] (50) NULL,
[Pay-to_Address_2] [varchar] (50) NULL,
[Pay-to_City] [varchar] (30) NULL,
[Pay-to_Contact] [varchar] (50) NULL,
[Pay-to_Contact_No_] [varchar] (20) NULL,
[Pay-to_Country_Region_Code] [varchar] (10) NULL,
[Pay-to_County] [varchar] (30) NULL,
[Pay-to_IC_Partner_Code] [varchar] (20) NULL,
[Pay-to_Name] [varchar] (50) NULL,
[Pay-to_Name_2] [varchar] (50) NULL,
[Pay-to_Post_Code] [varchar] (20) NULL,
[Pay-to_Vendor_No_] [varchar] (20) NULL,
[Pmt__Discount_Date] [datetime] NULL,
[Posting_Date] [datetime] NULL,
[Posting_Description] [varchar] (50) NULL,
[Posting_from_Whse__Ref_] [int] NULL,
[Posting_No_] [varchar] (20) NULL,
[Posting_No__Series] [varchar] (10) NULL,
[Prepayment_%] [decimal] (38, 20) NULL,
[Prepayment_Due_Date] [datetime] NULL,
[Prepayment_No_] [varchar] (20) NULL,
[Prepayment_No__Series] [varchar] (10) NULL,
[Prepmt__Cr__Memo_No_] [varchar] (20) NULL,
[Prepmt__Cr__Memo_No__Series] [varchar] (10) NULL,
[Prepmt__Payment_Discount_%] [decimal] (38, 20) NULL,
[Prepmt__Payment_Terms_Code] [varchar] (10) NULL,
[Prepmt__Pmt__Discount_Date] [datetime] NULL,
[Prepmt__Posting_Description] [varchar] (50) NULL,
[Prices_Including_VAT] [tinyint] NULL,
[Promised_Receipt_Date] [datetime] NULL,
[Purchaser_Code] [varchar] (10) NULL,
[Quote_No_] [varchar] (20) NULL,
[Reason_Code] [varchar] (10) NULL,
[Receive] [tinyint] NULL,
[Receiving_No_] [varchar] (20) NULL,
[Receiving_No__Series] [varchar] (10) NULL,
[Requested_Receipt_Date] [datetime] NULL,
[Responsibility_Center] [varchar] (10) NULL,
[Return_Shipment_No_] [varchar] (20) NULL,
[Return_Shipment_No__Series] [varchar] (10) NULL,
[Sales_Protocol] [tinyint] NULL,
[Sell-to_Customer_No_] [varchar] (20) NULL,
[Send_IC_Document] [tinyint] NULL,
[Ship] [tinyint] NULL,
[Shipment_Method_Code] [varchar] (10) NULL,
[Ship-to_Address] [varchar] (50) NULL,
[Ship-to_Address_2] [varchar] (50) NULL,
[Ship-to_City] [varchar] (30) NULL,
[Ship-to_Code] [varchar] (10) NULL,
[Ship-to_Contact] [varchar] (50) NULL,
[Ship-to_Country_Region_Code] [varchar] (10) NULL,
[Ship-to_County] [varchar] (30) NULL,
[Ship-to_Name] [varchar] (50) NULL,
[Ship-to_Name_2] [varchar] (50) NULL,
[Ship-to_Post_Code] [varchar] (20) NULL,
[Shortcut_Dimension_1_Code] [varchar] (20) NULL,
[Shortcut_Dimension_2_Code] [varchar] (20) NULL,
[Speditor] [varchar] (10) NULL,
[Status] [int] NULL,
[Tax_Area_Code] [varchar] (20) NULL,
[Tax_Liable] [tinyint] NULL,
[Time_Received] [datetime] NULL,
[Time_Sent] [datetime] NULL,
[timestamp] [varbinary] (max) NULL,
[To_Invoice_Date] [datetime] NULL,
[To_Invoice_No_] [varchar] (20) NULL,
[Transaction_Specification] [varchar] (10) NULL,
[Transaction_Type] [varchar] (10) NULL,
[Transport_Country_Region_Code] [varchar] (10) NULL,
[Transport_Method] [varchar] (10) NULL,
[Unrealized_VAT] [tinyint] NULL,
[VAT_Base_Discount_%] [decimal] (38, 20) NULL,
[VAT_Bus__Posting_Group] [varchar] (10) NULL,
[VAT_Country_Region_Code] [varchar] (10) NULL,
[VAT_Exempt_Ground] [varchar] (10) NULL,
[VAT_Registration_No_] [varchar] (20) NULL,
[VAT_Settlement_Date] [datetime] NULL,
[VAT_Subject] [varchar] (30) NULL,
[Vendor_Authorization_No_] [varchar] (20) NULL,
[Vendor_Cr__Memo_No_] [varchar] (20) NULL,
[Vendor_Invoice_No_] [varchar] (20) NULL,
[Vendor_Order_No_] [varchar] (20) NULL,
[Vendor_Posting_Group] [varchar] (10) NULL,
[Vendor_Quote_No_] [varchar] (20) NULL,
[Vendor_Shipment_No_] [varchar] (20) NULL,
[Void] [tinyint] NULL,
[Void_Date] [datetime] NULL,
[Your_Reference] [varchar] (30) NULL
)
GO
ALTER TABLE [psa].[ics_stg_Navision_BGR_Icopal Bulgaria$Purchase Header] ADD CONSTRAINT [PK_psa_ics_stg_Navision_BGR_Icopal Bulgaria$Purchase Header] PRIMARY KEY CLUSTERED  ([Document_Type], [No_])
GO
