CREATE TABLE [psa].[ics_stg_SAP_GBR_LFB1]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_LFB1_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_LFB1_IsIncomplete] DEFAULT ('N'),
[AD_HASH] [nvarchar] (10) NULL,
[AKONT] [nvarchar] (10) NULL,
[ALTKN] [nvarchar] (10) NULL,
[ASSIGN_TEST] [nvarchar] (4) NULL,
[AVSND] [nvarchar] (1) NULL,
[BASIS_PNT] [decimal] (18, 0) NULL,
[BEGRU] [nvarchar] (4) NULL,
[BLNKZ] [nvarchar] (2) NULL,
[BUKRS] [nvarchar] (4) NOT NULL,
[BUSAB] [nvarchar] (2) NULL,
[CERDT] [datetime] NULL,
[CIIUCODE] [nvarchar] (4) NULL,
[CONFS] [nvarchar] (1) NULL,
[DATLZ] [datetime] NULL,
[EIKTO] [nvarchar] (12) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[FDGRV] [nvarchar] (10) NULL,
[FRGRP] [nvarchar] (4) NULL,
[GMVKZK] [nvarchar] (1) NULL,
[GRICD] [nvarchar] (2) NULL,
[GRIDT] [nvarchar] (2) NULL,
[GUZTE] [nvarchar] (4) NULL,
[HBKID] [nvarchar] (5) NULL,
[INTAD] [nvarchar] (130) NULL,
[J_SC_COMPDATE] [nvarchar] (3) NULL,
[J_SC_OFFSM] [nvarchar] (1) NULL,
[J_SC_OFFSR] [nvarchar] (3) NULL,
[J_SC_SUBCONTYPE] [nvarchar] (1) NULL,
[KULTG] [decimal] (18, 0) NULL,
[KVERM] [nvarchar] (30) NULL,
[LIFNR] [nvarchar] (10) NOT NULL,
[LNRZB] [nvarchar] (10) NULL,
[LNRZE] [nvarchar] (10) NULL,
[LOEVM] [nvarchar] (1) NULL,
[MANDT] [nvarchar] (3) NULL,
[MGRUP] [nvarchar] (2) NULL,
[MINDK] [nvarchar] (3) NULL,
[NODEL] [nvarchar] (1) NULL,
[PERNR] [nvarchar] (8) NULL,
[PREPAY_RELEVANT] [nvarchar] (1) NULL,
[QLAND] [nvarchar] (3) NULL,
[QSBGR] [nvarchar] (1) NULL,
[QSREC] [nvarchar] (2) NULL,
[QSSKZ] [nvarchar] (2) NULL,
[QSZDT] [datetime] NULL,
[QSZNR] [nvarchar] (10) NULL,
[REPRF] [nvarchar] (1) NULL,
[SPERR] [nvarchar] (1) NULL,
[TLFNS] [nvarchar] (30) NULL,
[TLFXS] [nvarchar] (31) NULL,
[TOGRR] [nvarchar] (4) NULL,
[TOGRU] [nvarchar] (4) NULL,
[UPDAT] [datetime] NULL,
[UPTIM] [datetime] NULL,
[UZAWE] [nvarchar] (2) NULL,
[VZSKZ] [nvarchar] (2) NULL,
[WEBTR] [decimal] (18, 0) NULL,
[XAUSZ] [nvarchar] (1) NULL,
[XDEZV] [nvarchar] (1) NULL,
[XEDIP] [nvarchar] (1) NULL,
[XLFZB] [nvarchar] (1) NULL,
[XPORE] [nvarchar] (1) NULL,
[XVERR] [nvarchar] (1) NULL,
[ZAHLS] [nvarchar] (1) NULL,
[ZGRUP] [nvarchar] (2) NULL,
[ZINDT] [datetime] NULL,
[ZINRT] [nvarchar] (2) NULL,
[ZSABE] [nvarchar] (15) NULL,
[ZTERM] [nvarchar] (4) NULL,
[ZUAWA] [nvarchar] (3) NULL,
[ZWELS] [nvarchar] (10) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_LFB1] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_LFB1_PK] PRIMARY KEY CLUSTERED  ([LIFNR], [BUKRS])
GO
EXEC sp_addextendedproperty N'IncludeInMerge', N'Y', 'SCHEMA', N'psa', 'TABLE', N'ics_stg_SAP_GBR_LFB1', NULL, NULL
GO
