CREATE TABLE [psa].[ics_stg_m3v7_MITWHL]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL,
[IsIncomplete] [char] (1) NOT NULL,
[MWCONO] [decimal] (3, 0) NOT NULL,
[MWWHLO] [nvarchar] (255) NOT NULL,
[MWWHNM] [nvarchar] (255) NULL,
[MWDIVI] [nvarchar] (255) NULL,
[MWFACI] [nvarchar] (255) NULL,
[MWWHTY] [nvarchar] (255) NULL,
[MWWHSY] [nvarchar] (255) NULL,
[MWWHPL] [nvarchar] (255) NULL,
[MWOREF] [nvarchar] (255) NULL,
[MWPHNO] [nvarchar] (255) NULL,
[MWCOMA] [nvarchar] (255) NULL,
[MWCUNO] [nvarchar] (255) NULL,
[MWSUNO] [nvarchar] (255) NULL,
[MWSDES] [nvarchar] (255) NULL,
[MWSHNM] [nvarchar] (255) NULL,
[MWPLIS] [nvarchar] (255) NULL,
[MWCSCD] [nvarchar] (255) NULL,
[MWECAR] [nvarchar] (255) NULL,
[MWVRNO] [nvarchar] (255) NULL,
[MWLNCD] [nvarchar] (255) NULL,
[MWCPWH] [nvarchar] (255) NULL,
[MWAUAD] [decimal] (1, 0) NULL,
[MWALWH] [nvarchar] (255) NULL,
[MWALAC] [decimal] (1, 0) NULL,
[MWRESP] [nvarchar] (255) NULL,
[MWTWSL] [nvarchar] (255) NULL,
[MWGEOC] [decimal] (9, 0) NULL,
[MWTAXC] [nvarchar] (255) NULL,
[MWUNST] [nvarchar] (255) NULL,
[MWTXID] [decimal] (13, 0) NULL,
[MWDTID] [decimal] (13, 0) NULL,
[MWAASQ] [decimal] (1, 0) NULL,
[MWDMF0] [decimal] (3, 0) NULL,
[MWDMF1] [decimal] (3, 0) NULL,
[MWDMF2] [decimal] (3, 0) NULL,
[MWDMF3] [decimal] (3, 0) NULL,
[MWDMF4] [decimal] (3, 0) NULL,
[MWDMF5] [decimal] (3, 0) NULL,
[MWDMF6] [decimal] (3, 0) NULL,
[MWDMF7] [decimal] (3, 0) NULL,
[MWDMF8] [decimal] (3, 0) NULL,
[MWDMF9] [decimal] (3, 0) NULL,
[MWINUL] [decimal] (1, 0) NULL,
[MWEPUL] [decimal] (1, 0) NULL,
[MWEXDL] [decimal] (1, 0) NULL,
[MWPIDL] [decimal] (1, 0) NULL,
[MWALWQ] [nvarchar] (255) NULL,
[MWITDL] [decimal] (1, 0) NULL,
[MWCDYN] [decimal] (1, 0) NULL,
[MWPATF] [decimal] (3, 0) NULL,
[MWPAHF] [decimal] (4, 0) NULL,
[MWPMTF] [decimal] (3, 0) NULL,
[MWPMHF] [decimal] (4, 0) NULL,
[MWDDLO] [nvarchar] (255) NULL,
[MWCDPD] [decimal] (1, 0) NULL,
[MWCDPM] [decimal] (1, 0) NULL,
[MWCALV] [nvarchar] (255) NULL,
[MWACGR] [nvarchar] (255) NULL,
[MWNBID] [nvarchar] (255) NULL,
[MWSTOF] [decimal] (1, 0) NULL,
[MWASOT] [decimal] (1, 0) NULL,
[MWDAAS] [decimal] (2, 0) NULL,
[MWLEAM] [decimal] (3, 0) NULL,
[MWDMFC] [decimal] (1, 0) NULL,
[MWLSPM] [decimal] (1, 0) NULL,
[MWRSTN] [nvarchar] (255) NULL,
[MWRGDT] [decimal] (8, 0) NULL,
[MWRGTM] [decimal] (6, 0) NULL,
[MWLMDT] [decimal] (8, 0) NULL,
[MWCHNO] [decimal] (3, 0) NULL,
[MWCHID] [nvarchar] (255) NULL,
[MWLMTS] [decimal] (18, 0) NULL
)
GO
ALTER TABLE [psa].[ics_stg_m3v7_MITWHL] ADD CONSTRAINT [psa_ics_stg_m3v7_MITWHL_PK] PRIMARY KEY CLUSTERED  ([MWCONO], [MWWHLO])
GO
