CREATE TABLE [psa].[ics_stg_SAP_GBR_EKKO]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKKO_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKKO_IsIncomplete] DEFAULT ('N'),
[ABGRU] [nvarchar] (2) NULL,
[ABSGR] [nvarchar] (2) NULL,
[ADDNR] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[AEDAT] [datetime] NULL,
[ANGDT] [datetime] NULL,
[ANGNR] [nvarchar] (10) NULL,
[AUREL_ALLOW] [nvarchar] (1) NULL,
[AUSNR] [nvarchar] (10) NULL,
[AUTLF] [nvarchar] (1) NULL,
[BEDAT] [datetime] NULL,
[BNDDT] [datetime] NULL,
[BSAKZ] [nvarchar] (1) NULL,
[BSART] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[BUDG_TYPE] [nvarchar] (2) NULL,
[BUKRS] [nvarchar] (4) NULL,
[BWBDT] [datetime] NULL,
[CHECK_TYPE] [nvarchar] (1) NULL,
[CON_DISTR_LEV] [nvarchar] (1) NULL,
[CON_OTB_REQ] [nvarchar] (1) NULL,
[CON_PREBOOK_LEV] [nvarchar] (1) NULL,
[CONTRACT_ALLOW] [nvarchar] (1) NULL,
[DELPER_ALLOW] [nvarchar] (1) NULL,
[DESCRIPTION] [nvarchar] (40) NULL,
[DPAMT] [decimal] (18, 0) NULL,
[DPDAT] [datetime] NULL,
[DPPCT] [decimal] (18, 0) NULL,
[DPTYP] [nvarchar] (4) NULL,
[EBELN] [nvarchar] (10) NOT NULL,
[EINDT_ALLOW] [nvarchar] (1) NULL,
[EKGRP] [nvarchar] (3) NULL,
[EKGRP_ALLOW] [nvarchar] (1) NULL,
[EKORG] [nvarchar] (4) NULL,
[EQ_EINDT] [datetime] NULL,
[EQ_WERKS] [nvarchar] (4) NULL,
[ERNAM] [nvarchar] (12) NULL,
[EXNUM] [nvarchar] (10) NULL,
[FIXPO] [nvarchar] (1) NULL,
[FIXPO_ALLOW] [nvarchar] (1) NULL,
[FORCE_CNT] [nvarchar] (6) NULL,
[FORCE_ID] [nvarchar] (32) NULL,
[FRGGR] [nvarchar] (2) NULL,
[FRGKE] [nvarchar] (1) NULL,
[FRGRL] [nvarchar] (1) NULL,
[FRGSX] [nvarchar] (2) NULL,
[FRGZU] [nvarchar] (8) NULL,
[GWLDT] [datetime] NULL,
[HIERARCHY_EXISTS] [nvarchar] (1) NULL,
[IHRAN] [datetime] NULL,
[IHREZ] [nvarchar] (12) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[KALSM] [nvarchar] (6) NULL,
[KDATB] [datetime] NULL,
[KDATE] [datetime] NULL,
[KEY_ID] [nvarchar] (16) NULL,
[KEY_ID_ALLOW] [nvarchar] (1) NULL,
[KNUMV] [nvarchar] (10) NULL,
[KONNR] [nvarchar] (10) NULL,
[KORNR] [nvarchar] (1) NULL,
[KTWRT] [decimal] (18, 0) NULL,
[KUFIX] [nvarchar] (1) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LANDS] [nvarchar] (3) NULL,
[LBLIF] [nvarchar] (10) NULL,
[LEGAL_CONTRACT] [nvarchar] (40) NULL,
[LIFNR] [nvarchar] (10) NULL,
[LIFRE] [nvarchar] (10) NULL,
[LLIEF] [nvarchar] (10) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[LOGSY] [nvarchar] (10) NULL,
[LPHIS] [nvarchar] (1) NULL,
[LPONR] [nvarchar] (5) NULL,
[MANDT] [nvarchar] (3) NULL,
[MEMORY] [nvarchar] (1) NULL,
[MEMORYTYPE] [nvarchar] (1) NULL,
[MSR_ID] [nvarchar] (10) NULL,
[OTB_COND_TYPE] [nvarchar] (4) NULL,
[OTB_CURR] [nvarchar] (5) NULL,
[OTB_LEVEL] [nvarchar] (1) NULL,
[OTB_REASON] [nvarchar] (3) NULL,
[OTB_RES_VALUE] [decimal] (18, 0) NULL,
[OTB_SPEC_VALUE] [decimal] (18, 0) NULL,
[OTB_STATUS] [nvarchar] (1) NULL,
[OTB_VALUE] [decimal] (18, 0) NULL,
[PINCR] [nvarchar] (5) NULL,
[POHF_TYPE] [nvarchar] (1) NULL,
[PROCSTAT] [nvarchar] (2) NULL,
[PSTYP_ALLOW] [nvarchar] (1) NULL,
[REASON_CODE] [nvarchar] (4) NULL,
[RELEASE_DATE] [datetime] NULL,
[RELOC_ID] [nvarchar] (10) NULL,
[RELOC_SEQ_ID] [nvarchar] (4) NULL,
[RESWK] [nvarchar] (4) NULL,
[RETPC] [decimal] (18, 0) NULL,
[RETTP] [nvarchar] (1) NULL,
[REVNO] [nvarchar] (8) NULL,
[RLWRT] [decimal] (18, 0) NULL,
[SCMPROC] [nvarchar] (1) NULL,
[SPR_RSN_PROFILE] [nvarchar] (4) NULL,
[SPRAS] [nvarchar] (1) NULL,
[STAFO] [nvarchar] (6) NULL,
[STAKO] [nvarchar] (1) NULL,
[STATU] [nvarchar] (1) NULL,
[STCEG] [nvarchar] (20) NULL,
[STCEG_L] [nvarchar] (3) NULL,
[SUBMI] [nvarchar] (10) NULL,
[TELF1] [nvarchar] (16) NULL,
[THRESHOLD_EXISTS] [nvarchar] (1) NULL,
[UNSEZ] [nvarchar] (12) NULL,
[UPINC] [nvarchar] (5) NULL,
[VERKF] [nvarchar] (30) NULL,
[WAERS] [nvarchar] (5) NULL,
[WEAKT] [nvarchar] (1) NULL,
[WERKS_ALLOW] [nvarchar] (1) NULL,
[WKURS] [decimal] (18, 0) NULL,
[ZBD1P] [decimal] (18, 0) NULL,
[ZBD1T] [decimal] (18, 0) NULL,
[ZBD2P] [decimal] (18, 0) NULL,
[ZBD2T] [decimal] (18, 0) NULL,
[ZBD3T] [decimal] (18, 0) NULL,
[ZTERM] [nvarchar] (4) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EKKO] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_EKKO_PK] PRIMARY KEY CLUSTERED  ([EBELN])
GO
