CREATE TABLE [psa].[ICS_STG_SAP_GBR_MARD]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[MATNR] [nvarchar] (18) NULL,
[WERKS] [nvarchar] (4) NULL,
[LGORT] [nvarchar] (4) NULL,
[PSTAT] [nvarchar] (15) NULL,
[LVORM] [nvarchar] (1) NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFMON] [nvarchar] (2) NULL,
[SPERR] [nvarchar] (1) NULL,
[LABST] [decimal] (13, 3) NULL,
[UMLME] [decimal] (13, 3) NULL,
[INSME] [decimal] (13, 3) NULL,
[EINME] [decimal] (13, 3) NULL,
[SPEME] [decimal] (13, 3) NULL,
[RETME] [decimal] (13, 3) NULL,
[VMLAB] [decimal] (13, 3) NULL,
[VMUML] [decimal] (13, 3) NULL,
[VMINS] [decimal] (13, 3) NULL,
[VMEIN] [decimal] (13, 3) NULL,
[VMSPE] [decimal] (13, 3) NULL,
[VMRET] [decimal] (13, 3) NULL,
[KZILL] [nvarchar] (3) NULL,
[KZILQ] [nvarchar] (3) NULL,
[KZILE] [nvarchar] (3) NULL,
[KZILS] [nvarchar] (3) NULL,
[KZVLL] [nvarchar] (3) NULL,
[KZVLQ] [nvarchar] (3) NULL,
[KZVLE] [nvarchar] (3) NULL,
[KZVLS] [nvarchar] (3) NULL,
[DISKZ] [nvarchar] (1) NULL,
[LSOBS] [nvarchar] (2) NULL,
[LMINB] [decimal] (13, 3) NULL,
[LBSTF] [decimal] (13, 3) NULL,
[HERKL] [nvarchar] (3) NULL,
[EXPPG] [nvarchar] (1) NULL,
[EXVER] [nvarchar] (2) NULL,
[LGPBE] [nvarchar] (10) NULL,
[KLABS] [decimal] (13, 3) NULL,
[KINSM] [decimal] (13, 3) NULL,
[KEINM] [decimal] (13, 3) NULL,
[KSPEM] [decimal] (13, 3) NULL,
[DLINL] [datetime] NULL,
[PRCTL] [nvarchar] (10) NULL,
[ERSDA] [datetime] NULL,
[VKLAB] [decimal] (13, 2) NULL,
[VKUML] [decimal] (13, 2) NULL,
[LWMKB] [nvarchar] (3) NULL,
[BSKRF] [float] NULL,
[MDRUE] [nvarchar] (1) NULL,
[MDJIN] [nvarchar] (4) NULL,
[EtlRecordId] [bigint] NOT NULL,
[IsIncomplete] [char] (1) NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NOT NULL,
[EtlDeletedBy] [varchar] (200) NOT NULL,
[IsDeleted] [char] (1) NOT NULL
)
GO
