CREATE TABLE [psa].[ics_stg_SAP_SVK_EKBE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_EKBE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_EKBE_IsIncomplete] DEFAULT ('N'),
[AREWB] [decimal] (13, 2) NULL,
[AREWR] [decimal] (13, 2) NULL,
[AREWW] [decimal] (13, 2) NULL,
[BAMNG] [decimal] (13, 3) NULL,
[BEKKN] [nvarchar] (2) NULL,
[BELNR] [nvarchar] (10) NOT NULL,
[BEWTP] [nvarchar] (1) NULL,
[BLDAT] [nvarchar] (8) NULL,
[BPMNG] [decimal] (13, 3) NULL,
[BPWES] [decimal] (13, 3) NULL,
[BUDAT] [nvarchar] (8) NULL,
[BUZEI] [nvarchar] (4) NOT NULL,
[BWART] [nvarchar] (3) NULL,
[BWTAR] [nvarchar] (10) NULL,
[CHARG] [nvarchar] (10) NULL,
[CPUDT] [nvarchar] (8) NULL,
[CPUTM] [nvarchar] (6) NULL,
[DMBTR] [decimal] (13, 2) NULL,
[EBELN] [nvarchar] (10) NOT NULL,
[EBELP] [nvarchar] (5) NOT NULL,
[ELIKZ] [nvarchar] (1) NULL,
[EMATN] [nvarchar] (18) NULL,
[ERNAM] [nvarchar] (12) NULL,
[ET_UPD] [nvarchar] (1) NULL,
[ETENS] [nvarchar] (4) NULL,
[EVERE] [nvarchar] (2) NULL,
[GJAHR] [nvarchar] (4) NOT NULL,
[GRUND] [nvarchar] (4) NULL,
[HSWAE] [nvarchar] (5) NULL,
[INTROW] [nvarchar] (10) NULL,
[KNUMV] [nvarchar] (10) NULL,
[LEMIN] [nvarchar] (1) NULL,
[LFBNR] [nvarchar] (10) NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFPOS] [nvarchar] (4) NULL,
[LSMEH] [nvarchar] (3) NULL,
[LSMNG] [decimal] (13, 3) NULL,
[MANDT] [nvarchar] (3) NOT NULL,
[MATNR] [nvarchar] (18) NULL,
[MENGE] [decimal] (13, 3) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[PACKNO] [nvarchar] (10) NULL,
[QTY_DIFF] [decimal] (13, 3) NULL,
[REEWR] [decimal] (13, 2) NULL,
[REFWR] [decimal] (13, 2) NULL,
[REWRB] [decimal] (13, 2) NULL,
[SAPRL] [nvarchar] (4) NULL,
[SHKZG] [nvarchar] (1) NULL,
[SRVPOS] [nvarchar] (18) NULL,
[VGABE] [nvarchar] (1) NOT NULL,
[WAERS] [nvarchar] (5) NULL,
[WERKS] [nvarchar] (4) NULL,
[WESBS] [decimal] (13, 3) NULL,
[WRBTR] [decimal] (13, 2) NULL,
[XBLNR] [nvarchar] (16) NULL,
[XUNPL] [nvarchar] (1) NULL,
[XWOFF] [nvarchar] (1) NULL,
[XWSBR] [nvarchar] (1) NULL,
[ZEKKN] [nvarchar] (2) NOT NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_SVK_EKBE] ADD CONSTRAINT [PK_psa_ics_stg_SAP_SVK_EKBE] PRIMARY KEY CLUSTERED  ([BUZEI], [BELNR], [GJAHR], [VGABE], [ZEKKN], [EBELP], [EBELN], [MANDT])
GO
