CREATE TABLE [psa].[ics_stg_aspect4_modmtbl]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_aspect4_modmtbl_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_aspect4_modmtbl_IsIncomplete] DEFAULT ('N'),
[MODM_RECSTS] [decimal] (1, 0) NULL,
[MODM_RECID] [nvarchar] (2) NULL,
[MODM_TYPE] [nvarchar] (2) NULL,
[MODM_NR] [decimal] (9, 0) NULL,
[MODM_LLQBNR] [decimal] (4, 0) NULL,
[MODM_LINIE] [decimal] (4, 0) NULL,
[MODM_KONCRN] [decimal] (3, 0) NULL,
[MODM_FIRMA] [decimal] (3, 0) NULL,
[MODM_JOUNR] [decimal] (9, 0) NULL,
[MODM_BILNR] [decimal] (9, 0) NULL,
[MODM_BILDT] [decimal] (8, 0) NULL,
[MODM_BILTXT] [nvarchar] (255) NULL,
[MODM_REGID] [nvarchar] (8) NULL,
[MODM_LEVNR] [nvarchar] (16) NULL,
[MODM_VARENR] [nvarchar] (16) NULL,
[MODM_UDF1] [nvarchar] (5) NULL,
[MODM_UDF2] [nvarchar] (5) NULL,
[MODM_UDF3] [nvarchar] (5) NULL,
[MODM_UDF4] [nvarchar] (5) NULL,
[MODM_UDF5] [nvarchar] (5) NULL,
[MODM_LAGER] [nvarchar] (8) NULL,
[MODM_PARTI] [nvarchar] (24) NULL,
[MODM_LOKAT] [nvarchar] (10) NULL,
[MODM_ANTAL] [decimal] (13, 5) NULL,
[MODM_ANTALB] [decimal] (13, 5) NULL,
[MODM_SBELQB] [decimal] (11, 2) NULL,
[MODM_KBELQB] [decimal] (11, 2) NULL,
[MODM_OBELQB] [decimal] (11, 2) NULL,
[MODM_VREGN] [nvarchar] (2) NULL,
[MODM_LREGN] [nvarchar] (2) NULL,
[MODM_DREGN] [nvarchar] (2) NULL,
[MODM_AREGN] [nvarchar] (2) NULL,
[MODM_DIST] [nvarchar] (8) NULL,
[MODM_VAREB] [nvarchar] (16) NULL,
[MODM_UDF1B] [nvarchar] (5) NULL,
[MODM_UDF2B] [nvarchar] (5) NULL,
[MODM_UDF3B] [nvarchar] (5) NULL,
[MODM_UDF4B] [nvarchar] (5) NULL,
[MODM_UDF5B] [nvarchar] (5) NULL,
[MODM_BEST] [decimal] (13, 5) NULL,
[MODM_BESTB] [decimal] (13, 5) NULL,
[MODM_OBEST] [decimal] (13, 5) NULL,
[MODM_OBESTB] [decimal] (13, 5) NULL,
[MODM_LEVTER] [decimal] (8, 0) NULL,
[MODM_OPRTER] [decimal] (8, 0) NULL,
[MODM_QNSTER] [decimal] (8, 0) NULL,
[MODM_OPRDT] [decimal] (8, 0) NULL,
[MODM_OPRAF] [nvarchar] (10) NULL,
[MODM_PROJNR] [decimal] (9, 0) NULL,
[MODM_AARSAG] [nvarchar] (5) NULL,
[MODM_IOART] [nvarchar] (2) NULL,
[MODM_BEHTYP] [nvarchar] (2) NULL,
[MODM_MARSAG] [nvarchar] (5) NULL,
[MODM_TS] [decimal] (8, 0) NULL,
[MODM_FJOUNR] [decimal] (9, 0) NULL,
[MODM_FBILAG] [decimal] (9, 0) NULL,
[MODM_MTCHAF] [nvarchar] (10) NULL,
[MODM_UDLID] [nvarchar] (30) NULL
)
GO
ALTER TABLE [psa].[ics_stg_aspect4_modmtbl] ADD CONSTRAINT [PK_psa_ics_stg_aspect4_modmtbl] PRIMARY KEY CLUSTERED  ([EtlRecordId])
GO
EXEC sp_addextendedproperty N'IncludeInMerge', N'Y', 'SCHEMA', N'psa', 'TABLE', N'ics_stg_aspect4_modmtbl', NULL, NULL
GO
