CREATE TABLE [psa].[ics_stg_SAP_GBR_T006]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_T006_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_T006_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[MSEHI] [nvarchar] (3) NULL,
[KZEX3] [nvarchar] (1) NULL,
[KZEX6] [nvarchar] (1) NULL,
[ANDEC] [int] NULL,
[KZKEH] [nvarchar] (1) NULL,
[KZWOB] [nvarchar] (1) NULL,
[KZ1EH] [nvarchar] (1) NULL,
[KZ2EH] [nvarchar] (1) NULL,
[DIMID] [nvarchar] (6) NULL,
[ZAEHL] [bigint] NULL,
[NENNR] [bigint] NULL,
[EXP10] [int] NULL,
[ADDKO] [decimal] (9, 6) NULL,
[EXPON] [int] NULL,
[DECAN] [int] NULL,
[ISOCODE] [nvarchar] (3) NULL,
[PRIMARY] [nvarchar] (1) NULL,
[TEMP_VALUE] [float] NULL,
[TEMP_UNIT] [nvarchar] (3) NULL,
[FAMUNIT] [nvarchar] (1) NULL,
[PRESS_VAL] [float] NULL,
[PRESS_UNIT] [nvarchar] (3) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_T006] ADD CONSTRAINT [AK_psa_ics_stg_SAP_GBR_T006_EtlRecordId] UNIQUE CLUSTERED  ([EtlRecordId])
GO
