CREATE TABLE [psa].[ICS_STG_SAP_DEU_VBPA]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNR] [nvarchar] (6) NULL,
[PARVW] [nvarchar] (2) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LIFNR] [nvarchar] (10) NULL,
[PERNR] [nvarchar] (8) NULL,
[PARNR] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[ABLAD] [nvarchar] (25) NULL,
[LAND1] [nvarchar] (3) NULL,
[ADRDA] [nvarchar] (1) NULL,
[XCPDK] [nvarchar] (1) NULL,
[HITYP] [nvarchar] (1) NULL,
[PRFRE] [nvarchar] (1) NULL,
[BOKRE] [nvarchar] (1) NULL,
[HISTUNR] [nvarchar] (2) NULL,
[KNREF] [nvarchar] (30) NULL,
[LZONE] [nvarchar] (10) NULL,
[HZUOR] [nvarchar] (2) NULL,
[STCEG] [nvarchar] (20) NULL,
[PARVW_FF] [nvarchar] (1) NULL,
[ADRNP] [nvarchar] (10) NULL,
[KALE] [nvarchar] (1) NULL,
[EtlRecordId] [bigint] NOT NULL,
[IsIncomplete] [char] (1) NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NOT NULL,
[EtlDeletedBy] [varchar] (200) NOT NULL,
[IsDeleted] [char] (1) NOT NULL
)
GO
