CREATE TABLE [psa].[ICS_STG_SAP_GBR_MARM]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[MATNR] [nvarchar] (18) NULL,
[MEINH] [nvarchar] (3) NULL,
[UMREZ] [decimal] (5, 0) NULL,
[UMREN] [decimal] (5, 0) NULL,
[EANNR] [nvarchar] (13) NULL,
[EAN11] [nvarchar] (18) NULL,
[NUMTP] [nvarchar] (2) NULL,
[LAENG] [decimal] (13, 3) NULL,
[BREIT] [decimal] (13, 3) NULL,
[HOEHE] [decimal] (13, 3) NULL,
[MEABM] [nvarchar] (3) NULL,
[VOLUM] [decimal] (13, 3) NULL,
[VOLEH] [nvarchar] (3) NULL,
[BRGEW] [decimal] (13, 3) NULL,
[GEWEI] [nvarchar] (3) NULL,
[MESUB] [nvarchar] (3) NULL,
[ATINN] [nvarchar] (10) NULL,
[MESRT] [nvarchar] (2) NULL,
[XFHDW] [nvarchar] (1) NULL,
[XBEWW] [nvarchar] (1) NULL,
[KZWSO] [nvarchar] (1) NULL,
[MSEHI] [nvarchar] (3) NULL,
[BFLME_MARM] [nvarchar] (1) NULL,
[GTIN_VARIANT] [nvarchar] (2) NULL,
[NEST_FTR] [decimal] (3, 0) NULL,
[MAX_STACK] [smallint] NULL,
[CAPAUSE] [decimal] (15, 3) NULL,
[TY2TQ] [nvarchar] (1) NULL,
[EtlRecordId] [bigint] NOT NULL,
[IsIncomplete] [char] (1) NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NOT NULL,
[EtlDeletedBy] [varchar] (200) NOT NULL,
[IsDeleted] [char] (1) NOT NULL
)
GO
