CREATE TABLE [psa].[ics_stg_Symfonia_MG]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MG_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Symfonia_MG_IsIncomplete] DEFAULT ('N'),
[aktywny] [bit] NULL,
[anulowany] [smallint] NULL,
[bufor] [smallint] NULL,
[createdBy] [int] NULL,
[createdDate] [datetime] NULL,
[data] [datetime] NULL,
[datasp] [datetime] NULL,
[exp_fk] [smallint] NULL,
[flag] [smallint] NULL,
[grupacen] [smallint] NULL,
[guid] [uniqueidentifier] NULL,
[id] [int] NOT NULL,
[iddokkoryg] [int] NULL,
[info] [smallint] NULL,
[jpk] [smallint] NULL,
[katalog] [int] NULL,
[khadid] [int] NULL,
[khdzial] [int] NULL,
[khid] [int] NULL,
[kod] [varchar] (40) NULL,
[magazyn] [int] NULL,
[modifiedBy] [int] NULL,
[modifiedDate] [datetime] NULL,
[nazwa] [varchar] (40) NULL,
[netto] [float] NULL,
[odebrane] [varchar] (40) NULL,
[ok] [smallint] NULL,
[okres] [smallint] NULL,
[opis] [varchar] (80) NULL,
[przychod] [float] NULL,
[rejestrVat] [int] NULL,
[rodzaj] [int] NULL,
[rozchod] [float] NULL,
[rozlmg] [smallint] NULL,
[rr] [smallint] NULL,
[schemat] [varchar] (4) NULL,
[seria] [varchar] (5) NULL,
[seriadzial] [int] NULL,
[serianr] [int] NULL,
[statusFK] [smallint] NULL,
[statusRDF] [smallint] NULL,
[subtyp] [smallint] NULL,
[super] [int] NULL,
[termin] [datetime] NULL,
[typ] [smallint] NULL,
[typ_dk] [varchar] (4) NULL,
[wartk] [float] NULL,
[wartoscWz] [float] NULL,
[wystawil] [int] NULL,
[znacznik] [smallint] NULL
)
GO
ALTER TABLE [psa].[ics_stg_Symfonia_MG] ADD CONSTRAINT [PK_psa_ics_stg_Symfonia_MG] PRIMARY KEY CLUSTERED  ([id])
GO
