CREATE TABLE [psa].[ics_stg_M3V10vil_POL_MPOEXP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_MPOEXP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_MPOEXP_IsIncomplete] DEFAULT ('N'),
[IVACIN] [numeric] (15, 2) NULL,
[IVBANO] [nvarchar] (20) NOT NULL,
[IVCDSE] [numeric] (18, 0) NOT NULL,
[IVCEID] [nchar] (6) NOT NULL,
[IVCEVA] [numeric] (15, 2) NULL,
[IVCEVJ] [numeric] (15, 2) NULL,
[IVCHID] [nchar] (10) NULL,
[IVCHNO] [numeric] (3, 0) NULL,
[IVCONO] [numeric] (18, 0) NOT NULL,
[IVCUCD] [nchar] (3) NULL,
[IVEXIC] [numeric] (1, 0) NULL,
[IVEXTY] [numeric] (18, 0) NOT NULL,
[IVIVCQ] [numeric] (1, 0) NULL,
[IVLMDT] [numeric] (8, 0) NULL,
[IVOVHE] [numeric] (15, 2) NULL,
[IVPNLI] [numeric] (18, 0) NOT NULL,
[IVPNLS] [numeric] (18, 0) NOT NULL,
[IVPOOV] [numeric] (1, 0) NULL,
[IVPUNO] [nchar] (7) NOT NULL,
[IVREPN] [numeric] (18, 0) NOT NULL,
[IVRGDT] [numeric] (8, 0) NULL,
[IVRGTM] [numeric] (6, 0) NULL,
[IVTHPR] [numeric] (1, 0) NULL,
[IVWSOP] [nchar] (2) NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_MPOEXP] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_MPOEXP] PRIMARY KEY CLUSTERED  ([IVBANO], [IVCDSE], [IVCEID], [IVCONO], [IVEXTY], [IVPNLI], [IVPNLS], [IVPUNO], [IVREPN])
GO
