CREATE TABLE [psa].[ics_stg_SAP_GBR_EINE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_EINE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_GBR_EINE_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[INFNR] [nvarchar] (10) NULL,
[EKORG] [nvarchar] (4) NULL,
[ESOKZ] [nvarchar] (1) NULL,
[WERKS] [nvarchar] (4) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[EKGRP] [nvarchar] (3) NULL,
[WAERS] [nvarchar] (5) NULL,
[BONUS] [nvarchar] (1) NULL,
[MGBON] [nvarchar] (1) NULL,
[MINBM] [decimal] (13, 3) NULL,
[NORBM] [decimal] (13, 3) NULL,
[APLFZ] [decimal] (3, 0) NULL,
[UEBTO] [decimal] (3, 1) NULL,
[UEBTK] [nvarchar] (1) NULL,
[UNTTO] [decimal] (3, 1) NULL,
[ANGNR] [nvarchar] (10) NULL,
[ANGDT] [datetime] NULL,
[ANFNR] [nvarchar] (10) NULL,
[ANFPS] [nvarchar] (5) NULL,
[ABSKZ] [nvarchar] (1) NULL,
[AMODV] [datetime] NULL,
[AMODB] [datetime] NULL,
[AMOBM] [decimal] (15, 3) NULL,
[AMOBW] [decimal] (15, 2) NULL,
[AMOAM] [decimal] (15, 3) NULL,
[AMOAW] [decimal] (15, 2) NULL,
[AMORS] [nvarchar] (1) NULL,
[BSTYP] [nvarchar] (1) NULL,
[EBELN] [nvarchar] (10) NULL,
[EBELP] [nvarchar] (5) NULL,
[DATLB] [datetime] NULL,
[NETPR] [decimal] (11, 2) NULL,
[PEINH] [decimal] (5, 0) NULL,
[BPRME] [nvarchar] (3) NULL,
[PRDAT] [datetime] NULL,
[BPUMZ] [decimal] (5, 0) NULL,
[BPUMN] [decimal] (5, 0) NULL,
[MTXNO] [nvarchar] (1) NULL,
[WEBRE] [nvarchar] (1) NULL,
[EFFPR] [decimal] (11, 2) NULL,
[EKKOL] [nvarchar] (4) NULL,
[SKTOF] [nvarchar] (1) NULL,
[KZABS] [nvarchar] (1) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[BWTAR] [nvarchar] (10) NULL,
[EBONU] [nvarchar] (2) NULL,
[EVERS] [nvarchar] (2) NULL,
[EXPRF] [nvarchar] (8) NULL,
[BSTAE] [nvarchar] (4) NULL,
[MEPRF] [nvarchar] (1) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[XERSN] [nvarchar] (1) NULL,
[EBON2] [nvarchar] (2) NULL,
[EBON3] [nvarchar] (2) NULL,
[EBONF] [nvarchar] (1) NULL,
[MHDRZ] [decimal] (4, 0) NULL,
[VERID] [nvarchar] (4) NULL,
[BSTMA] [decimal] (13, 3) NULL,
[RDPRF] [nvarchar] (4) NULL,
[MEGRU] [nvarchar] (4) NULL,
[J_1BNBM] [nvarchar] (16) NULL,
[SPE_CRE_REF_DOC] [nvarchar] (1) NULL,
[IPRKZ] [nvarchar] (1) NULL,
[CO_ORDER] [nvarchar] (1) NULL,
[VENDOR_RMA_REQ] [nvarchar] (1) NULL,
[MRPIND] [nvarchar] (1) NULL,
[TRANSPORT_CHAIN] [nvarchar] (10) NULL,
[STAGING_TIME] [decimal] (3, 0) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EINE] ADD CONSTRAINT [AK_psa_ics_stg_SAP_GBR_EINE_EtlRecordId] UNIQUE CLUSTERED  ([EtlRecordId])
GO
