CREATE TABLE [psa].[ics_stg_Navision_Rom_Live Icopal Romania$Purchases&PayablesSetup]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_Rom_Live Icopal Romania1812$Purchases & Payables Setup_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_Navision_Rom_Live Icopal Romania1812$Purchases & Payables Setup_IsIncomplete] DEFAULT ('N'),
[Allow_VAT_Difference] [tinyint] NULL,
[Appln__between_Currencies] [int] NULL,
[Blanket_Order_Nos_] [varchar] (10) NULL,
[Calc__Inv__Disc__per_VAT_ID] [tinyint] NULL,
[Calc__Inv__Discount] [tinyint] NULL,
[Copy_Cmts_Ret_Ord__to_Cr__Memo] [tinyint] NULL,
[Copy_Cmts_Ret_Ord__to_Ret_Shpt] [tinyint] NULL,
[Copy_Comments_Blanket_to_Order] [tinyint] NULL,
[Copy_Comments_Order_to_Invoice] [tinyint] NULL,
[Copy_Comments_Order_to_Receipt] [tinyint] NULL,
[Credit_Memo_Nos_] [varchar] (10) NULL,
[Custom_Invoice_No__Mandatory] [tinyint] NULL,
[Discount_Posting] [int] NULL,
[Exact_Cost_Reversing_Mandatory] [tinyint] NULL,
[Ext__Doc__No__Mandatory] [tinyint] NULL,
[Invoice_Nos_] [varchar] (10) NULL,
[Invoice_Rounding] [tinyint] NULL,
[Order_Nos_] [varchar] (10) NULL,
[Posted_Credit_Memo_Nos_] [varchar] (10) NULL,
[Posted_Invoice_Nos_] [varchar] (10) NULL,
[Posted_Receipt_Nos_] [varchar] (10) NULL,
[Posted_Return_Shpt__Nos_] [varchar] (10) NULL,
[Posted_Self-Invoice_Nos_] [varchar] (10) NULL,
[Posting_Desc__Code] [varchar] (10) NULL,
[Primary_Key] [varchar] (10) NOT NULL,
[Quote_Nos_] [varchar] (10) NULL,
[Receipt_on_Invoice] [tinyint] NULL,
[Return_Order_Nos_] [varchar] (10) NULL,
[Return_Shipment_on_Credit_Memo] [tinyint] NULL,
[Vendor_Nos_] [varchar] (10) NULL,
[timestamp] [timestamp] NOT NULL
)
GO
ALTER TABLE [psa].[ics_stg_Navision_Rom_Live Icopal Romania$Purchases&PayablesSetup] ADD CONSTRAINT [PK_psa_ics_stg_Navision_Rom_Live Icopal Romania1812$Purchases & Payables Setup] PRIMARY KEY CLUSTERED  ([Primary_Key])
GO
