CREATE TABLE [psa].[ics_stg_baan_ttdpur061610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur061610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur061610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_citg] [varchar] (6) NULL,
[t_dejt] [int] NULL,
[t_dete] [int] NULL,
[t_detl] [int] NULL,
[t_frte] [real] NULL,
[t_frtl] [real] NULL,
[t_item] [varchar] (16) NULL,
[t_ndte] [smallint] NULL,
[t_ndtl] [smallint] NULL,
[t_suno] [varchar] (6) NULL,
[t_year] [smallint] NULL
)
GO
