CREATE TABLE [psa].[ics_stg_SAP_SVK_T001W]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_T001W_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_T001W_IsIncomplete] DEFAULT ('N'),
[ACHVM] [nvarchar] (1) NULL,
[ADRNR] [nvarchar] (10) NULL,
[AWSLS] [nvarchar] (6) NULL,
[BEDPL] [nvarchar] (1) NULL,
[BETOL] [nvarchar] (3) NULL,
[BWKEY] [nvarchar] (4) NULL,
[BZIRK] [nvarchar] (6) NULL,
[BZQHL] [nvarchar] (1) NULL,
[CHAZV] [nvarchar] (1) NULL,
[CHAZV_OLD] [nvarchar] (1) NULL,
[CITYC] [nvarchar] (4) NULL,
[COUNC] [nvarchar] (3) NULL,
[DVSART] [nvarchar] (1) NULL,
[EKORG] [nvarchar] (4) NULL,
[FABKL] [nvarchar] (2) NULL,
[FPRFW] [nvarchar] (3) NULL,
[IWERK] [nvarchar] (4) NULL,
[J_1BBRANCH] [nvarchar] (4) NULL,
[KKOWK] [nvarchar] (1) NULL,
[KORDB] [nvarchar] (1) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LAND1] [nvarchar] (3) NULL,
[LET01] [decimal] (3, 0) NULL,
[LET02] [decimal] (3, 0) NULL,
[LET03] [decimal] (3, 0) NULL,
[LIFNR] [nvarchar] (10) NULL,
[MANDT] [nvarchar] (3) NOT NULL,
[MGVLAUPD] [nvarchar] (1) NULL,
[MGVUPD] [nvarchar] (1) NULL,
[MISCH] [nvarchar] (1) NULL,
[NAME1] [nvarchar] (30) NULL,
[NAME2] [nvarchar] (30) NULL,
[NODETYPE] [nvarchar] (3) NULL,
[NSCHEMA] [nvarchar] (4) NULL,
[ORT01] [nvarchar] (25) NULL,
[PFACH] [nvarchar] (10) NULL,
[PKOSA] [nvarchar] (1) NULL,
[PSTLZ] [nvarchar] (10) NULL,
[REGIO] [nvarchar] (3) NULL,
[SOURCING] [nvarchar] (1) NULL,
[SPART] [nvarchar] (2) NULL,
[SPRAS] [nvarchar] (1) NULL,
[STRAS] [nvarchar] (30) NULL,
[TAXIW] [nvarchar] (1) NULL,
[TXJCD] [nvarchar] (15) NULL,
[TXNAM_MA1] [nvarchar] (16) NULL,
[TXNAM_MA2] [nvarchar] (16) NULL,
[TXNAM_MA3] [nvarchar] (16) NULL,
[VKORG] [nvarchar] (4) NULL,
[VLFKZ] [nvarchar] (1) NULL,
[VSTEL] [nvarchar] (4) NULL,
[VTBFI] [nvarchar] (2) NULL,
[VTWEG] [nvarchar] (2) NULL,
[WERKS] [nvarchar] (4) NOT NULL,
[WKSOP] [nvarchar] (1) NULL,
[ZONE1] [nvarchar] (10) NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_SVK_T001W] ADD CONSTRAINT [PK_psa_ics_stg_SAP_SVK_T001W] PRIMARY KEY CLUSTERED  ([MANDT], [WERKS])
GO
EXEC sp_addextendedproperty N'IncludeInMerge', N'Y', 'SCHEMA', N'psa', 'TABLE', N'ics_stg_SAP_SVK_T001W', NULL, NULL
GO
