CREATE TABLE [psa].[ics_stg_SAP_SVK_EKBZ]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_EKBZ_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_SAP_SVK_EKBZ_IsIncomplete] DEFAULT ('N'),
[AREWB] [decimal] (13, 2) NULL,
[AREWR] [decimal] (13, 2) NULL,
[AREWW] [decimal] (13, 2) NULL,
[BELNR] [nvarchar] (10) NOT NULL,
[BEWTP] [nvarchar] (1) NULL,
[BPMNG] [decimal] (13, 3) NULL,
[BUDAT] [nvarchar] (8) NULL,
[BUZEI] [nvarchar] (4) NOT NULL,
[BWTAR] [nvarchar] (10) NULL,
[CPUDT] [nvarchar] (8) NULL,
[CPUTM] [nvarchar] (6) NULL,
[DMBTR] [decimal] (13, 2) NULL,
[EBELN] [nvarchar] (10) NOT NULL,
[EBELP] [nvarchar] (5) NULL,
[ERNAM] [nvarchar] (12) NULL,
[FRBNR] [nvarchar] (16) NULL,
[GJAHR] [nvarchar] (4) NULL,
[HSWAE] [nvarchar] (5) NULL,
[KSCHL] [nvarchar] (4) NULL,
[LIFNR] [nvarchar] (10) NULL,
[MANDT] [nvarchar] (3) NULL,
[MENGE] [decimal] (13, 3) NULL,
[REEWR] [decimal] (13, 2) NULL,
[REFWR] [decimal] (13, 2) NULL,
[REWRB] [decimal] (13, 2) NULL,
[SAPRL] [nvarchar] (4) NULL,
[SHKKO] [nvarchar] (1) NULL,
[SHKZG] [nvarchar] (1) NULL,
[STUNR] [nvarchar] (3) NULL,
[VGABE] [nvarchar] (1) NULL,
[VNETW] [decimal] (13, 2) NULL,
[WAERS] [nvarchar] (5) NULL,
[WRBTR] [decimal] (13, 2) NULL,
[XBLNR] [nvarchar] (16) NULL,
[ZAEHK] [nvarchar] (2) NOT NULL
)
GO
ALTER TABLE [psa].[ics_stg_SAP_SVK_EKBZ] ADD CONSTRAINT [PK_psa_ics_stg_SAP_SVK_EKBZ] PRIMARY KEY CLUSTERED  ([BUZEI], [BELNR], [ZAEHK], [EBELN])
GO
EXEC sp_addextendedproperty N'IncludeInMerge', N'Y', 'SCHEMA', N'psa', 'TABLE', N'ics_stg_SAP_SVK_EKBZ', NULL, NULL
GO
