CREATE TABLE [psa].[ICS_STG_SAP_DEU_LIPS]
(
[EtlBatchRunId] [int] NULL,
[EtlStepRunId] [int] NULL,
[EtlThreadRunId] [int] NULL,
[DataSourceKey] [int] NULL,
[EtlCreatedOn] [datetime] NULL,
[EtlCreatedBy] [varchar] (200) NULL,
[MANDT] [nvarchar] (3) NULL,
[VBELN] [nvarchar] (10) NULL,
[POSNR] [nvarchar] (6) NULL,
[PSTYV] [nvarchar] (4) NULL,
[ERNAM] [nvarchar] (12) NULL,
[ERZET] [datetime] NULL,
[ERDAT] [datetime] NULL,
[MATNR] [nvarchar] (18) NULL,
[MATWA] [nvarchar] (18) NULL,
[MATKL] [nvarchar] (9) NULL,
[WERKS] [nvarchar] (4) NULL,
[LGORT] [nvarchar] (4) NULL,
[CHARG] [nvarchar] (10) NULL,
[LICHN] [nvarchar] (15) NULL,
[KDMAT] [nvarchar] (35) NULL,
[PRODH] [nvarchar] (18) NULL,
[LFIMG] [decimal] (13, 3) NULL,
[MEINS] [nvarchar] (3) NULL,
[VRKME] [nvarchar] (3) NULL,
[UMVKZ] [decimal] (5, 0) NULL,
[UMVKN] [decimal] (5, 0) NULL,
[NTGEW] [decimal] (15, 3) NULL,
[BRGEW] [decimal] (15, 3) NULL,
[GEWEI] [nvarchar] (3) NULL,
[VOLUM] [decimal] (15, 3) NULL,
[VOLEH] [nvarchar] (3) NULL,
[KZTLF] [nvarchar] (1) NULL,
[UEBTK] [nvarchar] (1) NULL,
[UEBTO] [decimal] (3, 1) NULL,
[UNTTO] [decimal] (3, 1) NULL,
[CHSPL] [nvarchar] (1) NULL,
[FAKSP] [nvarchar] (2) NULL,
[MBDAT] [datetime] NULL,
[LGMNG] [decimal] (13, 3) NULL,
[ARKTX] [nvarchar] (40) NULL,
[LGPBE] [nvarchar] (10) NULL,
[VBELV] [nvarchar] (10) NULL,
[POSNV] [nvarchar] (6) NULL,
[VBTYV] [nvarchar] (1) NULL,
[VGSYS] [nvarchar] (10) NULL,
[VGBEL] [nvarchar] (10) NULL,
[VGPOS] [nvarchar] (6) NULL,
[UPFLU] [nvarchar] (1) NULL,
[UEPOS] [nvarchar] (6) NULL,
[FKREL] [nvarchar] (1) NULL,
[LADGR] [nvarchar] (4) NULL,
[TRAGR] [nvarchar] (4) NULL,
[KOMKZ] [nvarchar] (1) NULL,
[LGNUM] [nvarchar] (3) NULL,
[LISPL] [nvarchar] (1) NULL,
[LGTYP] [nvarchar] (3) NULL,
[LGPLA] [nvarchar] (10) NULL,
[BWTEX] [nvarchar] (1) NULL,
[BWART] [nvarchar] (3) NULL,
[BWLVS] [nvarchar] (3) NULL,
[KZDLG] [nvarchar] (1) NULL,
[BDART] [nvarchar] (2) NULL,
[PLART] [nvarchar] (1) NULL,
[MTART] [nvarchar] (4) NULL,
[XCHPF] [nvarchar] (1) NULL,
[XCHAR] [nvarchar] (1) NULL,
[VGREF] [nvarchar] (1) NULL,
[POSAR] [nvarchar] (1) NULL,
[BWTAR] [nvarchar] (10) NULL,
[SUMBD] [nvarchar] (1) NULL,
[MTVFP] [nvarchar] (2) NULL,
[EANNR] [nvarchar] (13) NULL,
[GSBER] [nvarchar] (4) NULL,
[VKBUR] [nvarchar] (4) NULL,
[VKGRP] [nvarchar] (3) NULL,
[VTWEG] [nvarchar] (2) NULL,
[SPART] [nvarchar] (2) NULL,
[GRKOR] [nvarchar] (3) NULL,
[FMENG] [nvarchar] (1) NULL,
[ANTLF] [decimal] (1, 0) NULL,
[VBEAF] [decimal] (5, 2) NULL,
[VBEAV] [decimal] (5, 2) NULL,
[STAFO] [nvarchar] (6) NULL,
[WAVWR] [decimal] (13, 2) NULL,
[KZWI1] [decimal] (13, 2) NULL,
[KZWI2] [decimal] (13, 2) NULL,
[KZWI3] [decimal] (13, 2) NULL,
[KZWI4] [decimal] (13, 2) NULL,
[KZWI5] [decimal] (13, 2) NULL,
[KZWI6] [decimal] (13, 2) NULL,
[SOBKZ] [nvarchar] (1) NULL,
[AEDAT] [datetime] NULL,
[EAN11] [nvarchar] (18) NULL,
[KVGR1] [nvarchar] (3) NULL,
[KVGR2] [nvarchar] (3) NULL,
[KVGR3] [nvarchar] (3) NULL,
[KVGR4] [nvarchar] (3) NULL,
[KVGR5] [nvarchar] (3) NULL,
[MVGR1] [nvarchar] (3) NULL,
[MVGR2] [nvarchar] (3) NULL,
[MVGR3] [nvarchar] (3) NULL,
[MVGR4] [nvarchar] (3) NULL,
[MVGR5] [nvarchar] (3) NULL,
[VPZUO] [nvarchar] (1) NULL,
[VGTYP] [nvarchar] (1) NULL,
[RFVGTYP] [nvarchar] (1) NULL,
[KOSTL] [nvarchar] (10) NULL,
[KOKRS] [nvarchar] (4) NULL,
[PAOBJNR] [nvarchar] (10) NULL,
[PRCTR] [nvarchar] (10) NULL,
[PS_PSP_PNR] [nvarchar] (8) NULL,
[AUFNR] [nvarchar] (12) NULL,
[POSNR_PP] [nvarchar] (4) NULL,
[KDAUF] [nvarchar] (10) NULL,
[KDPOS] [nvarchar] (6) NULL,
[VPMAT] [nvarchar] (18) NULL,
[VPWRK] [nvarchar] (4) NULL,
[PRBME] [nvarchar] (3) NULL,
[UMREF] [float] NULL,
[KNTTP] [nvarchar] (1) NULL,
[KZVBR] [nvarchar] (1) NULL,
[FIPOS] [nvarchar] (14) NULL,
[FISTL] [nvarchar] (16) NULL,
[GEBER] [nvarchar] (10) NULL,
[PCKPF] [nvarchar] (1) NULL,
[BEDAR_LF] [nvarchar] (3) NULL,
[CMPNT] [nvarchar] (1) NULL,
[KCMENG] [decimal] (15, 3) NULL,
[KCBRGEW] [decimal] (15, 3) NULL,
[KCNTGEW] [decimal] (15, 3) NULL,
[KCVOLUM] [decimal] (15, 3) NULL,
[UECHA] [nvarchar] (6) NULL,
[CUOBJ] [nvarchar] (18) NULL,
[CUOBJ_CH] [nvarchar] (18) NULL,
[ANZSN] [bigint] NULL,
[SERAIL] [nvarchar] (4) NULL,
[KCGEWEI] [nvarchar] (3) NULL,
[KCVOLEH] [nvarchar] (3) NULL,
[SERNR] [nvarchar] (8) NULL,
[ABRLI] [nvarchar] (4) NULL,
[ABART] [nvarchar] (1) NULL,
[ABRVW] [nvarchar] (3) NULL,
[QPLOS] [nvarchar] (12) NULL,
[QTLOS] [nvarchar] (6) NULL,
[NACHL] [nvarchar] (1) NULL,
[MAGRV] [nvarchar] (4) NULL,
[OBJKO] [nvarchar] (22) NULL,
[OBJPO] [nvarchar] (22) NULL,
[AESKD] [nvarchar] (17) NULL,
[SHKZG] [nvarchar] (1) NULL,
[PROSA] [nvarchar] (1) NULL,
[UEPVW] [nvarchar] (1) NULL,
[EMPST] [nvarchar] (25) NULL,
[ABTNR] [nvarchar] (4) NULL,
[KOQUI] [nvarchar] (1) NULL,
[STADAT] [datetime] NULL,
[AKTNR] [nvarchar] (10) NULL,
[KNUMH_CH] [nvarchar] (10) NULL,
[PREFE] [nvarchar] (1) NULL,
[EXART] [nvarchar] (2) NULL,
[CLINT] [nvarchar] (10) NULL,
[CHMVS] [nvarchar] (3) NULL,
[ABELN] [nvarchar] (10) NULL,
[ABELP] [nvarchar] (5) NULL,
[LFIMG_FLO] [float] NULL,
[LGMNG_FLO] [float] NULL,
[KCMENG_FLO] [float] NULL,
[KZUMW] [nvarchar] (1) NULL,
[KMPMG] [decimal] (13, 3) NULL,
[AUREL] [nvarchar] (1) NULL,
[KPEIN] [decimal] (5, 0) NULL,
[KMEIN] [nvarchar] (3) NULL,
[NETPR] [decimal] (11, 2) NULL,
[NETWR] [decimal] (15, 2) NULL,
[KOWRR] [nvarchar] (1) NULL,
[KZBEW] [nvarchar] (1) NULL,
[MFRGR] [nvarchar] (8) NULL,
[CHHPV] [nvarchar] (1) NULL,
[ABFOR] [nvarchar] (2) NULL,
[ABGES] [float] NULL,
[MBUHR] [datetime] NULL,
[WKTNR] [nvarchar] (10) NULL,
[WKTPS] [nvarchar] (6) NULL,
[J_1BCFOP] [nvarchar] (10) NULL,
[J_1BTAXLW1] [nvarchar] (3) NULL,
[J_1BTAXLW2] [nvarchar] (3) NULL,
[J_1BTXSDC] [nvarchar] (2) NULL,
[SITUA] [nvarchar] (2) NULL,
[RSNUM] [nvarchar] (10) NULL,
[RSPOS] [nvarchar] (4) NULL,
[RSART] [nvarchar] (1) NULL,
[KANNR] [nvarchar] (35) NULL,
[KZFME] [nvarchar] (1) NULL,
[PROFL] [nvarchar] (3) NULL,
[KCMENGVME] [decimal] (15, 3) NULL,
[KCMENGVMEF] [float] NULL,
[KZBWS] [nvarchar] (1) NULL,
[PSPNR] [nvarchar] (8) NULL,
[EPRIO] [nvarchar] (4) NULL,
[RULES] [nvarchar] (4) NULL,
[KZBEF] [nvarchar] (1) NULL,
[MPROF] [nvarchar] (4) NULL,
[EMATN] [nvarchar] (18) NULL,
[LGBZO] [nvarchar] (10) NULL,
[HANDLE] [nvarchar] (22) NULL,
[VERURPOS] [nvarchar] (6) NULL,
[LIFEXPOS] [nvarchar] (6) NULL,
[NOATP] [nvarchar] (1) NULL,
[NOPCK] [nvarchar] (1) NULL,
[RBLVS] [nvarchar] (3) NULL,
[BERID] [nvarchar] (10) NULL,
[BESTQ] [nvarchar] (1) NULL,
[UMBSQ] [nvarchar] (1) NULL,
[UMMAT] [nvarchar] (18) NULL,
[UMWRK] [nvarchar] (4) NULL,
[UMLGO] [nvarchar] (4) NULL,
[UMCHA] [nvarchar] (10) NULL,
[UMBAR] [nvarchar] (10) NULL,
[UMSOK] [nvarchar] (1) NULL,
[SONUM] [nvarchar] (16) NULL,
[USONU] [nvarchar] (16) NULL,
[AKKUR] [decimal] (9, 5) NULL,
[AKMNG] [nvarchar] (1) NULL,
[VKGRU] [nvarchar] (3) NULL,
[SHKZG_UM] [nvarchar] (1) NULL,
[INSMK] [nvarchar] (1) NULL,
[KZECH] [nvarchar] (1) NULL,
[FLGWM] [nvarchar] (1) NULL,
[BERKZ] [nvarchar] (1) NULL,
[HUPOS] [nvarchar] (1) NULL,
[NOWAB] [nvarchar] (1) NULL,
[KONTO] [nvarchar] (10) NULL,
[KZEAR] [nvarchar] (1) NULL,
[HSDAT] [datetime] NULL,
[VFDAT] [datetime] NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFBNR] [nvarchar] (10) NULL,
[LFPOS] [nvarchar] (4) NULL,
[GRUND] [nvarchar] (4) NULL,
[FOBWA] [nvarchar] (3) NULL,
[DLVTP] [nvarchar] (2) NULL,
[EXBWR] [decimal] (13, 2) NULL,
[BPMNG] [decimal] (13, 3) NULL,
[EXVKW] [decimal] (13, 2) NULL,
[CMPRE_FLT] [float] NULL,
[KZPOD] [nvarchar] (1) NULL,
[LFDEZ] [nvarchar] (1) NULL,
[UMREV] [float] NULL,
[PODREL] [nvarchar] (1) NULL,
[KZUML] [nvarchar] (1) NULL,
[FKBER] [nvarchar] (16) NULL,
[GRANT_NBR] [nvarchar] (20) NULL,
[KZWSO] [nvarchar] (1) NULL,
[GMCONTROL] [nvarchar] (1) NULL,
[POSTING_CHANGE] [nvarchar] (1) NULL,
[UM_PS_PSP_PNR] [nvarchar] (8) NULL,
[PRE_VL_ETENS] [nvarchar] (4) NULL,
[SPE_GEN_ELIKZ] [nvarchar] (1) NULL,
[SPE_SCRAP_IND] [nvarchar] (1) NULL,
[SPE_AUTH_NUMBER] [nvarchar] (20) NULL,
[SPE_INSPOUT_GUID] [binary] (16) NULL,
[SPE_FOLLOW_UP] [nvarchar] (4) NULL,
[SPE_EXP_DATE_EXT] [decimal] (15, 0) NULL,
[SPE_EXP_DATE_INT] [decimal] (15, 0) NULL,
[SPE_AUTH_COMPLET] [nvarchar] (1) NULL,
[ORMNG] [decimal] (13, 3) NULL,
[SPE_ATP_TMSTMP] [decimal] (15, 0) NULL,
[SPE_ORIG_SYS] [nvarchar] (1) NULL,
[SPE_LIEFFZ] [decimal] (15, 3) NULL,
[SPE_IMWRK] [nvarchar] (1) NULL,
[SPE_LIFEXPOS2] [nvarchar] (35) NULL,
[SPE_EXCEPT_CODE] [nvarchar] (4) NULL,
[SPE_KEEP_QTY] [decimal] (13, 3) NULL,
[SPE_ALTERNATE] [nvarchar] (40) NULL,
[SPE_MAT_SUBST] [nvarchar] (1) NULL,
[SPE_STRUC] [nvarchar] (3) NULL,
[SPE_APO_QNTYFAC] [decimal] (5, 0) NULL,
[SPE_APO_QNTYDIV] [decimal] (5, 0) NULL,
[SPE_HERKL] [nvarchar] (3) NULL,
[SPE_BXP_DATE_EXT] [decimal] (15, 0) NULL,
[SPE_VERSION] [nvarchar] (4) NULL,
[SPE_COMPL_MVT] [nvarchar] (1) NULL,
[J_1BTAXLW4] [nvarchar] (3) NULL,
[J_1BTAXLW5] [nvarchar] (3) NULL,
[J_1BTAXLW3] [nvarchar] (3) NULL,
[BUDGET_PD] [nvarchar] (10) NULL,
[KBNKZ] [nvarchar] (1) NULL,
[FARR_RELTYPE] [nvarchar] (10) NULL,
[SITKZ] [nvarchar] (1) NULL,
[CONS_ORDER] [nvarchar] (1) NULL,
[ZZVERPEH] [nvarchar] (3) NULL,
[ZZVERPMENG] [decimal] (15, 3) NULL,
[ZZUMREN] [decimal] (5, 0) NULL,
[ZZUMREZ] [decimal] (5, 0) NULL,
[ZZVERPEH_SCR] [nvarchar] (3) NULL,
[ZZRESTAUSL] [nvarchar] (1) NULL,
[ZZABWGRU] [nvarchar] (2) NULL,
[ZZURSP_LFIMG] [decimal] (13, 3) NULL,
[ZZURSP_VRKME] [nvarchar] (3) NULL,
[ZZRESTPALJN] [nvarchar] (1) NULL,
[ZZKMSTU] [nvarchar] (2) NULL,
[ZZOTIFNR] [nvarchar] (3) NULL,
[EtlRecordId] [bigint] NOT NULL,
[IsIncomplete] [char] (1) NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NOT NULL,
[EtlDeletedBy] [varchar] (200) NOT NULL,
[IsDeleted] [char] (1) NOT NULL
)
GO
