CREATE TABLE [psa].[ics_stg_M3V10vil_POL_CIDADR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_CIDADR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_vil_CIDADR_IsIncomplete] DEFAULT ('N'),
[SAADID] [nchar] (6) NOT NULL,
[SAADR1] [nvarchar] (36) NULL,
[SAADR2] [nvarchar] (36) NULL,
[SAADR3] [nvarchar] (36) NULL,
[SAADR4] [nvarchar] (36) NULL,
[SAADTE] [numeric] (18, 0) NOT NULL,
[SAADVI] [nchar] (6) NULL,
[SACHID] [nchar] (10) NULL,
[SACHNO] [numeric] (3, 0) NULL,
[SACONO] [numeric] (18, 0) NOT NULL,
[SACSCD] [nchar] (3) NULL,
[SAECAR] [nchar] (2) NULL,
[SAEDES] [nchar] (10) NULL,
[SAGEOC] [numeric] (9, 0) NULL,
[SAGEOX] [numeric] (15, 6) NULL,
[SAGEOY] [numeric] (15, 6) NULL,
[SAGEOZ] [numeric] (15, 6) NULL,
[SALMDT] [numeric] (8, 0) NULL,
[SALMTS] [numeric] (18, 0) NULL,
[SAPNOD] [nchar] (15) NULL,
[SAPONO] [nchar] (10) NULL,
[SAPRIA] [numeric] (1, 0) NULL,
[SARGDT] [numeric] (8, 0) NULL,
[SARGTM] [numeric] (6, 0) NULL,
[SASTDT] [numeric] (18, 0) NOT NULL,
[SASUNM] [nvarchar] (36) NULL,
[SASUNO] [nchar] (10) NOT NULL,
[SATAXC] [nchar] (3) NULL,
[SATOWN] [nvarchar] (20) NULL,
[SATXID] [numeric] (13, 0) NULL
)
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_CIDADR] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_CIDADR] PRIMARY KEY CLUSTERED  ([SAADID], [SAADTE], [SACONO], [SASTDT], [SASUNO])
GO
