CREATE TABLE [psa].[ics_stg_baan_ttdpur401610]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur401610_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_baan_ttdpur401610_IsIncomplete] DEFAULT ('N'),
[t_Refcntd] [int] NULL,
[t_Refcntu] [int] NULL,
[t_clot] [varchar] (16) NULL,
[t_cntr] [varchar] (3) NULL,
[t_cprj] [varchar] (6) NULL,
[t_dino] [varchar] (10) NULL,
[t_item] [varchar] (16) NULL,
[t_orno] [int] NULL,
[t_pono] [smallint] NULL,
[t_qstc] [float] NULL,
[t_qstr] [float] NULL,
[t_sera] [tinyint] NULL,
[t_serb] [int] NULL,
[t_suno] [varchar] (6) NULL
)
GO
