CREATE TABLE [dbo].[PU_CATEGORY]
(
[CATEGORY_ID] [int] NOT NULL,
[CATEGORY_NAME] [varchar] (100) NULL,
[PARENT_ID] [int] NULL,
[CREATE_BY] [varchar] (100) NULL,
[CREATE_DATE] [datetime] NULL,
[UPDATE_BY] [varchar] (100) NULL,
[UPDATE_DATE] [datetime] NULL
)
GO
ALTER TABLE [dbo].[PU_CATEGORY] ADD CONSTRAINT [PK_PU_CATEGORY_1] PRIMARY KEY CLUSTERED  ([CATEGORY_ID])
GO
ALTER TABLE [dbo].[PU_CATEGORY] ADD CONSTRAINT [FK_PU_CATEGORY_PU_CATEGORY] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[PU_CATEGORY] ([CATEGORY_ID])
GO
