-- <Migration ID="72ed62a9-54e2-4a09-b03d-3da81146ede9" />
GO

PRINT N'Creating [psa].[ics_stg_SAP_GBR_MBEW]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_MBEW]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_MBEW_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_MBEW_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NULL,
[MATNR] [nvarchar] (18) NOT NULL,
[BWKEY] [nvarchar] (4) NOT NULL,
[BWTAR] [nvarchar] (10) NULL,
[LVORM] [nvarchar] (1) NULL,
[LBKUM] [decimal] (13, 3) NULL,
[SALK3] [decimal] (13, 2) NULL,
[VPRSV] [nvarchar] (1) NULL,
[VERPR] [decimal] (11, 2) NULL,
[STPRS] [decimal] (11, 2) NULL,
[PEINH] [decimal] (5, 0) NULL,
[BKLAS] [nvarchar] (4) NULL,
[SALKV] [decimal] (13, 2) NULL,
[VMKUM] [decimal] (13, 3) NULL,
[VMSAL] [decimal] (13, 2) NULL,
[VMVPR] [nvarchar] (1) NULL,
[VMVER] [decimal] (11, 2) NULL,
[VMSTP] [decimal] (11, 2) NULL,
[VMPEI] [decimal] (5, 0) NULL,
[VMBKL] [nvarchar] (4) NULL,
[VMSAV] [decimal] (13, 2) NULL,
[VJKUM] [decimal] (13, 3) NULL,
[VJSAL] [decimal] (13, 2) NULL,
[VJVPR] [nvarchar] (1) NULL,
[VJVER] [decimal] (11, 2) NULL,
[VJSTP] [decimal] (11, 2) NULL,
[VJPEI] [decimal] (5, 0) NULL,
[VJBKL] [nvarchar] (4) NULL,
[VJSAV] [decimal] (13, 2) NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFMON] [nvarchar] (2) NULL,
[BWTTY] [nvarchar] (1) NULL,
[STPRV] [decimal] (11, 2) NULL,
[LAEPR] [datetime] NULL,
[ZKPRS] [decimal] (11, 2) NULL,
[ZKDAT] [datetime] NULL,
[TIMESTAMP] [decimal] (15, 0) NULL,
[BWPRS] [decimal] (11, 2) NULL,
[BWPRH] [decimal] (11, 2) NULL,
[VJBWS] [decimal] (11, 2) NULL,
[VJBWH] [decimal] (11, 2) NULL,
[VVJSL] [decimal] (13, 2) NULL,
[VVJLB] [decimal] (13, 3) NULL,
[VVMLB] [decimal] (13, 3) NULL,
[VVSAL] [decimal] (13, 2) NULL,
[ZPLPR] [decimal] (11, 2) NULL,
[ZPLP1] [decimal] (11, 2) NULL,
[ZPLP2] [decimal] (11, 2) NULL,
[ZPLP3] [decimal] (11, 2) NULL,
[ZPLD1] [datetime] NULL,
[ZPLD2] [datetime] NULL,
[ZPLD3] [datetime] NULL,
[PPERZ] [datetime] NULL,
[PPERL] [datetime] NULL,
[PPERV] [datetime] NULL,
[KALKZ] [nvarchar] (1) NULL,
[KALKL] [nvarchar] (1) NULL,
[KALKV] [nvarchar] (1) NULL,
[KALSC] [nvarchar] (6) NULL,
[XLIFO] [nvarchar] (1) NULL,
[MYPOL] [nvarchar] (4) NULL,
[BWPH1] [decimal] (11, 2) NULL,
[BWPS1] [decimal] (11, 2) NULL,
[ABWKZ] [nvarchar] (2) NULL,
[PSTAT] [nvarchar] (15) NULL,
[KALN1] [nvarchar] (12) NULL,
[KALNR] [nvarchar] (12) NULL,
[BWVA1] [nvarchar] (3) NULL,
[BWVA2] [nvarchar] (3) NULL,
[BWVA3] [nvarchar] (3) NULL,
[VERS1] [nvarchar] (2) NULL,
[VERS2] [nvarchar] (2) NULL,
[VERS3] [nvarchar] (2) NULL,
[HRKFT] [nvarchar] (4) NULL,
[KOSGR] [nvarchar] (10) NULL,
[PPRDZ] [nvarchar] (3) NULL,
[PPRDL] [nvarchar] (3) NULL,
[PPRDV] [nvarchar] (3) NULL,
[PDATZ] [nvarchar] (4) NULL,
[PDATL] [nvarchar] (4) NULL,
[PDATV] [nvarchar] (4) NULL,
[EKALR] [nvarchar] (1) NULL,
[VPLPR] [decimal] (11, 2) NULL,
[MLMAA] [nvarchar] (1) NULL,
[MLAST] [nvarchar] (1) NULL,
[LPLPR] [decimal] (11, 2) NULL,
[VKSAL] [decimal] (13, 2) NULL,
[HKMAT] [nvarchar] (1) NULL,
[SPERW] [nvarchar] (1) NULL,
[KZIWL] [nvarchar] (3) NULL,
[WLINL] [datetime] NULL,
[ABCIW] [nvarchar] (1) NULL,
[BWSPA] [decimal] (6, 2) NULL,
[LPLPX] [decimal] (11, 2) NULL,
[VPLPX] [decimal] (11, 2) NULL,
[FPLPX] [decimal] (11, 2) NULL,
[LBWST] [nvarchar] (1) NULL,
[VBWST] [nvarchar] (1) NULL,
[FBWST] [nvarchar] (1) NULL,
[EKLAS] [nvarchar] (4) NULL,
[QKLAS] [nvarchar] (4) NULL,
[MTUSE] [nvarchar] (1) NULL,
[MTORG] [nvarchar] (1) NULL,
[OWNPR] [nvarchar] (1) NULL,
[XBEWM] [nvarchar] (1) NULL,
[BWPEI] [decimal] (5, 0) NULL,
[MBRUE] [nvarchar] (1) NULL,
[OKLAS] [nvarchar] (4) NULL,
[OIPPINV] [nvarchar] (1) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_MBEW_PK] on [psa].[ics_stg_SAP_GBR_MBEW]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_MBEW] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_MBEW_PK] PRIMARY KEY CLUSTERED  ([MATNR], [BWKEY])
GO
