-- <Migration ID="a5e6d549-5ac0-4a7c-965b-8f682a75edeb" />
GO

PRINT N'Creating [psa].[ics_stg_SAP_GBR_EKBE]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_EKBE]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKBE_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKBE_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NOT NULL,
[EBELN] [nvarchar] (10) NOT NULL,
[EBELP] [nvarchar] (5) NOT NULL,
[ZEKKN] [nvarchar] (2) NOT NULL,
[VGABE] [nvarchar] (1) NOT NULL,
[GJAHR] [nvarchar] (4) NOT NULL,
[BELNR] [nvarchar] (10) NOT NULL,
[BUZEI] [nvarchar] (4) NOT NULL,
[BEWTP] [nvarchar] (1) NULL,
[BWART] [nvarchar] (3) NULL,
[BUDAT] [datetime] NULL,
[MENGE] [decimal] (13, 3) NULL,
[BPMNG] [decimal] (13, 3) NULL,
[DMBTR] [decimal] (13, 2) NULL,
[WRBTR] [decimal] (13, 2) NULL,
[WAERS] [nvarchar] (5) NULL,
[AREWR] [decimal] (13, 2) NULL,
[WESBS] [decimal] (13, 3) NULL,
[BPWES] [decimal] (13, 3) NULL,
[SHKZG] [nvarchar] (1) NULL,
[BWTAR] [nvarchar] (10) NULL,
[ELIKZ] [nvarchar] (1) NULL,
[XBLNR] [nvarchar] (16) NULL,
[LFGJA] [nvarchar] (4) NULL,
[LFBNR] [nvarchar] (10) NULL,
[LFPOS] [nvarchar] (4) NULL,
[GRUND] [nvarchar] (4) NULL,
[CPUDT] [datetime] NULL,
[CPUTM] [datetime] NULL,
[REEWR] [decimal] (13, 2) NULL,
[EVERE] [nvarchar] (2) NULL,
[REFWR] [decimal] (13, 2) NULL,
[MATNR] [nvarchar] (18) NULL,
[WERKS] [nvarchar] (4) NULL,
[XWSBR] [nvarchar] (1) NULL,
[ETENS] [nvarchar] (4) NULL,
[KNUMV] [nvarchar] (10) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[LSMNG] [decimal] (13, 3) NULL,
[LSMEH] [nvarchar] (3) NULL,
[EMATN] [nvarchar] (18) NULL,
[AREWW] [decimal] (13, 2) NULL,
[HSWAE] [nvarchar] (5) NULL,
[BAMNG] [decimal] (13, 3) NULL,
[CHARG] [nvarchar] (10) NULL,
[BLDAT] [datetime] NULL,
[XWOFF] [nvarchar] (1) NULL,
[XUNPL] [nvarchar] (1) NULL,
[ERNAM] [nvarchar] (12) NULL,
[SRVPOS] [nvarchar] (18) NULL,
[PACKNO] [nvarchar] (10) NULL,
[INTROW] [nvarchar] (10) NULL,
[BEKKN] [nvarchar] (2) NULL,
[LEMIN] [nvarchar] (1) NULL,
[AREWB] [decimal] (13, 2) NULL,
[REWRB] [decimal] (13, 2) NULL,
[SAPRL] [nvarchar] (4) NULL,
[MENGE_POP] [decimal] (13, 3) NULL,
[BPMNG_POP] [decimal] (13, 3) NULL,
[DMBTR_POP] [decimal] (13, 2) NULL,
[WRBTR_POP] [decimal] (13, 2) NULL,
[WESBB] [decimal] (13, 3) NULL,
[BPWEB] [decimal] (13, 3) NULL,
[WEORA] [nvarchar] (1) NULL,
[AREWR_POP] [decimal] (13, 2) NULL,
[KUDIF] [decimal] (13, 2) NULL,
[RETAMT_FC] [decimal] (13, 2) NULL,
[RETAMT_LC] [decimal] (13, 2) NULL,
[RETAMTP_FC] [decimal] (13, 2) NULL,
[RETAMTP_LC] [decimal] (13, 2) NULL,
[XMACC] [nvarchar] (1) NULL,
[WKURS] [decimal] (9, 5) NULL,
[VBELN_ST] [nvarchar] (10) NULL,
[VBELP_ST] [nvarchar] (6) NULL,
[ET_UPD] [nvarchar] (1) NULL,
[J_SC_DIE_COMP_F] [nvarchar] (1) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_EKBE_PK] on [psa].[ics_stg_SAP_GBR_EKBE]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EKBE] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_EKBE_PK] PRIMARY KEY CLUSTERED  ([BELNR], [EBELN], [MANDT], [EBELP], [BUZEI], [GJAHR], [VGABE], [ZEKKN])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_TCURR]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_TCURR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_TCURR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_TCURR_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NOT NULL,
[KURST] [nvarchar] (4) NOT NULL,
[FCURR] [nvarchar] (5) NOT NULL,
[TCURR] [nvarchar] (5) NOT NULL,
[GDATU] [nvarchar] (8) NOT NULL,
[UKURS] [decimal] (9, 5) NULL,
[FFACT] [decimal] (9, 0) NULL,
[TFACT] [decimal] (9, 0) NULL
)
go
PRINT N'Creating [psa].[ics_stg_SAP_GBR_T052U]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_T052U]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_T052U_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_T052U_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NOT NULL,
[SPRAS] [nvarchar] (1) NOT NULL,
[ZTERM] [nvarchar] (4) NOT NULL,
[ZTAGG] [nvarchar] (2) NOT NULL,
[TEXT1] [nvarchar] (50) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_T052U_PK] on [psa].[ics_stg_SAP_GBR_T052U]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_T052U] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_T052U_PK] PRIMARY KEY CLUSTERED  ([MANDT], [SPRAS], [ZTERM], [ZTAGG])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_LFM1]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_LFM1]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LFM1_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LFM1_IsIncomplete] DEFAULT ('N'),
[MANDT] [nvarchar] (3) NOT NULL,
[LIFNR] [nvarchar] (10) NOT NULL,
[EKORG] [nvarchar] (4) NOT NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[SPERM] [nvarchar] (1) NULL,
[LOEVM] [nvarchar] (1) NULL,
[LFABC] [nvarchar] (1) NULL,
[WAERS] [nvarchar] (5) NULL,
[VERKF] [nvarchar] (30) NULL,
[TELF1] [nvarchar] (16) NULL,
[MINBW] [decimal] (13, 2) NULL,
[ZTERM] [nvarchar] (4) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[WEBRE] [nvarchar] (1) NULL,
[KZABS] [nvarchar] (1) NULL,
[KALSK] [nvarchar] (2) NULL,
[KZAUT] [nvarchar] (1) NULL,
[EXPVZ] [nvarchar] (1) NULL,
[ZOLLA] [nvarchar] (6) NULL,
[MEPRF] [nvarchar] (1) NULL,
[EKGRP] [nvarchar] (3) NULL,
[XERSY] [nvarchar] (1) NULL,
[PLIFZ] [decimal] (3, 0) NULL,
[MRPPP] [nvarchar] (3) NULL,
[LFRHY] [nvarchar] (3) NULL,
[LIBES] [nvarchar] (1) NULL,
[LIPRE] [nvarchar] (2) NULL,
[LISER] [nvarchar] (1) NULL,
[PRFRE] [nvarchar] (1) NULL,
[NRGEW] [nvarchar] (1) NULL,
[BOIND] [nvarchar] (1) NULL,
[BLIND] [nvarchar] (1) NULL,
[KZRET] [nvarchar] (1) NULL,
[SKRIT] [nvarchar] (1) NULL,
[BSTAE] [nvarchar] (4) NULL,
[RDPRF] [nvarchar] (4) NULL,
[MEGRU] [nvarchar] (4) NULL,
[VENSL] [decimal] (4, 1) NULL,
[BOPNR] [nvarchar] (4) NULL,
[XERSR] [nvarchar] (1) NULL,
[EIKTO] [nvarchar] (12) NULL,
[ABUEB] [nvarchar] (4) NULL,
[PAPRF] [nvarchar] (4) NULL,
[AGREL] [nvarchar] (1) NULL,
[XNBWY] [nvarchar] (1) NULL,
[VSBED] [nvarchar] (2) NULL,
[LEBRE] [nvarchar] (1) NULL,
[BOLRE] [nvarchar] (1) NULL,
[UMSAE] [nvarchar] (1) NULL,
[VENDOR_RMA_REQ] [nvarchar] (1) NULL,
[ACTIVITY_PROFIL] [nvarchar] (4) NULL,
[TRANSPORT_CHAIN] [nvarchar] (10) NULL,
[STAGING_TIME] [decimal] (3, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_LFM1_PK] on [psa].[ics_stg_SAP_GBR_LFM1]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_LFM1] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_LFM1_PK] PRIMARY KEY CLUSTERED  ([MANDT], [LIFNR], [EKORG])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_MARM]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_MARM]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_MARM_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_MARM_IsIncomplete] DEFAULT ('N'),
[ATINN] [nvarchar] (10) NULL,
[BFLME_MARM] [nvarchar] (1) NULL,
[BREIT] [decimal] (18, 0) NULL,
[BRGEW] [decimal] (18, 0) NULL,
[CAPAUSE] [decimal] (18, 0) NULL,
[EAN11] [nvarchar] (18) NULL,
[EANNR] [nvarchar] (13) NULL,
[GEWEI] [nvarchar] (3) NULL,
[GTIN_VARIANT] [nvarchar] (2) NULL,
[HOEHE] [decimal] (18, 0) NULL,
[KZWSO] [nvarchar] (1) NULL,
[LAENG] [decimal] (18, 0) NULL,
[MANDT] [nvarchar] (3) NULL,
[MATNR] [nvarchar] (18) NOT NULL,
[MAX_STACK] [smallint] NULL,
[MEABM] [nvarchar] (3) NULL,
[MEINH] [nvarchar] (3) NOT NULL,
[MESRT] [nvarchar] (2) NULL,
[MESUB] [nvarchar] (3) NULL,
[MSEHI] [nvarchar] (3) NULL,
[NEST_FTR] [decimal] (18, 0) NULL,
[NUMTP] [nvarchar] (2) NULL,
[TY2TQ] [nvarchar] (1) NULL,
[UMREN] [decimal] (18, 0) NULL,
[UMREZ] [decimal] (18, 0) NULL,
[VOLEH] [nvarchar] (3) NULL,
[VOLUM] [decimal] (18, 0) NULL,
[XBEWW] [nvarchar] (1) NULL,
[XFHDW] [nvarchar] (1) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_MARM_PK] on [psa].[ics_stg_SAP_GBR_MARM]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_MARM] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_MARM_PK] PRIMARY KEY CLUSTERED  ([MATNR], [MEINH])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_LIKP]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_LIKP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LIKP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LIKP_IsIncomplete] DEFAULT ('N'),
[_BEV1_LULEINH] [nvarchar] (8) NULL,
[_BEV1_RPCONT] [decimal] (18, 0) NULL,
[_BEV1_RPFAESS] [decimal] (18, 0) NULL,
[_BEV1_RPFLGNR] [nvarchar] (5) NULL,
[_BEV1_RPKIST] [decimal] (18, 0) NULL,
[_BEV1_RPSONST] [decimal] (18, 0) NULL,
[ABLAD] [nvarchar] (25) NULL,
[ABSSC] [nvarchar] (6) NULL,
[AEDAT] [datetime] NULL,
[AENAM] [nvarchar] (12) NULL,
[AKKUR] [decimal] (18, 0) NULL,
[AKPRZ] [decimal] (18, 0) NULL,
[AKWAE] [nvarchar] (5) NULL,
[AMTBL] [decimal] (18, 0) NULL,
[ANZPK] [nvarchar] (5) NULL,
[AULWE] [nvarchar] (10) NULL,
[AUTLF] [nvarchar] (1) NULL,
[BEROT] [nvarchar] (20) NULL,
[BLDAT] [datetime] NULL,
[BOLNR] [nvarchar] (35) NULL,
[BORGR_GRP] [nvarchar] (35) NULL,
[BTGEW] [decimal] (18, 0) NULL,
[BZIRK] [nvarchar] (6) NULL,
[CMFRE] [datetime] NULL,
[CMNGV] [datetime] NULL,
[CMWAE] [nvarchar] (5) NULL,
[COMMN] [nvarchar] (5) NULL,
[CONT_DG] [nvarchar] (1) NULL,
[CTLPC] [nvarchar] (3) NULL,
[DIRTA] [nvarchar] (1) NULL,
[DLV_SPLIT_INITIA] [nvarchar] (1) NULL,
[DLV_VERSION] [nvarchar] (4) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[ERZET] [datetime] NULL,
[EXNUM] [nvarchar] (10) NULL,
[EXPKZ] [nvarchar] (1) NULL,
[FAKSK] [nvarchar] (2) NULL,
[FKAIV] [nvarchar] (4) NULL,
[FKARV] [nvarchar] (4) NULL,
[FKDAT] [datetime] NULL,
[FKDIV] [datetime] NULL,
[FOLAR] [nvarchar] (4) NULL,
[GEWEI] [nvarchar] (3) NULL,
[GRULG] [nvarchar] (4) NULL,
[GRUPP] [nvarchar] (4) NULL,
[HANDLE] [nvarchar] (22) NULL,
[IMWRK] [nvarchar] (1) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[KALSM] [nvarchar] (6) NULL,
[KALSM_CH] [nvarchar] (6) NULL,
[KALSP] [nvarchar] (6) NULL,
[KDGRP] [nvarchar] (2) NULL,
[KKBER] [nvarchar] (4) NULL,
[KLIEF] [nvarchar] (1) NULL,
[KNFAK] [nvarchar] (2) NULL,
[KNKLI] [nvarchar] (10) NULL,
[KNUMP] [nvarchar] (10) NULL,
[KNUMV] [nvarchar] (10) NULL,
[KODAT] [datetime] NULL,
[KOUHR] [datetime] NULL,
[KUNAG] [nvarchar] (10) NULL,
[KUNIV] [nvarchar] (10) NULL,
[KUNNR] [nvarchar] (10) NULL,
[KZAZU] [nvarchar] (1) NULL,
[KZWAB] [nvarchar] (1) NULL,
[LCNUM] [nvarchar] (10) NULL,
[LDDAT] [datetime] NULL,
[LDUHR] [datetime] NULL,
[LFART] [nvarchar] (4) NULL,
[LFDAT] [datetime] NULL,
[LFUHR] [datetime] NULL,
[LGBZO] [nvarchar] (10) NULL,
[LGNUM] [nvarchar] (3) NULL,
[LGTOR] [nvarchar] (3) NULL,
[LIFEX] [nvarchar] (35) NULL,
[LIFNR] [nvarchar] (10) NULL,
[LIFSK] [nvarchar] (2) NULL,
[LISPL] [nvarchar] (1) NULL,
[LOC_GUID] [binary] (16) NULL,
[LPRIO] [nvarchar] (2) NULL,
[LSTEL] [nvarchar] (2) NULL,
[MANDT] [nvarchar] (3) NULL,
[MSR_ACTIVE] [nvarchar] (1) NULL,
[NETWR] [decimal] (18, 0) NULL,
[NTGEW] [decimal] (18, 0) NULL,
[PERFK] [nvarchar] (2) NULL,
[PIOIV] [nvarchar] (2) NULL,
[PODAT] [datetime] NULL,
[POTIM] [datetime] NULL,
[PRINTER_PROFILE] [nvarchar] (10) NULL,
[PROLI] [nvarchar] (3) NULL,
[PRTNR] [nvarchar] (10) NULL,
[PRVBE] [nvarchar] (10) NULL,
[ROUTA] [nvarchar] (6) NULL,
[ROUTE] [nvarchar] (6) NULL,
[SAKES] [nvarchar] (1) NULL,
[SBGRP] [nvarchar] (3) NULL,
[SDABW] [nvarchar] (4) NULL,
[SPAIV] [nvarchar] (2) NULL,
[SPE_ACC_APP_STS] [nvarchar] (1) NULL,
[SPE_BILLING_IND] [nvarchar] (1) NULL,
[SPE_CARRIER_IND] [nvarchar] (1) NULL,
[SPE_CHNG_SYS] [nvarchar] (1) NULL,
[SPE_GEOROUTE] [nvarchar] (10) NULL,
[SPE_GEOROUTEIND] [nvarchar] (1) NULL,
[SPE_GTS_REL] [nvarchar] (2) NULL,
[SPE_GTS_RT_CDE] [nvarchar] (10) NULL,
[SPE_INV_BFR_GI] [nvarchar] (1) NULL,
[SPE_LE_SCENARIO] [nvarchar] (1) NULL,
[SPE_LIFEX_TYPE] [nvarchar] (1) NULL,
[SPE_LOC_SEQ] [nvarchar] (3) NULL,
[SPE_LOEKZ] [nvarchar] (1) NULL,
[SPE_ORIG_SYS] [nvarchar] (1) NULL,
[SPE_PRO_NUMBER] [nvarchar] (35) NULL,
[SPE_QI_STATUS] [nvarchar] (1) NULL,
[SPE_RED_IND] [nvarchar] (1) NULL,
[SPE_REL_TMSTMP] [decimal] (18, 0) NULL,
[SPE_RET_CANC] [nvarchar] (1) NULL,
[SPE_REV_VLSTK] [nvarchar] (1) NULL,
[SPE_SHP_INF_STS] [nvarchar] (1) NULL,
[SPE_TTYPE] [nvarchar] (10) NULL,
[SPE_UNIT_SYSTEM] [nvarchar] (10) NULL,
[SPE_WAUHR_IST] [datetime] NULL,
[SPE_WAZONE_IST] [nvarchar] (6) NULL,
[STAFO] [nvarchar] (6) NULL,
[STCUR] [decimal] (18, 0) NULL,
[STGE_LOC_CHANGE] [nvarchar] (1) NULL,
[STWAE] [nvarchar] (5) NULL,
[STZKL] [decimal] (18, 0) NULL,
[STZZU] [decimal] (18, 0) NULL,
[TCODE] [nvarchar] (20) NULL,
[TDDAT] [datetime] NULL,
[TDUHR] [datetime] NULL,
[TERNR] [nvarchar] (12) NULL,
[TM_CTRL_KEY] [nvarchar] (4) NULL,
[TPGRP] [nvarchar] (2) NULL,
[TPQUA] [nvarchar] (1) NULL,
[TPSID] [nvarchar] (5) NULL,
[TRAGR] [nvarchar] (4) NULL,
[TRAID] [nvarchar] (20) NULL,
[TRATY] [nvarchar] (4) NULL,
[TRMTYP] [nvarchar] (18) NULL,
[TRSPG] [nvarchar] (2) NULL,
[TSEGFL] [nvarchar] (1) NULL,
[TSEGTP] [nvarchar] (10) NULL,
[TZONIS] [nvarchar] (6) NULL,
[TZONRC] [nvarchar] (6) NULL,
[VBEAK] [decimal] (18, 0) NULL,
[VBELN] [nvarchar] (10) NOT NULL,
[VBTYP] [nvarchar] (1) NULL,
[VBUND] [nvarchar] (6) NULL,
[VERUR] [nvarchar] (35) NULL,
[VERURSYS] [nvarchar] (10) NULL,
[VGANZ] [bigint] NULL,
[VKBUR] [nvarchar] (4) NULL,
[VKOIV] [nvarchar] (4) NULL,
[VKORG] [nvarchar] (4) NULL,
[VLSTK] [nvarchar] (1) NULL,
[VOLEH] [nvarchar] (3) NULL,
[VOLUM] [decimal] (18, 0) NULL,
[VSART] [nvarchar] (2) NULL,
[VSBED] [nvarchar] (2) NULL,
[VSTEL] [nvarchar] (4) NULL,
[VTWIV] [nvarchar] (2) NULL,
[WADAT] [datetime] NULL,
[WADAT_IST] [datetime] NULL,
[WAERK] [nvarchar] (5) NULL,
[WAUHR] [datetime] NULL,
[WERKS] [nvarchar] (4) NULL,
[XABLN] [nvarchar] (10) NULL,
[XBLNR] [nvarchar] (25) NULL,
[XWOFF] [nvarchar] (1) NULL,
[ZUKRL] [nvarchar] (40) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_LIKP_PK] on [psa].[ics_stg_SAP_GBR_LIKP]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_LIKP] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_LIKP_PK] PRIMARY KEY CLUSTERED  ([VBELN])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_LFB1]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_LFB1]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LFB1_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LFB1_IsIncomplete] DEFAULT ('N'),
[AD_HASH] [nvarchar] (10) NULL,
[AKONT] [nvarchar] (10) NULL,
[ALTKN] [nvarchar] (10) NULL,
[ASSIGN_TEST] [nvarchar] (4) NULL,
[AVSND] [nvarchar] (1) NULL,
[BASIS_PNT] [decimal] (18, 0) NULL,
[BEGRU] [nvarchar] (4) NULL,
[BLNKZ] [nvarchar] (2) NULL,
[BUKRS] [nvarchar] (4) NOT NULL,
[BUSAB] [nvarchar] (2) NULL,
[CERDT] [datetime] NULL,
[CIIUCODE] [nvarchar] (4) NULL,
[CONFS] [nvarchar] (1) NULL,
[DATLZ] [datetime] NULL,
[EIKTO] [nvarchar] (12) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[FDGRV] [nvarchar] (10) NULL,
[FRGRP] [nvarchar] (4) NULL,
[GMVKZK] [nvarchar] (1) NULL,
[GRICD] [nvarchar] (2) NULL,
[GRIDT] [nvarchar] (2) NULL,
[GUZTE] [nvarchar] (4) NULL,
[HBKID] [nvarchar] (5) NULL,
[INTAD] [nvarchar] (130) NULL,
[J_SC_COMPDATE] [nvarchar] (3) NULL,
[J_SC_OFFSM] [nvarchar] (1) NULL,
[J_SC_OFFSR] [nvarchar] (3) NULL,
[J_SC_SUBCONTYPE] [nvarchar] (1) NULL,
[KULTG] [decimal] (18, 0) NULL,
[KVERM] [nvarchar] (30) NULL,
[LIFNR] [nvarchar] (10) NOT NULL,
[LNRZB] [nvarchar] (10) NULL,
[LNRZE] [nvarchar] (10) NULL,
[LOEVM] [nvarchar] (1) NULL,
[MANDT] [nvarchar] (3) NULL,
[MGRUP] [nvarchar] (2) NULL,
[MINDK] [nvarchar] (3) NULL,
[NODEL] [nvarchar] (1) NULL,
[PERNR] [nvarchar] (8) NULL,
[PREPAY_RELEVANT] [nvarchar] (1) NULL,
[QLAND] [nvarchar] (3) NULL,
[QSBGR] [nvarchar] (1) NULL,
[QSREC] [nvarchar] (2) NULL,
[QSSKZ] [nvarchar] (2) NULL,
[QSZDT] [datetime] NULL,
[QSZNR] [nvarchar] (10) NULL,
[REPRF] [nvarchar] (1) NULL,
[SPERR] [nvarchar] (1) NULL,
[TLFNS] [nvarchar] (30) NULL,
[TLFXS] [nvarchar] (31) NULL,
[TOGRR] [nvarchar] (4) NULL,
[TOGRU] [nvarchar] (4) NULL,
[UPDAT] [datetime] NULL,
[UPTIM] [datetime] NULL,
[UZAWE] [nvarchar] (2) NULL,
[VZSKZ] [nvarchar] (2) NULL,
[WEBTR] [decimal] (18, 0) NULL,
[XAUSZ] [nvarchar] (1) NULL,
[XDEZV] [nvarchar] (1) NULL,
[XEDIP] [nvarchar] (1) NULL,
[XLFZB] [nvarchar] (1) NULL,
[XPORE] [nvarchar] (1) NULL,
[XVERR] [nvarchar] (1) NULL,
[ZAHLS] [nvarchar] (1) NULL,
[ZGRUP] [nvarchar] (2) NULL,
[ZINDT] [datetime] NULL,
[ZINRT] [nvarchar] (2) NULL,
[ZSABE] [nvarchar] (15) NULL,
[ZTERM] [nvarchar] (4) NULL,
[ZUAWA] [nvarchar] (3) NULL,
[ZWELS] [nvarchar] (10) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_LFB1_PK] on [psa].[ics_stg_SAP_GBR_LFB1]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_LFB1] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_LFB1_PK] PRIMARY KEY CLUSTERED  ([LIFNR], [BUKRS])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_LFA1]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_LFA1]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LFA1_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_LFA1_IsIncomplete] DEFAULT ('N'),
[ACTSS] [nvarchar] (3) NULL,
[ADRNR] [nvarchar] (10) NULL,
[ALC] [nvarchar] (8) NULL,
[ANRED] [nvarchar] (15) NULL,
[BAHNS] [nvarchar] (25) NULL,
[BBBNR] [nvarchar] (7) NULL,
[BBSNR] [nvarchar] (5) NULL,
[BEGRU] [nvarchar] (4) NULL,
[BRSCH] [nvarchar] (4) NULL,
[BUBKZ] [nvarchar] (1) NULL,
[CARRIER_CONF] [nvarchar] (1) NULL,
[CNAE] [nvarchar] (7) NULL,
[COMSIZE] [nvarchar] (2) NULL,
[CONFS] [nvarchar] (1) NULL,
[CRC_NUM] [nvarchar] (25) NULL,
[CRTN] [nvarchar] (1) NULL,
[DATLT] [nvarchar] (14) NULL,
[DECREGPC] [nvarchar] (2) NULL,
[DLGRP] [nvarchar] (4) NULL,
[DTAMS] [nvarchar] (1) NULL,
[DTAWS] [nvarchar] (2) NULL,
[DUEFL] [nvarchar] (1) NULL,
[EMNFR] [nvarchar] (10) NULL,
[ERDAT] [datetime] NULL,
[ERNAM] [nvarchar] (12) NULL,
[ESRNR] [nvarchar] (11) NULL,
[EXP] [nvarchar] (3) NULL,
[FISKN] [nvarchar] (10) NULL,
[FISKU] [nvarchar] (10) NULL,
[FITYP] [nvarchar] (2) NULL,
[GBDAT] [datetime] NULL,
[GBORT] [nvarchar] (25) NULL,
[ICMSTAXPAY] [nvarchar] (2) NULL,
[INDTYP] [nvarchar] (2) NULL,
[IPISP] [nvarchar] (1) NULL,
[J_1KFREPRE] [nvarchar] (10) NULL,
[J_1KFTBUS] [nvarchar] (30) NULL,
[J_1KFTIND] [nvarchar] (30) NULL,
[J_SC_CAPITAL] [decimal] (18, 0) NULL,
[J_SC_CURRENCY] [nvarchar] (5) NULL,
[KONZS] [nvarchar] (10) NULL,
[KRAUS] [nvarchar] (11) NULL,
[KTOCK] [nvarchar] (4) NULL,
[KTOKK] [nvarchar] (4) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LAND1] [nvarchar] (3) NULL,
[LEGALNAT] [nvarchar] (4) NULL,
[LFURL] [nvarchar] (132) NULL,
[LIFNR] [nvarchar] (10) NOT NULL,
[LNRZA] [nvarchar] (10) NULL,
[LOEVM] [nvarchar] (1) NULL,
[LTSNA] [nvarchar] (1) NULL,
[LZONE] [nvarchar] (10) NULL,
[MANDT] [nvarchar] (3) NULL,
[MCOD1] [nvarchar] (25) NULL,
[MCOD2] [nvarchar] (25) NULL,
[MCOD3] [nvarchar] (25) NULL,
[MIN_COMP] [nvarchar] (1) NULL,
[NAME1] [nvarchar] (35) NULL,
[NAME2] [nvarchar] (35) NULL,
[NAME3] [nvarchar] (35) NULL,
[NAME4] [nvarchar] (35) NULL,
[NODEL] [nvarchar] (1) NULL,
[ORT01] [nvarchar] (35) NULL,
[ORT02] [nvarchar] (35) NULL,
[PFACH] [nvarchar] (10) NULL,
[PFORT] [nvarchar] (35) NULL,
[PLKAL] [nvarchar] (2) NULL,
[PMT_OFFICE] [nvarchar] (5) NULL,
[PODKZB] [nvarchar] (1) NULL,
[PROFS] [nvarchar] (30) NULL,
[PSOFG] [nvarchar] (10) NULL,
[PSOHS] [nvarchar] (6) NULL,
[PSOIS] [nvarchar] (20) NULL,
[PSON1] [nvarchar] (35) NULL,
[PSON2] [nvarchar] (35) NULL,
[PSON3] [nvarchar] (35) NULL,
[PSOST] [nvarchar] (28) NULL,
[PSOTL] [nvarchar] (20) NULL,
[PSOVN] [nvarchar] (35) NULL,
[PSTL2] [nvarchar] (10) NULL,
[PSTLZ] [nvarchar] (10) NULL,
[QSSYS] [nvarchar] (4) NULL,
[QSSYSDAT] [datetime] NULL,
[REGIO] [nvarchar] (3) NULL,
[REGSS] [nvarchar] (1) NULL,
[REVDB] [datetime] NULL,
[RG] [nvarchar] (11) NULL,
[RGDATE] [datetime] NULL,
[RIC] [nvarchar] (11) NULL,
[RNE] [nvarchar] (10) NULL,
[RNEDATE] [datetime] NULL,
[SCACD] [nvarchar] (4) NULL,
[SCHEDULING_TYPE] [nvarchar] (1) NULL,
[SEXKZ] [nvarchar] (1) NULL,
[SFRGR] [nvarchar] (4) NULL,
[SORTL] [nvarchar] (10) NULL,
[SPERM] [nvarchar] (1) NULL,
[SPERQ] [nvarchar] (2) NULL,
[SPERR] [nvarchar] (1) NULL,
[SPERZ] [nvarchar] (1) NULL,
[SPRAS] [nvarchar] (1) NULL,
[STAGING_TIME] [decimal] (18, 0) NULL,
[STCD1] [nvarchar] (16) NULL,
[STCD2] [nvarchar] (11) NULL,
[STCD3] [nvarchar] (18) NULL,
[STCD4] [nvarchar] (18) NULL,
[STCD5] [nvarchar] (60) NULL,
[STCDT] [nvarchar] (2) NULL,
[STCEG] [nvarchar] (20) NULL,
[STENR] [nvarchar] (18) NULL,
[STGDL] [nvarchar] (2) NULL,
[STKZA] [nvarchar] (1) NULL,
[STKZN] [nvarchar] (1) NULL,
[STKZU] [nvarchar] (1) NULL,
[STRAS] [nvarchar] (35) NULL,
[SUBMI_RELEVANT] [nvarchar] (1) NULL,
[TAXBS] [nvarchar] (1) NULL,
[TDT] [nvarchar] (2) NULL,
[TELBX] [nvarchar] (15) NULL,
[TELF1] [nvarchar] (16) NULL,
[TELF2] [nvarchar] (16) NULL,
[TELFX] [nvarchar] (31) NULL,
[TELTX] [nvarchar] (30) NULL,
[TELX1] [nvarchar] (30) NULL,
[TERM_LI] [nvarchar] (1) NULL,
[TRANSPORT_CHAIN] [nvarchar] (10) NULL,
[TXJCD] [nvarchar] (15) NULL,
[UF] [nvarchar] (2) NULL,
[UPDAT] [datetime] NULL,
[UPTIM] [datetime] NULL,
[VBUND] [nvarchar] (6) NULL,
[WERKR] [nvarchar] (1) NULL,
[WERKS] [nvarchar] (4) NULL,
[XCPDK] [nvarchar] (1) NULL,
[XLFZA] [nvarchar] (1) NULL,
[XZEMP] [nvarchar] (1) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_LFA1_PK] on [psa].[ics_stg_SAP_GBR_LFA1]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_LFA1] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_LFA1_PK] PRIMARY KEY CLUSTERED  ([LIFNR])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_EKET]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_EKET]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKET_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKET_IsIncomplete] DEFAULT ('N'),
[ABART] [nvarchar] (1) NULL,
[ALTDT] [datetime] NULL,
[AMENG] [decimal] (18, 0) NULL,
[ANZSN] [bigint] NULL,
[AULWE] [nvarchar] (10) NULL,
[BANFN] [nvarchar] (10) NULL,
[BEDAT] [datetime] NULL,
[BNFPO] [nvarchar] (5) NULL,
[BUDG_TYPE] [nvarchar] (2) NULL,
[CD_LOCNO] [nvarchar] (20) NULL,
[CD_LOCTYPE] [nvarchar] (4) NULL,
[CHARG] [nvarchar] (10) NULL,
[CHECK_TYPE] [nvarchar] (1) NULL,
[CHKOM] [nvarchar] (1) NULL,
[CNCL_ANCMNT_DONE] [nvarchar] (1) NULL,
[DABMG] [decimal] (18, 0) NULL,
[DAT01] [datetime] NULL,
[DATESHIFT_NUMBER] [decimal] (18, 0) NULL,
[DL_ID] [nvarchar] (22) NULL,
[DNG_DATE] [datetime] NULL,
[DNG_TIME] [datetime] NULL,
[EBELN] [nvarchar] (10) NOT NULL,
[EBELP] [nvarchar] (5) NOT NULL,
[EINDT] [datetime] NULL,
[ELDAT] [datetime] NULL,
[ELUHR] [datetime] NULL,
[ESTKZ] [nvarchar] (1) NULL,
[ETENR] [nvarchar] (4) NOT NULL,
[FIXKZ] [nvarchar] (1) NULL,
[GEO_ROUTE] [nvarchar] (10) NULL,
[GLMNG] [decimal] (18, 0) NULL,
[GTS_IND] [nvarchar] (2) NULL,
[HANDOVER_DATE] [datetime] NULL,
[KEY_ID] [nvarchar] (16) NULL,
[LDDAT] [datetime] NULL,
[LDUHR] [datetime] NULL,
[LICHA] [nvarchar] (15) NULL,
[LPEIN] [nvarchar] (1) NULL,
[MAHNZ] [decimal] (18, 0) NULL,
[MANDT] [nvarchar] (3) NULL,
[MBDAT] [datetime] NULL,
[MBUHR] [datetime] NULL,
[MENGE] [decimal] (18, 0) NULL,
[MNG02] [decimal] (18, 0) NULL,
[NO_SCEM] [nvarchar] (1) NULL,
[NODISP] [nvarchar] (1) NULL,
[OTB_CURR] [nvarchar] (5) NULL,
[OTB_REASON] [nvarchar] (3) NULL,
[OTB_RES_VALUE] [decimal] (18, 0) NULL,
[OTB_SPEC_VALUE] [decimal] (18, 0) NULL,
[OTB_STATUS] [nvarchar] (1) NULL,
[OTB_VALUE] [decimal] (18, 0) NULL,
[QUNUM] [nvarchar] (10) NULL,
[QUPOS] [nvarchar] (3) NULL,
[ROUTE_GTS] [nvarchar] (10) NULL,
[RSNUM] [nvarchar] (10) NULL,
[SERNR] [nvarchar] (8) NULL,
[SLFDT] [datetime] NULL,
[SPR_RSN_PROFILE] [nvarchar] (4) NULL,
[TDDAT] [datetime] NULL,
[TDUHR] [datetime] NULL,
[TSP] [nvarchar] (10) NULL,
[UZEIT] [datetime] NULL,
[VERID] [nvarchar] (4) NULL,
[WADAT] [datetime] NULL,
[WAMNG] [decimal] (18, 0) NULL,
[WAUHR] [datetime] NULL,
[WEMNG] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_EKET_PK] on [psa].[ics_stg_SAP_GBR_EKET]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EKET] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_EKET_PK] PRIMARY KEY CLUSTERED  ([EBELN], [EBELP], [ETENR])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_EKKO]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_EKKO]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKKO_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKKO_IsIncomplete] DEFAULT ('N'),
[ABGRU] [nvarchar] (2) NULL,
[ABSGR] [nvarchar] (2) NULL,
[ADDNR] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[AEDAT] [datetime] NULL,
[ANGDT] [datetime] NULL,
[ANGNR] [nvarchar] (10) NULL,
[AUREL_ALLOW] [nvarchar] (1) NULL,
[AUSNR] [nvarchar] (10) NULL,
[AUTLF] [nvarchar] (1) NULL,
[BEDAT] [datetime] NULL,
[BNDDT] [datetime] NULL,
[BSAKZ] [nvarchar] (1) NULL,
[BSART] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[BUDG_TYPE] [nvarchar] (2) NULL,
[BUKRS] [nvarchar] (4) NULL,
[BWBDT] [datetime] NULL,
[CHECK_TYPE] [nvarchar] (1) NULL,
[CON_DISTR_LEV] [nvarchar] (1) NULL,
[CON_OTB_REQ] [nvarchar] (1) NULL,
[CON_PREBOOK_LEV] [nvarchar] (1) NULL,
[CONTRACT_ALLOW] [nvarchar] (1) NULL,
[DELPER_ALLOW] [nvarchar] (1) NULL,
[DESCRIPTION] [nvarchar] (40) NULL,
[DPAMT] [decimal] (18, 0) NULL,
[DPDAT] [datetime] NULL,
[DPPCT] [decimal] (18, 0) NULL,
[DPTYP] [nvarchar] (4) NULL,
[EBELN] [nvarchar] (10) NOT NULL,
[EINDT_ALLOW] [nvarchar] (1) NULL,
[EKGRP] [nvarchar] (3) NULL,
[EKGRP_ALLOW] [nvarchar] (1) NULL,
[EKORG] [nvarchar] (4) NULL,
[EQ_EINDT] [datetime] NULL,
[EQ_WERKS] [nvarchar] (4) NULL,
[ERNAM] [nvarchar] (12) NULL,
[EXNUM] [nvarchar] (10) NULL,
[FIXPO] [nvarchar] (1) NULL,
[FIXPO_ALLOW] [nvarchar] (1) NULL,
[FORCE_CNT] [nvarchar] (6) NULL,
[FORCE_ID] [nvarchar] (32) NULL,
[FRGGR] [nvarchar] (2) NULL,
[FRGKE] [nvarchar] (1) NULL,
[FRGRL] [nvarchar] (1) NULL,
[FRGSX] [nvarchar] (2) NULL,
[FRGZU] [nvarchar] (8) NULL,
[GWLDT] [datetime] NULL,
[HIERARCHY_EXISTS] [nvarchar] (1) NULL,
[IHRAN] [datetime] NULL,
[IHREZ] [nvarchar] (12) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[KALSM] [nvarchar] (6) NULL,
[KDATB] [datetime] NULL,
[KDATE] [datetime] NULL,
[KEY_ID] [nvarchar] (16) NULL,
[KEY_ID_ALLOW] [nvarchar] (1) NULL,
[KNUMV] [nvarchar] (10) NULL,
[KONNR] [nvarchar] (10) NULL,
[KORNR] [nvarchar] (1) NULL,
[KTWRT] [decimal] (18, 0) NULL,
[KUFIX] [nvarchar] (1) NULL,
[KUNNR] [nvarchar] (10) NULL,
[LANDS] [nvarchar] (3) NULL,
[LBLIF] [nvarchar] (10) NULL,
[LEGAL_CONTRACT] [nvarchar] (40) NULL,
[LIFNR] [nvarchar] (10) NULL,
[LIFRE] [nvarchar] (10) NULL,
[LLIEF] [nvarchar] (10) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[LOGSY] [nvarchar] (10) NULL,
[LPHIS] [nvarchar] (1) NULL,
[LPONR] [nvarchar] (5) NULL,
[MANDT] [nvarchar] (3) NULL,
[MEMORY] [nvarchar] (1) NULL,
[MEMORYTYPE] [nvarchar] (1) NULL,
[MSR_ID] [nvarchar] (10) NULL,
[OTB_COND_TYPE] [nvarchar] (4) NULL,
[OTB_CURR] [nvarchar] (5) NULL,
[OTB_LEVEL] [nvarchar] (1) NULL,
[OTB_REASON] [nvarchar] (3) NULL,
[OTB_RES_VALUE] [decimal] (18, 0) NULL,
[OTB_SPEC_VALUE] [decimal] (18, 0) NULL,
[OTB_STATUS] [nvarchar] (1) NULL,
[OTB_VALUE] [decimal] (18, 0) NULL,
[PINCR] [nvarchar] (5) NULL,
[POHF_TYPE] [nvarchar] (1) NULL,
[PROCSTAT] [nvarchar] (2) NULL,
[PSTYP_ALLOW] [nvarchar] (1) NULL,
[REASON_CODE] [nvarchar] (4) NULL,
[RELEASE_DATE] [datetime] NULL,
[RELOC_ID] [nvarchar] (10) NULL,
[RELOC_SEQ_ID] [nvarchar] (4) NULL,
[RESWK] [nvarchar] (4) NULL,
[RETPC] [decimal] (18, 0) NULL,
[RETTP] [nvarchar] (1) NULL,
[REVNO] [nvarchar] (8) NULL,
[RLWRT] [decimal] (18, 0) NULL,
[SCMPROC] [nvarchar] (1) NULL,
[SPR_RSN_PROFILE] [nvarchar] (4) NULL,
[SPRAS] [nvarchar] (1) NULL,
[STAFO] [nvarchar] (6) NULL,
[STAKO] [nvarchar] (1) NULL,
[STATU] [nvarchar] (1) NULL,
[STCEG] [nvarchar] (20) NULL,
[STCEG_L] [nvarchar] (3) NULL,
[SUBMI] [nvarchar] (10) NULL,
[TELF1] [nvarchar] (16) NULL,
[THRESHOLD_EXISTS] [nvarchar] (1) NULL,
[UNSEZ] [nvarchar] (12) NULL,
[UPINC] [nvarchar] (5) NULL,
[VERKF] [nvarchar] (30) NULL,
[WAERS] [nvarchar] (5) NULL,
[WEAKT] [nvarchar] (1) NULL,
[WERKS_ALLOW] [nvarchar] (1) NULL,
[WKURS] [decimal] (18, 0) NULL,
[ZBD1P] [decimal] (18, 0) NULL,
[ZBD1T] [decimal] (18, 0) NULL,
[ZBD2P] [decimal] (18, 0) NULL,
[ZBD2T] [decimal] (18, 0) NULL,
[ZBD3T] [decimal] (18, 0) NULL,
[ZTERM] [nvarchar] (4) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_EKKO_PK] on [psa].[ics_stg_SAP_GBR_EKKO]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EKKO] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_EKKO_PK] PRIMARY KEY CLUSTERED  ([EBELN])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_EKPO]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_EKPO]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKPO_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_EKPO_IsIncomplete] DEFAULT ('N'),
[_BEV1_NEDEPFREE] [nvarchar] (1) NULL,
[_BEV1_NEGEN_ITEM] [nvarchar] (1) NULL,
[_BEV1_NESTRUCCAT] [nvarchar] (1) NULL,
[ABDAT] [datetime] NULL,
[ABELN] [nvarchar] (10) NULL,
[ABELP] [nvarchar] (5) NULL,
[ABFTZ] [decimal] (18, 0) NULL,
[ABMNG] [decimal] (18, 0) NULL,
[ABSKZ] [nvarchar] (1) NULL,
[ABUEB] [nvarchar] (4) NULL,
[ADRN2] [nvarchar] (10) NULL,
[ADRNR] [nvarchar] (10) NULL,
[ADVCODE] [nvarchar] (2) NULL,
[AEDAT] [datetime] NULL,
[AFNAM] [nvarchar] (12) NULL,
[AGDAT] [datetime] NULL,
[AGMEM] [nvarchar] (3) NULL,
[AKTNR] [nvarchar] (10) NULL,
[ANFNR] [nvarchar] (10) NULL,
[ANFPS] [nvarchar] (5) NULL,
[ANZPU] [decimal] (18, 0) NULL,
[ANZSN] [bigint] NULL,
[APOMS] [nvarchar] (1) NULL,
[ARSNR] [nvarchar] (10) NULL,
[ARSPS] [nvarchar] (4) NULL,
[ATTYP] [nvarchar] (2) NULL,
[AUREL] [nvarchar] (1) NULL,
[BANFN] [nvarchar] (10) NULL,
[BEDNR] [nvarchar] (10) NULL,
[BERID] [nvarchar] (10) NULL,
[BLK_REASON_ID] [nvarchar] (4) NULL,
[BLK_REASON_TXT] [nvarchar] (40) NULL,
[BNFPO] [nvarchar] (5) NULL,
[BONBA] [decimal] (18, 0) NULL,
[BONUS] [nvarchar] (2) NULL,
[BPRME] [nvarchar] (3) NULL,
[BPUMN] [decimal] (18, 0) NULL,
[BPUMZ] [decimal] (18, 0) NULL,
[BRGEW] [decimal] (18, 0) NULL,
[BRTWR] [decimal] (18, 0) NULL,
[BSGRU] [nvarchar] (3) NULL,
[BSTAE] [nvarchar] (4) NULL,
[BSTYP] [nvarchar] (1) NULL,
[BUDGET_PD] [nvarchar] (10) NULL,
[BUKRS] [nvarchar] (4) NULL,
[BWTAR] [nvarchar] (10) NULL,
[BWTTY] [nvarchar] (1) NULL,
[CCOMP] [nvarchar] (1) NULL,
[CHG_FPLNR] [nvarchar] (1) NULL,
[CHG_SRV] [nvarchar] (1) NULL,
[CONS_ORDER] [nvarchar] (1) NULL,
[CQU_SAR] [decimal] (18, 0) NULL,
[CUOBJ] [nvarchar] (18) NULL,
[DPAMT] [decimal] (18, 0) NULL,
[DPDAT] [datetime] NULL,
[DPPCT] [decimal] (18, 0) NULL,
[DPTYP] [nvarchar] (4) NULL,
[DRDAT] [datetime] NULL,
[DRUHR] [datetime] NULL,
[DRUNR] [nvarchar] (4) NULL,
[EAN11] [nvarchar] (18) NULL,
[EBELN] [nvarchar] (10) NOT NULL,
[EBELP] [nvarchar] (5) NOT NULL,
[EBON2] [nvarchar] (2) NULL,
[EBON3] [nvarchar] (2) NULL,
[EBONF] [nvarchar] (1) NULL,
[EFFWR] [decimal] (18, 0) NULL,
[EGLKZ] [nvarchar] (1) NULL,
[EHTYP] [nvarchar] (4) NULL,
[EILDT] [datetime] NULL,
[EKKOL] [nvarchar] (4) NULL,
[ELIKZ] [nvarchar] (1) NULL,
[EMATN] [nvarchar] (18) NULL,
[EMLIF] [nvarchar] (10) NULL,
[EMNFR] [nvarchar] (10) NULL,
[EMPST] [nvarchar] (25) NULL,
[EREKZ] [nvarchar] (1) NULL,
[ETDRK] [nvarchar] (1) NULL,
[ETFZ1] [decimal] (18, 0) NULL,
[ETFZ2] [decimal] (18, 0) NULL,
[EVERS] [nvarchar] (2) NULL,
[EXCPE] [nvarchar] (2) NULL,
[EXLIN] [nvarchar] (40) NULL,
[EXSNR] [nvarchar] (5) NULL,
[EXT_RFX_ITEM] [nvarchar] (10) NULL,
[EXT_RFX_NUMBER] [nvarchar] (35) NULL,
[EXT_RFX_SYSTEM] [nvarchar] (10) NULL,
[FABKZ] [nvarchar] (1) NULL,
[FFZHI] [decimal] (18, 0) NULL,
[FIPOS] [nvarchar] (14) NULL,
[FISCAL_INCENTIVE] [nvarchar] (4) NULL,
[FISCAL_INCENTIVE_ID] [nvarchar] (4) NULL,
[FISTL] [nvarchar] (16) NULL,
[FIXMG] [nvarchar] (1) NULL,
[FKBER] [nvarchar] (16) NULL,
[FLS_RSTO] [nvarchar] (1) NULL,
[FMFGUS_KEY] [nvarchar] (22) NULL,
[FPLNR] [nvarchar] (10) NULL,
[GEBER] [nvarchar] (10) NULL,
[GEWEI] [nvarchar] (3) NULL,
[GNETWR] [decimal] (18, 0) NULL,
[GRANT_NBR] [nvarchar] (20) NULL,
[IDNLF] [nvarchar] (35) NULL,
[INCO1] [nvarchar] (3) NULL,
[INCO2] [nvarchar] (28) NULL,
[INFNR] [nvarchar] (10) NULL,
[INSMK] [nvarchar] (1) NULL,
[INSNC] [nvarchar] (1) NULL,
[IPRKZ] [nvarchar] (1) NULL,
[ITCONS] [nvarchar] (1) NULL,
[IUID_RELEVANT] [nvarchar] (1) NULL,
[J_1AIDATEP] [datetime] NULL,
[J_1AINDXP] [nvarchar] (5) NULL,
[J_1BINDUST] [nvarchar] (2) NULL,
[J_1BMATORG] [nvarchar] (1) NULL,
[J_1BMATUSE] [nvarchar] (1) NULL,
[J_1BNBM] [nvarchar] (16) NULL,
[J_1BOWNPRO] [nvarchar] (1) NULL,
[KANBA] [nvarchar] (1) NULL,
[KBLNR] [nvarchar] (10) NULL,
[KBLPOS] [nvarchar] (3) NULL,
[KNTTP] [nvarchar] (1) NULL,
[KO_GSBER] [nvarchar] (4) NULL,
[KO_PARGB] [nvarchar] (4) NULL,
[KO_PPRCTR] [nvarchar] (10) NULL,
[KO_PRCTR] [nvarchar] (10) NULL,
[KOLIF] [nvarchar] (10) NULL,
[KONNR] [nvarchar] (10) NULL,
[KTMNG] [decimal] (18, 0) NULL,
[KTPNR] [nvarchar] (5) NULL,
[KUNNR] [nvarchar] (10) NULL,
[KZABS] [nvarchar] (1) NULL,
[KZBWS] [nvarchar] (1) NULL,
[KZFME] [nvarchar] (1) NULL,
[KZKFG] [nvarchar] (1) NULL,
[KZSTU] [nvarchar] (1) NULL,
[KZTLF] [nvarchar] (1) NULL,
[KZVBR] [nvarchar] (1) NULL,
[KZWI1] [decimal] (18, 0) NULL,
[KZWI2] [decimal] (18, 0) NULL,
[KZWI3] [decimal] (18, 0) NULL,
[KZWI4] [decimal] (18, 0) NULL,
[KZWI5] [decimal] (18, 0) NULL,
[KZWI6] [decimal] (18, 0) NULL,
[LABNR] [nvarchar] (20) NULL,
[LBLKZ] [nvarchar] (1) NULL,
[LEBRE] [nvarchar] (1) NULL,
[LEWED] [datetime] NULL,
[LFRET] [nvarchar] (4) NULL,
[LGORT] [nvarchar] (4) NULL,
[LMEIN] [nvarchar] (3) NULL,
[LOEKZ] [nvarchar] (1) NULL,
[LTSNR] [nvarchar] (6) NULL,
[MAHN1] [decimal] (18, 0) NULL,
[MAHN2] [decimal] (18, 0) NULL,
[MAHN3] [decimal] (18, 0) NULL,
[MAHNZ] [decimal] (18, 0) NULL,
[MANDT] [nvarchar] (3) NULL,
[MANUAL_TC_REASON] [nvarchar] (2) NULL,
[MATKL] [nvarchar] (9) NULL,
[MATNR] [nvarchar] (18) NULL,
[MEINS] [nvarchar] (3) NULL,
[MENGE] [decimal] (18, 0) NULL,
[MEPRF] [nvarchar] (1) NULL,
[MFRGR] [nvarchar] (8) NULL,
[MFRNR] [nvarchar] (10) NULL,
[MFRPN] [nvarchar] (40) NULL,
[MFZHI] [decimal] (18, 0) NULL,
[MHDRZ] [decimal] (18, 0) NULL,
[MLMAA] [nvarchar] (1) NULL,
[MPROF] [nvarchar] (4) NULL,
[MRPIND] [nvarchar] (1) NULL,
[MTART] [nvarchar] (4) NULL,
[MWSKZ] [nvarchar] (2) NULL,
[NAVNW] [decimal] (18, 0) NULL,
[NETPR] [decimal] (18, 0) NULL,
[NETWR] [decimal] (18, 0) NULL,
[NFABD] [datetime] NULL,
[NLABD] [datetime] NULL,
[NOTKZ] [nvarchar] (1) NULL,
[NOVET] [nvarchar] (1) NULL,
[NRFHG] [nvarchar] (1) NULL,
[NTGEW] [decimal] (18, 0) NULL,
[PACKNO] [nvarchar] (10) NULL,
[PEINH] [decimal] (18, 0) NULL,
[PLIFZ] [decimal] (18, 0) NULL,
[POL_ID] [nvarchar] (10) NULL,
[PRDAT] [datetime] NULL,
[PRIO_REQ] [nvarchar] (3) NULL,
[PRIO_URG] [nvarchar] (2) NULL,
[PRSDR] [nvarchar] (1) NULL,
[PSTYP] [nvarchar] (1) NULL,
[PUNEI] [nvarchar] (3) NULL,
[PUT_BACK] [nvarchar] (1) NULL,
[RDPRF] [nvarchar] (4) NULL,
[REASON_CODE] [nvarchar] (4) NULL,
[REF_ITEM] [nvarchar] (5) NULL,
[REFSITE] [nvarchar] (4) NULL,
[REPOS] [nvarchar] (1) NULL,
[RESLO] [nvarchar] (4) NULL,
[RETPC] [decimal] (18, 0) NULL,
[RETPO] [nvarchar] (1) NULL,
[REVLV] [nvarchar] (2) NULL,
[SAISJ] [nvarchar] (4) NULL,
[SAISO] [nvarchar] (4) NULL,
[SATNR] [nvarchar] (18) NULL,
[SCHPR] [nvarchar] (1) NULL,
[SIKGR] [nvarchar] (3) NULL,
[SKTOF] [nvarchar] (1) NULL,
[SOBKZ] [nvarchar] (1) NULL,
[SOURCE_ID] [nvarchar] (3) NULL,
[SOURCE_KEY] [nvarchar] (32) NULL,
[SPE_ABGRU] [nvarchar] (2) NULL,
[SPE_CHNG_SYS] [nvarchar] (1) NULL,
[SPE_CQ_CTRLTYPE] [nvarchar] (1) NULL,
[SPE_CQ_NOCQ] [nvarchar] (1) NULL,
[SPE_CRM_FKREL] [nvarchar] (1) NULL,
[SPE_CRM_REF_ITEM] [nvarchar] (6) NULL,
[SPE_CRM_REF_SO] [nvarchar] (35) NULL,
[SPE_CRM_SO] [nvarchar] (10) NULL,
[SPE_CRM_SO_ITEM] [nvarchar] (6) NULL,
[SPE_EWM_DTC] [nvarchar] (1) NULL,
[SPE_INSMK_SRC] [nvarchar] (1) NULL,
[SPINF] [nvarchar] (1) NULL,
[SRM_CONTRACT_ID] [nvarchar] (10) NULL,
[SRM_CONTRACT_ITM] [nvarchar] (10) NULL,
[SRV_BAS_COM] [nvarchar] (1) NULL,
[SSQSS] [nvarchar] (8) NULL,
[STAFO] [nvarchar] (6) NULL,
[STAPO] [nvarchar] (1) NULL,
[STATU] [nvarchar] (1) NULL,
[STATUS] [nvarchar] (1) NULL,
[TAX_SUBJECT_ST] [nvarchar] (1) NULL,
[TC_AUT_DET] [nvarchar] (2) NULL,
[TECHS] [nvarchar] (12) NULL,
[TWRKZ] [nvarchar] (1) NULL,
[TXJCD] [nvarchar] (15) NULL,
[TXZ01] [nvarchar] (40) NULL,
[TZONRC] [nvarchar] (6) NULL,
[UEBPO] [nvarchar] (5) NULL,
[UEBTK] [nvarchar] (1) NULL,
[UEBTO] [decimal] (18, 0) NULL,
[UMREN] [decimal] (18, 0) NULL,
[UMREZ] [decimal] (18, 0) NULL,
[UMSOK] [nvarchar] (1) NULL,
[UNTTO] [decimal] (18, 0) NULL,
[UPTYP] [nvarchar] (1) NULL,
[UPVOR] [nvarchar] (1) NULL,
[USEQU] [nvarchar] (1) NULL,
[VOLEH] [nvarchar] (3) NULL,
[VOLUM] [decimal] (18, 0) NULL,
[VORAB] [nvarchar] (1) NULL,
[VRTKZ] [nvarchar] (1) NULL,
[WABWE] [nvarchar] (1) NULL,
[WEBAZ] [decimal] (18, 0) NULL,
[WEBRE] [nvarchar] (1) NULL,
[WEORA] [nvarchar] (1) NULL,
[WEPOS] [nvarchar] (1) NULL,
[WERKS] [nvarchar] (4) NULL,
[WEUNB] [nvarchar] (1) NULL,
[XCONDITIONS] [nvarchar] (1) NULL,
[XERSY] [nvarchar] (1) NULL,
[XOBLR] [nvarchar] (1) NULL,
[ZGTYP] [nvarchar] (4) NULL,
[ZWERT] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_EKPO_PK] on [psa].[ics_stg_SAP_GBR_EKPO]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_EKPO] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_EKPO_PK] PRIMARY KEY CLUSTERED  ([EBELN], [EBELP])
GO
PRINT N'Creating [psa].[ics_stg_SAP_GBR_ADRC]'
GO
CREATE TABLE [psa].[ics_stg_SAP_GBR_ADRC]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_ADRC_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_SAP_GBR_ADRC_IsIncomplete] DEFAULT ('N'),
[ADDR_GROUP] [nvarchar] (4) NULL,
[ADDRESS_ID] [nvarchar] (10) NULL,
[ADDRNUMBER] [nvarchar] (10) NOT NULL,
[ADDRORIGIN] [nvarchar] (4) NULL,
[BUILDING] [nvarchar] (20) NULL,
[CHCKSTATUS] [nvarchar] (1) NULL,
[CITY_CODE] [nvarchar] (12) NULL,
[CITY_CODE2] [nvarchar] (12) NULL,
[CITY1] [nvarchar] (40) NULL,
[CITY2] [nvarchar] (40) NULL,
[CITYH_CODE] [nvarchar] (12) NULL,
[CITYP_CODE] [nvarchar] (8) NULL,
[CLIENT] [nvarchar] (3) NULL,
[COUNTRY] [nvarchar] (3) NULL,
[DATE_FROM] [datetime2] NOT NULL,
[DATE_TO] [datetime2] NULL,
[DEFLT_COMM] [nvarchar] (3) NULL,
[DELI_SERV_NUMBER] [nvarchar] (10) NULL,
[DELI_SERV_TYPE] [nvarchar] (4) NULL,
[DONT_USE_P] [nvarchar] (4) NULL,
[DONT_USE_S] [nvarchar] (4) NULL,
[EXTENSION1] [nvarchar] (40) NULL,
[EXTENSION2] [nvarchar] (40) NULL,
[FAX_EXTENS] [nvarchar] (10) NULL,
[FAX_NUMBER] [nvarchar] (30) NULL,
[FLAGCOMM10] [nvarchar] (1) NULL,
[FLAGCOMM11] [nvarchar] (1) NULL,
[FLAGCOMM12] [nvarchar] (1) NULL,
[FLAGCOMM13] [nvarchar] (1) NULL,
[FLAGCOMM2] [nvarchar] (1) NULL,
[FLAGCOMM3] [nvarchar] (1) NULL,
[FLAGCOMM4] [nvarchar] (1) NULL,
[FLAGCOMM5] [nvarchar] (1) NULL,
[FLAGCOMM6] [nvarchar] (1) NULL,
[FLAGCOMM7] [nvarchar] (1) NULL,
[FLAGCOMM8] [nvarchar] (1) NULL,
[FLAGCOMM9] [nvarchar] (1) NULL,
[FLAGGROUPS] [nvarchar] (1) NULL,
[FLOOR] [nvarchar] (10) NULL,
[HOME_CITY] [nvarchar] (40) NULL,
[HOUSE_NUM1] [nvarchar] (10) NULL,
[HOUSE_NUM2] [nvarchar] (10) NULL,
[HOUSE_NUM3] [nvarchar] (10) NULL,
[LANGU] [nvarchar] (1) NULL,
[LANGU_CREA] [nvarchar] (1) NULL,
[LOCATION] [nvarchar] (40) NULL,
[MC_CITY1] [nvarchar] (25) NULL,
[MC_NAME1] [nvarchar] (25) NULL,
[MC_STREET] [nvarchar] (25) NULL,
[NAME_CO] [nvarchar] (40) NULL,
[NAME_TEXT] [nvarchar] (50) NULL,
[NAME1] [nvarchar] (40) NULL,
[NAME2] [nvarchar] (40) NULL,
[NAME3] [nvarchar] (40) NULL,
[NAME4] [nvarchar] (40) NULL,
[NATION] [nvarchar] (1) NULL,
[PCODE1_EXT] [nvarchar] (10) NULL,
[PCODE2_EXT] [nvarchar] (10) NULL,
[PCODE3_EXT] [nvarchar] (10) NULL,
[PERS_ADDR] [nvarchar] (1) NULL,
[PO_BOX] [nvarchar] (10) NULL,
[PO_BOX_CTY] [nvarchar] (3) NULL,
[PO_BOX_LOBBY] [nvarchar] (40) NULL,
[PO_BOX_LOC] [nvarchar] (40) NULL,
[PO_BOX_NUM] [nvarchar] (1) NULL,
[PO_BOX_REG] [nvarchar] (3) NULL,
[POST_CODE1] [nvarchar] (10) NULL,
[POST_CODE2] [nvarchar] (10) NULL,
[POST_CODE3] [nvarchar] (10) NULL,
[POSTALAREA] [nvarchar] (15) NULL,
[REGIOGROUP] [nvarchar] (8) NULL,
[REGION] [nvarchar] (3) NULL,
[ROOMNUMBER] [nvarchar] (10) NULL,
[SORT_PHN] [nvarchar] (20) NULL,
[SORT1] [nvarchar] (20) NULL,
[SORT2] [nvarchar] (20) NULL,
[STR_SUPPL1] [nvarchar] (40) NULL,
[STR_SUPPL2] [nvarchar] (40) NULL,
[STR_SUPPL3] [nvarchar] (40) NULL,
[STREET] [nvarchar] (60) NULL,
[STREETABBR] [nvarchar] (2) NULL,
[STREETCODE] [nvarchar] (12) NULL,
[TAXJURCODE] [nvarchar] (15) NULL,
[TEL_EXTENS] [nvarchar] (10) NULL,
[TEL_NUMBER] [nvarchar] (30) NULL,
[TIME_ZONE] [nvarchar] (6) NULL,
[TITLE] [nvarchar] (4) NULL,
[TRANSPZONE] [nvarchar] (10) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_ADRC_PK] on [psa].[ics_stg_SAP_GBR_ADRC]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_ADRC] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_ADRC_PK] PRIMARY KEY CLUSTERED  ([ADDRNUMBER], [DATE_FROM])
GO
