-- <Migration ID="5e3fab58-04b8-4304-bce2-6c3d6aab8613" />
GO

PRINT N'Creating [psa].[ics_stg_m3v7_CIDADR]'
GO
CREATE TABLE [psa].[ics_stg_m3v7_CIDADR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3v7_CIDADR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3v7_CIDADR_IsIncomplete] DEFAULT ('N'),
[SACONO] [decimal] (3, 0) NULL,
[SASUNO] [nvarchar] (255) NOT NULL,
[SAADTE] [decimal] (2, 0) NOT NULL,
[SAADID] [nvarchar] (255) NOT NULL,
[SASTDT] [decimal] (8, 0) NOT NULL,
[SASUNM] [nvarchar] (255) NULL,
[SAPRIA] [decimal] (1, 0) NULL,
[SAADR1] [nvarchar] (255) NULL,
[SAADR2] [nvarchar] (255) NULL,
[SAADR3] [nvarchar] (255) NULL,
[SAADR4] [nvarchar] (255) NULL,
[SACSCD] [nvarchar] (255) NULL,
[SAPONO] [nvarchar] (255) NULL,
[SAADVI] [nvarchar] (255) NULL,
[SAEDES] [nvarchar] (255) NULL,
[SAGEOC] [decimal] (9, 0) NULL,
[SATAXC] [nvarchar] (255) NULL,
[SAECAR] [nvarchar] (255) NULL,
[SATOWN] [nvarchar] (255) NULL,
[SAPNOD] [nvarchar] (255) NULL,
[SATXID] [decimal] (13, 0) NULL,
[SARGDT] [decimal] (8, 0) NULL,
[SARGTM] [decimal] (6, 0) NULL,
[SALMDT] [decimal] (8, 0) NULL,
[SACHNO] [decimal] (3, 0) NULL,
[SACHID] [nvarchar] (255) NULL,
[SALMTS] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_m3v7_CIDADR_PK] on [psa].[ics_stg_m3v7_CIDADR]'
GO
ALTER TABLE [psa].[ics_stg_m3v7_CIDADR] ADD CONSTRAINT [psa_ics_stg_m3v7_CIDADR_PK] PRIMARY KEY CLUSTERED  ([SASUNO], [SAADTE], [SAADID], [SASTDT])
GO
PRINT N'Creating [psa].[ics_stg_m3v7_CIDMAS]'
GO
CREATE TABLE [psa].[ics_stg_m3v7_CIDMAS]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3v7_CIDMAS_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3v7_CIDMAS_IsIncomplete] DEFAULT ('N'),
[IDCONO] [decimal] (3, 0) NULL,
[IDSUNO] [nvarchar] (255) NOT NULL,
[IDSUTY] [decimal] (1, 0) NULL,
[IDSUNM] [nvarchar] (255) NULL,
[IDALSU] [nvarchar] (255) NULL,
[IDSTAT] [nvarchar] (255) NULL,
[IDCORG] [nvarchar] (255) NULL,
[IDCOR2] [nvarchar] (255) NULL,
[IDLNCD] [nvarchar] (255) NULL,
[IDPHNO] [nvarchar] (255) NULL,
[IDPHN2] [nvarchar] (255) NULL,
[IDTLNO] [nvarchar] (255) NULL,
[IDTFNO] [nvarchar] (255) NULL,
[IDCSCD] [nvarchar] (255) NULL,
[IDECAR] [nvarchar] (255) NULL,
[IDDTFM] [nvarchar] (255) NULL,
[IDEDIT] [nvarchar] (255) NULL,
[IDVRNO] [nvarchar] (255) NULL,
[IDSUCO] [nvarchar] (255) NULL,
[IDSUAL] [nvarchar] (255) NULL,
[IDSUCM] [nvarchar] (255) NULL,
[IDMEPF] [nvarchar] (255) NULL,
[IDPODA] [decimal] (3, 0) NULL,
[IDCFI1] [nvarchar] (255) NULL,
[IDCFI2] [decimal] (15, 2) NULL,
[IDCFI3] [nvarchar] (255) NULL,
[IDCFI4] [nvarchar] (255) NULL,
[IDCFI5] [nvarchar] (255) NULL,
[IDHAFE] [nvarchar] (255) NULL,
[IDDESV] [nvarchar] (255) NULL,
[IDTIZO] [nvarchar] (255) NULL,
[IDFWSC] [nvarchar] (255) NULL,
[IDTXID] [decimal] (13, 0) NULL,
[IDRGDT] [decimal] (8, 0) NULL,
[IDRGTM] [decimal] (6, 0) NULL,
[IDLMDT] [decimal] (8, 0) NULL,
[IDCHNO] [decimal] (3, 0) NULL,
[IDCHID] [nvarchar] (255) NULL,
[IDLMTS] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_m3v7_CIDMAS_PK] on [psa].[ics_stg_m3v7_CIDMAS]'
GO
ALTER TABLE [psa].[ics_stg_m3v7_CIDMAS] ADD CONSTRAINT [psa_ics_stg_m3v7_CIDMAS_PK] PRIMARY KEY CLUSTERED  ([IDSUNO])
GO
PRINT N'Creating [psa].[ics_stg_m3v7_MITWHL]'
GO
CREATE TABLE [psa].[ics_stg_m3v7_MITWHL]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3v7_MITWHL_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3v7_MITWHL_IsIncomplete] DEFAULT ('N'),
[MWCONO] [decimal] (3, 0) NOT NULL,
[MWWHLO] [nvarchar] (255) NOT NULL,
[MWWHNM] [nvarchar] (255) NULL,
[MWDIVI] [nvarchar] (255) NULL,
[MWFACI] [nvarchar] (255) NULL,
[MWWHTY] [nvarchar] (255) NULL,
[MWWHSY] [nvarchar] (255) NULL,
[MWWHPL] [nvarchar] (255) NULL,
[MWOREF] [nvarchar] (255) NULL,
[MWPHNO] [nvarchar] (255) NULL,
[MWCOMA] [nvarchar] (255) NULL,
[MWCUNO] [nvarchar] (255) NULL,
[MWSUNO] [nvarchar] (255) NULL,
[MWSDES] [nvarchar] (255) NULL,
[MWSHNM] [nvarchar] (255) NULL,
[MWPLIS] [nvarchar] (255) NULL,
[MWCSCD] [nvarchar] (255) NULL,
[MWECAR] [nvarchar] (255) NULL,
[MWVRNO] [nvarchar] (255) NULL,
[MWLNCD] [nvarchar] (255) NULL,
[MWCPWH] [nvarchar] (255) NULL,
[MWAUAD] [decimal] (1, 0) NULL,
[MWALWH] [nvarchar] (255) NULL,
[MWALAC] [decimal] (1, 0) NULL,
[MWRESP] [nvarchar] (255) NULL,
[MWTWSL] [nvarchar] (255) NULL,
[MWGEOC] [decimal] (9, 0) NULL,
[MWTAXC] [nvarchar] (255) NULL,
[MWUNST] [nvarchar] (255) NULL,
[MWTXID] [decimal] (13, 0) NULL,
[MWDTID] [decimal] (13, 0) NULL,
[MWAASQ] [decimal] (1, 0) NULL,
[MWDMF0] [decimal] (3, 0) NULL,
[MWDMF1] [decimal] (3, 0) NULL,
[MWDMF2] [decimal] (3, 0) NULL,
[MWDMF3] [decimal] (3, 0) NULL,
[MWDMF4] [decimal] (3, 0) NULL,
[MWDMF5] [decimal] (3, 0) NULL,
[MWDMF6] [decimal] (3, 0) NULL,
[MWDMF7] [decimal] (3, 0) NULL,
[MWDMF8] [decimal] (3, 0) NULL,
[MWDMF9] [decimal] (3, 0) NULL,
[MWINUL] [decimal] (1, 0) NULL,
[MWEPUL] [decimal] (1, 0) NULL,
[MWEXDL] [decimal] (1, 0) NULL,
[MWPIDL] [decimal] (1, 0) NULL,
[MWALWQ] [nvarchar] (255) NULL,
[MWITDL] [decimal] (1, 0) NULL,
[MWCDYN] [decimal] (1, 0) NULL,
[MWPATF] [decimal] (3, 0) NULL,
[MWPAHF] [decimal] (4, 0) NULL,
[MWPMTF] [decimal] (3, 0) NULL,
[MWPMHF] [decimal] (4, 0) NULL,
[MWDDLO] [nvarchar] (255) NULL,
[MWCDPD] [decimal] (1, 0) NULL,
[MWCDPM] [decimal] (1, 0) NULL,
[MWCALV] [nvarchar] (255) NULL,
[MWACGR] [nvarchar] (255) NULL,
[MWNBID] [nvarchar] (255) NULL,
[MWSTOF] [decimal] (1, 0) NULL,
[MWASOT] [decimal] (1, 0) NULL,
[MWDAAS] [decimal] (2, 0) NULL,
[MWLEAM] [decimal] (3, 0) NULL,
[MWDMFC] [decimal] (1, 0) NULL,
[MWLSPM] [decimal] (1, 0) NULL,
[MWRSTN] [nvarchar] (255) NULL,
[MWRGDT] [decimal] (8, 0) NULL,
[MWRGTM] [decimal] (6, 0) NULL,
[MWLMDT] [decimal] (8, 0) NULL,
[MWCHNO] [decimal] (3, 0) NULL,
[MWCHID] [nvarchar] (255) NULL,
[MWLMTS] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_m3v7_MITWHL_PK] on [psa].[ics_stg_m3v7_MITWHL]'
GO
ALTER TABLE [psa].[ics_stg_m3v7_MITWHL] ADD CONSTRAINT [psa_ics_stg_m3v7_MITWHL_PK] PRIMARY KEY CLUSTERED  ([MWCONO], [MWWHLO])
GO
PRINT N'Creating [psa].[ics_stg_m3_CIDADR]'
GO
CREATE TABLE [psa].[ics_stg_m3_CIDADR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_CIDADR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_CIDADR_IsIncomplete] DEFAULT ('N'),
[SACONO] [decimal] (3, 0) NULL,
[SASUNO] [nvarchar] (255) NOT NULL,
[SAADTE] [decimal] (2, 0) NOT NULL,
[SAADID] [nvarchar] (255) NOT NULL,
[SASTDT] [decimal] (8, 0) NOT NULL,
[SASUNM] [nvarchar] (255) NULL,
[SAPRIA] [decimal] (1, 0) NULL,
[SAADR1] [nvarchar] (255) NULL,
[SAADR2] [nvarchar] (255) NULL,
[SAADR3] [nvarchar] (255) NULL,
[SAADR4] [nvarchar] (255) NULL,
[SACSCD] [nvarchar] (255) NULL,
[SAPONO] [nvarchar] (255) NULL,
[SAADVI] [nvarchar] (255) NULL,
[SAEDES] [nvarchar] (255) NULL,
[SAGEOC] [decimal] (9, 0) NULL,
[SATAXC] [nvarchar] (255) NULL,
[SAECAR] [nvarchar] (255) NULL,
[SATOWN] [nvarchar] (255) NULL,
[SAPNOD] [nvarchar] (255) NULL,
[SATXID] [decimal] (13, 0) NULL,
[SARGDT] [decimal] (8, 0) NULL,
[SARGTM] [decimal] (6, 0) NULL,
[SALMDT] [decimal] (8, 0) NULL,
[SACHNO] [decimal] (3, 0) NULL,
[SACHID] [nvarchar] (255) NULL,
[SALMTS] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_m3_CIDADR_PK] on [psa].[ics_stg_m3_CIDADR]'
GO
ALTER TABLE [psa].[ics_stg_m3_CIDADR] ADD CONSTRAINT [psa_ics_stg_m3_CIDADR_PK] PRIMARY KEY CLUSTERED  ([SASUNO], [SAADTE], [SAADID], [SASTDT])
GO
PRINT N'Creating [psa].[ics_stg_m3_CIDMAS]'
GO
CREATE TABLE [psa].[ics_stg_m3_CIDMAS]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_CIDMAS_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_CIDMAS_IsIncomplete] DEFAULT ('N'),
[IDCONO] [decimal] (3, 0) NULL,
[IDSUNO] [nvarchar] (255) NOT NULL,
[IDSUTY] [decimal] (1, 0) NULL,
[IDSUNM] [nvarchar] (255) NULL,
[IDALSU] [nvarchar] (255) NULL,
[IDSTAT] [nvarchar] (255) NULL,
[IDCORG] [nvarchar] (255) NULL,
[IDCOR2] [nvarchar] (255) NULL,
[IDLNCD] [nvarchar] (255) NULL,
[IDPHNO] [nvarchar] (255) NULL,
[IDPHN2] [nvarchar] (255) NULL,
[IDTLNO] [nvarchar] (255) NULL,
[IDTFNO] [nvarchar] (255) NULL,
[IDCSCD] [nvarchar] (255) NULL,
[IDECAR] [nvarchar] (255) NULL,
[IDDTFM] [nvarchar] (255) NULL,
[IDEDIT] [nvarchar] (255) NULL,
[IDVRNO] [nvarchar] (255) NULL,
[IDSUCO] [nvarchar] (255) NULL,
[IDSUAL] [nvarchar] (255) NULL,
[IDSUCM] [nvarchar] (255) NULL,
[IDMEPF] [nvarchar] (255) NULL,
[IDPODA] [decimal] (3, 0) NULL,
[IDCFI1] [nvarchar] (255) NULL,
[IDCFI2] [decimal] (15, 2) NULL,
[IDCFI3] [nvarchar] (255) NULL,
[IDCFI4] [nvarchar] (255) NULL,
[IDCFI5] [nvarchar] (255) NULL,
[IDHAFE] [nvarchar] (255) NULL,
[IDDESV] [nvarchar] (255) NULL,
[IDTIZO] [nvarchar] (255) NULL,
[IDFWSC] [nvarchar] (255) NULL,
[IDTXID] [decimal] (13, 0) NULL,
[IDRGDT] [decimal] (8, 0) NULL,
[IDRGTM] [decimal] (6, 0) NULL,
[IDLMDT] [decimal] (8, 0) NULL,
[IDCHNO] [decimal] (3, 0) NULL,
[IDCHID] [nvarchar] (255) NULL,
[IDLMTS] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_m3_CIDMAS_PK] on [psa].[ics_stg_m3_CIDMAS]'
GO
ALTER TABLE [psa].[ics_stg_m3_CIDMAS] ADD CONSTRAINT [psa_ics_stg_m3_CIDMAS_PK] PRIMARY KEY CLUSTERED  ([IDSUNO])
GO
PRINT N'Creating [psa].[ics_stg_m3_CMNDIV]'
GO
CREATE TABLE [psa].[ics_stg_m3_CMNDIV]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_CMNDIV_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_CMNDIV_IsIncomplete] DEFAULT ('N'),
[CCCONO] [decimal] (3, 0) NOT NULL,
[CCDIVI] [nvarchar] (255) NOT NULL,
[CCCONM] [nvarchar] (255) NULL,
[CCTX15] [nvarchar] (255) NULL,
[CCROW2] [nvarchar] (255) NULL,
[CCROW3] [nvarchar] (255) NULL,
[CCFACI] [nvarchar] (255) NULL,
[CCWHLO] [nvarchar] (255) NULL,
[CCDTFM] [nvarchar] (255) NULL,
[CCACGR] [nvarchar] (255) NULL,
[CCLOCD] [nvarchar] (255) NULL,
[CCTATM] [decimal] (1, 0) NULL,
[CCISTA] [decimal] (1, 0) NULL,
[CCRAEM] [decimal] (1, 0) NULL,
[CCNPT1] [decimal] (2, 0) NULL,
[CCNPT2] [decimal] (2, 0) NULL,
[CCNPT3] [decimal] (2, 0) NULL,
[CCNPT4] [decimal] (2, 0) NULL,
[CCNPT5] [decimal] (2, 0) NULL,
[CCDMCU] [decimal] (1, 0) NULL,
[CCPTMP] [decimal] (1, 0) NULL,
[CCPTOI] [decimal] (1, 0) NULL,
[CCPTFA] [decimal] (1, 0) NULL,
[CCPTPA] [decimal] (1, 0) NULL,
[CCPTEI] [decimal] (1, 0) NULL,
[CCVDME] [decimal] (1, 0) NULL,
[CCVRNO] [nvarchar] (255) NULL,
[CCCOA1] [nvarchar] (255) NULL,
[CCCOA2] [nvarchar] (255) NULL,
[CCCOA3] [nvarchar] (255) NULL,
[CCCOA4] [nvarchar] (255) NULL,
[CCPHNO] [nvarchar] (255) NULL,
[CCPHN2] [nvarchar] (255) NULL,
[CCTLNO] [nvarchar] (255) NULL,
[CCTFNO] [nvarchar] (255) NULL,
[CCOREF] [nvarchar] (255) NULL,
[CCCSCD] [nvarchar] (255) NULL,
[CCLL01] [nvarchar] (255) NULL,
[CCLL02] [nvarchar] (255) NULL,
[CCLL03] [nvarchar] (255) NULL,
[CCLL04] [nvarchar] (255) NULL,
[CCLL05] [nvarchar] (255) NULL,
[CCLL06] [nvarchar] (255) NULL,
[CCLL07] [nvarchar] (255) NULL,
[CCLL08] [nvarchar] (255) NULL,
[CCLL09] [nvarchar] (255) NULL,
[CCLL10] [nvarchar] (255) NULL,
[CCCDCD] [decimal] (1, 0) NULL,
[CCFIRM] [nvarchar] (255) NULL,
[CCPSND] [nvarchar] (255) NULL,
[CCVRNL] [nvarchar] (255) NULL,
[CCRROF] [nvarchar] (255) NULL,
[CCUNST] [nvarchar] (255) NULL,
[CCGEOC] [decimal] (9, 0) NULL,
[CCCONL] [decimal] (3, 0) NULL,
[CCMXAP] [decimal] (1, 0) NULL,
[CCMXAR] [decimal] (1, 0) NULL,
[CCMXAT] [decimal] (1, 0) NULL,
[CCMXBU] [decimal] (1, 0) NULL,
[CCMXCA] [decimal] (1, 0) NULL,
[CCMXCF] [decimal] (1, 0) NULL,
[CCMXCP] [decimal] (1, 0) NULL,
[CCMXCR] [decimal] (1, 0) NULL,
[CCMXDC] [decimal] (1, 0) NULL,
[CCMXDO] [decimal] (1, 0) NULL,
[CCMXDP] [decimal] (1, 0) NULL,
[CCMXDR] [decimal] (1, 0) NULL,
[CCMXDT] [decimal] (1, 0) NULL,
[CCMXDS] [decimal] (1, 0) NULL,
[CCMXEC] [decimal] (1, 0) NULL,
[CCMXED] [decimal] (1, 0) NULL,
[CCMXEM] [decimal] (1, 0) NULL,
[CCMXEP] [decimal] (1, 0) NULL,
[CCMXET] [decimal] (1, 0) NULL,
[CCMXEV] [decimal] (1, 0) NULL,
[CCMXFA] [decimal] (1, 0) NULL,
[CCMXFC] [decimal] (1, 0) NULL,
[CCMXGL] [decimal] (1, 0) NULL,
[CCMXGM] [decimal] (1, 0) NULL,
[CCMXIC] [decimal] (1, 0) NULL,
[CCMXIP] [decimal] (1, 0) NULL,
[CCMXJO] [decimal] (1, 0) NULL,
[CCMXJQ] [decimal] (1, 0) NULL,
[CCMXLI] [decimal] (1, 0) NULL,
[CCMXMA] [decimal] (1, 0) NULL,
[CCMXMC] [decimal] (1, 0) NULL,
[CCMXMD] [decimal] (1, 0) NULL,
[CCMXMF] [decimal] (1, 0) NULL,
[CCMXMI] [decimal] (1, 0) NULL,
[CCMXMM] [decimal] (1, 0) NULL,
[CCMXMN] [decimal] (1, 0) NULL,
[CCMXMO] [decimal] (1, 0) NULL,
[CCMXMP] [decimal] (1, 0) NULL,
[CCMXMQ] [decimal] (1, 0) NULL,
[CCMXMS] [decimal] (1, 0) NULL,
[CCMXOC] [decimal] (1, 0) NULL,
[CCMXOD] [decimal] (1, 0) NULL,
[CCMXOI] [decimal] (1, 0) NULL,
[CCMXOQ] [decimal] (1, 0) NULL,
[CCMXOS] [decimal] (1, 0) NULL,
[CCMXPA] [decimal] (1, 0) NULL,
[CCMXPC] [decimal] (1, 0) NULL,
[CCMXPD] [decimal] (1, 0) NULL,
[CCMXPM] [decimal] (1, 0) NULL,
[CCMXPO] [decimal] (1, 0) NULL,
[CCMXPP] [decimal] (1, 0) NULL,
[CCMXPQ] [decimal] (1, 0) NULL,
[CCMXPR] [decimal] (1, 0) NULL,
[CCMXPS] [decimal] (1, 0) NULL,
[CCMXQP] [decimal] (1, 0) NULL,
[CCMXRC] [decimal] (1, 0) NULL,
[CCMXRG] [decimal] (1, 0) NULL,
[CCMXRM] [decimal] (1, 0) NULL,
[CCMXRP] [decimal] (1, 0) NULL,
[CCMXRR] [decimal] (1, 0) NULL,
[CCMXRS] [decimal] (1, 0) NULL,
[CCMXSA] [decimal] (1, 0) NULL,
[CCMXSB] [decimal] (1, 0) NULL,
[CCMXSE] [decimal] (1, 0) NULL,
[CCMXSO] [decimal] (1, 0) NULL,
[CCMXSP] [decimal] (1, 0) NULL,
[CCMXTA] [decimal] (1, 0) NULL,
[CCMXTE] [decimal] (1, 0) NULL,
[CCMXTM] [decimal] (1, 0) NULL,
[CCMXTP] [decimal] (1, 0) NULL,
[CCMXWO] [decimal] (1, 0) NULL,
[CCMXWP] [decimal] (1, 0) NULL,
[CCMXWT] [decimal] (1, 0) NULL,
[CCMXST] [decimal] (1, 0) NULL,
[CCMXLT] [decimal] (1, 0) NULL,
[CCMXV1] [nvarchar] (255) NULL,
[CCMXV2] [nvarchar] (255) NULL,
[CCLLID] [nvarchar] (255) NULL,
[CCTIZO] [nvarchar] (255) NULL,
[CCECAR] [nvarchar] (255) NULL,
[CCTOWN] [nvarchar] (255) NULL,
[CCPONO] [nvarchar] (255) NULL,
[CCTXID] [decimal] (13, 0) NULL,
[CCRGDT] [decimal] (8, 0) NULL,
[CCRGTM] [decimal] (6, 0) NULL,
[CCLMDT] [decimal] (8, 0) NULL,
[CCCHNO] [decimal] (3, 0) NULL,
[CCCHID] [nvarchar] (255) NULL,
[CCDCFM] [nvarchar] (255) NULL,
[CCHCMA] [decimal] (1, 0) NULL,
[CCSYRE] [decimal] (1, 0) NULL,
[CCCCD1] [nvarchar] (255) NULL,
[CCCCD2] [decimal] (15, 2) NULL,
[CCCCD3] [nvarchar] (255) NULL,
[CCCCD4] [nvarchar] (255) NULL,
[CCCCD5] [nvarchar] (255) NULL,
[CCCCD6] [nvarchar] (255) NULL,
[CCCCD7] [decimal] (15, 2) NULL,
[CCCCD8] [nvarchar] (255) NULL,
[CCCCD9] [nvarchar] (255) NULL,
[CCCCD0] [nvarchar] (255) NULL,
[CCMXAH] [decimal] (1, 0) NULL,
[CCMXAM] [decimal] (1, 0) NULL,
[CCLMTS] [decimal] (18, 0) NULL,
[CCCUEX] [nvarchar] (255) NULL,
[CCFRCO] [nvarchar] (255) NULL,
[CCMXQM] [decimal] (1, 0) NULL,
[CCRMAN] [decimal] (1, 0) NULL,
[CCIAAT] [decimal] (1, 0) NULL,
[CCCSVN] [nvarchar] (255) NULL,
[CCMXGC] [decimal] (1, 0) NULL,
[CCCORG] [nvarchar] (255) NULL,
[CCCOR2] [nvarchar] (255) NULL,
[CCEALO] [decimal] (13, 0) NULL,
[CCSPLE] [nvarchar] (255) NULL,
[CCECOE] [decimal] (1, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_m3_CMNDIV_PK] on [psa].[ics_stg_m3_CMNDIV]'
GO
ALTER TABLE [psa].[ics_stg_m3_CMNDIV] ADD CONSTRAINT [psa_ics_stg_m3_CMNDIV_PK] PRIMARY KEY CLUSTERED  ([CCCONO], [CCDIVI])
GO
PRINT N'Creating [psa].[ics_stg_m3_MITWHL]'
GO
CREATE TABLE [psa].[ics_stg_m3_MITWHL]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_MITWHL_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_ics_stg_m3_MITWHL_IsIncomplete] DEFAULT ('N'),
[MWCONO] [decimal] (3, 0) NOT NULL,
[MWWHLO] [nvarchar] (255) NOT NULL,
[MWWHNM] [nvarchar] (255) NULL,
[MWDIVI] [nvarchar] (255) NULL,
[MWFACI] [nvarchar] (255) NULL,
[MWWHTY] [nvarchar] (255) NULL,
[MWWHSY] [nvarchar] (255) NULL,
[MWWHPL] [nvarchar] (255) NULL,
[MWOREF] [nvarchar] (255) NULL,
[MWPHNO] [nvarchar] (255) NULL,
[MWCOMA] [nvarchar] (255) NULL,
[MWCUNO] [nvarchar] (255) NULL,
[MWSUNO] [nvarchar] (255) NULL,
[MWSDES] [nvarchar] (255) NULL,
[MWSHNM] [nvarchar] (255) NULL,
[MWPLIS] [nvarchar] (255) NULL,
[MWCSCD] [nvarchar] (255) NULL,
[MWECAR] [nvarchar] (255) NULL,
[MWVRNO] [nvarchar] (255) NULL,
[MWLNCD] [nvarchar] (255) NULL,
[MWCPWH] [nvarchar] (255) NULL,
[MWAUAD] [decimal] (1, 0) NULL,
[MWALWH] [nvarchar] (255) NULL,
[MWALAC] [decimal] (1, 0) NULL,
[MWRESP] [nvarchar] (255) NULL,
[MWTWSL] [nvarchar] (255) NULL,
[MWGEOC] [decimal] (9, 0) NULL,
[MWTAXC] [nvarchar] (255) NULL,
[MWUNST] [nvarchar] (255) NULL,
[MWTXID] [decimal] (13, 0) NULL,
[MWDTID] [decimal] (13, 0) NULL,
[MWAASQ] [decimal] (1, 0) NULL,
[MWDMF0] [decimal] (3, 0) NULL,
[MWDMF1] [decimal] (3, 0) NULL,
[MWDMF2] [decimal] (3, 0) NULL,
[MWDMF3] [decimal] (3, 0) NULL,
[MWDMF4] [decimal] (3, 0) NULL,
[MWDMF5] [decimal] (3, 0) NULL,
[MWDMF6] [decimal] (3, 0) NULL,
[MWDMF7] [decimal] (3, 0) NULL,
[MWDMF8] [decimal] (3, 0) NULL,
[MWDMF9] [decimal] (3, 0) NULL,
[MWINUL] [decimal] (1, 0) NULL,
[MWEPUL] [decimal] (1, 0) NULL,
[MWEXDL] [decimal] (1, 0) NULL,
[MWPIDL] [decimal] (1, 0) NULL,
[MWALWQ] [nvarchar] (255) NULL,
[MWITDL] [decimal] (1, 0) NULL,
[MWCDYN] [decimal] (1, 0) NULL,
[MWPATF] [decimal] (3, 0) NULL,
[MWPAHF] [decimal] (4, 0) NULL,
[MWPMTF] [decimal] (3, 0) NULL,
[MWPMHF] [decimal] (4, 0) NULL,
[MWDDLO] [nvarchar] (255) NULL,
[MWCDPD] [decimal] (1, 0) NULL,
[MWCDPM] [decimal] (1, 0) NULL,
[MWCALV] [nvarchar] (255) NULL,
[MWACGR] [nvarchar] (255) NULL,
[MWNBID] [nvarchar] (255) NULL,
[MWSTOF] [decimal] (1, 0) NULL,
[MWASOT] [decimal] (1, 0) NULL,
[MWDAAS] [decimal] (2, 0) NULL,
[MWLEAM] [decimal] (3, 0) NULL,
[MWDMFC] [decimal] (1, 0) NULL,
[MWLSPM] [decimal] (1, 0) NULL,
[MWRSTN] [nvarchar] (255) NULL,
[MWRGDT] [decimal] (8, 0) NULL,
[MWRGTM] [decimal] (6, 0) NULL,
[MWLMDT] [decimal] (8, 0) NULL,
[MWCHNO] [decimal] (3, 0) NULL,
[MWCHID] [nvarchar] (255) NULL,
[MWLMTS] [decimal] (18, 0) NULL
)
GO
PRINT N'Creating primary key [psa_ics_stg_m3_MITWHL_PK] on [psa].[ics_stg_m3_MITWHL]'
GO
ALTER TABLE [psa].[ics_stg_m3_MITWHL] ADD CONSTRAINT [psa_ics_stg_m3_MITWHL_PK] PRIMARY KEY CLUSTERED  ([MWCONO], [MWWHLO])
GO
PRINT N'Creating primary key [psa_ics_stg_SAP_GBR_TCURR_PK] on [psa].[ics_stg_SAP_GBR_TCURR]'
GO
ALTER TABLE [psa].[ics_stg_SAP_GBR_TCURR] ADD CONSTRAINT [psa_ics_stg_SAP_GBR_TCURR_PK] PRIMARY KEY CLUSTERED  ([MANDT], [KURST], [FCURR], [TCURR], [GDATU])
GO
