




CREATE view [dbo].[V_CEX_FINANCE] as
SELECT fin.SUB_SBU
      ,FINANCE_DATE
      ,INSTALL_EMPLOY_SALES_MANAGERS
      ,INSTALL_EMPLOY_EXTERNAL_SALES
      ,INSTALL_EMPLOY_INTERNAL_SALES
      ,INSTALL_EMPLOY_MARKETING
      ,INSTALL_EXTERNAL_SALES
      ,INSTALL_EXTERNAL_SALES_LTM
      ,INSTALL_EXTERNAL_CM_II
      ,INSTALL_EXTERNAL_CM_II_LTM
      ,INSTALL_SALES_COSTS
      ,INSTALL_SALES_COSTS_LTM
      ,INSTALL_ACTIVE_CUSTOMERS
      ,INSTALL_VISIT_COUNT
      ,INSTALL_VISIT_COUNT_LTM

      ,DEALER_EMPLOY_SALES_MANAGERS
      ,DEALER_EMPLOY_EXTERNAL_SALES
      ,DEALER_EMPLOY_INTERNAL_SALES
      ,DEALER_EMPLOY_MARKETING
      ,DEALER_EXTERNAL_SALES
      ,DEALER_EXTERNAL_SALES_LTM
      ,DEALER_EXTERNAL_CM_II
      ,DEALER_EXTERNAL_CM_II_LTM
      ,DEALER_SALES_COSTS
      ,DEALER_SALES_COSTS_LTM
      ,DEALER_ACTIVE_CUSTOMERS
      ,DEALER_VISIT_COUNT
      ,DEALER_VISIT_COUNT_LTM
      ,DEALER_INST_VISIT_COUNT
      ,DEALER_INST_VISIT_COUNT_LTM

      ,SPECIFIER_EMPLOY_SALES_MANAGERS
      ,SPECIFIER_EMPLOY_EXTERNAL_SALES
      ,SPECIFIER_EMPLOY_INTERNAL_SALES
      ,SPECIFIER_EMPLOY_MARKETING
      ,SPECIFIER_VISIT_COUNT
      ,SPECIFIER_VISIT_COUNT_LTM

      ,PIPELINE_VALUE
      ,PIPELINE_WEIGHTED_VALUE
      ,PIPELINE_ACTIVE_PROJECTS
      ,PIPELINE_NEW_PROJECTS
      ,PIPELINE_NEW_PROJECTS_LTM
      ,PIPELINE_WON_PROJECTS
      ,PIPELINE_WON_PROJECTS_LTM
      ,PIPELINE_WON_VALUE
      ,PIPELINE_WON_VALUE_LTM
      ,PIPELINE_LOST_PROJECTS
      ,PIPELINE_LOST_PROJECTS_LTM
      ,PIPELINE_WORKED_ON_PROJECTS
      ,PIPELINE_WORKED_ON_PROJECTS_LTM
      ,PIPELINE_POOLCHANGE
      ,PIPELINE_POOLCHANGE_LTM
	        
	  ,cr.CURRENCY_RATE   as LocalCurrencyRate
	  ,eurr.CURRENCY_RATE as EurCurrencyRate
	  ,sb.CURRENCY
      ,fin.UPDATE_DATE
      ,fin.UPDATE_BY
FROM CEX_FINANCE as fin
       join
	     MD_SUB_SBU as bu on (bu.SUB_SBU = fin.SUB_SBU)
	   join
	     MD_SBU as sb on (sb.SBU = bu.SBU)
	   join
         MD_CURRENCY_RATE as cr on (cr.CURRENCY = sb.CURRENCY and
		                            cr.CURRENCY_RATE_TYPE = 2)
       join
         MD_CURRENCY_RATE as eurr on (eurr.CURRENCY = 'EUR' and
		                              eurr.CURRENCY_RATE_TYPE = 2)
where 
      cr.DATE_ACTIVE = (select TOP 1 DATE_ACTIVE
                        from MD_CURRENCY_RATE
                        where CURRENCY     = sb.CURRENCY and
                              DATE_ACTIVE <= fin.FINANCE_DATE and
							  CURRENCY_RATE_TYPE = 2
                        order by DATE_ACTIVE desc) and
      eurr.DATE_ACTIVE = (select TOP 1 DATE_ACTIVE
                          from MD_CURRENCY_RATE
                          where CURRENCY     = 'EUR' and
                                DATE_ACTIVE <= fin.FINANCE_DATE and
								CURRENCY_RATE_TYPE = 2
                          order by DATE_ACTIVE desc)