create view [dbo].[V_FLEX_PARAMETER] as
select PARAMTYPE   as PARAMETER_TYPE,
       PARAMNAVN   as PARAMETER_NAME,
       TEKST       as PARAMETER_VALUE,
       BESKRIVELSE as PARAMETER_DESCRIPTION
from FLEXPARAMS
where PARAMTYPE = 'DWH'