CREATE view [dbo].[V_PU_SUPPLIER_BONUS]
as
select SUPPLIER_BONUS_ID, 
       SUPPLIER_CATEGORY_ID, BONUS_ID,
       START_DATE, END_DATE,
       BONUS_UNIT, BONUS_CURRENCY,
       LOCAL_GLOBAL, BONUS_PERIOD
from PU_SUPPLIER_BONUS