




CREATE view [dbo].[V_SA_PRICE_DEVELOPMENT] as
select [SYSTEM_ID]
      ,[ITEM_NO]
      ,[CUSTOMER_NO]
      ,[PRICE_YEAR]
      ,[PRICE_MONTH]
      ,[SBU]
      ,[ACTUAL1_GROUP_AMOUNT]
      ,[CALC1_GROUP_AMOUNT]
      ,[ACTUAL1_LOCAL_AMOUNT]
      ,[CALC1_LOCAL_AMOUNT]
      ,[ACTUAL2_GROUP_AMOUNT]
      ,[CALC2_GROUP_AMOUNT]
      ,[ACTUAL2_LOCAL_AMOUNT]
      ,[CALC2_LOCAL_AMOUNT]
      ,[INDEX1001_GROUP_AMOUNT]
      ,[INDEX1001_LOCAL_AMOUNT]
      ,[INDEX1002_GROUP_AMOUNT]
      ,[INDEX1002_LOCAL_AMOUNT]
      ,[QUANTITY]
FROM SA_ITEM_PRICE_DEVELOPMENT