IF OBJECT_ID('[tSQLt].[Private_SqlVersion]') IS NOT NULL
	DROP FUNCTION [tSQLt].[Private_SqlVersion];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [tSQLt].[Private_SqlVersion]()
RETURNS TABLE
AS
RETURN
  SELECT CAST(SERVERPROPERTY('ProductVersion')AS NVARCHAR(128)) ProductVersion;
GO
