IF OBJECT_ID('[tSQLt].[Private_GetCleanObjectName]') IS NOT NULL
	DROP FUNCTION [tSQLt].[Private_GetCleanObjectName];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [tSQLt].[Private_GetCleanObjectName](@ObjectName NVARCHAR(MAX))
RETURNS NVARCHAR(MAX)
AS
BEGIN
    RETURN (SELECT OBJECT_NAME(OBJECT_ID(@ObjectName)));
END;
GO
