CREATE TABLE [dbo].[AMM_BUDGET] (
    [AMM_GROUP_ID]    [dbo].[D_INT]      NOT NULL,
    [BUDGET_YEAR]     [dbo].[D_INT]      NOT NULL,
    [BUDGET_AMOUNT]   [dbo].[D_DEC12.2]  NULL,
    [BUDGET_CURRENCY] [dbo].[N_CURRENCY] NULL,
    [UPDATE_BY]       [dbo].[N_USER]     NULL,
    [UPDATE_DATE]     [dbo].[D_DATE]     NULL,
    CONSTRAINT [PK_AMM_BUDGET] PRIMARY KEY CLUSTERED ([AMM_GROUP_ID] ASC, [BUDGET_YEAR] ASC),
    CONSTRAINT [FK_AMM_BUDGET_AMM_GROUP] FOREIGN KEY ([AMM_GROUP_ID]) REFERENCES [dbo].[MD_AMM_GROUP] ([AMM_GROUP_ID]) ON DELETE CASCADE
);

