CREATE TABLE [dbo].[CEX_FINANCE] (
    [SUB_SBU]                         [dbo].[N_C50]     NOT NULL,
    [FINANCE_DATE]                    [dbo].[D_DATE]    NOT NULL,
    [INSTALL_EMPLOY_SALES_MANAGERS]   [dbo].[D_DEC7.2]  NULL,
    [INSTALL_EMPLOY_EXTERNAL_SALES]   [dbo].[D_DEC7.2]  NULL,
    [INSTALL_EMPLOY_INTERNAL_SALES]   [dbo].[D_DEC7.2]  NULL,
    [INSTALL_EMPLOY_MARKETING]        [dbo].[D_DEC7.2]  NULL,
    [INSTALL_EXTERNAL_SALES]          [dbo].[D_DEC15,4] NULL,
    [INSTALL_EXTERNAL_SALES_LTM]      [dbo].[D_DEC15,4] NULL,
    [INSTALL_EXTERNAL_CM_II]          [dbo].[D_DEC15,4] NULL,
    [INSTALL_EXTERNAL_CM_II_LTM]      [dbo].[D_DEC15,4] NULL,
    [INSTALL_SALES_COSTS]             [dbo].[D_DEC15,4] NULL,
    [INSTALL_SALES_COSTS_LTM]         [dbo].[D_DEC15,4] NULL,
    [INSTALL_ACTIVE_CUSTOMERS]        [dbo].[D_INT]     NULL,
    [INSTALL_VISIT_COUNT]             [dbo].[D_INT]     NULL,
    [INSTALL_VISIT_COUNT_LTM]         [dbo].[D_INT]     NULL,
    [DEALER_EMPLOY_SALES_MANAGERS]    [dbo].[D_DEC7.2]  NULL,
    [DEALER_EMPLOY_EXTERNAL_SALES]    [dbo].[D_DEC7.2]  NULL,
    [DEALER_EMPLOY_INTERNAL_SALES]    [dbo].[D_DEC7.2]  NULL,
    [DEALER_EMPLOY_MARKETING]         [dbo].[D_DEC7.2]  NULL,
    [DEALER_EXTERNAL_SALES]           [dbo].[D_DEC15,4] NULL,
    [DEALER_EXTERNAL_SALES_LTM]       [dbo].[D_DEC15,4] NULL,
    [DEALER_EXTERNAL_CM_II]           [dbo].[D_DEC15,4] NULL,
    [DEALER_EXTERNAL_CM_II_LTM]       [dbo].[D_DEC15,4] NULL,
    [DEALER_SALES_COSTS]              [dbo].[D_DEC15,4] NULL,
    [DEALER_SALES_COSTS_LTM]          [dbo].[D_DEC15,4] NULL,
    [DEALER_ACTIVE_CUSTOMERS]         [dbo].[D_INT]     NULL,
    [DEALER_VISIT_COUNT]              [dbo].[D_INT]     NULL,
    [DEALER_VISIT_COUNT_LTM]          [dbo].[D_INT]     NULL,
    [DEALER_INST_VISIT_COUNT]         [dbo].[D_INT]     NULL,
    [DEALER_INST_VISIT_COUNT_LTM]     [dbo].[D_INT]     NULL,
    [SPECIFIER_VISIT_COUNT]           [dbo].[D_INT]     NULL,
    [SPECIFIER_VISIT_COUNT_LTM]       [dbo].[D_INT]     NULL,
    [SPECIFIER_EMPLOY_SALES_MANAGERS] [dbo].[D_DEC7.2]  NULL,
    [SPECIFIER_EMPLOY_EXTERNAL_SALES] [dbo].[D_DEC7.2]  NULL,
    [SPECIFIER_EMPLOY_INTERNAL_SALES] [dbo].[D_DEC7.2]  NULL,
    [SPECIFIER_EMPLOY_MARKETING]      [dbo].[D_DEC7.2]  NULL,
    [PIPELINE_VALUE]                  [dbo].[D_DEC15,4] NULL,
    [PIPELINE_WEIGHTED_VALUE]         [dbo].[D_DEC15,4] NULL,
    [PIPELINE_ACTIVE_PROJECTS]        [dbo].[D_INT]     NULL,
    [PIPELINE_NEW_PROJECTS]           [dbo].[D_INT]     NULL,
    [PIPELINE_NEW_PROJECTS_LTM]       [dbo].[D_INT]     NULL,
    [PIPELINE_WON_PROJECTS]           [dbo].[D_INT]     NULL,
    [PIPELINE_WON_PROJECTS_LTM]       [dbo].[D_INT]     NULL,
    [PIPELINE_WON_VALUE]              [dbo].[D_DEC15,4] NOT NULL,
    [PIPELINE_WON_VALUE_LTM]          [dbo].[D_DEC15,4] NULL,
    [PIPELINE_LOST_PROJECTS]          [dbo].[D_INT]     NULL,
    [PIPELINE_LOST_PROJECTS_LTM]      [dbo].[D_INT]     NULL,
    [PIPELINE_WORKED_ON_PROJECTS]     [dbo].[D_INT]     NULL,
    [PIPELINE_WORKED_ON_PROJECTS_LTM] [dbo].[D_INT]     NULL,
    [PIPELINE_POOLCHANGE]             [dbo].[D_INT]     NULL,
    [PIPELINE_POOLCHANGE_LTM]         [dbo].[D_INT]     NULL,
    [EXCEL_FILENAME]                  [dbo].[N_MEMO]    NULL,
    [UPDATE_DATE]                     [dbo].[D_DATE]    NULL,
    [UPDATE_BY]                       [dbo].[N_USER]    NULL,
    CONSTRAINT [PK_CEX_FINANCE_1] PRIMARY KEY CLUSTERED ([SUB_SBU] ASC, [FINANCE_DATE] ASC),
    CONSTRAINT [FK_CEX_FINANCE_MD_SUB_SBU] FOREIGN KEY ([SUB_SBU]) REFERENCES [dbo].[MD_SUB_SBU] ([SUB_SBU])
);

