CREATE TABLE [dbo].[FLEXFORM] (
    [USERNAME]    [dbo].[N_USER] NOT NULL,
    [FORMNAME]    [dbo].[N_C100] NOT NULL,
    [OBJECTNAME]  [dbo].[N_C100] NOT NULL,
    [OBJECTVALUE] [dbo].[N_C100] NULL,
    CONSTRAINT [PK_FLEXFORM] PRIMARY KEY CLUSTERED ([USERNAME] ASC, [FORMNAME] ASC, [OBJECTNAME] ASC)
);

