CREATE TABLE [dbo].[FLEXUSERGROUPS] (
    [USERGROUP]   [dbo].[N_C100] NOT NULL,
    [DESCRIPTION] [dbo].[N_MEMO] NULL,
    [UPDATE_BY]   [dbo].[N_USER] NULL,
    [UPDATE_DATE] [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_FLEXUSERGROUPS] PRIMARY KEY CLUSTERED ([USERGROUP] ASC)
);

