CREATE TABLE [dbo].[FLEXPROGRAMS] (
    [PROGRAMNAME]     [dbo].[N_C100] NOT NULL,
    [TRANSACTIONCODE] [dbo].[N_C20]  NULL,
    [BESKRIVELSE]     [dbo].[N_MEMO] NULL,
    [CLASSNAME]       [dbo].[N_C100] NULL,
    [UPDATE_BY]       [dbo].[N_USER] NULL,
    [UPDATE_DATE]     [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_FLEXPROGRAMS] PRIMARY KEY CLUSTERED ([PROGRAMNAME] ASC)
);

