CREATE TABLE [dbo].[FLEXMENUS] (
    [MENUNAME]        [dbo].[N_C100] NOT NULL,
    [TRANSACTIONCODE] [dbo].[N_C100] NOT NULL,
    [DESCRIPTION]     [dbo].[N_MEMO] NULL,
    [HEADLINE]        [dbo].[N_C100] NULL,
    [UPDATE_BY]       [dbo].[N_USER] NULL,
    [UPDATE_DATE]     [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_FLEXMENUS] PRIMARY KEY CLUSTERED ([MENUNAME] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_FLEXMENUS]
    ON [dbo].[FLEXMENUS]([TRANSACTIONCODE] ASC);

