CREATE TABLE [dbo].[FLEXUSERS_SYSTEM] (
    [USERINITIALS] [dbo].[N_C100] NOT NULL,
    [SYSTEM_ID]    [dbo].[D_INT]  NOT NULL,
    [CREATE_BY]    [dbo].[D_USER] NULL,
    [CREATE_DATE]  [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_FLEXUSERS_SYSTEM] PRIMARY KEY CLUSTERED ([USERINITIALS] ASC, [SYSTEM_ID] ASC),
    CONSTRAINT [FK_FLEXUSERS_SYSTEM_FLEXUSERS] FOREIGN KEY ([USERINITIALS]) REFERENCES [dbo].[FLEXUSERS] ([USERINITIALS]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_FLEXUSERS_SYSTEM_MD_SYSTEMID] FOREIGN KEY ([SYSTEM_ID]) REFERENCES [dbo].[MD_SYSTEMID] ([SYSTEM_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FLEXUSERS_SYSTEM]
    ON [dbo].[FLEXUSERS_SYSTEM]([USERINITIALS] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FLEXUSERS_SYSTEM_1]
    ON [dbo].[FLEXUSERS_SYSTEM]([SYSTEM_ID] ASC);

