CREATE TABLE [dbo].[FLEXPROGRAMSECUR] (
    [PROGRAMNAME] [dbo].[N_C100] NOT NULL,
    [USERGROUP]   [dbo].[N_C100] NOT NULL,
    [UPDATE_BY]   [dbo].[N_USER] NULL,
    [UPDATE_DATE] [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_FLEXPROGRAMSECUR] PRIMARY KEY CLUSTERED ([PROGRAMNAME] ASC, [USERGROUP] ASC),
    CONSTRAINT [FK_FLEXPROGRAMSECUR_FLEXPROGRAMS] FOREIGN KEY ([PROGRAMNAME]) REFERENCES [dbo].[FLEXPROGRAMS] ([PROGRAMNAME]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_FLEXPROGRAMSECUR_FLEXUSERGROUPS] FOREIGN KEY ([USERGROUP]) REFERENCES [dbo].[FLEXUSERGROUPS] ([USERGROUP]) ON DELETE CASCADE ON UPDATE CASCADE
);

