CREATE TABLE [dbo].[FLEXPARAMS] (
    [PARAMTYPE]   [dbo].[N_C50]  NOT NULL,
    [PARAMNAVN]   [dbo].[N_C50]  NOT NULL,
    [TEKST]       [dbo].[N_MEMO] NULL,
    [BESKRIVELSE] [dbo].[N_MEMO] NULL,
    [ACCESS_DATE] [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_FLEXPARAMS] PRIMARY KEY CLUSTERED ([PARAMTYPE] ASC, [PARAMNAVN] ASC)
);

