CREATE TABLE [dbo].[FLEXUSERSINGROUP] (
    [USERINITIALS] [dbo].[N_USER] NOT NULL,
    [USERGROUP]    [dbo].[N_C100] NOT NULL,
    CONSTRAINT [PK_FLEXUSERSINGROUP] PRIMARY KEY CLUSTERED ([USERINITIALS] ASC, [USERGROUP] ASC),
    CONSTRAINT [FK_FLEXUSERSINGROUP_FLEXUSERGROUPS] FOREIGN KEY ([USERGROUP]) REFERENCES [dbo].[FLEXUSERGROUPS] ([USERGROUP]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_FLEXUSERSINGROUP_FLEXUSERS] FOREIGN KEY ([USERINITIALS]) REFERENCES [dbo].[FLEXUSERS] ([USERINITIALS]) ON DELETE CASCADE ON UPDATE CASCADE
);

