CREATE TABLE [dbo].[FLEXUSERS_SBU] (
    [USERINITIALS] [dbo].[N_USER] NOT NULL,
    [SBU]          [dbo].[N_SBU]  NOT NULL,
    [CREATE_BY]    [dbo].[N_USER] NULL,
    [CREATE_DATE]  [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_FLEXUSERS_SBU] PRIMARY KEY CLUSTERED ([USERINITIALS] ASC, [SBU] ASC),
    CONSTRAINT [FK_FLEXUSERS_SBU_FLEXUSERS] FOREIGN KEY ([USERINITIALS]) REFERENCES [dbo].[FLEXUSERS] ([USERINITIALS]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_FLEXUSERS_SBU_MD_SBU] FOREIGN KEY ([SBU]) REFERENCES [dbo].[MD_SBU] ([SBU]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FLEXUSERS_SBU]
    ON [dbo].[FLEXUSERS_SBU]([USERINITIALS] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FLEXUSERS_SBU_1]
    ON [dbo].[FLEXUSERS_SBU]([SBU] ASC);

