CREATE TABLE [dbo].[KPI_SCM_PLANT] (
    [PLANT_ID]            [dbo].[D_INT]       NOT NULL,
    [KPI_YEAR]            [dbo].[D_INT]       NOT NULL,
    [KPI_MONTH]           [dbo].[D_INT]       NOT NULL,
    [KPI_YYMM]            [dbo].[D_INT]       NOT NULL,
    [PLANT_ACTIVE]        [dbo].[N_BOOLEAN_Y] NULL,
    [SLF_ORDER_ON_TIME]   [dbo].[D_INT]       NULL,
    [SLF_ORDER_RAISED]    [dbo].[D_INT]       NULL,
    [CC_COUNT]            [dbo].[D_INT]       NULL,
    [SA_SICK_HOURS]       [dbo].[D_DEC12.2]   NULL,
    [SA_HOURS]            [dbo].[D_DEC12.2]   NULL,
    [LTA_PROD_WORK_HOURS] [dbo].[D_DEC12.2]   NULL,
    [LTA_CONT_WORK_HOURS] [dbo].[D_DEC12.2]   NULL,
    [LTA_PROD_COUNT]      [dbo].[D_INT]       NULL,
    [LTA_CONT_COUNT]      [dbo].[D_INT]       NULL,
    [NLTA_PROD_COUNT]     [dbo].[D_INT]       NULL,
    [NLTA_CONT_COUNT]     [dbo].[D_INT]       NULL,
    [NEAR_PROD_COUNT]     [dbo].[D_INT]       NULL,
    [NEAR_CONT_COUNT]     [dbo].[D_INT]       NULL,
    [FAA_PROD_COUNT]      [dbo].[D_INT]       NULL,
    [FAA_CONT_COUNT]      [dbo].[D_INT]       NULL,
    [EC_GAS_KWH]          [dbo].[D_INT]       NULL,
    [EC_ELEC_KWH]         [dbo].[D_INT]       NULL,
    [EC_OTHER_KWH]        [dbo].[D_INT]       NULL,
    [CREATE_BY]           [dbo].[N_USER]      NULL,
    [CREATE_DATE]         [dbo].[D_DATE]      NULL,
    [UPDATE_BY]           [dbo].[N_USER]      NULL,
    [UPDATE_DATE]         [dbo].[D_DATE]      NULL,
    CONSTRAINT [PK_KPI_SCM_PLANT_1] PRIMARY KEY CLUSTERED ([PLANT_ID] ASC, [KPI_YEAR] ASC, [KPI_MONTH] ASC),
    CONSTRAINT [FK_KPI_SCM_PLANT_MD_PLANT] FOREIGN KEY ([PLANT_ID]) REFERENCES [dbo].[MD_PLANT] ([PLANT_ID]) ON DELETE CASCADE
);

