CREATE TABLE [dbo].[KPI_HR] (
    [SBU]                             [dbo].[N_SBU]    NOT NULL,
    [REPORT_YEAR]                     [dbo].[D_INT]    NOT NULL,
    [REPORTED_DATE]                   [dbo].[D_DATE]   NOT NULL,
    [W_LEFT]                          [dbo].[D_INT]    NULL,
    [W_EMPLOYED]                      [dbo].[D_INT]    NULL,
    [W_SICKNESS_DAYS]                 [dbo].[D_INT]    NULL,
    [W_WORK_DAYS]                     [dbo].[D_INT]    NULL,
    [W_YEARS_IN_POSITION]             [dbo].[D_INT]    NULL,
    [W_APPRAISALS]                    [dbo].[D_INT]    NULL,
    [W_INTERNAL_PROMOTIONS]           [dbo].[D_INT]    NULL,
    [W_TRAINING_HOURS]                [dbo].[D_INT]    NULL,
    [W_NO_EMPLOYEES_RECEIVED_TRANING] [dbo].[D_INT]    NULL,
    [W_AVERAGE_AGE]                   [dbo].[D_INT]    NULL,
    [W_AVERAGE_YEARS_OF_SERVICE]      [dbo].[D_INT]    NULL,
    [W_FEMALE_PCT]                    [dbo].[D_INT]    NULL,
    [W_SKILLS_HIGH]                   [dbo].[D_INT]    NULL,
    [W_SKILLS_MEDIUM]                 [dbo].[D_INT]    NULL,
    [W_SKILLS_LOW]                    [dbo].[D_INT]    NULL,
    [W_ACCIDENT_NO]                   [dbo].[D_INT]    NULL,
    [W_ACCIDENT_RATIO]                [dbo].[D_DEC7.2] NULL,
    [B_LEFT]                          [dbo].[D_INT]    NULL,
    [B_EMPLOYED]                      [dbo].[D_INT]    NULL,
    [B_SICKNESS_HOURS]                [dbo].[D_INT]    NULL,
    [B_WORK_HOURS]                    [dbo].[D_INT]    NULL,
    [B_YEARS_IN_POSITION]             [dbo].[D_INT]    NULL,
    [B_APPRAISALS]                    [dbo].[D_INT]    NULL,
    [B_INTERNAL_PROMOTIONS]           [dbo].[D_INT]    NULL,
    [B_TRAINING_HOURS]                [dbo].[D_INT]    NULL,
    [B_NO_EMPLOYEES_RECEIVED_TRANING] [dbo].[D_INT]    NULL,
    [B_AVERAGE_AGE]                   [dbo].[D_INT]    NULL,
    [B_AVERAGE_YEARS_OF_SERVICE]      [dbo].[D_INT]    NULL,
    [B_FEMALE_PCT]                    [dbo].[D_INT]    NULL,
    [B_SKILLS_HIGH]                   [dbo].[D_INT]    NULL,
    [B_SKILLS_MEDIUM]                 [dbo].[D_INT]    NULL,
    [B_SKILLS_LOW]                    [dbo].[D_INT]    NULL,
    [B_ACCIDENT_NO]                   [dbo].[D_INT]    NULL,
    [B_ACCIDENT_RATIO]                [dbo].[D_DEC7.2] NULL,
    [CREATE_BY]                       [dbo].[N_USER]   NULL,
    [CREATE_DATE]                     [dbo].[D_DATE]   NULL,
    [UPDATE_BY]                       [dbo].[N_USER]   NULL,
    [UPDATE_DATE]                     [dbo].[D_DATE]   NULL,
    CONSTRAINT [PK_KPI_HR] PRIMARY KEY CLUSTERED ([SBU] ASC, [REPORT_YEAR] ASC, [REPORTED_DATE] ASC),
    CONSTRAINT [FK_KPI_HR_MD_SBU] FOREIGN KEY ([SBU]) REFERENCES [dbo].[MD_SBU] ([SBU]) ON UPDATE CASCADE
);

