CREATE TABLE [dbo].[KPI_LOCAL_PRODLINE] (
    [SYSTEM_ID]      [dbo].[D_INT] NOT NULL,
    [LOCAL_PRODLINE] [dbo].[N_C50] NOT NULL,
    [LOCAL_PLANT]    [dbo].[N_C50] NOT NULL,
    CONSTRAINT [PK_KPI_LOCAL_PRODLINE] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC, [LOCAL_PRODLINE] ASC, [LOCAL_PLANT] ASC)
);

