CREATE TABLE [dbo].[KPI_RMI_BUDGET] (
    [SBU]                 [dbo].[N_SBU]      NOT NULL,
    [PRODUCT_GROUP]       [dbo].[N_C100]     NOT NULL,
    [BUDGET_YEAR]         [dbo].[D_INT]      NOT NULL,
    [QUANTITY_BUDGET]     [dbo].[D_INT]      NULL,
    [UOM]                 [dbo].[N_C20]      NULL,
    [AMOUNT_BUDGET]       [dbo].[D_DEC12.2]  NULL,
    [FREIGHT_BUDGET]      DECIMAL (11, 6)    NULL,
    [CURRENCY]            [dbo].[N_CURRENCY] NULL,
    [CREATE_BY]           [dbo].[N_USER]     NULL,
    [CREATE_DATE]         [dbo].[D_DATE]     NULL,
    [UPDATE_BY]           [dbo].[N_USER]     NULL,
    [UPDATE_DATE]         [dbo].[D_DATE]     NULL,
    [FREIGHT_UPDATE_DATE] [dbo].[D_DATE]     NULL,
    [FREIGHT_UPDATE_BY]   [dbo].[N_USER]     NULL,
    CONSTRAINT [PK_KPI_RMI_BUDGET] PRIMARY KEY CLUSTERED ([SBU] ASC, [PRODUCT_GROUP] ASC, [BUDGET_YEAR] ASC),
    CONSTRAINT [FK_KPI_RMI_BUDGET_MD_CURRENCY] FOREIGN KEY ([CURRENCY]) REFERENCES [dbo].[MD_CURRENCY] ([CURRENCY]),
    CONSTRAINT [FK_KPI_RMI_BUDGET_MD_PRODUCTGROUPS] FOREIGN KEY ([PRODUCT_GROUP]) REFERENCES [dbo].[MD_PRODUCTGROUPS] ([PRODUCT_GROUP]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_KPI_RMI_BUDGET_MD_SBU] FOREIGN KEY ([SBU]) REFERENCES [dbo].[MD_SBU] ([SBU]) ON UPDATE CASCADE
);

