CREATE TABLE [dbo].[KPI_REPORT_TYPE] (
    [REPORT_TYPE_ID] [dbo].[D_INT]  NOT NULL,
    [REPORT_NAME]    [dbo].[N_C100] NULL,
    CONSTRAINT [PK_KPI_REPORT_TYPE] PRIMARY KEY CLUSTERED ([REPORT_TYPE_ID] ASC)
);

