CREATE TABLE [dbo].[KPI_LOCAL_REASON] (
    [SYSTEM_ID]         [dbo].[D_INT]  NOT NULL,
    [REASON_TYPE_ID]    [dbo].[D_INT]  NOT NULL,
    [LOCAL_PLANT]       [dbo].[N_C50]  NOT NULL,
    [LOCAL_PRODLINE]    [dbo].[N_C50]  NOT NULL,
    [LOCAL_REASON_CODE] [dbo].[N_C50]  NOT NULL,
    [LOCAL_REASON_NAME] [dbo].[N_C100] NOT NULL,
    [CREATE_DATE]       [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_KPI_LOCAL_REASON] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC, [REASON_TYPE_ID] ASC, [LOCAL_PLANT] ASC, [LOCAL_PRODLINE] ASC, [LOCAL_REASON_CODE] ASC, [LOCAL_REASON_NAME] ASC)
);

