CREATE TABLE [dbo].[MD_BONUSTYPE] (
    [BONUS_ID]    [dbo].[D_INT]  NOT NULL,
    [BONUS_NAME]  [dbo].[N_C50]  NULL,
    [BONUS_DESC]  [dbo].[N_MEMO] NULL,
    [UPDATE_BY]   [dbo].[N_USER] NULL,
    [UPDATE_DATE] [dbo].[D_DATE] NULL,
    [CREATE_BY]   [dbo].[N_USER] NULL,
    [CREATE_DATE] [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_MD_BONUSTYPE] PRIMARY KEY CLUSTERED ([BONUS_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MD_BONUSTYPE]
    ON [dbo].[MD_BONUSTYPE]([BONUS_NAME] ASC);

