CREATE TABLE [dbo].[MD_CURRENCY_RATE_TYPE] (
    [RATE_TYPE] INT            NOT NULL,
    [RATE_NAME] [dbo].[N_C100] NULL,
    CONSTRAINT [PK_MD_CURRENCY_RATE_TYPE] PRIMARY KEY CLUSTERED ([RATE_TYPE] ASC)
);

