CREATE TABLE [dbo].[MD_COMPANY_CATEGORY] (
    [COMPANY_CATEGORY_ID] [dbo].[D_INT]  NOT NULL,
    [CATEGORY_NAME]       [dbo].[N_C100] NULL,
    [PARENT_ID]           [dbo].[D_INT]  NULL,
    [CREATE_BY]           [dbo].[N_USER] NULL,
    [CREATE_DATE]         [dbo].[D_DATE] NULL,
    [UPDATE_BY]           [dbo].[N_USER] NULL,
    [UPDATE_DATE]         [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_MD_COMPANY_CATEGORY] PRIMARY KEY CLUSTERED ([COMPANY_CATEGORY_ID] ASC),
    CONSTRAINT [FK_MD_COMPANY_CATEGORY_MD_COMPANY_CATEGORY] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[MD_COMPANY_CATEGORY] ([COMPANY_CATEGORY_ID])
);

