CREATE TABLE [dbo].[MD_CURRENCY_RATE] (
    [CURRENCY]           [dbo].[N_CURRENCY] NOT NULL,
    [DATE_ACTIVE]        [dbo].[D_DATE]     NOT NULL,
    [CURRENCY_RATE_TYPE] [dbo].[D_INT]      NOT NULL,
    [CURRENCY_RATE]      [dbo].[D_DEC11.4]  NULL,
    [CREATE_BY]          [dbo].[N_USER]     NULL,
    [CREATE_DATE]        [dbo].[D_DATE]     NULL,
    [UPDATE_BY]          [dbo].[N_USER]     NULL,
    [UPDATE_DATE]        [dbo].[D_DATE]     NULL,
    CONSTRAINT [PK_CURRENCY_RATE] PRIMARY KEY CLUSTERED ([CURRENCY] ASC, [DATE_ACTIVE] ASC, [CURRENCY_RATE_TYPE] ASC),
    CONSTRAINT [FK_MD_CURRENCY_RATE_MD_CURRENCY] FOREIGN KEY ([CURRENCY]) REFERENCES [dbo].[MD_CURRENCY] ([CURRENCY]),
    CONSTRAINT [FK_MD_CURRENCY_RATE_MD_CURRENCY_RATE_TYPE] FOREIGN KEY ([CURRENCY_RATE_TYPE]) REFERENCES [dbo].[MD_CURRENCY_RATE_TYPE] ([RATE_TYPE])
);

