CREATE TABLE [dbo].[MD_ICIS_PRICE] (
    [ICIS_PRODUCT]  [dbo].[N_C100]    NOT NULL,
    [ICIS_DATE]     [dbo].[D_DATE]    NOT NULL,
    [PRICE]         [dbo].[D_DEC11.4] NULL,
    [SHIPPING_COST] [dbo].[D_DEC11.4] NULL,
    [TERMINAL_COST] [dbo].[D_DEC11.4] NULL,
    [CREATE_BY]     [dbo].[N_USER]    NULL,
    [CREATE_DATE]   [dbo].[D_DATE]    NULL,
    [UPDATE_BY]     [dbo].[N_USER]    NULL,
    [UPDATE_DATE]   [dbo].[D_DATE]    NULL,
    CONSTRAINT [PK_MD_ICIS_PRICE] PRIMARY KEY CLUSTERED ([ICIS_PRODUCT] ASC, [ICIS_DATE] ASC),
    CONSTRAINT [FK_MD_ICIS_PRICE_MD_ICIS_PRODUCT] FOREIGN KEY ([ICIS_PRODUCT]) REFERENCES [dbo].[MD_ICIS_PRODUCT] ([ICIS_PRODUCT])
);

