CREATE TABLE [dbo].[MD_LINK_UNSPSC] (
    [UNSPSC_ID]     [dbo].[N_C20]  NOT NULL,
    [SYSTEM_ID]     [dbo].[D_INT]  NOT NULL,
    [MATERIAL_CODE] [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]     [dbo].[N_USER] NULL,
    [CREATE_DATE]   [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_MD_LINK_UNSPSC] PRIMARY KEY CLUSTERED ([UNSPSC_ID] ASC, [SYSTEM_ID] ASC, [MATERIAL_CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_MD_LINK_UNSPSC]
    ON [dbo].[MD_LINK_UNSPSC]([UNSPSC_ID] ASC);

