CREATE TABLE [dbo].[MD_LINK_COMPANY] (
    [COMPANY_CATEGORY_ID] [dbo].[D_INT]  NOT NULL,
    [SITE_ID]             [dbo].[D_INT]  NOT NULL,
    [CREATE_BY]           [dbo].[N_USER] NULL,
    [CREATE_DATE]         [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_MD_LINK_COMPANY] PRIMARY KEY CLUSTERED ([COMPANY_CATEGORY_ID] ASC, [SITE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_MD_LINK_COMPANY]
    ON [dbo].[MD_LINK_COMPANY]([COMPANY_CATEGORY_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MD_LINK_COMPANY_1]
    ON [dbo].[MD_LINK_COMPANY]([SITE_ID] ASC);

