CREATE TABLE [dbo].[MD_MATCH_FIELD] (
    [MATCH_TYPE]        [dbo].[N_C1]   NOT NULL,
    [MATCH_FIELD]       [dbo].[N_C50]  NOT NULL,
    [MATCH_DESCRIPTION] [dbo].[N_C100] NULL,
    [MATCH_SORT]        [dbo].[D_INT]  NULL,
    CONSTRAINT [PK_MD_MATCH_FIELD] PRIMARY KEY CLUSTERED ([MATCH_TYPE] ASC, [MATCH_FIELD] ASC)
);

