CREATE TABLE [dbo].[MD_MATCH_LINE] (
    [MATCH_ID]      [dbo].[D_INT]       NOT NULL,
    [MATCH_LINE_NO] [dbo].[D_INT]       NULL,
    [MATCH_FIELD]   [dbo].[N_C50]       NULL,
    [MATCH_KEYWORD] [dbo].[N_C100]      NULL,
    [MATCH_EVAL]    [dbo].[D_INT]       NULL,
    [MATCH_AND_OR]  [dbo].[D_INT]       NULL,
    [MATCH_LEVEL]   [dbo].[D_INT]       NULL,
    [MATCH_REGEX]   [dbo].[N_BOOLEAN_N] NULL,
    CONSTRAINT [FK_MD_MATCH_LINE_MD_MATCH_EVALTYPE] FOREIGN KEY ([MATCH_EVAL]) REFERENCES [dbo].[MD_MATCH_EVALTYPE] ([MATCH_EVAL_ID]),
    CONSTRAINT [FK_MD_MATCH_LINE_MD_MATCH_RULES] FOREIGN KEY ([MATCH_ID]) REFERENCES [dbo].[MD_MATCH_RULES] ([MATCH_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MD_MATCH_LINE]
    ON [dbo].[MD_MATCH_LINE]([MATCH_ID] ASC, [MATCH_LINE_NO] ASC);

