CREATE TABLE [dbo].[MD_MATCH_EVALTYPE] (
    [MATCH_EVAL_ID]   [dbo].[D_INT]  NOT NULL,
    [MATCH_EVAL_NAME] [dbo].[N_C100] NULL,
    CONSTRAINT [PK_MD_MATCH_EVALTYPE] PRIMARY KEY CLUSTERED ([MATCH_EVAL_ID] ASC)
);

