CREATE TABLE [dbo].[MD_SBU] (
    [SBU]                  [dbo].[N_SBU]       NOT NULL,
    [REGION_ID]            [dbo].[D_INT]       NULL,
    [SBU_NAME]             [dbo].[N_C100]      NULL,
    [SALESCENTER_SBU]      [dbo].[N_SBU]       NULL,
    [SALESCENTER_SBU_NAME] [dbo].[N_C100]      NULL,
    [CURRENCY]             [dbo].[N_CURRENCY]  NULL,
    [SCM_KPI]              [dbo].[N_BOOLEAN_N] NULL,
    [HR_KPI]               [dbo].[N_BOOLEAN_N] NULL,
    [RMI_KPI]              [dbo].[N_BOOLEAN_N] NULL,
    [IPROBIS_INDIRECT]     [dbo].[N_BOOLEAN_N] NULL,
    [IPROBIS_PURCHASE]     [dbo].[N_BOOLEAN_N] NULL,
    [IPROBIS_CONTRACTING]  [dbo].[N_BOOLEAN_N] NULL,
    [SABIS]                [dbo].[N_BOOLEAN_N] NULL,
    [CRM_SYSTEM]           [dbo].[N_BOOLEAN_N] NULL,
    [CRM_PROJECT]          [dbo].[N_BOOLEAN_N] NULL,
    [CRM_VISIT]            [dbo].[N_BOOLEAN_N] NULL,
    [CRM_RESPONSIBLE]      [dbo].[N_C100]      NULL,
    [ICIS_PRODUCT_1]       [dbo].[N_C100]      NULL,
    [ICIS_PRODUCT_2]       [dbo].[N_C100]      NULL,
    [ICIS_PCT_1]           [dbo].[D_DEC7.2]    NULL,
    [ICIS_PCT_2]           [dbo].[D_DEC7.2]    NULL,
    [IPROBIS_AMM]          [dbo].[N_BOOLEAN_N] NULL,
    [IPROBIS_AMM_PVC]      [dbo].[N_BOOLEAN_N] NULL,
    [IPROBIS_AMM_NAME]     [dbo].[N_SBU]       NULL,
    [IPROBIS_AMM_PCT]      [dbo].[D_DEC7.2]    NULL,
    [CREATE_BY]            [dbo].[N_USER]      NULL,
    [CREATE_DATE]          [dbo].[D_DATE]      NULL,
    [UPDATE_BY]            [dbo].[N_USER]      NULL,
    [UPDATE_DATE]          [dbo].[D_DATE]      NULL,
    CONSTRAINT [PK_MD_SBU] PRIMARY KEY CLUSTERED ([SBU] ASC)
);

