CREATE TABLE [dbo].[MD_SYSTEMID] (
    [SYSTEM_ID]             [dbo].[D_INT]       NOT NULL,
    [NAME]                  [dbo].[N_C100]      NULL,
    [SHORT_NAME]            [dbo].[N_C20]       NULL,
    [TRANSLATE_TYPE]        [dbo].[D_INT]       NULL,
    [IT_RESPONSIBLE]        [dbo].[N_C100]      NULL,
    [IT_MAIL]               [dbo].[N_MEMO]      NULL,
    [PURCHASE_ACTIVE]       [dbo].[N_BOOLEAN_N] NULL,
    [PURCHASE_RESPONSIBLE]  [dbo].[N_C100]      NULL,
    [PURCHASE_MAIL]         [dbo].[N_MEMO]      NULL,
    [DEFAULT_DIRECT_SITE]   [dbo].[D_INT]       NULL,
    [INDIRECT_ACTIVE]       [dbo].[N_BOOLEAN_N] NULL,
    [INDIRECT_RESPONSIBLE]  [dbo].[N_USER]      NULL,
    [INDIRECT_MAIL]         [dbo].[N_MEMO]      NULL,
    [CONTRACT_ACTIVE]       [dbo].[N_BOOLEAN_N] NULL,
    [CONTRACT_RESPONSIBLE]  [dbo].[N_USER]      NULL,
    [CONTRACT_MAIL]         [dbo].[N_MEMO]      NULL,
    [PURCHASEFILE_DATE]     [dbo].[D_DATE]      NULL,
    [SUPPLIERFILE_DATE]     [dbo].[D_DATE]      NULL,
    [INDIRECTFILE_DATE]     [dbo].[D_DATE]      NULL,
    [CONTRACTFILE_DATE]     [dbo].[D_DATE]      NULL,
    [SALES_ACTIVE]          [dbo].[N_BOOLEAN_N] NULL,
    [FINANCE_ACTIVE]        [dbo].[N_BOOLEAN_N] NULL,
    [DEFAULT_SALES_SITE]    [dbo].[D_INT]       NULL,
    [SALES_RESPONSIBLE]     [dbo].[N_USER]      NULL,
    [SALES_MAIL]            [dbo].[N_MEMO]      NULL,
    [SALESINVOICEFILE_DATE] [dbo].[D_DATE]      NULL,
    [ITEMFILE_DATE]         [dbo].[D_DATE]      NULL,
    [CUSTOMERFILE_DATE]     [dbo].[D_DATE]      NULL,
    [ORDERBACKLOGFILE_DATE] [dbo].[D_DATE]      NULL,
    [SNIFILE_DATE]          [dbo].[D_DATE]      NULL,
    [SHIFTPRODFILE_DATE]    [dbo].[D_DATE]      NULL,
    [REMOVE_FTP_FILE]       [dbo].[N_BOOLEAN_Y] NULL,
    [IMPORT_UNICODE]        [dbo].[N_BOOLEAN_N] NULL,
    [EXPORT_UNICODE]        [dbo].[N_BOOLEAN_N] NULL,
    [IMPORT_METHOD]         [dbo].[D_INT]       NULL,
    [EXPORT_METHOD]         [dbo].[D_INT]       NULL,
    [IMPORT_CODEPAGE]       [dbo].[D_INT]       NULL,
    [CREATE_DATE]           [dbo].[D_DATE]      NULL,
    [CREATE_BY]             [dbo].[N_USER]      NULL,
    [UPDATE_DATE]           [dbo].[D_DATE]      NULL,
    [UPDATE_BY]             [dbo].[N_USER]      NULL,
    CONSTRAINT [PK_MD_SYSTEMID] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC)
);

