CREATE TABLE [dbo].[MD_UNSPSC] (
    [UNSPSC_ID]        [dbo].[N_C20]  NOT NULL,
    [UNSPSC_NAME]      [dbo].[N_C100] NULL,
    [UNSPSC_PARENT_ID] [dbo].[N_C20]  NULL,
    CONSTRAINT [PK_MD_UNSPSC] PRIMARY KEY CLUSTERED ([UNSPSC_ID] ASC),
    CONSTRAINT [FK_MD_UNSPSC_MD_UNSPSC] FOREIGN KEY ([UNSPSC_PARENT_ID]) REFERENCES [dbo].[MD_UNSPSC] ([UNSPSC_ID])
);

