CREATE TABLE [dbo].[PU_COMPLIANCE_SUPPLIER] (
    [COMPLIANCE_ID]        [dbo].[D_INT]  NULL,
    [SYSTEM_ID]            [dbo].[D_INT]  NULL,
    [SUPPLIER_CODE]        [dbo].[N_C50]  NULL,
    [SUPPLIER_CATEGORY_ID] [dbo].[D_INT]  NULL,
    [CREATE_DATE]          [dbo].[D_DATE] NULL,
    [CREATE_USER]          [dbo].[N_USER] NULL,
    CONSTRAINT [FK_PU_COMPLIANCE_SUPPLIER_PU_COMPLIANCE] FOREIGN KEY ([COMPLIANCE_ID]) REFERENCES [dbo].[PU_COMPLIANCE] ([COMPLIANCE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_SUPPLIER]
    ON [dbo].[PU_COMPLIANCE_SUPPLIER]([COMPLIANCE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_SUPPLIER_1]
    ON [dbo].[PU_COMPLIANCE_SUPPLIER]([SYSTEM_ID] ASC, [SUPPLIER_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_SUPPLIER_2]
    ON [dbo].[PU_COMPLIANCE_SUPPLIER]([SYSTEM_ID] ASC, [SUPPLIER_CATEGORY_ID] ASC);

