CREATE TABLE [dbo].[PU_COMPLIANCE_BONUS] (
    [COMPLIANCE_ID] [dbo].[D_INT]     NULL,
    [BONUS_AMOUNT]  [dbo].[D_DEC12.2] NULL,
    [BONUS_PCT]     [dbo].[D_DEC7.2]  NULL,
    [UPDATE_BY]     [dbo].[N_USER]    NULL,
    [UPDATE_DATE]   [dbo].[D_DATE]    NULL,
    CONSTRAINT [FK_PU_COMPLIANCE_BONUS_PU_COMPLIANCE] FOREIGN KEY ([COMPLIANCE_ID]) REFERENCES [dbo].[PU_COMPLIANCE] ([COMPLIANCE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_BONUS]
    ON [dbo].[PU_COMPLIANCE_BONUS]([COMPLIANCE_ID] ASC);

