CREATE TABLE [dbo].[PU_COMPLIANCE_IMAGE] (
    [COMPLIANCE_ID]    [dbo].[D_INT]  NULL,
    [IMAGE_ID]         [dbo].[D_INT]  NULL,
    [FILENAME]         [dbo].[N_C100] NULL,
    [COMPLIANCE_IMAGE] IMAGE          NULL,
    [CREATE_DATE]      [dbo].[D_DATE] NULL,
    [CREATE_BY]        [dbo].[N_USER] NULL,
    CONSTRAINT [FK_PU_COMPLIANCE_IMAGE_PU_COMPLIANCE] FOREIGN KEY ([COMPLIANCE_ID]) REFERENCES [dbo].[PU_COMPLIANCE] ([COMPLIANCE_ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_IMAGE]
    ON [dbo].[PU_COMPLIANCE_IMAGE]([COMPLIANCE_ID] ASC);

