CREATE TABLE [dbo].[PU_CATEGORY] (
    [CATEGORY_ID]   [dbo].[D_INT]  NOT NULL,
    [CATEGORY_NAME] [dbo].[N_C100] NULL,
    [PARENT_ID]     [dbo].[D_INT]  NULL,
    [CREATE_BY]     [dbo].[N_USER] NULL,
    [CREATE_DATE]   [dbo].[D_DATE] NULL,
    [UPDATE_BY]     [dbo].[N_USER] NULL,
    [UPDATE_DATE]   [dbo].[D_DATE] NULL,
    [LEVEL_1_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_2_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_3_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_4_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_5_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_6_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_7_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_8_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_9_ID]    [dbo].[D_INT]  NULL,
    [LEVEL_10_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_11_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_12_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_13_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_14_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_15_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_16_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_17_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_18_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_19_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_20_ID]   [dbo].[D_INT]  NULL,
    [LEVEL_1_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_2_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_3_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_4_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_5_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_6_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_7_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_8_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_9_NAME]  [dbo].[N_C100] NULL,
    [LEVEL_10_NAME] [dbo].[N_C100] NULL,
    [LEVEL_11_NAME] [dbo].[N_C100] NULL,
    [LEVEL_12_NAME] [dbo].[N_C100] NULL,
    [LEVEL_13_NAME] [dbo].[N_C100] NULL,
    [LEVEL_14_NAME] [dbo].[N_C100] NULL,
    [LEVEL_15_NAME] [dbo].[N_C100] NULL,
    [LEVEL_16_NAME] [dbo].[N_C100] NULL,
    [LEVEL_17_NAME] [dbo].[N_C100] NULL,
    [LEVEL_18_NAME] [dbo].[N_C100] NULL,
    [LEVEL_19_NAME] [dbo].[N_C100] NULL,
    [LEVEL_20_NAME] [dbo].[N_C100] NULL,
    CONSTRAINT [PK_PU_CATEGORY_1] PRIMARY KEY CLUSTERED ([CATEGORY_ID] ASC),
    CONSTRAINT [FK_PU_CATEGORY_PU_CATEGORY] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[PU_CATEGORY] ([CATEGORY_ID])
);

