CREATE TABLE [dbo].[PU_COMPLIANCE_BONUSTYPE] (
    [BONUS_ID]          [dbo].[D_INT]  NOT NULL,
    [BONUS_NAME]        [dbo].[N_C100] NULL,
    [BONUS_TYPE]        [dbo].[D_INT]  NULL,
    [BONUS_DESCRIPTION] [dbo].[N_MEMO] NULL,
    CONSTRAINT [PK_PU_COMPLIANCE_BONUSTYPE] PRIMARY KEY CLUSTERED ([BONUS_ID] ASC)
);

