CREATE TABLE [dbo].[PU_COMPLIANCE_ITEM] (
    [COMPLIANCE_ID]   [dbo].[D_INT]      NULL,
    [SYSTEM_ID]       [dbo].[D_INT]      NULL,
    [ITEM_NO]         [dbo].[N_C50]      NULL,
    [CATEGORY_ID]     [dbo].[D_INT]      NULL,
    [CREATE_DATE]     [dbo].[D_DATE]     NULL,
    [CREATE_USER]     [dbo].[N_USER]     NULL,
    [AGREED_PRICE]    [dbo].[D_DEC11.4]  NULL,
    [AGREED_CURRENCY] [dbo].[N_CURRENCY] NULL,
    [UOM]             [dbo].[N_C20]      NULL,
    [QUANTITY_FROM]   [dbo].[D_DEC11.4]  NULL,
    [QUANTITY_TO]     [dbo].[D_DEC11.4]  NULL,
    CONSTRAINT [FK_PU_COMPLIANCE_ITEM_MD_ITEMS] FOREIGN KEY ([SYSTEM_ID], [ITEM_NO]) REFERENCES [dbo].[MD_ITEMS] ([SYSTEM_ID], [ITEM_NO]),
    CONSTRAINT [FK_PU_COMPLIANCE_ITEM_PU_CATEGORY] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[PU_CATEGORY] ([CATEGORY_ID]),
    CONSTRAINT [FK_PU_COMPLIANCE_MATERIAL_PU_COMPLIANCE] FOREIGN KEY ([COMPLIANCE_ID]) REFERENCES [dbo].[PU_COMPLIANCE] ([COMPLIANCE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[PU_COMPLIANCE_ITEM] NOCHECK CONSTRAINT [FK_PU_COMPLIANCE_ITEM_MD_ITEMS];


GO
ALTER TABLE [dbo].[PU_COMPLIANCE_ITEM] NOCHECK CONSTRAINT [FK_PU_COMPLIANCE_ITEM_PU_CATEGORY];


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_MATERIAL]
    ON [dbo].[PU_COMPLIANCE_ITEM]([COMPLIANCE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_MATERIAL_1]
    ON [dbo].[PU_COMPLIANCE_ITEM]([SYSTEM_ID] ASC, [ITEM_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PU_COMPLIANCE_MATERIAL_2]
    ON [dbo].[PU_COMPLIANCE_ITEM]([SYSTEM_ID] ASC, [CATEGORY_ID] ASC);

