CREATE TABLE [dbo].[PU_DELIVERYTERM] (
    [DELEVERITERM] [dbo].[N_C100] NOT NULL,
    [TEXT]         [dbo].[N_C100] NULL,
    CONSTRAINT [PK_PU_DELIVERYTERM] PRIMARY KEY CLUSTERED ([DELEVERITERM] ASC)
);

