CREATE TABLE [dbo].[PU_DEPARTMENT] (
    [DEPARTMENT_ID]   [dbo].[D_INT]  NOT NULL,
    [DEPARTMENT_NAME] [dbo].[N_C100] NULL,
    [PARENT_ID]       [dbo].[D_INT]  NULL,
    [CREATE_BY]       [dbo].[N_USER] NULL,
    [CREATE_DATE]     [dbo].[D_DATE] NULL,
    [UPDATE_BY]       [dbo].[N_USER] NULL,
    [UPDATE_DATE]     [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_DEPARTMENT_1] PRIMARY KEY CLUSTERED ([DEPARTMENT_ID] ASC),
    CONSTRAINT [FK_PU_DEPARTMENT_PU_DEPARTMENT] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[PU_DEPARTMENT] ([DEPARTMENT_ID])
);

