CREATE TABLE [dbo].[PU_IGNORE_WORD] (
    [SYSTEM_ID]   [dbo].[D_INT] NOT NULL,
    [IGNORE_WORD] [dbo].[N_C50] NOT NULL,
    CONSTRAINT [PK_PU_IGNORE_WORD] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC, [IGNORE_WORD] ASC)
);

