CREATE TABLE [dbo].[PU_IGNORE_CHAR] (
    [SYSTEM_ID]   [dbo].[D_INT] NOT NULL,
    [IGNORE_CHAR] [dbo].[N_C1]  NOT NULL,
    CONSTRAINT [PK_PU_IGNORE_CHAR] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC, [IGNORE_CHAR] ASC)
);

