CREATE TABLE [dbo].[PU_LINK_SUPPLIER_CATEGORY] (
    [SUPPLIER_CATEGORY_ID] [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]            [dbo].[D_INT]  NOT NULL,
    [SUPPLIER_CODE]        [dbo].[N_C50]  NOT NULL,
    [MATCH_ID]             [dbo].[D_INT]  NULL,
    [CREATE_BY]            [dbo].[N_USER] NULL,
    [CREATE_DATE]          [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_SUPPLIER_CATEGORY_1] PRIMARY KEY CLUSTERED ([SUPPLIER_CATEGORY_ID] ASC, [SYSTEM_ID] ASC, [SUPPLIER_CODE] ASC),
    CONSTRAINT [FK_PU_LINK_SUPPLIER_CATEGORY_PU_SUPPLIER] FOREIGN KEY ([SYSTEM_ID], [SUPPLIER_CODE]) REFERENCES [dbo].[PU_SUPPLIER] ([SYSTEM_ID], [SUPPLIER_CODE]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PU_LINK_SUPPLIER_CATEGORY_PU_SUPPLIER_CATEGORY] FOREIGN KEY ([SUPPLIER_CATEGORY_ID]) REFERENCES [dbo].[PU_SUPPLIER_CATEGORY] ([SUPPLIER_CATEGORY_ID])
);


GO
ALTER TABLE [dbo].[PU_LINK_SUPPLIER_CATEGORY] NOCHECK CONSTRAINT [FK_PU_LINK_SUPPLIER_CATEGORY_PU_SUPPLIER];


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_SUPPLIER_CATEGORY]
    ON [dbo].[PU_LINK_SUPPLIER_CATEGORY]([SYSTEM_ID] ASC, [SUPPLIER_CODE] ASC);

