CREATE TABLE [dbo].[PU_LINK_DEPARTMENT] (
    [DEPARTMENT_ID]       [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]           [dbo].[D_INT]  NOT NULL,
    [LOCAL_DEPARTMENT_ID] [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]           [dbo].[N_USER] NULL,
    [CREATE_DATE]         [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_DEPARTMENT] PRIMARY KEY CLUSTERED ([DEPARTMENT_ID] ASC, [SYSTEM_ID] ASC, [LOCAL_DEPARTMENT_ID] ASC),
    CONSTRAINT [FK_PU_LINK_DEPARTMENT_PU_DEPARTMENT] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[PU_DEPARTMENT] ([DEPARTMENT_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_DEPARTMENT]
    ON [dbo].[PU_LINK_DEPARTMENT]([SYSTEM_ID] ASC, [LOCAL_DEPARTMENT_ID] ASC);

