CREATE TABLE [dbo].[PU_LINK_RMI_CATEGORY] (
    [PRODUCT_GROUP] [dbo].[N_C100] NOT NULL,
    [CATEGORY_ID]   [dbo].[D_INT]  NOT NULL,
    [CREATE_DATE]   [dbo].[D_DATE] NULL,
    [CREATE_BY]     [dbo].[N_USER] NULL,
    CONSTRAINT [PK_PU_LINK_RMI_CATEGORY] PRIMARY KEY CLUSTERED ([PRODUCT_GROUP] ASC, [CATEGORY_ID] ASC),
    CONSTRAINT [FK_PU_LINK_RMI_CATEGORY_MD_PRODUCTGROUPS] FOREIGN KEY ([PRODUCT_GROUP]) REFERENCES [dbo].[MD_PRODUCTGROUPS] ([PRODUCT_GROUP]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PU_LINK_RMI_CATEGORY_PU_CATEGORY] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[PU_CATEGORY] ([CATEGORY_ID]) ON DELETE CASCADE
);

