CREATE TABLE [dbo].[PU_LINK_DELIVERYTERM] (
    [DELIVERYTERM_ID] [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]       [dbo].[D_INT]  NOT NULL,
    [DELIVERY_TERM]   [dbo].[N_C20]  NOT NULL,
    [CREATE_BY]       [dbo].[N_USER] NULL,
    [CREATE_DATE]     [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_DELIVERYTERM] PRIMARY KEY CLUSTERED ([DELIVERYTERM_ID] ASC, [SYSTEM_ID] ASC, [DELIVERY_TERM] ASC)
);

