CREATE TABLE [dbo].[PU_LINK_AMM_CATEGORY] (
    [AMM_GROUP_ID] [dbo].[D_INT]  NOT NULL,
    [CATEGORY_ID]  [dbo].[D_INT]  NOT NULL,
    [CREATE_DATE]  [dbo].[D_DATE] NULL,
    [CREATE_BY]    [dbo].[N_USER] NULL,
    CONSTRAINT [PK_PU_LINK_AMM_CATEGORY] PRIMARY KEY CLUSTERED ([AMM_GROUP_ID] ASC, [CATEGORY_ID] ASC),
    CONSTRAINT [FK_PU_LINK_AMM_CATEGORY_PU_CATEGORY] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[PU_CATEGORY] ([CATEGORY_ID])
);

