CREATE TABLE [dbo].[PU_LINK_COUNTRY] (
    [COUNTRY_ID]  [dbo].[N_C20]  NOT NULL,
    [SYSTEM_ID]   [dbo].[D_INT]  NOT NULL,
    [COUNTRY]     [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]   [dbo].[N_USER] NULL,
    [CREATE_DATE] [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_COUNTRY] PRIMARY KEY CLUSTERED ([COUNTRY_ID] ASC, [SYSTEM_ID] ASC, [COUNTRY] ASC),
    CONSTRAINT [FK_PU_LINK_COUNTRY_MD_COUNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[MD_COUNTRY] ([COUNTRY_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_COUNTRY]
    ON [dbo].[PU_LINK_COUNTRY]([SYSTEM_ID] ASC, [COUNTRY] ASC);

