CREATE TABLE [dbo].[PU_LINK_CUSTOMER_SUPPLIER] (
    [CUSTOMER_ID]   [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]     [dbo].[D_INT]  NOT NULL,
    [SUPPLIER_CODE] [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]     [dbo].[N_USER] NULL,
    [CREATE_DATE]   [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_CUSTOMER_SUPPLIER] PRIMARY KEY CLUSTERED ([CUSTOMER_ID] ASC, [SYSTEM_ID] ASC, [SUPPLIER_CODE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_CUSTOMER_SUPPLIER]
    ON [dbo].[PU_LINK_CUSTOMER_SUPPLIER]([SYSTEM_ID] ASC, [SUPPLIER_CODE] ASC);

