CREATE TABLE [dbo].[PU_LINK_UOM] (
    [SYSTEM_ID]      [dbo].[D_INT]     NOT NULL,
    [LOCAL_UOM]      [dbo].[N_C20]     NOT NULL,
    [HARMONIZED_UOM] [dbo].[N_C20]     NOT NULL,
    [FACTOR]         [dbo].[D_DEC11.4] NULL,
    [CREATE_BY]      [dbo].[N_USER]    NULL,
    [CREATE_DATE]    [dbo].[D_DATE]    NULL,
    [UPDATE_BY]      [dbo].[N_USER]    NULL,
    [UPDATE_DATE]    [dbo].[D_DATE]    NULL,
    CONSTRAINT [PK_PU_LINK_UOM] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC, [LOCAL_UOM] ASC, [HARMONIZED_UOM] ASC),
    CONSTRAINT [FK_PU_LINK_UOM_MD_SYSTEMID] FOREIGN KEY ([SYSTEM_ID]) REFERENCES [dbo].[MD_SYSTEMID] ([SYSTEM_ID]),
    CONSTRAINT [FK_PU_LINK_UOM_MD_UNIT] FOREIGN KEY ([HARMONIZED_UOM]) REFERENCES [dbo].[MD_UNIT] ([UOM])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_UOM]
    ON [dbo].[PU_LINK_UOM]([SYSTEM_ID] ASC, [LOCAL_UOM] ASC);

