CREATE TABLE [dbo].[PU_LINK_SITE] (
    [SITE_ID]     [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]   [dbo].[D_INT]  NOT NULL,
    [LOCAL_SITE]  [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]   [dbo].[N_USER] NULL,
    [CREATE_DATE] [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_SITE] PRIMARY KEY CLUSTERED ([SITE_ID] ASC, [SYSTEM_ID] ASC, [LOCAL_SITE] ASC),
    CONSTRAINT [FK_PU_LINK_SITE_MD_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[MD_SITE] ([SITE_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_SITE]
    ON [dbo].[PU_LINK_SITE]([SYSTEM_ID] ASC, [LOCAL_SITE] ASC);

