CREATE TABLE [dbo].[PU_LINK_JOIN] (
    [JOIN_ITEM_NO] [dbo].[N_C50]  NOT NULL,
    [SYSTEM_ID]    [dbo].[D_INT]  NOT NULL,
    [ITEM_NO]      [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]    [dbo].[N_USER] NULL,
    [CREATE_DATE]  [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_JOIN] PRIMARY KEY CLUSTERED ([JOIN_ITEM_NO] ASC, [SYSTEM_ID] ASC, [ITEM_NO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PU_LINK_JOIN]
    ON [dbo].[PU_LINK_JOIN]([JOIN_ITEM_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PU_LINK_JOIN_1]
    ON [dbo].[PU_LINK_JOIN]([SYSTEM_ID] ASC, [ITEM_NO] ASC);

