CREATE TABLE [dbo].[PU_LINK_ACCOUNT] (
    [CATEGORY_ID] [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]   [dbo].[D_INT]  NOT NULL,
    [ACCOUNT_NO]  [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]   [dbo].[N_USER] NULL,
    [CREATE_DATE] [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_ACCOUNT] PRIMARY KEY CLUSTERED ([CATEGORY_ID] ASC, [SYSTEM_ID] ASC, [ACCOUNT_NO] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_ACCOUNT]
    ON [dbo].[PU_LINK_ACCOUNT]([SYSTEM_ID] ASC, [ACCOUNT_NO] ASC);

