CREATE TABLE [dbo].[PU_LINK_ELEMENT] (
    [CATEGORY_ID]     [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]       [dbo].[D_INT]  NOT NULL,
    [PROJECT_ELEMENT] [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]       [dbo].[N_USER] NULL,
    [CREATE_DATE]     [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_LINK_ELEMENT] PRIMARY KEY CLUSTERED ([CATEGORY_ID] ASC, [SYSTEM_ID] ASC, [PROJECT_ELEMENT] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_ELEMENT]
    ON [dbo].[PU_LINK_ELEMENT]([SYSTEM_ID] ASC, [PROJECT_ELEMENT] ASC);

