CREATE TABLE [dbo].[PU_LINK_ITEM] (
    [CATEGORY_ID] [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]   [dbo].[D_INT]  NOT NULL,
    [ITEM_NO]     [dbo].[N_C50]  NOT NULL,
    [CREATE_BY]   [dbo].[N_USER] NULL,
    [CREATE_DATE] [dbo].[D_DATE] NULL,
    [MATCH_ID]    [dbo].[D_INT]  NULL,
    CONSTRAINT [PK_PU_LINK_CATEGORY_1] PRIMARY KEY CLUSTERED ([CATEGORY_ID] ASC, [SYSTEM_ID] ASC, [ITEM_NO] ASC),
    CONSTRAINT [FK_PU_LINK_CATEGORY_MD_SYSTEMID] FOREIGN KEY ([SYSTEM_ID]) REFERENCES [dbo].[MD_SYSTEMID] ([SYSTEM_ID]),
    CONSTRAINT [FK_PU_LINK_CATEGORY_PU_CATEGORY] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[PU_CATEGORY] ([CATEGORY_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PU_LINK_CATEGORY]
    ON [dbo].[PU_LINK_ITEM]([SYSTEM_ID] ASC, [ITEM_NO] ASC);

