CREATE TABLE [dbo].[PU_PURCHASE_BACKUP] (
    [SYSTEM_ID]                     [dbo].[D_INT]      NOT NULL,
    [INVOICE_DATE]                  [dbo].[D_DATE]     NOT NULL,
    [INVOICE_NUMBER]                [dbo].[N_C20]      NOT NULL,
    [INVOICE_LINE_NUMBER]           [dbo].[N_C20]      NOT NULL,
    [SUPPLIER_CODE]                 [dbo].[N_C50]      NOT NULL,
    [ORDERING_SITE]                 [dbo].[N_C20]      NULL,
    [SHIP_TO_SITE]                  [dbo].[N_C20]      NULL,
    [INVOICE_TYPE]                  [dbo].[N_C1]       NULL,
    [MATERIAL_CODE]                 [dbo].[N_C50]      NULL,
    [PAYMENT_TERM]                  [dbo].[N_C20]      NULL,
    [PAYMENT_TERM_TEXT]             [dbo].[N_C100]     NULL,
    [DELIVERY_TERM]                 [dbo].[N_C20]      NULL,
    [DELIVERY_TERM_TEXT]            [dbo].[N_C100]     NULL,
    [INVOICE_AMOUNT]                [dbo].[D_DEC15,4]  NULL,
    [INVOICE_CURRENCY]              [dbo].[N_CURRENCY] NULL,
    [INVOICE_AMOUNT_EURO]           [dbo].[D_DEC15,4]  NULL,
    [INVOICE_AMOUNT_LOCAL]          [dbo].[D_DEC15,4]  NULL,
    [INVOICE_LOCAL_CURRENCY]        [dbo].[N_CURRENCY] NULL,
    [QUANTITY]                      [dbo].[D_DEC12.2]  NULL,
    [UOM]                           [dbo].[N_C20]      NULL,
    [LOCAL_QUANTITY]                [dbo].[D_DEC12.2]  NULL,
    [LOCAL_UOM]                     [dbo].[N_CURRENCY] NULL,
    [DELIVERY_DATE]                 [dbo].[D_DATE]     NULL,
    [AGREED_DATE]                   [dbo].[D_DATE]     NULL,
    [AGREED_QUANTITY]               [dbo].[D_DEC12.2]  NULL,
    [AGREED_UOM]                    [dbo].[N_C20]      NULL,
    [AGREED_QUANTITY_LOCAL]         [dbo].[D_DEC12.2]  NULL,
    [AGREED_UOM_LOCAL]              [dbo].[N_C20]      NULL,
    [MATERIAL_DESCRIPTION_LOCAL]    [dbo].[N_C100]     NULL,
    [MATERIAL_DESCRIPTION_SUPPLIER] [dbo].[N_C100]     NULL,
    [MATERIAL_CHAR1]                [dbo].[N_C50]      NULL,
    [MATERIAL_CHAR1_VALUE]          [dbo].[D_DEC12.2]  NULL,
    [MATERIAL_CHAR2]                [dbo].[N_C50]      NULL,
    [MATERIAL_CHAR2_VALUE]          [dbo].[D_DEC12.2]  NULL,
    [MATERIAL_CHAR3]                [dbo].[N_C50]      NULL,
    [MATERIAL_CHAR3_VALUE]          [dbo].[D_DEC12.2]  NULL,
    [MATERIAL_CHAR4]                [dbo].[N_C50]      NULL,
    [MATERIAL_CHAR4_VALUE]          [dbo].[D_DEC12.2]  NULL,
    [MATERIAL_CHAR5]                [dbo].[N_C50]      NULL,
    [MATERIAL_CHAR5_VALUE]          [dbo].[D_DEC12.2]  NULL,
    [PURCHASE_ORDER_NUMBER]         [dbo].[N_C50]      NULL,
    [MATERIAL_GROUP]                [dbo].[N_C50]      NULL,
    [MATERIAL_TYPE1]                [dbo].[N_C50]      NULL,
    [MATERIAL_TYPE2]                [dbo].[N_C50]      NULL,
    [CREATE_DATE]                   [dbo].[D_DATE]     NULL,
    [CREATE_BY]                     [dbo].[N_USER]     NULL,
    [UPDATE_DATE]                   [dbo].[D_DATE]     NULL,
    [UPDATE_BY]                     [dbo].[N_USER]     NULL,
    [BUYER]                         [dbo].[N_C20]      NULL,
    [COMPLIANCE_ID]                 [dbo].[D_INT]      NULL,
    [COMPLIANCE_KEPT]               BIT                NULL,
    [COMPLIANCE_PRICE]              [dbo].[D_DEC12.2]  NULL,
    [COMPLIANCE_CURRENCY]           [dbo].[N_CURRENCY] NULL,
    [UNSPEC_ID]                     [dbo].[N_C20]      NULL,
    CONSTRAINT [PK_PU_PURCHASE_BACKUP] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC, [INVOICE_DATE] ASC, [INVOICE_NUMBER] ASC, [INVOICE_LINE_NUMBER] ASC, [SUPPLIER_CODE] ASC)
);

