CREATE TABLE [dbo].[PU_PAYMENTTERM] (
    [PAYMENTTERM_ID]   [dbo].[D_INT]  NOT NULL,
    [PAYMENTTERM_NAME] [dbo].[N_C100] NULL,
    [DAYS]             [dbo].[D_INT]  NULL,
    [CREATE_BY]        [dbo].[N_USER] NULL,
    [CREATE_DATE]      [dbo].[D_DATE] NULL,
    [UPDATE_BY]        [dbo].[N_USER] NULL,
    [UPDATE_DATE]      [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_PAYMENTTERM] PRIMARY KEY CLUSTERED ([PAYMENTTERM_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PU_PAYMENTTERM]
    ON [dbo].[PU_PAYMENTTERM]([PAYMENTTERM_ID] ASC);

