CREATE TABLE [dbo].[PU_SUPPLIER_BONUS] (
    [SUPPLIER_BONUS_ID]    [dbo].[D_INT]      NOT NULL,
    [SUPPLIER_CATEGORY_ID] [dbo].[D_INT]      NOT NULL,
    [BONUS_ID]             [dbo].[D_INT]      NOT NULL,
    [START_DATE]           [dbo].[D_DATE]     NOT NULL,
    [END_DATE]             [dbo].[D_DATE]     NULL,
    [BONUS_UNIT]           [dbo].[N_C20]      NULL,
    [BONUS_CURRENCY]       [dbo].[N_CURRENCY] NULL,
    [LOCAL_GLOBAL]         [dbo].[N_C1]       NULL,
    [BONUS_PERIOD]         [dbo].[N_C20]      NULL,
    [REMARKS]              [dbo].[N_MEMO]     NULL,
    [CREATE_BY]            [dbo].[N_USER]     NULL,
    [CREATE_DATE]          [dbo].[D_DATE]     NULL,
    [UPDATE_BY]            [dbo].[N_USER]     NULL,
    [UPDATE_DATE]          [dbo].[D_DATE]     NULL,
    CONSTRAINT [PK_PU_SUPPLIER_BONUS] PRIMARY KEY CLUSTERED ([SUPPLIER_BONUS_ID] ASC),
    CONSTRAINT [FK_PU_SUPPLIER_BONUS_MD_BONUSTYPE] FOREIGN KEY ([BONUS_ID]) REFERENCES [dbo].[MD_BONUSTYPE] ([BONUS_ID]),
    CONSTRAINT [FK_PU_SUPPLIER_BONUS_MD_CURRENCY] FOREIGN KEY ([BONUS_CURRENCY]) REFERENCES [dbo].[MD_CURRENCY] ([CURRENCY]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PU_SUPPLIER_BONUS_MD_UNIT] FOREIGN KEY ([BONUS_UNIT]) REFERENCES [dbo].[MD_UNIT] ([UOM]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PU_SUPPLIER_BONUS_PU_SUPPLIER_CATEGORY] FOREIGN KEY ([SUPPLIER_CATEGORY_ID]) REFERENCES [dbo].[PU_SUPPLIER_CATEGORY] ([SUPPLIER_CATEGORY_ID]) ON DELETE CASCADE
);


GO
ALTER TABLE [dbo].[PU_SUPPLIER_BONUS] NOCHECK CONSTRAINT [FK_PU_SUPPLIER_BONUS_MD_CURRENCY];


GO
ALTER TABLE [dbo].[PU_SUPPLIER_BONUS] NOCHECK CONSTRAINT [FK_PU_SUPPLIER_BONUS_MD_UNIT];

