CREATE TABLE [dbo].[PU_SUPPLIER_BONUS_ADJUST] (
    [SUPPLIER_BONUS_ID] [dbo].[D_INT]      NOT NULL,
    [BONUS_YEAR]        [dbo].[D_INT]      NOT NULL,
    [ADJUST_AMOUNT]     [dbo].[D_DEC12.2]  NULL,
    [ADJUST_CURRENCY]   [dbo].[N_CURRENCY] NULL,
    [CREATE_DATE]       [dbo].[D_DATE]     NULL,
    [CREATE_BY]         [dbo].[N_USER]     NULL,
    [UPDATE_DATE]       [dbo].[D_DATE]     NULL,
    [UPDATE_BY]         [dbo].[N_USER]     NULL,
    CONSTRAINT [PK_PU_SUPPLIER_BONUS_ADJUST] PRIMARY KEY CLUSTERED ([SUPPLIER_BONUS_ID] ASC, [BONUS_YEAR] ASC),
    CONSTRAINT [FK_PU_SUPPLIER_BONUS_ADJUST_PU_SUPPLIER_BONUS] FOREIGN KEY ([SUPPLIER_BONUS_ID]) REFERENCES [dbo].[PU_SUPPLIER_BONUS] ([SUPPLIER_BONUS_ID]) ON DELETE CASCADE
);

