CREATE TABLE [dbo].[PU_SUPPLIER_BONUS_STEP] (
    [SUPPLIER_BONUS_ID] [dbo].[D_INT]    NOT NULL,
    [FROM_VALUE]        [dbo].[D_INT]    NULL,
    [TO_VALUE]          [dbo].[D_INT]    NULL,
    [BONUS_PCT]         [dbo].[D_DEC7.2] NULL,
    [BONUS_PER_UNIT]    [dbo].[D_DEC7.2] NULL,
    CONSTRAINT [FK_PU_SUPPLIER_BONUS_STEP_PU_SUPPLIER_BONUS] FOREIGN KEY ([SUPPLIER_BONUS_ID]) REFERENCES [dbo].[PU_SUPPLIER_BONUS] ([SUPPLIER_BONUS_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PU_SUPPLIER_BONUS_STEP]
    ON [dbo].[PU_SUPPLIER_BONUS_STEP]([SUPPLIER_BONUS_ID] ASC);

