CREATE TABLE [dbo].[PU_SUPPLIER_CATEGORY] (
    [SUPPLIER_CATEGORY_ID]   [dbo].[D_INT]  NOT NULL,
    [SUPPLIER_CATEGORY_NAME] [dbo].[N_C100] NULL,
    [SUPPLIER_PARENT_ID]     [dbo].[D_INT]  NULL,
    [CREATE_BY]              [dbo].[N_USER] NULL,
    [CREATE_DATE]            [dbo].[D_DATE] NULL,
    [UPDATE_BY]              [dbo].[N_USER] NULL,
    [UPDATE_DATE]            [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_PU_SUPPLIER_CATEGORY_1] PRIMARY KEY CLUSTERED ([SUPPLIER_CATEGORY_ID] ASC),
    CONSTRAINT [FK_PU_SUPPLIER_CATEGORY_PU_SUPPLIER_CATEGORY] FOREIGN KEY ([SUPPLIER_PARENT_ID]) REFERENCES [dbo].[PU_SUPPLIER_CATEGORY] ([SUPPLIER_CATEGORY_ID])
);

