CREATE TABLE [dbo].[PU_WARNING] (
    [SYSTEM_ID]            [dbo].[D_INT]     NOT NULL,
    [INVOICE_NUMBER]       [dbo].[N_C20]     NOT NULL,
    [INVOICE_LINE_NUMBER]  [dbo].[N_C20]     NOT NULL,
    [SUPPLIER_CODE]        [dbo].[N_C50]     NOT NULL,
    [INVOICE_AMOUNT_GROUP] [dbo].[D_DEC15,4] NULL,
    [QUANTITY]             [dbo].[D_DEC12.2] NULL,
    [CREATE_DATE]          [dbo].[D_DATE]    NULL,
    [CREATE_BY]            [dbo].[N_USER]    NULL,
    CONSTRAINT [PK_PU_WARNING_1] PRIMARY KEY CLUSTERED ([SYSTEM_ID] ASC, [INVOICE_NUMBER] ASC, [INVOICE_LINE_NUMBER] ASC, [SUPPLIER_CODE] ASC),
    CONSTRAINT [FK_PU_WARNING_MD_SYSTEMID] FOREIGN KEY ([SYSTEM_ID]) REFERENCES [dbo].[MD_SYSTEMID] ([SYSTEM_ID])
);

