CREATE TABLE [dbo].[SA_CUSTOMER_CATEGORY] (
    [CUSTOMER_CATEGORY_ID]   [dbo].[D_INT]       NOT NULL,
    [CUSTOMER_CATEGORY_NAME] [dbo].[N_C100]      NULL,
    [CUSTOMER_PARENT_ID]     [dbo].[D_INT]       NULL,
    [ALLOW_CREATE_SUB]       [dbo].[N_BOOLEAN_N] NULL,
    [CENTRALIZED_MANAGED]    [dbo].[N_BOOLEAN_N] NULL,
    [CREATE_BY]              [dbo].[N_USER]      NULL,
    [CREATE_DATE]            [dbo].[D_DATE]      NULL,
    CONSTRAINT [PK_SA_CUSTOMER_CATEGORY_1] PRIMARY KEY CLUSTERED ([CUSTOMER_CATEGORY_ID] ASC),
    CONSTRAINT [FK_SA_CUSTOMER_CATEGORY_SA_CUSTOMER_CATEGORY] FOREIGN KEY ([CUSTOMER_PARENT_ID]) REFERENCES [dbo].[SA_CUSTOMER_CATEGORY] ([CUSTOMER_CATEGORY_ID])
);

