CREATE TABLE [dbo].[SA_ENV_CATEGORY] (
    [ENV_CATEGORY_ID]   [dbo].[D_INT]  NOT NULL,
    [ENV_CATEGORY_NAME] [dbo].[N_C100] NULL,
    [ENV_PARENT_ID]     [dbo].[D_INT]  NULL,
    [ENV_SORT_NO]       [dbo].[D_INT]  NULL,
    [ENV_SORTSTRING]    [dbo].[N_C50]  NULL,
    [ENV_CATEGORY_TYPE] [dbo].[D_INT]  NULL,
    [CREATE_BY]         [dbo].[N_USER] NULL,
    [CREATE_DATE]       [dbo].[D_DATE] NULL,
    [UPDATE_BY]         [dbo].[N_USER] NULL,
    [UPDATE_DATE]       [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_SA_ENV_CATEGORY_1] PRIMARY KEY CLUSTERED ([ENV_CATEGORY_ID] ASC),
    CONSTRAINT [FK_SA_ENV_CATEGORY_SA_ENV_CATEGORY] FOREIGN KEY ([ENV_PARENT_ID]) REFERENCES [dbo].[SA_ENV_CATEGORY] ([ENV_CATEGORY_ID])
);

