CREATE TABLE [dbo].[SA_ITEM_CATEGORY_REQUEST] (
    [ITEM_REQUEST_ID]      [dbo].[D_INT]       NOT NULL,
    [ITEM_CATEGORY_ID]     [dbo].[D_INT]       NOT NULL,
    [NAME_SUGGESTION]      [dbo].[N_C50]       NOT NULL,
    [INGROUP]              [dbo].[N_MEMO]      NULL,
    [DESCRIPTION]          [dbo].[N_MEMO]      NULL,
    [CREATE_BY]            [dbo].[N_USER]      NULL,
    [CREATE_DATE]          [dbo].[D_DATE]      NULL,
    [CATEGORY_CREATED]     [dbo].[N_BOOLEAN_N] NULL,
    [CATEGORY_REJECTED]    [dbo].[N_BOOLEAN_N] NULL,
    [REQUEST_MANAGER]      [dbo].[N_USER]      NULL,
    [REQUEST_MANAGER_DATE] [dbo].[D_DATE]      NULL,
    CONSTRAINT [PK_SA_ITEM_CATEGORY_REQUEST] PRIMARY KEY CLUSTERED ([ITEM_REQUEST_ID] ASC),
    CONSTRAINT [FK_SA_ITEM_CATEGORY_REQUEST_SA_ITEM_CATEGORY] FOREIGN KEY ([ITEM_CATEGORY_ID]) REFERENCES [dbo].[SA_ITEM_CATEGORY] ([ITEM_CATEGORY_ID])
);

