CREATE TABLE [dbo].[SA_LINK_CUSTOMER] (
    [CUSTOMER_CATEGORY_ID] [dbo].[D_INT]  NOT NULL,
    [SYSTEM_ID]            [dbo].[D_INT]  NOT NULL,
    [CUSTOMER_NO]          [dbo].[N_C50]  NOT NULL,
    [MATCH_ID]             [dbo].[D_INT]  NULL,
    [CREATE_BY]            [dbo].[N_USER] NULL,
    [CREATE_DATE]          [dbo].[D_DATE] NULL,
    CONSTRAINT [PK_SA_LINK_CUSTOMER_CATEGORY_1] PRIMARY KEY CLUSTERED ([CUSTOMER_CATEGORY_ID] ASC, [SYSTEM_ID] ASC, [CUSTOMER_NO] ASC),
    CONSTRAINT [FK_SA_LINK_CUSTOMER_CATEGORY_SA_CUSTOMER] FOREIGN KEY ([SYSTEM_ID], [CUSTOMER_NO]) REFERENCES [dbo].[SA_CUSTOMER] ([SYSTEM_ID], [CUSTOMER_NO]) NOT FOR REPLICATION,
    CONSTRAINT [FK_SA_LINK_CUSTOMER_CATEGORY_SA_CUSTOMER_CATEGORY] FOREIGN KEY ([CUSTOMER_CATEGORY_ID]) REFERENCES [dbo].[SA_CUSTOMER_CATEGORY] ([CUSTOMER_CATEGORY_ID])
);


GO
ALTER TABLE [dbo].[SA_LINK_CUSTOMER] NOCHECK CONSTRAINT [FK_SA_LINK_CUSTOMER_CATEGORY_SA_CUSTOMER];


GO
CREATE NONCLUSTERED INDEX [IX_SA_LINK_CUSTOMER_CATEGORY]
    ON [dbo].[SA_LINK_CUSTOMER]([SYSTEM_ID] ASC, [CUSTOMER_NO] ASC);

