IF OBJECT_ID('[discovery].[inventory]') IS NOT NULL
	DROP VIEW [discovery].[inventory];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create view [discovery].[inventory]
as
--<CommentHeader>
/**********************************************************************************************************************

Properties
==========
VIEW NAME:      discovery.inventory
DESCRIPTION:    Exposes inventory data per warehouse
AUTHOR:         Tom L. Manville
ORIGIN DATE:    03-OCT-2017

Additional Notes
================


REVISION HISTORY
=====================================================================================================================
Version	ChangeDate		Author	BugRef	Narrative
=======	============	======	=======	=============================================================================
001		03-OCT-2017		TLM		N/A		Created
------- ------------	------	-------	-----------------------------------------------------------------------------


**********************************************************************************************************************/
--</CommentHeader>

select
	mitloc.MLACUQ					as cumulative_usage_quantity
  , mitloc.MLACUW					as cumulative_usage_weight
  , mitloc.MLADJW					as adjusted_weight
  , mitloc.MLALOC					as allocatable
  , mitloc.MLALQT					as allocated_quantity_basic_um
  , mitloc.MLATNR					as ml_attribute_number
  , mitloc.MLATV1					as attribute_value_1
  , mitloc.MLATV2					as attribute_value_2
  , mitloc.MLATV3					as attribute_value_3
  , mitloc.MLATV4					as attribute_value_4
  , mitloc.MLATV5					as attribute_value_5
  , mitloc.MLAUDD					as automatic_deletion_delay
  , mitloc.MLAUDE					as automatic_deletion
  , mitloc.MLBANO					as lot_number
  , mitloc.MLBRE2					as lot_reference_2
  , mitloc.MLBREF					as lot_reference_1
  , mitloc.MLBREM					as remark
  , mitloc.MLCAMU					as container
  , mitloc.MLCANB					as cost_attribute_number
  , mitloc.MLCAWE					as catch_weight
  , mitloc.MLCHID					as changed_by
  , mitloc.MLCHNO					as change_number
  , mitloc.MLCNDT					as follow_up_date
  , mitloc.MLCONO					as company
  , mitloc.MLDTID					as data_identity
  , mitloc.MLFACI					as facility
  , mitloc.MLFIFL					as completion_flag
  , mitloc.MLIDDT					as last_receipt_date
  , mitloc.MLINCW					as initial_catch_weight
  , mitloc.MLINDT					as latest_physical_inventory_date
  , mitloc.MLINON					as physical_inventory_in_progress
  , mitloc.MLINVC					as physical_inventory_candidate
  , mitloc.MLIQTY					as initial_quantity
  , mitloc.MLITNO					as item_number
  , mitloc.MLLMDT					as change_date
  , mitloc.MLLMTS					as timestamp
  , mitloc.MLODDT					as last_issue_date
  , mitloc.MLOPAN					as outer_package_number
  , mitloc.MLPACT					as packaging
  , mitloc.MLPLQT					as picking_list_quantity_basic_um
  , mitloc.MLPOCY					as normal_potency
  , mitloc.MLPPRI					as ml_picking_priority
  , mitloc.MLPRDT					as priority_date
  , mitloc.MLPUAB					as put_away_possible
  , mitloc.MLRCLN					as reclassification_number
  , mitloc.MLRCLS					as planned_reclassification_date
  , mitloc.MLREPN					as receiving_number
  , mitloc.MLRGDT					as entry_date
  , mitloc.MLRGTM					as entry_time
  , mitloc.MLSEDT					as sales_date
  , mitloc.MLSLTP					as stock_zone
  , mitloc.MLSTAS					as status_balance_id
  , mitloc.MLSTES					as sample_test
  , mitloc.MLSTNB					as physical_inventory_number
  , mitloc.MLSTQM					as on_hand_balance_main_um
  , mitloc.MLSTQT					as on_hand_balance_approved
  , mitloc.MLTXID					as text_identity
  , mitloc.MLWHLO					as warehouse
  , mitloc.MLWHLT					as location_type
  , mitloc.MLWHSL					as location
  , mitaun.MUCONO					as uom_company
  , mitaun.MUITNO					as uom_item_number
  , mitaun.MUAUTP					as uom_alternate_um_type
  , mitaun.MUALUN					as uom_alternate_um
  , mitaun.MUDCCD					as uom_number_of_decimal_places
  , mitaun.MUCOFA					as uom_conversion_factor
  , mitaun.MUDMCF					as uom_conversion_form
  , mitaun.MUPCOF					as uom_price_adjustment_factor
  , mitaun.MUAUS1					as uom_standard_um_purchase_order
  , mitaun.MUAUS2					as uom_standard_um_customer_order_sales
  , mitaun.MUAUS3					as uom_standard_um_manufacturing
  , mitaun.MUAUS4					as uom_standard_um_production_engineering
  , mitaun.MUAUS5					as uom_standard_um_purchase_price
  , mitaun.MUAUS6					as uom_standard_um_statistics
  , mitaun.MUAUS9					as uom_standard_um_sales_price
  , mitaun.MUUNMU					as uom_order_multiple
  , mitaun.MUFMID					as uom_formula
  , mitaun.MURESI					as uom_result_identity
  , mitaun.MUTXID					as uom_text_identity
  , mitaun.MURGDT					as uom_entry_date
  , mitaun.MURGTM					as uom_entry_time
  , mitaun.MULMDT					as uom_change_date
  , mitaun.MUCHNO					as uom_change_number
  , mitaun.MUCHID					as uom_changed_by
  , mitaun.MULMTS					as uom_timestamp
  , mitaun.MUPACT					as uom_packaging
  , mitaun.MUAUSC					as uom_standard_um_catch_weight
  , mitaun.MUAUSB					as uom_standard_um_cost
  , mitmas.MMCONO					as master_company
  , mitmas.MMSTAT					as master_status
  , mitmas.MMITNO					as master_item_number
  , mitmas.MMITDS					as master_name
  , mitmas.MMFUDS					as master_description_2
  , mitmas.MMDWNO					as master_drawing_number
  , mitmas.MMRESP					as master_responsible
  , mitmas.MMDCCD					as master_number_of_decimal_places
  , mitmas.MMUNMS					as master_basic_unit_of_measure
  , mitmas.MMITGR					as master_item_group
  , mitmas.MMITCL					as master_product_group
  , mitmas.MMBUAR					as master_business_area
  , mitmas.MMEVGR					as master_environment_group
  , mitmas.MMITTY					as master_item_type
  , mitmas.MMTPCD					as master_item_category
  , mitmas.MMMABU					as makebuy_code
  , mitmas.MMCHCD					as configuration_code
  , mitmas.MMSTCD					as inventory_accounting
  , mitmas.MMBACD					as lot_numbering_method
  , mitmas.MMVOL3					as volume
  , mitmas.MMNEWE					as net_weight
  , mitmas.MMGRWE					as gross_weight
  , mitmas.MMPPUN					as purchase_price_um
  , mitmas.MMBYPR					as byco_product_code
  , mitmas.MMWAPC					as normal_waste_percentage
  , mitmas.MMQACD					as inspection_code
  , mitmas.MMEPCD					as yield_calculation
  , mitmas.MMPOCY					as mas_normal_potency
  , mitmas.MMACTI					as active_or_catch_weight_item
  , mitmas.MMHIE1					as hierarchy_level_1
  , mitmas.MMHIE2					as hierarchy_level_2
  , mitmas.MMHIE3					as hierarchy_level_3
  , mitmas.MMHIE4					as hierarchy_level_4
  , mitmas.MMHIE5					as hierarchy_level_5
  , mitmas.MMGRP1					as search_group_1
  , mitmas.MMGRP2					as search_group_2
  , mitmas.MMGRP3					as search_group_3
  , mitmas.MMGRP4					as search_group_4
  , mitmas.MMGRP5					as search_group_5
  , mitmas.MMCFI1					as user_defined_field_1_item
  , mitmas.MMCFI2					as user_defined_field_2_item
  , mitmas.MMCFI3					as user_defined_field_3_item
  , mitmas.MMCFI4					as user_defined_field_4_item
  , mitmas.MMCFI5					as user_defined_field_5_item
  , mitmas.MMECCC					as consumption_code_trade_stat_tst
  , mitmas.MMTXID					as master_text_identity
  , mitmas.MMDTID					as master_data_identity
  , mitmas.MMECVE					as revision_number
  , mitmas.MMECAC					as engineering_change_order_type
  , mitmas.MMECMA					as eco_managed
  , mitmas.MMECFL					as active_engineering_changes
  , mitmas.MMWSCA					as costing_model
  , mitmas.MMPRGP					as procurement_group
  , mitmas.MMETRF					as external_instruction
  , mitmas.MMACRF					as user_defined_accounting_control_object
  , mitmas.MMINDI					as lot_control_method
  , mitmas.MMPUUN					as purchase_order_um
  , mitmas.MMAUTC					as issue_message
  , mitmas.MMALUC					as alternate_um_in_use
  , mitmas.MMPDCC					as number_of_price_decimal_places
  , mitmas.MMIEAA					as item_exists_as_alias_identity
  , mitmas.MMRIDE					as reference_identity
  , mitmas.MMRIDC					as reference_identity_code
  , mitmas.MMGRTI					as group_technology_class
  , mitmas.MMGRTS					as master_distribution_group_technology
  , mitmas.MMEXPD					as expiration_date_method
  , mitmas.MMITRF					as internal_instruction
  , mitmas.MMPRCM					as costing_model_product_costing
  , mitmas.MMGRMT					as goods_receiving_method
  , mitmas.MMHAZI					as danger_indicator
  , mitmas.MMSALE					as sales_item
  , mitmas.MMFRAG					as fragility
  , mitmas.MMTAXC					as tax_code_customeraddress
  , mitmas.MMATMO					as attribute_model
  , mitmas.MMATMN					as attribute_managed
  , mitmas.MMTPLI					as template_item_number
  , mitmas.MMFCU1					as capacity_free_capacity_unit
  , mitmas.MMSUNO					as master_supplier
  , mitmas.MMPUPR					as purchase_price
  , mitmas.MMPUCD					as purchase_price_quantity
  , mitmas.MMCUCD					as currency
  , mitmas.MMPPDT					as purchase_price_date
  , mitmas.MMSAPR					as sales_price
  , mitmas.MMSTUN					as statistical_um
  , mitmas.MMSACD					as sales_price_quantity
  , mitmas.MMCUCS					as currency_sales_price
  , mitmas.MMSPDT					as sales_price_date
  , mitmas.MMDIGI					as discount_group_item
  , mitmas.MMBGRP					as bonus_group
  , mitmas.MMPRVG					as commission_group
  , mitmas.MMFRE3					as statistics_identity_3_item
  , mitmas.MMFRE4					as statistics_identity_4_item
  , mitmas.MMOTDI					as order_total_discount_generating
  , mitmas.MMBOGR					as bonus_generating
  , mitmas.MMPRGR					as commission_generating
  , mitmas.MMLAMA					as minimum_accepted_contributn_margin_ratio
  , mitmas.MMACHK					as assortment_check
  , mitmas.MMBPEY					as update_buying_pattern
  , mitmas.MMSPUN					as sales_price_unit_of_measure
  , mitmas.MMSPUC					as fixed_or_dynamic_sales_price_um
  , mitmas.MMALUN					as master_alternate_um
  , mitmas.MMUNNN					as un_number
  , mitmas.MMUNPA					as un_pack_code
  , mitmas.MMHAC1					as danger_class_1
  , mitmas.MMHAC2					as danger_class_2
  , mitmas.MMHAC3					as danger_class_3
  , mitmas.MMDIM1					as measurement_1
  , mitmas.MMDIM2					as measurement_2
  , mitmas.MMDIM3					as measurement_3
  , mitmas.MMSPE1					as specification_1
  , mitmas.MMSPE2					as specification_2
  , mitmas.MMSPE3					as specification_3
  , mitmas.MMSPE4					as specification_4
  , mitmas.MMSPE5					as specification_5
  , mitmas.MMCETY					as lot_restricted_release
  , mitmas.MMSTCN					as storage_requirements
  , mitmas.MMSPAC					as storage_packaging
  , mitmas.MMTRPA					as transportation_packaging
  , mitmas.MMPROD					as manufacturer
  , mitmas.MMSMFI					as single_manufacturer
  , mitmas.MMTANK					as location_characteristic
  , mitmas.MMARPA					as repair_supplier
  , mitmas.MMARPR					as repair_planner
  , mitmas.MMAMPT					as repair_time
  , mitmas.MMAWDY					as repair_warranty_days
  , mitmas.MMNPTO					as tool_quantity
  , mitmas.MMMES1					as meter_1
  , mitmas.MMMES2					as meter_2
  , mitmas.MMMES3					as meter_3
  , mitmas.MMMES4					as meter_4
  , mitmas.MMMVA1					as meter_value_1
  , mitmas.MMMVA2					as meter_value_2
  , mitmas.MMMVA3					as meter_value_3
  , mitmas.MMMVA4					as meter_value_4
  , mitmas.MMPEQ1					as quantity_or_time_1
  , mitmas.MMPEQ2					as quantity_or_time_2
  , mitmas.MMPEQ3					as quantity_or_time_3
  , mitmas.MMPEQ4					as quantity_or_time_4
  , mitmas.MMPET1					as trigger_type_1
  , mitmas.MMPET2					as trigger_type_2
  , mitmas.MMPET3					as trigger_type_3
  , mitmas.MMPET4					as trigger_type_4
  , mitmas.MMMPGM					as maintenance_program
  , mitmas.MMORTY					as master_order_type
  , mitmas.MMPLCD					as master_planning_policy
  , mitmas.MMMAPL					as planner_maintenance
  , mitmas.MMTOHI					as tool_history
  , mitmas.MMTORE					as tool_allocation
  , mitmas.MMFEBA					as tool_reporting
  , mitmas.MMMAPN					as maintenance_planning
  , mitmas.MMDOID					as document_identity
  , mitmas.MMSEPR					as setup_price
  , mitmas.MMSTCS					as downtime_cost
  , mitmas.MMNESA					as next_shop_action_type
  , mitmas.MMNSUF					as next_service
  , mitmas.MMFCCM					as master_forecast_logic
  , mitmas.MMDPID					as master_period_frame
  , mitmas.MMCONC					as master_continuous_net_change
  , mitmas.MMPLMZ					as master_planning_horizon
  , mitmas.MMCCO1					as calculation_constant_1
  , mitmas.MMCCO2					as calculation_constant_2
  , mitmas.MMCCO3					as calculation_constant_3
  , mitmas.MMWADY					as manufacturer_warranty
  , mitmas.MMTBSR					as time_between_scheduled_shop_visits
  , mitmas.MMMBSR					as meter_scheduled_shop_visits
  , mitmas.MMTBUR					as unscheduled_removal_rate
  , mitmas.MMMBUR					as meter_unscheduled_removal_rate
  , mitmas.MMTBFR					as time_between_failure
  , mitmas.MMMBFR					as meter_failure
  , mitmas.MMAESC					as criticality_class
  , mitmas.MMAES2					as extended_range_twin_engine_operations
  , mitmas.MMAMOR					as maintenanceoverhaulrepair_class
  , mitmas.MMFUNC					as function_area
  , mitmas.MMSTNC					as standard_numbering_system
  , mitmas.MMDIRR					as dimensional_removal_rate
  , mitmas.MMMDIR					as meter_dimensioning_removal_rate
  , mitmas.MMSCGR					as master_service_level
  , mitmas.MMARR1					as removal_class
  , mitmas.MMAEQY					as extra_quantity
  , mitmas.MMLEAI					as internal_lead_time
  , mitmas.MMWAL1					as warranty_limit_1
  , mitmas.MMWAL2					as warranty_limit_2
  , mitmas.MMWAL3					as warranty_limit_3
  , mitmas.MMWAL4					as warranty_limit_4
  , mitmas.MMIACP					as attribute_controlled_item
  , mitmas.MMHDPR					as main_product
  , mitmas.MMAAD0					as extended_qa_used
  , mitmas.MMAAD1					as generate_txt_from_text_template
  , mitmas.MMCHCL					as charge_calculation
  , mitmas.MMITRC					as individual_item_tracing
  , mitmas.MMVTCP					as master_vat_code_purchase
  , mitmas.MMVTCS					as master_vat_code_sales
  , mitmas.MMRGDT					as master_entry_date
  , mitmas.MMRGTM					as master_entry_time
  , mitmas.MMLMDT					as master_change_date
  , mitmas.MMCHNO					as master_change_number
  , mitmas.MMCHID					as master_changed_by
  , mitmas.MMLMTS					as master_timestamp
  , mitmas.MMATNR					as attribute_number
  , mitmas.MMNMIT					as non_material_type
  , mitmas.MMTECR					as core_terms
  , mitmas.MMEXCA					as exchangeable
  , mitmas.MMCAWP					as location_based_catch_weight
  , mitmas.MMCWUN					as catch_weight_unit_of_measure
  , mitmas.MMCPUN					as cost_unit_of_measure
  , mitwhl.MWCONO					as company_whl
  , mitwhl.MWWHLO					as warehouse_whl
  , mitwhl.MWWHNM					as description_whl
  , mitwhl.MWDIVI					as division_whl
  , mitwhl.MWFACI					as facility_whl
  , mitwhl.MWWHTY					as warehouse_type_whl
  , mitwhl.MWWHSY					as warehouse_subtype_whl
  , mitwhl.MWWHPL					as place_whl
  , mitwhl.MWOREF					as our_reference_whl
  , mitwhl.MWPHNO					as telephone_number_1_whl
  , mitwhl.MWCOMA					as communication_address_whl
  , mitwhl.MWCUNO					as customer_whl
  , mitwhl.MWSUNO					as supplier_whl
  , mitwhl.MWSDES					as place_of_loading_whl
  , mitwhl.MWSHNM					as consignor_whl
  , mitwhl.MWPLIS					as place_of_export_whl
  , mitwhl.MWCSCD					as country_whl
  , mitwhl.MWECAR					as state_whl
  , mitwhl.MWVRNO					as vat_registration_number_whl
  , mitwhl.MWLNCD					as language_whl
  , mitwhl.MWCPWH					as copy_from_warehouse_whl
  , mitwhl.MWAUAD					as automatic_add_permitted_whl
  , mitwhl.MWALWH					as alias_warehouse_whl
  , mitwhl.MWALAC					as display_alias_no_for_physical_inventory_whl
  , mitwhl.MWRESP					as responsible_whl
  , mitwhl.MWTWSL					as location_whl
  , mitwhl.MWGEOC					as geographical_code_whl
  , mitwhl.MWTAXC					as tax_code_customeraddress_whl
  , mitwhl.MWUNST					as separation_number_whl
  , mitwhl.MWTXID					as text_identity_whl
  , mitwhl.MWDTID					as data_identity_whl
  , mitwhl.MWAASQ					as automatic_allocation_sequence_whl
  , mitwhl.MWDMF0					as demand_time_fence_0_whl
  , mitwhl.MWDMF1					as demand_time_fence_1_whl
  , mitwhl.MWDMF2					as demand_time_fence_2_whl
  , mitwhl.MWDMF3					as demand_time_fence_3_whl
  , mitwhl.MWDMF4					as demand_time_fence_4_whl
  , mitwhl.MWDMF5					as demand_time_fence_5_whl
  , mitwhl.MWDMF6					as demand_time_fence_6_whl
  , mitwhl.MWDMF7					as demand_time_fence_7_whl
  , mitwhl.MWDMF8					as demand_time_fence_8_whl
  , mitwhl.MWDMF9					as demand_time_fence_9_whl
  , mitwhl.MWINUL					as retrieve_stock_transactions_whl
  , mitwhl.MWEPUL					as retrieve_receiptpicklist_whl
  , mitwhl.MWEXDL					as send_planned_receipts_whl
  , mitwhl.MWPIDL					as send_picking_lists_whl
  , mitwhl.MWALWQ					as alias_qualifier_whl
  , mitwhl.MWITDL					as send_item_master_whl
  , mitwhl.MWCDYN					as cross_dock_whl
  , mitwhl.MWPATF					as planned_cross_dock_time_fence_days_whl
  , mitwhl.MWPAHF					as planned_cross_dock_time_fence_hours_whl
  , mitwhl.MWPMTF					as opportunity_cd_time_fence_days_whl
  , mitwhl.MWPMHF					as opportunity_cd_time_fence_hours_whl
  , mitwhl.MWDDLO					as default_docking_location_whl
  , mitwhl.MWCDPD					as pack_or_dock_location_whl
  , mitwhl.MWCDPM					as display_cross_dock_result_whl
  , mitwhl.MWCALV					as calendar_version_whl
  , mitwhl.MWACGR					as object_access_group_whl
  , mitwhl.MWNBID					as number_series_whl
  , mitwhl.MWSTOF					as shop_information_whl
  , mitwhl.MWASOT					as allocation_stop_type_whl
  , mitwhl.MWDAAS					as number_of_days_for_allocation_stop_type_whl
  , mitwhl.MWLEAM					as allocation_time_fence_whl
  , mitwhl.MWDMFC					as demand_time_fence_type_whl
  , mitwhl.MWLSPM					as location_selection_prompt_whl
  , mitwhl.MWRSTN					as store_id_whl
  , mitwhl.MWRGDT					as entry_date_whl
  , mitwhl.MWRGTM					as entry_time_whl
  , mitwhl.MWLMDT					as change_date_whl
  , mitwhl.MWCHNO					as change_number_whl
  , mitwhl.MWCHID					as changed_by_whl
  , mitwhl.MWLMTS					as timestamp_whl
  , mitwhl.MWCPTE					as cpy_templ_item_whl
  , mitwhl.MWSCED					as delivery_regrouping_whl
  , mitwhl.MWGEOX					as geographic_code_x_whl
  , mitwhl.MWGEOY					as geographic_code_y_whl
  , mitwhl.MWGEOZ					as geographic_code_z_whl
  , prod.[ProductName]				as product_name
  , prod.[ProductCategoryBaseLevel] as product_category_base_level
  , prod.[ProductCategoryLevel1]	as product_category_level_1
  , prod.[ProductCategoryLevel2]	as product_category_level_2
  , prod.[ProductCategoryLevel3]	as product_category_level_3
  , prod.[ProductCategoryLevel4]	as product_category_level_4
  , prod.[ProductCategoryLevel5]	as product_category_level_5
from
	[psa].[ics_stg_M3V10vil_POL_MITLOC]		  as mitloc
left join [psa].[ics_stg_M3V10vil_POL_MITAUN] as mitaun
	on mitaun.MUITNO = mitloc.MLITNO
left join [psa].[ics_stg_M3V10vil_POL_MITMAS] as mitmas
	on mitmas.MMITNO = mitloc.MLITNO
left join tsa.ics_land_M3V10vil_POL_MITWHL	  as mitwhl
	on mitwhl.MWWHLO = mitloc.MLWHLO
left join qvstg.Product						  as prod
	on prod.NativeProductKey = mitloc.MLITNO
union all
select
	mitloc.MLACUQ					as cumulative_usage_quantity
  , mitloc.MLACUW					as cumulative_usage_weight
  , mitloc.MLADJW					as adjusted_weight
  , mitloc.MLALOC					as allocatable
  , mitloc.MLALQT					as allocated_quantity_basic_um
  , mitloc.MLATNR					as attribute_number
  , mitloc.MLATV1					as attribute_value_1
  , mitloc.MLATV2					as attribute_value_2
  , mitloc.MLATV3					as attribute_value_3
  , mitloc.MLATV4					as attribute_value_4
  , mitloc.MLATV5					as attribute_value_5
  , mitloc.MLAUDD					as automatic_deletion_delay
  , mitloc.MLAUDE					as automatic_deletion
  , mitloc.MLBANO					as lot_number
  , mitloc.MLBRE2					as lot_reference_2
  , mitloc.MLBREF					as lot_reference_1
  , mitloc.MLBREM					as remark
  , mitloc.MLCAMU					as container
  , mitloc.MLCANB					as cost_attribute_number
  , mitloc.MLCAWE					as catch_weight
  , mitloc.MLCHID					as changed_by
  , mitloc.MLCHNO					as change_number
  , mitloc.MLCNDT					as follow_up_date
  , mitloc.MLCONO					as company
  , mitloc.MLDTID					as data_identity
  , mitloc.MLFACI					as facility
  , mitloc.MLFIFL					as completion_flag
  , mitloc.MLIDDT					as last_receipt_date
  , mitloc.MLINCW					as initial_catch_weight
  , mitloc.MLINDT					as latest_physical_inventory_date
  , mitloc.MLINON					as physical_inventory_in_progress
  , mitloc.MLINVC					as physical_inventory_candidate
  , mitloc.MLIQTY					as initial_quantity
  , mitloc.MLITNO					as item_number
  , mitloc.MLLMDT					as change_date
  , mitloc.MLLMTS					as timestamp
  , mitloc.MLODDT					as last_issue_date
  , mitloc.MLOPAN					as outer_package_number
  , mitloc.MLPACT					as packaging
  , mitloc.MLPLQT					as picking_list_quantity_basic_um
  , mitloc.MLPOCY					as normal_potency
  , mitloc.MLPPRI					as picking_priority
  , mitloc.MLPRDT					as priority_date
  , mitloc.MLPUAB					as put_away_possible
  , mitloc.MLRCLN					as reclassification_number
  , mitloc.MLRCLS					as planned_reclassification_date
  , mitloc.MLREPN					as receiving_number
  , mitloc.MLRGDT					as entry_date
  , mitloc.MLRGTM					as entry_time
  , mitloc.MLSEDT					as sales_date
  , mitloc.MLSLTP					as stock_zone
  , mitloc.MLSTAS					as status_balance_id
  , mitloc.MLSTES					as sample_test
  , mitloc.MLSTNB					as physical_inventory_number
  , mitloc.MLSTQM					as on_hand_balance_main_um
  , mitloc.MLSTQT					as on_hand_balance_approved
  , mitloc.MLTXID					as text_identity
  , mitloc.MLWHLO					as warehouse
  , mitloc.MLWHLT					as location_type
  , mitloc.MLWHSL					as location
  , mitaun.MUCONO					as uom_company
  , mitaun.MUITNO					as uom_item_number
  , mitaun.MUAUTP					as uom_alternate_um_type
  , mitaun.MUALUN					as uom_alternate_um
  , mitaun.MUDCCD					as uom_number_of_decimal_places
  , mitaun.MUCOFA					as uom_conversion_factor
  , mitaun.MUDMCF					as uom_conversion_form
  , mitaun.MUPCOF					as uom_price_adjustment_factor
  , mitaun.MUAUS1					as uom_standard_um_purchase_order
  , mitaun.MUAUS2					as uom_standard_um_customer_order_sales
  , mitaun.MUAUS3					as uom_standard_um_manufacturing
  , mitaun.MUAUS4					as uom_standard_um_production_engineering
  , mitaun.MUAUS5					as uom_standard_um_purchase_price
  , mitaun.MUAUS6					as uom_standard_um_statistics
  , mitaun.MUAUS9					as uom_standard_um_sales_price
  , mitaun.MUUNMU					as uom_order_multiple
  , mitaun.MUFMID					as uom_formula
  , mitaun.MURESI					as uom_result_identity
  , mitaun.MUTXID					as uom_text_identity
  , mitaun.MURGDT					as uom_entry_date
  , mitaun.MURGTM					as uom_entry_time
  , mitaun.MULMDT					as uom_change_date
  , mitaun.MUCHNO					as uom_change_number
  , mitaun.MUCHID					as uom_changed_by
  , mitaun.MULMTS					as uom_timestamp
  , mitaun.MUPACT					as uom_packaging
  , mitaun.MUAUSC					as uom_standard_um_catch_weight
  , mitaun.MUAUSB					as uom_standard_um_cost
  , mitmas.MMCONO					as master_company
  , mitmas.MMSTAT					as master_status
  , mitmas.MMITNO					as master_item_number
  , mitmas.MMITDS					as master_name
  , mitmas.MMFUDS					as master_description_2
  , mitmas.MMDWNO					as master_drawing_number
  , mitmas.MMRESP					as master_responsible
  , mitmas.MMDCCD					as master_number_of_decimal_places
  , mitmas.MMUNMS					as master_basic_unit_of_measure
  , mitmas.MMITGR					as master_item_group
  , mitmas.MMITCL					as master_product_group
  , mitmas.MMBUAR					as master_business_area
  , mitmas.MMEVGR					as master_environment_group
  , mitmas.MMITTY					as master_item_type
  , mitmas.MMTPCD					as master_item_category
  , mitmas.MMMABU					as makebuy_code
  , mitmas.MMCHCD					as configuration_code
  , mitmas.MMSTCD					as inventory_accounting
  , mitmas.MMBACD					as lot_numbering_method
  , mitmas.MMVOL3					as volume
  , mitmas.MMNEWE					as net_weight
  , mitmas.MMGRWE					as gross_weight
  , mitmas.MMPPUN					as purchase_price_um
  , mitmas.MMBYPR					as byco_product_code
  , mitmas.MMWAPC					as normal_waste_percentage
  , mitmas.MMQACD					as inspection_code
  , mitmas.MMEPCD					as yield_calculation
  , mitmas.MMPOCY					as normal_potency
  , mitmas.MMACTI					as active_or_catch_weight_item
  , mitmas.MMHIE1					as hierarchy_level_1
  , mitmas.MMHIE2					as hierarchy_level_2
  , mitmas.MMHIE3					as hierarchy_level_3
  , mitmas.MMHIE4					as hierarchy_level_4
  , mitmas.MMHIE5					as hierarchy_level_5
  , mitmas.MMGRP1					as search_group_1
  , mitmas.MMGRP2					as search_group_2
  , mitmas.MMGRP3					as search_group_3
  , mitmas.MMGRP4					as search_group_4
  , mitmas.MMGRP5					as search_group_5
  , mitmas.MMCFI1					as user_defined_field_1_item
  , mitmas.MMCFI2					as user_defined_field_2_item
  , mitmas.MMCFI3					as user_defined_field_3_item
  , mitmas.MMCFI4					as user_defined_field_4_item
  , mitmas.MMCFI5					as user_defined_field_5_item
  , mitmas.MMECCC					as consumption_code_trade_stat_tst
  , mitmas.MMTXID					as master_text_identity
  , mitmas.MMDTID					as master_data_identity
  , mitmas.MMECVE					as revision_number
  , mitmas.MMECAC					as engineering_change_order_type
  , mitmas.MMECMA					as eco_managed
  , mitmas.MMECFL					as active_engineering_changes
  , mitmas.MMWSCA					as costing_model
  , mitmas.MMPRGP					as procurement_group
  , mitmas.MMETRF					as external_instruction
  , mitmas.MMACRF					as user_defined_accounting_control_object
  , mitmas.MMINDI					as lot_control_method
  , mitmas.MMPUUN					as purchase_order_um
  , mitmas.MMAUTC					as issue_message
  , mitmas.MMALUC					as alternate_um_in_use
  , mitmas.MMPDCC					as number_of_price_decimal_places
  , mitmas.MMIEAA					as item_exists_as_alias_identity
  , mitmas.MMRIDE					as reference_identity
  , mitmas.MMRIDC					as reference_identity_code
  , mitmas.MMGRTI					as group_technology_class
  , mitmas.MMGRTS					as master_distribution_group_technology
  , mitmas.MMEXPD					as expiration_date_method
  , mitmas.MMITRF					as internal_instruction
  , mitmas.MMPRCM					as costing_model_product_costing
  , mitmas.MMGRMT					as goods_receiving_method
  , mitmas.MMHAZI					as danger_indicator
  , mitmas.MMSALE					as sales_item
  , mitmas.MMFRAG					as fragility
  , mitmas.MMTAXC					as tax_code_customeraddress
  , mitmas.MMATMO					as attribute_model
  , mitmas.MMATMN					as attribute_managed
  , mitmas.MMTPLI					as template_item_number
  , mitmas.MMFCU1					as capacity_free_capacity_unit
  , mitmas.MMSUNO					as master_supplier
  , mitmas.MMPUPR					as purchase_price
  , mitmas.MMPUCD					as purchase_price_quantity
  , mitmas.MMCUCD					as currency
  , mitmas.MMPPDT					as purchase_price_date
  , mitmas.MMSAPR					as sales_price
  , mitmas.MMSTUN					as statistical_um
  , mitmas.MMSACD					as sales_price_quantity
  , mitmas.MMCUCS					as currency_sales_price
  , mitmas.MMSPDT					as sales_price_date
  , mitmas.MMDIGI					as discount_group_item
  , mitmas.MMBGRP					as bonus_group
  , mitmas.MMPRVG					as commission_group
  , mitmas.MMFRE3					as statistics_identity_3_item
  , mitmas.MMFRE4					as statistics_identity_4_item
  , mitmas.MMOTDI					as order_total_discount_generating
  , mitmas.MMBOGR					as bonus_generating
  , mitmas.MMPRGR					as commission_generating
  , mitmas.MMLAMA					as minimum_accepted_contributn_margin_ratio
  , mitmas.MMACHK					as assortment_check
  , mitmas.MMBPEY					as update_buying_pattern
  , mitmas.MMSPUN					as sales_price_unit_of_measure
  , mitmas.MMSPUC					as fixed_or_dynamic_sales_price_um
  , mitmas.MMALUN					as master_alternate_um
  , mitmas.MMUNNN					as un_number
  , mitmas.MMUNPA					as un_pack_code
  , mitmas.MMHAC1					as danger_class_1
  , mitmas.MMHAC2					as danger_class_2
  , mitmas.MMHAC3					as danger_class_3
  , mitmas.MMDIM1					as measurement_1
  , mitmas.MMDIM2					as measurement_2
  , mitmas.MMDIM3					as measurement_3
  , mitmas.MMSPE1					as specification_1
  , mitmas.MMSPE2					as specification_2
  , mitmas.MMSPE3					as specification_3
  , mitmas.MMSPE4					as specification_4
  , mitmas.MMSPE5					as specification_5
  , mitmas.MMCETY					as lot_restricted_release
  , mitmas.MMSTCN					as storage_requirements
  , mitmas.MMSPAC					as storage_packaging
  , mitmas.MMTRPA					as transportation_packaging
  , mitmas.MMPROD					as manufacturer
  , mitmas.MMSMFI					as single_manufacturer
  , mitmas.MMTANK					as location_characteristic
  , mitmas.MMARPA					as repair_supplier
  , mitmas.MMARPR					as repair_planner
  , mitmas.MMAMPT					as repair_time
  , mitmas.MMAWDY					as repair_warranty_days
  , mitmas.MMNPTO					as tool_quantity
  , mitmas.MMMES1					as meter_1
  , mitmas.MMMES2					as meter_2
  , mitmas.MMMES3					as meter_3
  , mitmas.MMMES4					as meter_4
  , mitmas.MMMVA1					as meter_value_1
  , mitmas.MMMVA2					as meter_value_2
  , mitmas.MMMVA3					as meter_value_3
  , mitmas.MMMVA4					as meter_value_4
  , mitmas.MMPEQ1					as quantity_or_time_1
  , mitmas.MMPEQ2					as quantity_or_time_2
  , mitmas.MMPEQ3					as quantity_or_time_3
  , mitmas.MMPEQ4					as quantity_or_time_4
  , mitmas.MMPET1					as trigger_type_1
  , mitmas.MMPET2					as trigger_type_2
  , mitmas.MMPET3					as trigger_type_3
  , mitmas.MMPET4					as trigger_type_4
  , mitmas.MMMPGM					as maintenance_program
  , mitmas.MMORTY					as master_order_type
  , mitmas.MMPLCD					as master_planning_policy
  , mitmas.MMMAPL					as planner_maintenance
  , mitmas.MMTOHI					as tool_history
  , mitmas.MMTORE					as tool_allocation
  , mitmas.MMFEBA					as tool_reporting
  , mitmas.MMMAPN					as maintenance_planning
  , mitmas.MMDOID					as document_identity
  , mitmas.MMSEPR					as setup_price
  , mitmas.MMSTCS					as downtime_cost
  , mitmas.MMNESA					as next_shop_action_type
  , mitmas.MMNSUF					as next_service
  , mitmas.MMFCCM					as master_forecast_logic
  , mitmas.MMDPID					as master_period_frame
  , mitmas.MMCONC					as master_continuous_net_change
  , mitmas.MMPLMZ					as master_planning_horizon
  , mitmas.MMCCO1					as calculation_constant_1
  , mitmas.MMCCO2					as calculation_constant_2
  , mitmas.MMCCO3					as calculation_constant_3
  , mitmas.MMWADY					as manufacturer_warranty
  , mitmas.MMTBSR					as time_between_scheduled_shop_visits
  , mitmas.MMMBSR					as meter_scheduled_shop_visits
  , mitmas.MMTBUR					as unscheduled_removal_rate
  , mitmas.MMMBUR					as meter_unscheduled_removal_rate
  , mitmas.MMTBFR					as time_between_failure
  , mitmas.MMMBFR					as meter_failure
  , mitmas.MMAESC					as criticality_class
  , mitmas.MMAES2					as extended_range_twin_engine_operations
  , mitmas.MMAMOR					as maintenanceoverhaulrepair_class
  , mitmas.MMFUNC					as function_area
  , mitmas.MMSTNC					as standard_numbering_system
  , mitmas.MMDIRR					as dimensional_removal_rate
  , mitmas.MMMDIR					as meter_dimensioning_removal_rate
  , mitmas.MMSCGR					as master_service_level
  , mitmas.MMARR1					as removal_class
  , mitmas.MMAEQY					as extra_quantity
  , mitmas.MMLEAI					as internal_lead_time
  , mitmas.MMWAL1					as warranty_limit_1
  , mitmas.MMWAL2					as warranty_limit_2
  , mitmas.MMWAL3					as warranty_limit_3
  , mitmas.MMWAL4					as warranty_limit_4
  , mitmas.MMIACP					as attribute_controlled_item
  , mitmas.MMHDPR					as main_product
  , mitmas.MMAAD0					as extended_qa_used
  , mitmas.MMAAD1					as generate_txt_from_text_template
  , mitmas.MMCHCL					as charge_calculation
  , mitmas.MMITRC					as individual_item_tracing
  , mitmas.MMVTCP					as master_vat_code_purchase
  , mitmas.MMVTCS					as master_vat_code_sales
  , mitmas.MMRGDT					as master_entry_date
  , mitmas.MMRGTM					as master_entry_time
  , mitmas.MMLMDT					as master_change_date
  , mitmas.MMCHNO					as master_change_number
  , mitmas.MMCHID					as master_changed_by
  , mitmas.MMLMTS					as master_timestamp
  , mitmas.MMATNR					as attribute_number
  , mitmas.MMNMIT					as non_material_type
  , mitmas.MMTECR					as core_terms
  , mitmas.MMEXCA					as exchangeable
  , mitmas.MMCAWP					as location_based_catch_weight
  , mitmas.MMCWUN					as catch_weight_unit_of_measure
  , mitmas.MMCPUN					as cost_unit_of_measure
  , mitwhl.MWCONO					as company_whl
  , mitwhl.MWWHLO					as warehouse_whl
  , mitwhl.MWWHNM					as description_whl
  , mitwhl.MWDIVI					as division_whl
  , mitwhl.MWFACI					as facility_whl
  , mitwhl.MWWHTY					as warehouse_type_whl
  , mitwhl.MWWHSY					as warehouse_subtype_whl
  , mitwhl.MWWHPL					as place_whl
  , mitwhl.MWOREF					as our_reference_whl
  , mitwhl.MWPHNO					as telephone_number_1_whl
  , mitwhl.MWCOMA					as communication_address_whl
  , mitwhl.MWCUNO					as customer_whl
  , mitwhl.MWSUNO					as supplier_whl
  , mitwhl.MWSDES					as place_of_loading_whl
  , mitwhl.MWSHNM					as consignor_whl
  , mitwhl.MWPLIS					as place_of_export_whl
  , mitwhl.MWCSCD					as country_whl
  , mitwhl.MWECAR					as state_whl
  , mitwhl.MWVRNO					as vat_registration_number_whl
  , mitwhl.MWLNCD					as language_whl
  , mitwhl.MWCPWH					as copy_from_warehouse_whl
  , mitwhl.MWAUAD					as automatic_add_permitted_whl
  , mitwhl.MWALWH					as alias_warehouse_whl
  , mitwhl.MWALAC					as display_alias_no_for_physical_inventory_whl
  , mitwhl.MWRESP					as responsible_whl
  , mitwhl.MWTWSL					as location_whl
  , mitwhl.MWGEOC					as geographical_code_whl
  , mitwhl.MWTAXC					as tax_code_customeraddress_whl
  , mitwhl.MWUNST					as separation_number_whl
  , mitwhl.MWTXID					as text_identity_whl
  , mitwhl.MWDTID					as data_identity_whl
  , mitwhl.MWAASQ					as automatic_allocation_sequence_whl
  , mitwhl.MWDMF0					as demand_time_fence_0_whl
  , mitwhl.MWDMF1					as demand_time_fence_1_whl
  , mitwhl.MWDMF2					as demand_time_fence_2_whl
  , mitwhl.MWDMF3					as demand_time_fence_3_whl
  , mitwhl.MWDMF4					as demand_time_fence_4_whl
  , mitwhl.MWDMF5					as demand_time_fence_5_whl
  , mitwhl.MWDMF6					as demand_time_fence_6_whl
  , mitwhl.MWDMF7					as demand_time_fence_7_whl
  , mitwhl.MWDMF8					as demand_time_fence_8_whl
  , mitwhl.MWDMF9					as demand_time_fence_9_whl
  , mitwhl.MWINUL					as retrieve_stock_transactions_whl
  , mitwhl.MWEPUL					as retrieve_receiptpicklist_whl
  , mitwhl.MWEXDL					as send_planned_receipts_whl
  , mitwhl.MWPIDL					as send_picking_lists_whl
  , mitwhl.MWALWQ					as alias_qualifier_whl
  , mitwhl.MWITDL					as send_item_master_whl
  , mitwhl.MWCDYN					as cross_dock_whl
  , mitwhl.MWPATF					as planned_cross_dock_time_fence_days_whl
  , mitwhl.MWPAHF					as planned_cross_dock_time_fence_hours_whl
  , mitwhl.MWPMTF					as opportunity_cd_time_fence_days_whl
  , mitwhl.MWPMHF					as opportunity_cd_time_fence_hours_whl
  , mitwhl.MWDDLO					as default_docking_location_whl
  , mitwhl.MWCDPD					as pack_or_dock_location_whl
  , mitwhl.MWCDPM					as display_cross_dock_result_whl
  , mitwhl.MWCALV					as calendar_version_whl
  , mitwhl.MWACGR					as object_access_group_whl
  , mitwhl.MWNBID					as number_series_whl
  , mitwhl.MWSTOF					as shop_information_whl
  , mitwhl.MWASOT					as allocation_stop_type_whl
  , mitwhl.MWDAAS					as number_of_days_for_allocation_stop_type_whl
  , mitwhl.MWLEAM					as allocation_time_fence_whl
  , mitwhl.MWDMFC					as demand_time_fence_type_whl
  , mitwhl.MWLSPM					as location_selection_prompt_whl
  , mitwhl.MWRSTN					as store_id_whl
  , mitwhl.MWRGDT					as entry_date_whl
  , mitwhl.MWRGTM					as entry_time_whl
  , mitwhl.MWLMDT					as change_date_whl
  , mitwhl.MWCHNO					as change_number_whl
  , mitwhl.MWCHID					as changed_by_whl
  , mitwhl.MWLMTS					as timestamp_whl
  , mitwhl.MWCPTE					as cpy_templ_item_whl
  , mitwhl.MWSCED					as delivery_regrouping_whl
  , mitwhl.MWGEOX					as geographic_code_x_whl
  , mitwhl.MWGEOY					as geographic_code_y_whl
  , mitwhl.MWGEOZ					as geographic_code_z_whl
  , prod.[ProductName]				as product_name
  , prod.[ProductCategoryBaseLevel] as product_category_base_level
  , prod.[ProductCategoryLevel1]	as product_category_level_1
  , prod.[ProductCategoryLevel2]	as product_category_level_2
  , prod.[ProductCategoryLevel3]	as product_category_level_3
  , prod.[ProductCategoryLevel4]	as product_category_level_4
  , prod.[ProductCategoryLevel5]	as product_category_level_5
from
	[psa].[ics_stg_M3V10gen_POL_MITLOC]		  as mitloc
left join [psa].[ics_stg_M3V10gen_POL_MITAUN] as mitaun
	on mitaun.MUITNO = mitloc.MLITNO
left join [psa].[ics_stg_M3V10gen_POL_MITMAS] as mitmas
	on mitmas.MMITNO = mitloc.MLITNO
left join tsa.ics_land_M3V10gen_POL_MITWHL	  as mitwhl
	on mitwhl.MWWHLO = mitloc.MLWHLO
left join qvstg.Product						  as prod
	on prod.NativeProductKey = mitloc.MLITNO
union all
select
	mitloc.MLACUQ					as cumulative_usage_quantity
  , mitloc.MLACUW					as cumulative_usage_weight
  , mitloc.MLADJW					as adjusted_weight
  , mitloc.MLALOC					as allocatable
  , mitloc.MLALQT					as allocated_quantity_basic_um
  , mitloc.MLATNR					as attribute_number
  , mitloc.MLATV1					as attribute_value_1
  , mitloc.MLATV2					as attribute_value_2
  , mitloc.MLATV3					as attribute_value_3
  , mitloc.MLATV4					as attribute_value_4
  , mitloc.MLATV5					as attribute_value_5
  , mitloc.MLAUDD					as automatic_deletion_delay
  , mitloc.MLAUDE					as automatic_deletion
  , mitloc.MLBANO					as lot_number
  , mitloc.MLBRE2					as lot_reference_2
  , mitloc.MLBREF					as lot_reference_1
  , mitloc.MLBREM					as remark
  , mitloc.MLCAMU					as container
  , mitloc.MLCANB					as cost_attribute_number
  , mitloc.MLCAWE					as catch_weight
  , mitloc.MLCHID					as changed_by
  , mitloc.MLCHNO					as change_number
  , mitloc.MLCNDT					as follow_up_date
  , mitloc.MLCONO					as company
  , mitloc.MLDTID					as data_identity
  , mitloc.MLFACI					as facility
  , mitloc.MLFIFL					as completion_flag
  , mitloc.MLIDDT					as last_receipt_date
  , mitloc.MLINCW					as initial_catch_weight
  , mitloc.MLINDT					as latest_physical_inventory_date
  , mitloc.MLINON					as physical_inventory_in_progress
  , mitloc.MLINVC					as physical_inventory_candidate
  , mitloc.MLIQTY					as initial_quantity
  , mitloc.MLITNO					as item_number
  , mitloc.MLLMDT					as change_date
  , mitloc.MLLMTS					as timestamp
  , mitloc.MLODDT					as last_issue_date
  , mitloc.MLOPAN					as outer_package_number
  , mitloc.MLPACT					as packaging
  , mitloc.MLPLQT					as picking_list_quantity_basic_um
  , mitloc.MLPOCY					as normal_potency
  , mitloc.MLPPRI					as picking_priority
  , mitloc.MLPRDT					as priority_date
  , mitloc.MLPUAB					as put_away_possible
  , mitloc.MLRCLN					as reclassification_number
  , mitloc.MLRCLS					as planned_reclassification_date
  , mitloc.MLREPN					as receiving_number
  , mitloc.MLRGDT					as entry_date
  , mitloc.MLRGTM					as entry_time
  , mitloc.MLSEDT					as sales_date
  , mitloc.MLSLTP					as stock_zone
  , mitloc.MLSTAS					as status_balance_id
  , mitloc.MLSTES					as sample_test
  , mitloc.MLSTNB					as physical_inventory_number
  , mitloc.MLSTQM					as on_hand_balance_main_um
  , mitloc.MLSTQT					as on_hand_balance_approved
  , mitloc.MLTXID					as text_identity
  , mitloc.MLWHLO					as warehouse
  , mitloc.MLWHLT					as location_type
  , mitloc.MLWHSL					as location
  , mitaun.MUCONO					as uom_company
  , mitaun.MUITNO					as uom_item_number
  , mitaun.MUAUTP					as uom_alternate_um_type
  , mitaun.MUALUN					as uom_alternate_um
  , mitaun.MUDCCD					as uom_number_of_decimal_places
  , mitaun.MUCOFA					as uom_conversion_factor
  , mitaun.MUDMCF					as uom_conversion_form
  , mitaun.MUPCOF					as uom_price_adjustment_factor
  , mitaun.MUAUS1					as uom_standard_um_purchase_order
  , mitaun.MUAUS2					as uom_standard_um_customer_order_sales
  , mitaun.MUAUS3					as uom_standard_um_manufacturing
  , mitaun.MUAUS4					as uom_standard_um_production_engineering
  , mitaun.MUAUS5					as uom_standard_um_purchase_price
  , mitaun.MUAUS6					as uom_standard_um_statistics
  , mitaun.MUAUS9					as uom_standard_um_sales_price
  , mitaun.MUUNMU					as uom_order_multiple
  , mitaun.MUFMID					as uom_formula
  , mitaun.MURESI					as uom_result_identity
  , mitaun.MUTXID					as uom_text_identity
  , mitaun.MURGDT					as uom_entry_date
  , mitaun.MURGTM					as uom_entry_time
  , mitaun.MULMDT					as uom_change_date
  , mitaun.MUCHNO					as uom_change_number
  , mitaun.MUCHID					as uom_changed_by
  , mitaun.MULMTS					as uom_timestamp
  , mitaun.MUPACT					as uom_packaging
  , mitaun.MUAUSC					as uom_standard_um_catch_weight
  , mitaun.MUAUSB					as uom_standard_um_cost
  , mitmas.MMCONO					as master_company
  , mitmas.MMSTAT					as master_status
  , mitmas.MMITNO					as master_item_number
  , mitmas.MMITDS					as master_name
  , mitmas.MMFUDS					as master_description_2
  , mitmas.MMDWNO					as master_drawing_number
  , mitmas.MMRESP					as master_responsible
  , mitmas.MMDCCD					as master_number_of_decimal_places
  , mitmas.MMUNMS					as master_basic_unit_of_measure
  , mitmas.MMITGR					as master_item_group
  , mitmas.MMITCL					as master_product_group
  , mitmas.MMBUAR					as master_business_area
  , mitmas.MMEVGR					as master_environment_group
  , mitmas.MMITTY					as master_item_type
  , mitmas.MMTPCD					as master_item_category
  , mitmas.MMMABU					as makebuy_code
  , mitmas.MMCHCD					as configuration_code
  , mitmas.MMSTCD					as inventory_accounting
  , mitmas.MMBACD					as lot_numbering_method
  , mitmas.MMVOL3					as volume
  , mitmas.MMNEWE					as net_weight
  , mitmas.MMGRWE					as gross_weight
  , mitmas.MMPPUN					as purchase_price_um
  , mitmas.MMBYPR					as byco_product_code
  , mitmas.MMWAPC					as normal_waste_percentage
  , mitmas.MMQACD					as inspection_code
  , mitmas.MMEPCD					as yield_calculation
  , mitmas.MMPOCY					as normal_potency
  , mitmas.MMACTI					as active_or_catch_weight_item
  , mitmas.MMHIE1					as hierarchy_level_1
  , mitmas.MMHIE2					as hierarchy_level_2
  , mitmas.MMHIE3					as hierarchy_level_3
  , mitmas.MMHIE4					as hierarchy_level_4
  , mitmas.MMHIE5					as hierarchy_level_5
  , mitmas.MMGRP1					as search_group_1
  , mitmas.MMGRP2					as search_group_2
  , mitmas.MMGRP3					as search_group_3
  , mitmas.MMGRP4					as search_group_4
  , mitmas.MMGRP5					as search_group_5
  , mitmas.MMCFI1					as user_defined_field_1_item
  , mitmas.MMCFI2					as user_defined_field_2_item
  , mitmas.MMCFI3					as user_defined_field_3_item
  , mitmas.MMCFI4					as user_defined_field_4_item
  , mitmas.MMCFI5					as user_defined_field_5_item
  , mitmas.MMECCC					as consumption_code_trade_stat_tst
  , mitmas.MMTXID					as master_text_identity
  , mitmas.MMDTID					as master_data_identity
  , mitmas.MMECVE					as revision_number
  , mitmas.MMECAC					as engineering_change_order_type
  , mitmas.MMECMA					as eco_managed
  , mitmas.MMECFL					as active_engineering_changes
  , mitmas.MMWSCA					as costing_model
  , mitmas.MMPRGP					as procurement_group
  , mitmas.MMETRF					as external_instruction
  , mitmas.MMACRF					as user_defined_accounting_control_object
  , mitmas.MMINDI					as lot_control_method
  , mitmas.MMPUUN					as purchase_order_um
  , mitmas.MMAUTC					as issue_message
  , mitmas.MMALUC					as alternate_um_in_use
  , mitmas.MMPDCC					as number_of_price_decimal_places
  , mitmas.MMIEAA					as item_exists_as_alias_identity
  , mitmas.MMRIDE					as reference_identity
  , mitmas.MMRIDC					as reference_identity_code
  , mitmas.MMGRTI					as group_technology_class
  , mitmas.MMGRTS					as master_distribution_group_technology
  , mitmas.MMEXPD					as expiration_date_method
  , mitmas.MMITRF					as internal_instruction
  , mitmas.MMPRCM					as costing_model_product_costing
  , mitmas.MMGRMT					as goods_receiving_method
  , mitmas.MMHAZI					as danger_indicator
  , mitmas.MMSALE					as sales_item
  , mitmas.MMFRAG					as fragility
  , mitmas.MMTAXC					as tax_code_customeraddress
  , mitmas.MMATMO					as attribute_model
  , mitmas.MMATMN					as attribute_managed
  , mitmas.MMTPLI					as template_item_number
  , mitmas.MMFCU1					as capacity_free_capacity_unit
  , mitmas.MMSUNO					as master_supplier
  , mitmas.MMPUPR					as purchase_price
  , mitmas.MMPUCD					as purchase_price_quantity
  , mitmas.MMCUCD					as currency
  , mitmas.MMPPDT					as purchase_price_date
  , mitmas.MMSAPR					as sales_price
  , mitmas.MMSTUN					as statistical_um
  , mitmas.MMSACD					as sales_price_quantity
  , mitmas.MMCUCS					as currency_sales_price
  , mitmas.MMSPDT					as sales_price_date
  , mitmas.MMDIGI					as discount_group_item
  , mitmas.MMBGRP					as bonus_group
  , mitmas.MMPRVG					as commission_group
  , mitmas.MMFRE3					as statistics_identity_3_item
  , mitmas.MMFRE4					as statistics_identity_4_item
  , mitmas.MMOTDI					as order_total_discount_generating
  , mitmas.MMBOGR					as bonus_generating
  , mitmas.MMPRGR					as commission_generating
  , mitmas.MMLAMA					as minimum_accepted_contributn_margin_ratio
  , mitmas.MMACHK					as assortment_check
  , mitmas.MMBPEY					as update_buying_pattern
  , mitmas.MMSPUN					as sales_price_unit_of_measure
  , mitmas.MMSPUC					as fixed_or_dynamic_sales_price_um
  , mitmas.MMALUN					as master_alternate_um
  , mitmas.MMUNNN					as un_number
  , mitmas.MMUNPA					as un_pack_code
  , mitmas.MMHAC1					as danger_class_1
  , mitmas.MMHAC2					as danger_class_2
  , mitmas.MMHAC3					as danger_class_3
  , mitmas.MMDIM1					as measurement_1
  , mitmas.MMDIM2					as measurement_2
  , mitmas.MMDIM3					as measurement_3
  , mitmas.MMSPE1					as specification_1
  , mitmas.MMSPE2					as specification_2
  , mitmas.MMSPE3					as specification_3
  , mitmas.MMSPE4					as specification_4
  , mitmas.MMSPE5					as specification_5
  , mitmas.MMCETY					as lot_restricted_release
  , mitmas.MMSTCN					as storage_requirements
  , mitmas.MMSPAC					as storage_packaging
  , mitmas.MMTRPA					as transportation_packaging
  , mitmas.MMPROD					as manufacturer
  , mitmas.MMSMFI					as single_manufacturer
  , mitmas.MMTANK					as location_characteristic
  , mitmas.MMARPA					as repair_supplier
  , mitmas.MMARPR					as repair_planner
  , mitmas.MMAMPT					as repair_time
  , mitmas.MMAWDY					as repair_warranty_days
  , mitmas.MMNPTO					as tool_quantity
  , mitmas.MMMES1					as meter_1
  , mitmas.MMMES2					as meter_2
  , mitmas.MMMES3					as meter_3
  , mitmas.MMMES4					as meter_4
  , mitmas.MMMVA1					as meter_value_1
  , mitmas.MMMVA2					as meter_value_2
  , mitmas.MMMVA3					as meter_value_3
  , mitmas.MMMVA4					as meter_value_4
  , mitmas.MMPEQ1					as quantity_or_time_1
  , mitmas.MMPEQ2					as quantity_or_time_2
  , mitmas.MMPEQ3					as quantity_or_time_3
  , mitmas.MMPEQ4					as quantity_or_time_4
  , mitmas.MMPET1					as trigger_type_1
  , mitmas.MMPET2					as trigger_type_2
  , mitmas.MMPET3					as trigger_type_3
  , mitmas.MMPET4					as trigger_type_4
  , mitmas.MMMPGM					as maintenance_program
  , mitmas.MMORTY					as master_order_type
  , mitmas.MMPLCD					as master_planning_policy
  , mitmas.MMMAPL					as planner_maintenance
  , mitmas.MMTOHI					as tool_history
  , mitmas.MMTORE					as tool_allocation
  , mitmas.MMFEBA					as tool_reporting
  , mitmas.MMMAPN					as maintenance_planning
  , mitmas.MMDOID					as document_identity
  , mitmas.MMSEPR					as setup_price
  , mitmas.MMSTCS					as downtime_cost
  , mitmas.MMNESA					as next_shop_action_type
  , mitmas.MMNSUF					as next_service
  , mitmas.MMFCCM					as master_forecast_logic
  , mitmas.MMDPID					as master_period_frame
  , mitmas.MMCONC					as master_continuous_net_change
  , mitmas.MMPLMZ					as master_planning_horizon
  , mitmas.MMCCO1					as calculation_constant_1
  , mitmas.MMCCO2					as calculation_constant_2
  , mitmas.MMCCO3					as calculation_constant_3
  , mitmas.MMWADY					as manufacturer_warranty
  , mitmas.MMTBSR					as time_between_scheduled_shop_visits
  , mitmas.MMMBSR					as meter_scheduled_shop_visits
  , mitmas.MMTBUR					as unscheduled_removal_rate
  , mitmas.MMMBUR					as meter_unscheduled_removal_rate
  , mitmas.MMTBFR					as time_between_failure
  , mitmas.MMMBFR					as meter_failure
  , mitmas.MMAESC					as criticality_class
  , mitmas.MMAES2					as extended_range_twin_engine_operations
  , mitmas.MMAMOR					as maintenanceoverhaulrepair_class
  , mitmas.MMFUNC					as function_area
  , mitmas.MMSTNC					as standard_numbering_system
  , mitmas.MMDIRR					as dimensional_removal_rate
  , mitmas.MMMDIR					as meter_dimensioning_removal_rate
  , mitmas.MMSCGR					as master_service_level
  , mitmas.MMARR1					as removal_class
  , mitmas.MMAEQY					as extra_quantity
  , mitmas.MMLEAI					as internal_lead_time
  , mitmas.MMWAL1					as warranty_limit_1
  , mitmas.MMWAL2					as warranty_limit_2
  , mitmas.MMWAL3					as warranty_limit_3
  , mitmas.MMWAL4					as warranty_limit_4
  , mitmas.MMIACP					as attribute_controlled_item
  , mitmas.MMHDPR					as main_product
  , mitmas.MMAAD0					as extended_qa_used
  , mitmas.MMAAD1					as generate_txt_from_text_template
  , mitmas.MMCHCL					as charge_calculation
  , mitmas.MMITRC					as individual_item_tracing
  , mitmas.MMVTCP					as master_vat_code_purchase
  , mitmas.MMVTCS					as master_vat_code_sales
  , mitmas.MMRGDT					as master_entry_date
  , mitmas.MMRGTM					as master_entry_time
  , mitmas.MMLMDT					as master_change_date
  , mitmas.MMCHNO					as master_change_number
  , mitmas.MMCHID					as master_changed_by
  , mitmas.MMLMTS					as master_timestamp
  , mitmas.MMATNR					as attribute_number
  , mitmas.MMNMIT					as non_material_type
  , mitmas.MMTECR					as core_terms
  , mitmas.MMEXCA					as exchangeable
  , mitmas.MMCAWP					as location_based_catch_weight
  , mitmas.MMCWUN					as catch_weight_unit_of_measure
  , mitmas.MMCPUN					as cost_unit_of_measure
  , mitwhl.MWCONO					as company_whl
  , mitwhl.MWWHLO					as warehouse_whl
  , mitwhl.MWWHNM					as description_whl
  , mitwhl.MWDIVI					as division_whl
  , mitwhl.MWFACI					as facility_whl
  , mitwhl.MWWHTY					as warehouse_type_whl
  , mitwhl.MWWHSY					as warehouse_subtype_whl
  , mitwhl.MWWHPL					as place_whl
  , mitwhl.MWOREF					as our_reference_whl
  , mitwhl.MWPHNO					as telephone_number_1_whl
  , mitwhl.MWCOMA					as communication_address_whl
  , mitwhl.MWCUNO					as customer_whl
  , mitwhl.MWSUNO					as supplier_whl
  , mitwhl.MWSDES					as place_of_loading_whl
  , mitwhl.MWSHNM					as consignor_whl
  , mitwhl.MWPLIS					as place_of_export_whl
  , mitwhl.MWCSCD					as country_whl
  , mitwhl.MWECAR					as state_whl
  , mitwhl.MWVRNO					as vat_registration_number_whl
  , mitwhl.MWLNCD					as language_whl
  , mitwhl.MWCPWH					as copy_from_warehouse_whl
  , mitwhl.MWAUAD					as automatic_add_permitted_whl
  , mitwhl.MWALWH					as alias_warehouse_whl
  , mitwhl.MWALAC					as display_alias_no_for_physical_inventory_whl
  , mitwhl.MWRESP					as responsible_whl
  , mitwhl.MWTWSL					as location_whl
  , mitwhl.MWGEOC					as geographical_code_whl
  , mitwhl.MWTAXC					as tax_code_customeraddress_whl
  , mitwhl.MWUNST					as separation_number_whl
  , mitwhl.MWTXID					as text_identity_whl
  , mitwhl.MWDTID					as data_identity_whl
  , mitwhl.MWAASQ					as automatic_allocation_sequence_whl
  , mitwhl.MWDMF0					as demand_time_fence_0_whl
  , mitwhl.MWDMF1					as demand_time_fence_1_whl
  , mitwhl.MWDMF2					as demand_time_fence_2_whl
  , mitwhl.MWDMF3					as demand_time_fence_3_whl
  , mitwhl.MWDMF4					as demand_time_fence_4_whl
  , mitwhl.MWDMF5					as demand_time_fence_5_whl
  , mitwhl.MWDMF6					as demand_time_fence_6_whl
  , mitwhl.MWDMF7					as demand_time_fence_7_whl
  , mitwhl.MWDMF8					as demand_time_fence_8_whl
  , mitwhl.MWDMF9					as demand_time_fence_9_whl
  , mitwhl.MWINUL					as retrieve_stock_transactions_whl
  , mitwhl.MWEPUL					as retrieve_receiptpicklist_whl
  , mitwhl.MWEXDL					as send_planned_receipts_whl
  , mitwhl.MWPIDL					as send_picking_lists_whl
  , mitwhl.MWALWQ					as alias_qualifier_whl
  , mitwhl.MWITDL					as send_item_master_whl
  , mitwhl.MWCDYN					as cross_dock_whl
  , mitwhl.MWPATF					as planned_cross_dock_time_fence_days_whl
  , mitwhl.MWPAHF					as planned_cross_dock_time_fence_hours_whl
  , mitwhl.MWPMTF					as opportunity_cd_time_fence_days_whl
  , mitwhl.MWPMHF					as opportunity_cd_time_fence_hours_whl
  , mitwhl.MWDDLO					as default_docking_location_whl
  , mitwhl.MWCDPD					as pack_or_dock_location_whl
  , mitwhl.MWCDPM					as display_cross_dock_result_whl
  , mitwhl.MWCALV					as calendar_version_whl
  , mitwhl.MWACGR					as object_access_group_whl
  , mitwhl.MWNBID					as number_series_whl
  , mitwhl.MWSTOF					as shop_information_whl
  , mitwhl.MWASOT					as allocation_stop_type_whl
  , mitwhl.MWDAAS					as number_of_days_for_allocation_stop_type_whl
  , mitwhl.MWLEAM					as allocation_time_fence_whl
  , mitwhl.MWDMFC					as demand_time_fence_type_whl
  , mitwhl.MWLSPM					as location_selection_prompt_whl
  , mitwhl.MWRSTN					as store_id_whl
  , mitwhl.MWRGDT					as entry_date_whl
  , mitwhl.MWRGTM					as entry_time_whl
  , mitwhl.MWLMDT					as change_date_whl
  , mitwhl.MWCHNO					as change_number_whl
  , mitwhl.MWCHID					as changed_by_whl
  , mitwhl.MWLMTS					as timestamp_whl
  , mitwhl.MWCPTE					as cpy_templ_item_whl
  , mitwhl.MWSCED					as delivery_regrouping_whl
  , mitwhl.MWGEOX					as geographic_code_x_whl
  , mitwhl.MWGEOY					as geographic_code_y_whl
  , mitwhl.MWGEOZ					as geographic_code_z_whl
  , prod.[ProductName]				as product_name
  , prod.[ProductCategoryBaseLevel] as product_category_base_level
  , prod.[ProductCategoryLevel1]	as product_category_level_1
  , prod.[ProductCategoryLevel2]	as product_category_level_2
  , prod.[ProductCategoryLevel3]	as product_category_level_3
  , prod.[ProductCategoryLevel4]	as product_category_level_4
  , prod.[ProductCategoryLevel5]	as product_category_level_5
from
	[psa].[ics_stg_M3V10ved_POL_MITLOC]		  as mitloc
left join [psa].[ics_stg_M3V10ved_POL_MITAUN] as mitaun
	on mitaun.MUITNO = mitloc.MLITNO
left join [psa].[ics_stg_M3V10ved_POL_MITMAS] as mitmas
	on mitmas.MMITNO = mitloc.MLITNO
left join tsa.ics_land_M3V10ved_POL_MITWHL	  as mitwhl
	on mitwhl.MWWHLO = mitloc.MLWHLO
left join qvstg.Product						  as prod
	on prod.NativeProductKey = mitloc.MLITNO ;

GO
