-- <Migration ID="37c3da1f-f09b-4250-8f38-2619754af3aa" />
GO

PRINT N'Dropping constraints from [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
ALTER TABLE [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName] DROP CONSTRAINT [CK_ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName_IsProcessed]
GO
PRINT N'Dropping constraints from [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
ALTER TABLE [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName] DROP CONSTRAINT [CK_ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName_IsDeleted]
GO
PRINT N'Dropping constraints from [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
ALTER TABLE [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName] DROP CONSTRAINT [PK_ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]
GO
PRINT N'Dropping constraints from [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
ALTER TABLE [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName] DROP CONSTRAINT [AK_ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]
GO
PRINT N'Dropping constraints from [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
ALTER TABLE [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName] DROP CONSTRAINT [DF_ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName_IsProcessed]
GO
PRINT N'Dropping constraints from [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
ALTER TABLE [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName] DROP CONSTRAINT [DF_ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName_IsDeleted]
GO
PRINT N'Dropping constraints from [tsa].[ICS_LAND_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
ALTER TABLE [tsa].[ICS_LAND_SampleSystemName_SourceCountryCode_SampleTableName] DROP CONSTRAINT [PK_ICS_LAND_SampleSystemName_SourceCountryCode_SampleTableName]
GO
PRINT N'Dropping [tsa].[ICS_LAND_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
DROP TABLE [tsa].[ICS_LAND_SampleSystemName_SourceCountryCode_SampleTableName]
GO
PRINT N'Dropping [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]'
GO
DROP TABLE [psa].[ICS_STG_SampleSystemName_SourceCountryCode_SampleTableName]
GO
PRINT N'Creating [psa].[ics_stg_M3V10gen_POL_CIDADR]'
GO
CREATE TABLE [psa].[ics_stg_M3V10gen_POL_CIDADR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_CIDADR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_CIDADR_IsIncomplete] DEFAULT ('N'),
[SAADID] [nchar] (6) NULL,
[SAADR1] [nvarchar] (36) NULL,
[SAADR2] [nvarchar] (36) NULL,
[SAADR3] [nvarchar] (36) NULL,
[SAADR4] [nvarchar] (36) NULL,
[SAADTE] [numeric] (18, 0) NULL,
[SAADVI] [nchar] (6) NULL,
[SACHID] [nchar] (10) NULL,
[SACHNO] [numeric] (18, 0) NULL,
[SACONO] [numeric] (18, 0) NULL,
[SACSCD] [nchar] (3) NULL,
[SAECAR] [nchar] (2) NULL,
[SAEDES] [nchar] (10) NULL,
[SAGEOC] [numeric] (18, 0) NULL,
[SAGEOX] [numeric] (18, 0) NULL,
[SAGEOY] [numeric] (18, 0) NULL,
[SAGEOZ] [numeric] (18, 0) NULL,
[SALMDT] [numeric] (18, 0) NULL,
[SALMTS] [numeric] (18, 0) NULL,
[SAPNOD] [nchar] (15) NULL,
[SAPONO] [nchar] (10) NULL,
[SAPRIA] [numeric] (18, 0) NULL,
[SARGDT] [numeric] (18, 0) NULL,
[SARGTM] [numeric] (18, 0) NULL,
[SASTDT] [numeric] (18, 0) NULL,
[SASUNM] [nvarchar] (36) NULL,
[SASUNO] [nchar] (10) NULL,
[SATAXC] [nchar] (3) NULL,
[SATOWN] [nvarchar] (20) NULL,
[SATXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_M3V10gen_POL_CMNCMP]'
GO
CREATE TABLE [psa].[ics_stg_M3V10gen_POL_CMNCMP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_CMNCMP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_CMNCMP_IsIncomplete] DEFAULT ('N'),
[JICCRT] [numeric] (18, 0) NULL,
[JICCUC] [nchar] (3) NULL,
[JICHID] [nchar] (10) NULL,
[JICHNO] [numeric] (18, 0) NULL,
[JICMTP] [numeric] (18, 0) NULL,
[JICONO] [numeric] (18, 0) NULL,
[JIDBAS] [nchar] (10) NULL,
[JIDCFM] [nchar] (1) NULL,
[JIDFMN] [nchar] (10) NULL,
[JILL01] [nchar] (10) NULL,
[JILL02] [nchar] (10) NULL,
[JILL03] [nchar] (10) NULL,
[JILL04] [nchar] (10) NULL,
[JILL05] [nchar] (10) NULL,
[JILL06] [nchar] (10) NULL,
[JILL07] [nchar] (10) NULL,
[JILL08] [nchar] (10) NULL,
[JILL09] [nchar] (10) NULL,
[JILL10] [nchar] (10) NULL,
[JILMDT] [numeric] (18, 0) NULL,
[JIMNMN] [numeric] (18, 0) NULL,
[JIMNVR] [nchar] (10) NULL,
[JIMXV1] [nchar] (3) NULL,
[JIRGDT] [numeric] (18, 0) NULL,
[JIRGTM] [numeric] (18, 0) NULL,
[JISTMN] [nchar] (15) NULL,
[JITX40] [nvarchar] (40) NULL,
[JITXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating [psa].[ics_stg_M3V10gen_POL_CMNDIV]'
GO
CREATE TABLE [psa].[ics_stg_M3V10gen_POL_CMNDIV]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_CMNDIV_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_CMNDIV_IsIncomplete] DEFAULT ('N'),
[CCACGR] [nchar] (10) NULL,
[CCCCD0] [nchar] (1) NULL,
[CCCCD1] [nchar] (10) NULL,
[CCCCD2] [numeric] (18, 0) NULL,
[CCCCD3] [nchar] (3) NULL,
[CCCCD4] [nchar] (5) NULL,
[CCCCD5] [nchar] (1) NULL,
[CCCCD6] [nchar] (10) NULL,
[CCCCD7] [numeric] (18, 0) NULL,
[CCCCD8] [nchar] (3) NULL,
[CCCCD9] [nchar] (5) NULL,
[CCCDCD] [numeric] (18, 0) NULL,
[CCCHID] [nchar] (10) NULL,
[CCCHNO] [numeric] (18, 0) NULL,
[CCCOA1] [nvarchar] (36) NULL,
[CCCOA2] [nvarchar] (36) NULL,
[CCCOA3] [nvarchar] (36) NULL,
[CCCOA4] [nvarchar] (36) NULL,
[CCCONL] [numeric] (18, 0) NULL,
[CCCONM] [nvarchar] (36) NULL,
[CCCONO] [numeric] (18, 0) NULL,
[CCCSCD] [nchar] (3) NULL,
[CCDCFM] [nchar] (1) NULL,
[CCDIVI] [nchar] (3) NULL,
[CCDMCU] [numeric] (18, 0) NULL,
[CCDTFM] [nchar] (3) NULL,
[CCECAR] [nchar] (2) NULL,
[CCFACI] [nchar] (3) NULL,
[CCFIRM] [nchar] (7) NULL,
[CCGEOC] [numeric] (18, 0) NULL,
[CCHCMA] [numeric] (18, 0) NULL,
[CCISTA] [numeric] (18, 0) NULL,
[CCLL01] [nchar] (10) NULL,
[CCLL02] [nchar] (10) NULL,
[CCLL03] [nchar] (10) NULL,
[CCLL04] [nchar] (10) NULL,
[CCLL05] [nchar] (10) NULL,
[CCLL06] [nchar] (10) NULL,
[CCLL07] [nchar] (10) NULL,
[CCLL08] [nchar] (10) NULL,
[CCLL09] [nchar] (10) NULL,
[CCLL10] [nchar] (10) NULL,
[CCLLID] [nchar] (10) NULL,
[CCLMDT] [numeric] (18, 0) NULL,
[CCLOCD] [nchar] (3) NULL,
[CCMXAP] [numeric] (18, 0) NULL,
[CCMXAR] [numeric] (18, 0) NULL,
[CCMXAT] [numeric] (18, 0) NULL,
[CCMXBU] [numeric] (18, 0) NULL,
[CCMXCA] [numeric] (18, 0) NULL,
[CCMXCF] [numeric] (18, 0) NULL,
[CCMXCP] [numeric] (18, 0) NULL,
[CCMXCR] [numeric] (18, 0) NULL,
[CCMXDC] [numeric] (18, 0) NULL,
[CCMXDO] [numeric] (18, 0) NULL,
[CCMXDP] [numeric] (18, 0) NULL,
[CCMXDR] [numeric] (18, 0) NULL,
[CCMXDS] [numeric] (18, 0) NULL,
[CCMXDT] [numeric] (18, 0) NULL,
[CCMXEC] [numeric] (18, 0) NULL,
[CCMXED] [numeric] (18, 0) NULL,
[CCMXEM] [numeric] (18, 0) NULL,
[CCMXEP] [numeric] (18, 0) NULL,
[CCMXET] [numeric] (18, 0) NULL,
[CCMXEV] [numeric] (18, 0) NULL,
[CCMXFA] [numeric] (18, 0) NULL,
[CCMXFC] [numeric] (18, 0) NULL,
[CCMXGL] [numeric] (18, 0) NULL,
[CCMXGM] [numeric] (18, 0) NULL,
[CCMXIC] [numeric] (18, 0) NULL,
[CCMXIP] [numeric] (18, 0) NULL,
[CCMXJO] [numeric] (18, 0) NULL,
[CCMXJQ] [numeric] (18, 0) NULL,
[CCMXLI] [numeric] (18, 0) NULL,
[CCMXLT] [numeric] (18, 0) NULL,
[CCMXMA] [numeric] (18, 0) NULL,
[CCMXMC] [numeric] (18, 0) NULL,
[CCMXMD] [numeric] (18, 0) NULL,
[CCMXMF] [numeric] (18, 0) NULL,
[CCMXMI] [numeric] (18, 0) NULL,
[CCMXMM] [numeric] (18, 0) NULL,
[CCMXMN] [numeric] (18, 0) NULL,
[CCMXMO] [numeric] (18, 0) NULL,
[CCMXMP] [numeric] (18, 0) NULL,
[CCMXMQ] [numeric] (18, 0) NULL,
[CCMXMS] [numeric] (18, 0) NULL,
[CCMXOC] [numeric] (18, 0) NULL,
[CCMXOD] [numeric] (18, 0) NULL,
[CCMXOI] [numeric] (18, 0) NULL,
[CCMXOQ] [numeric] (18, 0) NULL,
[CCMXOS] [numeric] (18, 0) NULL,
[CCMXPA] [numeric] (18, 0) NULL,
[CCMXPC] [numeric] (18, 0) NULL,
[CCMXPD] [numeric] (18, 0) NULL,
[CCMXPM] [numeric] (18, 0) NULL,
[CCMXPO] [numeric] (18, 0) NULL,
[CCMXPP] [numeric] (18, 0) NULL,
[CCMXPQ] [numeric] (18, 0) NULL,
[CCMXPR] [numeric] (18, 0) NULL,
[CCMXPS] [numeric] (18, 0) NULL,
[CCMXQP] [numeric] (18, 0) NULL,
[CCMXRC] [numeric] (18, 0) NULL,
[CCMXRG] [numeric] (18, 0) NULL,
[CCMXRM] [numeric] (18, 0) NULL,
[CCMXRP] [numeric] (18, 0) NULL,
[CCMXRR] [numeric] (18, 0) NULL,
[CCMXRS] [numeric] (18, 0) NULL,
[CCMXSA] [numeric] (18, 0) NULL,
[CCMXSB] [numeric] (18, 0) NULL,
[CCMXSE] [numeric] (18, 0) NULL,
[CCMXSO] [numeric] (18, 0) NULL,
[CCMXSP] [numeric] (18, 0) NULL,
[CCMXST] [numeric] (18, 0) NULL,
[CCMXTA] [numeric] (18, 0) NULL,
[CCMXTE] [numeric] (18, 0) NULL,
[CCMXTM] [numeric] (18, 0) NULL,
[CCMXTP] [numeric] (18, 0) NULL,
[CCMXV1] [nchar] (3) NULL,
[CCMXV2] [nchar] (3) NULL,
[CCMXWO] [numeric] (18, 0) NULL,
[CCMXWP] [numeric] (18, 0) NULL,
[CCMXWT] [numeric] (18, 0) NULL,
[CCNPT1] [numeric] (18, 0) NULL,
[CCNPT2] [numeric] (18, 0) NULL,
[CCNPT3] [numeric] (18, 0) NULL,
[CCNPT4] [numeric] (18, 0) NULL,
[CCNPT5] [numeric] (18, 0) NULL,
[CCOREF] [nvarchar] (30) NULL,
[CCPHN2] [nchar] (16) NULL,
[CCPHNO] [nchar] (16) NULL,
[CCPONO] [nchar] (10) NULL,
[CCPSND] [nchar] (1) NULL,
[CCPTEI] [numeric] (18, 0) NULL,
[CCPTFA] [numeric] (18, 0) NULL,
[CCPTMP] [numeric] (18, 0) NULL,
[CCPTOI] [numeric] (18, 0) NULL,
[CCPTPA] [numeric] (18, 0) NULL,
[CCRAEM] [numeric] (18, 0) NULL,
[CCRGDT] [numeric] (18, 0) NULL,
[CCRGTM] [numeric] (18, 0) NULL,
[CCROW2] [nvarchar] (17) NULL,
[CCROW3] [nvarchar] (78) NULL,
[CCRROF] [nchar] (2) NULL,
[CCSYRE] [numeric] (18, 0) NULL,
[CCTATM] [numeric] (18, 0) NULL,
[CCTFNO] [nchar] (16) NULL,
[CCTIZO] [nchar] (5) NULL,
[CCTLNO] [nchar] (16) NULL,
[CCTOWN] [nvarchar] (20) NULL,
[CCTX15] [nchar] (15) NULL,
[CCTXID] [numeric] (18, 0) NULL,
[CCUNST] [nchar] (3) NULL,
[CCVDME] [numeric] (18, 0) NULL,
[CCVRNL] [nchar] (16) NULL,
[CCVRNO] [nchar] (16) NULL,
[CCWHLO] [nchar] (3) NULL
)
GO
