-- <Migration ID="b615e8ec-1556-4023-9df8-11587a839d78" />
GO

PRINT N'Creating [tsa].[ics_land_M3V10ved_POL_CMNDIV]'
GO
CREATE TABLE [tsa].[ics_land_M3V10ved_POL_CMNDIV]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_CMNDIV_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_CMNDIV_IsDuplicate] DEFAULT ((0)),
[CCACGR] [nchar] (10) NULL,
[CCCCD0] [nchar] (1) NULL,
[CCCCD1] [nchar] (10) NULL,
[CCCCD2] [numeric] (18, 0) NULL,
[CCCCD3] [nchar] (3) NULL,
[CCCCD4] [nchar] (5) NULL,
[CCCCD5] [nchar] (1) NULL,
[CCCCD6] [nchar] (10) NULL,
[CCCCD7] [numeric] (18, 0) NULL,
[CCCCD8] [nchar] (3) NULL,
[CCCCD9] [nchar] (5) NULL,
[CCCDCD] [numeric] (18, 0) NULL,
[CCCHID] [nchar] (10) NULL,
[CCCHNO] [numeric] (18, 0) NULL,
[CCCOA1] [nvarchar] (36) NULL,
[CCCOA2] [nvarchar] (36) NULL,
[CCCOA3] [nvarchar] (36) NULL,
[CCCOA4] [nvarchar] (36) NULL,
[CCCONL] [numeric] (18, 0) NULL,
[CCCONM] [nvarchar] (36) NULL,
[CCCONO] [numeric] (18, 0) NULL,
[CCCSCD] [nchar] (3) NULL,
[CCDCFM] [nchar] (1) NULL,
[CCDIVI] [nchar] (3) NULL,
[CCDMCU] [numeric] (18, 0) NULL,
[CCDTFM] [nchar] (3) NULL,
[CCECAR] [nchar] (2) NULL,
[CCFACI] [nchar] (3) NULL,
[CCFIRM] [nchar] (7) NULL,
[CCGEOC] [numeric] (18, 0) NULL,
[CCHCMA] [numeric] (18, 0) NULL,
[CCISTA] [numeric] (18, 0) NULL,
[CCLL01] [nchar] (10) NULL,
[CCLL02] [nchar] (10) NULL,
[CCLL03] [nchar] (10) NULL,
[CCLL04] [nchar] (10) NULL,
[CCLL05] [nchar] (10) NULL,
[CCLL06] [nchar] (10) NULL,
[CCLL07] [nchar] (10) NULL,
[CCLL08] [nchar] (10) NULL,
[CCLL09] [nchar] (10) NULL,
[CCLL10] [nchar] (10) NULL,
[CCLLID] [nchar] (10) NULL,
[CCLMDT] [numeric] (18, 0) NULL,
[CCLOCD] [nchar] (3) NULL,
[CCMXAP] [numeric] (18, 0) NULL,
[CCMXAR] [numeric] (18, 0) NULL,
[CCMXAT] [numeric] (18, 0) NULL,
[CCMXBU] [numeric] (18, 0) NULL,
[CCMXCA] [numeric] (18, 0) NULL,
[CCMXCF] [numeric] (18, 0) NULL,
[CCMXCP] [numeric] (18, 0) NULL,
[CCMXCR] [numeric] (18, 0) NULL,
[CCMXDC] [numeric] (18, 0) NULL,
[CCMXDO] [numeric] (18, 0) NULL,
[CCMXDP] [numeric] (18, 0) NULL,
[CCMXDR] [numeric] (18, 0) NULL,
[CCMXDS] [numeric] (18, 0) NULL,
[CCMXDT] [numeric] (18, 0) NULL,
[CCMXEC] [numeric] (18, 0) NULL,
[CCMXED] [numeric] (18, 0) NULL,
[CCMXEM] [numeric] (18, 0) NULL,
[CCMXEP] [numeric] (18, 0) NULL,
[CCMXET] [numeric] (18, 0) NULL,
[CCMXEV] [numeric] (18, 0) NULL,
[CCMXFA] [numeric] (18, 0) NULL,
[CCMXFC] [numeric] (18, 0) NULL,
[CCMXGL] [numeric] (18, 0) NULL,
[CCMXGM] [numeric] (18, 0) NULL,
[CCMXIC] [numeric] (18, 0) NULL,
[CCMXIP] [numeric] (18, 0) NULL,
[CCMXJO] [numeric] (18, 0) NULL,
[CCMXJQ] [numeric] (18, 0) NULL,
[CCMXLI] [numeric] (18, 0) NULL,
[CCMXLT] [numeric] (18, 0) NULL,
[CCMXMA] [numeric] (18, 0) NULL,
[CCMXMC] [numeric] (18, 0) NULL,
[CCMXMD] [numeric] (18, 0) NULL,
[CCMXMF] [numeric] (18, 0) NULL,
[CCMXMI] [numeric] (18, 0) NULL,
[CCMXMM] [numeric] (18, 0) NULL,
[CCMXMN] [numeric] (18, 0) NULL,
[CCMXMO] [numeric] (18, 0) NULL,
[CCMXMP] [numeric] (18, 0) NULL,
[CCMXMQ] [numeric] (18, 0) NULL,
[CCMXMS] [numeric] (18, 0) NULL,
[CCMXOC] [numeric] (18, 0) NULL,
[CCMXOD] [numeric] (18, 0) NULL,
[CCMXOI] [numeric] (18, 0) NULL,
[CCMXOQ] [numeric] (18, 0) NULL,
[CCMXOS] [numeric] (18, 0) NULL,
[CCMXPA] [numeric] (18, 0) NULL,
[CCMXPC] [numeric] (18, 0) NULL,
[CCMXPD] [numeric] (18, 0) NULL,
[CCMXPM] [numeric] (18, 0) NULL,
[CCMXPO] [numeric] (18, 0) NULL,
[CCMXPP] [numeric] (18, 0) NULL,
[CCMXPQ] [numeric] (18, 0) NULL,
[CCMXPR] [numeric] (18, 0) NULL,
[CCMXPS] [numeric] (18, 0) NULL,
[CCMXQP] [numeric] (18, 0) NULL,
[CCMXRC] [numeric] (18, 0) NULL,
[CCMXRG] [numeric] (18, 0) NULL,
[CCMXRM] [numeric] (18, 0) NULL,
[CCMXRP] [numeric] (18, 0) NULL,
[CCMXRR] [numeric] (18, 0) NULL,
[CCMXRS] [numeric] (18, 0) NULL,
[CCMXSA] [numeric] (18, 0) NULL,
[CCMXSB] [numeric] (18, 0) NULL,
[CCMXSE] [numeric] (18, 0) NULL,
[CCMXSO] [numeric] (18, 0) NULL,
[CCMXSP] [numeric] (18, 0) NULL,
[CCMXST] [numeric] (18, 0) NULL,
[CCMXTA] [numeric] (18, 0) NULL,
[CCMXTE] [numeric] (18, 0) NULL,
[CCMXTM] [numeric] (18, 0) NULL,
[CCMXTP] [numeric] (18, 0) NULL,
[CCMXV1] [nchar] (3) NULL,
[CCMXV2] [nchar] (3) NULL,
[CCMXWO] [numeric] (18, 0) NULL,
[CCMXWP] [numeric] (18, 0) NULL,
[CCMXWT] [numeric] (18, 0) NULL,
[CCNPT1] [numeric] (18, 0) NULL,
[CCNPT2] [numeric] (18, 0) NULL,
[CCNPT3] [numeric] (18, 0) NULL,
[CCNPT4] [numeric] (18, 0) NULL,
[CCNPT5] [numeric] (18, 0) NULL,
[CCOREF] [nvarchar] (30) NULL,
[CCPHN2] [nchar] (16) NULL,
[CCPHNO] [nchar] (16) NULL,
[CCPONO] [nchar] (10) NULL,
[CCPSND] [nchar] (1) NULL,
[CCPTEI] [numeric] (18, 0) NULL,
[CCPTFA] [numeric] (18, 0) NULL,
[CCPTMP] [numeric] (18, 0) NULL,
[CCPTOI] [numeric] (18, 0) NULL,
[CCPTPA] [numeric] (18, 0) NULL,
[CCRAEM] [numeric] (18, 0) NULL,
[CCRGDT] [numeric] (18, 0) NULL,
[CCRGTM] [numeric] (18, 0) NULL,
[CCROW2] [nvarchar] (17) NULL,
[CCROW3] [nvarchar] (78) NULL,
[CCRROF] [nchar] (2) NULL,
[CCSYRE] [numeric] (18, 0) NULL,
[CCTATM] [numeric] (18, 0) NULL,
[CCTFNO] [nchar] (16) NULL,
[CCTIZO] [nchar] (5) NULL,
[CCTLNO] [nchar] (16) NULL,
[CCTOWN] [nvarchar] (20) NULL,
[CCTX15] [nchar] (15) NULL,
[CCTXID] [numeric] (18, 0) NULL,
[CCUNST] [nchar] (3) NULL,
[CCVDME] [numeric] (18, 0) NULL,
[CCVRNL] [nchar] (16) NULL,
[CCVRNO] [nchar] (16) NULL,
[CCWHLO] [nchar] (3) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10ved_POL_CMNDIV_1] on [tsa].[ics_land_M3V10ved_POL_CMNDIV]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10ved_POL_CMNDIV_1] ON [tsa].[ics_land_M3V10ved_POL_CMNDIV] ([CCCONO], [CCDIVI])
GO
PRINT N'Creating [tsa].[ics_land_M3V10vil_POL_CIDADR]'
GO
CREATE TABLE [tsa].[ics_land_M3V10vil_POL_CIDADR]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10vil_POL_CIDADR_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10vil_POL_CIDADR_IsDuplicate] DEFAULT ((0)),
[SAADID] [nchar] (6) NULL,
[SAADR1] [nvarchar] (36) NULL,
[SAADR2] [nvarchar] (36) NULL,
[SAADR3] [nvarchar] (36) NULL,
[SAADR4] [nvarchar] (36) NULL,
[SAADTE] [numeric] (18, 0) NULL,
[SAADVI] [nchar] (6) NULL,
[SACHID] [nchar] (10) NULL,
[SACHNO] [numeric] (18, 0) NULL,
[SACONO] [numeric] (18, 0) NULL,
[SACSCD] [nchar] (3) NULL,
[SAECAR] [nchar] (2) NULL,
[SAEDES] [nchar] (10) NULL,
[SAGEOC] [numeric] (18, 0) NULL,
[SAGEOX] [numeric] (18, 0) NULL,
[SAGEOY] [numeric] (18, 0) NULL,
[SAGEOZ] [numeric] (18, 0) NULL,
[SALMDT] [numeric] (18, 0) NULL,
[SALMTS] [numeric] (18, 0) NULL,
[SAPNOD] [nchar] (15) NULL,
[SAPONO] [nchar] (10) NULL,
[SAPRIA] [numeric] (18, 0) NULL,
[SARGDT] [numeric] (18, 0) NULL,
[SARGTM] [numeric] (18, 0) NULL,
[SASTDT] [numeric] (18, 0) NULL,
[SASUNM] [nvarchar] (36) NULL,
[SASUNO] [nchar] (10) NULL,
[SATAXC] [nchar] (3) NULL,
[SATOWN] [nvarchar] (20) NULL,
[SATXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10vil_POL_CIDADR_1] on [tsa].[ics_land_M3V10vil_POL_CIDADR]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10vil_POL_CIDADR_1] ON [tsa].[ics_land_M3V10vil_POL_CIDADR] ([SAADID], [SAADTE], [SACONO], [SASTDT], [SASUNO])
GO
PRINT N'Creating [tsa].[ics_land_M3V10vil_POL_CMNCMP]'
GO
CREATE TABLE [tsa].[ics_land_M3V10vil_POL_CMNCMP]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10vil_POL_CMNCMP_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10vil_POL_CMNCMP_IsDuplicate] DEFAULT ((0)),
[JICCRT] [numeric] (18, 0) NULL,
[JICCUC] [nchar] (3) NULL,
[JICHID] [nchar] (10) NULL,
[JICHNO] [numeric] (18, 0) NULL,
[JICMTP] [numeric] (18, 0) NULL,
[JICONO] [numeric] (18, 0) NULL,
[JIDBAS] [nchar] (10) NULL,
[JIDCFM] [nchar] (1) NULL,
[JIDFMN] [nchar] (10) NULL,
[JILL01] [nchar] (10) NULL,
[JILL02] [nchar] (10) NULL,
[JILL03] [nchar] (10) NULL,
[JILL04] [nchar] (10) NULL,
[JILL05] [nchar] (10) NULL,
[JILL06] [nchar] (10) NULL,
[JILL07] [nchar] (10) NULL,
[JILL08] [nchar] (10) NULL,
[JILL09] [nchar] (10) NULL,
[JILL10] [nchar] (10) NULL,
[JILMDT] [numeric] (18, 0) NULL,
[JIMNMN] [numeric] (18, 0) NULL,
[JIMNVR] [nchar] (10) NULL,
[JIMXV1] [nchar] (3) NULL,
[JIRGDT] [numeric] (18, 0) NULL,
[JIRGTM] [numeric] (18, 0) NULL,
[JISTMN] [nchar] (15) NULL,
[JITX40] [nvarchar] (40) NULL,
[JITXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10vil_POL_CMNCMP_1] on [tsa].[ics_land_M3V10vil_POL_CMNCMP]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10vil_POL_CMNCMP_1] ON [tsa].[ics_land_M3V10vil_POL_CMNCMP] ([JICONO])
GO
PRINT N'Creating [tsa].[ics_land_M3V10vil_POL_CMNDIV]'
GO
CREATE TABLE [tsa].[ics_land_M3V10vil_POL_CMNDIV]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10vil_POL_CMNDIV_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10vil_POL_CMNDIV_IsDuplicate] DEFAULT ((0)),
[CCACGR] [nchar] (10) NULL,
[CCCCD0] [nchar] (1) NULL,
[CCCCD1] [nchar] (10) NULL,
[CCCCD2] [numeric] (18, 0) NULL,
[CCCCD3] [nchar] (3) NULL,
[CCCCD4] [nchar] (5) NULL,
[CCCCD5] [nchar] (1) NULL,
[CCCCD6] [nchar] (10) NULL,
[CCCCD7] [numeric] (18, 0) NULL,
[CCCCD8] [nchar] (3) NULL,
[CCCCD9] [nchar] (5) NULL,
[CCCDCD] [numeric] (18, 0) NULL,
[CCCHID] [nchar] (10) NULL,
[CCCHNO] [numeric] (18, 0) NULL,
[CCCOA1] [nvarchar] (36) NULL,
[CCCOA2] [nvarchar] (36) NULL,
[CCCOA3] [nvarchar] (36) NULL,
[CCCOA4] [nvarchar] (36) NULL,
[CCCONL] [numeric] (18, 0) NULL,
[CCCONM] [nvarchar] (36) NULL,
[CCCONO] [numeric] (18, 0) NULL,
[CCCSCD] [nchar] (3) NULL,
[CCDCFM] [nchar] (1) NULL,
[CCDIVI] [nchar] (3) NULL,
[CCDMCU] [numeric] (18, 0) NULL,
[CCDTFM] [nchar] (3) NULL,
[CCECAR] [nchar] (2) NULL,
[CCFACI] [nchar] (3) NULL,
[CCFIRM] [nchar] (7) NULL,
[CCGEOC] [numeric] (18, 0) NULL,
[CCHCMA] [numeric] (18, 0) NULL,
[CCISTA] [numeric] (18, 0) NULL,
[CCLL01] [nchar] (10) NULL,
[CCLL02] [nchar] (10) NULL,
[CCLL03] [nchar] (10) NULL,
[CCLL04] [nchar] (10) NULL,
[CCLL05] [nchar] (10) NULL,
[CCLL06] [nchar] (10) NULL,
[CCLL07] [nchar] (10) NULL,
[CCLL08] [nchar] (10) NULL,
[CCLL09] [nchar] (10) NULL,
[CCLL10] [nchar] (10) NULL,
[CCLLID] [nchar] (10) NULL,
[CCLMDT] [numeric] (18, 0) NULL,
[CCLOCD] [nchar] (3) NULL,
[CCMXAP] [numeric] (18, 0) NULL,
[CCMXAR] [numeric] (18, 0) NULL,
[CCMXAT] [numeric] (18, 0) NULL,
[CCMXBU] [numeric] (18, 0) NULL,
[CCMXCA] [numeric] (18, 0) NULL,
[CCMXCF] [numeric] (18, 0) NULL,
[CCMXCP] [numeric] (18, 0) NULL,
[CCMXCR] [numeric] (18, 0) NULL,
[CCMXDC] [numeric] (18, 0) NULL,
[CCMXDO] [numeric] (18, 0) NULL,
[CCMXDP] [numeric] (18, 0) NULL,
[CCMXDR] [numeric] (18, 0) NULL,
[CCMXDS] [numeric] (18, 0) NULL,
[CCMXDT] [numeric] (18, 0) NULL,
[CCMXEC] [numeric] (18, 0) NULL,
[CCMXED] [numeric] (18, 0) NULL,
[CCMXEM] [numeric] (18, 0) NULL,
[CCMXEP] [numeric] (18, 0) NULL,
[CCMXET] [numeric] (18, 0) NULL,
[CCMXEV] [numeric] (18, 0) NULL,
[CCMXFA] [numeric] (18, 0) NULL,
[CCMXFC] [numeric] (18, 0) NULL,
[CCMXGL] [numeric] (18, 0) NULL,
[CCMXGM] [numeric] (18, 0) NULL,
[CCMXIC] [numeric] (18, 0) NULL,
[CCMXIP] [numeric] (18, 0) NULL,
[CCMXJO] [numeric] (18, 0) NULL,
[CCMXJQ] [numeric] (18, 0) NULL,
[CCMXLI] [numeric] (18, 0) NULL,
[CCMXLT] [numeric] (18, 0) NULL,
[CCMXMA] [numeric] (18, 0) NULL,
[CCMXMC] [numeric] (18, 0) NULL,
[CCMXMD] [numeric] (18, 0) NULL,
[CCMXMF] [numeric] (18, 0) NULL,
[CCMXMI] [numeric] (18, 0) NULL,
[CCMXMM] [numeric] (18, 0) NULL,
[CCMXMN] [numeric] (18, 0) NULL,
[CCMXMO] [numeric] (18, 0) NULL,
[CCMXMP] [numeric] (18, 0) NULL,
[CCMXMQ] [numeric] (18, 0) NULL,
[CCMXMS] [numeric] (18, 0) NULL,
[CCMXOC] [numeric] (18, 0) NULL,
[CCMXOD] [numeric] (18, 0) NULL,
[CCMXOI] [numeric] (18, 0) NULL,
[CCMXOQ] [numeric] (18, 0) NULL,
[CCMXOS] [numeric] (18, 0) NULL,
[CCMXPA] [numeric] (18, 0) NULL,
[CCMXPC] [numeric] (18, 0) NULL,
[CCMXPD] [numeric] (18, 0) NULL,
[CCMXPM] [numeric] (18, 0) NULL,
[CCMXPO] [numeric] (18, 0) NULL,
[CCMXPP] [numeric] (18, 0) NULL,
[CCMXPQ] [numeric] (18, 0) NULL,
[CCMXPR] [numeric] (18, 0) NULL,
[CCMXPS] [numeric] (18, 0) NULL,
[CCMXQP] [numeric] (18, 0) NULL,
[CCMXRC] [numeric] (18, 0) NULL,
[CCMXRG] [numeric] (18, 0) NULL,
[CCMXRM] [numeric] (18, 0) NULL,
[CCMXRP] [numeric] (18, 0) NULL,
[CCMXRR] [numeric] (18, 0) NULL,
[CCMXRS] [numeric] (18, 0) NULL,
[CCMXSA] [numeric] (18, 0) NULL,
[CCMXSB] [numeric] (18, 0) NULL,
[CCMXSE] [numeric] (18, 0) NULL,
[CCMXSO] [numeric] (18, 0) NULL,
[CCMXSP] [numeric] (18, 0) NULL,
[CCMXST] [numeric] (18, 0) NULL,
[CCMXTA] [numeric] (18, 0) NULL,
[CCMXTE] [numeric] (18, 0) NULL,
[CCMXTM] [numeric] (18, 0) NULL,
[CCMXTP] [numeric] (18, 0) NULL,
[CCMXV1] [nchar] (3) NULL,
[CCMXV2] [nchar] (3) NULL,
[CCMXWO] [numeric] (18, 0) NULL,
[CCMXWP] [numeric] (18, 0) NULL,
[CCMXWT] [numeric] (18, 0) NULL,
[CCNPT1] [numeric] (18, 0) NULL,
[CCNPT2] [numeric] (18, 0) NULL,
[CCNPT3] [numeric] (18, 0) NULL,
[CCNPT4] [numeric] (18, 0) NULL,
[CCNPT5] [numeric] (18, 0) NULL,
[CCOREF] [nvarchar] (30) NULL,
[CCPHN2] [nchar] (16) NULL,
[CCPHNO] [nchar] (16) NULL,
[CCPONO] [nchar] (10) NULL,
[CCPSND] [nchar] (1) NULL,
[CCPTEI] [numeric] (18, 0) NULL,
[CCPTFA] [numeric] (18, 0) NULL,
[CCPTMP] [numeric] (18, 0) NULL,
[CCPTOI] [numeric] (18, 0) NULL,
[CCPTPA] [numeric] (18, 0) NULL,
[CCRAEM] [numeric] (18, 0) NULL,
[CCRGDT] [numeric] (18, 0) NULL,
[CCRGTM] [numeric] (18, 0) NULL,
[CCROW2] [nvarchar] (17) NULL,
[CCROW3] [nvarchar] (78) NULL,
[CCRROF] [nchar] (2) NULL,
[CCSYRE] [numeric] (18, 0) NULL,
[CCTATM] [numeric] (18, 0) NULL,
[CCTFNO] [nchar] (16) NULL,
[CCTIZO] [nchar] (5) NULL,
[CCTLNO] [nchar] (16) NULL,
[CCTOWN] [nvarchar] (20) NULL,
[CCTX15] [nchar] (15) NULL,
[CCTXID] [numeric] (18, 0) NULL,
[CCUNST] [nchar] (3) NULL,
[CCVDME] [numeric] (18, 0) NULL,
[CCVRNL] [nchar] (16) NULL,
[CCVRNO] [nchar] (16) NULL,
[CCWHLO] [nchar] (3) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10vil_POL_CMNDIV_1] on [tsa].[ics_land_M3V10vil_POL_CMNDIV]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10vil_POL_CMNDIV_1] ON [tsa].[ics_land_M3V10vil_POL_CMNDIV] ([CCCONO], [CCDIVI])
GO
PRINT N'Creating [tsa].[ics_land_M3V10vil_POL_MITTRA]'
GO
CREATE TABLE [tsa].[ics_land_M3V10vil_POL_MITTRA]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_MITTRA_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_MITTRA_IsDuplicate] DEFAULT ((0)),
[MTACRF] [nchar] (8) NULL,
[MTADCU] [numeric] (18, 0) NULL,
[MTANBR] [numeric] (18, 0) NULL,
[MTATNB] [numeric] (18, 0) NULL,
[MTATNR] [numeric] (18, 0) NULL,
[MTBANO] [nvarchar] (20) NULL,
[MTBIRT] [numeric] (18, 0) NULL,
[MTBRE2] [nvarchar] (20) NULL,
[MTBREF] [nvarchar] (20) NULL,
[MTCAMU] [nvarchar] (20) NULL,
[MTCANB] [numeric] (18, 0) NULL,
[MTCAWE] [numeric] (18, 0) NULL,
[MTCDTP] [numeric] (18, 0) NULL,
[MTCFGL] [nchar] (15) NULL,
[MTCNDA] [numeric] (18, 0) NULL,
[MTCONO] [numeric] (18, 0) NULL,
[MTCSQT] [numeric] (18, 0) NULL,
[MTCWTQ] [numeric] (18, 0) NULL,
[MTCWTT] [numeric] (18, 0) NULL,
[MTDEID] [numeric] (18, 0) NULL,
[MTECVE] [nchar] (4) NULL,
[MTELNO] [nchar] (8) NULL,
[MTFIAS] [numeric] (18, 0) NULL,
[MTHACP] [numeric] (18, 0) NULL,
[MTHACS] [numeric] (18, 0) NULL,
[MTINDI] [numeric] (18, 0) NULL,
[MTINER] [numeric] (18, 0) NULL,
[MTITNO] [nchar] (15) NULL,
[MTLMTS] [numeric] (18, 0) NULL,
[MTLOCH] [numeric] (18, 0) NULL,
[MTMFCO] [numeric] (18, 0) NULL,
[MTNHAI] [nchar] (15) NULL,
[MTNHSN] [nvarchar] (20) NULL,
[MTNSTQ] [numeric] (18, 0) NULL,
[MTNSTT] [numeric] (18, 0) NULL,
[MTOPAN] [nvarchar] (20) NULL,
[MTPANR] [nvarchar] (20) NULL,
[MTPLSX] [numeric] (18, 0) NULL,
[MTPRMF] [numeric] (18, 0) NULL,
[MTPROJ] [nchar] (7) NULL,
[MTREPN] [numeric] (18, 0) NULL,
[MTRESP] [nchar] (10) NULL,
[MTRFTX] [nvarchar] (40) NULL,
[MTRGDT] [numeric] (18, 0) NULL,
[MTRGTM] [numeric] (18, 0) NULL,
[MTRIDI] [numeric] (18, 0) NULL,
[MTRIDL] [numeric] (18, 0) NULL,
[MTRIDN] [nchar] (10) NULL,
[MTRIDO] [numeric] (18, 0) NULL,
[MTRIDX] [numeric] (18, 0) NULL,
[MTRORC] [numeric] (18, 0) NULL,
[MTRORL] [numeric] (18, 0) NULL,
[MTRORN] [nchar] (10) NULL,
[MTRORX] [numeric] (18, 0) NULL,
[MTRPRT] [numeric] (18, 0) NULL,
[MTRSCD] [nchar] (3) NULL,
[MTSCNB] [nchar] (10) NULL,
[MTSLTP] [nchar] (2) NULL,
[MTSTAS] [nchar] (1) NULL,
[MTSTCD] [numeric] (18, 0) NULL,
[MTSTNO] [numeric] (18, 0) NULL,
[MTSUDO] [nvarchar] (20) NULL,
[MTTMSX] [numeric] (18, 0) NULL,
[MTTRDT] [numeric] (18, 0) NULL,
[MTTRPR] [numeric] (18, 0) NULL,
[MTTRQA] [numeric] (18, 0) NULL,
[MTTRQT] [numeric] (18, 0) NULL,
[MTTRTM] [numeric] (18, 0) NULL,
[MTTRTP] [nchar] (3) NULL,
[MTTTID] [nchar] (3) NULL,
[MTTTYP] [numeric] (18, 0) NULL,
[MTTUPC] [numeric] (18, 0) NULL,
[MTUPIS] [numeric] (18, 0) NULL,
[MTWHLO] [nchar] (3) NULL,
[MTWHSL] [nchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10vil_POL_MITTRA_1] on [tsa].[ics_land_M3V10vil_POL_MITTRA]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10vil_POL_MITTRA_1] ON [tsa].[ics_land_M3V10vil_POL_MITTRA] ([MTCONO], [MTITNO], [MTRGDT], [MTRGTM], [MTTMSX], [MTWHLO])
GO
PRINT N'Creating [tsa].[ics_land_M3V10gen_POL_MITTRA]'
GO
CREATE TABLE [tsa].[ics_land_M3V10gen_POL_MITTRA]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_M3V10gen_POL_MITTRA_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_M3V10gen_POL_MITTRA_IsDuplicate] DEFAULT ((0)),
[MTACRF] [nchar] (8) NULL,
[MTADCU] [numeric] (18, 0) NULL,
[MTANBR] [numeric] (18, 0) NULL,
[MTATNB] [numeric] (18, 0) NULL,
[MTATNR] [numeric] (18, 0) NULL,
[MTBANO] [nvarchar] (20) NULL,
[MTBIRT] [numeric] (18, 0) NULL,
[MTBRE2] [nvarchar] (20) NULL,
[MTBREF] [nvarchar] (20) NULL,
[MTCAMU] [nvarchar] (20) NULL,
[MTCANB] [numeric] (18, 0) NULL,
[MTCAWE] [numeric] (18, 0) NULL,
[MTCDTP] [numeric] (18, 0) NULL,
[MTCFGL] [nchar] (15) NULL,
[MTCNDA] [numeric] (18, 0) NULL,
[MTCONO] [numeric] (18, 0) NULL,
[MTCSQT] [numeric] (18, 0) NULL,
[MTCWTQ] [numeric] (18, 0) NULL,
[MTCWTT] [numeric] (18, 0) NULL,
[MTDEID] [numeric] (18, 0) NULL,
[MTECVE] [nchar] (4) NULL,
[MTELNO] [nchar] (8) NULL,
[MTFIAS] [numeric] (18, 0) NULL,
[MTHACP] [numeric] (18, 0) NULL,
[MTHACS] [numeric] (18, 0) NULL,
[MTINDI] [numeric] (18, 0) NULL,
[MTINER] [numeric] (18, 0) NULL,
[MTITNO] [nchar] (15) NULL,
[MTLMTS] [numeric] (18, 0) NULL,
[MTLOCH] [numeric] (18, 0) NULL,
[MTMFCO] [numeric] (18, 0) NULL,
[MTNHAI] [nchar] (15) NULL,
[MTNHSN] [nvarchar] (20) NULL,
[MTNSTQ] [numeric] (18, 0) NULL,
[MTNSTT] [numeric] (18, 0) NULL,
[MTOPAN] [nvarchar] (20) NULL,
[MTPANR] [nvarchar] (20) NULL,
[MTPLSX] [numeric] (18, 0) NULL,
[MTPRMF] [numeric] (18, 0) NULL,
[MTPROJ] [nchar] (7) NULL,
[MTREPN] [numeric] (18, 0) NULL,
[MTRESP] [nchar] (10) NULL,
[MTRFTX] [nvarchar] (40) NULL,
[MTRGDT] [numeric] (18, 0) NULL,
[MTRGTM] [numeric] (18, 0) NULL,
[MTRIDI] [numeric] (18, 0) NULL,
[MTRIDL] [numeric] (18, 0) NULL,
[MTRIDN] [nchar] (10) NULL,
[MTRIDO] [numeric] (18, 0) NULL,
[MTRIDX] [numeric] (18, 0) NULL,
[MTRORC] [numeric] (18, 0) NULL,
[MTRORL] [numeric] (18, 0) NULL,
[MTRORN] [nchar] (10) NULL,
[MTRORX] [numeric] (18, 0) NULL,
[MTRPRT] [numeric] (18, 0) NULL,
[MTRSCD] [nchar] (3) NULL,
[MTSCNB] [nchar] (10) NULL,
[MTSLTP] [nchar] (2) NULL,
[MTSTAS] [nchar] (1) NULL,
[MTSTCD] [numeric] (18, 0) NULL,
[MTSTNO] [numeric] (18, 0) NULL,
[MTSUDO] [nvarchar] (20) NULL,
[MTTMSX] [numeric] (18, 0) NULL,
[MTTRDT] [numeric] (18, 0) NULL,
[MTTRPR] [numeric] (18, 0) NULL,
[MTTRQA] [numeric] (18, 0) NULL,
[MTTRQT] [numeric] (18, 0) NULL,
[MTTRTM] [numeric] (18, 0) NULL,
[MTTRTP] [nchar] (3) NULL,
[MTTTID] [nchar] (3) NULL,
[MTTTYP] [numeric] (18, 0) NULL,
[MTTUPC] [numeric] (18, 0) NULL,
[MTUPIS] [numeric] (18, 0) NULL,
[MTWHLO] [nchar] (3) NULL,
[MTWHSL] [nchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10gen_POL_MITTRA_1] on [tsa].[ics_land_M3V10gen_POL_MITTRA]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_MITTRA_1] ON [tsa].[ics_land_M3V10gen_POL_MITTRA] ([MTCONO], [MTITNO], [MTRGDT], [MTRGTM], [MTTMSX], [MTWHLO])
GO
PRINT N'Altering [psa].[ics_stg_M3V10gen_POL_CIDADR]'
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CIDADR] ALTER COLUMN [SAADID] [nchar] (6) NOT NULL
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CIDADR] ALTER COLUMN [SAADTE] [numeric] (18, 0) NOT NULL
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CIDADR] ALTER COLUMN [SACONO] [numeric] (18, 0) NOT NULL
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CIDADR] ALTER COLUMN [SASTDT] [numeric] (18, 0) NOT NULL
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CIDADR] ALTER COLUMN [SASUNO] [nchar] (10) NOT NULL
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10gen_POL_CIDADR] on [psa].[ics_stg_M3V10gen_POL_CIDADR]'
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CIDADR] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_CIDADR] PRIMARY KEY CLUSTERED  ([SAADID], [SAADTE], [SACONO], [SASTDT], [SASUNO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10vil_POL_MITTRA]'
GO
CREATE TABLE [psa].[ics_stg_M3V10vil_POL_MITTRA]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_MITTRA_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_MITTRA_IsIncomplete] DEFAULT ('N'),
[MTACRF] [nchar] (8) NULL,
[MTADCU] [numeric] (18, 0) NULL,
[MTANBR] [numeric] (18, 0) NULL,
[MTATNB] [numeric] (18, 0) NULL,
[MTATNR] [numeric] (18, 0) NULL,
[MTBANO] [nvarchar] (20) NULL,
[MTBIRT] [numeric] (18, 0) NULL,
[MTBRE2] [nvarchar] (20) NULL,
[MTBREF] [nvarchar] (20) NULL,
[MTCAMU] [nvarchar] (20) NULL,
[MTCANB] [numeric] (18, 0) NULL,
[MTCAWE] [numeric] (18, 0) NULL,
[MTCDTP] [numeric] (18, 0) NULL,
[MTCFGL] [nchar] (15) NULL,
[MTCNDA] [numeric] (18, 0) NULL,
[MTCONO] [numeric] (18, 0) NOT NULL,
[MTCSQT] [numeric] (18, 0) NULL,
[MTCWTQ] [numeric] (18, 0) NULL,
[MTCWTT] [numeric] (18, 0) NULL,
[MTDEID] [numeric] (18, 0) NULL,
[MTECVE] [nchar] (4) NULL,
[MTELNO] [nchar] (8) NULL,
[MTFIAS] [numeric] (18, 0) NULL,
[MTHACP] [numeric] (18, 0) NULL,
[MTHACS] [numeric] (18, 0) NULL,
[MTINDI] [numeric] (18, 0) NULL,
[MTINER] [numeric] (18, 0) NULL,
[MTITNO] [nchar] (15) NOT NULL,
[MTLMTS] [numeric] (18, 0) NULL,
[MTLOCH] [numeric] (18, 0) NULL,
[MTMFCO] [numeric] (18, 0) NULL,
[MTNHAI] [nchar] (15) NULL,
[MTNHSN] [nvarchar] (20) NULL,
[MTNSTQ] [numeric] (18, 0) NULL,
[MTNSTT] [numeric] (18, 0) NULL,
[MTOPAN] [nvarchar] (20) NULL,
[MTPANR] [nvarchar] (20) NULL,
[MTPLSX] [numeric] (18, 0) NULL,
[MTPRMF] [numeric] (18, 0) NULL,
[MTPROJ] [nchar] (7) NULL,
[MTREPN] [numeric] (18, 0) NULL,
[MTRESP] [nchar] (10) NULL,
[MTRFTX] [nvarchar] (40) NULL,
[MTRGDT] [numeric] (18, 0) NOT NULL,
[MTRGTM] [numeric] (18, 0) NOT NULL,
[MTRIDI] [numeric] (18, 0) NULL,
[MTRIDL] [numeric] (18, 0) NULL,
[MTRIDN] [nchar] (10) NULL,
[MTRIDO] [numeric] (18, 0) NULL,
[MTRIDX] [numeric] (18, 0) NULL,
[MTRORC] [numeric] (18, 0) NULL,
[MTRORL] [numeric] (18, 0) NULL,
[MTRORN] [nchar] (10) NULL,
[MTRORX] [numeric] (18, 0) NULL,
[MTRPRT] [numeric] (18, 0) NULL,
[MTRSCD] [nchar] (3) NULL,
[MTSCNB] [nchar] (10) NULL,
[MTSLTP] [nchar] (2) NULL,
[MTSTAS] [nchar] (1) NULL,
[MTSTCD] [numeric] (18, 0) NULL,
[MTSTNO] [numeric] (18, 0) NULL,
[MTSUDO] [nvarchar] (20) NULL,
[MTTMSX] [numeric] (18, 0) NOT NULL,
[MTTRDT] [numeric] (18, 0) NULL,
[MTTRPR] [numeric] (18, 0) NULL,
[MTTRQA] [numeric] (18, 0) NULL,
[MTTRQT] [numeric] (18, 0) NULL,
[MTTRTM] [numeric] (18, 0) NULL,
[MTTRTP] [nchar] (3) NULL,
[MTTTID] [nchar] (3) NULL,
[MTTTYP] [numeric] (18, 0) NULL,
[MTTUPC] [numeric] (18, 0) NULL,
[MTUPIS] [numeric] (18, 0) NULL,
[MTWHLO] [nchar] (3) NOT NULL,
[MTWHSL] [nchar] (10) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10vil_POL_MITTRA] on [psa].[ics_stg_M3V10vil_POL_MITTRA]'
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_MITTRA] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_MITTRA] PRIMARY KEY CLUSTERED  ([MTCONO], [MTITNO], [MTRGDT], [MTRGTM], [MTTMSX], [MTWHLO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10gen_POL_MITTRA]'
GO
CREATE TABLE [psa].[ics_stg_M3V10gen_POL_MITTRA]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_MITTRA_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10gen_POL_MITTRA_IsIncomplete] DEFAULT ('N'),
[MTACRF] [nchar] (8) NULL,
[MTADCU] [numeric] (18, 0) NULL,
[MTANBR] [numeric] (18, 0) NULL,
[MTATNB] [numeric] (18, 0) NULL,
[MTATNR] [numeric] (18, 0) NULL,
[MTBANO] [nvarchar] (20) NULL,
[MTBIRT] [numeric] (18, 0) NULL,
[MTBRE2] [nvarchar] (20) NULL,
[MTBREF] [nvarchar] (20) NULL,
[MTCAMU] [nvarchar] (20) NULL,
[MTCANB] [numeric] (18, 0) NULL,
[MTCAWE] [numeric] (18, 0) NULL,
[MTCDTP] [numeric] (18, 0) NULL,
[MTCFGL] [nchar] (15) NULL,
[MTCNDA] [numeric] (18, 0) NULL,
[MTCONO] [numeric] (18, 0) NOT NULL,
[MTCSQT] [numeric] (18, 0) NULL,
[MTCWTQ] [numeric] (18, 0) NULL,
[MTCWTT] [numeric] (18, 0) NULL,
[MTDEID] [numeric] (18, 0) NULL,
[MTECVE] [nchar] (4) NULL,
[MTELNO] [nchar] (8) NULL,
[MTFIAS] [numeric] (18, 0) NULL,
[MTHACP] [numeric] (18, 0) NULL,
[MTHACS] [numeric] (18, 0) NULL,
[MTINDI] [numeric] (18, 0) NULL,
[MTINER] [numeric] (18, 0) NULL,
[MTITNO] [nchar] (15) NOT NULL,
[MTLMTS] [numeric] (18, 0) NULL,
[MTLOCH] [numeric] (18, 0) NULL,
[MTMFCO] [numeric] (18, 0) NULL,
[MTNHAI] [nchar] (15) NULL,
[MTNHSN] [nvarchar] (20) NULL,
[MTNSTQ] [numeric] (18, 0) NULL,
[MTNSTT] [numeric] (18, 0) NULL,
[MTOPAN] [nvarchar] (20) NULL,
[MTPANR] [nvarchar] (20) NULL,
[MTPLSX] [numeric] (18, 0) NULL,
[MTPRMF] [numeric] (18, 0) NULL,
[MTPROJ] [nchar] (7) NULL,
[MTREPN] [numeric] (18, 0) NULL,
[MTRESP] [nchar] (10) NULL,
[MTRFTX] [nvarchar] (40) NULL,
[MTRGDT] [numeric] (18, 0) NOT NULL,
[MTRGTM] [numeric] (18, 0) NOT NULL,
[MTRIDI] [numeric] (18, 0) NULL,
[MTRIDL] [numeric] (18, 0) NULL,
[MTRIDN] [nchar] (10) NULL,
[MTRIDO] [numeric] (18, 0) NULL,
[MTRIDX] [numeric] (18, 0) NULL,
[MTRORC] [numeric] (18, 0) NULL,
[MTRORL] [numeric] (18, 0) NULL,
[MTRORN] [nchar] (10) NULL,
[MTRORX] [numeric] (18, 0) NULL,
[MTRPRT] [numeric] (18, 0) NULL,
[MTRSCD] [nchar] (3) NULL,
[MTSCNB] [nchar] (10) NULL,
[MTSLTP] [nchar] (2) NULL,
[MTSTAS] [nchar] (1) NULL,
[MTSTCD] [numeric] (18, 0) NULL,
[MTSTNO] [numeric] (18, 0) NULL,
[MTSUDO] [nvarchar] (20) NULL,
[MTTMSX] [numeric] (18, 0) NOT NULL,
[MTTRDT] [numeric] (18, 0) NULL,
[MTTRPR] [numeric] (18, 0) NULL,
[MTTRQA] [numeric] (18, 0) NULL,
[MTTRQT] [numeric] (18, 0) NULL,
[MTTRTM] [numeric] (18, 0) NULL,
[MTTRTP] [nchar] (3) NULL,
[MTTTID] [nchar] (3) NULL,
[MTTTYP] [numeric] (18, 0) NULL,
[MTTUPC] [numeric] (18, 0) NULL,
[MTUPIS] [numeric] (18, 0) NULL,
[MTWHLO] [nchar] (3) NOT NULL,
[MTWHSL] [nchar] (10) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10gen_POL_MITTRA] on [psa].[ics_stg_M3V10gen_POL_MITTRA]'
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_MITTRA] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_MITTRA] PRIMARY KEY CLUSTERED  ([MTCONO], [MTITNO], [MTRGDT], [MTRGTM], [MTTMSX], [MTWHLO])
GO
PRINT N'Altering [psa].[ics_stg_M3V10gen_POL_CMNCMP]'
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CMNCMP] ALTER COLUMN [JICONO] [numeric] (18, 0) NOT NULL
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10gen_POL_CMNCMP] on [psa].[ics_stg_M3V10gen_POL_CMNCMP]'
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CMNCMP] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_CMNCMP] PRIMARY KEY CLUSTERED  ([JICONO])
GO
PRINT N'Altering [psa].[ics_stg_M3V10gen_POL_CMNDIV]'
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CMNDIV] ALTER COLUMN [CCCONO] [numeric] (18, 0) NOT NULL
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CMNDIV] ALTER COLUMN [CCDIVI] [nchar] (3) NOT NULL
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10gen_POL_CMNDIV] on [psa].[ics_stg_M3V10gen_POL_CMNDIV]'
GO
ALTER TABLE [psa].[ics_stg_M3V10gen_POL_CMNDIV] ADD CONSTRAINT [PK_psa_ics_stg_M3V10gen_POL_CMNDIV] PRIMARY KEY CLUSTERED  ([CCCONO], [CCDIVI])
GO
PRINT N'Creating [tsa].[ics_land_M3V10ved_POL_MITTRA]'
GO
CREATE TABLE [tsa].[ics_land_M3V10ved_POL_MITTRA]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_MITTRA_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_MITTRA_IsDuplicate] DEFAULT ((0)),
[MTACRF] [nchar] (8) NULL,
[MTADCU] [numeric] (18, 0) NULL,
[MTANBR] [numeric] (18, 0) NULL,
[MTATNB] [numeric] (18, 0) NULL,
[MTATNR] [numeric] (18, 0) NULL,
[MTBANO] [nvarchar] (20) NULL,
[MTBIRT] [numeric] (18, 0) NULL,
[MTBRE2] [nvarchar] (20) NULL,
[MTBREF] [nvarchar] (20) NULL,
[MTCAMU] [nvarchar] (20) NULL,
[MTCANB] [numeric] (18, 0) NULL,
[MTCAWE] [numeric] (18, 0) NULL,
[MTCDTP] [numeric] (18, 0) NULL,
[MTCFGL] [nchar] (15) NULL,
[MTCNDA] [numeric] (18, 0) NULL,
[MTCONO] [numeric] (18, 0) NULL,
[MTCSQT] [numeric] (18, 0) NULL,
[MTCWTQ] [numeric] (18, 0) NULL,
[MTCWTT] [numeric] (18, 0) NULL,
[MTDEID] [numeric] (18, 0) NULL,
[MTECVE] [nchar] (4) NULL,
[MTELNO] [nchar] (8) NULL,
[MTFIAS] [numeric] (18, 0) NULL,
[MTHACP] [numeric] (18, 0) NULL,
[MTHACS] [numeric] (18, 0) NULL,
[MTINDI] [numeric] (18, 0) NULL,
[MTINER] [numeric] (18, 0) NULL,
[MTITNO] [nchar] (15) NULL,
[MTLMTS] [numeric] (18, 0) NULL,
[MTLOCH] [numeric] (18, 0) NULL,
[MTMFCO] [numeric] (18, 0) NULL,
[MTNHAI] [nchar] (15) NULL,
[MTNHSN] [nvarchar] (20) NULL,
[MTNSTQ] [numeric] (18, 0) NULL,
[MTNSTT] [numeric] (18, 0) NULL,
[MTOPAN] [nvarchar] (20) NULL,
[MTPANR] [nvarchar] (20) NULL,
[MTPLSX] [numeric] (18, 0) NULL,
[MTPRMF] [numeric] (18, 0) NULL,
[MTPROJ] [nchar] (7) NULL,
[MTREPN] [numeric] (18, 0) NULL,
[MTRESP] [nchar] (10) NULL,
[MTRFTX] [nvarchar] (40) NULL,
[MTRGDT] [numeric] (18, 0) NULL,
[MTRGTM] [numeric] (18, 0) NULL,
[MTRIDI] [numeric] (18, 0) NULL,
[MTRIDL] [numeric] (18, 0) NULL,
[MTRIDN] [nchar] (10) NULL,
[MTRIDO] [numeric] (18, 0) NULL,
[MTRIDX] [numeric] (18, 0) NULL,
[MTRORC] [numeric] (18, 0) NULL,
[MTRORL] [numeric] (18, 0) NULL,
[MTRORN] [nchar] (10) NULL,
[MTRORX] [numeric] (18, 0) NULL,
[MTRPRT] [numeric] (18, 0) NULL,
[MTRSCD] [nchar] (3) NULL,
[MTSCNB] [nchar] (10) NULL,
[MTSLTP] [nchar] (2) NULL,
[MTSTAS] [nchar] (1) NULL,
[MTSTCD] [numeric] (18, 0) NULL,
[MTSTNO] [numeric] (18, 0) NULL,
[MTSUDO] [nvarchar] (20) NULL,
[MTTMSX] [numeric] (18, 0) NULL,
[MTTRDT] [numeric] (18, 0) NULL,
[MTTRPR] [numeric] (18, 0) NULL,
[MTTRQA] [numeric] (18, 0) NULL,
[MTTRQT] [numeric] (18, 0) NULL,
[MTTRTM] [numeric] (18, 0) NULL,
[MTTRTP] [nchar] (3) NULL,
[MTTTID] [nchar] (3) NULL,
[MTTTYP] [numeric] (18, 0) NULL,
[MTTUPC] [numeric] (18, 0) NULL,
[MTUPIS] [numeric] (18, 0) NULL,
[MTWHLO] [nchar] (3) NULL,
[MTWHSL] [nchar] (10) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10ved_POL_MITTRA_1] on [tsa].[ics_land_M3V10ved_POL_MITTRA]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10ved_POL_MITTRA_1] ON [tsa].[ics_land_M3V10ved_POL_MITTRA] ([MTCONO], [MTITNO], [MTRGDT], [MTRGTM], [MTTMSX], [MTWHLO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10ved_POL_MITTRA]'
GO
CREATE TABLE [psa].[ics_stg_M3V10ved_POL_MITTRA]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_MITTRA_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_MITTRA_IsIncomplete] DEFAULT ('N'),
[MTACRF] [nchar] (8) NULL,
[MTADCU] [numeric] (18, 0) NULL,
[MTANBR] [numeric] (18, 0) NULL,
[MTATNB] [numeric] (18, 0) NULL,
[MTATNR] [numeric] (18, 0) NULL,
[MTBANO] [nvarchar] (20) NULL,
[MTBIRT] [numeric] (18, 0) NULL,
[MTBRE2] [nvarchar] (20) NULL,
[MTBREF] [nvarchar] (20) NULL,
[MTCAMU] [nvarchar] (20) NULL,
[MTCANB] [numeric] (18, 0) NULL,
[MTCAWE] [numeric] (18, 0) NULL,
[MTCDTP] [numeric] (18, 0) NULL,
[MTCFGL] [nchar] (15) NULL,
[MTCNDA] [numeric] (18, 0) NULL,
[MTCONO] [numeric] (18, 0) NOT NULL,
[MTCSQT] [numeric] (18, 0) NULL,
[MTCWTQ] [numeric] (18, 0) NULL,
[MTCWTT] [numeric] (18, 0) NULL,
[MTDEID] [numeric] (18, 0) NULL,
[MTECVE] [nchar] (4) NULL,
[MTELNO] [nchar] (8) NULL,
[MTFIAS] [numeric] (18, 0) NULL,
[MTHACP] [numeric] (18, 0) NULL,
[MTHACS] [numeric] (18, 0) NULL,
[MTINDI] [numeric] (18, 0) NULL,
[MTINER] [numeric] (18, 0) NULL,
[MTITNO] [nchar] (15) NOT NULL,
[MTLMTS] [numeric] (18, 0) NULL,
[MTLOCH] [numeric] (18, 0) NULL,
[MTMFCO] [numeric] (18, 0) NULL,
[MTNHAI] [nchar] (15) NULL,
[MTNHSN] [nvarchar] (20) NULL,
[MTNSTQ] [numeric] (18, 0) NULL,
[MTNSTT] [numeric] (18, 0) NULL,
[MTOPAN] [nvarchar] (20) NULL,
[MTPANR] [nvarchar] (20) NULL,
[MTPLSX] [numeric] (18, 0) NULL,
[MTPRMF] [numeric] (18, 0) NULL,
[MTPROJ] [nchar] (7) NULL,
[MTREPN] [numeric] (18, 0) NULL,
[MTRESP] [nchar] (10) NULL,
[MTRFTX] [nvarchar] (40) NULL,
[MTRGDT] [numeric] (18, 0) NOT NULL,
[MTRGTM] [numeric] (18, 0) NOT NULL,
[MTRIDI] [numeric] (18, 0) NULL,
[MTRIDL] [numeric] (18, 0) NULL,
[MTRIDN] [nchar] (10) NULL,
[MTRIDO] [numeric] (18, 0) NULL,
[MTRIDX] [numeric] (18, 0) NULL,
[MTRORC] [numeric] (18, 0) NULL,
[MTRORL] [numeric] (18, 0) NULL,
[MTRORN] [nchar] (10) NULL,
[MTRORX] [numeric] (18, 0) NULL,
[MTRPRT] [numeric] (18, 0) NULL,
[MTRSCD] [nchar] (3) NULL,
[MTSCNB] [nchar] (10) NULL,
[MTSLTP] [nchar] (2) NULL,
[MTSTAS] [nchar] (1) NULL,
[MTSTCD] [numeric] (18, 0) NULL,
[MTSTNO] [numeric] (18, 0) NULL,
[MTSUDO] [nvarchar] (20) NULL,
[MTTMSX] [numeric] (18, 0) NOT NULL,
[MTTRDT] [numeric] (18, 0) NULL,
[MTTRPR] [numeric] (18, 0) NULL,
[MTTRQA] [numeric] (18, 0) NULL,
[MTTRQT] [numeric] (18, 0) NULL,
[MTTRTM] [numeric] (18, 0) NULL,
[MTTRTP] [nchar] (3) NULL,
[MTTTID] [nchar] (3) NULL,
[MTTTYP] [numeric] (18, 0) NULL,
[MTTUPC] [numeric] (18, 0) NULL,
[MTUPIS] [numeric] (18, 0) NULL,
[MTWHLO] [nchar] (3) NOT NULL,
[MTWHSL] [nchar] (10) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10ved_POL_MITTRA] on [psa].[ics_stg_M3V10ved_POL_MITTRA]'
GO
ALTER TABLE [psa].[ics_stg_M3V10ved_POL_MITTRA] ADD CONSTRAINT [PK_psa_ics_stg_M3V10ved_POL_MITTRA] PRIMARY KEY CLUSTERED  ([MTCONO], [MTITNO], [MTRGDT], [MTRGTM], [MTTMSX], [MTWHLO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10vil_POL_CIDADR]'
GO
CREATE TABLE [psa].[ics_stg_M3V10vil_POL_CIDADR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_CIDADR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_CIDADR_IsIncomplete] DEFAULT ('N'),
[SAADID] [nchar] (6) NOT NULL,
[SAADR1] [nvarchar] (36) NULL,
[SAADR2] [nvarchar] (36) NULL,
[SAADR3] [nvarchar] (36) NULL,
[SAADR4] [nvarchar] (36) NULL,
[SAADTE] [numeric] (18, 0) NOT NULL,
[SAADVI] [nchar] (6) NULL,
[SACHID] [nchar] (10) NULL,
[SACHNO] [numeric] (18, 0) NULL,
[SACONO] [numeric] (18, 0) NOT NULL,
[SACSCD] [nchar] (3) NULL,
[SAECAR] [nchar] (2) NULL,
[SAEDES] [nchar] (10) NULL,
[SAGEOC] [numeric] (18, 0) NULL,
[SAGEOX] [numeric] (18, 0) NULL,
[SAGEOY] [numeric] (18, 0) NULL,
[SAGEOZ] [numeric] (18, 0) NULL,
[SALMDT] [numeric] (18, 0) NULL,
[SALMTS] [numeric] (18, 0) NULL,
[SAPNOD] [nchar] (15) NULL,
[SAPONO] [nchar] (10) NULL,
[SAPRIA] [numeric] (18, 0) NULL,
[SARGDT] [numeric] (18, 0) NULL,
[SARGTM] [numeric] (18, 0) NULL,
[SASTDT] [numeric] (18, 0) NOT NULL,
[SASUNM] [nvarchar] (36) NULL,
[SASUNO] [nchar] (10) NOT NULL,
[SATAXC] [nchar] (3) NULL,
[SATOWN] [nvarchar] (20) NULL,
[SATXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10vil_POL_CIDADR] on [psa].[ics_stg_M3V10vil_POL_CIDADR]'
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_CIDADR] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_CIDADR] PRIMARY KEY CLUSTERED  ([SAADID], [SAADTE], [SACONO], [SASTDT], [SASUNO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10vil_POL_CMNCMP]'
GO
CREATE TABLE [psa].[ics_stg_M3V10vil_POL_CMNCMP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_CMNCMP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_CMNCMP_IsIncomplete] DEFAULT ('N'),
[JICCRT] [numeric] (18, 0) NULL,
[JICCUC] [nchar] (3) NULL,
[JICHID] [nchar] (10) NULL,
[JICHNO] [numeric] (18, 0) NULL,
[JICMTP] [numeric] (18, 0) NULL,
[JICONO] [numeric] (18, 0) NOT NULL,
[JIDBAS] [nchar] (10) NULL,
[JIDCFM] [nchar] (1) NULL,
[JIDFMN] [nchar] (10) NULL,
[JILL01] [nchar] (10) NULL,
[JILL02] [nchar] (10) NULL,
[JILL03] [nchar] (10) NULL,
[JILL04] [nchar] (10) NULL,
[JILL05] [nchar] (10) NULL,
[JILL06] [nchar] (10) NULL,
[JILL07] [nchar] (10) NULL,
[JILL08] [nchar] (10) NULL,
[JILL09] [nchar] (10) NULL,
[JILL10] [nchar] (10) NULL,
[JILMDT] [numeric] (18, 0) NULL,
[JIMNMN] [numeric] (18, 0) NULL,
[JIMNVR] [nchar] (10) NULL,
[JIMXV1] [nchar] (3) NULL,
[JIRGDT] [numeric] (18, 0) NULL,
[JIRGTM] [numeric] (18, 0) NULL,
[JISTMN] [nchar] (15) NULL,
[JITX40] [nvarchar] (40) NULL,
[JITXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10vil_POL_CMNCMP] on [psa].[ics_stg_M3V10vil_POL_CMNCMP]'
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_CMNCMP] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_CMNCMP] PRIMARY KEY CLUSTERED  ([JICONO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10vil_POL_CMNDIV]'
GO
CREATE TABLE [psa].[ics_stg_M3V10vil_POL_CMNDIV]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_CMNDIV_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10vil_POL_CMNDIV_IsIncomplete] DEFAULT ('N'),
[CCACGR] [nchar] (10) NULL,
[CCCCD0] [nchar] (1) NULL,
[CCCCD1] [nchar] (10) NULL,
[CCCCD2] [numeric] (18, 0) NULL,
[CCCCD3] [nchar] (3) NULL,
[CCCCD4] [nchar] (5) NULL,
[CCCCD5] [nchar] (1) NULL,
[CCCCD6] [nchar] (10) NULL,
[CCCCD7] [numeric] (18, 0) NULL,
[CCCCD8] [nchar] (3) NULL,
[CCCCD9] [nchar] (5) NULL,
[CCCDCD] [numeric] (18, 0) NULL,
[CCCHID] [nchar] (10) NULL,
[CCCHNO] [numeric] (18, 0) NULL,
[CCCOA1] [nvarchar] (36) NULL,
[CCCOA2] [nvarchar] (36) NULL,
[CCCOA3] [nvarchar] (36) NULL,
[CCCOA4] [nvarchar] (36) NULL,
[CCCONL] [numeric] (18, 0) NULL,
[CCCONM] [nvarchar] (36) NULL,
[CCCONO] [numeric] (18, 0) NOT NULL,
[CCCSCD] [nchar] (3) NULL,
[CCDCFM] [nchar] (1) NULL,
[CCDIVI] [nchar] (3) NOT NULL,
[CCDMCU] [numeric] (18, 0) NULL,
[CCDTFM] [nchar] (3) NULL,
[CCECAR] [nchar] (2) NULL,
[CCFACI] [nchar] (3) NULL,
[CCFIRM] [nchar] (7) NULL,
[CCGEOC] [numeric] (18, 0) NULL,
[CCHCMA] [numeric] (18, 0) NULL,
[CCISTA] [numeric] (18, 0) NULL,
[CCLL01] [nchar] (10) NULL,
[CCLL02] [nchar] (10) NULL,
[CCLL03] [nchar] (10) NULL,
[CCLL04] [nchar] (10) NULL,
[CCLL05] [nchar] (10) NULL,
[CCLL06] [nchar] (10) NULL,
[CCLL07] [nchar] (10) NULL,
[CCLL08] [nchar] (10) NULL,
[CCLL09] [nchar] (10) NULL,
[CCLL10] [nchar] (10) NULL,
[CCLLID] [nchar] (10) NULL,
[CCLMDT] [numeric] (18, 0) NULL,
[CCLOCD] [nchar] (3) NULL,
[CCMXAP] [numeric] (18, 0) NULL,
[CCMXAR] [numeric] (18, 0) NULL,
[CCMXAT] [numeric] (18, 0) NULL,
[CCMXBU] [numeric] (18, 0) NULL,
[CCMXCA] [numeric] (18, 0) NULL,
[CCMXCF] [numeric] (18, 0) NULL,
[CCMXCP] [numeric] (18, 0) NULL,
[CCMXCR] [numeric] (18, 0) NULL,
[CCMXDC] [numeric] (18, 0) NULL,
[CCMXDO] [numeric] (18, 0) NULL,
[CCMXDP] [numeric] (18, 0) NULL,
[CCMXDR] [numeric] (18, 0) NULL,
[CCMXDS] [numeric] (18, 0) NULL,
[CCMXDT] [numeric] (18, 0) NULL,
[CCMXEC] [numeric] (18, 0) NULL,
[CCMXED] [numeric] (18, 0) NULL,
[CCMXEM] [numeric] (18, 0) NULL,
[CCMXEP] [numeric] (18, 0) NULL,
[CCMXET] [numeric] (18, 0) NULL,
[CCMXEV] [numeric] (18, 0) NULL,
[CCMXFA] [numeric] (18, 0) NULL,
[CCMXFC] [numeric] (18, 0) NULL,
[CCMXGL] [numeric] (18, 0) NULL,
[CCMXGM] [numeric] (18, 0) NULL,
[CCMXIC] [numeric] (18, 0) NULL,
[CCMXIP] [numeric] (18, 0) NULL,
[CCMXJO] [numeric] (18, 0) NULL,
[CCMXJQ] [numeric] (18, 0) NULL,
[CCMXLI] [numeric] (18, 0) NULL,
[CCMXLT] [numeric] (18, 0) NULL,
[CCMXMA] [numeric] (18, 0) NULL,
[CCMXMC] [numeric] (18, 0) NULL,
[CCMXMD] [numeric] (18, 0) NULL,
[CCMXMF] [numeric] (18, 0) NULL,
[CCMXMI] [numeric] (18, 0) NULL,
[CCMXMM] [numeric] (18, 0) NULL,
[CCMXMN] [numeric] (18, 0) NULL,
[CCMXMO] [numeric] (18, 0) NULL,
[CCMXMP] [numeric] (18, 0) NULL,
[CCMXMQ] [numeric] (18, 0) NULL,
[CCMXMS] [numeric] (18, 0) NULL,
[CCMXOC] [numeric] (18, 0) NULL,
[CCMXOD] [numeric] (18, 0) NULL,
[CCMXOI] [numeric] (18, 0) NULL,
[CCMXOQ] [numeric] (18, 0) NULL,
[CCMXOS] [numeric] (18, 0) NULL,
[CCMXPA] [numeric] (18, 0) NULL,
[CCMXPC] [numeric] (18, 0) NULL,
[CCMXPD] [numeric] (18, 0) NULL,
[CCMXPM] [numeric] (18, 0) NULL,
[CCMXPO] [numeric] (18, 0) NULL,
[CCMXPP] [numeric] (18, 0) NULL,
[CCMXPQ] [numeric] (18, 0) NULL,
[CCMXPR] [numeric] (18, 0) NULL,
[CCMXPS] [numeric] (18, 0) NULL,
[CCMXQP] [numeric] (18, 0) NULL,
[CCMXRC] [numeric] (18, 0) NULL,
[CCMXRG] [numeric] (18, 0) NULL,
[CCMXRM] [numeric] (18, 0) NULL,
[CCMXRP] [numeric] (18, 0) NULL,
[CCMXRR] [numeric] (18, 0) NULL,
[CCMXRS] [numeric] (18, 0) NULL,
[CCMXSA] [numeric] (18, 0) NULL,
[CCMXSB] [numeric] (18, 0) NULL,
[CCMXSE] [numeric] (18, 0) NULL,
[CCMXSO] [numeric] (18, 0) NULL,
[CCMXSP] [numeric] (18, 0) NULL,
[CCMXST] [numeric] (18, 0) NULL,
[CCMXTA] [numeric] (18, 0) NULL,
[CCMXTE] [numeric] (18, 0) NULL,
[CCMXTM] [numeric] (18, 0) NULL,
[CCMXTP] [numeric] (18, 0) NULL,
[CCMXV1] [nchar] (3) NULL,
[CCMXV2] [nchar] (3) NULL,
[CCMXWO] [numeric] (18, 0) NULL,
[CCMXWP] [numeric] (18, 0) NULL,
[CCMXWT] [numeric] (18, 0) NULL,
[CCNPT1] [numeric] (18, 0) NULL,
[CCNPT2] [numeric] (18, 0) NULL,
[CCNPT3] [numeric] (18, 0) NULL,
[CCNPT4] [numeric] (18, 0) NULL,
[CCNPT5] [numeric] (18, 0) NULL,
[CCOREF] [nvarchar] (30) NULL,
[CCPHN2] [nchar] (16) NULL,
[CCPHNO] [nchar] (16) NULL,
[CCPONO] [nchar] (10) NULL,
[CCPSND] [nchar] (1) NULL,
[CCPTEI] [numeric] (18, 0) NULL,
[CCPTFA] [numeric] (18, 0) NULL,
[CCPTMP] [numeric] (18, 0) NULL,
[CCPTOI] [numeric] (18, 0) NULL,
[CCPTPA] [numeric] (18, 0) NULL,
[CCRAEM] [numeric] (18, 0) NULL,
[CCRGDT] [numeric] (18, 0) NULL,
[CCRGTM] [numeric] (18, 0) NULL,
[CCROW2] [nvarchar] (17) NULL,
[CCROW3] [nvarchar] (78) NULL,
[CCRROF] [nchar] (2) NULL,
[CCSYRE] [numeric] (18, 0) NULL,
[CCTATM] [numeric] (18, 0) NULL,
[CCTFNO] [nchar] (16) NULL,
[CCTIZO] [nchar] (5) NULL,
[CCTLNO] [nchar] (16) NULL,
[CCTOWN] [nvarchar] (20) NULL,
[CCTX15] [nchar] (15) NULL,
[CCTXID] [numeric] (18, 0) NULL,
[CCUNST] [nchar] (3) NULL,
[CCVDME] [numeric] (18, 0) NULL,
[CCVRNL] [nchar] (16) NULL,
[CCVRNO] [nchar] (16) NULL,
[CCWHLO] [nchar] (3) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10vil_POL_CMNDIV] on [psa].[ics_stg_M3V10vil_POL_CMNDIV]'
GO
ALTER TABLE [psa].[ics_stg_M3V10vil_POL_CMNDIV] ADD CONSTRAINT [PK_psa_ics_stg_M3V10vil_POL_CMNDIV] PRIMARY KEY CLUSTERED  ([CCCONO], [CCDIVI])
GO
PRINT N'Creating [psa].[ics_stg_M3V10ved_POL_CIDADR]'
GO
CREATE TABLE [psa].[ics_stg_M3V10ved_POL_CIDADR]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_CIDADR_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_CIDADR_IsIncomplete] DEFAULT ('N'),
[SAADID] [nchar] (6) NOT NULL,
[SAADR1] [nvarchar] (36) NULL,
[SAADR2] [nvarchar] (36) NULL,
[SAADR3] [nvarchar] (36) NULL,
[SAADR4] [nvarchar] (36) NULL,
[SAADTE] [numeric] (18, 0) NOT NULL,
[SAADVI] [nchar] (6) NULL,
[SACHID] [nchar] (10) NULL,
[SACHNO] [numeric] (18, 0) NULL,
[SACONO] [numeric] (18, 0) NOT NULL,
[SACSCD] [nchar] (3) NULL,
[SAECAR] [nchar] (2) NULL,
[SAEDES] [nchar] (10) NULL,
[SAGEOC] [numeric] (18, 0) NULL,
[SAGEOX] [numeric] (18, 0) NULL,
[SAGEOY] [numeric] (18, 0) NULL,
[SAGEOZ] [numeric] (18, 0) NULL,
[SALMDT] [numeric] (18, 0) NULL,
[SALMTS] [numeric] (18, 0) NULL,
[SAPNOD] [nchar] (15) NULL,
[SAPONO] [nchar] (10) NULL,
[SAPRIA] [numeric] (18, 0) NULL,
[SARGDT] [numeric] (18, 0) NULL,
[SARGTM] [numeric] (18, 0) NULL,
[SASTDT] [numeric] (18, 0) NOT NULL,
[SASUNM] [nvarchar] (36) NULL,
[SASUNO] [nchar] (10) NOT NULL,
[SATAXC] [nchar] (3) NULL,
[SATOWN] [nvarchar] (20) NULL,
[SATXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10ved_POL_CIDADR] on [psa].[ics_stg_M3V10ved_POL_CIDADR]'
GO
ALTER TABLE [psa].[ics_stg_M3V10ved_POL_CIDADR] ADD CONSTRAINT [PK_psa_ics_stg_M3V10ved_POL_CIDADR] PRIMARY KEY CLUSTERED  ([SAADID], [SAADTE], [SACONO], [SASTDT], [SASUNO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10ved_POL_CMNCMP]'
GO
CREATE TABLE [psa].[ics_stg_M3V10ved_POL_CMNCMP]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_CMNCMP_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_CMNCMP_IsIncomplete] DEFAULT ('N'),
[JICCRT] [numeric] (18, 0) NULL,
[JICCUC] [nchar] (3) NULL,
[JICHID] [nchar] (10) NULL,
[JICHNO] [numeric] (18, 0) NULL,
[JICMTP] [numeric] (18, 0) NULL,
[JICONO] [numeric] (18, 0) NOT NULL,
[JIDBAS] [nchar] (10) NULL,
[JIDCFM] [nchar] (1) NULL,
[JIDFMN] [nchar] (10) NULL,
[JILL01] [nchar] (10) NULL,
[JILL02] [nchar] (10) NULL,
[JILL03] [nchar] (10) NULL,
[JILL04] [nchar] (10) NULL,
[JILL05] [nchar] (10) NULL,
[JILL06] [nchar] (10) NULL,
[JILL07] [nchar] (10) NULL,
[JILL08] [nchar] (10) NULL,
[JILL09] [nchar] (10) NULL,
[JILL10] [nchar] (10) NULL,
[JILMDT] [numeric] (18, 0) NULL,
[JIMNMN] [numeric] (18, 0) NULL,
[JIMNVR] [nchar] (10) NULL,
[JIMXV1] [nchar] (3) NULL,
[JIRGDT] [numeric] (18, 0) NULL,
[JIRGTM] [numeric] (18, 0) NULL,
[JISTMN] [nchar] (15) NULL,
[JITX40] [nvarchar] (40) NULL,
[JITXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10ved_POL_CMNCMP] on [psa].[ics_stg_M3V10ved_POL_CMNCMP]'
GO
ALTER TABLE [psa].[ics_stg_M3V10ved_POL_CMNCMP] ADD CONSTRAINT [PK_psa_ics_stg_M3V10ved_POL_CMNCMP] PRIMARY KEY CLUSTERED  ([JICONO])
GO
PRINT N'Creating [psa].[ics_stg_M3V10ved_POL_CMNDIV]'
GO
CREATE TABLE [psa].[ics_stg_M3V10ved_POL_CMNDIV]
(
[EtlRecordId] [bigint] NOT NULL IDENTITY(1, 1),
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[EtlUpdatedOn] [datetime] NOT NULL,
[EtlUpdatedBy] [varchar] (200) NOT NULL,
[EtlDeletedOn] [datetime] NULL,
[EtlDeletedBy] [varchar] (200) NULL,
[IsDeleted] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_CMNDIV_IsDeleted] DEFAULT ('N'),
[IsIncomplete] [char] (1) NOT NULL CONSTRAINT [DF_psa_ics_stg_M3V10ved_POL_CMNDIV_IsIncomplete] DEFAULT ('N'),
[CCACGR] [nchar] (10) NULL,
[CCCCD0] [nchar] (1) NULL,
[CCCCD1] [nchar] (10) NULL,
[CCCCD2] [numeric] (18, 0) NULL,
[CCCCD3] [nchar] (3) NULL,
[CCCCD4] [nchar] (5) NULL,
[CCCCD5] [nchar] (1) NULL,
[CCCCD6] [nchar] (10) NULL,
[CCCCD7] [numeric] (18, 0) NULL,
[CCCCD8] [nchar] (3) NULL,
[CCCCD9] [nchar] (5) NULL,
[CCCDCD] [numeric] (18, 0) NULL,
[CCCHID] [nchar] (10) NULL,
[CCCHNO] [numeric] (18, 0) NULL,
[CCCOA1] [nvarchar] (36) NULL,
[CCCOA2] [nvarchar] (36) NULL,
[CCCOA3] [nvarchar] (36) NULL,
[CCCOA4] [nvarchar] (36) NULL,
[CCCONL] [numeric] (18, 0) NULL,
[CCCONM] [nvarchar] (36) NULL,
[CCCONO] [numeric] (18, 0) NOT NULL,
[CCCSCD] [nchar] (3) NULL,
[CCDCFM] [nchar] (1) NULL,
[CCDIVI] [nchar] (3) NOT NULL,
[CCDMCU] [numeric] (18, 0) NULL,
[CCDTFM] [nchar] (3) NULL,
[CCECAR] [nchar] (2) NULL,
[CCFACI] [nchar] (3) NULL,
[CCFIRM] [nchar] (7) NULL,
[CCGEOC] [numeric] (18, 0) NULL,
[CCHCMA] [numeric] (18, 0) NULL,
[CCISTA] [numeric] (18, 0) NULL,
[CCLL01] [nchar] (10) NULL,
[CCLL02] [nchar] (10) NULL,
[CCLL03] [nchar] (10) NULL,
[CCLL04] [nchar] (10) NULL,
[CCLL05] [nchar] (10) NULL,
[CCLL06] [nchar] (10) NULL,
[CCLL07] [nchar] (10) NULL,
[CCLL08] [nchar] (10) NULL,
[CCLL09] [nchar] (10) NULL,
[CCLL10] [nchar] (10) NULL,
[CCLLID] [nchar] (10) NULL,
[CCLMDT] [numeric] (18, 0) NULL,
[CCLOCD] [nchar] (3) NULL,
[CCMXAP] [numeric] (18, 0) NULL,
[CCMXAR] [numeric] (18, 0) NULL,
[CCMXAT] [numeric] (18, 0) NULL,
[CCMXBU] [numeric] (18, 0) NULL,
[CCMXCA] [numeric] (18, 0) NULL,
[CCMXCF] [numeric] (18, 0) NULL,
[CCMXCP] [numeric] (18, 0) NULL,
[CCMXCR] [numeric] (18, 0) NULL,
[CCMXDC] [numeric] (18, 0) NULL,
[CCMXDO] [numeric] (18, 0) NULL,
[CCMXDP] [numeric] (18, 0) NULL,
[CCMXDR] [numeric] (18, 0) NULL,
[CCMXDS] [numeric] (18, 0) NULL,
[CCMXDT] [numeric] (18, 0) NULL,
[CCMXEC] [numeric] (18, 0) NULL,
[CCMXED] [numeric] (18, 0) NULL,
[CCMXEM] [numeric] (18, 0) NULL,
[CCMXEP] [numeric] (18, 0) NULL,
[CCMXET] [numeric] (18, 0) NULL,
[CCMXEV] [numeric] (18, 0) NULL,
[CCMXFA] [numeric] (18, 0) NULL,
[CCMXFC] [numeric] (18, 0) NULL,
[CCMXGL] [numeric] (18, 0) NULL,
[CCMXGM] [numeric] (18, 0) NULL,
[CCMXIC] [numeric] (18, 0) NULL,
[CCMXIP] [numeric] (18, 0) NULL,
[CCMXJO] [numeric] (18, 0) NULL,
[CCMXJQ] [numeric] (18, 0) NULL,
[CCMXLI] [numeric] (18, 0) NULL,
[CCMXLT] [numeric] (18, 0) NULL,
[CCMXMA] [numeric] (18, 0) NULL,
[CCMXMC] [numeric] (18, 0) NULL,
[CCMXMD] [numeric] (18, 0) NULL,
[CCMXMF] [numeric] (18, 0) NULL,
[CCMXMI] [numeric] (18, 0) NULL,
[CCMXMM] [numeric] (18, 0) NULL,
[CCMXMN] [numeric] (18, 0) NULL,
[CCMXMO] [numeric] (18, 0) NULL,
[CCMXMP] [numeric] (18, 0) NULL,
[CCMXMQ] [numeric] (18, 0) NULL,
[CCMXMS] [numeric] (18, 0) NULL,
[CCMXOC] [numeric] (18, 0) NULL,
[CCMXOD] [numeric] (18, 0) NULL,
[CCMXOI] [numeric] (18, 0) NULL,
[CCMXOQ] [numeric] (18, 0) NULL,
[CCMXOS] [numeric] (18, 0) NULL,
[CCMXPA] [numeric] (18, 0) NULL,
[CCMXPC] [numeric] (18, 0) NULL,
[CCMXPD] [numeric] (18, 0) NULL,
[CCMXPM] [numeric] (18, 0) NULL,
[CCMXPO] [numeric] (18, 0) NULL,
[CCMXPP] [numeric] (18, 0) NULL,
[CCMXPQ] [numeric] (18, 0) NULL,
[CCMXPR] [numeric] (18, 0) NULL,
[CCMXPS] [numeric] (18, 0) NULL,
[CCMXQP] [numeric] (18, 0) NULL,
[CCMXRC] [numeric] (18, 0) NULL,
[CCMXRG] [numeric] (18, 0) NULL,
[CCMXRM] [numeric] (18, 0) NULL,
[CCMXRP] [numeric] (18, 0) NULL,
[CCMXRR] [numeric] (18, 0) NULL,
[CCMXRS] [numeric] (18, 0) NULL,
[CCMXSA] [numeric] (18, 0) NULL,
[CCMXSB] [numeric] (18, 0) NULL,
[CCMXSE] [numeric] (18, 0) NULL,
[CCMXSO] [numeric] (18, 0) NULL,
[CCMXSP] [numeric] (18, 0) NULL,
[CCMXST] [numeric] (18, 0) NULL,
[CCMXTA] [numeric] (18, 0) NULL,
[CCMXTE] [numeric] (18, 0) NULL,
[CCMXTM] [numeric] (18, 0) NULL,
[CCMXTP] [numeric] (18, 0) NULL,
[CCMXV1] [nchar] (3) NULL,
[CCMXV2] [nchar] (3) NULL,
[CCMXWO] [numeric] (18, 0) NULL,
[CCMXWP] [numeric] (18, 0) NULL,
[CCMXWT] [numeric] (18, 0) NULL,
[CCNPT1] [numeric] (18, 0) NULL,
[CCNPT2] [numeric] (18, 0) NULL,
[CCNPT3] [numeric] (18, 0) NULL,
[CCNPT4] [numeric] (18, 0) NULL,
[CCNPT5] [numeric] (18, 0) NULL,
[CCOREF] [nvarchar] (30) NULL,
[CCPHN2] [nchar] (16) NULL,
[CCPHNO] [nchar] (16) NULL,
[CCPONO] [nchar] (10) NULL,
[CCPSND] [nchar] (1) NULL,
[CCPTEI] [numeric] (18, 0) NULL,
[CCPTFA] [numeric] (18, 0) NULL,
[CCPTMP] [numeric] (18, 0) NULL,
[CCPTOI] [numeric] (18, 0) NULL,
[CCPTPA] [numeric] (18, 0) NULL,
[CCRAEM] [numeric] (18, 0) NULL,
[CCRGDT] [numeric] (18, 0) NULL,
[CCRGTM] [numeric] (18, 0) NULL,
[CCROW2] [nvarchar] (17) NULL,
[CCROW3] [nvarchar] (78) NULL,
[CCRROF] [nchar] (2) NULL,
[CCSYRE] [numeric] (18, 0) NULL,
[CCTATM] [numeric] (18, 0) NULL,
[CCTFNO] [nchar] (16) NULL,
[CCTIZO] [nchar] (5) NULL,
[CCTLNO] [nchar] (16) NULL,
[CCTOWN] [nvarchar] (20) NULL,
[CCTX15] [nchar] (15) NULL,
[CCTXID] [numeric] (18, 0) NULL,
[CCUNST] [nchar] (3) NULL,
[CCVDME] [numeric] (18, 0) NULL,
[CCVRNL] [nchar] (16) NULL,
[CCVRNO] [nchar] (16) NULL,
[CCWHLO] [nchar] (3) NULL
)
GO
PRINT N'Creating primary key [PK_psa_ics_stg_M3V10ved_POL_CMNDIV] on [psa].[ics_stg_M3V10ved_POL_CMNDIV]'
GO
ALTER TABLE [psa].[ics_stg_M3V10ved_POL_CMNDIV] ADD CONSTRAINT [PK_psa_ics_stg_M3V10ved_POL_CMNDIV] PRIMARY KEY CLUSTERED  ([CCCONO], [CCDIVI])
GO
PRINT N'Creating [tsa].[ics_land_M3V10ved_POL_CIDADR]'
GO
CREATE TABLE [tsa].[ics_land_M3V10ved_POL_CIDADR]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_CIDADR_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_CIDADR_IsDuplicate] DEFAULT ((0)),
[SAADID] [nchar] (6) NULL,
[SAADR1] [nvarchar] (36) NULL,
[SAADR2] [nvarchar] (36) NULL,
[SAADR3] [nvarchar] (36) NULL,
[SAADR4] [nvarchar] (36) NULL,
[SAADTE] [numeric] (18, 0) NULL,
[SAADVI] [nchar] (6) NULL,
[SACHID] [nchar] (10) NULL,
[SACHNO] [numeric] (18, 0) NULL,
[SACONO] [numeric] (18, 0) NULL,
[SACSCD] [nchar] (3) NULL,
[SAECAR] [nchar] (2) NULL,
[SAEDES] [nchar] (10) NULL,
[SAGEOC] [numeric] (18, 0) NULL,
[SAGEOX] [numeric] (18, 0) NULL,
[SAGEOY] [numeric] (18, 0) NULL,
[SAGEOZ] [numeric] (18, 0) NULL,
[SALMDT] [numeric] (18, 0) NULL,
[SALMTS] [numeric] (18, 0) NULL,
[SAPNOD] [nchar] (15) NULL,
[SAPONO] [nchar] (10) NULL,
[SAPRIA] [numeric] (18, 0) NULL,
[SARGDT] [numeric] (18, 0) NULL,
[SARGTM] [numeric] (18, 0) NULL,
[SASTDT] [numeric] (18, 0) NULL,
[SASUNM] [nvarchar] (36) NULL,
[SASUNO] [nchar] (10) NULL,
[SATAXC] [nchar] (3) NULL,
[SATOWN] [nvarchar] (20) NULL,
[SATXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10ved_POL_CIDADR_1] on [tsa].[ics_land_M3V10ved_POL_CIDADR]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10ved_POL_CIDADR_1] ON [tsa].[ics_land_M3V10ved_POL_CIDADR] ([SAADID], [SAADTE], [SACONO], [SASTDT], [SASUNO])
GO
PRINT N'Creating [tsa].[ics_land_M3V10ved_POL_CMNCMP]'
GO
CREATE TABLE [tsa].[ics_land_M3V10ved_POL_CMNCMP]
(
[EtlBatchRunId] [int] NOT NULL,
[EtlStepRunId] [int] NOT NULL,
[EtlThreadRunId] [int] NOT NULL,
[DataSourceKey] [int] NOT NULL,
[EtlSourceTable] [varchar] (200) NOT NULL,
[EtlCreatedOn] [datetime] NOT NULL,
[EtlCreatedBy] [varchar] (200) NOT NULL,
[ExcludeFromMerge] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_CMNCMP_ExcludeFromMerge] DEFAULT ((0)),
[IsDuplicate] [bit] NOT NULL CONSTRAINT [DF_tsa_ics_land_M3V10ved_POL_CMNCMP_IsDuplicate] DEFAULT ((0)),
[JICCRT] [numeric] (18, 0) NULL,
[JICCUC] [nchar] (3) NULL,
[JICHID] [nchar] (10) NULL,
[JICHNO] [numeric] (18, 0) NULL,
[JICMTP] [numeric] (18, 0) NULL,
[JICONO] [numeric] (18, 0) NULL,
[JIDBAS] [nchar] (10) NULL,
[JIDCFM] [nchar] (1) NULL,
[JIDFMN] [nchar] (10) NULL,
[JILL01] [nchar] (10) NULL,
[JILL02] [nchar] (10) NULL,
[JILL03] [nchar] (10) NULL,
[JILL04] [nchar] (10) NULL,
[JILL05] [nchar] (10) NULL,
[JILL06] [nchar] (10) NULL,
[JILL07] [nchar] (10) NULL,
[JILL08] [nchar] (10) NULL,
[JILL09] [nchar] (10) NULL,
[JILL10] [nchar] (10) NULL,
[JILMDT] [numeric] (18, 0) NULL,
[JIMNMN] [numeric] (18, 0) NULL,
[JIMNVR] [nchar] (10) NULL,
[JIMXV1] [nchar] (3) NULL,
[JIRGDT] [numeric] (18, 0) NULL,
[JIRGTM] [numeric] (18, 0) NULL,
[JISTMN] [nchar] (15) NULL,
[JITX40] [nvarchar] (40) NULL,
[JITXID] [numeric] (18, 0) NULL
)
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10ved_POL_CMNCMP_1] on [tsa].[ics_land_M3V10ved_POL_CMNCMP]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10ved_POL_CMNCMP_1] ON [tsa].[ics_land_M3V10ved_POL_CMNCMP] ([JICONO])
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10gen_POL_CIDADR_1] on [tsa].[ics_land_M3V10gen_POL_CIDADR]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_CIDADR_1] ON [tsa].[ics_land_M3V10gen_POL_CIDADR] ([SAADID], [SAADTE], [SACONO], [SASTDT], [SASUNO])
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10gen_POL_CMNCMP_1] on [tsa].[ics_land_M3V10gen_POL_CMNCMP]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_CMNCMP_1] ON [tsa].[ics_land_M3V10gen_POL_CMNCMP] ([JICONO])
GO
PRINT N'Creating index [IndClust_tsa_ics_land_M3V10gen_POL_CMNDIV_1] on [tsa].[ics_land_M3V10gen_POL_CMNDIV]'
GO
CREATE CLUSTERED INDEX [IndClust_tsa_ics_land_M3V10gen_POL_CMNDIV_1] ON [tsa].[ics_land_M3V10gen_POL_CMNDIV] ([CCCONO], [CCDIVI])
GO
